### ISSUE TITLE
Some issues: icon overlap, component not responding, datagrid column width, etc.

### ISSUE THREAD

**Issue by imshivamchauhan** [formio/formio.js#1001]
Some issues of formio.js:
Demo created for issue replication at:
https://github.com/imshivamchauhan/formio-demo

Please find Test Cases.xlsx for issues with steps to replicate also in above git repository.

Read README.md file for steps to run server.(no need to build client again, dist is already there).
Just install node_modules & run node server. Portal will listen at port-5000.

**Comment by travist** [comment]
Thanks. We will take a look.
