### ISSUE TITLE
Problem Calculated Value with JSONLogic

### ISSUE THREAD

**Issue by bigjorjao** [formio/formio.js#1006]
i have a data grid (meiosLogisticosNecessarios) where i define de cost of material.
And i like in other element sum(total) of cost of material.
In the data > Calculated Value i use JSONLogic:
{
  "reduce": [ { "var": "row.meiosLogisticosNecessarios" },
    { "+": [ { "var": "current.custo" },
               { "var": "accumulator"  }]},
    0
  ]
}

Values: {"row.meiosLogisticosNecessarios":[0.1,0.7]}
But Output: 0.7999999999999999
why? should not give 0.8? Is there any expression to round up?

if i have {"row.meiosLogisticosNecessarios":[0.1,0.3]} --> output: 0.4 OK
but if {"row.meiosLogisticosNecessarios":[11.11,22.63]} --> output: 33.739999999999995 ??

**Comment by travist** [comment]
If you want to sum all the data within all the rows of a datagrid, then you should not use "row" (since that only refers to the contextual row), but rather data. Try this.

```
{
"reduce": [ { "var": "data.meiosLogisticosNecessarios" },
{ "+": [ { "var": "current.custo" },
{ "var": "accumulator" }]},
0
]
}
```

**Comment by bigjorjao** [comment]
If I use data my sum not work. see my example..

![imagem](https://user-images.githubusercontent.com/46224388/52425327-aaa6fa00-2af3-11e9-9393-4ec56ea512da.png)

**Comment by bigjorjao** [comment]
I resolve my problem with round. Example:

```
{
  "_round": [
    {
      "reduce": [
        {
          "var": "row.meiosLogisticosNecessarios"
        },
        {
          "+": [
            {
              "+": {
                "var": "current.custo"
              }
            },
            {
              "var": "accumulator"
            }
          ]
        },
        0
      ]
    },
    2
  ]
}
```
