### ISSUE TITLE
Format issue with DateTime component

### ISSUE THREAD

**Issue by chenyil** [formio/formio.js#1008]
1. The format does not apply to submission data, it only applies to the displayed value. The template literals doesn't work either.
2. Event I set  "displayInTimezone": "utc", the value is still my local time.

My goal is to have the value in this ISO format (UTC time). Is there something wrong with my setup? Thank you for taking the time looking into the issue.

This is my schema.
 
{
    "display": "form",
    "components": [
        {
            "label": "Date / Time",
            "displayInTimezone": "utc",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "datetime",
            "input": true,
            "key": "dateTime2",
            "suffix": true,
            "widget": {
                "type": "calendar",
                "displayInTimezone": "utc",
                "language": "en",
                "useLocaleSettings": false,
                "allowInput": true,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "YYYY-MM-ddTHH:mm:ss.sssZ",
                "defaultDate": "",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": "",
                "maxDate": ""
            },
            "defaultValue": "",
            "datePicker": {
                "minDate": "",
                "maxDate": ""
            },
            "encrypted": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by randallknutson** [comment]
If I understand correctly, the submission data is still in the raw format but is displaying

**Comment by chenyil** [comment]
Hi Randall, thanks for the prompt reply!

If the submission data is stored in the raw format and then formatted during display, then all of my questions are actually expected behaviours... I thought the format applies to saved value too. I was using https://formio.github.io/formio.js/app/builder, but the tooltip of format says "The date format is for saving the value of this field". I probably misunderstood.

Thanks again.

**Comment by vishaldenzil** [comment]
If i want the submission data in other format ... How can i do it ? 
For eg. the date format is 2019-10-09T00:00:00+05:30 .. I need the format in 09-10-2019 ..
How i can achieve using the date//time component  .. Or any other way?

**Comment by wag110894** [comment]
Will you please create a new ticket for this issue as this issue is over 8 months old?

Thanks,
