### ISSUE TITLE
Ability to assign promises to the `value` property

### ISSUE THREAD

**Issue by pmanu93** [formio/formio.js#1009]
Hi,

Will we ever be able to assign a promise to the `value` of a component?

I think that would be a awesome feature because sometimes we just want to use some API which does some request and treats the response turning it into the way we want.

Some examples of how it would be cool to handle these kind of situations:
```js
// assign promise to value, resolve internally and use the response data
value = api.fetchIssues({open: true});
```
```js
// use custom function to handle the promise
instance.setAsyncValue(api.fetchIssues({open: true}));
```
```js
// same as before, but with some handling of the response in between
instance.setAsyncValue(api.fetchIssues({open: true}).then( _res => {
   // handle the data
   let value = {title: _res.name, content: _res.body};
   return Promise.resolve(value);
}));
```

Right now we are doing something similar, which is:

```js
api.fetchIssues({open: true}).then(_res=>{
 instance.setValue(_res);
});
```
That works fine in the `customValue` field .. but if we use the same  in `calculatedValue`, it results in a bunch of: 
![captura de ecra de 2019-02-08 10 28 35](https://user-images.githubusercontent.com/15691766/52472898-674c9a00-2b8c-11e9-935b-8a84d7b83db4.png)
Any way to workaround that?

Probably the *infinite loop* problem is related to the fact that there are some *`change`*  and *`validation`* events involved in the `setValue`  method. Is there an way to disable that?
- - -
Anyway, I think it would be awesome if Formio.js could give us an official way to make that kind of things work.

Thanks,
Pedro Silva

**Comment by randallknutson** [comment]
Hi Pedro,

This is definitely an interesting idea. We've had requests from customers about how to do async requests to set values so this has come up before. It wouldn't be too difficult on our side to check to see if the value is a Promise and if it is, wait for it to resolve. We're going to bring this up at planning and see if it is something we are going to add. In the meantime, if you wanted to look into this it is something we would definitely take a pull request for.

**Comment by suportecaso1** [comment]
Hi guys,
I'm interested in this too. I need to define a select box default value based on data fetched from a API call. It will be nice if the value is always treated as a promise.

Is there any development on this?

Thanks

**Comment by randallknutson** [comment]
Nothing has moved forward on this yet. We'd be happy to have someone drive this forward.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
