### ISSUE TITLE
Translation of Form's informations

### ISSUE THREAD

**Issue by dcoevoet51** [formio/formio.js#1010]
Hello, 

I would like to translate some form's informations like "Drag and Drop a form component" or the different days of the week (I can only translate the months).

Could you please tell me how to do this if it's possible?

Thanks by advance, 

Best regards,

**Comment by travist** [comment]
Most of these can be done with our i18n support. Here are some docs over how that works.

http://formio.github.io/formio.js/app/examples/language.html

Let us know if this is not sufficient for what you need.

**Comment by dcoevoet51** [comment]
Hello, 

I'm using formio.js with react.

I have already read these documents but there is no information for the "Drag and Drop a form component" label and the different days of the week.

Best regards,
