### ISSUE TITLE
Content Component Does Update without Edit and Save

### ISSUE THREAD

**Issue by themattkenney** [formio/formio.js#1013]
The content component will not update the JSON Schema unless you click edit on the component and then save. I would think it would update at least onblur. 

To recreate:
Navigate to http://formio.github.io/formio.js/app/builder > Drag a Content component to form > add content > Notice the JSON Schema does not update

**Comment by travist** [comment]
Yes I agree... it should save the JSON on blur. We will add this to our list, but it does not sound very urgent so if you need this done quickly then you may consider expediting the resolution. Otherwise, feel free to dig into the code and submit a pull request.

**Comment by pradipp287** [comment]
@travist  Any update on this?

**Comment by MohitNaroliya** [comment]
@travist - Any update on this?

**Comment by travist** [comment]
Deemed not urgent on our side, so we would hope this could be a community resolved bug. Of course there is an option to have the Form.io team expedite this issue but there is a fee for this. Contact support @ form.io if you want to go that route.

**Comment by wag110894** [comment]
This issue has been resolved in the latest version of our formio.js. 4.4.2.
