### ISSUE TITLE
Panel Unique Key Values

### ISSUE THREAD

**Issue by 152hq** [formio/formio.js#1019]
Hi,

We are trying to implement a functionality where if a checkbox is checked, the panel should hide and show. The below code is used to get instances of all the rendered components.

`instance.root.editForm.components `

However, the current base code does not assign unique keys to a panel and so the when iterating its really had to distinguish when there exist multiple panels. Is there away to assign unique keys to panels? (same like when multiple text fields are there, it would assign as textfield1, textfield2.....)

Thanks

**Comment by randallknutson** [comment]
Have you tried using the conditional functionality? You shouldn't need to iterate over components to do this.

**Comment by 152hq** [comment]
Yes, we use that. Sorry for the confusion, but what we are aiming is to have like 3-4 panels and get a drop down that can list all the 4 panels and based on user selection, we make some logic around it. So, it is really important to identify which panel the user has selected. Is there a way to solve this?
