### ISSUE TITLE
Formio.js is exported in UMD format

### ISSUE THREAD

**Issue by kva2** [formio/formio.js#1020]
I would like to use formio in a SystemJS setup. As such, an UMD version is required. Is it possible to provide the library in this format? Thx

**Comment by randallknutson** [comment]
I believe our build tools provide a UMD build. Just use the lib files instead of the dist files.

**Comment by kva2** [comment]
In 2.29.9, there is indeed a lib folder, but not in version 3.14.1

folder structure for 2.29.9 
<img width="266" alt="2 29 9" src="https://user-images.githubusercontent.com/47599806/52771130-5fca3c80-3035-11e9-9ffc-bc2fbdef796e.png">

folder structure for 3.14.1 
<img width="324" alt="3 14 1" src="https://user-images.githubusercontent.com/47599806/52771139-65278700-3035-11e9-82e3-233a332dfa95.png">

**Comment by randallknutson** [comment]
We typically publish just the lib folder so you should be able to import "formiojs/Form" to get the Form object.
