### ISSUE TITLE
the columns prop - hideOnChildrenHidden hides the column even if conditional value is true

### ISSUE THREAD

**Issue by ranjitab** [formio/formio.js#1022]
With the following form components, I expect to see the textField1 if checkbox1 is checked, but with hideOnChildrenHidden set to true, the columns never show up

{
            "label": "Checkbox 1",
            "type": "checkbox",
            "input": true,
            "key": "checkbox1"
        },
        {
            "label": "Checkbox 2",
            "type": "checkbox",
            "input": true,
            "key": "checkbox2"
        },
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [
                        {
                            "label": "Text Field 1",
                            "type": "textfield",
                            "input": true,
                            "key": "textField1",
                            **"conditional": {
                                "show": true,
                                "when": "checkbox1",
                                "eq": "true",
                                "json": ""
                            },**
                            "customConditional": ""
                        }
                    ],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "type": "column",
                    "hideOnChildrenHidden": true,
                    "input": true,
                    "key": "",
                    "tableView": true,
                    "label": ""
                },
                {
                    "components": [
                        {
                            "label": "Text Field 2",
                            "type": "textfield",
                            "input": true,
                            "key": "textField2",
                            "conditional": {
                                "show": true,
                                "when": "checkbox2",
                                "eq": "true",
                                "json": ""
                            },
                            "customConditional": ""
                        }
                    ],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "type": "column",
                    **"hideOnChildrenHidden": true,**
                    "input": true,
                    "key": "",
                    "tableView": true,
                    "label": ""
                }
            ],
            "hideOnChildrenHidden": true,
            "mask": false,
            "tableView": false,
            "alwaysEnabled": false,
            "type": "columns",
            "input": false,
            "key": "columns"
        }

**Comment by ranjitab** [comment]
@travist - hey any update on this issue ?

**Comment by jhen1422** [comment]
@ranjitab can you send over your form embed URL of this form or send of a jsfiddle so we can replicate the issue?

**Comment by ranjitab** [comment]
@jhen1422 - here is the link - http://jsfiddle.net/ranjitab/1r4uzx79/1/#&togetherjs=uf3VQVdQxy

I expected to see the "testName" text box in the first column to show up when "showText field testName" checkbox is checked

**Comment by jhen1422** [comment]
@ranjitab 

I've created a form using the latest version of our formio.js renderer and your use case seems to be working fine on my end. I've included a form embed URL showcasing the test results. Please test this in your environment using the latest version of formio.js to verify 
http://gijyfvdlhtiwfue.form.io/checkboxtest

**Comment by ranjitab** [comment]
@jhen1422 the form you shared, has hideOnChildrenHidden prop set to false, if we set it to true - the columns do not show up even when checkboxTwo/checkboxOne is selected.My question was why hideOnChildrenHidden hides column when children not hidden.

**Comment by jhen1422** [comment]
@ranjitab I'm apologize about the misunderstanding. We do have a setting within the column settings called 'Hide Column when Children Hidden' which sets that attribute to 'true' when checked. https://www.screencast.com/t/nicJ3Yor4Nfl 

Your column must carry this setting which is causing the issue. Please uncheck this setting to resolve the issue.

**Comment by ranjitab** [comment]
@jhen1422 thank you so much for all the quick responses, this is what is happening though - 

steps to reproduce my issue
- use hideOnChildrenHidden, so set hideOnChildrenHidden to true
- select checkboxTwo, unselect checkboxOne

expected behaviour 
- Text Field Two shows up , Text Field One is hidden

actual behaviour 
- both textfields do not show up

I was expecting if there are two columns and the components of first column are hidden then the column itself is also hidden and second column takes up the space of first column.

**Comment by jhen1422** [comment]
@ranjitab Thank you for the clarification. What you're needing is the 'Auto Adjust Columns' setting found within the column settings. Unfortunately it seems that there is an issue with this setting. I've added this issue to our platform backlog.

Thank you again for the report!

**Comment by ranjitab** [comment]
thank you @jhen1422 , is there a github issue for this that I can follow ?

**Comment by jhen1422** [comment]
We typically prioritize our issue list every Monday. I can get back with you next week on where we land with this item. If this item does not get priority over other items, we do offer services to expedite issue fixes at  a cost. If you are interested, please notify support@form.io

**Comment by ranjitab** [comment]
@jhen1422 Any updates on this issue, if it got prioritized ?

**Comment by jhen1422** [comment]
@ranjitab This issue has not yet been prioritized but is on the top our backlog. Unfortunately it's hard to give an accurate ETA at this point.

As mentioned before, feel free to submit a pull request to fix the issue or contact our support team for information on expediting.

Thanks again!

**Comment by dev-thinks** [comment]
This is still an open issue and there is one more related one here, https://github.com/formio/formio.js/issues/1915
