### ISSUE TITLE
Able to create new component if I not fill required property. 

### ISSUE THREAD

**Issue by AvnishVerma** [formio/formio.js#1026]
Hi, 

I able to create component with out filling required fields, if create text box I can create it without filling label.

**Comment by travist** [comment]
I do not understand this issue. Are you saying that you are able to create a new component without providing the Label property?

**Comment by AvnishVerma** [comment]
Yes, 
Create a new component, Remove Label text, now change tab and move to any other tab and press save button.

**Comment by AvnishVerma** [comment]
After fix required error message is missing..

**Comment by jhen1422** [comment]
@AvnishVerma Thank you for the report.

We have added this item to our development backlog

**Comment by jhen1422** [comment]
This issue has been resolved
