### ISSUE TITLE
Unable to add sibling nested panels

### ISSUE THREAD

**Issue by Venators** [formio/formio.js#1027]
Hi all,
There is an issue in formio.js library, wherein one is unable to add sibling nested panel components. 
The desired form layout can be achieved through the form.io portal, as shown below:
![image](https://user-images.githubusercontent.com/20661886/52922103-1b1b0a00-3383-11e9-8de3-c9b2d9320895.png)
You can see that panel B and C are nested and siblings to each other. If you try and create the same layout on either the formio.js demo site or in a downloaded copy of formio.js, you are unable to add a sibling nested panel:
![image](https://user-images.githubusercontent.com/20661886/52922122-6208ff80-3383-11e9-9eb8-a5ad15adde91.png)
Dragging a new panel into the build area presents the edit modal, however upon saving the modal, no panel componant is added to the form. Attempting to work around the issue hasn't worked either, i.e. adding a non-nested panel and then trying to move it to a nested level results in the component being stuck in a moving state, unable to be placed into the form again:
![image](https://user-images.githubusercontent.com/20661886/52922166-d93e9380-3383-11e9-8484-d18611a348ec.png)
There are no errors raised in the console either, nothing to indicate what is going wrong.
Thanks,
David

**Comment by travist** [comment]
Thanks for the report. We will add this to our development backlog.

**Comment by jhen1422** [comment]
@Venators Are you still experiencing this issue? If so, could you provide a form embed URL of the issue ?
