### ISSUE TITLE
Select "searchField" option not triggering request

### ISSUE THREAD

**Issue by coronoz** [formio/formio.js#103]
Hi!

The form is rendered, and the select initial options are rendered, but when url data source and searchField are set, no request is triggered when i type in the select seach box. I checked my endpoint in data.url and is returning a valid json, but no new request is triggered after the initial one that populate the select.

Is there an error with my select component config?

I have followed the documentation that is show in [https://help.form.io/userguide/form-components/#search-query-name](https://help.form.io/userguide/form-components/#search-query-name)

Here is an example of how i'm loading the form.

```
$(document).ready(function(){
    var form = new FormioForm(document.getElementById('formio'));
    form.form = {
        components: [
            {
                input: true,
                tableView: true,
                placeholder: "Opción",
                data: {
                    url: "http://page.com/formio/api/options/58"
                },
                dataSrc: "url",
                valueProperty: "value",
                template: "{{ item.text }}",
                type: "select",
                searchField: "query"
            }
        ]
    };
});
```

**Comment by coronoz** [comment]
@travist i wonder if this is going  to be reviewed and patched in a future release? I think  this could be a bug, i have followed the documentation but the setup is not functioning as is required.

**Comment by travist** [comment]
This will be fixed in next release. Coming soon.

**Comment by travist** [comment]
Fixed with 2.17.6

**Comment by juliousglori** [comment]
Hi guys, how can I remove the search input field inside the select component? 
Coz in my preference i dont need the search input inside it

**Comment by Aiso786** [comment]
Hello @juliousglori you can do it by unselecting the "Enable Static Search" option on the "Data" tab when you are editing the component.

![image](https://user-images.githubusercontent.com/22521614/45213922-3d1f4500-b299-11e8-9963-72b937be4a02.png)


![image](https://user-images.githubusercontent.com/22521614/45213890-2973de80-b299-11e8-9812-0359379bd8ef.png)

**Comment by denisekay** [comment]
Enable static search is only available in the 3.x branch of ngFormio. This switches the form builder from the original ng based form builder to the new javascript only form builder. The new form builder is still in beta.
