### ISSUE TITLE
In Text Field Component, minimum word length and maximum word length is not working LIke I have created a field and gave any numeric value to the field minimum word length and maximum word length and save form successfully but it does nothing while giving user input to the same field

### ISSUE THREAD

**Issue by alimukarram** [formio/formio.js#1032]
#1001 
Demo created for issue replication at:
https://github.com/imshivamchauhan/formio-demo

Read README.md file for steps to run server.(no need to build client again, dist is already there).
Just install node_modules & run node server. Portal will listen at port-5000.
![formfield](https://user-images.githubusercontent.com/47807190/53091396-dd131700-3537-11e9-8780-475e3f104a02.PNG)

**Comment by travist** [comment]
Thanks. We will add this to our development backlog.

**Comment by jhen1422** [comment]
Hello @alimukarram 
We have tested this issue on our end and the field does throw a validation error when a user submits the form without meeting the min/max word requirement set within the validation tab. Please review the video link of our testing results 
https://www.screencast.com/t/xAqX7kNOAR
