### ISSUE TITLE
Fieldset is movable but as soon as the user saves it and views it again, it moves back to its original position

### ISSUE THREAD

**Issue by alimukarram** [formio/formio.js#1035]
Fieldset is movable but as soon as the user saves it and views it again, it moves back to its original position 

Demo created for issue replication at:
https://github.com/imshivamchauhan/formio-demo

Read README.md file for steps to run server.(no need to build client again, dist is already there).
Just install node_modules & run node server. Portal will listen at port-5000.

![fieldset1](https://user-images.githubusercontent.com/47807190/53146903-e057e280-35cb-11e9-8628-f09aa527f203.PNG)
![afterswapping](https://user-images.githubusercontent.com/47807190/53146902-e057e280-35cb-11e9-9b43-9757f5df48f1.PNG)
![swapfieldset](https://user-images.githubusercontent.com/47807190/53146905-e0f07900-35cb-11e9-97f3-b0a47cdd52a4.PNG)
![submitfrom1](https://user-images.githubusercontent.com/47807190/53146904-e057e280-35cb-11e9-80d3-794ecb40381a.PNG)
Expected output: Field Set 2 should be on top and Field set 1 should display just below Field Set 2

#1001

**Comment by jhen1422** [comment]
Thank you for the report. We will add this item to our platform backlog.

**Comment by JoelAlphonso** [comment]
Any update on when this will be fixed?

Formio is completely unusable without it fixed.

**Comment by wag110894** [comment]
Hello,
This issue is resolved on our 4x Core Renderer. 

Our current timeframe for releasing 4x is end of the second quarter.
We will keep you updated on when this is released.

Thanks.

**Comment by krixerx** [comment]
But will be it fixed in version 3.* too?

**Comment by travist** [comment]
We are not familiar with the commit that actually "fixed" it so it would require some investigation to backport it. I would say this is probably not going to be back-ported unless a company sponsors it. Feel free to dig and submit a pull request.
