### ISSUE TITLE
rendering form with initial data buges

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#1043]
when trying to render form with initial data select component doesn't work currectly
reproduce the bug
1- create two select component with custom data which loads data from a GET web service(using js xhttp request)
2- name them country & province for exp.....
3- make both component disable 
*note that the provinces data depends on country data 
*note that the both component should have valueProperty 
*consider your data like that 
```
[{"name":"USA","value":"US"},...]

```
4- when you pass the initial that to the form the select component doesn't show the name ('USA') it just show the value ('US') (it's only happens to the province component not the country ... i think there is problem with the triggering refreshOn or change or setValue in select component)

**Comment by randallknutson** [comment]
Have you followed this example? It shows how to get something similar working. http://formio.github.io/formio.js/app/examples/external.html
