### ISSUE TITLE
How to create a new component made up of other existing components

### ISSUE THREAD

**Issue by noordawod** [formio/formio.js#1044]
Hi there,
I'm trying to build a new component where I would like to use another other component (not extend it, but use it internally). The new component will extend `BaseComponent`.
Have you got an example on how this should be done?
Thanks.

**Comment by randallknutson** [comment]
We've done something similar to this with some custom components where we needed to wrap multiple components together into a single component. The best way we've found to do this is to basically do something like the nested form where you have a form definition for all of the components and then render the form as the component render. Then for the nested form onChange event, set the value of the component on the main form. This is similar to how the nested form component works but can be cleaned up a bit to make it part of the main form. https://github.com/formio/formio.js/blob/master/src/components/nested/NestedComponent.js

**Comment by noordawod** [comment]
Thanks a lot for the answer, @rahatarmanahmed!

That file is very big and will take me a while to uncover what it does, so I'm wondering if you could point me to a portion of the file where such inclusion take place?

Or if you have few moments of your precious time, even to write an example here.

Very much appreciated, thanks!

**Comment by randallknutson** [comment]
Unfortunately I don't have a good example handy. The key parts as I remember are to instantiate the nested form in the build method, add a listener to the change event of the nested form and set this.dataValue equal to the submission data of the subform.

**Comment by noordawod** [comment]
Thanks! I'll try to replicate for my use case.
