### ISSUE TITLE
Resource Component render error with HTML5 widget

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#1045]
Resource Component does not render correctly when using the HTML5 widget and has `addResource` property enabled.

![](https://i.imgur.com/iY2fomW.png)

Looking at the console it shows the following set of errors:

![](https://i.imgur.com/uIX6YuF.png)

DEMO: [jsFiddle](https://jsfiddle.net/airarrazaval/ugtvzw5b/)

**Comment by wag110894** [comment]
Hello Alfredo,

Thanks for reaching out!

After testing, it appears that the HTML Widget is not compatible with the Resource component.

Please let me know if you have any further questions or concerns.

Thanks.

**Comment by airarrazaval** [comment]
@angelhu Could you please check this? I just send you an email regarding this issue.
