### ISSUE TITLE
Bug: hiding controls when using dataGrid 

### ISSUE THREAD

**Issue by ferasA22** [formio/formio.js#1046]
Hi,
I'm facing a bug when using show conditions for specific control.
You can reproduce it with datagrid example:
http://formio.github.io/formio.js/app/examples/datagrid.html
1- Uncheck all "Dependant" checkboxes.
2- check any "Dependant" checkbox.
3- You'll see that all the birthdate text fields going to be displayed. Even though it's supposed to display only the selected "Dependant".

Thanks,
Feras

**Comment by wag110894** [comment]
Hello Feras,

Thank you for reaching out regarding this issue. 

We are able to replicate this issue and have created a ticket (FOR-2106). We will discuss the level of priority for this item at our next planning meeting.


Thanks.

William Gay

**Comment by wag110894** [comment]
Hello Feras,

After discussion with the team, we have concluded that this a medium priority for us. That being said, we have quoted this item for 3 hours if you wish to have this issue expedited. Please let us know if you are interested and we can sent you a formal quote.

Please let me know if you have any further questions or concerns.

Thanks,
William Gay

**Comment by jhen1422** [comment]
This has been fixed on the 4x branch of our formio.js renderer
