### ISSUE TITLE
BUG: Can't change component disabled after initialization

### ISSUE THREAD

**Issue by brianagriffith** [formio/formio.js#1047]
We have use cases where we need to conditionally enable/disable components based on business logic and we've used custom scripts to set component.disabled at run time. We currently use ngFormio and this works fine there. We've been testing out moving to this library and ran into the following issue.

In Base.js the setter function for component.disabled is calling the shouldDisable function to (I think) prevent disabling a component that should not be disabled.
```
// Do not allow a component to be disabled if it should be always...
if ((!disabled && this.shouldDisable) || (disabled && !this.shouldDisable)) {
  return;
}
```
The shouldDisable function checks the current value of component.disabled as part of the logic to determine whether the component should be disabled.
```
get shouldDisable() {
    return (this.options.readOnly || this.component.disabled) && !this.component.alwaysEnabled;
}
```
This works fine when the component is being initialized because the value of component.disabled is undefined. However, once component.disabled is set, it cannot be changed because shouldDisable will also return the current value of component.disable (assuming the form is not read-only). So, if component.disable is already false, and you try to set component.disabled = true, shouldDisable returns false and the setter function returns without actually updating the value of component.disabled

I'm not sure about the fix. My inclination would be to remove the shouldDisable check from the setter function. In the constructor for Base.js, the shouldDisable function is already being called before attempting to set the value of disable so it seems redundant to call it again in the setter.
```
// Disable if needed.
if (this.shouldDisable) {
  this.disabled = true;
}
```

**Comment by randallknutson** [comment]
There are multiple ways to disable a component such as passing in a list of disabled components, setting the entire form to disabled (this.options.readOnly) and others so that's why there is a function to determine if any of the conditions cause a component to be hidden.

You shouldn't be updating this.component while the component is initialized. That's the component definition from the api server. If you want to set wether a component is disabled or not, you should be able to set this.disabled = true instead of this.component.disabled.

**Comment by brianagriffith** [comment]
Sorry, I think I was unclear. We are attempting to set the value of this.disabled, not this.component.disabled. The issue is that shouldDisable is invoked from inside the this.disabled setter function. shouldDisable checks the value of this.component.disable and (assuming the other values are false) will always resolve to that value.

So, if the value of this.component.disable = false and you attempt to set this.disabled = true, the if statement below will always resolve to false
```
// disabled would be true, shouldDisable would be false
if ((!disabled && this.shouldDisable) || (disabled && !this.shouldDisable)) {
  return;
}
```
Because this resolves to false, it returns out of the setter function without changing the value or disabling the component.

The opposite is true as well, if this.component.disable = true and you attempt to set this.disabled = false, the above if statement would resolve to false and return out of the function without doing anything.

I did a quick test locally and commenting out that if statement seemed to resolve the issue but I can't say if it that is the correct fix or not.

**Comment by randallknutson** [comment]
I think this is by design. If the component definition says it is disabled, it should stay disabled. What are you trying to accomplish?

**Comment by brianagriffith** [comment]
We use these forms in the context of a workflow and the same form is often presented in different contexts (think steps of a workflow). We frequently have requirements to enable/disable components based on the context in which they are being presented/used. Given that, we can't rely on just the component definition from the server. We've accomplished this in the past (using the ngFormio library) via custom scripts that set this.disabled based on the appropriate business logic. We would like to move over to this library but really need this functionality to be able to do that.

**Comment by randallknutson** [comment]
In ngFormio we had an option to pass an array of disabled components to the renderer. That was the best way to disable a dynamic list of components. We could do something similar to formio.js by changing the line in base/Base.js to

get shouldDisable() {
    return (this.options.readOnly || this.component.disabled) && !this.component.alwaysEnabled || (this.options.hasOwnProperty('disabled') && this.options.disabled.includes(this.component.key));
}

Then pass an array of component keys to be disabled

options = {
  disabled = ['one', 'two']
};

**Comment by brianagriffith** [comment]
I still think there is an issue with the shouldDisable logic. I did some more testing today and discovered that if you disable a nested component (like datagrid) the components within it are not disabled. 

Looking at the code, the nested component simply calls the disable setter of each child component. The disable setter in turn calls shouldDisable, which returns false because the individual components inside the datagrid are not disabled and thus the components do not get disabled.

That, to me, is the core issue. The disable setter needs to be able to accept a value that is different from the component definition and apply that value accordingly, while still accounting for things like the form being read only or a component being always enabled.

**Comment by travist** [comment]
Sounds like we need to traverse the parent tree to determine if the component should disable. Either that or we can pass in a "force" variable to the disable methods to force them to be disabled. Pull requests welcome.
