### ISSUE TITLE
BUG: Form builder taking a lot of memory

### ISSUE THREAD

**Issue by sanjaykrgaur** [formio/formio.js#1052]
Hi,

I am using formiojs version 3.16.2. When I drag any component e.g. text field a popup opens asking to set its properties
Each time I switch tabs in the property window memory utilization of chrome increases

If I switch tabs multiple times then it uses all the available memory and chrome crashes with out of memory error.

This issue has started coming since formiojs version 3.16.1. It is not coming in versions before that.

Can You please look into this.

**Comment by travist** [comment]
Thanks for reporting. I am looking at some recent breaking changes today and will investigate this issue.

Thanks.

**Comment by travist** [comment]
This should be resolved in **3.16.3**. Please let us know otherwise.

**Comment by duanlixia** [comment]
hello. The  form builder,memory occupied is not released, and memory is increasing.What is the reason? thinks.

**Comment by travist** [comment]
Please share your javascript memory consumption logs using Developer Tools so that we can identify what may be causing this problem.

**Comment by sanjaykrgaur** [comment]
For me this was solved in 3.16.3
