### ISSUE TITLE
Select Component does not send Headers

### ISSUE THREAD

**Issue by erbg** [formio/formio.js#1053]
Seems that the change from whatwg-fetch to fetch-ponyfill break the Headers in the Rest calls. 

My Formio:
 
{
    "components": [
{
                    "label": "Test",
                    "mask": false,
                    "autofocus": true,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "select",
                    "input": true,
                    "key": "Test",
                    "defaultValue": "",
                    "valueProperty": "id",
                    "data": {
                        "url": "http://localhost:6002/groups",
                        "headers": [
                            {
                                "key": "Content-Type",
                                "value": "application/json"
                            },
                            {
                                "key": "X-ZUMO-AUTH",
                                "value": ""
                            }
                        ],
                        "values": []
                    },
                    "dataSrc": "url",
                    "template": "<span>{{ item.name }}</span>",
                    "encrypted": false,
                    "lazyLoad": false,
                    "selectValues": "data",
                    "disableLimit": false,
                    "properties": {},
                    "tags": [],
                    "validate": {
                        "select": false,
                        "customMessage": "",
                        "json": ""
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "sort": "",
                    "selectThreshold": 0,
                    "customConditional": "",
                    "logic": [],
                    "reorder": false,
                    "reference": false
                }   ]
}

The Rest call has no X-ZUMO-Header nor a content-type header.

**Comment by travist** [comment]
Thanks for reporting. We will take a look asap.

**Comment by erbg** [comment]
Probably you have to use the Headers Object of Fetch/ and not the nativ ones. 
If i understand it well fetch-ponyfill uses the version 2.0.3 of whatwg-fetch.

https://github.com/github/fetch/issues/673

**Comment by travist** [comment]
I think I found the problem. New version coming soon with the fix in place.

**Comment by travist** [comment]
This is fixed in **3.16.3**.  Thanks for reporting it.
