### ISSUE TITLE
Load data in cascade from select

### ISSUE THREAD

**Issue by gjagomez** [formio/formio.js#1057]
Load data in cascade from select

Hello, there is some way to load cascade data in a select using Data Source Raw JSON.

Thanks for the help

**Comment by randallknutson** [comment]
I'm not entirely sure what you mean by cascading data. 

Here are some examples of what you can do with selects:
http://formio.github.io/formio.js/app/examples/external.html
http://formio.github.io/formio.js/app/examples/select.html

**Comment by gjagomez** [comment]
Thanks for answering what I need is like this example [http://formio.github.io/formio.js/app/examples/external.html ](url)
but with Data Source Type Raw JSON

**Comment by randallknutson** [comment]
You can't do this with JSON, you can do it with Custom though. You can have different data sets based on the value of a previous component.

**Comment by gjagomez** [comment]
> You can't do this with JSON, you can do it with Custom though. You can have different data sets based on the value of a previous component.
