### ISSUE TITLE
"Adding a new resource" not working

### ISSUE THREAD

**Issue by msubero** [formio/formio.js#106]
Hi,
I'm trying to render a form with a resource component within it, but even when I'm capable of render the **resource type component** and display the records related to the resource itself, it seems like the library not support the inclusion of a button for adding a new resource like it does in the _ngFormio library_

This is my JSON schema sample:

    "components" : [{
            "project" : "",
            "defaultPermission" : "",
            "input" : true, 
            "tableView" : true, 
            "label" : "Customer", 
            "key" : "customer", 
            "placeholder" : "", 
            "resource" : "my_resource_id", 
            "defaultValue" : "", 
            "template" : "<span>{{ item.data }}</span>", 
            "selectFields" : "", 
            "searchFields" : "", 
            "multiple" : false, 
            "protected" : false, 
            "persistent" : true, 
            "validate" : {
                "required" : true
            }, 
            "type" : "resource", 
            "hidden" : false, 
            "clearOnHide" : true, 
            "tags" : [

            ], 
            "conditional" : {
                "show" : "", 
                "when" : null, 
                "eq" : ""
            }, 
            "addResource" : true, 
            "addResourceLabel" : "Add"
        }]

This is what I expect to see:
![sample_1](https://user-images.githubusercontent.com/8751050/26889484-b78ffe38-4b84-11e7-8def-4f5df7b46055.png)
This is what I actually see:
![sample_2](https://user-images.githubusercontent.com/8751050/26889705-5d37b2b8-4b85-11e7-9988-213713a69569.png)

The only thing that is rendered is the **resource field** and not **the resource field + the "add" button** like it should.

**Comment by travist** [comment]
Yes, this still has not been implemented in the core renderer. We are working very hard to get all of the Angular 1 features built into this renderer and this is on our list. Thanks for your patience.

**Comment by douglaselee** [comment]
I'm working on this.

**Comment by jhen1422** [comment]
This feature has been added to the core renderer
