### ISSUE TITLE
Can't load component from local link

### ISSUE THREAD

**Issue by binhluong2012** [formio/formio.js#1065]
Hi,
Can i load components from different url, not from form.io? for example:
`Formio.builder(document.getElementById('builder'),"http://localhost/loadForm/1",{});`
I try to save form to db, then can load again to edit,view without add to "form.io"
Thank you.

**Comment by randallknutson** [comment]
You can pass the form json directly to Formio.builder which might be a better idea. For example,

// load form definition from http://localhost/loadForm/1
const formDefinition = {}

Formio.builder(document.getElementById('builder'), formDefinition, {});

**Comment by binhluong2012** [comment]
It's worked. Thanks @randallknutson
