### ISSUE TITLE
Editing the Designer Area Text

### ISSUE THREAD

**Issue by sneha-boopal** [formio/formio.js#1066]
I want to edit the text(Drag and Drop a form component) in the designer region of form builder. Is there any way so that i can override the text. Please suggest.

**Comment by travist** [comment]
You can modify the edit forms by providing an override configuration as you see here.

http://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by sneha-boopal** [comment]
![designer](https://user-images.githubusercontent.com/30856025/54177200-6d99a300-44b7-11e9-8b49-a59b31b78cfb.PNG)

@travist Thanks for the reply. I wanted to override the text which is highlighted in the image. Do did mean it can achieved by edit forms?

**Comment by randallknutson** [comment]
Looks like this is currently not possible. We would need to wrap the content on this line https://github.com/formio/formio.js/blob/6f0d0cb8cc3b830527a53ef4cacc1db827aa32b6/src/WebformBuilder.js#L52 with this.t() to make it translatable.
