### ISSUE TITLE
Extending an existing formio component.

### ISSUE THREAD

**Issue by sneha-boopal** [formio/formio.js#1069]
Is there any way to extend the existing formio components? Please provide any example link for extending the existing components like textfield component.

**Comment by travist** [comment]
You can extend any component by creating a custom renderer, extending the base classes, and then setting the component back into the components array. 

Please take a look at how the Custom Renderer repo works https://github.com/formio/custom-renderer.

Specifically here... 

https://github.com/formio/custom-renderer/blob/master/components/TextField.js

and here.

https://github.com/formio/custom-renderer/blob/master/index.js#L9

**Comment by Anandks1993** [comment]
@travist Is there an example of extending a component via React (react-formio)?

**Comment by AlexeyDavyd** [comment]
@Anandks1993 You can do same steps mentioned above and replace component with your new one before calling setComponents method.

For example in src/index.js if you would like to use react-app-starterkit: https://github.com/formio/react-app-starterkit/blob/master/src/index.js
