### ISSUE TITLE
Wizard fails to display JSON data after 1st panel

### ISSUE THREAD

**Issue by ammonlee01** [formio/formio.js#107]
I loaded a form with initial submission data using JSONs for both the form itself as wells as the data.

However, I found that only the 1st visible panel got the fields populated. Any other panels, after navigating to them, shows blank pages.

I checked that the form.submission are trimmed after I assign them to the form.

Grateful if you can look into the issue.

**Comment by cabrerabywaters** [comment]
Hello @ammonlee01 

I had the same problem but I managed to solve it changing the way that you load the submission for the Wizard component.

For FormioWizard use ==> form.data
For FormioForm    use ==> form.submission

there was another open issue that gave me to this solution. https://github.com/formio/formio.js/issues/111
