### ISSUE TITLE
Form running slow with lots of custom logic

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#1070]
We have a pretty lengthy form with approximately 700 yes/no questions inside about 40 panels. Each panel has some advanced logic for showing the panel and about 50% of the questions have a conditional on them to show/hide the question based on the question above it.

Problem 1: The form is slow - taking approx 2-5 seconds to update anytime anything is selected.
Problem 2: "Logic" tab does not seem to work. We had to write custom javascript to show/hide each panel due to the logic not working. The custom logic does seem to work properly.

Is there anything we can do to speed up the form? Would getting the logic to work and removal of the custom javascript speed things up, or would it amount to the same issue? Just curious if perhaps the custom logic we are using would run slower than using the provided "logic" tab for each panel. We need logic, versus conditional, due to 2-3 conditions needing to be met before showing/hiding a given panel.

Willing to discuss expediting if necessary.

**Comment by travist** [comment]
Hey @ProteanHub,

Sorry you are having issues. A form should work just fine with 700 yes/no questions, so this tells me that you are running into an infinite onchange issue that has caused performance problems with other forms that we have debugged having similar issues. To determine if you have hit an infinite on change issue, you can add the following to your form logic.

```
Formio.createForm(document.getElementById('formio'), 'https://yourproject.form.io/yourform').then((form) => {
  form.on('change', (change) => {
    console.log(change);
  });
});
```

If you see this change event going crazy without ever stopping then this tells me that is the source of the problem. We are able to debug the source of this for you if you would like (with paid support) or you can step through the event loop to determine why the form values appear to be constantly changing back and forth between states (which is what usually causes this problem). In some cases you may have conflicting conditions.. For example, where field A changes value of B, and B changes value of A.

As for logic, we do know it works for simple cases but have heard of it failing for more complex forms. This may be something that we could also look into. Here is a "simple" example of it working.

http://formio.github.io/formio.js/app/examples/fieldLogic.html

It may help if you provide some examples of your logic not working so we can debug on our end.

Again sorry you are having issues, but we have successfully debugged forms like this in the past and I am confident we can get to the bottom of the form performance issues.

Thanks,

Travis.

**Comment by ProteanHub** [comment]
Thanks @travist I appreciate the quick response. That code only brings up a single item during each change.

I will contact Denise and reference this issue so we can get the ball rolling on having you take a look.

**Comment by ProteanHub** [comment]
Just downloaded the newest version, thanks. When I enable that setting, it deletes all the content within the panel upon saving.

**Comment by ProteanHub** [comment]
After more testing, I am finding that the panel keeps closing (while in the editor) on our local system. I can open it up, then drag a component into the panel, and it instantly closes again. The link you sent doesn't do that, but it appears you are using the angular version for beta.form.io and we are using the pure javascript version for our system.

If I save the form with it collapsed, it deletes all the items in that panel. If I open it up, then save it, all appears normal.

In the end, this may indeed work for us if we can trigger the panel to open when a question above it is answered in a certain way.

**Comment by travist** [comment]
Yeah, we just found this issue in our testing and has already been fixed. Sorry about that. Please try again.

**Comment by ProteanHub** [comment]
Are you kidding me, thanks for being so responsive! I will take a look tonight.

**Comment by ProteanHub** [comment]
It is much improved with the lazy loading. Not quite 100%, but certainly workable. Is there a way to open a given panel up when it is triggered through a condition?

**Comment by travist** [comment]
I would have to test this, but am not sure how this will behave with conditions.

**Comment by ProteanHub** [comment]
The conditions work well on our end and shows the panel initially collapsed. I tried setting instance.collapsed=false and instance.component.collapsed = false inside of the advanced conditional with no effect.

**Comment by travist** [comment]
I think it would be this.

```
if (instance.collapsed) {
  instance.toggleCollapse();
}
```
