### ISSUE TITLE
Image in Content Component

### ISSUE THREAD

**Issue by noman115pk** [formio/formio.js#1071]
Hello,
Content component has been updated recently and it seems it do not support uploading of images anymore the way it was [described](https://www.screencast.com/t/RqJ0eBgC). I am receiving an error in console.

`filerepository-no-upload-adapter: Upload adapter is not defined.`

How can we define an upload adapter for formio content component?

Appreciate your help.

Thanks

**Comment by wag110894** [comment]
Hello, 

You are correct. We changed the content component on our Core Renderer from Quill to CK Editor. 
We have created a ticket (FOR-2140 ) and will address this in our next planning meeting. 

In the meantime, you can use our production portal to set it up as I showed in the above video. Another option is you can also use the HTML Component and add the image source code into the content section of the display tab.

Here is an example:
<div class="well"><p><img src="https://www.w3schools.com/tags/smiley.gif" /></p>
</div>

Here is a screencast to show how you can set up image in the HTML Component on our Core Builder as well as our Beta Portal that also uses our Core Renderer.

https://www.screencast.com/t/f4Lwe05Hqy


Please let me know if you have any further questions or concerns. 

Thanks!

**Comment by noman115pk** [comment]
Appreciate the quick response. I will be following up on FOR-2140 as this could be the need for customer to upload file from their local system rather than pasting link from a cloud.

Thanks,

**Comment by wag110894** [comment]
Hello,

Thank you for your patience regarding this issue. After discussion with the team, we have decided that this is a low priority on our end. We have quoted this fix at 8 hours. Please let me know if you are interested and I would be more than happy to send you a formal quote.

Please let me know if you have any further questions or concerns. 

Thanks.
William Gay
Form.io Support

**Comment by noman115pk** [comment]
Hello,

Thanks William for your response. We have also discussed with the team in planning meeting. It is not at highest priority for us at the moment. I will ask you about the formal quote when the time is right.

Thanks.

**Comment by jhen1422** [comment]
This issue has been resolved with our 4x branch of our formio,js renderer
