### ISSUE TITLE
How to get html data using form.io layout ?

### ISSUE THREAD

**Issue by ahankumar** [formio/formio.js#1072]
Hi,

I have added form.io for angular site but i am facing issue regarding getting components (input elements) in html format with supporting js so i can render this directly in another page as a form.

Please suggest me any solution regarding this  

Thanks

**Comment by randallknutson** [comment]
What issue are you facing?

**Comment by ahankumar** [comment]
Hi,

I need form html with it's supporting JS so i can use that form in my application means when i add form using input components then i want to get form html data 

Thanks

**Comment by travist** [comment]
The html of the form can be retrieved with the 4.x renderer. I think @randallknutson knows the api on how to get the html of the form, but again, you will need to use the 4.x version of the renderer. As for "supporting js" I am not sure what this means. Our whole renderer is a javascript renderer so "supporting js" would probably mean the whole renderer js code.

**Comment by randallknutson** [comment]
Our system works quite differently than other form systems. Forms are stored as JSON definitions of the form which you can see by looking at the embed url of the form after you create it. The way it works is that we have a renderer in javascript that will take the JSON definition and render it while it is in your webpage. To test this out, use the quick inline embed on the Embed page of your form. Just past the code provided onto your website and it will render the form and set up all the javascript for it as well.

**Comment by ahankumar** [comment]
Ok, so how to get JSON data using form.io because i have got the method to render the form but i didn't get the method to retrieve the components json after creating form. i am using below mehtod:
Formio.builder(document.getElementById('builder'))
