### ISSUE TITLE
JsonLogic and datagrid...refreshes calculated hidden value

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1073]
Hello,

I have a data grid with a set which looks like this:

```
hours: [
 {activity: 'a', hours: 24}
{activity: 'b', hours: 44}
]
```
I then have an input that shows the total (every time a new data grid item is added and populates the hours it should then update the input box.

I then have the following json logic to populate the total input box.

```
{
  "reduce": [
    {
      "var": "data.hours"
    },
    {
      "+": [
        {
          "var": "current.hours"
        },
        {
          "var": "accumulator"
        }
      ]
    },
    0
  ]
}
```
The issue is that everytime i add a new item the input count is cleared. However when i add a value in the hour data grid row the input is populated with the previous items and the new one.  Is there a way to stop the refresh in the input box and retain the original value?

Any help would be appreciated.

**Comment by randallknutson** [comment]
I'm not sure I understand what the issue is here. If values are getting placed in the wrong location, there may be a bug with the datagrid. Can you describe a little more what is going wrong?
