### ISSUE TITLE
Events whom to notify broken

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#1075]
When I update the "whom to notify with updates" section on the Events Calendar (in Settings), it doesn't "stick". When I go back the settings it shows blank again.

**Comment by randallknutson** [comment]
Can you clarify where the issue is? I'm not sure what forms or settings you are talking about. Is this an app you are working on?

**Comment by ProteanHub** [comment]
Haha, sorry... wrong project. Please delete.
