### ISSUE TITLE
DataGrid default value don't work in form builder.

### ISSUE THREAD

**Issue by kran** [formio/formio.js#1081]
notice the datagrid component has default value  in form builder in recent releases, when children components in datagrid are "required", default values must be given, if not, the builder form can't be submited.

and if remove the row of "default value" in datagrid builder (don't need default values), datagrid lost all children when re-render.

**Comment by jhen1422** [comment]
This issue will be resolved when we release our 4x renderer in the next couple of months

**Comment by AnthonyPhan** [comment]
Seems like this issue has not yet been resolved. @jhen1422 do you have any updates on this issue?

**Comment by jhen1422** [comment]
@AnthonyPhan This is working fine on our end. We are using version 4.8.0-rc.13, can you confirm what version you are using?

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51660">51660</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley unlinked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51660">51660</a> from this issue.</div>
