### ISSUE TITLE
After upgrading the bootstrap from 3 to 4, Form IO UI not displayed properly ?

### ISSUE THREAD

**Issue by signalarun** [formio/formio.js#1084]

**Comment by randallknutson** [comment]
The formio.js 3.x branch is mostly compatible with bootstrap 4. There are a few places with classes are missing. The formio.js 4.x branch (currently in beta) has a way to dynamically switch between bootstrap 3 and 4 and is fully compatible with bootstrap 4.

**Comment by signalarun** [comment]
I am using angularjs.Is there version that support angularjs and bootstrap 4.
