### ISSUE TITLE
How do i get the JSON from the form layout?

### ISSUE THREAD

**Issue by sankarvenkataraman** [formio/formio.js#1088]
I am using Formio.builder(document.getElementById('builder')) to build the form layout. After adding the required components to the form, how do i get the JSON representing the form?

**Comment by randallknutson** [comment]
You should be able to do something like the following:
```
var builder = Formio.builder(document.getElementById('builder')).then(function() {
  builder.instance.schema;
})
```

**Comment by sankarvenkataraman** [comment]
The instance property on the builder is null when the promise is resolved. Can you elaborate?

**Comment by randallknutson** [comment]
It may be that instance is returned by the promise. For example: 

```
Formio.builder(document.getElementById('builder')).then(function(instance) {
  instance.schema;
})
```

**Comment by sankarvenkataraman** [comment]
I am able to get the added components array from instance.schema. I will have to go through the array and construct the JSON myself?

**Comment by sankarvenkataraman** [comment]
Issue closed. Able to get the form JSON.
