### ISSUE TITLE
bug in calculateValue

### ISSUE THREAD

**Issue by ammonlee01** [formio/formio.js#109]
The existing logic:
    var val = eval('var value = [];' + this.component.calculateValue.toString() + '; return value;');

should be:
    var val = eval('var value = [];' + this.component.calculateValue.toString() + ';  value;');

**Comment by travist** [comment]
I am curious why having a ```return value``` is not correct. Can you explain further why you believe this is wrong?

**Comment by ivanljutyj** [comment]
![screen shot 2017-06-27 at 2 11 39 pm](https://user-images.githubusercontent.com/26074267/27602987-a4ef6138-5b42-11e7-94d1-7eada877341e.png)
I've also run into this issue, and removing the return statement from eval() fixes this bug.

**Comment by travist** [comment]
Will you guys let me know if this PR fixes this problem for you? https://github.com/formio/formio.js/pull/119

**Comment by ivanljutyj** [comment]
Looks good! @travist

**Comment by travist** [comment]
This is pushed with the latest version.
