### ISSUE TITLE
Cannot read property 'version' of undefined moment-timezone.js 

### ISSUE THREAD

**Issue by weixiaomiandui** [formio/formio.js#1093]
![image](https://user-images.githubusercontent.com/19527831/54581923-aa324500-4a49-11e9-95c5-7d913d9e5f13.png)
![image](https://user-images.githubusercontent.com/19527831/54581978-ebc2f000-4a49-11e9-8f43-08e2fe35ba73.png)
What is the cause of this?

**Comment by jhen1422** [comment]
This issue should no longer exists.

If the problem persists, please feel free to open a new issue.
