### ISSUE TITLE
offline is not defined in offline plugin

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1099]
trying to use offline plugin but when i am trying to make forced offline through plugin api it saying offline not defined...

![image](https://user-images.githubusercontent.com/48546522/54701339-d1c50280-4b5a-11e9-9ca6-4d63974a1100.png)

here in that parameter it saying offline not defined.
![image](https://user-images.githubusercontent.com/48546522/54701374-e73a2c80-4b5a-11e9-89f6-2174c3faeace.png)

![image](https://user-images.githubusercontent.com/48546522/54701654-6a5b8280-4b5b-11e9-942b-7ee9ed8a26d0.png)

**Comment by travist** [comment]
This seems to be an error that came from your "index.html" page which means somewhere in your logic handler you may be using the term ```offline``` that is not defined. Please confirm, but I don't believe this is a problem with our offline plugin.

**Comment by lane-formio** [comment]
<div>Agent Savvas Sidiropoulos linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/49511">49511</a> for this issue.</div><br/>
