### ISSUE TITLE
Application slows down: Angular infinite digest loop

### ISSUE THREAD

**Issue by basvandepol** [formio/formio.js#11]
![screen shot 2016-02-25 at 09 50 38](https://cloud.githubusercontent.com/assets/17470067/13315418/d98cfd92-dbaa-11e5-9bed-58e8192d606b.png)
![screen shot 2016-02-25 at 09 50 45](https://cloud.githubusercontent.com/assets/17470067/13315421/dd0534b2-dbaa-11e5-8230-f156da7a2300.png)

Hi Zack,

i'm trying to use Form.io to build beautiful forms. I've downloaded the repository and have it up and running with MongoDB. 
One of my needs is to build a form with a table. For example the table has 9> rows and 5 columns, each column has a different input. This works (as the only form builder i've found) like a charm. 
I face only one issue. For example when I reach row 6 and drag and drop a number form control into one of the columns the application gets real slow. I've checked and this is for both the local version as the cloud version on Form.io.

When i check the console Angular is giving errors (which also slows down the console real bad). 
The error: 
`Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations` 

I've also added screenshots for my example table and the total console logs. 

I hope you could help.
Thanks in advance,

Bas van de Pol

**Comment by randallknutson** [comment]
We've made several performance improvements to our form builder. Is this still occurring?

BTW, this should probably be in formio/ngFormBuilder as that is what is throwing the error.

**Comment by travist** [comment]
This will be resolved with core renderer.
