### ISSUE TITLE
how can i pass authentication key when i use custom component form  

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1100]
actually i created custom component to create from but how can i pass authentication when submitting form..

**Comment by randallknutson** [comment]
By default the form will pass along the form.io jwt token if you are logged in using the form.io authentication system. You can get the current token by calling Formio.getToken()

**Comment by randallknutson** [comment]
By default the form will pass along the form.io jwt token if you are logged in using the form.io authentication system. You can get the current token by calling Formio.getToken()
