### ISSUE TITLE
how to use loaded forms from offline plugin in another html page from indexedDB

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1104]
i am using offline plugin for loading all forms at app start and i am getting all forms in indexedDB but i want to render that forms in another page...my requirement is i want to load all forms at stating time and after that i want to render forms in another pages from indexedDb. please help me that..

setting at first like this..

![image](https://user-images.githubusercontent.com/48546522/54766344-203cd480-4c21-11e9-8360-548cdd217223.png)

2nd html page like this but i am not getting here..can u help me how can i access that forms.

![image](https://user-images.githubusercontent.com/48546522/54766468-50847300-4c21-11e9-8c35-60495f4d955a.png)

**Comment by travist** [comment]
It should work by just calling 

```html
<div id="formio"></div>
```

```js 
(new Formio(OTHER_FORM_URL)).loadForm((form) => {
  Formio.createForm(document.getElementByid('formio'), form);
});
```

**Comment by sureshece9999** [comment]
> It should work by just calling loadForm
> 
> ```
> <div id="formio"></div>
> ```
> 
> ```js
> (new Formio(OTHER_FORM_URL)).loadForm((form) => {
>   Formio.createForm(document.getElementByid('formio'), form);
> });
> ```

that is working when network present but i want to access that from in offline mode from indexedDB that to when i open new tab with from id.

**Comment by randallknutson** [comment]
Our offline mode was designed for Single Page Applications and may not work with multiple pages re-initializing the offline plugin. We could look into this and see what is going on.

**Comment by sureshece9999** [comment]
so in my case it wont work...?
actually i want to load all forms at app start and then move to offline why because my entire submissions will be offline only...and then i want to use this forms at different pages..
