### ISSUE TITLE
Variance in "load submission" method between FormioForm and FormioWizard

### ISSUE THREAD

**Issue by rmckeel** [formio/formio.js#111]
Not sure if this is intended (perhaps it just needs to be [documented](https://github.com/formio/formio.js/wiki/Form-Renderer)), but I found that on FormioForm, setting this.form.submission works, however using FormioWizard, you have to set the data specifically, and nothing happens (no data loaded) when you set this.form.submission.

Put another way, FormioWizard does not accept the submission parameter, but it does accept the data parameter.

Here is some sample code to illustrate the difference between form and wizard handling that currently works in my application.  Thanks for any thoughts!

```
            this.bindElement = this.elementRef.nativeElement.querySelector('.my-form');
            if ('wizard' == this.type) {
                this.form = new FormioWizard(this.bindElement);
            } else {
                this.form = new FormioForm(this.bindElement);
            }

            this.form.src = this.src;

            if( this.submission ) {
                if( 'wizard' == this.type ) {
                    this.form.data = this.submission.data;
                } else {
                    this.form.submission = this.submission;
                }
            }
```

**Comment by travist** [comment]
This is very strange. I will look into it.  On a similar note, you may have noticed that we created a factory that allows you to dynamically create a form based on the type defined in the schema. It works like.

```js
import { Formio } from 'formiojs/full';

let form = 'https://examples.form.io/example'; // This could also be the actual JSON object.
Formio.createForm(form).then((formInstance) => {
  formInstance.submission = {....};
});
```

Try that and see if that resolves the issue.

**Comment by rmckeel** [comment]
Nice.  Good to know that method exists.  I'll try it out.

**Comment by shuhaib-aot** [comment]
### I am rendering form with react-formio and when i use reference and check the validity is return true at the same time I am creating a form with formio.create function using the same data. and giving checking the submission but return false

```
    console.log(formRef.current.formio.checkValidity());
    const formInstance =  await Formio.createForm(form); 
    console.log(formInstance.checkValidity(submission.data));
```
