### ISSUE TITLE
how can i display submitted data in the form with submitted data

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1115]
i am trying to submit data from form and then want to display that submitted data like in form with data how can i do this ..please help me..thank you.

**Comment by randallknutson** [comment]
Once you have submitted the form, you will have a submissionId. If you change the form url to https://myproject.form.io/myform/submission/:submissionId it will load and display the submission.

Another way of doing this is to set the submission object on the form after it has loaded.
