### ISSUE TITLE
clear offline data through offline plugin methods

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1116]
i am trying to clear all cached offline data i.e offline cached forms and submissions, as well as submissions waiting in the offline queue. i am using this event **`plugin.clearOfflineData();`**.
but i am getting this error.

![image](https://user-images.githubusercontent.com/48546522/55219512-17549000-522b-11e9-80e5-29606d65ceb2.png)

so in this what is that **Document must be a JSON object**

In **index.es.js** file showing error

![image](https://user-images.githubusercontent.com/48546522/55219652-731f1900-522b-11e9-95c3-a4a78de49ada.png)

**please give me any example for this..thank you.**

**Comment by randallknutson** [comment]
Looks like we weren't clearing the submission queue correctly after the pouchdb update. I've pushed up 2.0.2 of the offline plugin with a fix. Can you test it out?
