### ISSUE TITLE
Bug: Select component does not store value after scrolling option list to bottom

### ISSUE THREAD

**Issue by zdegner** [formio/formio.js#1117]
Scrolling to the bottom of a select's options causes the select to remain in "loading" state which nulls out the value of the field when its value is read.

JS Fiddle here:
http://jsfiddle.net/y3qwucfo/

Steps to reproduce:
- open the select
- scroll all the way to the very bottom of the options (important step!)
- select an item
- notice that the Selected Value is not updated correctly

I've debugged through the code and believe the issue is here:
https://github.com/formio/formio.js/blob/083533aa768600de36baeff3063621e915b3aa66/src/components/select/Select.js#L283

The problem occurs because the block below causes the setItems(...) method to skip out early, but it never sets `this.loading = false;` after calling `this.stopInfiniteScroll();`

```if (
        this.currentItems.length &&
        items.length &&
        _.isEqual(this.currentItems[0], items[0]) &&
        _.isEqual(this.currentItems[1], items[1])
      ) {
        this.stopInfiniteScroll();
        return;
      }
```

**Comment by travist** [comment]
Yeah this is a bug. It sounds like you have a good idea what may be causing this so do you mind making a pull request with the fix in place? If so, then we will pull it into the next release.

**Comment by zdegner** [comment]
I've created a PR with the fix and confirmed that it resolves the scenario noted above. 

Great library by the way! I find it amazing what this tool can do.
