### ISSUE TITLE
Add custom component properties

### ISSUE THREAD

**Issue by adelaaji** [formio/formio.js#1121]
Hello all,

I would like to know how can I add properties for custom component to Form builder .
I have added custom component by following this link :
http://formio.github.io/formio.js/app/examples/customcomponent.html

 but I need to add my custom properties such as **Formio.Components.components.table.editForm**,

Is there any documentation or example can I follow ?

Thanks.

**Comment by randallknutson** [comment]
This example is in the React app but applies to any frontend. 

https://github.com/formio/react-app-starterkit/blob/master/src/components/CheckMatrix.js#L5-L22

**Comment by randallknutson** [comment]
You can modify the editFrom before passing it to the static editForm property. You can either modify the component like changing its title or add "ignore: true" to make it hide itself.

**Comment by adelaaji** [comment]
@randallknutson 

Is there any  any documentation or user guide for that ?

Thanks.

**Comment by randallknutson** [comment]
You can see lots of examples in the formio.js library. See https://github.com/formio/formio.js/blob/master/src/components/checkbox/Checkbox.form.js

**Comment by marcomoreira16101** [comment]
@rahatarmanahmed 

Hi, sorry to bore you. Could you please explain me how I access this editForm to edit
 or hide it before adding the component itself.

![Capture](https://user-images.githubusercontent.com/36764378/55475600-493f6b00-560c-11e9-84e7-e216be7a4a10.PNG)

**Comment by randallknutson** [comment]
You can either set it directly on your component or set it as a static property of the class. For example:
```
class MyClass extends Component {
  static editForm = theEditForm;
}
```

or 

```
class MyClass extends Component {
  ...
}

MyClass.editForm = theEditForm;
```
