### ISSUE TITLE
how to get previous drafted form values if i open that form again

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1122]
i am trying to draft my form submission, means i want to finish it later..so when i open that form again can i get previous drafted values with that respected form...?

i know how to get previous submissions..is this the way to do or else any alternative is there...?

**Comment by travist** [comment]
We have code in this library that will load existing "draft" submissions within the webform called ```restoreDraft```. Here is the code.

https://github.com/formio/formio.js/blob/master/src/Webform.js#L781

This happens automatically if you provide the ```saveDraft``` flag when you create the renderer.

https://github.com/formio/formio.js/blob/master/src/Webform.js#L256

Like this.

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
  saveDraft: true
}).then(() => {
  
});
```

Please note that this does require that you establish the user authentication like what our angular-formio library will do for you.
