### ISSUE TITLE
Text field description

### ISSUE THREAD

**Issue by HenoTaMyJIb** [formio/formio.js#113]
Does Formio.js not support text field description (text under the input), even if component has a description property?

**Comment by travist** [comment]
As of right now it does not, but that will be added soon.  Thanks.

**Comment by HenoTaMyJIb** [comment]
Thank you!

**Comment by travist** [comment]
This will be fixed with https://github.com/formio/formio.js/pull/122

**Comment by jhen1422** [comment]
The 'Description' feature is now supported with formio.js
