### ISSUE TITLE
CalculateValue not working on component in side the edit grid.

### ISSUE THREAD

**Issue by pradippatil04** [formio/formio.js#1150]
When write validation and calculated value on the edit grid template , the validation fires correctly on each row separately but calculated value not working at all even on first row of the edit grid.

**Comment by heather-formio** [comment]
@pradippatil04 I'm closing this issue for now as it was some time ago. In our testing, validation is firing correctly in the latest versions. Please feel free to reopen with a jsfiddle or example code if an issue remains.
