### ISSUE TITLE
How to dequeue Submissions from offline plugin

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1156]
I am trying to submit the submissions from offline cache through offline plugin, But when I use 
`offline.dequeueSubmissions()` all submissions are going to Formio. Which ever having error that are skipping and continue to the next queued request. While doing this which is having error one  that submission is removing from indexedDB. How can i maintain that submitted one while skipping queue.
 
**Here I am listening error event**

![image](https://user-images.githubusercontent.com/48546522/55803676-6d151c00-5af8-11e9-8439-c902ff3dad97.png)

**While doing dequeue submission getting error like this**

![image](https://user-images.githubusercontent.com/48546522/55803927-f88ead00-5af8-11e9-9191-3ceaea06d031.png)

How can i maintain failure submissions in indexedDB, It is deleting from indexedDB and continuing next submission. Thank you.

**Comment by travist** [comment]
This is possibly because the api is causing an error with a conflict. May need @randallknutson to chime in here since he is more familiar with how the offline mode plugin works.

**Comment by heather-formio** [comment]
@sureshece9999  I'm closing this issue for now as it was some time ago. In our testing, offline plugin is behaving correctly in the latest versions. This is also not a formio.js topic as this is offered only in our enterprise offering.
