### ISSUE TITLE
form builder custom validation not saved

### ISSUE THREAD

**Issue by mutex12** [formio/formio.js#1161]
In MAC Chrome: 

https://formio.github.io/formio.js/app/builder
^^^ throws js exceptions at the moment.

+ rolling my own builder:
<script src="https://unpkg.com/formiojs@latest/dist/formio.full.js"></script>
Formio.builder(document.getElementById('builder'));
^^^ no exceptions but rule is not saved.

**Comment by mutex12** [comment]
3.7.0 appears to work

**Comment by travist** [comment]
We do see an issue with the latest renderer.... we are looking into it.

**Comment by heather-formio** [comment]
This is working in our latest versions.
