### ISSUE TITLE
Integration with ionic3/angular5 app

### ISSUE THREAD

**Issue by oneserve** [formio/formio.js#1168]
Hello

Have been trying to use the formio package within ionic3/angular5 app. 

Have tried using both formiojs and angular-formio libraries, but both failing with same error.

Formio
"formiojs": "3.19.7"

Same error occurs when using angular wrapper
"angular-formio": "3.11.6"

Downgrading package to following version “formiojs": "2.29.11” removes the error.

I have setup example repo to replicate the issue.

https://github.com/oneserve/formio-ionic3/tree/master

@travist Do you have any suggestions how to solve this?

Error:
> Uncaught TypeError: t.resolve is not a function
> at Object.setNativePromise (polyfills.js:3)
> at R.configurable.R.set (polyfills.js:3)
> at module.exports (_redefine.js:19)
> at $export (_export.js:27)
> at Object.<anonymous> (es6.promise.js:222)
> at __webpack_require__ (bootstrap 2b2d9a3e27e783342729:54)
> at Object.<anonymous> (ModalEdit.js:10)
> at __webpack_require__ (bootstrap 2b2d9a3e27e783342729:54)
> at Object.<anonymous> (EditTable.js:28)
> at __webpack_require__ (bootstrap 2b2d9a3e27e783342729:54)

**Comment by travist** [comment]
We will need to assign this to a developer to take a look. We will talk about the priorities of this in our monday morning planning sessions.

**Comment by oneserve** [comment]
Hello @travist any update on this ticket ? Is this issue on your priority list ?

**Comment by wag110894** [comment]
This item is currently on one of our Developers list. We will keep you updated.

**Comment by heather-formio** [comment]
@oneserve  I'm closing this issue for now as it was some time ago. If anything on this thread remains, please reopen or open a new issue with the latest versions referenced.
