### ISSUE TITLE
I need to disable the data, api, conditional and login tabs from field component. how i done this

### ISSUE THREAD

**Issue by ranjanitechleaf** [formio/formio.js#1170]
![formio-shot](https://user-images.githubusercontent.com/49311287/56040374-e197c700-5d53-11e9-9ccc-167ed64f797b.png)

**Comment by randallknutson** [comment]
Here is an example of how to customize the builder http://formio.github.io/formio.js/app/examples/custombuilder.html

You can see it at the bottom where api is disabled.

**Comment by ranjanitechleaf** [comment]
Thank you for your instant reply.

**Comment by ps-from-md** [comment]
Is there a link or article on how to add a custom property tab with custom controls on it?

**Comment by randallknutson** [comment]
That is in the same link. You can add additional fields/tabs or remove fields/tabs in the builder.

**Comment by adnankhan033** [comment]
Hi can we hide  **Display and data** from specific field tab
