### ISSUE TITLE
How can I set Resource Fields data with in a Form while rendering Form

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1175]
I am trying to render a Form it contains some Resource Fields. I have some data in resources so I want to  
populate that resources data with in the Form while rendering Form. So I need to set that resources data when I render Form. Please give me any suggestion to solve this. Thank You.

**Comment by travist** [comment]
You should be able to use Calculated Values to do this... where you would just refer to the resource data within the other fields like so...

```js
value = data.resourceField.data.firstName;
```
