### ISSUE TITLE
Logic for hiding not working.

### ISSUE THREAD

**Issue by mrpavankmr** [formio/formio.js#1176]
Hi,

I am trying to build few components which will be visible on condition basis. 
it seems from properties hiding field is not working.

Also  I am seeing if any field contains Logic. its overriding custom property values like label alignment etc.
you can find one sample json below. If anything I am doing wrong please let me know

{
    "display": "form",
    "components": [
        {
            "label": "Text Field 1",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "textField1",
            "defaultValue": "",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "inputFormat": "plain",
            "encrypted": false,
            "properties": {},
            "tags": [],
            "widget": {
                "type": ""
            },
            "reorder": false,
            "customConditional": "",
            "logic": []
        },
        {
            "label": "Text Field 2",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "textField2",
            "defaultValue": "",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "inputFormat": "plain",
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": [
                {
                    "name": "hiddenfield",
                    "trigger": {
                        "type": "simple",
                        "simple": {
                            "show": true,
                            "when": "textField1",
                            "eq": "abc"
                        }
                    },
                    "actions": [
                        {
                            "name": "hide",
                            "type": "property",
                            "property": {
                                "label": "hidden",
                                "value": "hidden",
                                "type": "boolean"
                            },
                            "state": "true"
                        }
                    ]
                }
            ],
            "widget": {
                "type": ""
            },
            "reorder": false
        },
        {
            "label": "Text Field 3",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "textField3",
            "defaultValue": "",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "inputFormat": "plain",
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": [
                {
                    "name": "set value 1",
                    "trigger": {
                        "type": "simple",
                        "simple": {
                            "show": true,
                            "when": "textField1",
                            "eq": "abc"
                        }
                    },
                    "actions": [
                        {
                            "name": "set value",
                            "type": "value",
                            "value": "value = 'abc1';"
                        }
                    ]
                }
            ],
            "widget": {
                "type": ""
            },
            "reorder": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by heather-formio** [comment]
Closing this issue as it is stale. Please reopen as needed. Thank you!
