### ISSUE TITLE
"Could not find parent component."

### ISSUE THREAD

**Issue by xeon826** [formio/formio.js#1185]
I have the form on localhost. I downloaded the required js locally as well. I do as the example entails 
`function formBuilder() {
  window.onload = function() {
    Formio.builder(document.getElementById('builder'));
  };
}
`
The form renders, I drag and drop an element, I get a console warning that is "Could not find parent compoenent", what am I doing wrong?

**Comment by randallknutson** [comment]
Check out the source code on this page for how to set up the builder: http://formio.github.io/formio.js/app/builder

**Comment by xeon826** [comment]
> Check out the source code on this page for how to set up the builder: http://formio.github.io/formio.js/app/builder

I literally copy paste that page, replacing asset paths, still same error.

**Comment by randallknutson** [comment]
What version of formio.js are you using? This is working for us.

**Comment by xeon826** [comment]
v3.20.0-beta.3

**Comment by heather-formio** [comment]
Closing this issue as this was never reproducible on our end. Please feel free to reopen with more information if any behavior persists.
