### ISSUE TITLE
Duplicate submissions in IndexedDb while using Formio offline plugin

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1189]
Hi, I am using offline plugin and I want to work in offline mode. Rendering form is fine in offline mode through offline plugin but when i make any submission then in IndexedDB storing two  submissions for one submission request and in that data also missing some fields. you can check below snaps.

![image](https://user-images.githubusercontent.com/48546522/56337295-28f1dd80-61c2-11e9-9a45-f86a0e7a3e9a.png)

![image](https://user-images.githubusercontent.com/48546522/56337677-08c31e00-61c4-11e9-9cea-f53fff93bdab.png)

![image](https://user-images.githubusercontent.com/48546522/56337716-40ca6100-61c4-11e9-9b91-6a19a4a8bcc0.png)

While making `plugin.dequeueSubmissions()` it throwing validation error but its a draft submission.

**Project Cache also creating two times first one is empty after that one more with all forms.**

![image](https://user-images.githubusercontent.com/48546522/56338059-095cb400-61c6-11e9-93f0-5c428e40a8d9.png)

**Just using this script in index.html** 
> ```js
> Formio.setProjectUrl('https://abc-dev-gc.form.io'); 
> var plugin = new FormioOfflineProject('https://abc-dev-gc.form.io/');
> Formio.registerPlugin(plugin,"offlinePlugin"); 
> var formio = new Formio('https://abc-dev-gc.form.io/'); 
> formio.loadForms({ params:{type:'form',limit:'100'}});
> ```

**Comment by heather-formio** [comment]
Closing this issue as it is stale.
