### ISSUE TITLE
Using addComponents Method in Custom NestedComponent

### ISSUE THREAD

**Issue by westonwatson** [formio/formio.js#1190]
We're just looking for a good example of nesting/grouping components together so our end users can drag multiple components/elements in one action. We've been playing around with adding a custom component that extends the nestedComponent class (just like the fieldset). But we're having trouble adding multiple child components either manually with `appendChild(this.ce(...` or using the `addComponents` method.

If someone could just point me at an example of grouping components together that would be extremely helpful to us.  I'll close the issue if/when we figure out if it's possible...

--thanks in advance

**Comment by heather-formio** [comment]
Closing this issue as it is stale. FYI In our Enterprise offering there is a concept called "Existing Resource Fields" that groups components within a layout component for dragging onto a form. Please reopen if needed and thank you for using Form.io
