### ISSUE TITLE
select component rendering error

### ISSUE THREAD

**Issue by ayaanraj** [formio/formio.js#1195]
Using the latest version formiojs and select in every component is displayed as shown below and also shows error in the console

![1choice](https://user-images.githubusercontent.com/29095142/56454299-321eae00-636c-11e9-8c4d-769413d33ce7.png)

This also happens in the renderer also.

**Comment by travist** [comment]
latest version being ```3.2.0-beta.3```? or ```3.19.x```?

**Comment by ayaanraj** [comment]
this error occurs from 3.16.0 to higher versions, I have checked the below versions they worked correctly.
In 3.16.0 I see an upgrade in choices.js library to 6.x, I think that update in choices library is causing the error.

**Comment by randallknutson** [comment]
We're not seeing this in our testing. It is probably related to the choices upgrade and could be that you need to update your CSS from the choices.js library. Can you verify the CSS is the latest from them?

**Comment by travist** [comment]
this just means that the formio.css is not included in your project

**Comment by ayaanraj** [comment]
@travist @randallknutson  yes I was missing the styles file, thanks for your help and I'm closing this.
