### ISSUE TITLE
Progress Bar in Wizard

### ISSUE THREAD

**Issue by noman115pk** [formio/formio.js#1198]
Do we have any component like progress bar for wizard which can show user about the completion of steps of the form? Or something like CSS class to show page is visited and completed.
![image](https://user-images.githubusercontent.com/17640825/56576556-18869c00-65e2-11e9-8cbd-ac640816632b.png)

Thanks for the awesome library.

**Comment by randallknutson** [comment]
We don't currently have something like that as part of our default library. You could pretty quickly add something like that by extending the Wizard component and add some CSS classes for any pages below the current page. We would love a pull request adding this functionality through CSS classes to our library.

**Comment by noman115pk** [comment]
@randallknutson PR created.

**Comment by Josephalexantony-aot** [comment]
It will be really nice if a progress bar component is added in form.io. Currently there is nothing like that. and if someone knows how to implement it and connect to anther component, requesting your help.

**Comment by heather-formio** [comment]
This can be accomplished using custom CSS. Also, out of the box using the USWDS template with Form.io, a wizard step indicator with this kind of styling can be used. Also check out how city of San Francisco accomplished a vertical and responsive wizard step indicator here: https://github.com/SFDigitalServices/formio-sfds / https://formio-sfds.herokuapp.com/#form-address
