### ISSUE TITLE
How to remove the widget,placeholders,etc. from display tab

### ISSUE THREAD

**Issue by ranjanitechleaf** [formio/formio.js#1200]
I have attached screenshot 
![fieldremoval](https://user-images.githubusercontent.com/49311287/56588759-9e660f80-6601-11e9-87b7-353ea82efd72.png)

**Comment by randallknutson** [comment]
You can pass an options object to the builder component and set ignore: true on the fields you don't want. Here is an example:

http://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by ranjanitechleaf** [comment]
Hi 
I cannot find the options object, please help us to fix that. 
could you provide one example for an option.

**Comment by noman115pk** [comment]
> Hi
> I cannot find the options object, please help us to fix that.
> could you provide one example for an option.

https://github.com/formio/formio.js/issues/1205#issuecomment-486616694
