### ISSUE TITLE
You can pass an options object to the builder component and set ignore: true on the fields you don't want. Here is an example:

### ISSUE THREAD

**Issue by ranjanitechleaf** [formio/formio.js#1205]
You can pass an options object to the builder component and set ignore: true on the fields you don't want. Here is an example:

http://formio.github.io/formio.js/app/examples/custombuilder.html

_Originally posted by @randallknutson in https://github.com/formio/formio.js/issues/1200#issuecomment-485831686_

Hi
I cannot find the options object, please help us to fix that.
could you provide one example for an option.

**Comment by noman115pk** [comment]
@ranjanitechleaf 
Hi you can pass options object like this.
`Formio.builder(document.getElementById('builder'), { components: formioComponents }, FormBuilder.customForm).then(function (builder) {});`

**FormBuilder.customForm** is an options object which will consist the builder and editForm attributes. EditForm attribute will handle the configuration of that field Modal, ignore: true will hide the field from Modal.
`customForm = {
        builder: {
            ...
        },
        editForm: {
            textfield: [
				{
					key: 'display',
					ignore: false,
					components: [
						{
							key: 'prefix',
							ignore: true
						},
						{
							key: 'suffix',
							ignore: false
						}
					]
				}
		
			]
            }
    }`

Thanks,

**Comment by ranjanitechleaf** [comment]
Thank you soo much , its working fine

**Comment by contona68** [comment]
hi.
i want to ignore any component in custom tab of base component.
 but how?

![image](https://user-images.githubusercontent.com/44703339/71904078-b1624500-317a-11ea-88f5-f82e20c41b9f.png)


i want to ignore  (lable and placeholder ) of  (text field)  component of ( basic Components)   only. 
 thank.

**Comment by marcus-at-localhost** [comment]
@contona68 you want to ignore label and placeholder or all other fields but not label and placeholder? (I believe you need a label field)

```js
customForm = {
        builder: {
            ...
        },
        editForm: {
            textfield: [
				{
					key: 'display', // the tab
					ignore: false,
					components: [ // the fields you want to ignore
						{
							key: 'placeholder',
							ignore: true
						},
					]
				}
		
			],
			select:[
				{
					key: 'data', // the data tab
					ignore: false,
					components: [ // the fields you want to ignore
						{
							key: 'dataSrc',
							ignore: true
						},
					]
				}
            }
    }

```

for all field keys/tabs, look at the source code: https://github.com/formio/formio.js/tree/master/src/components

**Comment by contona68** [comment]
Thanks for your answer

but i want to custom display tab in textFiels component in Basic component of builder   only

not all textField in another .

![image](https://user-images.githubusercontent.com/44703339/71955352-49087780-31fd-11ea-828a-7d364497c317.png)

**Comment by marcus-at-localhost** [comment]
@contona68 could you post a jsfiddle/codepen of your case with your configuration? (Feel free to for from this: https://codepen.io/localhorst/pen/KKwQoNM)
With `editForm.textfield` set, you only affect the textfield component.
What does (3) mean in your illustration? you want to remove that only in the textField component?

![image](https://user-images.githubusercontent.com/1337223/71957787-f1fba600-31ee-11ea-9305-ea620c9490e6.png)

**Comment by contona68** [comment]
<script>
			var custom = {
				title: 'User Fields',
				weight: 10,
				components: {
					firstName: {
						title: 'First Name',
						key: 'firstName',
						icon: 'terminal',
						schema: {
							label: 'First Name',
							type: 'textfield',
							key: 'firstName',
							input: true,
							
						}
					},
					lastName: {
						title: 'Last Name',
						key: 'lastName',
						icon: 'terminal',
						schema: {
							label: 'Last Name',
							type: 'textfield',
							key: 'lastName',
							input: true
						}
					},
					email: {
						title: 'Email',
						key: 'email',
						icon: 'at',
						schema: {
							label: 'Email',
							type: 'email',
							key: 'email',
							input: true
						}
					},
					phoneNumber: {
						title: 'Mobile Phone',
						key: 'mobilePhone',
						icon: 'phone-square',
						schema: {
							label: 'Mobile Phone',
							type: 'phoneNumber',
							key: 'mobilePhone',
							input: true
						}
					}
				}
			};
		
			window.onload = function() {
				Formio.builder(document.getElementById('builder'), {}, {
					builder: {
						basic: false,
						advanced: false,
						data: false,
						layout: {
							components: {
								table: false
							}
						},
						premium: false,
						customBasic: {
							title: 'Basic Components',
							default: true,
							weight: 0,
							components: {
								videoEditor: true,
								checkmatrix: true,
								textfield: true,
								textarea: true,
								email: true,
								phoneNumber: true
							}
						},
						custom: custom
					},
					editForm: {
						textfield: [
							{
								key: "api",
								ignore: true,
							},
							{
								key: "display",
								ignore: false,
								components: [
									{
										key: "label",
										ignore: true
									},
									{
										key: "tooltip",
										ignore: true
									},
									{
										key: "widget",
										ignore: true
									}
								]
							}      
						]
					
				    }
				}).then(function(builder) {
					builder.on('change', function(schema) {
						console.log(schema)
					});
					builder.on('saveComponent', function() {
						console.log(builder.schema);
					});
				});
			};
		</script>

i create custom cumponet and used textFeild component in it .
if i ignore textfield all component that used textfield type  be ignore.
but I want to ignore textfield  in my cutomed  in display tab only not all.

**Comment by marcus-at-localhost** [comment]
@contona68 you mean that custom components like firstName, lastName that are based on textfield components are affected by `editForm.textfield` definitions as well?

**Comment by contona68** [comment]
yes I want to ignore and customation display tab in firstName, lastName  only.

**Comment by marcus-at-localhost** [comment]
You are right, custom fields based on another field seem to inherit the properties.
https://codepen.io/localhorst/pen/qBExMqz

I'm not sure if this is a bug, though...

**Comment by contona68** [comment]
Anyway  Thank you.

**Comment by gape16** [comment]
Hi ! 
I need the same thing but your example doesn't work. Widget input is not ignored. How can we do that ?

Thanks

**Comment by heather-formio** [comment]
Closing as this is stale, please feel free to reopen and thank you for everyone's contributions to this discussion.
