### ISSUE TITLE
How do I remove a component from inside a Data Grid?

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#1207]
Hi,

I have a Data Grid with a component in it. I want to remove this component from the Data Grid and put it somewhere else. But dragging the component just drags the entire Data Grid.

Or I want to change the order of the components in the Data Grid by dragging one component to the "Drop here" area. Same problem.

Is this possible to do? If it is not, would you be able to add this functionality?

Thanks

![image](https://user-images.githubusercontent.com/24515980/56775235-8234bf00-6809-11e9-9534-cadaed15163a.png)

**Comment by travist** [comment]
This is a known issue. Seems it may be related to the dragula library we are using. It will get added to our backlog, but honestly speaking, this would be fixed sooner if someone from the community chipped in to fix it.

**Comment by heather-formio** [comment]
This is resolved, tested using v4.14.8.
