### ISSUE TITLE
Component.addClass() adds 'null' to class attribute

### ISSUE THREAD

**Issue by sebastianhaberey** [formio/formio.js#1209]
Example: ```component.addClass('selected')``` results in ```class='null selected'``` on the HTML element.

 I observed this on an older version of formio (3.4.4), but I believe it would be the same in the current code:

```
const classes = element.getAttribute('class');
if (!classes?.includes(className)) {
  element.setAttribute('class', `${classes} ${className}`);
}
```

**Comment by travist** [comment]
Please feel free to fix and provide a pull request with the fix.

Thanks for your contribution.

**Comment by sebastianhaberey** [comment]
Hi Travis,

I believe I fixed this issue plus one or two other issues with `addClass()` / `removeClass()` that I discovered during testing. Have a look at the pull request, if you find the time.

**Comment by randallknutson** [comment]
With tests! Thank you!

**Comment by sebastianhaberey** [comment]
No worries 😄 

BTW I found another [small issue](https://github.com/formio/formio.js/issues/1241) while testing and I've made a pull request for that too. It might be useful, if you guys observe the same behavior on your end.

**Comment by heather-formio** [comment]
Thank you for the fixes, closing this issue.
