### ISSUE TITLE
How do I customize the CKEditor Toolbar and Upload Respository

### ISSUE THREAD

**Issue by ps-from-md** [formio/formio.js#1210]
I would like to remove some of the toolbar options in the Content component as well as configure the image upload to work with a remote location.  How would I go about doing this?

**Comment by randallknutson** [comment]
The content component is a build time component which will display as HTML on the actual form. You probably want the Textarea component with a wysiwyg editor. You can use the "URL" option for file upload and set up a file service to accept the files. https://help.form.io/userguide/form-components/#upload-url
