### ISSUE TITLE
Custom Component from Example - Adding Javascript for AutoComplete

### ISSUE THREAD

**Issue by du8die** [formio/formio.js#1212]
I'm following the directions at this link for creating/extending a custom component.

http://formio.github.io/formio.js/app/examples/customcomponent.html

I've gotten this working and am able to create a custom textbox. Using Vanilla JS, how would I attach the AutoComplete code? I've looked through https://formio.github.io/formio.js/docs/file/src/components/address/Address.js.html but am unable to figure out how it relates to the custom example.

Any suggestions / direction would be greatly helpful!

**Comment by travist** [comment]
A better example of "autocomplete" is what we do with the Select component. We have not made this part of the "base" component so you may need to transfer what you see here to the base component.

https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L348
