### ISSUE TITLE
"ace" editor conflict.

### ISSUE THREAD

**Issue by du8die** [formio/formio.js#1213]
I am using a Bootstrap theme that has a built-in Javascript component called "ace."  Formio uses an "ace" editor, which when ever I attempt to use the textarea field (in a form or in an EditForm) - causes an error.

Is there any way to make the default editor something else?

**Comment by travist** [comment]
The ace editor is really used for the component editor which we do require to be ace since this allows for javascript entry + json entry.

**Comment by du8die** [comment]
Is there no option for this to be a plain textbox? Must it be an editor? I really want to use formio in my project - but can't - and I can't change the name of the ace component in my theme. Just looking for options.

Thanks!

**Comment by du8die** [comment]
So - I figured out a work-around. I put the editor in a iFrame - so it isn't exposed to the theme component. Works like a champ. Would be nice if there was a way to disable the ace component. 

Thanks!

**Comment by travist** [comment]
We would welcome a change to our renderer to provide an option to disable the ace editor for the form builder. If you would like to contribute a change back, please submit a pull request.

**Comment by du8die** [comment]
Gosh - I wouldn't know where to begin. I'll take a look and see if I can figure it out with out screwing up things too badly!

Thanks
