### ISSUE TITLE
Calling `.render()` on a form that already exists causes it to become hidden

### ISSUE THREAD

**Issue by colons** [formio/formio.js#1214]
There's a demonstration of this at <https://jsfiddle.net/op1ajzu9/1/>. I don't understand the intention of this, but it does appear to be deliberate; `Webform.render()` calls `this.showElement(false)`.

This seems to have been introduced [here](https://github.com/formio/formio.js/commit/879cee9344f62f4de2f1efdb7e93ffeffcac86c9#diff-4e611624b7b88a37f6fce2ab01f515ac)

**Comment by travist** [comment]
I believe the intent of this is to hide the form while it renders so it does not glitch. What may be happening here is that something is keeping it from calling the final showElement(true) when it is done. We would need to investigate why that is unless you would like to take a stab and debugging this.

**Comment by colons** [comment]
I'm super not confident testing this, but I _think_ what I'd do would be but the `showElement(false)` before what is currently the first line of the `render()` function, and then put `showElement(true)` in the `then()` block? Given the `isBuilt = true`, I'd assume that's what's called when the render is complete. Super not sure, though; idk if there's a better event to hook into for the completion of rendering.

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by colons** [comment]
This is not a super high priority for us; I've just moved to using `.redraw()` instead, and extended our tests to cover the issue we were running into. It seems to be working okay for now, although this behaviour is still super weird.

**Comment by randallknutson** [comment]
redraw() is probably a better way of doing it. This already works very differently in the 4.x branch which we're hoping to get released soon. If you've got a workaround for now we will just move forward and make sure this is correct in 4.x

**Comment by wag110894** [comment]
Redraw has been added to our Core 4x renderer.
