### ISSUE TITLE
Submit button should not be visible in readOnly mode

### ISSUE THREAD

**Issue by mrcportillo** [formio/formio.js#1216]
Even with the `readOnly` prop with a true value, the form renders with the submit button visible.
This happens for all the forms with template display as `form`.

**Comment by travist** [comment]
It should be visible but disabled. Will you confirm if it is disabled? If you want it to not be visible, then you can add a conditional that checks for the readOnly property.

**Comment by mrcportillo** [comment]
@travist yes, it's visible and disabled. Which should be the option object to render the form without the submit button.

**Comment by travist** [comment]
We don't have an option that does this but feel free to contribute such an option. You may also just be able to use the conditional settings of that component to now show when the form is not valid.

**Comment by mrcportillo** [comment]
Great, I'll.

**Comment by franke-mc** [comment]
You can try something like this, in Button Component, Conditional, Advanced -> 
```
show = !!((instance.root.options.readOnly !== true)
       && (instance._disabled !== true)
       && (submission.readOnly !== true))
```
