### ISSUE TITLE
Hide submit button on Wizard Modeler

### ISSUE THREAD

**Issue by eldiegos** [formio/formio.js#1218]
### There is no option to hide the submit button on Wizard Modeler. **It always appears.**

Here you can see the Modeler
![image](https://user-images.githubusercontent.com/47030141/56998528-df36c900-6bab-11e9-8f0a-0564ac68f38a.png)

Here you can see the Rendered
![image](https://user-images.githubusercontent.com/47030141/56998405-74858d80-6bab-11e9-9ea3-d2bc74e6098a.png)

**Comment by eldiegos** [comment]
https://github.com/formio/formio.js/issues/1218

**Comment by wag110894** [comment]
This is how it is currently designed. We do allow pull requests if you wish to add some customization to the wizard buttons.

**Comment by eldiegos** [comment]
The project code is very complex. I found this solution.

formio.on('render', function() {
    var elements = document.getElementsByClassName("btn-wizard-nav-submit");
	  if(elements.length > 0){
		  elements[0].classList.add('invisible')
	 }
  });
