### ISSUE TITLE
Tabs issues

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#1219]
Deleting the middle tab deletes components in the last tab, doesn't delete components in the deleted tab, and components get moved to later tabs.

Also, Moving a tab's order seems to copy components from other tabs.

[Video of both issues](https://github.com/formio/formio.js/files/3133649/Formio.bug.tabs.zip)

**Comment by wag110894** [comment]
Hello David, 

Thanks for reaching out. 

We have created tickets for both of these issues (Issue #1 FOR-2237 & Issue #2  FOR-2238). We will discuss level of priority of both of these issues on Monday. 

Please let me know if you have any further questions or concerns.

Thanks.

**Comment by wag110894** [comment]
Hello David, 

Thank you for your patience regarding these issues.  Here is an update regarding item FOR-2237. 

This issue is resolved in the 4x branch of our Core Renderer.  

Have added item FOR-2238 to one of our developer's list.  We will notify you once it is fixed in our 4x branch.

Thanks.

**Comment by Davidvlv** [comment]
Thanks Will,

What timeframe do you have for releasing 4.0 as a full release?

**Comment by wag110894** [comment]
Hello David, 

Our current timeframe for releasing 4x is end of the second quarter.
We will keep you updated.

Thanks.

**Comment by heather-formio** [comment]
4.14.x is the current version, closing issue.
