### ISSUE TITLE
Save as Draft not working

### ISSUE THREAD

**Issue by Abd-Zinghr** [formio/formio.js#1223]
When I take Button component and take Action as 'Save in State' & Submission State  as 'draft'.
It is written in that 'draft' keyword will skip the validation of the page but it is not working and still firing validation.

**Comment by randallknutson** [comment]
This is working for us as we test it. Can you verify that the Submission State is "draft" (all lowercase)? Also, can you check if the submission is going to the server or not? The frontend and backend should skip the validation.

**Comment by abd-madness** [comment]
@randallknutson  I am facing this issue in my form IO CSV download , when I download CSV the header of all the columns are coming as API key of the Component in form IO.
I want to to download the header as it is showing up in the view data tab.

Waiting for your revert on the same asap.
Thank you.

**Comment by kristhiantiu** [comment]
same here, i can not see the `state` field on the data for the open source.
when i checked the commercial one they have this field but for the open source there is none.

is this only gonna work for the commercial form.io?

**Comment by moeVdm** [comment]
Any update on this issue? Save draft is not working at all with the open source version. Validations are still done even though we use the save draft functionality.

In the commercial version, we can see that by POSTing a submission with `state draft` without all required fields, it skips the validations and we receive a response with the `state: 'draft'`, as @kristhiantiu mentioned.

**Comment by randallknutson** [comment]
Unfortunately save as draft is currently only available in the commercial server.

**Comment by bobslee** [comment]
"Save as draft", with the JS client, worked fine until version **3.27.3**.
So I gues this is a bug or is it **removed** since version **4.x** ?

**Comment by travist** [comment]
The front end should support the "saveDraft" flag where it would skip validation. However, the server components of save as draft are only on Enterprise server as @randallknutson mentioned (and has always been the case). If the saveDraft functionality was broken in the 4.x branch of the front end elements, then we will definitely put that on our list to resolve. Let us know.

**Comment by bobslee** [comment]
Just found a workaround:

Put following API key/value in the "Save as draft" button component:
- key: submit
- value: false

I cross my fingers, this keeps on working.

**Comment by Home-Based** [comment]
Facing the same issue while setting up a "Save as Draft" button, I confirm this is not working with Formio.js 4.14.1-rc7.
Work around proposed by @bobslee doesn't work either.

Any development on this issue since 2019 ?

Best regards,
Seb

**Comment by Home-Based** [comment]
Just found another workaround: just give "saveDraft" as API property name. 

The problem with this is that you can just do it once, as the component's name has to be unique. But for one "save as draft" button, it's enough.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
