### ISSUE TITLE
form.on 'error'  never fires

### ISSUE THREAD

**Issue by ctchisholm** [formio/formio.js#1224]
I'm trying to get a very basic form rendered, and I want to know when the form is invalid.  I expected to be able to use form.on('error', ()=>{}) to do something when the form is invalid, but this event is never fired.  Is 'error' supposed to be fired when one of the components is set to 'invalid'?

Here's a plunker.  It's just the basic form with some validation.  OnChange is fired, OnError never is:

https://plnkr.co/edit/4vsG8iOQAkGDSpR1zVSF?p=preview

**Comment by randallknutson** [comment]
If you use the form.on('change', () => {}) event and inside of it, one of the parameters is whether or not the form is valid. I think it is called isValid.

**Comment by ctchisholm** [comment]
I'm actually using the angular renderer in conjunction with this, and was able to find a method that I can manually call to get the current validation state: 
app.html:
    <formio #form *ngIf='formJson' 
    [form]='formJson' 
    (change)='onChange()'"></formio>

app.ts:
onChange() {
    this.formValid = this.form.formio.checkData();
}

**Comment by teichsta** [comment]
@ctchisholm thanks for sharing your solution (some time ago). My question is: how did you manage to get access to `this.form` as you seem to just render the form using the angular component `<formio ...` ?

**Comment by ctchisholm** [comment]
Hi @teichsta, I actually stopped using the angular component, and instead used the regular formio library in my own angular component.  I use Formio.createForm in ngOnInit method of my component:

`Formio.createForm(document.getElementById(this.DIV_ID), formJson).then((form) => {
                  // restore the old values
                  form.submission = {
                    data: submissionJson
                  };
                  this.form = form;
                  this.setupFormOnChange(form);
                  this.formLoaded = true;
                  this.context.setShowLoading(false);
                });`

I hope this helps, if not feel free to reach out to me directly, or respond here and I'll get back to you.

**Comment by teichsta** [comment]
i am currently trying to solve something similar than at that days. I simply want to get notified (on form not component level) if the form is valid or not. Subscribing to `(change)` sends only change events on component level which i now have to take track of to find out whether the whole form is valid or not … which seem to be a quite huge overhead and feels to be wrong as knowing if the form is valid should be a solved problem ;-)

**Comment by ctchisholm** [comment]
There is another option as well..  as long as you have a reference to the form, you can call the methods form.checkData() or form.checkValidity().  This is helpful if you want to check for errors when trying to save or something like that, or during some other event.  If you want to have a variable that keeps track of the validity of the form as changes happen, then I think the (change) method is best.  You can always call checkData or checkValidity in your (change) handler as well.

**Comment by GMacAussie** [comment]
From memory the formio instance (from the createForm() call) has an errors accessor which returns an array of errors. Basically it is a smoosh of all the component errors. Works a little differently for wizards.

We check its length on the change event itself to keep track of overall form validity. You can trigger something in that change event if you need overall form validation management (example new error count goes to/from 0).
