### ISSUE TITLE
column component defaulting to input true

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#1225]
Noticed a change when we updated to 3.20 that column components are defaulting to input elements. Was this by design, or is there a bug?

**Comment by randallknutson** [comment]
I don't think the column component is supposed to have any input elements by default and we haven't seen anything like you describe yet. Can you give some more details?

**Comment by ProteanHub** [comment]
Sure, very simple example (using v3.20.6) using the form builder:
Drag a column component in, then saving gives me this in the JSON:

`{
  "components": [
    {
      "input": true,
      "label": "Submit",
      "tableView": false,
      "key": "submit",
      "theme": "primary",
      "type": "button",
      "$$hashKey": "object:15"
    },
    {
      "label": "Columns",
      "columns": [
        {
          "components": [],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "type": "column",
          "hideOnChildrenHidden": false,
          "input": true,
          "key": "column1",
          "tableView": true,
          "label": ""
        },
        {
          "components": [],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "type": "column",
          "hideOnChildrenHidden": false,
          "input": true,
          "key": "column2",
          "tableView": true,
          "label": ""
        }
      ],
      "mask": false,
      "tableView": false,
      "alwaysEnabled": false,
      "type": "columns",
      "input": false,
      "key": "columns2",
      "conditional": {
        "show": "",
        "when": "",
        "json": ""
      },
      "reorder": false,
      "properties": {},
      "customConditional": "",
      "logic": []
    }
  ],
  "display": "form",
  "page": 0
}`

**Comment by ProteanHub** [comment]
So doing some further testing, it looks like if the outer columns component is input: false, it ignores the fact that the individual columns are set as input: true. In other words, we wanted to make sure the cells would not come in as data points despite being set as an input element.

**Comment by randallknutson** [comment]
The input flag is a bit weird. It originally meant one thing and then changed to another. I would leave it however the form builder sets it and just let the renderer handle it accordingly.

**Comment by ProteanHub** [comment]
Fair enough, thanks for the reply Randall.
