### ISSUE TITLE
Datagrid: if number of visible components does not change, visible columns are not refreshed

### ISSUE THREAD

**Issue by diegodlh** [formio/formio.js#1227]
In a datagrid you may have more than one conditional component. For example, you may have two components A & B conditional on Field X. Say A is set to show if X == 1, while B is set to show if X==2. Then, for both values of X (1 and 2) the number of visible components in the datagrid will be the same = 1. As the number of visible components in the datagrid doesn't change when X is changed, the datagrid columns are not refreshed.
In other words: I start with an empty X. Then the Datagrid doesn't show either A or B. Then I set X to 1. Now the number of visible components changes to 1 (A shows, B doesn't), and the Datagrid refreshes accordingly. However, if I now change B to 2, as the number of visible components doesn't change (it remains 1), the Datagrid is not refreshed and B remains hidden.
https://github.com/formio/formio.js/blob/d7669033c79de2d9c8f53930c7354db056c61fda/src/components/datagrid/DataGrid.js#L437

**Comment by wag110894** [comment]
Hello,
This issue is resolved in our 4x branch of our core renderer.  

https://github.com/formio/formio.js/tree/4.x
