### ISSUE TITLE
when I download CSV file Header are coming as API key used in FORM.IO

### ISSUE THREAD

**Issue by Abd-Zinghr** [formio/formio.js#1230]
I am facing this issue in my form IO CSV download , when I download CSV the header of all the columns are coming as API key of the Component in form IO.
I want to to download the header as it is showing up in the view data tab.

Waiting for your revert on the same asap.
Thank you.

**Comment by abd-madness** [comment]
@travist  any update on above mentioned issue ???

**Comment by randallknutson** [comment]
I don't think we plan on changing this. CSV downloads are meant to be data dumps that you can then change however you want to change them. We use those headers as keys to the data and attempting to use titles is difficult in this scenario.
