### ISSUE TITLE
Contribution: New component "resourcetree"

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1232]
We would like to offer a new "resourcetree" component for merging into formio.js. Is there any interest on your side? (Before we prepare a formal pull request against the latest version, it would be good to get a broad picture of the road ahead for this.)

The idea is that for a specific resource representing tree nodes, this new component can display the tree of resources, and record multiple selections of leaves and inner nodes. Example use cases are e.g. selection of
- geographic areas of interest, or
- topics of interest.

The source code can be found here:
https://github.com/darabi/formio.js/commits/master/src/components/resourcetree

Here is an example:
![Formio-ResourceTree-Example-Geo](https://user-images.githubusercontent.com/46748541/57307556-13971180-70e5-11e9-97c7-e3d7979d5ff6.png)
To create this tree, the component can be configured with a URL that serves something like the following JSON expression:
```
{"_id":"000000000000000000000810",
 "data":{
   "name":"Deutschland",
   "children":[
     {"_id":"000000000000000000000919","data":{"name":"Deutschland gesamt"}},
     {"_id":"000000000000000000000865",
      "data":{
        "name":"Norddeutschland",
        "children":[
          {"_id":"000000000000000000000867","data":{"name":"Hannover"}}
        ]}},
     {"_id":"000000000000000000000873",
      "data":{
        "name":"Nordrhein-Westfalen",
        "children":[
          {"_id":"000000000000000000000874","data":{"name":"Bonn"}}
        ]}},
     {"_id":"000000000000000000000880",
      "data":{
        "name":"Hessen, Rheinland-Pfalz, Saarland",
        "children":[
          {"_id":"000000000000000000000881","data":{"name":"Darmstadt"}},
          {"_id":"000000000000000000000888","data":{"name":"Frankfurt"}}
        ]}},
     {"_id":"000000000000000000000891",
      "data":
      {"name":"Baden-W\u00FCrttemberg",
       "children":[
         {"_id":"000000000000000000000893","data":{"name":"Karlsruhe"}},
         {"_id":"000000000000000000000894","data":{"name":"Stuttgart"}}
       ]}},
     {"_id":"000000000000000000000899",
      "data":{
        "name":"Bayern",
        "children":[
          {"_id":"000000000000000000000901","data":{"name":"Niederbayern"}},
          {"_id":"000000000000000000000902","data":{"name":"Oberbayern"}}
        ]}},
     {"_id":"000000000000000000000909",
      "data":{
        "name":"Berlin, Mecklenburg-Vorpommern, Brandenburg, Sachsen-Anhalt",
        "children":[
          {"_id":"000000000000000000000910","data":{"name":"Berlin"}},
          {"_id":"000000000000000000000911","data":{"name":"Brandenburg"}}
        ]}},
     {"_id":"000000000000000000000914",
      "data":{
        "name":"Th\u00FCringen, Sachsen",
        "children":[
          {"_id":"000000000000000000000915","data":{"name":"Chemnitz"}},
          {"_id":"000000000000000000000916","data":{"name":"Dresden"}},
          {"_id":"000000000000000000000917","data":{"name":"Leipzig"}},
          {"_id":"000000000000000000000918","data":{"name":"Th\u00FCringen"}}
        ]}}
   ]}}
```
(Eventually, the formio API server could be extended to generate these tree structures on the fly, e.g. via a new URL parameter like `expand.recursively=children`, but this is out of scope for this contribution.)

**Comment by randallknutson** [comment]
I'm guessing you have seen our Tree component already? https://github.com/formio/formio.js/tree/master/src/components/tree

If so, how would this differ from that?

**Comment by franke-mc** [comment]
Yes, we've seen it, but since that component does not appear in the builder right now, it's not easy to understand what exactly it's supposed to do.

resourcetree, like resource, derives from Select (not NestedForm), with a list of choices as selection result:
![Formio-ResourceTree-Example-Geo-Choices](https://user-images.githubusercontent.com/46748541/57383046-61c41780-71ae-11e9-9d19-87f02fc78968.png)

The configuration UI in the builder allows to customize the behaviour:
![Formio-ResourceTree-Builder](https://user-images.githubusercontent.com/46748541/57383166-9b951e00-71ae-11e9-9835-aaec3770239f.png)

**Comment by travist** [comment]
My only hesitation is that the URL format of the data is something that is not provided by our API's and would require a lot of work for people to actually be able to use this. I really like this component, but we may need to think about how to get the data input as a supported feature set first.

**Comment by franke-mc** [comment]
Currently, we are not using a fully generic dynamic solution for the tree computation, but have about ~100 lines of code to compute it once for each of our specific use cases and cache them until the next server startup.

**Comment by randallknutson** [comment]
If you'd like to investigate the Tree component, you can use https://beta.form.io

**Comment by franke-mc** [comment]
Sorry, but I don't see any "Tree" component there. Am I overlooking something?

**Comment by randallknutson** [comment]
Sorry for that. You are right. It is in code only at the moment.

**Comment by heather-formio** [comment]
Please feel free to re-open at any time. Closing.
