### ISSUE TITLE
power-assert output not shown when running formio.js unit tests with karma

### ISSUE THREAD

**Issue by sebastianhaberey** [formio/formio.js#1241]
While unit testing the formio.js framework, I discovered that the power-assert output is not shown when the tests are run via karma (tested with Chrome or ChromeHeadless). It should actually output helpful info such as this when a test fails:

```
  assert(ary.indexOf(zero) === two)
         |   |       |     |   |
         |   |       |     |   2
         |   -1      0     false
         [1,2,3]
```

If you guys observe the same symptom on your side, you might try the fix I used locally (see [pull request](https://github.com/formio/formio.js/pull/1242)).

**Comment by randallknutson** [comment]
Thanks! We've experienced issues similarly but haven't had a chance to look into the root cause.
