### ISSUE TITLE
Tabs content validation errors are not displayed on submit

### ISSUE THREAD

**Issue by Sipaha** [formio/formio.js#1249]
https://github.com/formio/formio.js/blob/master/src/components/tabs/Tabs.js

In function checkValidity on line 236 component fill validityTabs array to return it later in getAllComponents (line 209), but component.destroy() (line 238) cleans all saved components and we are losing all errors.

This issue can be reproduced here http://jsfiddle.net/v38du9y1/1145/
You can press Submit button and see that error about mandatory field is missing.

It will be great if you fix it.
Thanks

**Comment by Sipaha** [comment]
My attempts to fix the component with minor changes was failed and I changed the component to render all children on create without destroing it on tab switch. Should I make pull request with this fix or it is a bad solution for Formio.js?

**Comment by randallknutson** [comment]
Feel free to make a pull request if you have changes that work. We love community provided fixes.

What you are describing sounds like something that is fixed in the 4.x branch which is currently in the beta process of release. We create all the components in the tabs regardless of if they are visible or not. I'd recommend testing out 4.0.0-beta.33 and see if it works better for you.

**Comment by ProteanHub** [comment]
@Sipaha We would be interested in what you did to fix the tab component. We are not quite brave enough to try v4 just yet, but need the tabs component to work.

**Comment by Sipaha** [comment]
> I'd recommend testing out 4.0.0-beta.33 and see if it works better for you.
@randallknutson will be 4.0.0 released soon? Does it have backward compatibility with form configs from 3.*?
Thanks

**Comment by randallknutson** [comment]
4.0.0 is nearing release. The main holdback at the moment is full pdf support and squashing the remaining bugs which is getting a lot of attention at the moment. It will be backwards compatible with form configs.

**Comment by ProteanHub** [comment]
Thanks @Sipaha the bug fix is working well!

**Comment by Sipaha** [comment]
> 4.0.0 is nearing release.
>It will be backwards compatible with form configs.

@randallknutson great to hear! Thank you and your team for the awesome library!
@ProteanHub you're welcome.

**Comment by ASmeha** [comment]
Thank you @Sipaha for the fix!

**Comment by bohan** [comment]
Thanks @Sipaha 
Created a [gist](https://gist.github.com/bohan/8e232851f13853ba5932f1a1247cfb3a) for the modified Tabs.js by @Sipaha
Just in case anyone wants it quickly
