### ISSUE TITLE
Disable submit in form builder

### ISSUE THREAD

**Issue by ssrini** [formio/formio.js#1250]
When the form builder is embedded using the Angular library/tag, the Submit button is still enabled and shows a Submission Success/failure message on click.

In the form builder screen, can the submit button be disabled?  I see that the demo on https://codepen.io/travist/pen/xVyMjo has it disabled and I need something similar.

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.
