### ISSUE TITLE
Inline Forms?

### ISSUE THREAD

**Issue by du8die** [formio/formio.js#1257]
Hello,

I'm wondering if the formio.js library has any functionality for inline forms. For example...

`<p>This is a paragraph. In order for it to work, please type "yes" in the textbox: <input type="text">. Thanks for your time.`

Thanks!

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out! It sounds like you are interested in adding either our HTML element or our Content component to your form. Below is documentation for both. 
https://help.form.io/userguide/form-components/#html-element
https://help.form.io/userguide/form-components/#content-1

Here is a quick screencast of both so you can see how both are set up as well as you can use conditional logic for them to appear.
https://www.screencast.com/t/fJSUlZ4q

Hope this helps.

Please let us know if you have any further questions or concerns.

Thanks,

**Comment by du8die** [comment]
Close.

I am wanting to embed form elements inside the HTML or Content element.

So - a sentence - with a textbox in the middle of it asking for input. Your screencast pulled the input element out of the HTML.

Is that something that can be supported?  

Thanks

**Comment by wag110894** [comment]
Hello,

Thanks for clarifying the feature you would like to see. We will discuss internally and let you know.

Thanks.

**Comment by JamesRArroyo** [comment]
@wag110894 any update on this or would I need to create a custom component?

**Comment by randallknutson** [comment]
While the content and html element components allow you to create any type of html input, you can't have input elements that are connected to the form. You can create them but they will be input elements on the page that don't do anything specific with form.io. If you need to create a custom component with functionality in the form that collects data, you will need to create a custom component.

**Comment by lane-formio** [comment]
There is now a process that you can go through to add some inline functionality to individual forms and components.

1. Navigate to the form you wish to add inline functionality
2. Go to Form Settings  (to the right of "Launch")
3. Paste the following code snippet into "Form Controller":
`(function() {
  var componentTemplate = Formio.Templates.templates.bootstrap.component.form;
  Formio.Templates.templates.bootstrap.component.form = function(ctx) {
    var template = componentTemplate(ctx);
    return template.replace('styles=', 'style=');
  };
  return false;
})();`
4. Make sure to save settings
5. Edit the json of any components you wish to make "inline" with one another and add the following snippet to the json schema:
`"style": {
    "display": "inline-block"
  },`
