### ISSUE TITLE
Edit Form is not working on Custom Component

### ISSUE THREAD

**Issue by rohitsahu365** [formio/formio.js#1267]
HI FormIo Team,
I am new to FormIo , and having formIo in my application on Angular7 , I am having a form Builder, inside that I am using a  custom component. But when I am trying to edit the form from Form Manager I am not able to retrieve the custom component only the basic component is available there. So on edit how can achieve the custom component with selected form.

The HTML what I am using is
<form-builder *ngIf="formReady"  id="builder" [form]="form" #builder></form-builder>

My Form Builder
Formio.builder(document.getElementById('builder'), {}, {
  builder: {
    basic: false,
    advanced: false,
    data: false,
    customBasic: {
      title: 'Basic Components',
      default: true,
      weight: 0,
      components: {
        textfield: true,
        textarea: true,
        email: true,
        phoneNumber: true
      }
    },
    custom: {
      title: 'User Fields',
      weight: 10,
      components: {
        firstName: {
          title: 'First Name',
          key: 'firstName',
          icon: 'fa fa-terminal',
          schema: {
            label: 'First Name',
            type: 'textfield',
            key: 'firstName',
            input: true
                }
      }
    },
    layout: {
      components: {
        table: false
      }
    }
  },
  editForm: {
    textfield: [
      {
        key: 'api',
        ignore: true
      }        
    ]
  }
}).then(function(builder) {
  builder.on('saveComponent', function() {
    console.log(builder.schema);
  });
});

Using this code to EditForm
 initBuilder(editing) {
    if (editing) {
      this.loading = true;
      this.ref.detectChanges();
      this.editMode = true;
      return this.service.loadForm().then(form => {
        this.form = form;
        this.formTitle.nativeElement.value = form.title;
        this.formType.nativeElement.value = form.display || 'form';
        this.loading = false;
        this.formReady = true;
        this.ref.detectChanges();
        return true;
      }).catch(err => {
        this.alerts.setAlert({type: 'danger', message: (err.message || err)});
        this.loading = false;
        this.formReady = true;
      });
    } else {
      this.formReady = true;
      return Promise.resolve(true);
    }
  }

**Comment by heather-formio** [comment]
Closing this as it is stale, please feel free to reopen at any time. Thank you!
