### ISSUE TITLE
File upload Error - Failed to execute 'replaceChild' on 'Node'

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#1271]
i have a simple form with file uploader component with api nam "fileComp"

i call below code in custom button
```
form.getComponent("fileComp").setValue([]);

```

after that when trying to submit the form i get the error 
Failed to execute 'replaceChild' on 'Node'

**Comment by travist** [comment]
Is the file component configured to use the "multiple" flag? This would make the value accept an array of file objects. Otherwise, I would assume it would be this.

```
form.getComponent('fileComp').setValue({});
```

**Comment by randallknutson** [comment]
The file component value is always an array so that should work correctly. It is possible that setValue is getting called too early (before the component is getting rendered). If you want to default a component to empty, you can do this with custom default value.

**Comment by heather-formio** [comment]
Closing this as it is stale, please feel free to reopen at any time. Thank you!
