### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set property 'count' of undefined

### ISSUE THREAD

**Issue by karamanos** [formio/formio.js#1275]
I have upgraded from release 3.10.0 to the current release (3.20.17).
When I open a form I get two errors:
1. TypeError: Cannot read property 'initialData' of null at classiceditor.js:204 (there is already an open ticket for it)
2. Uncaught (in promise) TypeError: Cannot set property 'count' of undefined
    at Function.value (formio.full.min.js:18)
    at Function.value (formio.full.min.js:18)
    at t.value (formio.full.min.js:18)
    at t.value (formio.full.min.js:18)
    at formio.full.min.js:18
    at Array.forEach (<anonymous>)
    at t.value (formio.full.min.js:18)
    at t.value (formio.full.min.js:18)
    at t.value (formio.full.min.js:18)
    at t.value (formio.full.min.js:18)
Any ideas regarding the second problem?

**Comment by travist** [comment]
We will investigate. Thanks.

**Comment by jhen1422** [comment]
Can you please let us know if you are still experiencing an issue for both #1 and #2 on your report list. Thank you!

**Comment by karamanos** [comment]
Hi, regarding issue #1, this is the same as issue #1270 which was solved with a new release.
Regarding issue 2, the problem has not appeared for some time now. A change we did on our part is that we moved away from the content component and started using more the HTML element component. I do not know if that error was related with the content component as well.
Many thanks.
