### ISSUE TITLE
refreshOn:'data' causes form element to not be editable.

### ISSUE THREAD

**Issue by du8die** [formio/formio.js#1276]
Good Morning,

Been looking into this one. 

In the FormBuilder, when one sets an element's refreshOn property to 'Any Change' (refreshOn:'data'), the element can no longer be edited. The toolbar does not appear.

Reproduced on the samples (http://formio.github.io/formio.js/app/examples/custombuilder.html).

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out!
We had added this item to one of our developers list. We will let you know once this issue has been resolved.
