### ISSUE TITLE
Adding width to every component field

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#1280]
Hi,

Is there any plan to add width field to component when the label position is top or bottom so that input box / select wont take 100% after rendering form.

![image](https://user-images.githubusercontent.com/7270651/58104043-ac5b8000-7c01-11e9-88c0-462ed6eb619b.png)

![image](https://user-images.githubusercontent.com/7270651/58104096-c5fcc780-7c01-11e9-9cc2-48297b54c1d9.png)

Thanks,
Sriram.

**Comment by randallknutson** [comment]
This is following the design styles of bootstrap and responsive design. The width of components is determined by the width of the container and you use columns to stack multiple items in a row. This allows the forms to look good on both the desktop, tablet and on mobile. 

We aren't planning on adding a width for this reason. When setting it, the width would look good for one specified device but would be incorrect for the others. 

In our new 4.x version of the renderer, we are adding templating support where you can change the html of our components or specify bootstrap 3, bootstrap 4, semantic ui or material ui for how you want it to render. It is also possible to completely override the templates as well and add your own CSS to change the look and feel however you'd like.

**Comment by sriram275** [comment]
That will be really helpful since there is no way of customizing html and css from builder. What is the release timeline for 4.x ?

**Comment by wag110894** [comment]
We are hoping to have our 4x renderer released at the end of the 2nd quarter.

**Comment by heather-formio** [comment]
4.x Render was released. Closing issue.
