### ISSUE TITLE
Cannot create property 'keyCode' on boolean 'false' from choices.js 7.0.0

### ISSUE THREAD

**Issue by Vedhachala** [formio/formio.js#1282]
Hi,

I recently upgraded  formiojs from 3.8.0 to 3.20.16 ,
I see this error while clicking any select dropdown.

![choices js error](https://user-images.githubusercontent.com/15833345/58149562-1f580b80-7c81-11e9-9e87-59c5a08f150b.PNG)

I also see the styles are improper for select fields.

![selectStyle](https://user-images.githubusercontent.com/15833345/58149587-34349f00-7c81-11e9-9d60-a4a60defde66.PNG)

Any idea why this might happen.?
Thank you

**Comment by randallknutson** [comment]
The issue with styling is that you may not be including the choices.js css files. You will need those to have the proper styling. The error may be that an older version of choices.js is still installed. Can you verify that it is the correct version?

**Comment by Vedhachala** [comment]
Thanks!
Importing the styles from "node_modules/choices.js/public/assets/styles/choices.css" in angular.json, fixed both the errors.
@randallknutson yes the correct version is installed.
although while using formiojs 3.8.0, the styles were proper even without adding choices.js styles
