### ISSUE TITLE
move components

### ISSUE THREAD

**Issue by ranjanitechleaf** [formio/formio.js#1283]
Hi
1. I need to move the advanced component fields to basic components, is this possible?
2. And also i need the custom component with column layout, if have any example code , please provide.

Thanks

**Comment by randallknutson** [comment]
Here is an example of how to customize the builder. 

http://formio.github.io/formio.js/app/examples/custombuilder.html

You can either list them specifically like customBasic or set "group" on the component to "basic".

Here is an example of a custom component: https://github.com/formio/react-app-starterkit/blob/master/src/components/CheckMatrix.js

**Comment by ranjanitechleaf** [comment]
Hi
In this page ( https://github.com/formio/react-app-starterkit/blob/master/src/components/CheckMatrix.js) it has the component with table, but i need to implement the components within the layouts.

**Comment by travist** [comment]
The component needs to be added to the renderer using the 

```
Components.addComponent('checkmatrix', CheckMatrixComponent);
```

**Comment by ranjanitechleaf** [comment]
Hi
i already added this 'Components.addComponent('checkmatrix', CheckMatrixComponent);', but still i got the error 'Unknown component: checkmatrix'.

**Comment by ranjanitechleaf** [comment]
I have done my custom component by using the example 'custom form builder'.
Thanks for your reply.

**Comment by Anandks1993** [comment]
@ranjanitechleaf  I am also trying to create a custom component, and I want that field to be properly validated, May I know how the validation is need to be done?
