### ISSUE TITLE
How to disable success alert when I submit form

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#1284]
I am rendering formio form and trying to submit the form. when i submit on top of form i am getting success alert.. I don't want to display that how can i disable that alert message when i submit form..

![image](https://user-images.githubusercontent.com/48546522/58154576-91375180-7c8f-11e9-9162-eb0a30a00e0d.png)

I want to disable this alert div...

**Comment by randallknutson** [comment]
If you set options.noAlerts = true it should stop messages from appearing.

**Comment by raguct25** [comment]
use this property, options.disableAlerts = true it should stop alert error and success message

**Comment by paulbors** [comment]
I have below setup:

Controller:
`
    public formioOptions: FormioOptions = {
        'disableAlerts': true
    };
`

Viewer:
`
<mat-formio
    [form]="formSchema"
    [formioOptions]="formioOptions"
    [refresh]="refreshForm"
    (submit)="onSubmit($event)"
></mat-formio>
`

Yet the feedback panel is still showing up :(

**Comment by travist** [comment]
This is an issue with the material library and should probably be logged in that issue queue.

**Comment by elias-soykat** [comment]
> This is an issue with the material library and should probably be logged in that issue queue.

is this issue solved for react project ??

**Comment by Kumaravel-00019** [comment]
@randallknutson thank lot it helps me.

**Comment by Amir-Pasha-Bagheri** [comment]
Give following keys to your form option

```
submitMessage: "",
  disableAlerts: true,
  noAlerts: true
```
