### ISSUE TITLE
wizard layout using semantic ui 

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1291]
Hello

I'm overriding the template framework of Formio to use semantic.  When building a form using display the builder is rendered correctly. However when using the wizard the builder doesn't render correct (see below). The semantic ui css is present on page.
![image A](https://user-images.githubusercontent.com/290639/58262158-a2f12580-7d71-11e9-9356-1185ee3016b8.png)

Also when displaying the form it looks as though the wizard css isn't being applied (see below)
![image B](https://user-images.githubusercontent.com/290639/58262159-a389bc00-7d71-11e9-85b4-f23c1879efa0.png)

Everything looks ok when using form display:
![Screenshot 2019-05-23 at 15 45 29](https://user-images.githubusercontent.com/290639/58262234-d03dd380-7d71-11e9-921b-a4d792716a32.png)

Any help on this would be appreciated.

**Comment by randallknutson** [comment]
Can you share an example code of how you are implementing this? When you set the template to semantic it should handle this correctly.

**Comment by aminmc** [comment]
Hi @randallknutson 

Here is an example:
https://codesandbox.io/s/react-example-84zlt

If you change the display from wizard to form then the builder looks ok.  Ignore the missing icons on the builder components.

Cheers

**Comment by randallknutson** [comment]
Yup. Looks like we never go the semantic template for the wizard built. If it doesn't exist in semantic it will fall back to the bootstrap3 version which is what it is doing currently. Is this something you could contribute? We definitely need this before release.

**Comment by aminmc** [comment]
Hi @randallknutson 

Created a PR for this:

https://github.com/formio/formio.js/pull/1299

I'm afraid I wasn't sure how to test this locally but if there is anything I need to do then let me know.

Thanks
