### ISSUE TITLE
Override Form template runtime

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1293]
Hello

Is it possible to change the Formio framework template at runtime? For example I would like to change the look of the form from bootstrap to semantic or custom template by changing a drop down option.  

Thanks

**Comment by travist** [comment]
We talked about this just the other day of allowing the 4.x renderer to switch dynamically at runtime. I believe we will add this in a future feature, but for now our main focus is to stabilize the core functionality.

**Comment by aminmc** [comment]
Is there any alternative way to implement this? Would you recommend an approach with the existing renderer?

**Comment by randallknutson** [comment]
Feel free to try the 4.x branch of formio.js. If you set the template to 'semantic' it will render for the semantic type themese.

**Comment by aminmc** [comment]
Closing this issue.
