### ISSUE TITLE
headers on select in 4.x

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#1294]
Hi,

Has this fix been merged to 4.x https://github.com/formio/formio.js/issues/1053

If not can you please do so as we are seeing a similar issue.

Thanks

Mark

**Comment by travist** [comment]
We still need to merge many pull requests into 4.x. That is high priority for us, but we are still not done with this item.

**Comment by pixie79** [comment]
Any chance we can get this by close of play monday please - we have shipped this to the customer and this is now blocking there next release.

**Comment by randallknutson** [comment]
This is fixed in 4.0.0-beta.36
