### ISSUE TITLE
Function Signature Changed but not handled

### ISSUE THREAD

**Issue by austindbertola** [formio/formio.js#1298]
Hi, so I am writing this as an issue instead of a pull request because I'm a little confused why this was allowed to happen, and I don't want to break something else. 

The webformbuilder function "addComponentTo" had the following signature on this commit on April 19: https://github.com/formio/formio.js/commit/5f0e49d6573d81701cf2bf1ca1f6ac246c9b4844#diff-dce2a82aac90a11aa0ca605834dc57f0
`addComponentTo(parent, schema, element, sibling) `

The next commit on April 22 (and latest code) shows the signature as the following:
`addComponentTo(schema, parent, element, sibling, after)`

This is problematic because any class inheriting from WebFormBuilder that uses this function will now break unless it is changed. For instance, the PDFBuilder still has ` addComponentTo(parent, schema, element, sibling)`

So I guess my question is, what should be changed? Should the original signature be reverted back, or should the PDFBuilder conform to the new signature?

**Comment by randallknutson** [comment]
Yup. We should check the 'after' parameter so that if it doesn't exist we don't call it.

**Comment by randallknutson** [comment]
Ah, so it turns out we already check it. https://github.com/formio/formio.js/commit/e47d5c21c948c21da8a1a63920bb1df2e524d338#diff-dce2a82aac90a11aa0ca605834dc57f0R866

What issue is this causing?

**Comment by austindbertola** [comment]
for me, the PDFBuilder was just plainly not working. The PDFBuilder calls super.addComponentTo with the "parent" object first and the "schema" object second https://github.com/formio/formio.js/blob/f9a0de9be0f1e2db664708095c09636eac4c4f76/src/PDFBuilder.js#L85. I am assuming they should correlate to what the WebFormBuilder needs which is the opposite now. Whenever I switch those params around, it works just fine. But I thought that was clear in my original description above, so now I am wondering if I am not understanding your response...

**Comment by wag110894** [comment]
We are aware of the PDF Builder issue using formio.js. We have this item on one of our developers list as high priority. We have tagged you onto the ticket (FOR-2328). We will let you know once this issue is resolved.

Thanks for reaching out!
