### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by abd-mhainy** [formio/formio.js#1300]
Hello all;
two days ago a problem has been appeared in form.io and the form is not initializing this problem shown in the console and says that "cannot read property namespace of undefined"

i have tested the jsfiddle link in the github project and the same issue appeared.
http://jsfiddle.net/travistidwell/v38du9y1/ 

thats weird cause there was no problem two days ago and after seeing the same problem on the jsfiddle page i guessed that this issue is a general issue.

thanks for helping
Abdulrahman

**Comment by dahmane86** [comment]
I have the same problem with the beta version (4.x)

**Comment by travhow99** [comment]
Same issue here. I resolved it for the moment by rolling back to version 3.20.17

**Comment by ASmeha** [comment]
1. Fork the fiddle 
2. Remove formio.full.min.css
3. Remove formio.full.min.js
4. Add https://unpkg.com/formiojs3.20.17/dist/formio.full.min.css
5. Add https://unpkg.com/formiojs@3.20.17/dist/formio.full.min.js

**Comment by randallknutson** [comment]
We inadvertently published a 4.x beta build to the latest NPM tag which caused this issue. It should be fixed now.

**Comment by abd-mhainy** [comment]
thank you so much the problem solved i have checked out to an old version but now i am on the latest version and every thing is fine thanks again
