### ISSUE TITLE
Uncaught TypeError: Cannot set property 'key' of undefined

### ISSUE THREAD

**Issue by keyurmeandev** [formio/formio.js#1302]
I am getting  "Uncaught TypeError: Cannot set property 'key' of undefined" error while rendering the form.

I have used https://unpkg.com/formiojs@4.0.0-beta.36/dist/formio.full.min.js

do I need to update it?

**Comment by randallknutson** [comment]
We aren't seeing this error in our testing. Can you give us an example form where this is happening?
