### ISSUE TITLE
[BUG] CSS class 'radio-selected' not added to the default radio choice inside a data grid

### ISSUE THREAD

**Issue by asamaha1** [formio/formio.js#1310]
Hi,

When rendering a radio button with a default value inside a **data grid**  component , the css class 'radio-selected' is not being added to the element.

My findings after debugging the issue : 
• the radio component in the data grid is being constructed twice, in the first time everything works fine, in the 2nd time, **changed** property inside the [updateValue ](https://github.com/formio/formio.js/blob/master/src/components/radio/Radio.js#L197)function of the radio component returns false, therefore the class is not added. 

Fiddle : http://jsfiddle.net/Lrh52je7/

version : 3.20.17

Form Payload :
`{
    "display": "form",
    "components": [
        {
            "label": "Radio",
            "optionsLabelPosition": "right",
            "values": [
                {
                    "label": "first",
                    "value": "first",
                    "shortcut": ""
                },
                {
                    "label": "second",
                    "value": "second",
                    "shortcut": ""
                }
            ],
            "inline": false,
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "radio",
            "input": true,
            "key": "radio2",
            "defaultValue": "first",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "encrypted": false,
            "reorder": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "label": "This Data Grid Should include a radio button",
            "disableAddingRemovingRows": false,
            "addAnother": "",
            "addAnotherPosition": "bottom",
            "removePlacement": "col",
            "defaultOpen": false,
            "layoutFixed": false,
            "enableRowGroups": false,
            "reorder": false,
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "datagrid",
            "input": true,
            "key": "thisDataGridShouldIncludeARadioButton",
            "defaultValue": [
                {}
            ],
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "components": [
                {
                    "label": "value",
                    "optionsLabelPosition": "right",
                    "values": [
                        {
                            "label": "default",
                            "value": "default",
                            "shortcut": ""
                        },
                        {
                            "label": "Not Default",
                            "value": "notDefault",
                            "shortcut": ""
                        }
                    ],
                    "inline": false,
                    "mask": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "radio",
                    "input": true,
                    "key": "value",
                    "defaultValue": "default",
                    "validate": {
                        "customMessage": "",
                        "json": ""
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "encrypted": false,
                    "reorder": false,
                    "properties": {},
                    "customConditional": "",
                    "logic": []
                }
            ],
            "groupToggle": false,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}`
Thank you.

**Comment by ASmeha** [comment]
Hi @travist @wag110894 any news on this? is it going to be on your backlog? is it going to be fixed in 4.0.0 ?

**Comment by heather-formio** [comment]
Testing using formio.js 4.14.8 this is working as expected. Closing this issue as it is stale, but please feel free to reopen if any behavior persists. Thank you for the report!
