### ISSUE TITLE
When executing a 'reset' action in a form containing a 'Day' component, the day component value is not being reset

### ISSUE THREAD

**Issue by ASmeha** [formio/formio.js#1311]
Expected behavior :  The month, day and year text boxes should be reset to empty

Current behavior : the 3 values not affected.

fiddle : http://jsfiddle.net/1kwdqf5h/

version : 3.20.17

Form Payload : 
`{
    "display": "form",
    "components": [
        {
            "label": "Day",
            "hideInputLabels": false,
            "inputsLabelPosition": "top",
            "fields": {
                "day": {
                    "hide": false,
                    "type": "number"
                },
                "month": {
                    "hide": false,
                    "type": "select"
                },
                "year": {
                    "hide": false,
                    "type": "number"
                }
            },
            "useLocaleSettings": false,
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "day",
            "input": true,
            "key": "day2",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "reorder": false,
            "encrypted": false,
            "maxDate": "",
            "minDate": "",
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        },
        {
            "label": "Reset",
            "action": "reset",
            "state": "",
            "theme": "danger",
            "shortcut": "",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "button",
            "input": true,
            "key": "reset",
            "defaultValue": false,
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "showValidations": false,
            "event": "",
            "url": "",
            "custom": "",
            "reorder": false,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}`
Thank you

**Comment by wag110894** [comment]
Hello ASmeha,

Thanks for reaching out. We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.

Thanks.

**Comment by ASmeha** [comment]
Hi @wag110894  you can find my PR [here ](https://github.com/formio/formio.js/pull/1316) 👍
