### ISSUE TITLE
Error in form.on 'render'

### ISSUE THREAD

**Issue by ZaKull** [formio/formio.js#1312]
When entering the render, it is repeated 4 times.

**Comment by randallknutson** [comment]
I'm not sure what this refers to, can you add any error messages and how to replicate the issue?

**Comment by ZaKull** [comment]
![image](https://user-images.githubusercontent.com/2388373/58487721-79a01300-813e-11e9-8386-578669618a75.png)
![image](https://user-images.githubusercontent.com/2388373/58487792-976d7800-813e-11e9-9738-d480c2624110.png)
when enter the form.on('render') repeat 4 times... this is error...

**Comment by ZaKull** [comment]
about 3 days ago the error did not occur, therefore an update was made to the js library of form.io which causes the render to be repeated many times.

**Comment by travist** [comment]
Will you share your form JSON with us that causes this problem? It may be easier to create a JSFiddle so that we can reproduce on our end and get a solution.
