### ISSUE TITLE
'Select' component inaccurate 'skip'

### ISSUE THREAD

**Issue by asamaha1** [formio/formio.js#1314]
'Select' component has the below settings : 
• Data Source Type : 'URL'
• Lazy Load url : true
• Limit : 20

Repro steps :
• Click on the select component, http request is sent with skip = 0 and limit = 20
• Click outside the component then click on the select component, http request is sent with skip =20 and limit = 20

Expected behavior : http request sent with skip = 0 and limit = 20.

My findings : 
• this issue is caused by this statement [`const skip = this.loadedItems || 0;`](https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L369)

**Another issue caused by this probably :**  (tell me if i should create it separately) 

**Search functionality** : when you search and you get 2 items for example, loadedItems is 2, type anything again and the request is made with skip = 2 and data is not fetched.

version : 3.20.7

**Comment by ASmeha** [comment]
Any news on this @travist @wag110894 ? Thank you!

**Comment by heather-formio** [comment]
Closing this as it is stale, please feel free to reopen at any time. Thank you!
