### ISSUE TITLE
[BUG] PDF Form Editor overlay and spinner preventing use

### ISSUE THREAD

**Issue by oneserve** [formio/formio.js#1318]
## Environment
- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 6.5.17
- Formio.js version: 3.20.16
- Frontend framework: Any
- Browser: Chrome
- Browser version: 74.0.3729.169

## Steps to Reproduce
1. Go to http://formio.github.io/formio.js/app/builder
2. Select PDF from the dropdown

## Expected behavior
PDF form is loaded and can be edited.

## Observed behavior
The PDF form loads, but cannot be used due to an overlay and spinner not disappearing. Manually removing the overlay and spinner doesn't correct the problem - components still cannot be dropped in the editor window. The browser console displays the following warnings:

```
postmessage data invalid json:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _dispatch (1ec0f8ee-6685-5d98-a847-26f67b67d6f0.html?id=eafcn7:1121)

postmessage data invalid json:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _dispatch (1ec0f8ee-6685-5d98-a847-26f67b67d6f0.html?id=eljh6d&builder=1:1121)
```

## Example
Example available in the reproduction steps.

**Comment by wag110894** [comment]
We have this item on one of our developers list as high priority. We have tagged you onto the ticket (FOR-2328). We will let you know once this issue is resolved.

Thanks for reaching out!
