### ISSUE TITLE
Get different Select properties in calculated text field then the value

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#1320]
My setup is as follows:
- 1 select component with the values(url): value, label, propertyA
- 1 text field component which should show propertyA after the selection

I know how to get the select value (as a calculated value) in the text field but how do I get another property?
Can you advise?

Kind regards,
Mario

**Comment by randallknutson** [comment]
If the select is an object with multiple properties, you can set the calculated value to:
```
value = data.mySelect.prop1 + ' ' + data.mySelect.prop2;
```

Since the textfield is stored as a string, the result must be a string.

**Comment by KyooMario** [comment]
Hello Randall,

I populate the Select values with an Url Json respone. In this respone there are my “proporties”
Do you mean the same with property? If so I cannot confirm it works this way.

Kind regards,
Mario

**Comment by randallknutson** [comment]
Make sure the value property is set to "Entire object" instead of one value. If you set one value there it will only save that value. If you set it to "Entire object", all the properties will be available from your url.

**Comment by KyooMario** [comment]
Hello Randal,

Maybe I misunderstand but the text "Entire object" returns nothing. Is this an option I overlook?
I am testing on: https://formio.github.io/formio.js/app/builder

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Randal,

Got it "Entire object" means leave it empty (cannot find this anywhere in the documentation).
then value = data.select.property works fine.

Again: A magnificent tool. Congrats and Thanks.

Kind regards,
Mario
