### ISSUE TITLE
Function in calculated Value

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#1321]
I want to call a function to populate a text value like below. The logging returns the value but the text component value is not populated. Please advise how to fix this?

const url='https://next.json-generator.com/4J7C77PpI';
function getData() {
  $.get(url, function(data,status){
    console.log('Name: '+data[0].Name);
    return data[0].Name;
  })
}
value = getData();

Kind regards,
Mario

**Comment by KyooMario** [comment]
Ah thanks,

Any example of the instance.setValue() ?

**Comment by KyooMario** [comment]
I tested it like below which gives me the result but the code keeps looping. What do I miss?

var makeRequest = function (url, method) {

	// Create the XHR request
	var request = new XMLHttpRequest();

	// Return it as a Promise
	return new Promise(function (resolve, reject) {

		// Setup our listener to process compeleted requests
		request.onreadystatechange = function () {

			// Only run if the request is complete
			if (request.readyState !== 4) return;

			// Process the response
			if (request.status >= 200 && request.status < 300) {
				// If successful
				resolve(request);
			} else {
				// If failed
				reject({
					status: request.status,
					statusText: request.statusText
				});
			}

		};

		// Setup our HTTP request
		request.open(method || 'GET', url, true);

		// Send the request
		request.send();

	});
};

const url='https://kyoodatrest-developer-edition.eu19.force.com/services/apexrest/kyoodat/rest?query=SELECT%20Id,IsActive,Name,Pricebook2Id,Product2Id,ProductCode,UnitPrice%20FROM%20PricebookEntry%20WHERE%20Pricebook2Id%20=%20%2701s1i000000ileyAAA%27';

makeRequest(url)
	.then(function (posts) {
		console.log('Success!', JSON.parse(posts.response)[0].Name);
		instance.setValue(JSON.parse(posts.response)[0].Name); 
	})
	.catch(function (error) {
		console.log('Something went wrong', error);
	});

**Comment by KyooMario** [comment]
Ah The looping is probably from an earlier code issue. Refreshed the page and it stops.

So the instance.setValue() works fine. THANKS.

**Comment by KyooMario** [comment]
No I have to come back on this. The code keeps looping. Hum. Any advise?

**Comment by randallknutson** [comment]
I'm not sure. We don't really recommend using setValue as it can cause issues (sorry for suggesting it). You may have better luck with instance.dataValue = ''; and then call instance.updateValue(); after.

**Comment by KyooMario** [comment]
Hello Randall,

I tested instance.dataValue = ''; and then call instance.updateValue(); after. But the same looping result.

As questioned in another issue I just want to set a value with a selected property (Url mode) but everything I try does not work.
I don't want to nag though because formio is a magnificent form builder. Hope we can get this to work also ;-)

Kind regards,
Mario

**Comment by travist** [comment]
Sorry for the continual bounce backs, but if you don't pass in the "value" into the updateValue method, then it uses the ```getValue()``` method to set the value back and then a "change" occurs which is what is causing your infinite loop. Try this instead.

```
instance.updateValue({}, CALCULATED_VALUE);
```

**Comment by gag29** [comment]
Is there any way that we can add a line break in calculated value? I basically want to add a line break and display 2 text fields one below the other into a text area

**Comment by randallknutson** [comment]
This depends on the type of textarea you are using. If it is just a textarea you probably can do this by adding a \n to the string. If it is a wysiwyg editor, add a "</br>" to the string.

**Comment by gag29** [comment]
Thanks @randallknutson

**Comment by krixerx** [comment]
What if i want to load all data (not just one field), some data in EditGrid and in some fields in Panel.
Should i iterate over all components or is the any universal method to reload data in all components?

**Comment by krixerx** [comment]
> What if i want to load all data (not just one field), some data in EditGrid and in some fields in Panel.
> Should i iterate over all components or is there any universal method to reload data in all components?

just found a solution to my problem, https://github.com/formio/formio.js/issues/3343
