### ISSUE TITLE
[BUG] Unable to add components to data grid

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1340]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.40
- Frontend framework: react-formio 4.0.0-beta.21
- Browser: Chrome
- Browser version:  74.0.3729.169

## Steps to Reproduce
1.  Create new form (semantic theme)
2.  Add data grid component
3.  Add any other component inside the data grid and you cannot.

## Expected behavior
Expecting to be able to add any components inside a data grid component
## Observed behavior
Unable place component inside the data grid.
## Example
<img width="970" alt="Screenshot 2019-06-03 at 09 26 05" src="https://user-images.githubusercontent.com/290639/58787400-a8583680-85e1-11e9-8572-e4e0d1f0e88f.png">

**Comment by randallknutson** [comment]
This is a known issue and is on our shortlist to have fixed soon so we should get to it shortly. We'll update the ticket when done.

**Comment by aminmc** [comment]
@randallknutson is there any updates on this? I'm using the lates version and I'm still not able to add a component to the data grid.

**Comment by aminmc** [comment]
@randallknutson I've noticed with the latest build I can add components to data grids however the layout of the builder looks slightly odd:

![Screenshot 2019-06-18 at 10 07 29](https://user-images.githubusercontent.com/290639/59668776-fa3bb780-91b0-11e9-8f27-49072d6d5aab.png)

I'm guessing it's still a work in progress?

**Comment by randallknutson** [comment]
That is generally correct but could be better. Datagrid is a row of components so you add the component on the right hand side. It should better handle the width but that should be relatively straightforward to fix.

**Comment by aminmc** [comment]
Is this something that needs to fixed in the template?

**Comment by randallknutson** [comment]
I don't see anything obvious in the template that needs fixing. The widths look like default table widths and for some reason it appears to be deciding the left column needs all the room.

**Comment by aminmc** [comment]
@randallknutson is there something I can look at? any pointers?

**Comment by randallknutson** [comment]
Sure. You can check to see why the table cells have certain widths. Browsers a weird when the assign widths in tables and will sometimes decide that one column needs most of the width which appears to be the case here.

**Comment by aminmc** [comment]
@randallknutson I think there is something going on more than just width. It looks like I can't move a component outside of the data grid once it's been added. A bit confusing :)

**Comment by randallknutson** [comment]
Yeah, our original renderer/builder has the ability to reoder a datagrid as well as drag a component out. Currently I don't think that is currently supported in 4.x as it is an incomplete feature. We have it marked as a blocker for full release so it will be coming at some point.
