### ISSUE TITLE
Ensure "Add Resource" works correctly with multiple-value selects in 4.x

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1347]
I haven't tested it, but to me it looks like [here](https://github.com/formio/formio.js/blob/f684fc4c5df5b956f4884fed8b20ca0239c82898/src/components/select/Select.js#L718) you might need [this](https://github.com/formio/formio.js/blob/master/src/components/resource/Resource.js#L65-L67), too.
(Source: [this commit](https://github.com/formio/formio.js/commit/418b655b6cac5e829ccac680fabc192cf6801cd6#diff-104f12ae26d41fc90804cf1ee2dbb392))

**Comment by randallknutson** [comment]
I'm adding that change to 4.x with the next release. Thanks!

**Comment by franke-mc** [comment]
Thank you
