### ISSUE TITLE
checkValidity() doesn't validate required fields.

### ISSUE THREAD

**Issue by 1100617** [formio/formio.js#1352]
> Yes this can be done. Here is a snippet that could achieve this.
> 
> ```js
> Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example').then(function(form) {
>   form.on('change', function(value) {
>     // This will tell you if it is valid.
>     console.log(value.isValid);
>   });
> 
>   // Or you can check it manually with.
>   var isValid = form.checkValidity(form.submission.data);
> });
> ```
> 
> _Originally posted by @travist in https://github.com/formio/formio.js/issues/224#issuecomment-373093568_

Client-side validation with the `form.checkValidity()` function will always return as valid `(true)` even if a required field is not filled. It only works after you fill in the data in a required field and then remove all data from the field.

Is this supposed behavior?

**Comment by randallknutson** [comment]
You may need to set pristine to false so that the checkValidity properly calculates. You can do that with form.setPristine(false).
