### ISSUE TITLE
Tooltip override semantic ui

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1355]
Hi,

This is more of a question...I'm looking to override the tooltip styling to be more inline with semantic ui:

https://semantic-ui.com/modules/popup.html

I was wondering if under src/templates/semantic i would need to create additional .hbs files to override the tooltip? Or is there somewhere different I need to override it? Just looking for a pointer and happy to create a PR for this.

Thanks

**Comment by randallknutson** [comment]
Currently the tooltip is using Tooltip.js. The code for it is here: https://github.com/formio/formio.js/blob/4.x/src/components/_classes/component/Component.js#L784-L797

You may be able to override this by removing the tooltip ref and then doing whatever you need for semantic. If semantic has some javascript part, you can add it in the same spot and either use a different ref or switch based on the theme.

**Comment by aminmc** [comment]
@randallknutson thanks...I'm imaging something like this inside the semantic template for field:
```js
{% if (component.tooltip) { %}
   <span data-tooltip="{{component.tooltip}}" data-position="right center">
    <i class="{{iconClass('question-sign')}}"></i>
  </span>
 {% } %}
```
which outputs something like this:
![Screenshot 2019-06-06 at 17 33 08](https://user-images.githubusercontent.com/290639/59051939-e4abc100-8885-11e9-8ea9-623fefccfb01.png)

The above version doesn't need JS and relies on CSS. The only issue is that I might need to break the text.

**Comment by randallknutson** [comment]
Looks perfect. There is already a place in the code I mentioned above that has a replacement with end of line for <br />. You could break that out into its own string that can be used in the template, for example put it in the variable "tooltip". Then both systems could use the string with <br /> in them.

**Comment by aminmc** [comment]
@randallknutson I've upraded the versions but I'm afraid i'm seeing:

![Screenshot 2019-06-07 at 17 46 05](https://user-images.githubusercontent.com/290639/59120410-39663f00-894d-11e9-9338-793315c7eef5.png)

I've checked my PR but can't see how that would cause the above...any thoughts?

**Comment by randallknutson** [comment]
We've done a ton of other updates this week which may have caused an issue. That happens when there is an error when interpolating the template. If you check in your console there should be an error about what went wrong. You may need to update some overridden templates or something like that.

**Comment by aminmc** [comment]
Just wondering if it might be related to this:https://github.com/formio/formio.js/commit/c6a6536779989b9d6dcf024eccfd0704ed5b4fbc
In semantic template I’m using tooltip variable.

**Comment by aminmc** [comment]
@randallknutson as I expected it is to do with:
Error interpolating template ReferenceError: tooltip is not defined

I renamed title to a variable tooltip so that it could be referenced inside the template.  It seems as though you reverted that back to title.  Is it possible to find out what the solution should be here?

**Comment by randallknutson** [comment]
The variable name in the template is "title" for both versions of the code (before and after I reverted the name of the variable). It is based on the Key of the object, not the value. You should be able to use {{ title }} for the tooltip. That does seem to be the wrong variable name but I don't want to change it without fixing it in all the other places as well.

**Comment by aminmc** [comment]
@randallknutson understood. Create new PR to align with "title".

https://github.com/formio/formio.js/pull/1367

**Comment by randallknutson** [comment]
Oh wait, I see the issue. We should pass tooltip as a data parameter to the render method here:

https://github.com/formio/formio.js/blob/4.x/src/components/_classes/component/Component.js#L773-L777

**Comment by aminmc** [comment]
oh...in that case my PR won't work then?

**Comment by aminmc** [comment]
@randallknutson still an issue:
![Screenshot 2019-06-12 at 07 08 34](https://user-images.githubusercontent.com/290639/59327278-f3103780-8ce0-11e9-915e-8b3284d4b8d2.png)

title is not defined. As you mentioned before I guess we need to pass title into the render method. That does mean moving title further up into a variable.  I added a variable tooltip...will change that to title and pass that into the render template method.

**Comment by randallknutson** [comment]
Sorry for all the confusion on this. What I'd like is to provide the variable "tooltip" to the render template for fields. That way we aren't adding items to "component" or "this". I did this and fixed the semantic templates here: https://github.com/formio/formio.js/commit/f474987cd72f93123af4842a76c491d1141e0b57

Let me know if that doesn't work.

**Comment by aminmc** [comment]
Will there be a release today? I can try and let you know. No worries about the confusion. I think I just need to understand the codebase a bit more.

**Comment by aminmc** [comment]
@randallknutson i'm afraid .47 doesn't have the fix for the tooltip in the Field.js class. I've downloaded the .47 version and can confirm it only has:

```js
import Component from '../component/Component';

export default class Field extends Component {
  render(element) {
    if (this.noField) {
      return super.render(element);
    }
    else {
      return super.render(this.renderTemplate('field', {
        label: this.labelInfo,
        element: element
      }));
    }
  }
}
```
instead of 

```js
import Component from '../component/Component';

export default class Field extends Component {
  render(element) {
    if (this.noField) {
      return super.render(element);
    }
    else {
      return super.render(this.renderTemplate('field', {
        label: this.labelInfo,
        element: element,
        tooltip: this.interpolate(this.component.tooltip || '').replace(/(?:\r\n|\r|\n)/g, '<br />'),
      }));
    }
  }
}

```

**Comment by travist** [comment]
Thanks @aminmc, please feel free to make a pull request and we will pull in those changes.

**Comment by aminmc** [comment]
@travist it’s already committed. Just seems as though the version 47 doesn’t have that change in there.

**Comment by aminmc** [comment]
@randallknutson will you be doing a release today for the tooltip fixes and PR? Would like to close this issue out.

**Comment by randallknutson** [comment]
Should be released as beta.48

**Comment by aminmc** [comment]
Working. Thanks @randallknutson
