### ISSUE TITLE
[BUG] Form builder failing to render

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1363]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [] Local deployment
    - Version: 
- Formio.js version:  4.0.0-beta.43
- Frontend framework: react-formio  4.0.0-beta.23
- Browser: Chrome
- Browser version:  74.0.3729.169 (Official Build) (64-bit)

Using semantic UI template

## Expected behavior

Create a form using the Form Builder should display a builder.

## Observed behavior

Error when trying to render the builder

![Screenshot 2019-06-07 at 07 30 17](https://user-images.githubusercontent.com/290639/59085837-cf6f7a80-88f7-11e9-9cff-145d38bf1299.png)

![Screenshot 2019-06-07 at 07 33 48](https://user-images.githubusercontent.com/290639/59085838-d1d1d480-88f7-11e9-9b98-68b0c02d21a0.png)

```js
<FormBuilder form={{display: "form"}} onChange={updateForm}/>
```

**Comment by randallknutson** [comment]
Thanks. This must be a bug introduced in the latest round of fixes. I'll take a look.

**Comment by randallknutson** [comment]
Fix is here. https://github.com/formio/formio.js/commit/f281cd9769ded8b079a8c8403482b29bccb28bce

It was caused by some recent other fixes we made.

I'm working on another urgent fix and will get a build together later in the day.

**Comment by randallknutson** [comment]
react-formio 4.0.0-beta.24 should be released with the fix. Thanks for reporting it!

**Comment by aminmc** [comment]
@randallknutson do you want me to raise this as separate issue? but I can no longer see the wizard builder.  Not sure if it is related to my PR change with changes to the form wizard builder for semantic...

**Comment by aminmc** [comment]
Also I’ve notice that swapping from form to wizard causes this exception to reappear. Also as mentioned before wizard builder doesn’t appear at all

**Comment by aminmc** [comment]
![Screenshot 2019-06-08 at 06 21 37](https://user-images.githubusercontent.com/290639/59142406-bcbb7b00-89b5-11e9-8282-08d4c6c0cda4.png)
 Issue still exists. This is happening when I use my dropdown to change theform from form to wizard to form.

**Comment by randallknutson** [comment]
How are you embedding the form? I fixed an issue related to this on Friday and it is working for us now. It may have something to do with how the form is instantiating.

**Comment by aminmc** [comment]
I hold some state and pass that into the builder:

```js
<FormBuilder form={{display: state.display,
                            }} onChange={updateForm}/>
```

I have a select box that allows me to toggle between form and wizard. When I change the select box I change state.display to either wizard or form.  Pre .45 I could change the builder from form to wizard and vice versa. Now when I try to change to wizard nothing happens and when I change back to form then I get the error as shown above.

**Comment by randallknutson** [comment]
Please try out beta.47. I think It is fixed now.

**Comment by aminmc** [comment]
@randallknutson I can confirm that this is working as expected:

![Screenshot 2019-06-12 at 07 06 47](https://user-images.githubusercontent.com/290639/59327208-c3612f80-8ce0-11e9-82d0-2d77591a1c55.png)
