### ISSUE TITLE
Word and character count in Text field : Cannot translate 'words' and 'characters'

### ISSUE THREAD

**Issue by samdidos** [formio/formio.js#1364]
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: formio-enterprise (latest)
- Formio.js version: ^3.20.11
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 76

## Steps to Reproduce
1. Select 'Show Word Counter' and 'Show Character Counter' in a text field component of a form
2. Write some stuff into it in your rendered form
3. Switch language of your application

## Expected behavior

Should change the words 'words' and 'characters' in the expected locale 
ex : 
in English (with the `en` value) : `4 words, 44 characters`
in French (with the `fr` value) : `4 mots, 44 charactères`

## Observed behavior

It doesn't change and there doesn't seems to be a field in form definition to change that.

I believe this should be supported as is, but Is there any existing solution for this? Thank you

**Comment by jhen1422** [comment]
@samdidos 
Thank you for the report. We have added this item to our development backlog. If you are interested in expediting this fix, please contact support@form.io for pricing information. 

Thank you.

**Comment by heather-formio** [comment]
Closing this as it is stale, please feel free to reopen at any time. Thank you!
