### ISSUE TITLE
[BUG] Custom select item label not working

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1365]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.41
- Frontend framework: react formio 4.0.0-beta.22
- Browser: Chrome

## Steps to Reproduce
1. Create a form with select component
2. Configure to use external URL
3.  Data structure:
```json
[{
      "id": "{{guid}}",
      "name": "{{lorem 4}}"
    }]
```
4. Configure value property to be 'id'
5. Configure label property to be:
```json
{{item.name}}
```

## Expected behavior
Drop down list should display the label

## Observed behavior
No values displayed. The items have been loaded correctly and the id property has been evaluated correctly however the template for the select component is:
![Screenshot 2019-06-10 at 09 19 46](https://user-images.githubusercontent.com/290639/59183293-99363300-8b63-11e9-88b3-680358ad6794.png)

If you do not customise the label then the template reverts to default:
![Screenshot 2019-06-10 at 09 25 35](https://user-images.githubusercontent.com/290639/59183361-b3701100-8b63-11e9-8092-92d58a44fbf7.png)

**Comment by aminmc** [comment]
Hello..any thoughts on this issue?

**Comment by randallknutson** [comment]
This is strange. I'm assuming you are setting your template to:
```
<span>{{item.name}}</span>
```
The only reason I can think of that not working would be that there is no actual value on "item.name". Can you verify that it is set?

**Comment by aminmc** [comment]
Hi I can confirm that name does exist. If I override and use item.name I get an empty span.

**Comment by aminmc** [comment]
Attaching screen shot where id and name exists in the data object in item template function:
![Screenshot 2019-06-12 at 19 13 17](https://user-images.githubusercontent.com/290639/59375503-33ee6780-8d46-11e9-9ab4-e7a2be55469c.png)

Additional screen shot shows template is empty:

![Screenshot 2019-06-12 at 19 14 52](https://user-images.githubusercontent.com/290639/59375608-6a2be700-8d46-11e9-9906-b0cabdb453ba.png)

**Comment by randallknutson** [comment]
Can you debug right here? https://github.com/formio/formio.js/blob/4.x/src/components/select/Select.js#L120

That is where the template is modified. Check that the data and templates are correct at this point.

**Comment by aminmc** [comment]
@randallknutson Here is screen shot:

![Screenshot 2019-06-13 at 06 48 58](https://user-images.githubusercontent.com/290639/59406869-74ca9880-8da7-11e9-912a-a1f9f828cdd5.png)

component.template is already <span></span>
![Screenshot 2019-06-13 at 06 51 04](https://user-images.githubusercontent.com/290639/59406938-a2174680-8da7-11e9-9eea-fd73bb9164ba.png)

**Comment by aminmc** [comment]
Closing this...turns out it was a user error :(. Thanks @randallknutson sorry for raising this as an issue
