### ISSUE TITLE
[BUG] Multiple Submit buttons issue

### ISSUE THREAD

**Issue by asamaha1** [formio/formio.js#1368]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [] Local deployment
    - Version: 
- Formio.js version: 3.22.0
- Frontend framework:
- Browser: chrome
- Browser version: 74.0.3729.169 

## Steps to Reproduce
1. create a form with 2 submit buttons
2. click on one button
3. the other button is also affected and is submitting action

## Expected behavior
Only the clicked button should receive the submit button event
## Observed behavior
All Submit buttons in the form are affected

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

http://jsfiddle.net/m5u4qs0o/

For code or form JSON, please enclose in a code block:

```js
 {
    "display": "form",
    "components": [
        {
            "label": "Text Field",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "textField2",
            "defaultValue": "",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "widget": {
                "type": ""
            },
            "reorder": false,
            "inputFormat": "plain",
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        },
        {
            "label": "Submit Second",
            "state": "",
            "theme": "primary",
            "shortcut": "",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "button",
            "input": true,
            "key": "submitSecond",
            "defaultValue": false,
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": [],
            "showValidations": false,
            "event": "",
            "url": "",
            "custom": "",
            "reorder": false
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}
```

**Comment by randallknutson** [comment]
Currently the submit buttons fire the same event (submit) that is listened to on the form level so they act the same. If you need different actions you can use the "Action" type of the button or "Save in State" which can be used to distinguish between different submit states.

**Comment by ASmeha** [comment]
@randallknutson  But why not send an identifier in the event payload and validate it in the event handler, like the id of the element ?

**Comment by randallknutson** [comment]
Each component has a "key" that is the identifier. When you click a button it should set its key to true on the data object. For example, if your button has the key of "mySubmit" then data.mySubmit should be true when that button is pressed. I'm not sure this has been tested recently though so it is possible the events are cross pollinating the events to cause both submits to occur. Is this something you could look into and fix?

**Comment by ASmeha** [comment]
@randallknutson i will take a look 👍
