### ISSUE TITLE
Overriding API property name when using custom components in formbuilder

### ISSUE THREAD

**Issue by baseline-s** [formio/formio.js#1373]
Is it possible to define the API endpoint property name when using custom components ?

Example:
1. Create builder with the following component.
components: {
        frm001_fname: {
          title: 'First Name',
          key: 'frm001_fname',
          icon: 'fa fa-terminal',
          schema: {
            label: 'First Name',
            type: 'textfield',
            key: 'frm001_fname'',
            input: true
          }
        }
2. Drag to create form element and API Property Name should reflect as 'frm001_fname' instead of 'firstName'

I can't seem to find a way to do this.

**Comment by jhen1422** [comment]
@baseline-s 
Thank you for the report.

We have added this item to our backlog which we will prioritize with our development team next week. We do offer services to expedite bug fixes for a service fee. Please feel free to reach out to support@form.io for more information.

Thanks again!

**Comment by Alena-Levina-Softensity** [comment]
Hi @baseline-s , could you please attach a code snippet / CodePen / JSFiddle demonstrating your issue? I'm not sure I understand how you use the JSON you've provided in the description. Would much appreciate!

**Comment by baseline-s** [comment]
Hi Alena,

Thanks for looking into this.

Here is a pen that should give you an idea of the problem I am facing.

https://codepen.io/baseline-s/pen/ewRxvp

Using custom components in the builder, I am trying to get the key to be the elements name attribute once the form is rendered. I assumed this was the API Property Name in the component editor.

Please let me know if you require more information.

Thanks,
Karl

**Comment by mujtaba1016** [comment]
> @baseline-s Thank you for the report.
> 
> We have added this item to our backlog which we will prioritize with our development team next week. We do offer services to expedite bug fixes for a service fee. Please feel free to reach out to [support@form.io](mailto:support@form.io) for more information.
> 
> Thanks again!

Is that still in backlog. Any update??

**Comment by mujtaba1016** [comment]
Found a solution for those who are looking for override the default camelCase formatting of component property API name

  `Formio.builder(document.getElementById('builderId'), {}, components).then(function (builder) {
            builder.on('saveComponent', function () {
                builder.editForm._data.key = myCustomFormat(builder.editForm._data.key) // myCustomFormat is formatting func
            });
        });`
