### ISSUE TITLE
[BUG] Feature "allowCalculateOverride" not working as expected

### ISSUE THREAD

**Issue by sebastianhaberey** [formio/formio.js#1378]
Formio.js version: latest (3.22.4)

## Expected behavior

As described in editor: "When checked, this will allow the user to manually override the calculated value."

## Observed behavior

allowCalculateOverride: false -> calculated value overrides user input
allowCalculateOverride: true -> no calculated value, user input possible

see https://codepen.io/sebastianhaberey/pen/NVjLov

**Comment by heather-formio** [comment]
Testing using formio.js 4.14.8, this is working as expected. Closing this as it is stale, please feel free to reopen at any time. Thank you!
