### ISSUE TITLE
Long running forms

### ISSUE THREAD

**Issue by Terry-Cornwell** [formio/formio.js#138]
Hi,

Not so much an issue as to more a design pattern, but how would FormIO support the completion of a form over a number of sessions?

For example, a user signs in on Monday and completes forms section 1 to 3. They then realise they don't have all the information to hand to complete the form. They save the form as-is and sign out. The next day, when they have sourced the information they log back in and continue completing the form before submitting.

Terry

**Comment by cabrerabywaters** [comment]
Hello @Terry-Cornwell .
At least what I would do it to create a "state" dropdown list maybe with two basic states: "DRAFT" and "Submitted".

As long as the user is still trying to get all the information for your form they can submit the Form as draft... afterward, with all the information in hand, they can tell you that the status is "Submitted" so you can do whatever you need to do with the final information.
If they made a mistake and they want to continue drafting after the submission, just provide a simple way to change the state from Submitted to draft again.

Hope it helps!

Best Regards,
Ignacio
