### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by akhilesh-sharma168** [formio/formio.js#1380]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 3.18
- Frontend framework: angular 6
- Browser: chrome
- Browser version: 75

## Steps to Reproduce
1. Create a form using the form-io. Put select control inside it.
2. Set the Custom CSS Class to notranslate.
3. Click on Save button.

## Expected behavior:
After applying the google translate on the page, labels of select div should not be translated.
only select options should not get translated.
## Observed behavior: Labels are not getting translated.
Find the screenshot for the same.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
![screenshot](https://user-images.githubusercontent.com/45589364/59428768-db79a180-8dfb-11e9-9404-82e5756f3554.png)

```

**Comment by randallknutson** [comment]
I'm not very aware of how google translate works. Is the issue that the notranslate is being added in the wrong spot in the DOM? This might be a place where using the 4.x branch would allow modifying the templates to add the class wherever you need.

**Comment by akhilesh-sharma168** [comment]
@randallknutson, 
yes the notranslate is a class which is used by google translate to not translate the specific element where it is present, in our case we need to add it to the select options, not to its  label, is there any way for doing this in formio.

**Comment by randallknutson** [comment]
I don't think this is currently possible in the 3.x branch. In 4.x you can modify the templates for the fields directly and could add the class wherever you want. We are getting very close to having 4.x ready for a release candidate so it might be worth checking out.

**Comment by akhilesh-sharma168** [comment]
@randallknutson 
Can you let me know when will the final release of 4.x branch be available?

**Comment by heather-formio** [comment]
4.X has been released for some time now so I am closing this issue as it is stale. Please feel free to check out the change log for the latest versions and changes within them. Thank you for using Form.io!
