### ISSUE TITLE
[BUG] Deletion of last character doesn't trigger change

### ISSUE THREAD

**Issue by sebastianhaberey** [formio/formio.js#1383]
## Environment

- Formio.js version: latest (3.22.4)

## Steps to Reproduce

1. enter some characters in field of type textfield / number (maybe others?)
2. delete characters one by one using backspace

## Expected behavior

Each deletion triggers change.

## Observed behavior

Deletion of last character doesn't trigger change.

## Example

see https://codepen.io/sebastianhaberey/pen/WqvBGq?editors=0011 (watch console for events)

**Comment by Alena-Levina-Softensity** [comment]
@sebastianhaberey I took a look at your codepen and at line 37 you have following code: 
```submission.data.textfield && console.log(submission.data.textfield);```
and first part of it (```submission.data.textfield &&```) is the reason why you don't see console output for empty textfield value. You can remove this part ot put a breakpoint at this place and you'll see that change event actually gets fired.

Please let me know you have any more questions on this

**Comment by sebastianhaberey** [comment]
Hi Alena,

you are right! My example wasn't very good. I didn't expect the textfield to become undefined once the last character was deleted. I've made an updated codepen that's a bit closer to what we have in our application and shows the bug:

https://codepen.io/sebastianhaberey/pen/MMoLyg

**Comment by sebastianhaberey** [comment]
Here is a pull request that fixes the issue. The proposed solution is for the number component to return null if no value is set, so the entry is not removed entirely from the internal data structure.

Note that this pull request **breaks the 'client-only' feature**, which is why we disabled the corresponding unit test. We are convinced that this feature is mostly broken, since it doesn't work for nested components and it doesn't work for elements that have a default value set (the unit test has been modified to verify the last point).

**Comment by heather-formio** [comment]
This looks to be working as expected in the current version. Closing this as it is stale, please feel free to reopen at any time. Thank you!
