### ISSUE TITLE
Unexpected behaviour: buttons with custom action altering data before submitting

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1384]
The goal: Multiple "submit" buttons, each POSTing a different variant of the submission.
Question: What is the simplest, recommended, robust way to achieve this? Does it require using a `beforeSubmit` hook? Or buttons with `Event` actions, like e.g. `submitMode1` etc.?

I tried using multiple buttons with `Custom` action, each setting `data['mode']` to a unique value for the buttton, before calling `form.submit();` but: 
* in a form launched from beta.form.io, nothing is working because form.submit is not a function: https://formview.io/#/benudbjfljpobfo/testdifferentsubmitmodes&header=1
* using it within beta.form.io, e.g. clicking on `Submit: Mode 2`, the display changes briefly as expected (-> shows `Mode 2` as selected), but the value is lost in the submission data: `{"data":{"mode":"","submitMode2":true}...}` instead of `{"data":{"mode":"mode2"...}...}`
* using it within the form builder of beta.form.io, nothing is POSTed at all (probably as intended), but the behaviour does not appear to be deterministic: upon clicking a button, either nothing is happening, or the value of the *previous* button starts being displayed as selected

**Comment by travist** [comment]
The way I would do this is to trigger an event and then receive that event from the outside js controller and then make your call from there. Is that not working?

**Comment by franke-mc** [comment]
```
+                (ready)="onFormReady($event);"
+                (customEvent)="onCustomEvent($event);"
```
```
+  formReady = null;

+  onFormReady(formReady) {
+    this.formReady = formReady;
+  }
+
+  onCustomEvent(event) {
+    const _this = this;
+    const customSubmit = function (mode) {
+      event.data['mode'] = mode;
+      if (_this.formReady) {
+        _this.formReady.formio.submit({ data: event.data });
+      }
+    };
+    switch (event.type) {
+    case 'submitMode1':
+      customSubmit("mode1");
+      break;
+    case 'submitMode2':
+      customSubmit("mode2");
+      break;
+    default:
+      alert('unexpected custom event: '+event.type);
+      break;
+    }
+ }
```

That works well, but the downside is that the logic leaks out of the form into the surrounding framework-specific app code (e.g angular).

Looking for an alternative, I found that within the form itself, defining advanced logic to set the "mode" value from events works well, too, but there does not seem to be a way to schedule a "submit" action for when all the logic code has finished. So for now we are going with the above solution, thank you!
