### ISSUE TITLE
[BUG] form builder date max date `moment()` values are not shown properly on edit of form

### ISSUE THREAD

**Issue by cymen** [formio/formio.js#1385]
## Environment

When I use the form builder on form.io, it shows me how I can set max date to `moment()` or `moment().add(1, 'days')`. This works however when I go back to edit the form, I find that the max date field contains the calculated/executed result not the original input -- so it'll have a date string not what I typed in.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Create new form with a date field and set max date to `moment()` (which is basically now)
2. Save the form
3. Navigate away from the form builder and then return and edit the form (or do a hard refresh) and check the value of the input field you were editing on the form builder

## Expected behavior

It shows me what I typed in not the calculated value.

## Observed behavior

It shows me the calculated/executed result (ie a date time string) not what I typed in.

**Comment by travist** [comment]
This is a known issue that we are aware of and is prioritized. I will re-elevate this in our planning meeting on Monday and let you know if priority changes. We may need some help from the community to solve this one.

**Comment by heather-formio** [comment]
Closing this as it is stale, please feel free to reopen at any time. Thank you!
