### ISSUE TITLE
Javascript Custom Default value in HTML Element

### ISSUE THREAD

**Issue by jftsaraiva** [formio/formio.js#1389]
In a HTML Element if I have a Custom Defaut Value like this:

```
value = data.downloadUrl;
```

how can I use it in `a` HTML Tag `<a href=""> ...`

![image](https://user-images.githubusercontent.com/2278476/59554689-a22d6700-8f9e-11e9-8863-1bdead2ee442.png)

In HTML Element the `value` (Javascript code) is never used - the functionality is not the same as the others components.

**Comment by jftsaraiva** [comment]
Yes, I understand that HTML are display only, but if I have this data:

```
submission: {
        data: {
          downloadUrl: 'http://www.example.com/file/test.pdf'
        }
      }
```

can I use HTML Element to render to this: ?

```
<a href="http://www.example.com/file/test.pdf">Download</a>
```

where `href` is a dynamic value from `submission.data.downloadUrl`.

or I need a custom component to do this?

**Comment by randallknutson** [comment]
Ah, you should be able to use this for the value: "{{data.downloadUrl}}" to render something like that.

**Comment by jftsaraiva** [comment]
I tried that, but with this configuration:

![image](https://user-images.githubusercontent.com/2278476/60614425-c2458e80-9dc4-11e9-9ebe-36e91d4925e4.png)

I'm getting:

![image](https://user-images.githubusercontent.com/2278476/60614583-13558280-9dc5-11e9-9eec-a065933c5d48.png)

It doesn't replaces interpolation with the string value of the corresponding component property.

**Comment by travist** [comment]
This just means we are not interpolating the attribute values. This could be added by changing this line

https://github.com/formio/formio.js/blob/master/src/components/html/HTML.js#L44

to the following.

```js
this.htmlElement.setAttribute(attr.attr, this.interpolate(attr.value));
```

If you submit a pull request we will consider making it a part of the renderer.

**Comment by kentferolino** [comment]
Hi @jftsaraiva , hope this would help.

I tried this one:
```
<a href='{{data.downloadUrl}}'>
     <div>Download</div>
</a>
```
This worked for me. Hopefully this would work for you.

**Comment by jftsaraiva** [comment]
Hi @kentferolino thanks, but I tried that and doesn't work
