### ISSUE TITLE
[BUG] Edit Grid and Data Map is not draggable; label is draggable when it shouldn't be.

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#1391]
## Environment
Please provide as many details as you can:
The demo project located at [https://formio.github.io/formio.js/app/builder](https://formio.github.io/formio.js/app/builder)

## Steps to Reproduce
1. Drag in an Edit Grid and a Data Map onto the form builder.
2. Click&drag the label (and edit/copy/remove controls) of each of the components.
3. Click and drag anywhere in the components except for the default contents

## Expected behavior
The label (and controls) shouldn't be draggable.
The control itself should be draggable.

## Observed behavior
The label (and controls) are able to be dragged and reordered.
The control cannot be dragged and reordered.

## Example
[image](https://user-images.githubusercontent.com/24515980/59580214-8f886e80-9113-11e9-8a0d-29ddcbc08010.png)

**Comment by heather-formio** [comment]
This is resolved. Closing issue. Thank you for contributing and using Form.io!
