### ISSUE TITLE
Form is submitted after click on "builder-group-button" (v4)

### ISSUE THREAD

**Issue by psmarsch** [formio/formio.js#1392]
The problem described in #981 does still appear in Version 4.0.0-beta.46.

Please add type="button" to the corresponding elements in the sidebar of the builder for that version as well.

**Comment by randallknutson** [comment]
Is this what you need? https://github.com/formio/formio.js/commit/9b4d9160e6c721e3fdf1fcea6a9eac6885dfd6ee

**Comment by psmarsch** [comment]
Yes, that looks good.
