### ISSUE TITLE
How to control the execution event of the delete button? Some components do not let delete

### ISSUE THREAD

**Issue by weixiaomiandui** [formio/formio.js#1396]
![image](https://user-images.githubusercontent.com/19527831/59679667-06039a00-9202-11e9-9784-0e84ee747dcd.png)
How to control the execution event of the delete button? Some components do not let delete
![image](https://user-images.githubusercontent.com/19527831/59679796-5f6bc900-9202-11e9-87cb-60f7903c2682.png)

**Comment by randallknutson** [comment]
It sounds like you want to make some components that are unable to be deleted from the form (have some fixed components). There currently isn't an easy way of doing this but we've had this request before and would be interested in adding it. The code for the delete button is at https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L77-L82. What could be done is to add a property to that field and make that logic conditional so the button doesn't show up if it should be disabled.

**Comment by weixiaomiandui** [comment]
![image](https://user-images.githubusercontent.com/19527831/59744122-74009d80-92a4-11e9-9948-9640afa1a631.png)
![image](https://user-images.githubusercontent.com/19527831/59744178-8d094e80-92a4-11e9-9796-f8ffdd04be6b.png)
Is that field in json? Is there a simple example?

**Comment by randallknutson** [comment]
The property currently doesn't exist. It would need to be added. We would accept a pull request for this or can get a support package in place to add it for you.
