### ISSUE TITLE
shows undefined after removing selected value from dropdown(select.js) [BUG] 

### ISSUE THREAD

**Issue by SwathiAdari27** [formio/formio.js#1404]
## Steps to Reproduce
1. add a dropdown with placeholder
2. select a value
3. click on remove item
4. shows undefined

## Expected behavior
should show provided placeholder.
## Observed behavior
shows undefined.
## Example
![image](https://user-images.githubusercontent.com/49482225/59826012-0d868880-9353-11e9-8b2c-c271170530cf.png)

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out! We are aware of this issue. For reference, the ticket number is FOR-2127. We have tagged you to this ticket. 

We will let you know once this issue is resolved.

Thanks.

**Comment by wag110894** [comment]
Hello,

This issue has been resolved in the latest version of our 3x formio.js Core Server (3.22.14).

Thanks!
