### ISSUE TITLE
Problem pre-filling data grid elements

### ISSUE THREAD

**Issue by dontfeedthecode** [formio/formio.js#141]
I have a data grid element where people can add x number of text fields, while I can pre-fill basic fields the grid does not behave in the same way when trying to pre-fill some of the form fields on page load.

```
  var form = new FormioForm(document.getElementById('formio'));
  form.src = 'path-to-form';
  form.submission = {
      data: {
        addressStreet: '123 Something Street', // works
        addressSuburb: 'Somewhere', // works
        addressPostcode: '40000', // works
        licencePlates: [
            {
                textField: "abc123"
            },
            {
                textField: "another"
            }
        ]
      }
    };
```

The address fields prefill and when doing a console.log on form.submission after adding some data grid items through the form itself it comes back in the same format as the pre-fill object.

Does the data grid component have any pre-fill ability at present? Is it limited to basic fields?

**Comment by travist** [comment]
This shows an example of a data grid being pre-populated with data. 

http://formio.github.io/formio.js/app/examples/datagrid.html

Are you experiencing something else where something like this usecase is not working?

**Comment by mojtaba-khallash** [comment]
Your example works fine, but if the values of the `Gender` field are load from url like this:

``` json
{
	"label": "Gender",
	"key": "gender",
	"type": "select",
	"input": true,
	"data": {
	  "url": "path/to/gender.json",
	},
	"dataSrc": "url",
	"template": "<span>{{ item.label }}</span>"
}
```

Again, the pre-filling data will load properly

![image](https://user-images.githubusercontent.com/3192517/82343332-f2f7dc00-9a07-11ea-8dd4-892e208e9858.png)

But as soon as you add a new item, pre-filling value of `Gender` are reset!

![image](https://user-images.githubusercontent.com/3192517/82343539-3e11ef00-9a08-11ea-9574-43732d534bf0.png)

I am using version "4.10.0-beta.19".

**Comment by wag110894** [comment]
@mojtaba-khallash,

Thanks for reaching out!

We are not seeing this issue on the examples page. Can you provide a video so we can replicate on our side?

**Comment by mojtaba-khallash** [comment]
This is the code I tested

[DataGridDemo.zip](https://github.com/formio/formio.js/files/4651480/DataGridDemo.zip)

**Comment by cmcortez** [comment]
@mojtaba-khallash we are unable to replicate your issue, as part of a support package we would be happy to assign a developer to meet with you and go over the issue with you. Please contact support@form.io if you are interested.

**Comment by rahulseth625** [comment]
@travist @cmcortez Can we do sorting , filtering and pagination in Data Grid ?

**Comment by dinbtechit** [comment]
When you have `Initialize Empty` checked, the data grid is not populated.

![image](https://github.com/user-attachments/assets/66c5c046-657c-4d17-8d7e-6cc8d9a70fe7)
