### ISSUE TITLE
[BUG] The search box of the drop-down box can control the loss of focus? Android and ios are not unified, how to achieve uniform display problems

### ISSUE THREAD

**Issue by weixiaomiandui** [formio/formio.js#1410]
![IMG_1900](https://user-images.githubusercontent.com/19527831/59998322-ab4ec000-9691-11e9-8adb-9ae1e210c1a0.JPG)
![IMG_1901](https://user-images.githubusercontent.com/19527831/59998323-ab4ec000-9691-11e9-8901-9a320395c2a4.PNG)
The search box of the drop-down box can control the loss of focus? Android and ios are not unified, how to do it

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
