### ISSUE TITLE
[BUG] textfield kept refreshing

### ISSUE THREAD

**Issue by homoujs** [formio/formio.js#1427]
Hi,I found that textfield kept refreshing.when I select a item from the selectbox, then value of the textfield was not changed.thanks,The code is as follows
{
    "display": "form",
    "components": [
        {
            "label": "s1",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "select",
            "input": true,
            "key": "s1",
            "defaultValue": "",
            "validate": {
                "select": false,
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "data": {
                "values": [
                    {
                        "label": "1",
                        "value": "1"
                    },
                    {
                        "label": "2",
                        "value": "2"
                    }
                ]
            },
            "valueProperty": "value",
            "selectThreshold": 0.3,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": [],
            "lazyLoad": false,
            "selectValues": "",
            "disableLimit": false,
            "sort": "",
            "reference": false,
            "tags": [],
            "reorder": false
        },
        {
            "label": "Text Field",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "textField2",
            "defaultValue": "1561697838297",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "inputFormat": "plain",
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": [],
            "calculateValue": "var curdate = new Date().getTime();\nvalue=curdate;",
            "refreshOn": "s1",
            "widget": {
                "type": ""
            },
            "reorder": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        },
        {
            "label": "Data Grid",
            "disableAddingRemovingRows": false,
            "addAnother": "",
            "addAnotherPosition": "bottom",
            "removePlacement": "col",
            "defaultOpen": false,
            "layoutFixed": false,
            "enableRowGroups": false,
            "reorder": false,
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "datagrid",
            "input": true,
            "key": "dataGrid2",
            "defaultValue": [
                {
                    "select": "1",
                    "ww": "ss"
                }
            ],
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "components": [
                {
                    "label": "Select",
                    "mask": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "select",
                    "input": true,
                    "key": "select",
                    "defaultValue": "",
                    "validate": {
                        "customMessage": "",
                        "json": "",
                        "custom": "row.ww=\"ss\";",
                        "select": false
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "data": {
                        "values": [
                            {
                                "label": "1",
                                "value": "1"
                            },
                            {
                                "label": "2",
                                "value": "2"
                            }
                        ]
                    },
                    "valueProperty": "value",
                    "selectThreshold": 0.3,
                    "encrypted": false,
                    "properties": {},
                    "customConditional": "",
                    "logic": [],
                    "row": "0-0",
                    "lazyLoad": false,
                    "selectValues": "",
                    "disableLimit": false,
                    "sort": "",
                    "reference": false,
                    "reorder": false
                },
                {
                    "label": "Text Field",
                    "allowMultipleMasks": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "textfield",
                    "input": true,
                    "key": "ww",
                    "defaultValue": "",
                    "validate": {
                        "customMessage": "",
                        "json": ""
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "widget": {
                        "type": ""
                    },
                    "properties": {},
                    "tags": [],
                    "reorder": false,
                    "inputFormat": "plain",
                    "encrypted": false,
                    "customConditional": "",
                    "logic": [],
                    "row": "0-1"
                }
            ],
            "groupToggle": false,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by wag110894** [comment]
Hello,
Thanks for reaching out!
Change "calculateValue": "var curdate = new Date().getTime();\nvalue=curdate;", to "customDefaultValue": "var curdate = new Date().getTime();\nvalue=curdate;",.

The reason it was refreshing was that you were grabbing the current date/time, which is always changing.

Hope this helps.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
