### ISSUE TITLE
The textfield in the datagrid is not updated[BUG] 

### ISSUE THREAD

**Issue by homoujs** [formio/formio.js#1430]
hi，I found a problem.I want change the textfield value in  select component validation.The textfield in the datagrid is not updated.
here is the code.

{
    "display": "form",
    "components": [
        {
            "label": "Data Grid",
            "disableAddingRemovingRows": false,
            "addAnother": "",
            "addAnotherPosition": "bottom",
            "removePlacement": "col",
            "defaultOpen": false,
            "layoutFixed": false,
            "enableRowGroups": false,
            "reorder": false,
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "datagrid",
            "input": true,
            "key": "dataGrid2",
            "defaultValue": [
                {
                    "s1": "",
                    "t1": ""
                }
            ],
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "components": [
                {
                    "label": "s1",
                    "mask": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "select",
                    "input": true,
                    "key": "s1",
                    "defaultValue": "",
                    "validate": {
                        "customMessage": "",
                        "json": "",
                        "custom": "if(value==\"1\")\n  row.t1=\"1\";\nelse if(value==\"2\")\n  row.t1=\"2\";",
                        "select": false
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "data": {
                        "values": [
                            {
                                "label": "1",
                                "value": "1"
                            },
                            {
                                "label": "2",
                                "value": "2"
                            }
                        ]
                    },
                    "valueProperty": "value",
                    "properties": {},
                    "selectThreshold": 0.3,
                    "encrypted": false,
                    "customConditional": "",
                    "logic": [],
                    "row": "0-0",
                    "reorder": false,
                    "lazyLoad": false,
                    "selectValues": "",
                    "disableLimit": false,
                    "sort": "",
                    "reference": false
                },
                {
                    "label": "t1",
                    "allowMultipleMasks": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "textfield",
                    "input": true,
                    "key": "t1",
                    "defaultValue": "",
                    "validate": {
                        "customMessage": "",
                        "json": ""
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "widget": {
                        "type": ""
                    },
                    "reorder": false,
                    "inputFormat": "plain",
                    "encrypted": false,
                    "properties": {},
                    "customConditional": "",
                    "logic": [],
                    "row": "0-1"
                }
            ],
            "groupToggle": false,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by homoujs** [comment]
[http://www.dccon.com.cn/noupdate.jpg](url)

**Comment by randallknutson** [comment]
What version of the renderer (formio.js) are you using?

**Comment by homoujs** [comment]
I use the version。
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
    <script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script>

**Comment by homoujs** [comment]
I test the version v3.22.14,The result is the same.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
