### ISSUE TITLE
Turn off form autocompletion

### ISSUE THREAD

**Issue by Inaamhusain** [formio/formio.js#1431]
Is there a way where we can turn off browser autocomplete? for both form and field level.
Using autocomplete="off" we can do that. but looking into formio with configurable.

**Comment by randallknutson** [comment]
Currently there is not. We are looking at adding the ability to customize the autocomplete attribute of input components which will hopefully be coming soon. You could then set it to off.

**Comment by Inaamhusain** [comment]
Thanks for the update.

**Comment by saravananshc** [comment]
@randallknutson is the turn off autocomplete off available in form.io 4.6.1

**Comment by jhen1422** [comment]
@saravananshc 
This feature is currently not available. As mentioned, we are hoping to implement this in the future

**Comment by Jibreel-Ahmed** [comment]
> Is there a way where we can turn off browser autocomplete? for both form and field level.
> Using autocomplete="off" we can do that. but looking into formio with configurable.

How you did it?

**Comment by SalTor** [comment]
@jhen1422 it's a year later, any update?

**Comment by wag110894** [comment]
Hello @SalTor, 

This is functionality that we are currently working on. We will let you know once it has been released.

**Comment by hugeps** [comment]
I can see there's autocomplete feature, but it sets value to "off" even if I provide alternative value. 
This behavior is not respected by Chrome. What should we do? Any way to ensure that value provided in JSON is passed as is, without modification?

**Comment by SalTor** [comment]
One option would be to disable it on the element level on page render (listen for "render" or "nextPage" or "prevPage" events from `form.on(event: string, (data: any) => {})`

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
