### ISSUE TITLE
Duplicate keys when we drag and drop colums component  "key" : "column"  is showing in every column  [BUG] 

### ISSUE THREAD

**Issue by Asifislam110** [formio/formio.js#1437]
## Environment
https://formio.github.io/formio.js/app/builder

## Steps to Reproduce
1. Go to Layout in side bar 
2. Drag and Drop Column Control and click on Save
3. See "JSON Schema" Panel 

## Expected behavior
{
    "display": "form",
    "components": [
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "type": "column",
                    "input": false,
                    "hideOnChildrenHidden": false,
                    **"key": "column1",**
                    "tableView": true,
                    "label": "Column"
                },
                {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "type": "column",
                    "input": false,
                    "hideOnChildrenHidden": false,
                    **"key": "column2",**
                    "tableView": true,
                    "label": "Column"
                }
            ],
            "mask": false,
            "tableView": false,
            "alwaysEnabled": false,
            "type": "columns",
            "input": false,
            "key": "columns2",
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "reorder": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}
## Observed behavior
{
    "display": "form",
    "components": [
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "type": "column",
                    "input": false,
                    "hideOnChildrenHidden": false,
                    **"key": "column",**
                    "tableView": true,
                    "label": "Column"
                },
                {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "type": "column",
                    "input": false,
                    "hideOnChildrenHidden": false,
                    **"key": "column",**
                    "tableView": true,
                    "label": "Column"
                }
            ],
            "mask": false,
            "tableView": false,
            "alwaysEnabled": false,
            "type": "columns",
            "input": false,
            "key": "columns2",
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "reorder": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by randallknutson** [comment]
What version of the formio.js library are you using? We have recently fixed this in the latest 4.x branch.

**Comment by Asifislam110** [comment]
we have downloaded demo angular application in which above mentioned issue is not fixed

Demo App Link here
https://formio.github.io/formio.js/app/builder

Can you please update demo as well

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
