### ISSUE TITLE
[BUG] Component in DataGrid stops working after Webform.setSubmission()

### ISSUE THREAD

**Issue by sebastianhaberey** [formio/formio.js#1440]
Hi, sorry for submitting all those bugs lately, it's just that we use Form.io JS a lot currently and that's why we stumble across them.

## Environment

- Formio.js version: 3.22.5

## Steps to Reproduce

1. open [codepen example](https://codepen.io/sebastianhaberey/pen/RzVXpp?editors=1111) 
2. changes in number field will show up in change event (see console)
3. enter number 42 in number field
4. press button "Set Submission" 
5. changes in number field won't show up in change event any more

**Comment by sebastianhaberey** [comment]
We believe that the core of the issue is components referencing outdated model data and our changes [here ](https://github.com/peichhorn-arxes/formio.js/commit/ee42dd61c784799594c5486c4b8d347ff1d57b3e) (don't setValue() on DataGrid's children if model hasn't changed) and [here ](https://github.com/peichhorn-arxes/formio.js/commit/599f1ada414323369f92d81ef4708f257afb0cd4)(setNestedValue of a NestedComponent passes the whole value along) could fix the issue.

We've been working on our fork for quite a long time, so I'm not sure they're 100 percent mergeable per pull request, but maybe the general idea can be of help.

**Comment by travist** [comment]
Thanks for reporting this. We will investigate. As for your pull request, we still have not had the bandwidth to pull this in and do some investigation on our end.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
