### ISSUE TITLE
How to check if the form is dirty?

### ISSUE THREAD

**Issue by prajaktaekal** [formio/formio.js#1446]
Hi,

I am using formio and trying to identify a way to find whether the form has some changes, which are not yet saved.

I tried with approach, which will check the old submission and new submission data. Unfortunately it fails if only some properties of submission are submitted to server. 

Is there any way or flag which will give information about whether the form is dirty or not?

**Comment by randallknutson** [comment]
Two ways.

1. You can listen to the "change" event any time someone changes a component on the form.
2. There should be a dirty or pristine flag somewhere on the form instance itself that you can check. I'm not sure where it is at the moment but you should be able to find it in a debugger.

**Comment by prajaktaekal** [comment]
There is no any dirty flag. I'm getting Pristine flag but it always returns to true, even if form is not changed. Is there any other way?

**Comment by travist** [comment]
What version of the renderer are you using? If 4.x, then we have recently made some changes that fixes the pristine flag for 4.x and will be included in the next RC release.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
