### ISSUE TITLE
Cannot update panel's title with "logic" [BUG] 

### ISSUE THREAD

**Issue by kamsi** [formio/formio.js#1447]
See the below form schema:

`{
    "display": "form",
    "components": [
        {
            "label": "totalCost",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "number",
            "input": true,
            "key": "totalCost",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "reorder": false,
            "delimiter": false,
            "requireDecimal": false,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "label": "Panel",
            "title": "Fee",
            "collapsible": false,
            "mask": false,
            "tableView": false,
            "alwaysEnabled": false,
            "type": "panel",
            "input": false,
            "key": "panel",
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "components": [
                {
                    "label": "Text Field",
                    "allowMultipleMasks": false,
                    "showWordCount": false,
                    "showCharCount": false,
                    "tableView": true,
                    "alwaysEnabled": false,
                    "type": "textfield",
                    "input": true,
                    "key": "textField",
                    "defaultValue": "",
                    "validate": {
                        "customMessage": "",
                        "json": ""
                    },
                    "conditional": {
                        "show": "",
                        "when": "",
                        "json": ""
                    },
                    "widget": {
                        "type": ""
                    },
                    "reorder": false,
                    "inputFormat": "plain",
                    "encrypted": false,
                    "properties": {},
                    "customConditional": "",
                    "logic": []
                }
            ],
            "properties": {},
            "customConditional": "",
            "logic": [
                {
                    "name": "resolveTitle",
                    "trigger": {
                        "type": "json",
                        "json": {
                            ">": [
                                {
                                    "var": "data.totalCost"
                                },
                                0
                            ]
                        }
                    },
                    "actions": [
                        {
                            "name": "resolveTitle",
                            "type": "property",
                            "property": {
                                "label": "Title",
                                "value": "title",
                                "type": "string"
                            },
                            "text": "Fee: {{data.totalCost}}"
                        }
                    ]
                }
            ],
            "collapsed": false,
            "reorder": false
        },
        {
            "label": "This works",
            "allowMultipleMasks": false,
            "showWordCount": false,
            "showCharCount": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "textfield",
            "input": true,
            "key": "thisWorks",
            "defaultValue": "",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "widget": {
                "type": ""
            },
            "logic": [
                {
                    "name": "resolveLabel",
                    "trigger": {
                        "type": "json",
                        "json": {
                            ">": [
                                {
                                    "var": "data.totalCost"
                                },
                                0
                            ]
                        }
                    },
                    "actions": [
                        {
                            "name": "resolveLabel",
                            "type": "property",
                            "property": {
                                "label": "Label",
                                "value": "label",
                                "type": "string"
                            },
                            "text": "Fee: {{data.totalCost}}"
                        }
                    ]
                }
            ],
            "reorder": false,
            "inputFormat": "plain",
            "encrypted": false,
            "properties": {},
            "customConditional": ""
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}`

I have pretty much same logic to change the panel's title and the "thisWorks" label. Whe my cost is > 0 the label of "thisWorks" gets updated correctly, but panel is broken. I would expect that panel's title will be updated just like a label.

**Comment by wag110894** [comment]
Hello Kamil,

Thanks for reaching out!

We are unable to replicate this issue on our side. [Here](https://www.screencast.com/t/0f1xVh1i1K) is a screencast of this working using the latest version of formio.js (3.23.0) via JSFiddle.  

Please let me know the version number that you are experiencing this issue in.

Thanks.

**Comment by kamsi** [comment]
Well, that video exactly shows the problem I described.
Please notice what gets updated - not the panel's title. What gets updated is the label of "thisWorks" component, while the panel remains out of the view (or is represented by the line between components).

**Comment by wag110894** [comment]
My apologies for misunderstanding the issue. We have created a ticket and have added it to our backlog. 

We will let you know once this issue is resolved.

**Comment by kamsi** [comment]
Thank you!

**Comment by jtamm-red** [comment]
I solved. PR: https://github.com/formio/formio.js/pull/1485
