### ISSUE TITLE
Instantiate FormioWizard Class

### ISSUE THREAD

**Issue by bohan** [formio/formio.js#1450]
Setting display to "wizard" returns the following message on the console 
"You need to instantiate the FormioWizard class to use this form as a wizard"
and the form doesn't render on the UI. Instead I get the following message on the UI 
"Unknown component: custom". Here is the JSON
```
{
  "title": "My Wizard",
  "type": "form",
  "display: "wizard",
  "components": [
    {
      "type": "panel",
      "title": "Page 1",
      "components": [ ]
    },
    {
      "type": "panel",
      "title": "Page 2",
      "components": [ ]
    }
  ]
}
```
Using formiojs v3.23.0

**Comment by randallknutson** [comment]
You may be importing Webform instead of Form. If you use Form it will instantiate the correct class for Webform, Wizard and PDF. If you directly import Webform then it will fail if you try to use a different type.
