### ISSUE TITLE
Need to add carousel component in formbuilder

### ISSUE THREAD

**Issue by Tarni-Baghel** [formio/formio.js#1451]
Hi Team,

I have created custom formbuilder using the following link:
https://formio.github.io/formio.js/app/examples/custombuilder.html

Now I want to add carousel component on formbuilder. Can you help me how to create carousel component for formbuilder?

**Comment by wag110894** [comment]
Hello Tarni-Baghel,

Thanks for reaching out!

Form.io offers Support Packages to help you make the most of Form.io. Let us know if you are interested and I’ll send over pricing.

Our support packages are for training, support or development services. The hours can be used in one hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.

Please let us know if you are interested in our support package by contacting us at support@form.io

Thanks.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
