### ISSUE TITLE
How to customize submit action for wizard form

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#1457]
If we display form as wizard then prev, next and submit buttons are adding at run time so not able to customize for submit button from builder.

we can handle if it is single from renderer with .wizard(function(){}) but we want to have different action for each wizard form which can be customized from builder.

Is there way to achieve this?

Thanks.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
