### ISSUE TITLE
How can I build formio.js library locally

### ISSUE THREAD

**Issue by abdullahqudeer** [formio/formio.js#1458]
## Environment
angular 8

I have downloaded formIo.js library project from https://github.com/formio/formio.js.

Now I want to build it locally and want to use it in my some other project instead of installing it from NPM.

Please guide me step by step process to create its build.

**Comment by aiwebb** [comment]
Hi @abdullahqudeer, there is a Gulp `build` task that you can invoke to run through the build process.

**Comment by abdullahqudeer** [comment]
Hi @aiwebb ,it worked..... thanks
