### ISSUE TITLE
Data Table [Feature]

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [formio/formio.js#1465]
First of all thanks for such an amazing library, I being using it for my hobby project for a while. 

**Form Builder** and **Form Render** is working pretty well, now I want to implement data table, I can't find documentation of even in source code in `formio.js` to do it but I see it in angular project
[FormioGridModule](https://formio.github.io/angular-demo/#/data).

since I don't use angular is there anyway i can implement data table with this pure js library `formio.js`.

Thanks,

**Comment by wag110894** [comment]
Hello, 
We do not have a vanilla js library the formio-grid, however we do have it available in React as well as Angular.  

Hope this helps.
Thanks.

**Comment by kyawkyawsoezhu** [comment]
I found it in [ReactJS](https://github.com/formio/react-formio#formgrid) but I think it's not the same as [formio-grid,](https://formio.github.io/angular-demo/#/data), formio-grid is for showing submission data such as name, email, phone number, but formgrid of ReactJS is to show forms list.

I could be wrong about ReactJS formgrid, can you please show me example of how to use ReactJS formgrid with [codesandbox](https://codesandbox.io/) 

thanks @wag110894

**Comment by travist** [comment]
What you are looking for is the SubmissionGrid https://github.com/formio/react-formio/blob/master/src/components/SubmissionGrid.js

**Comment by kyawkyawsoezhu** [comment]
Thanks @travist
