### ISSUE TITLE
Question  How to use Formio.pluginAlter('requestOptions', options, url)?

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1468]
Hello

Is there any documentation on how to create a plugin that can be executed for:

```js
 options = Formio.pluginAlter('requestOptions', options, url);
```

I'm assuming I create a plugin add add it to:

```js
Formio.plugins
```

I would like to intercept the options and add some additional headers.  

Thanks

**Comment by wag110894** [comment]
Hello Amin, 

Thanks for reaching out!  This would take us about an hour to write up some examples of this. We can allocate someone against your support contract to develop this for you.

Please let me know if you are interested.

Thanks.

**Comment by aminmc** [comment]
Hello. I think this should be documented as part of the api for Formio unless this feature is supposed to be part of the enterprise edition. It would be helpful to document what the plugin api looks like and then we can test ourselves.

**Comment by aminmc** [comment]
@wag110894 I've managed to workout how the plugin is being used. 
```js
 Formio.plugins = [{
            priority: 0,
            requestOptions: function (value) {
                value.headers.append("Authorization", <Bearer Token loaded>);
                return value;
            }
        }];
```
