### ISSUE TITLE
[BUG] Builder crashes

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1469]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.6
- Frontend framework: react-formio 4.0.0-beta.28
- Browser:
- Browser version:
Trying to create a form with formbuilder results in the following:

![Screenshot 2019-07-12 at 07 01 19](https://user-images.githubusercontent.com/290639/61105843-04309d80-a473-11e9-9cf7-46d4a0c0cdec.png)

This happens straight after trying to render formio.

**Comment by wag110894** [comment]
Hello, 

Thanks for reaching out!

We have created a ticket and have added this to our backlog. 

We will let you know once this is resolved.

**Comment by aminmc** [comment]
No longer an issue with latest build so closing. Thanks
