### ISSUE TITLE
Nested form missing in preview pane (builder view)

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1470]
This is more of a question and I'm trying to work out why a nested form is not appearing in the preview pane in builder view. I can see the form in the drop down list and I can debug to a point where the sub form has been loaded into the formio code but I'm slightly lost where to pin point the actual bit of code that should display the nested form component.

Any advice on which bit of code to look would be helpful.

**Comment by randallknutson** [comment]
The form component handles the nested form. https://github.com/formio/formio.js/blob/master/src/components/form/Form.js

**Comment by aminmc** [comment]
Just to double check it is also responsible for the preview part in the builder?

**Comment by aminmc** [comment]
@randallknutson I can see the sub form being loaded and it being set in 
```js
this.subForm
```
Just can't work out why it's not appearing in the preview pane:

<img width="1143" alt="Screenshot 2019-07-14 at 12 17 51" src="https://user-images.githubusercontent.com/290639/61182870-6b944c00-a631-11e9-96d5-0b315645770a.png">

**Comment by randallknutson** [comment]
I'm not sure why this is happening. What version of formio.js are you using?

**Comment by aminmc** [comment]
Using 4.x version locally https://github.com/randallknutson. The form has been loaded

**Comment by aminmc** [comment]
Not sure if it’s a semantic theme issue but if that was the case it should fallback to default view.

**Comment by wag110894** [comment]
Hello,
 
We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested.  Our developers have estimated this fix at 4 hours.  We will have this fixed by the end of the year regardless.
Please let us know if you are interested and we can send over a formal quote.
 
Thanks.

**Comment by aminmc** [comment]
Hello. Just wondering if there was an update to this?

**Comment by wag110894** [comment]
Hello Amin, 

This is a top priority of our 4x Core Renderer. 

We will let you know once this item has been resolved.

Thanks.

**Comment by pixie79** [comment]
Hi,

I note you have closed this - does that mean it is fixed or on the backlog still?

Thanks

Mark

**Comment by wag110894** [comment]
Sorry. Did not mean to close this item.

**Comment by aminmc** [comment]
Hello @randallknutson and team is there any updates on this?  I've upgraded formio js and currently  seeing:
<img width="1151" alt="Screenshot 2019-09-04 at 07 24 31" src="https://user-images.githubusercontent.com/290639/64230615-385d9300-cee5-11e9-91a3-a66d2fec9075.png">

You can't click on Save no errors in the console.  We're in need of this feature so any help with this would be appreciated.

**Comment by jhen1422** [comment]
@aminmc 
Similar to 1559, we are still working on our backlog items but this is high on the list for our dev team to complete. Thanks

**Comment by travist** [comment]
This is fixed in the latest build.

**Comment by aminmc** [comment]
@travist Good news ...I can see the form in the builder pane however when I hit save button nothing happens. No console errors just no action after hitting save.

**Comment by aminmc** [comment]
@travist we're experiencing some weird behaviour.  After the upgrade I could see the forms in the sub form list. However this has stopped working now and we're seeing the following infinite loop:

![Screenshot 2019-09-06 at 09 00 38](https://user-images.githubusercontent.com/290639/64411345-dcca0b80-d084-11e9-9403-6aba7f070c95.png)

There is a request to the backend to load the requested form and the server is responding correctly with the sub form.

**Comment by travist** [comment]
Thanks @aminmc. I am looking into some of these weird issues right now, although the issue I am working on is different from what you described. The issue I am working on relates to when you set the form, you cannot "unset" the form for some reason as well as the Select dropdown shows the ID of the form instead of the name once selected. 

Is there a way you can provide a fiddle of this issue occurring?  I have not seen these errors with my examples.

**Comment by aminmc** [comment]
I’ll try to reproduce but I think I’m seeing the same thing you mentioned. It worked the first time and then basically it stopped. If I select another form it would work and the stop if I try to re select. It’s been a long day I probably don’t make sense 🥺

**Comment by aminmc** [comment]
@travist I can now see nested form appearing in the builder preview however I've noticed that it's infinitely adding the nested form in the builder.  This seemed to have happened when I added a formVersion number.  Even after removing the version number it's infinitely adding the sub form:

<img width="1158" alt="Screenshot 2019-09-11 at 06 58 40" src="https://user-images.githubusercontent.com/290639/64671940-eaefa180-d461-11e9-8de9-3b0b20220eca.png">

I'm doing this:

```
Formio.plugins = [{
            priority: 0,
            preRequest: async function (requestArgs) {
                if (!requestArgs.opts.header) {
                    requestArgs.opts.header = new Headers({
                        'Accept': 'application/json',
                        'Content-type': 'application/json; charset=UTF-8'
                    });
                }
                const token = //load bearer token which is a. promise
                requestArgs.opts.header.set('Authorization', `Bearer ${token}`);
              
                return Promise.resolve(requestArgs);
            }
        }
```

The reason being that we have a keycloak in front of the api. Not sure if this could cause a problem. It was working yesterday only failed once I added the formVersion. Not sure if they;'re related.

**Comment by aminmc** [comment]
@travist Looks like nested forms is working. Just a quick question is formVersion supposed to work? I've added a formVersion but it doesn't seem to be loading the exact version. I've checked the network tab and there isn't a call to get the specific version. Just seems to be the latest version.

**Comment by randallknutson** [comment]
formRevision should be working. You can see the code for it here: https://github.com/formio/formio.js/blob/master/src/components/form/Form.js#L86-L88

**Comment by aminmc** [comment]
Hi Randall. I can see that working but there isn’t a call to get the specific version.

**Comment by travist** [comment]
Ok, we may need to add that as a bug in our backlog. I think that should be a separate bug though so we can close this one.
