### ISSUE TITLE
Modify CKEditor Options

### ISSUE THREAD

**Issue by du8die** [formio/formio.js#1471]
I am currently using the Content Component - and have the need to embed images. That works fine. However, there are no options in CKEditor that will allow resizing or repositioning of images. 

Is there a way to allow users more control over the CKEditor?

Worst case scenario, can we have access to the Edit Source function of CKEditor?

Thanks

**Comment by du8die** [comment]
Sorry - didn't intentionally add the "bug" label - and now can't get rid of it.

**Comment by randallknutson** [comment]
I don't believe there is currently any way of doing this. If you'd like to add this as a new feature, we can connect you with our support team to see about developing it for you or you could contribute the code for it.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
