### ISSUE TITLE
Validation of un-required email field 

### ISSUE THREAD

**Issue by lookatmypinky** [formio/formio.js#149]
Trying to embed a form using the one-liner script tag outlined here[1], served in a flat page using:

    <script src="https://unpkg.com/formiojs@latest/dist/formio.embed.min.js?
        src=https://examples.form.io/example"></script>

Can't seem to apply any kind of validation to an email component without the validation being applied to an empty field.  Effectively, the submit dismisses my un-required/empty field as being improperly formatted.   

Although the submit error is technically accurate, it doesn't seem appropriate for this case.  Am I misinterpreting the intended behavior? 

[1] https://github.com/formio/formio.js/wiki/Form-Renderer#form-embedding

**Comment by travist** [comment]
I agree with this. We will fix in next release.

**Comment by jhen1422** [comment]
This issue has been resolved

**Comment by akapei** [comment]
Issue remains for text fields.
