### ISSUE TITLE
[BUG] Can't add components in tabs

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1496]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0.-rc-12
- Frontend framework: react
- Browser: chrome
- Browser version:

Currently we are unable to add components to tab component.

**Comment by aminmc** [comment]
any updates on this issue?

**Comment by travist** [comment]
We are aware and this is now a high priority for us. We will take a look.

**Comment by travist** [comment]
This is now fixed with latest.
