### ISSUE TITLE
Need Help in passing custom token with Service url

### ISSUE THREAD

**Issue by Theaggarwal** [formio/formio.js#1498]
Hi,

In my angular 7 application, i want to use "angular-formio" and "formiojs". I able to show the form on the application. I am not doing any login/authentication/registration with formio in my application.
Now i want to populate dropdown by fetching data from my service. Now that service requires token.  
**Question is now do i pass token to that our own service, without login/authentication/registering with formio??** 
I tried to assign the token before rendering the form-builder, but it starts giving the error.
![image](https://user-images.githubusercontent.com/20251397/61801969-526b7680-ae4d-11e9-9dc8-1cafb49ffef9.png)
![image](https://user-images.githubusercontent.com/20251397/61802012-61eabf80-ae4d-11e9-9413-c15ed57d7343.png)

**Comment by travist** [comment]
The select dropdown control allows you to provide your own Headers to the request, and this is where you would provide the headers that are needed for authentication. This is just done in the Select component configuration.

**Comment by Theaggarwal** [comment]
Since this token is dynamic, and if i placed in headers, then user will able to see that token. so i don't want to show this to anyone ... is there any alternative ???

**Comment by travist** [comment]
You can make the value of this token dynamic using something like.

```
{{ metadata.token }}
```

And then can be dynamically set with the submission metadata as follows.

```
form.submission.metadata.token = 'dynamic value here.';
```

**Comment by Theaggarwal** [comment]
but i dn't want to show token to user. i want to handle it internally (in js behind the scenes). that is , if url that user entered belongs to specific list of sites then i will append the token while fetching data otherwise i don't need that.

**Comment by travist** [comment]
If you don't want to show the token, then you will need to have an API proxy to send the JWT token to, and it will validate the user and then proxy the request you wish to make with the private token. This would need to be done with a custom JavaScript controller around the form so that exceeds what can be done within a simple github issue response. If you need resolution to this, then we do sell support packages where a developer could help you develop this controller.
