### ISSUE TITLE
[BUG] Infinite loop error in calculated value of WYSIWYG Editor

### ISSUE THREAD

**Issue by shai93** [formio/formio.js#1505]
I have two fields one is text field and WYSIWYG Editor. I want the value of text field into WYSIWYG Editor, so whenever text filed value get changed it should come inside editor.
 
Below code which i have written in calucated value of editor 

`console.log('aaa)`
`value=data.textField`

But console.log runs in infinite loop, due to which i'm unable to write anything in WYSIWYG Editor.

![image](https://user-images.githubusercontent.com/33196878/61856693-47adf180-aee0-11e9-8f00-6551ab2a000c.png)

**Comment by aiwebb** [comment]
Thanks @shai93 - can you let us know what version of formio.js you're using?

**Comment by shai93** [comment]
I have created form in formiojs builder(V 3.21.1) and using in angular-formio(V 3.10.2)

**Comment by shai93** [comment]
Hi @aiwebb any solution for this? i'm still facing the same problem

**Comment by aiwebb** [comment]
Are you seeing it in the latest versions? (formio.js@3.24.3, angular-formio@3.25.0)

**Comment by shai93** [comment]
I have updated formio Version but still getting the same error, infinite loop detected.

**Comment by aiwebb** [comment]
Thanks @shai93 - we've confirmed it on latest and have added it to our backlog for investigation.

**Comment by jhen1422** [comment]
@shai93 This should be resolved in the latest version of our 4x renderer
