### ISSUE TITLE
DataGrid cannot save data that has been thrown by a button custom action

### ISSUE THREAD

**Issue by Sundered** [formio/formio.js#1514]

**Comment by Sundered** [comment]
> _No description provided._

**Comment by wag110894** [comment]
Hello Sundered,
Can you provide some context on this issue? 

What version of formio.js are you using?

**Comment by Sundered** [comment]
hello WG,how can i import data into a datagrid with a button custom action,problem is that i cant use form.submit() method.do we have any other method exceptexcept form.submit() to save data in datagrid?here is the code im using in button custom action:

var wePurposeDate = data.wePurposeEnumId1;var cableLayList = [];var innerMp = {};if(wePurposeDate.toString().includes("akmCableLay")){    var ary = ["PartyChief","SeniorSurveyor","Surveyor","FieldEngineer"        ,"SeniorCableEngineer","CableEngineer","TensionerOperator"        ,"SeniorTesterAndJointer","TesterAndJointer","RiggerForeman","Rigger"];    var num = [2,1,1,2,1,1,1,1,1,1,5];    for(var i = 0;i < ary.length;i++){      innerMp ={'wePurposeEnumId' : "akmCableLay",      'roleTypeId' : ary[i],'facilityId' : "akm"      ,'quantity' : num[i]}      cableLayList.push(innerMp)    }    form.getComponent("cableLay").setValue(cableLayList);}
    On Monday, July 29, 2019, 04:39:23 PM GMT+4:30, Will Gay <notifications@github.com> wrote:  
 
 
Hello Sundered,
Can you provide some context on this issue?

What version of formio.js are you using?

**Comment by randallknutson** [comment]
We're still not entirely sure what you are trying to do. You may be able to do something like this: http://formio.github.io/formio.js/app/examples/externalload.html
