### ISSUE TITLE
You can upload multiple files even if it's Multiple Values are not checked on a File Component

### ISSUE THREAD

**Issue by marcosamorim** [formio/formio.js#1518]
* Add a File Component to a form
* Leave the option Multiple Values unchecked.
* Upload a file (larger one would work better)
* While the file is being uploading, you can add more files to the field.
* All files are uploaded.

**Comment by ashishbansal-xooa** [comment]
Yes the issue is persistent.

**Comment by uniu** [comment]
I meet also problem. Specially i You have slow network (or simulate it using limitation of speed) then you can add more files that will break limitation of attachment size (breaks validation).

**Comment by heather-formio** [comment]
The validations for this behavior for File Component exist in formio-enterprise. To utilize in Open Source, this would need to be developed to function in this way.
