### ISSUE TITLE
[BUG] ChoicesJS and Radio/Check boxes

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1530]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ x] Local deployment
    - Version:  
- Formio.js version: 4.0.0.-rc-20
- Frontend framework: react-formio
- Browser: chromse
- Browser version:

## Steps to Reproduce
1. Create a wizard
2. Add a select component with ChoicesJS and URL source
3. Add second Page
4. Add radio with 2 options
5. Save form
6. Select from drop down page in Page 1
7. Go to Page 2 and select radio option
8. Page 1 selection has been wiped clean

## Expected behaviour
Going back to Page 1 after selecting an option should not clear the drop down selected in page 1. 

Folks this is a critical issue for us. This was working fine before 4.x, and this has effectively caused all of our forms to stop working when we have select boxes using ChoicesJS and radio buttons. Can someone please investigate this issue as soon as possible?

**Comment by aminmc** [comment]
Also might be related to this:
https://github.com/formio/formio.js/issues/1492

**Comment by wag110894** [comment]
Hello Amin,

Thanks for reaching out! We were able to discuss this item on our Afternoon Call and did deem it as a High Priority item. We will let you know once this item is resolved.

Thanks

**Comment by travist** [comment]
This will be resolved when ^ is merged.  Should be later today.

**Comment by aminmc** [comment]
This is working as expected.  Thank you guys!
