### ISSUE TITLE
[BUG] Datagrid remove item causes Next button on wizard to stop working

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1533]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.20
- Frontend framework: react-formio
- Browser: chromse
- Browser version:

## Steps to Reproduce
1. Create a wizard with 2 pages
2. First page add a data grid with text field component
3. Make text field mandatory
4. Second page add any component

## Expected behavior
On Page 1 if i add or remove a data item i should be able to navigate to the next page (even if one data item is present)
## Observed behavior
Next button does not work after removing items from the data list on the first page.

Use attached zipped json

[json2.json.zip](https://github.com/formio/formio.js/files/3459808/json2.json.zip)

**Comment by jhen1422** [comment]
@aminmc 
After testing the issue, we were unable to replicate. Wizard 'Next' navigation was executing properly when Datagrid item was present. Here is a video showing the test result. https://www.screencast.com/t/Eioxl8FxLba

If you are still experiencing this issue, could you provide a jsfiddle that shows the problem?

**Comment by aminmc** [comment]
Hi https://github.com/jhen1422 I will try to create a jfiddle. The json schema should replicate the issue.

**Comment by aminmc** [comment]
Also you need to add an additional item and then remove the second item.

**Comment by aminmc** [comment]
@jhen1422 it's reproducible with the following steps:
1. Load form
2. Remove the text field component inside the data grid (basically no entries)
3. Click 'Add Another'
4. Type something into the text field
5. Hit next

Next button doesn't work.

**Comment by travist** [comment]
I have tried your steps and cannot reproduce with latest build.

**Comment by aminmc** [comment]
Will try again if there is another release later. Thanks guys appreciate your help!

**Comment by travist** [comment]
Should be good now.
