### ISSUE TITLE
Can't able to choose multiple file in file component

### ISSUE THREAD

**Issue by sudhakar29495** [formio/formio.js#1541]
If I checked Multiple values in the File component I can able to drag multiple files, but I can't able to browse multiple files. This is happening because of multiple property not added in the input box.
![imageedit_5_5937587074](https://user-images.githubusercontent.com/20576960/62466982-503fdb00-b7b0-11e9-9991-7ba57077eb7c.gif)

**Comment by randallknutson** [comment]
What version of the formio.js library are you using?

**Comment by sudhakar29495** [comment]
I'm using version 3.18.0

**Comment by jhen1422** [comment]
Please try using our latest version of our formio.js renderer. This should resolved the issue.
