### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Pramodf** [formio/formio.js#1543]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: formiojs@3.23.3
- Frontend framework: angular-form@3.12
- Browser: Chrome 
- Browser version: 

## Steps to Reproduce
1.  Create onChange for first datefield 
2. Write logic for updating minDate of 2nd field 

## Expected behavior
3. When user select date in first field, it should become minDate for 2nd field

## Observed behavior
minDate property not getting changed which was working in earlier version.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

Logic Object for 2nd field:

"logic": [
                {
                  "trigger": {
                    "type": "simple",
                    "simple": {
                      "when": "W15_WELL_CHLD_VST_DOS",
                      "eq": "",
                      "show": false
                    }
                  },
                  "actions": [
                    {
                      "type": "property",
                      "property": {
                        "type": "string",
                        "value": "datePicker.minDate"
                      },
                      "text": "2000-05-05"
                    },
                    {
                      "type": "property",
                      "property": {
                        "type": "boolean",
                        "value": "disabled"
                      },
                      "state": false
                    }
                  ]
                },
                {
                  "trigger": {
                    "type": "simple",
                    "simple": {
                      "when": "W15_WELL_CHLD_VST_DOS",
                      "eq": "",
                      "show": true
                    }
                  },
                  "actions": [
                    {
                      "type": "property",
                      "property": {
                        "type": "string",
                        "value": "datePicker.minDate"
                      },
                      "text": "01/01/1970"
                    },
                    {
                      "type": "property",
                      "property": {
                        "type": "string",
                        "value": "datePicker.maxDate"
                      },
                      "text": "01/01/1970"
                    }
                  ]
                },
                {
                  "trigger": {
                    "type": "simple",
                    "simple": {
                      "when": "W15_EXCLSN_FLG_OPTNL",
                      "eq": true,
                      "show": true
                    }
                  },
                  "actions": [
                    {
                      "type": "property",
                      "property": {
                        "type": "boolean",
                        "value": "disabled"
                      },
                      "state": true
                    },
                    {
                      "type": "property",
                      "property": {
                        "type": "boolean",
                        "value": "validate"
                      },
                      "state": false
                    }
                  ]
                },
                {
                  "trigger": {
                    "type": "simple",
                    "simple": {
                      "when": "W15_EXCLSN_FLG_MNDTRY",
                      "eq": true,
                      "show": true
                    }
                  },
                  "actions": [
                    {
                      "type": "property",
                      "property": {
                        "type": "boolean",
                        "value": "disabled"
                      },
                      "state": true
                    },
                    {
                      "type": "property",
                      "property": {
                        "type": "boolean",
                        "value": "validate"
                      },
                      "state": false
                    }
                  ]
                }
              ]
            },
// your code here
```

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
