### ISSUE TITLE
select component rendering error in viewAsHtml model

### ISSUE THREAD

**Issue by huzech** [formio/formio.js#1545]
When I set { readOnly: true,viewAsHtml:true } in createForm.  The select component does not display value, but '-' replace. I think it is a bug.
Sorry Some times works, some times not work, I'm trying to reproduce

**Comment by randallknutson** [comment]
What version of formio.js are you seeing this with?

**Comment by huzech** [comment]
I use 3.x, and I found when the value is Number it won't show, if the value is string it will show

**Comment by aiwebb** [comment]
@huzech, can you post some example form JSON that reproduces this?

**Comment by bleungAtGTI** [comment]
I found some [example](https://jsfiddle.net/o10gepsx/1/)
@aiwebb

**Comment by jhen1422** [comment]
@bleungAtGTI Thank you for the report. We have created a ticket for the issue and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing

**Comment by jhen1422** [comment]
@bleungAtGTI 
Can you please confirm if this is an issue using our 4x renderer? Latest is 4.6.0

**Comment by bleungAtGTI** [comment]
https://jsfiddle.net/0Lvtaxes/
Still on 4.6.1

**Comment by jhen1422** [comment]
@bleungAtGTI 
Thank you for the update

**Comment by bobslee** [comment]
Hi, any update?
This issue still remains in version 4.9.26.

**Comment by jhen1422** [comment]
@bobslee This ticket is still in our backlog and we don't have a timeline on when this item will be prioritized. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by bobslee** [comment]
That's not necessary. Let's wait on your planning and need :)

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
