### ISSUE TITLE
Can i get submission more than 10?

### ISSUE THREAD

**Issue by kajohnsakk** [formio/formio.js#1546]
When i call api for get submission, form.io will response 10 submission(i think default is 10). How i will get submission more than 10(not use limit in query string).

Thank you for help.

**Comment by randallknutson** [comment]
You can add &limit=100 to the request querystring to get more. Is there a reason that you can't use the querystring?

**Comment by kajohnsakk** [comment]
I need to get all data submission and i need to know how many all submission.

**Comment by CharlyPoppins** [comment]
> I need to know how many and get all data submission.

@kajohnsakk how did you manage to know how many submissions a form has ?
