### ISSUE TITLE
Much duplicate code in form components

### ISSUE THREAD

**Issue by psmarsch** [formio/formio.js#1548]
Hi form.io,

I am about to write a complex custom form component and while looking at your own components, I discovered much duplicate code.

Is this really necessary? It makes it very confusing when cloning/extending them - don't want to further duplicate those duplicates. Plus, I can imagine that it would be easier for you to maintain the code as well if you could collect these bits somewhere else and reuse them.

Please find the code parts in question listed below, descendingly ordered by the cost of their duplication. Its for ./components (@4.0.0-rc.25).

12 times:
`function set(target, property, value, receiver) { if (typeof Reflect !== "undefined" && Reflect.set) { set = Reflect.set; } else { set = function set(target, property, value, receiver) { var base = _superPropBase(target, property); var desc; if (base) { desc = Object.getOwnPropertyDescriptor(base, property); if (desc.set) { desc.set.call(receiver, value); return true; } else if (!desc.writable) { return false; } } desc = Object.getOwnPropertyDescriptor(receiver, property); if (desc) { if (!desc.writable) { return false; } desc.value = value; Object.defineProperty(receiver, property, desc); } else { _defineProperty(receiver, property, value); } return true; }; } return set(target, property, value, receiver); }`

41 times:
`function _get(target, property, receiver) { if (typeof Reflect !== "undefined" && Reflect.get) { _get = Reflect.get; } else { _get = function _get(target, property, receiver) { var base = _superPropBase(target, property); if (!base) return; var desc = Object.getOwnPropertyDescriptor(base, property); if (desc.get) { return desc.get.call(receiver); } return desc.value; }; } return _get(target, property, receiver || target); }
`

46 times:
`function _typeof(obj) { if (typeof Symbol === "function" && typeof Symbol.iterator === "symbol") { _typeof = function _typeof(obj) { return typeof obj; }; } else { _typeof = function _typeof(obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }; } return _typeof(obj); }`

27 times:
`"use strict"; Object.defineProperty(exports, "__esModule", { value: true }); Object.defineProperty(exports, "comp1", { enumerable: true, get: function get() {  return _comp2.default; } }); var _comp2 = _interopRequireDefault(require("./comp1")); function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`

46 times:
`function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function"); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, writable: true, configurable: true } }); if (superClass) _setPrototypeOf(subClass, superClass); }`

19 times:
`function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }`

42 times:
`function _superPropBase(object, property) { while (!Object.prototype.hasOwnProperty.call(object, property)) { object = _getPrototypeOf(object); if (object === null) break; } return object; }
`

46 times:
`function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }
`

46 times:
`function _getPrototypeOf(o) { _getPrototypeOf = Object.setPrototypeOf ? Object.getPrototypeOf : function _getPrototypeOf(o) { return o.__proto__ || Object.getPrototypeOf(o); }; return _getPrototypeOf(o); }`

46 times:
`function _possibleConstructorReturn(self, call) { if (call && (_typeof(call) === "object" || typeof call === "function")) { return call; } return _assertThisInitialized(self); }`

79 times:
`for (var _len = arguments.length, extend = new Array(_len), _key = 0; _key < _len; _key++) {
    extend[_key] = arguments[_key];
}`

46 times:
`function _assertThisInitialized(self) { if (self === void 0) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return self; }`

**Comment by christophermurphy2-allscripts** [comment]
This looks like the babelified code. Babel is used to maintain compatibility with older browsers, and generates code such as the class check function above that maintains class behavior even when it is not natively supported by the browser. Factoring out this kind of auto-generated code doesn't really make sense. Have a look here if you want a better understanding: <https://github.com/babel/gulp-babel>

**Comment by travist** [comment]
Thanks for the response @christophermurphy2-allscripts

**Comment by travist** [comment]
Most bundler's "tree-shake" these out anyway.
