### ISSUE TITLE
[BUG] OnChange not working with select box and lazy loading

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1551]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.25
- Frontend framework: react
- Browser: chrome
- Browser version:

## Steps to Reproduce
1. Create a form with 2 select boxes 
2. Select box A makes a URL call with lazy loading enabled
3. Select box B makes a URL call with lazy loading enabled
4. Select box should update it's value if Select box A is updated

## Expected behavior
Select box B clears if A is updated

## Observed behavior
When lazy load enabled then select B is not cleared if Select A is changed.

**Comment by jhen1422** [comment]
@aminmc 
Thank you for the report.
We have added this item to our backlog and will discuss this in our weekly planning meeting next week. If you would like to expedite this issue, please email support@form.io for cost information.

Thank you!

**Comment by aminmc** [comment]
@jhen1422 any updates on this?

**Comment by jhen1422** [comment]
@aminmc This issue has not yet been prioritized but is on our 4x backlog list
