### ISSUE TITLE
How can i custom builder drag & drop logic?

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#1553]
## Background
I want to custom builder & component,
for customer easily create the form with database table
(In web form only)

I have few component
\[Staff\]
\- DataSource (Container)
\- Name (Textbox)
\[Leave\]
\- DataSource (Container)

**Logic**
`Staff.Name` only can drop into `Staff.DataSource`
Can't drop into `Leave.DataSource`

## Question
How can i custom `onDrop` event, to prevent user drop some _not valid_ component into container?

I know i can add some code in [here](https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L1017) to prevent the drop event,
But any proper way to do that?

**Comment by randallknutson** [comment]
You can extend or override the WebformBuilder component to add that functionality. We don't have a good example of that at the moment but I've seen some customers do this successfully.

**Comment by bleungAtGTI** [comment]
Thanks for advice, I override and compiled, it work.

But would your team will consider export `WebformBuilder`
and split `dragula.options` like [Base.getRowDragulaOptions()](https://github.com/formio/formio.js/blob/master/src/components/base/Base.js#L977) at future?

**Comment by cskr11** [comment]
> Thanks for advice, I override and compiled, it work.
> 
> But would your team will consider export `WebformBuilder`
> and split `dragula.options` like [Base.getRowDragulaOptions()](https://github.com/formio/formio.js/blob/master/src/components/base/Base.js#L977) at future?

Hi, Can you pls let me know how you have accomplished that? We need to build a drag and drop framework - such that instead of dragging and dropping conrols, we will be dragging and dropping search data from the server. On drop, based on the search data selected, we need to show textfield/select box etc by overriding onDrop method..
