### ISSUE TITLE
How can I handle button click event

### ISSUE THREAD

**Issue by huzech** [formio/formio.js#1554]
I want to handle button click, and do something, any methods like following setting to work?

```
Formio.createForm(document.getElementById('formio'),
                    {"display": "form", "components": response.data.components},
                    {}).then((form) => {

                form.on("click", function (form) {
                   to do something.
                });
```

**Comment by randallknutson** [comment]
A button click should trigger a change event that you can listen to with "change". Here is an example of listening to the change event: http://formio.github.io/formio.js/app/examples/externalload.html

In addition, if you change the button type to "custom" you should be able to write javascript directly into the button itself which might have the functionality you need although it is more limited.
