### ISSUE TITLE
Utils getComponent can not find datagrid component

### ISSUE THREAD

**Issue by huzech** [formio/formio.js#1556]
Utils getComponent can not find datagrid component
```
var utils = require('formiojs/utils');
var component = utils.getComponent(form.components, 'myKey');
```

**Comment by aiwebb** [comment]
@huzech, can you supply an example form JSON for testing?

**Comment by randallknutson** [comment]
Try passing "true" as the third parameter. By default it doesn't include layout components and passing true causes it to search those as well.
