### ISSUE TITLE
[BUG] Conditional display for wizard

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1559]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.29
- Frontend framework: react-formic
- Browser:
- Browser version:

## Steps to Reproduce
1. Use attached form in renderer
2. Form has 2 pages.
3. Page 2 should be visible when you select 'Make page visible'
4. Make grid visible should display grid

## Expected behavior
1. If I select Make grid visible then grid should be visible.
2. If I select Make grid visible 'No' then grid should not be visible and if I select Make page visible then 2nd page in wizard should appear

## Observed behavior
If I select 'Make page visible' then hidden data grid appears.  This seem to be an issue when the form is a wizard.

[wizardHiddenPage.json.zip](https://github.com/formio/formio.js/files/3495802/wizardHiddenPage.json.zip)

**Comment by jhen1422** [comment]
@aminmc 

Thank you for the report

We have been able to reproduce the issue and will discuss priority with our dev team. If you would like to expedite this fix, please feel free to contact support@form.io.

**Comment by aminmc** [comment]
@jhen1422 Any updates on this issue?

**Comment by jhen1422** [comment]
@aminmc 
This item is still on our backlog as we are working through other issues.

**Comment by aminmc** [comment]
This is resolved in 4.2.0-rc.7
