### ISSUE TITLE
Request Hook Plugin on Resource Loading (question)

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#156]
I'm trying to find a way to hook up in the middle of a resource get request, to try to load data locally for a Select component (that calls an external URL) rather than going to the defined URL.

I thought that the "request" hook plugin would do, but actually, it is not called in this type of Ajax calls.

Which would be the right way to resolve this call locally?

Thank you!

**Comment by travist** [comment]
We may be able to make a change to allow plugins to hook into Select urls by changing this line

https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L102

To instead call ```Formio.makeRequest``` seen here https://github.com/formio/formio.js/blob/master/src/formio.js#L221. As you can see, this calls into the plugin system which you could then hook into that request using a plugin.

**Comment by cabrerabywaters** [comment]
Actually, makes a lot of sense to have it like that, seems to be a quick change for a big benefit.
I'm working on an offline first app, and this could help to load local values into the select.
How do you do it with the offline plugin that you have for angular? How about making the same also for the Resource component? (that it seems to work in a similar way)

Should I create a PR?

**Comment by cabrerabywaters** [comment]
@travist 
Any update on this?

At least what I'm doing now it's just changing it to Formio.makeStaticRequest not makeRequest as the first one is available to use in the component (works with no problem)

**Comment by travist** [comment]
This should be fixed with version 2.20.2.
