### ISSUE TITLE
Table component responsive issue

### ISSUE THREAD

**Issue by BhagyaUnvired** [formio/formio.js#1560]
Hi, I am using table component in my form to show some text box fields with labels. when I render the form in desktop it showing fine but when I run in mobile device its not showing like full table in a page it showing like horizontal scroll with some content. How can I make table as fit to screen in all platforms.
### Example in desktop view:
![image](https://user-images.githubusercontent.com/52695685/62947763-b821a180-be00-11e9-9fa0-dea632a298ec.png)
### Example in mobile  view:
![image](https://user-images.githubusercontent.com/52695685/62947877-eb643080-be00-11e9-984f-3aa23b2b3b7d.png)

Please give me a solution to solve this issue.. Thank you.

**Comment by randallknutson** [comment]
HTML Tables are inherently not responsive. The best workaround at the moment is to make them scrollable. You can try using the columns component instead which will collapse nicely on mobile devices.
