### ISSUE TITLE
File component active in readOnly mode [BUG] 

### ISSUE THREAD

**Issue by mrcportillo** [formio/formio.js#1566]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 3.16.0

## Steps to Reproduce
1. Submit a form with a file component.
2. Load the submitted form in readOnly mode.
3. File component is active, you can remove the file, or add new ones.

## Expected behavior
File component should be deactivated in readOnly mode.
## Observed behavior
File component still active.

## Example
![Screen Shot 2019-08-15 at 10 40 53 AM](https://user-images.githubusercontent.com/3878312/63098571-8f58f380-bf49-11e9-95c2-0a87e6526b78.png)

Form render logic:
```js
FormioCore.createForm(this.el, form, { readOnly: true})
```

**Comment by travist** [comment]
Looks like a bug. We will add this to our backlog. Let us know if you need expedited resolution.

**Comment by jhen1422** [comment]
This issue has been resolved in version 4.8.0.
