### ISSUE TITLE
[BUG] Angular vendor.js. Strict mode code may not include a with statement

### ISSUE THREAD

**Issue by Andrjuxa** [formio/formio.js#1567]
## Environment
Please provide as many details as you can:

- Hosting type
  - Form.io
  - [x] Local deployment
    - Version: -
- Formio.js version: 3.25.1
- Frontend framework: Angular 8.2.2
- Browser: Chrome / Firefox
- Browser version: -

## Steps to Reproduce
1. ng serve
2. open browser
3. enter localhost:4200
4. empty page
5. open browser console

## Example
![1](https://user-images.githubusercontent.com/12463504/63098760-42dadb80-bf7c-11e9-8608-f69793905147.jpg)

![2](https://user-images.githubusercontent.com/12463504/63098764-4706f900-bf7c-11e9-8f71-ef463f2ff96c.jpg)

**Comment by travist** [comment]
This is because we are now pre-compiling our templates which resolved both a performance + CSP issues. Not sure how we would resolve this unless there is another term that could be used, or how we can use Lodash templates inside of Angular application. Maybe someone from the community knows?

**Comment by christophermurphy2-allscripts** [comment]
Looks like you can pass an extra parameter to the template generation to avoid with(obj) being used. I tested the templates task and it removed the use of with(obj). Also seemed to work fine on a test page with a full build.

variable doesn't have to be 'data', I was just following the example found here:
https://www.npmjs.com/package/babel-plugin-lodash-template-precompile

An explanation for why with(obj) is the default is explained here:
https://stackoverflow.com/questions/18679422/issue-with-with-use-strict-and-underscore-js

Fixed code:
```js
.pipe(template.precompile({
      evaluate: /\{%([\s\S]+?)%\}/g,
      interpolate: /\{\{([\s\S]+?)\}\}/g,
      escape: /\{\{\{([\s\S]+?)\}\}\}/g,
      variable: 'data'
    }))
```

**Comment by travist** [comment]
Oh wow! Thank you @christophermurphy2-allscripts!  I am going to try this now in the 4.x and 3.x branches and if it works, then I will do a new build with this in place. Thanks again!

**Comment by travist** [comment]
So, just tried this in 4.x and it does cause problems. As an example, it looks like it would change the template to the following.

```js
exports.default=function(data) {
var __t, __p = '', __j = Array.prototype.join;
function print() { __p += __j.call(arguments, '') }

 if (!label.hidden && label.labelPosition !== 'bottom') { ;
__p += '\n  <label class="col-form-label ' +
((__t = (label.className)) == null ? '' : __t) +
```

Notice that we have a lot of other fields in here that expect the template to be defined. I believe what we may need to do here is change ALL templates to now use the keyword ```context``` which is the ```evalContext``` which is passed into each render template method. Not the end of the world, but does require quite a bit of change on our end.

**Comment by travist** [comment]
So, this will be pretty easy to resolve with 3.x, but we will need some time to convert all the templates to 4.x to use this variable method. stay tuned.

**Comment by christophermurphy2-allscripts** [comment]
Ah, ok. I'd only tested with the 3.x branch since that's the one my team is experiencing issues with as a dependency in ngFormio. Thanks for the updates!

**Comment by travist** [comment]
I should have an updated 3.x out very soon with this fix in place.

**Comment by travist** [comment]
This is now fixed in 3.x latest release. Will need some time to resolve it in 4.x since this does require us to make wide changes to our templates to use a template variable context.

**Comment by deadon523** [comment]
after updating to angular 9 I am getting this error.  Has this been resolved and I need to make an adjustment?  

An unhandled exception occurred: d:\Test\Test\ClientApp\vendor-es2015.js: 'with' in strict mode (150261:4)

  150259 |   Window_run: function _run(code, file) {
  150260 |     if (file) code += '\n//@ sourceURL=' + file;
> 150261 |     with(this) eval(code);
         |     ^
  150262 |   },
  150263 |   EventHandlerBuilder_build: function build() {
  150264 |     try {

**Comment by deadon523** [comment]
jasontaylor.dev/asp-net-core-angular-9-upgrade/  

I found this link right after posting my last comment.

**Comment by georgievstgeorge** [comment]
> jasontaylor.dev/asp-net-core-angular-9-upgrade/

On the link above it is described how to resolve the issue. 
Thanks

**Comment by Owned333** [comment]
I just figured out myself on the error (not related to formio).

tsconfig.ts, changing

"target": "es2015"

to
"target": "es5"

removed the "Generating ES5 bundles for differential loading..." stuff at all, works like a charm! :)
