### ISSUE TITLE
SetBaseUrl fails to pass regex when added with '/' at the end

### ISSUE THREAD

**Issue by adornala** [formio/formio.js#1573]
Formio.setBaseUrl("https://sample.com/formio/")  fails, because regex couldn't parse '/' at the end.

` 
{
     key: "getUrlParts",
     value: function getUrlParts(url, formio) {}
}
`

Formio.js - Line: 835 - 847

**Comment by travist** [comment]
Looks like it should just get trimmed before it is parsed. Pull requests welcome.
