### ISSUE TITLE
[BUG] DataGridComponent loses value in wizard

### ISSUE THREAD

**Issue by hans** [formio/formio.js#1575]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: Git 8777d3016 (HEAD as of last night)
- Formio.js version:
- Frontend framework: N/A
- Browser: Chrome Linux 64-bit
- Browser version: 76.0.3809.87

## Steps to Reproduce
1. Create a Wizard
2. Create DataGrid component with row groups in the non-final panel of a wizard
3. Put any other element in a final panel of the wizard
4. Fill out form; note that DataGrid values are lost

This may be relevant to #1452 ?

## Expected behavior

DataGrid inputs should not be lost!

## Observed behavior

DataGrid values are lost in the submisssion data.

## Example

https://jsfiddle.net/r1oxyzuh/

Form code example:

```js
{
  "display":"wizard",
  "components":[
    {
      "type":"panel",
      "title":"Panel 1",
      "components":[
        {
          "type":"datagrid",
          "label":"grid",
          "key":"datagrid",
          "enableRowGroups":true,
          "rowGroups":[
            {
              "label":"group 0",
              "numberOfRows":2
            },
            {
              "label":"group 1",
              "numberOfRows":2
            }
          ],
          "components":[
            {
              "type":"textfield",
              "input":true,
              "key":"foo"
            }
          ]
        }
      ]
    },
    {
      "type":"panel",
      "title":"Panel 2",
      "components":[
        {
          "type":"textfield",
          "label":"Name",
          "key":"name"
        }
      ]
    }
  ]
}
```

**Comment by hans** [comment]
I've hacked a fix for my purposes here: https://github.com/hans/formio.js/commit/63a689aa3dffaf18587f5093048eb5219bd69a4b

But I'm not sure this is a general solution. I'm new to this library and may be misunderstanding the purpose of the `setStaticValue` call. Please advise! :)

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
