### ISSUE TITLE
HTML5 select widget doesn't populate values?

### ISSUE THREAD

**Issue by thenixtone** [formio/formio.js#1584]
Unsure if I'm doing something wrong, but you can clearly see the issue on the official docs:

https://formio.github.io/formio.js/app/examples/select.html

The value does not get added to the `<option>` within the select itself. Can replicate on 3.1x.x, seems to be fixed on 4.x rc with same form schema.

Any ideas..?

**Comment by wag110894** [comment]
We are unable to replicate this issue using our docs you provided. Could you clarify the issue that you are having?

**Comment by thenixtone** [comment]
If you go down to the html5 widget

`
data: {
        values: [
          {value: 'apple', label: 'Apple'},
          {value: 'banana', label: 'Banana'},
          {value: 'pear', label: 'Pear'},
          {value: 'orange', label: 'Orange'}
        ]
      },
      dataSrc: "values",
      defaultValue: 'banana',
`

`<option><span>Pear</span></option>`

There is no value attribute on the option tag, it is there on the rc35 Formio4 release however.

**Comment by travist** [comment]
so are you saying it is fixed with latest versions?

**Comment by thenixtone** [comment]
It is fixed ONLY on the Formio 4.0 releases, not 3. So it isn't fixed since 4.0 has not released.

**Comment by travist** [comment]
I see. We are currently getting very close to releasing 4.x as production ready so I would try to migrate over to that renderer since it offers a significant amount of benefits over 3. If you require 3, then it may be some time for us to get to this item since it isn't urgent and has already been resolved in our latest renderer.
