### ISSUE TITLE
'Render' vent will trigger before loading spinner disappears [BUG] 

### ISSUE THREAD

**Issue by anonymousonline** [formio/formio.js#1585]
## Environment
Please provide as many details as you can:
We are trying to implement our own loading placeholder to better align with the UI elements used in our application. In short we want to show a loading place holder until the form has been successfully loaded by the form renderer. To do so we are using the form.on('render',..) event to hide or show the loading place holder. We have found that the onRender event will trigger before the loading spinner actually disappears. 

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: v3.25.3
- Frontend framework: 
- Browser: Chrome/ Phone gap application

## Steps to Reproduce
1.  When a render event is fired set a variable from false to true.
2. Open a large form (prepopulated with enough data like files) to force the renderer to take a second to load.
3. You will see that the variable will toggle form false to true before the loading spinner disappears.

## Expected behavior
Render event to trigger after the loading spinner disappears.

## Observed behavior
The render event should only fire after the loading spinner disappears. Per the documentation 'render' is Triggered after the form is done rendering and '
The form is rendered and ready to go'. My opinion is a form is not ready to go when the loading spinner is visible.

## Example
Notice how the OnRender variable toggles from false to true before the loading spinner appears

![2019_08_21_13_30_16](https://user-images.githubusercontent.com/54179686/63405231-a780b500-c418-11e9-82fb-693527976a4d.gif)

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen if needed.
