### ISSUE TITLE
Unable to drag components on to formbuilder latest version [BUG] 

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1586]
Hello,

I've just upgraded to .36 of 4.x and it seems as though I'm no longer able to add any components to the builder. See error below:

<img width="1312" alt="Screenshot 2019-08-21 at 06 57 16" src="https://user-images.githubusercontent.com/290639/63406211-1d692a00-c3e1-11e9-9fb9-00e9c373ca3e.png">

Thanks

**Comment by randallknutson** [comment]
We've been wrestling with form building in the latest versions of 4.x and will be reverting the fixes today that are causing these issues. We should have a stable release later today.

**Comment by aminmc** [comment]
This is working now..so closing
