### ISSUE TITLE
[BUG] Editgrid required does not prevent submission

### ISSUE THREAD

**Issue by christophermurphy2-allscripts** [formio/formio.js#1587]
# Editgrid required does not prevent submission

## Environment

Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: formio-enterprise image 6.6.5
- Formio.js version: ^3.24.0
- Frontend framework: vanilla javascript
- Browser: any
- Browser version: any

## Steps to Reproduce

1. Add an editgrid to a form. Make it required.

2. Add components to the editgrid (optional).

3. View the form and attempt to submit it. An error will briefly display as
the form proceeds to submit successfully.

## Expected behavior

An editgrid that is required should not allow the form to submit until it has at
least one entry. Not sure if it makes sense to allow this in all cases, since
technically a user can add an editgrid and not put any components inside it.

Maybe checkValidity should return false if this.component.validate.required ===
true and editrows has a length of 0?

## Observed behavior

The editgrid's error container is updated with the proper message through
setCustomValidity(), but is still considered valid. So the form can submit
successfully even though an error displays.

## Example

The problem is that in the case where the editgrid is required the message is
set and the error displayed, but checkValidity returns true by default. Returning
false when the editgrid is required and has no rows seems to make more sense.
In my example fix I did notice that my if statement got hit twice, not sure if
that's normal or not.

```js
// current code
checkValidity(data, dirty) {
    ...

    const message = this.invalid || this.invalidMessage(data, dirty);
    this.setCustomValidity(message, dirty);
    return true;
}
```

```js
// example fix
checkValidity(data, dirty) {
    ...

    if (this.component.validate.required && this.editRows.length === 0) {
        // error message is the same as data in this case, but this
        // is more explicit
        this.setCustomValidity(this.component.label + ' is required', dirty);
        return false;
    }

    const message = this.invalid || this.invalidMessage(data, dirty);
    this.setCustomValidity(message, dirty);
    return true;
}

**Comment by travist** [comment]
Thanks @christophermurphy2-allscripts. We will add this as a bug to be fixed in our backlog.

**Comment by wag110894** [comment]
Hello @christophermurphy2-allscripts Thank you for your patience while we worked on this issue. This issue has been resolved in the latest version of our Core Renderer 4.8.0-rc3.

Thank you for using Form.io.
