### ISSUE TITLE
[BUG] select box fails to save when multi select is turned on, and causes form builder to freeze / break

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#1593]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest app on website
- Frontend framework: js
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. Add a select box
2. Add some values in the config
3. Set the "multiple values" config
4. Save the component

## Expected 

The component would save on the form

## Observed behavior

The form component does not save and the form is frozen.  Console shows a error of "uncaught promise.. cannot set property "value" of undefined"

**Comment by StephenOTT** [comment]
Looking at the code, the error appears to be:

Select box inherits from radio.js. So radio has the same issue:

So looking at radio we see that: the createInput() method does not return the input element.  See Radio.js line 103-104 is missing the return

**Comment by StephenOTT** [comment]
ReCaptcha might have the same issue as well

**Comment by randallknutson** [comment]
I believe we removed the "Multiple" setting on new versions of the builder (4.x) since it doesn't make sense on these components.

Really, selectboxes is the same as radio but with multiple options allowed. At some point we may change it to that but don't have plans of doing it at this time.

**Comment by StephenOTT** [comment]
This is on a 4x release?
