### ISSUE TITLE
[BUG] Custom Components Drag and Drop in Layout

### ISSUE THREAD

**Issue by sssxiaocainiao** [formio/formio.js#1602]
Custom components are dragged back and forth in the layout. After saving the template, the location of the custom components is still where they were dragged in at the beginning. No change in placement

**Comment by wag110894** [comment]
what version of the formio.js are you using? 3x or 4x?

**Comment by sssxiaocainiao** [comment]
Version 3.20

**Comment by sssxiaocainiao** [comment]
OK thanks
