### ISSUE TITLE
[BUG] Missing font awesome icons on Builder

### ISSUE THREAD

**Issue by Rvaucher** [formio/formio.js#1608]
Hi,
I'm actually using the 3.22.8 version of Formio.js in a React Front App.
Some icons seem to be missing in the builder :
![image](https://user-images.githubusercontent.com/43232928/63843281-6ba09f00-c986-11e9-987a-9ebe86e434a8.png)
I noticed the font awesome class doesn't match with any existing icons atm.

Thanks in advance.

**Comment by Rvaucher** [comment]
I just tried and I noticed the base component was removed from the components directory.
I'm using it on some custom made components therefore I can't build
Any reason in particular ?

**Comment by Rvaucher** [comment]
Any news or updates on this issue ?

Thanks in advance,

Best regards.

**Comment by randallknutson** [comment]
4.x no longer has a "base" component. It is now called "component" and it is in the components/_classes directory.

If you are creating your own custom components, 4.x is going to be very different than 3.x was. You can find out how it is different and how to change your components here: https://github.com/formio/formio.js/wiki/Form-Templating
