### ISSUE TITLE
formio-component width with required enabled

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#1617]
Hello FormioJs Team,

Something I cannot figure out. When I enable the required option of a component the width of that component is fixed to 202px. When I disable the required option the width follows the width of the container.

Can you advise where to look in the code that messes up the width setting?

Kind regards,
Mario

**Comment by randallknutson** [comment]
We aren't aware of anything that would do this and aren't able to replicate it. We do add some sort of "required" class when a field is required. It could be that there are some styles on your page that are causing the component to pick up those additional styles. Can you inspect the CSS and see if there is a style setting the width?

**Comment by KyooMario** [comment]
Hello Randall,

I am investigating.
But can you tell me where you add the 'required' class. For testing I can disable the addition and see if that causes it.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Randall,

I deleted the classname in the Chrome inspect window and you are right. The width restored.
Question: Does FormIOjs uses this class name?
Maybe we can rename the class name in the code.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Randall,

I can find some lines in the code saying: setAttribute('class', 'field-required');
But only add the class required I cannot find anywhere.

Can you tell me where this class is added?

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Randall,

I found it: base.js
if (this.hasInput && this.component.validate && this.component.validate.required) {
        className += ' required';
      }

I have changed the className to filledRequired so I can reuse the class if needed.
Which brings me to the question if you can tell if we need this class.
Please advise.

Kind regards,
Mario

**Comment by randallknutson** [comment]
Hi Mario,

I believe this is a bootstrap class which is why we are adding it there. In the 4.x branch we are more dynamic in how we do templating and it may be easier to override this in that version.
