### ISSUE TITLE
Call REST API on custom validation field

### ISSUE THREAD

**Issue by romain-rhieu** [formio/formio.js#1622]
Hello FormioJs Team,

I started using formio recently and would like to validate my form fields by calling a REST validation API.

I thought to use the field "Custom Validation" but the code seems horrible :)

```
const req = new XMLHttpRequest();
req.open('GET', 'MY_URL', false); 
req.send(null);

if (req.status === 200) {
    valid = true
} else {
    valid = 'Invalid field value'
}
```

Do you have any advice ?

Kind regards,

Romain

**Comment by randallknutson** [comment]
The Custom Validation code is not asynchronous so you can't use it for server validation. There is a customValidation hook that you can use to asynchronously validate to a server and set error messages. You can see the hook here: https://github.com/formio/formio.js/blob/f6fbcc6b82af23c67f0aa771e051e0439992d2a3/src/Webform.js#L1237

**Comment by romain-rhieu** [comment]
Thank you for your quick reply !

I tested this hook and it seems to be relative to the form. 

I would like to be able to execute a specific rest api validation for each field on blur event.

Do you think that is possible ?

Moreover, when I run a validation on the "blur" (validateOn=blur), the validation is triggered on the change event (whenever I enter a character), is there an open bug on it ?

Regards,

**Comment by travist** [comment]
Sounds like a bug... We will add this to our backlog.

**Comment by mohsinxmushtaq** [comment]
Hi,

I tried the following to check with custom validation. 

`    var xmlhttp = new XMLHttpRequest();   // new HttpRequest instance
    var theUrl = "https://solitary-wave-4071.getsandbox.com/promo";
    xmlhttp.open("POST", theUrl);
    xmlhttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    xmlhttp.send(JSON.stringify({ "promo": "mohsin1" }));
    xmlhttp.addEventListener('load', complete, false);

    function complete(e) {
        if (this.status === 200) {
            valid = true;
        }
        else {
            valid = 'Invalid';
        }
    }`

if I console.log() the this.status it comes but it is not setting the valid to true or invalid.

**Comment by nadiolina82** [comment]
Hi,
I need to allow the administrator to add server validation url (for each field or one for all) during form building step, so I'd like to add a server validation url from Form.io builder. 

I tried to implement a custom "hook" render side but it is not a solution for my requirement.

What is the best approach to implement this requirement?

Regards,
NC

**Comment by ilistes** [comment]
I've just experienced this problem, it would be nice to have it fixed/have a solution.

**Comment by MohitNaroliya** [comment]
@travist any update on this bug or have any work around to achieve requirements?

**Comment by travist** [comment]
Within the custom evaluator, you have access to the instance, so if the validity check is asynchronous, then you can always call the instance and set the validity like this.

```
setTimeout(() => {
  instance.setCustomValidity('Something bad happened!!!');
  instance.root.redraw();
}, 100);
```

**Comment by sirolf2009** [comment]
Setting an error message asynchronously works for me using the `instance.setCustomValidity`, it doesn't grey out the submit button though, meaning the user can still submit an invalid submission

**Comment by brendanbond** [comment]
@sirolf2009 FWIW it's probably better to use the underlying signature pad dependency for signature complexity validation, here's a JSFiddle to demonstrate: 
https://jsfiddle.net/brendanbond/cLs9nrka/10/
