### ISSUE TITLE
[BUG] Console error when rendering builder

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1625]
Hi All

We're using the latest version of the 4.x and when displaying the builder we're seeing the following:

<img width="1310" alt="Screenshot 2019-09-04 at 07 43 44" src="https://user-images.githubusercontent.com/290639/64231800-714b3700-cee8-11e9-9d78-d1542a6664ec.png">

This is a blank builder, on inspecting the line it's trying to do a forEach on a string:
<img width="1408" alt="Screenshot 2019-09-04 at 07 49 43" src="https://user-images.githubusercontent.com/290639/64231875-9f307b80-cee8-11e9-8c72-4cc549eeb708.png">

**Comment by randallknutson** [comment]
Thanks. We are working on adding functionality for existing resources to the core library and it may be that our developer forgot to check if it exists first. I'll pass this along to them to get fixed.

**Comment by randallknutson** [comment]
We're not sure why the components are coming in as a string but we can easily add a check and parse around it. Would this fix the issue? https://github.com/formio/formio.js/pull/1630

**Comment by aminmc** [comment]
Strange that we see it with an empty builder. Nothing at this point has been added.

**Comment by aminmc** [comment]
no longer an issue with 4.2.0-rc.7
