### ISSUE TITLE
[BUG] "Cancel" button doesn't work in Edit Grid component with modal view

### ISSUE THREAD

**Issue by onmywaytoheaven** [formio/formio.js#1632]
## Environment
Found this bug here https://github.com/novacode-nl/odoo-formio/issues/7
- Browser: Firefox
- Browser version: 68.0.2

## Steps to Reproduce
1. Go to https://formio.github.io/formio.js/app/builder
2. Add Edit Grid component
3. Check "Display as modal" in Templates tab. Click Save
4. Add something to Edit Grid (e.g. Text Field). Save it
5. Go to rendered form
6. Click "Add Another"
7. Click "Cancel"
## Expected behavior
"Add Another" view closes
## Observed behavior
Nothing happened
## Example
![formio_cancel_bug1](https://user-images.githubusercontent.com/43062804/64290932-b8c8d600-cf6f-11e9-854d-15aced3b3d03.gif)

**Comment by jhen1422** [comment]
@onmywaytoheaven Thank you for the report. We have added this to our 4x backlog.

**Comment by heather-formio** [comment]
I tested this with 4.14.9 and it is working as expected. Closing thread, please reopen if needed. Thank you for your contributions!
