### ISSUE TITLE
[BUG] Copy and paste a page misses page child components

### ISSUE THREAD

**Issue by CatBakun** [formio/formio.js#1634]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io - https://formio.github.io/formio.js/app/builder
  - [ ] Local deployment
    - Version: 
- Formio.js version: https://formio.github.io/formio.js/app/builder
- Frontend framework: N/A
- Browser: Chrome
- Browser version: Version 76.0.3809.100 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a wizard form
2. in the first page add 4 text input, one radio input, and another text input in that order
3. copy and paste the page (will create a new one)

## Expected behavior
Now I have 2 pages with the same components

## Observed behavior
The new page does not have all components of page one

## Example
This is the page 1:
![Screenshot from 2019-09-05 17-55-12](https://user-images.githubusercontent.com/4873355/64379975-71d9ef80-d006-11e9-9ece-ae5df6a1fac0.png)

This is page 2 (copy/paste) missing components:
![Screenshot from 2019-09-05 17-55-40](https://user-images.githubusercontent.com/4873355/64380025-8cac6400-d006-11e9-859a-171021fe502b.png)

**Comment by jhen1422** [comment]
@CatBakun 
Thank you for the report. We tested on our end and were unable to replicate using our latest 4x renderer. It looks like we need to upgrade our builder on the example builder page to resolve.

Thanks again.

**Comment by CatBakun** [comment]
@jhen1422 This error happens in version 3
I just upgraded form version 2 to version 3.

**Comment by wag110894** [comment]
This issue does not occur using our 4x Core renderer. You can upgrade to our 4x Core Renderer. If you need to have this fixed in 3x please let me know and we can quote that for you.

Thanks!

**Comment by CatBakun** [comment]
@wag110894 thanks, yes. I need this to get fixed in version 3

**Comment by wag110894** [comment]
@CatBakun,

Our developers have estimated this fix would take about 8 hours to resolve. 

Please contact us via email at support@form.io if you are interested and I can send over a formal quote.

Thanks.

**Comment by heather-formio** [comment]
I tested this with 4.14.9 and it is working as expected. Closing thread, please reopen if needed. Thank you for your contributions!
