### ISSUE TITLE
[BUG] Is possible to bundle cdn libraries wherever we are using in components?

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#1649]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 3.21.5
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. In Textarea component we are adding ace.js like       this.editorReady = Formio.requireLibrary('ace', 'ace', 'https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.1/ace.js', true)
2. When we are in with in firewall this component is not working
3. is possible to bundle as part of build by adding into package.json

## Expected behavior
Need to bundle using package.json

## Observed behavior
Adding cdn library

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
 this.editorReady = Formio.requireLibrary('ace', 'ace', 'https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.1/ace.js', true)
```

**Comment by randallknutson** [comment]
If you look in the Formio.requireLibrary function, https://github.com/formio/formio.js/blob/master/src/Formio.js#L1255, it will first check the global scope for the variable before attempting to import from our cdn. Our cdn is more of a fallback. If you include your own library above our script it will skip loading from our cdn.

**Comment by heather-formio** [comment]
Closing this thread, but keeping the related #3750 open.
