### ISSUE TITLE
The input element's type ('email') does not support selectionStart

### ISSUE THREAD

**Issue by gregbown** [formio/formio.js#1662]
BUG Using Formio.js v4.0.3-8
Running the app like the demo at https://formio.github.io/formio.js/app/builder
Also verified that your demo throws the same error.

Add an email input to the form
paste an email address into the test rendered form
throws error because it is trying to set selectionStart on an input type email which does not have the property. 

See: [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange), according to the forms spec selectionStart, selectionEnd properties and setSelectionRange method apply only to inputs of types text, search

**Error**
```
formio.full.min.js:26 Uncaught DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.
```
**Just thought you should know this bug breaks the ability to use the email input completely. As soon as the error occurs no input is passed to the submission rendering the field useless.**

The fix I used was to check for the property first.  
File: src\components\_classes\multivalue\Multivalue.js

```
        if (element.selectionStart && element.selectionEnd) {
          element.selectionStart = selectionStart;
          element.selectionEnd = selectionEnd;
        }
```

**Comment by jhen1422** [comment]
@gregbown 
Thank you for the report. We have a created a ticket for the issue and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by gregbown** [comment]
This appears to be fixed in version 4.2.0-rc.7

**Comment by gregbown** [comment]
This error is back in version 4.2.5 ?

**Comment by randallknutson** [comment]
I'm not sure if we have fixed this yet. It is a valid issue that we need to fix. 

We need to wrap these lines in a check for the input type and not run it for other types. https://github.com/formio/formio.js/blob/2fff6bf0147fca1b7df05af605cd97851ed3c5c1/src/components/_classes/multivalue/Multivalue.js#L114-L115

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/1812

**Comment by jhen1422** [comment]
This should be resolved in version 4.5.1

**Comment by sergei-maertens** [comment]
Seeing this again in 4.12

**Comment by AlexByte** [comment]
It should be reopened

**Comment by AlexByte** [comment]
It should be reopened, error occurs in Chrome 49

**Comment by jabcreations** [comment]
This is a specification bug for WHATWG Forms, you can view the bug report here: https://github.com/whatwg/html/issues/12555
