### ISSUE TITLE
[Need Help] Color picker component

### ISSUE THREAD

**Issue by prashantsail** [formio/formio.js#1663]
I am using formio.js version 3.26.0

I need to have a simple color picker as part of my form.
Something as simple as `<input type="color">` would also suffice.

Is there an easy way to get this color picker component out of the box ?
(Say - I modify textfield component with some additional json properties, etc)
OR
Do I need to implement it as a custom component ?

**Comment by travist** [comment]
If you are ok with just having the "type" color, then this could be done very similar to how our password component works.

https://github.com/formio/formio.js/blob/master/src/components/password/Password.js

Just change the code to this...

```js
get inputInfo() {
    const info = super.inputInfo;
    info.attr.type = 'color';
    return info;
  }
```

If you create a Pull request with this, we will consider making it part of our renderer.

**Comment by prashantsail** [comment]
@travist 
Alright.. Thanks for the help.. 👍
