### ISSUE TITLE
[Need Help] Examples and Help for formio.js 3.x

### ISSUE THREAD

**Issue by prashantsail** [formio/formio.js#1664]
The [Examples page](https://formio.github.io/formio.js/app/examples/) & the [SDK page](https://formio.github.io/formio.js/app/sdk) are updated for the latest release 4.x

Where can I find examples and SDK docs for the earlier release 3.x version

**Comment by travist** [comment]
We will need to push up the 3.x somewhere else. The other option is that you can just run it locally by typing the following in your command line.

```
npm run serve
```

**Comment by prashantsail** [comment]
@travist 
Having a 3.x hosted some place else would be really useful..

Meanwhile I will run it locally on my setup.

Thanks 👍
