### ISSUE TITLE
Formio formbuilder drag and drop features not appearing issues with formio.min.js skipInit[BUG] 

### ISSUE THREAD

**Issue by sandeepsingh3i** [formio/formio.js#1675]
## Environment
Windows 10 OS
- Hosting type
  - [x] Form.io
  - [ ] Local deployment/Remote deployment both
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. Added CDN online as follow tutorial (formio full min js, css in script tag )
2. created formio and added it on ID of formio
3. it was working fine till two days back and also hosted it on remote server .

## Example

Uncaught TypeError: Cannot set property 'skipInit' of undefined
    at new t (formio.full.min.js:26)
    at t.value (formio.full.min.js:227)
    at t.value (formio.full.min.js:19)
    at t (formio.full.min.js:19)
    at new t (formio.full.min.js:227)
    at u (formio.full.min.js:227)
    at Function.r.default.builder (formio.full.min.js:227)
    at window.onload (templateCreate.js:10)

**Comment by jhen1422** [comment]
@sandeepsingh3i 
In our efforts to keep the issue log organized, please open a new bug report for the expanding/collapsing issue described in your previous comment.

4.0.7 has been released and available now. Please refer to the formio.js change log for details
