### ISSUE TITLE
[Question] Submission schema

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1685]
Hi

This is a question rather than a bug. I was wondering if it was possible to get the submission data schema that formio builds on submission without actually submitting.  I would like to preview the data schema that formio will generate if the form is submitted.  Any pointers to classes or fragment of code would be appreciated.

Thanks

**Comment by randallknutson** [comment]
Currently the best way to do this is to instantiate the form and grab the default submission from it. The place where this has issues is if something starts with some fields hidden in which case they won't be added to the submission. There used to be some options you could pass in that force that to work but I haven't been able to find it.
