### ISSUE TITLE
[BUG] Nothing happens when submitting with nested form

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1686]
Hi

I'm using the latest version of formio js 4.0.8 and I've noticed that when you hit the submit button on a form using nested forms nothing happens. The submit button has the spinner and nothing else.I tried version 4.0.3 and it is working fine.  

Thanks

4.0.3:

<img width="1179" alt="Screenshot 2019-09-14 at 16 10 21" src="https://user-images.githubusercontent.com/290639/64909993-33c98380-d70a-11e9-8a62-b936ad973089.png">

After 4.0.3:

<img width="1180" alt="Screenshot 2019-09-14 at 16 07 12" src="https://user-images.githubusercontent.com/290639/64909945-c0c00d00-d709-11e9-9f9f-43f6e9d037de.png">

**Comment by jhen1422** [comment]
@aminmc 
We are unable to replicate this using version 4.0.8. Can you confirm you have the correct permissions set up for the nested form?

**Comment by aminmc** [comment]
hi @jhen1422 The subform is visible and has the correct permissions.  I have disabled save as reference and I see the following when I hit submit:

![Screenshot 2019-09-16 at 15 53 35](https://user-images.githubusercontent.com/290639/64968548-483c8600-d89a-11e9-8f3e-368e0b2e77ff.png)
If I revert to 4.0.3 then it works as expected.

**Comment by aminmc** [comment]
@jhen1422 Any updates on this? I've upgraded to latest and I'm still seeing the same behaviour

**Comment by randallknutson** [comment]
Hi Amin,

We aren't able to reproduce this when we test it. Is there something you can think of that would be different in your code? Also, is there some way you can provide an example where it isn't working?

**Comment by aminmc** [comment]
@randallknutson It's a simple 2 forms.  I'm using react formio 4.0.0-beta.28 (due to other issues). The form is rendered correctly. I just never see this code being executed:

```js
onSubmit={(submission) => {
                  alert('Hello');
                 //handle submission

              }}
```

**Comment by aminmc** [comment]
@randallknutson @travist this looks like it's working on 4.2.12:

<img width="1271" alt="Screenshot 2019-10-04 at 11 10 52" src="https://user-images.githubusercontent.com/290639/66199896-af7a7880-e697-11e9-98d4-703e9be2edb6.png">


Thank you!
