### ISSUE TITLE
[BUG] Tab will jump to first tab when drop the components in builder

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#1689]
## Environment
- Hosting type
  - (As at 2019-09-16) https://formio.github.io/formio.js/app/builder
- Browser: Chrome
- Browser version:  76.0.3809.132 

## Steps to Reproduce
1. New Tabs with two tab
2. Select second tab
3. Drag & drop some component to second tab
4. Click `Save` to save new component

## Expected behavior
Tabs will change to first tab

## Observed behavior
Tabs should be still in second tab

## Example
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_1689.apng?raw=true)

**Comment by jhen1422** [comment]
@bleungAtGTI Thank you for the report. We were able to replicate this issue on our end as well and have added a ticket to our 4x backlog. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing

**Comment by randallknutson** [comment]
This should be fixed with the 4.1.0 release. I tested it out and it appears to work now. Let us know if you find it is still an issue.
