### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rushi02** [formio/formio.js#1691]
I am not able to add and update data in multiple nested tabs. It is not saving that data properly.
Data vanishes when i click to nest tab.

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by jhen1422** [comment]
@rushi02 
Can you provide a form embed url JSON of your form(s) as well as the formio.js version you are using to help us troubleshoot the issue?

**Comment by rushi02** [comment]
Thank you jhen1422 for quick response. I updated to latest version and this issue resolved .Thanks for support.
