### ISSUE TITLE
Panel doesn't expand on errors when the display type is wizard.  

### ISSUE THREAD

**Issue by AmeeBhadania** [formio/formio.js#1697]
Formio version: 3.21.5

Steps to reproduce:
1. Add 2 panels. Say P1, P2. 
2. Within P1 add a textField. Set required to true.
3. Add another panel within P1. Say C1. Set collapsible and initially collapsed options to true.
4. Within C1, add a number component. Set required to true.
5. Add a textArea within P2.
6. In the json, set the display type to 'wizard'

In the renderer,
1. Enter some value in the textField.
2. Click on the Next button. 

Observations:
One will not be able to navigate to the next page because no value has been entered in the number field. This is expected. But, no error is seen on the screen. 

Expected:
C1 panel to expand automatically on clicking the next button when there are errors.
In general, if there are any errors in the child component, the error class needs to be added to the parent component also.

*I have set disableAlerts option to true because I want to highlight errors at the field level only.

----------------------------------------------------------------------------------------------------------
When C1 is collapsed and we click on Next button: 

![WhenC1isCollapsed](https://user-images.githubusercontent.com/48707525/65028584-e80d1900-d959-11e9-81fc-a43c14300f6b.JPG)

---------------------------------------------------------------------------------------------------------
When C1 is expanded and we click on Next button :  
![WhenC1isExpanded](https://user-images.githubusercontent.com/48707525/65028582-e7748280-d959-11e9-8634-81a1c24fde8e.JPG)

**Comment by jhen1422** [comment]
@AmeeBhadania 
Although the panel does not expand automatically, you do see a validation message when using the latest version of our 4x renderer. Can you upgrade to the latest 4x version of Formio.js to resolve?

I will also add an issue to our 4x backlog to auto expand the panel when a validation is triggered. 

Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
Hello @AmeeBhadania Thank you for your patience while we got this working. When validation is triggered, the Panel auto expands and shows inside the Panel. This issue is resolved in the latest version of formio.js (4.8.0-rc13)

Thank you for using Form.io and let me know if you have any further questions.
