### ISSUE TITLE
Change the main file in package.json

### ISSUE THREAD

**Issue by batusai513** [formio/formio.js#17]
i've been working with react-formio, and i've made this change there, when working with commonjs and more specific, with webpack, it is better to provide the commonjs (not compiled version) of the code, so if you are not using any code that needs to be transpiled with babel or something like that is better to set the main to the source file to avoid this:
```
./~/formiojs/dist/formio.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/formiojs/dist/formio.js 1:479-486
```
```js
{
   "main": "dist/formio.js"
}
//to
 {
   "main": "src/formio.js"
}
```

**Comment by randallknutson** [comment]
#20

**Comment by randallknutson** [comment]
This is complete.
