### ISSUE TITLE
[BUG] Select Box search limited results

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#1701]
<img width="604" alt="Screenshot 2019-09-18 at 13 21 28" src="https://user-images.githubusercontent.com/534416/65148487-32ed6600-da18-11e9-8b2c-90f73aa40a4d.png">

## Environment
Using FormIO.js 4.0.3 we are seeing an issue where when you have a select box (Choices.JS) and a remote URL then start typing to locate an entry. 
I would expect to display all the results that match or at least a fair number (i.e up to 20). When we have tested we seem to only be getting 4 responses. Rather than a match of 10. 
i.e from the picture attached we have 10 teams HRH-1 to HRH-10. If I type HRH then I expect to see all 10.

- Hosting type
  - [] Form.io
  - [ X] Local deployment
    - Version: 
- Formio.js version: 4.0.3
- Browser: Safari | Chrome

```js
{
  "id": "e8gg17",
  "key": "teamid",
  "data": {
    "url": "{$.environmentContext.referenceDataUrl}/v1/entities/team",
    "json": "",
    "custom": "",
    "values": [],
    "headers": [
      {
        "key": "",
        "value": ""
      }
    ],
    "resource": ""
  },
  "sort": "",
  "tags": [
    "platform-data-read"
  ],
  "type": "select",
  "input": true,
  "label": "Select team",
  "limit": 100,
  "logic": [],
  "filter": "",
  "hidden": false,
  "prefix": "",
  "suffix": "",
  "unique": false,
  "widget": null,
  "dataSrc": "url",
  "dbIndex": false,
  "lockKey": true,
  "overlay": {
    "top": "",
    "left": "",
    "style": "",
    "width": "",
    "height": ""
  },
  "tooltip": "",
  "disabled": false,
  "lazyLoad": false,
  "multiple": false,
  "tabindex": "",
  "template": "<span>{{ item.name }}</span>",
  "validate": {
    "json": "",
    "custom": "",
    "required": true,
    "customMessage": "",
    "customPrivate": false
  },
  "autofocus": false,
  "encrypted": false,
  "hideLabel": false,
  "minSearch": 0,
  "protected": false,
  "refreshOn": "locationid",
  "tableView": true,
  "errorLabel": "",
  "persistent": true,
  "properties": {},
  "validateOn": "change",
  "clearOnHide": true,
  "conditional": {
    "eq": "",
    "json": "",
    "show": "",
    "when": null
  },
  "customClass": "",
  "description": "",
  "fuseOptions": {
    "include": "score",
    "threshold": 0.3
  },
  "placeholder": "",
  "searchField": "",
  "authenticate": false,
  "defaultValue": "",
  "disableLimit": false,
  "selectFields": "",
  "selectValues": "data",
  "alwaysEnabled": false,
  "customOptions": {},
  "labelPosition": "top",
  "readOnlyValue": false,
  "searchEnabled": true,
  "showCharCount": false,
  "showWordCount": false,
  "valueProperty": "id",
  "calculateValue": "",
  "clearOnRefresh": true,
  "searchThreshold": 0.3,
  "selectThreshold": 0.3,
  "customConditional": "",
  "allowMultipleMasks": false,
  "customDefaultValue": "",
  "allowCalculateOverride": false,
  "redrawOn": "",
  "attributes": {
    "renderChoiceLimit": "-1"
  }
}
```

**Comment by jhen1422** [comment]
@pixie79 
can you please try version 4.0.11 as I'm unable to reproduce using the latest renderer. If the issue still persists could you provide a jsfiddle?

Thank you

**Comment by gavinorland** [comment]
Hi @jhen1422  As of formiojs 4.2.8 we still the same issue.

**Comment by gavinorland** [comment]
JSFiddle example: http://jsfiddle.net/nirvanagold/kwbfqu0x/21/

**Comment by randallknutson** [comment]
The issue is actually in choices.js at it automatically limits the results to 4 by default. The setting is here: https://github.com/jshjohnson/Choices#searchresultlimit-4

You can set it in the choices.js options of the select component.

**Comment by gavinorland** [comment]
Thanks @randallknutson - I can confirm that works fine. :)

**Comment by bandman0226** [comment]
Thanks for the info @randallknutson - This also worked for us. I did have another question to ask. It works fine now but when a we scroll to the bottom of the list it seems to "reset" the filter and shows all the records. Any thoughts or suggestions?

**Comment by dsuresh-ap** [comment]
@randallknutson Could you provide an example on how to set this value after `Formio.createForm` is called?

**Comment by namti** [comment]
> @randallknutson Could you provide an example on how to set this value after `Formio.createForm` is called?

```json
customBasic: {
	title: 'Form Fields',
	default: true,
	weight: 0,
	components: {
		select: {
			title: 'Select',
			key: 'select',
			icon: 'list',
			schema: {
				type: 'select',
				label: 'Select',
				key: 'select',
				customOptions: {
					searchResultLimit: 999
				}
			}
		}
	}
}
```
