### ISSUE TITLE
boolean values are transformed to string values

### ISSUE THREAD

**Issue by dannymcpherson** [formio/formio.js#171]
In my form, I'm using a two option Radio component, and trying to store true/false (as a boolean).  But upon submission, formio converts the value to string, and will not load submissions into the form unless it is a quoted "true" or "false" value.

Am I missing something?  Is this correct behavior?  It seems incorrect to me.

**Comment by mkrienke** [comment]
I noticed the same, but decided it wasn't a problem.  It's just different than I expected and we can work with it.  I have, however, had a problem making a different field's conditional visibility function based on the radio button.  I've tried double quotes and single quoted on the condition parameters with no luck.

**Comment by cabrerabywaters** [comment]
I have a similar problem with this, but in my case is Radio buttons transforming a Number to a String.
I think it's important to have the ability to define the data type as at least in our case, we send the data to elasticSearch and using autoindexing for the inputs. In this case, this causes problems as is indexed as a String.

**Comment by dannymcpherson** [comment]
@mkrienke - I did get radio based form conditionals working, here's an example:
```javascript
conditional: {
    show: true,
    json: {
        and: [
            {"===": ["false", {"var": "data.some_radio_boolean_value1"}]},
            {"===": ["false", {"var": "data.some_radio_boolean_value2"}]},
        ],
    },
},
```

@cabrerabywaters - I completely agree on respecting data types.  I'm sad that I'm having to do some additional data transformation on the way in and out in order to force booleans to be respected.  In case it helps, here's my workaround until formio.js fixes the issue:

```javascript
function adjustSubmissionBeforeLoad(schema, submission) {
    var booleanMap = buildBooleanMap(schema['components']);
    var data = submission.data || {};
    _.each(Object.keys(data), function(k) {
        if (booleanMap[k] && (data[k] === true || data[k] === false)) {
            data[k] = data[k].toString();
        }
    });
    window.submission = submission;
    return submission;
}

function adjustSubmissionBeforePost(schema, submission) {
    var booleanMap = buildBooleanMap(schema['components']);
    var data = submission.data || {};
    _.each(Object.keys(data), function(k) {
        if (booleanMap[k] && (data[k] === 'true' || data[k] === 'false')) {
            data[k] = data[k] === 'true';
        }
    });
    return submission;
}

function buildBooleanMap(components) {
    var booleanMap = {};
    _.each(components, function(c) {
        (c['values'] || []).forEach(function(v) { v['value'] === true ? booleanMap[c['key']] = true : null });
        Object.assign(booleanMap, buildBooleanMap((c['components'] || [])));
    });
    return booleanMap;
}

var form = Formio.createForm(document.getElementById('my_form'), schema, options)
    .then(function(form) {
        form.setSubmission(adjustSubmissionBeforeLoad(schema, _.cloneDeep(submissionData)));

        // this workaround is needed because the submit button is still enabled/functional in read-only mode
        if (isReadOnly) {
            $('#my_form').find("button[type='submit']").hide();
        }

        form.on('submit', function(submission) {
            // this workaround is needed because the submit button is still enabled/functional in read-only mode
            if (isReadOnly) {
                return;
            }

            // this is a workaround to deal with hidden inputs not getting cleared
            $('#my_form').find('input:hidden').not("[type='hidden']").each(function(i, e) {
                var name = e.name.slice(5, -1); // ex: name="data[actual_name]"
                submission.data[name] = '';
            });
    
            // not sure why this lingers around, but we don't want it in our data
            delete submission.data[""];
    
            var data = {json: JSON.stringify(adjustSubmissionBeforePost(schema, submission))};
            $.post(url, data)
                .done(function(response) {
                    window.location.reload();
                })
                .fail(function() {
                    alert('An error ocurred when trying to handle the request. Please try again later.');
                })
            });
    });
};
```

**Comment by travist** [comment]
I have been making some fixes to the renderer and would like to include a fix for this, but am a little unclear as to how everyone expects it to behave. From what

**Comment by travist** [comment]
give 2.17.6 a chance.

**Comment by KYusufbd** [comment]
This is a common issue when working with form element. It can be solved multiple ways. One of them is:

Call JSON.pase() on the value.
`
const isActive = JSON.parse(e.target.value);
`
It will return true of false rather than 'true' or 'false'.
