### ISSUE TITLE
[BUG] data loss - Radio button not keeping value when navigating between pages

### ISSUE THREAD

**Issue by CatBakun** [formio/formio.js#1717]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.1.0
- Frontend framework: JS
- Browser: Chrome 
- Browser version: 76.0.3809.100 (Official Build) (64-bit)

## Steps to Reproduce
1. In the first page select a radio choice.
2. Navigate to second page by clicking in the page link (not "next" button)
3. Navigate back to page 1

## Expected behavior
The radio I selected in page 1 remains selected

## Observed behavior
The radio I selected is unselected.

Note: this form works on version 3. Other wizard forms work inversion 4.

## Example
`git clone https://github.com/CatBakun/test-formio`
`cd test-formio`
`npm ci` 
`npm run start`

**Comment by randallknutson** [comment]
I tested this with a radio in a wizard and it worked as expected. Can you share a form where this isn't working?

**Comment by CatBakun** [comment]
Hi @randallknutson  I have shared the example in a repo, at the end of this report

**Comment by CatBakun** [comment]
Hi @randallknutson did you get the chance to try out my example and reproduce?
Some more context: This form was created with version 2, and used without this problem in version 3. But when moved to version 4, this form started to show this bug. It was hard to figure out because there is not error log when this happens.
Is there a list of breaking changes in components definitions between version 3 vs 4 or 2 vs 4? Maybe there is something in the form definition breaking the render value set of the components.

**Comment by jhen1422** [comment]
@CatBakun I can confirm this is working on the latest version of our 4x renderer. Can you try on the latest?

**Comment by CatBakun** [comment]
@jhen1422 No luck fter upgrading to 4.1.1, and later to 4.2.0-rc.7. Keep losing radio selections when navigating between pages. Your success try was with my example?
```
git clone https://github.com/CatBakun/test-formio
cd test-formio
npm ci
npm run start
```

**Comment by ps-from-md** [comment]
I have also noticed an issue when using the radio control in a panel.  I will get a fiddle together to see if i can reproduce it.  Simply put, if i have the control on the main area it works fine.  However, if I nest it in a Panel, it does not set the value.

**Comment by ps-from-md** [comment]
> I have also noticed an issue when using the radio control in a panel. I will get a fiddle together to see if i can reproduce it. Simply put, if i have the control on the main area it works fine. However, if I nest it in a Panel, it does not set the value.

After a bit more testing, it seems to be related to the Initially Hide property of the Panel (when set to collapsible.)  If I add the control to the Panel it works fine, but if I set the panel to be collapsible and then to initially hide, the value is not set...

**Comment by CatBakun** [comment]
Hello @randallknutson I have checked again and the bug seems to persist in version ^4.8.0-rc.11. Is it considered to include a fix for this in a future release?

**Comment by jhen1422** [comment]
@CatBakun Can you provide a jsfiddle example of the issue?
Thanks!

**Comment by CatBakun** [comment]
Hello @jhen1422 sure,
here is a jsfiddle: https://jsfiddle.net/g6mpsLfh/

There is also a repo you can clone in this report if it helps.

Thank you,

Enrique

**Comment by jhen1422** [comment]
@CatBakun That's strange. I can see the issue on the fiddle you provided but have been unable to replicate using my own examples. Regardless I will add a ticket to our backlog. Thanks!

**Comment by jhen1422** [comment]
@CatBakun 
Our developers have investigated this issue but we are unable to reproduce using the latest version of formio.js
