### ISSUE TITLE
[BUG] Year Field Within Day Component does not Populate Global Data Until Tabbed or Clicked Off

### ISSUE THREAD

**Issue by rscallscripts** [formio/formio.js#1724]
---
name: Year Field Within Day Component does not Populate Global Data Until Tabbed or Clicked Off
title: "[BUG]  Year Field Within Day Component does not Populate Global Data Until Tabbed or Clicked Off "
labels: bug
assignees: ''

---

## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: formio-enterprise image 6.6.5
- Formio.js version: ^3.24.0
- Frontend framework: vanilla javascript
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Add a day component and any other component
2. Under the conditionals of the other component, set a custom conditional as follows that validates when any of the day component fields are changed:
```
show = (data.day !== '00/00/0000') ;
```
3. Save the form
4. Preview the form
5. Ignoring the Day and Month fields, begin to enter information in the year field
6. Verify the component that depends on the custom conditional does not display

## Expected behavior
When data is entered into the year field in the day component, it should populate global data
## Observed behavior
Data entered into the year field of a day component does not populate global data unless the user clicks a step arrow, or clicks/tabs out of the year field

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Example jsfiddle: http://jsfiddle.net/k439nsch/8/

**Comment by rscallscripts** [comment]
Was not able to test in IE at the moment

**Comment by wag110894** [comment]
This issue has been resolved on the latest version of Formio.js. (4.4.2)
