### ISSUE TITLE
[BUG] Select List w/ valueProperty not Working as Expected

### ISSUE THREAD

**Issue by ps-from-md** [formio/formio.js#1726]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: none
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. create a select list with a url property to a JSON datasource
2. set the valueProperty to a field in the object array that is returned
3. set the data in the form submission to the default value 
4. run it

## Expected behavior
If I am setting the valueProperty of a Select object I would expect that when I define that value it would display the correct option in the dropdown list.  

For instance:
In the below linked fiddle, I would expect the Select list would load and select the option with id = 2 and therefor display "Ervin Howell".

## Observed behavior
Currently it displays the actual ID value and populates the list with the remaining items.

## Example
[jsfiddle](http://jsfiddle.net/bk2gp179/1/)

**Comment by randallknutson** [comment]
Do you have "Lazy Load" enabled for the select component? It sounds like you are setting the value before the options are loaded. If that is the case it will set the actual value since the options don't exist and it can't match.

**Comment by ps-from-md** [comment]
Lazy load is not selected, please see the jsfiddle from above.

**Comment by jhen1422** [comment]
@ps-from-md Thanks for the clarification, we were able to replicate this issue on our end as well and have created a ticket for the issue. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by aminmc** [comment]
@jhen1422 @randallknutson I think there are a few issues raised surrounding this.  I know my colleague @pixie79 has raised this as well.  Setting storage type does not fix or resolve this issue.

**Comment by aiwebb** [comment]
@aminmc I think that's correct - there are a few open issues currently that seem related. We'll be investigating this soon - and we're always open to PRs if you find a fix before us!

**Comment by wag110894** [comment]
@aminmc Thank you for your patience while we worked on getting this issue resolved. This has been resolved in the latest version of formio.js(4.9.0-beta.4)

Thank you for using Form.io!
