### ISSUE TITLE
Submit with createForm

### ISSUE THREAD

**Issue by worksofliam** [formio/formio.js#1729]
## Environment
Please provide as many details as you can:

- Hosting type
  - Local deployment
- Formio.js version: `@latest`
- Frontend framework: Bootstrap
- Browser: Chrome
- Browser version: ?

## Situation 

I am using createForm to display a form:

```javascript
    formio = Formio.createForm(document.getElementById('formio'), formiodata);
    formio.then(function (form) {
      form.submission = {
        data: sessionAnswers
      };

      form.on('change', function (event) {
        //We need to save our answers too :)
        sessionAnswers[event.changed.component.key] = event.changed.value;
      });
    });
```

I also have a function which is triggered by a button press (button is not part of the form):

```html
<button id="next_btn" type="button" class="btn btn-secondary" onclick="nextQuestion()">Next</button>
```

```javascript
function nextQuestion() {
  questionStage += 1;
  var checkQ, show = false;

  //Check is valid here!!
  $("#allform").fadeOut(fadetime, function () {
    for (i = questionStage; i < currentSubform.length; i++) {
      if (testQuestion(currentSubform[i]))
        break;
    }
  });
}
```

Inside of my `nextQuestion` function I need to figure out how I can make sure the current form is valid before continuing to show the next question.

Using createForm doesn't seem that well documented so I am having to create this issue.

Thanks.

**Comment by randallknutson** [comment]
You should probably set this up as a wizard with one question per page. Then you get the navigation at the bottom. In addition, each page will validate before moving to the next page. You can also manually move to the next page by calling form.nextPage();

**Comment by travist** [comment]
You could do something like this... https://formio.github.io/formio.js/app/examples/customwizard.html

Then before going onto the next page, you could execute. ```wizard.checkValidity()``` or something.
