### ISSUE TITLE
How to Implement Custom Renderer In an angular 7 App?

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#1730]
Hi, 
I'm trying to implement a custom renderer (to be able to extend / override Basic Components) in an angular App, 
and I do not seem to have a clue on how to do that, any help is appriciated, I already had a look on the Custom Renderer formio.custom.min.js thing, all is clear but I seem to not be able to find a way to integrate the same thing in angular. 
any help is appriciated

**Comment by aiwebb** [comment]
You can check out the `CheckMatrix` custom component from formio/angular-demo here: https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js

**Comment by imadbakir** [comment]
@aiwebb thank you I know about this, it is for custom Components, What I actually need is extending a basic component for example extend the functionality of a Dropdown select component, which already exists. for that it is different.

**Comment by randallknutson** [comment]
You can do the exact same thing but instead of importing base component, import the Select component and extend it. Then you can override any methods in the select component.
