### ISSUE TITLE
[BUG] Form Renderer : select component's customDefaultValue is not working as expected

### ISSUE THREAD

**Issue by prashantsail** [formio/formio.js#1735]
I am planning to migrate formio.js 3.26.0 >> latest 4.x (4.1.1)
This bug is a blocker for my migration.

## Environment
- Formio.js version: 4.1.1
- Frontend framework: vanilla js
- Browser: Chrome
- Browser version: 76.0

## Steps to Reproduce
1. Render a form using the JSON schema provided in the example section
```
Note:
This scenario works as expected in formio.js@3.26.0
```

## Expected behavior
- The `customDefaultValue` should be set on render as well as after redraw of the select component
- Working in 3.26.0 : https://codepen.io/psail4444/full/oNvmbvz

## Observed behavior
- The `customDefaultValue` is NOT set on render as well as after redraw of the select component
- Stopped working in 4.1.1 : https://codepen.io/psail4444/full/KKPJzwd

## Example

JSON schema:
```js
{
    "display": "form",
    "components": [
        {
            "type": "selectboxes",
            "key": "countries",
            "label": "The checked countries are source of the Select Component",
            "values": [
                {
                    "label": "USA",
                    "value": "usa"
                },
                {
                    "label": "Australia",
                    "value": "australia"
                },
                {
                    "label": "Singapore",
                    "value": "singapore"
                },
                {
                    "label": "England",
                    "value": "england"
                }
            ]
        },
        {
            "type": "select",
            "key": "selected_country",
            "label": "The checked countries are source of the Select Component",
            "customOptions": {
                "removeItemButton": false,
                "searchEnabled": false
            },
            "refreshOn": "countries",
            "clearOnRefresh": true,
            "template": "{{item.label}}",
            "customDefaultValue": "value = _.filter(_.map(data.countries,(val,ky) => {return val && {'label': ky, 'value': ky}}),(val) => val)[0]",
            "dataSrc": "custom",
            "data": {
                "custom": "values = _.filter(_.map(data.countries,(val,ky) => {return val && {'label': ky, 'value': ky}}),(val) => val)"
            }
        }
    ]
}
```

**Comment by jhen1422** [comment]
@prashantsail Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket for the issue. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
After investigation, we discovered that this is not a bug. The Default value only calculates on initial form load. You should use calculated value with "Allow override of calculated value"


Hope that this helps.
Thanks.
