### ISSUE TITLE
[BUG]  Can not edit "checkmatrix" custom component settings in form builder v4

### ISSUE THREAD

**Issue by CatBakun** [formio/formio.js#1737]
## Environment
Please provide as many details as you can:

The custom component example here: https://formio.github.io/formio.js/app/examples/customcomponent.html does not allow to edit in form builder. Is it possible to get the example updated so it works in both FormBuilder and WebForm/WizardForm at the same time?

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.1.0
- Frontend framework: JS/bootstrap3
- Browser: Chrome 
- Browser version: 76.0.3809.100 (Official Build) (64-bit)

## Steps to Reproduce

`git clone https://github.com/CatBakun/test-formio`
`cd test-formio`
`git checkout bug/cant-edit-custom-form-in-builder`
`npm ci` 
`npm run start`

1. Hover the "Select" component.
2. Confirm that "settings" actions buttons are displayed fot the "Select" component.
3. Hover custom "checkmatrix" component.
4. Confirm that "settings" actions buttons are displayed for the "checkmatrix" component.

## Expected behavior
"settings" actions buttons are displayed for the custom "checkmatrix" component.

## Observed behavior
"settings" actions buttons are NOT displayed for the custom "checkmatrix" component.

## Example
`git clone https://github.com/CatBakun/test-formio`
`cd test-formio`
`git clone bug/cant-edit-custom-form-in-builder`
`npm ci` 
`npm run start`

**Comment by jhen1422** [comment]
@CatBakun Thank you for the report. We have created a ticket for the issue and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by randallknutson** [comment]
We've got an updated version of how to do this. See https://github.com/formio/module-example

You can use it by:
import example from 'module-example';
import { Formio } from 'formiojs';

Formio.use(example);

**Comment by moeVdm** [comment]
@randallknutson I don't understand how we can call the function "Formio.use". It's not a static function of the Formio class.

I am on formiojs 4.7.8.

**Comment by randallknutson** [comment]
It is in a little bit of a weird spot. We couldn't add it as a static method on the Formio class because it caused circular dependencies so it is here: https://github.com/formio/formio.js/blob/master/src/formio.form.js#L60

**Comment by marcus-at-localhost** [comment]
@randallknutson how can the [Custom Component Example](http://formio.github.io/formio.js/app/examples/customcomponent.html) be fixed, so the edit buttons show up?

As far as I understand, the component has to be wrapped in `super.render()` like here:
https://github.com/formio/module-example/blob/master/src/components/CheckMatrix/CheckMatrix.ts#L71
and I suppose, `super.render` wraps the form in this template: https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builderComponent/form.ejs

In the Custom Component Example this is missing.

```js
CheckMatrixComponent.prototype.render = function(element) {
  var tpl = '<div class="table-responsive">';
  tpl += this.renderTemplate('label', {
    label: this.labelInfo,
    component: this.component,
    element: element,
    tooltip: this.interpolate(this.component.tooltip || '').replace(/(?:\r\n|\r|\n)/g, '<br />'),
  });
 // ...
  return tpl;
};
```

How is it possible to get access to `super.render()` from the outside? is there another way to get the component edit buttons into a custom component?

**Comment by marcus-at-localhost** [comment]
I kind of solved it. Please correct me if there is a better way: https://github.com/formio/formio.js/issues/2038#issuecomment-559308874

**Comment by CatBakun** [comment]
Hello @jhen1422 do you know if there is a plan to get a fix for this in upcoming releases?

**Comment by jhen1422** [comment]
@CatBakun This item is still on our 4x backlog. Feel free to contact support@form.io for information on expediting.

**Comment by wag110894** [comment]
Hello @CatBakun, 

After discussion with our developers, the checkmatrix component just an example that you are able to create custom components and not to be used as a component. 

Thank you,

William Gay

**Comment by CatBakun** [comment]
Hello @wag110894, I just used the checkmatrix in my example because it is the one in the documentation, but I found this issue with other custom components that I have. When I got this issue in my custom component I wanted to ensure that the problem was not coming from my custom component code, and checked with the checkmatrix just to confirm that.
The problem I have is that I can not figure out what would be the right way to define a custom component so it is configurable in the form builder.
Is it possible to get an example of a custom component that works in forms builder and also in the form rendering?

Thanks,

Enrique

**Comment by samswbk** [comment]
@wag110894 i had the same issue, but i think the problem is on WebFormBuilder.js>_this.options.hooks.renderComponent.

i cannot figure out why, but the key of custom component it's empty even though key: "checkmatrix" is configured:

self.key is empty

`if (self.type === 'form' && !self.key) {
        // The main webform shouldn't have this class as it adds extra styles.
        return html.replace('formio-component-form', '');
      }`

**Comment by heather-formio** [comment]
Closing as this is stale but please feel free to reopen as needed. Thank you for your contributions, everyone!
