### ISSUE TITLE
[BUG] Nested Forms Does Not Fire The Submit Event

### ISSUE THREAD

**Issue by lailapfit** [formio/formio.js#1738]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 6.9.0
- Frontend framework: Pure JS
- Browser: Chrome
- Browser version: 76.0.3809.100

## Steps to Reproduce
1. Add JS code from below and render the form (it is public)
2. Add your own submission to the form

## Expected behavior
-Data will be saved in the parent and child form.
-File will be saved to S3.
-Email action will occur.
-Console.log messages will occur after each submission

## Observed behavior
-Data saved to the parent and child form.
-File saved to S3.
-Email action does not occur.
-Console.log messages does not fire at submit.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
window.onload = function() {
    // 1) Render the instance of Formio
    Formio.createForm(document.getElementById('formio'), 'https://gczorxncusomhpg.form.io/commentnested', {
        hooks: {
            // 2) Use hooks to insert the data for Project ID and geo-Location before submitting the data
          beforeSubmit: (submission, next) => {
            // Alter the submission
            submission.data.location = 'Franklin';
            submission.data.projectId = '01';
            submission.data.status = 'New';
            this.console.log("Only the before submit hook submitted");
            // Only call next when we are ready.
            next();
          }
        } 

      }).then(function(form) {
          // 3) Submit the form data
form.on('submit', (submission) => {
    console.log('The form was just submitted!!!');
    console.log(submission);
    console.log(submission.data);
    console.log(submission._id);
        });
        // 4) Catching errors
form.on('error', (errors) => {
    console.log('We have errors!');
        });
        // 5) If a Thank You page is needed
// form.on('submitDone', function(completed) {
//     window.location = './thanks.html';
// })
    });
  };
```
![screenshot](https://user-images.githubusercontent.com/52266239/65465721-fad88f80-de2a-11e9-9e36-8d06a6e0f720.png)

**Comment by jhen1422** [comment]
@lailapfit 
Thank you for the report. We have created a ticket and added to our 4x backlog. It may be some time before we have the bandwidth to fix this issue. If you need to expedite a fix, please feel free to contact support@form.io for a quote. We welcome pull requests to this library as well. Thank you
