### ISSUE TITLE
[question] Is it possible to set form _id ?

### ISSUE THREAD

**Issue by gcrofils** [formio/formio.js#1742]
We have several forms on the same page and we would like to set up interactions between them. 
It would be nice to assign a predefined id to a form and then
```Formio.forms['myFirstFormId']```

Currently we create a global variable after the form instanciation. It works well, but It's a kind of useless duplication. 

```
Formio.createForm(document.getElementById('...'), '...', { }).then(function(form) {
  Formio.forms['myFirstFormId'] = form;
} ...
```

**Comment by randallknutson** [comment]
It is not possible to set the form._id. This is generated in the database which means it isn't configurable. You could go through the forms and map to the "name" property which is unique but user configurable.

**Comment by gcrofils** [comment]
Sorry for the confusion. We are currently experimenting with the locally deployed and not the hosted version. 
However since you said the ID is generated _in the database_, it means it could be set during the instantiation of the form `Formio.createForm...` , correct ?

**Comment by randallknutson** [comment]
Formio.createform is a client side functionality which doesn't occur when the form is actually created. The data is sent to the server and in the database create event is when that id is generated.

If you need a unique identifier for submissions you can accomplish this by adding a hidden field to the submission and then setting the value in the submission when the form is created. We have a lot of people who do something like this. While the _id is still generated, there is a set id associated with it as well that you can filter and query on.
