### ISSUE TITLE
[BUG] No way to identify if a change event was fired by manual change or pre-load of a submission

### ISSUE THREAD

**Issue by gith-amitm7** [formio/formio.js#1743]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: ^4.0.8(via react-formio ^4.0.0)
- Frontend framework: React
- Browser: Chrome
- Browser version: 72

## Steps to Reproduce
1. Render a form by passing submission initially
2. Enable logging on "onChange" event handlers

## Expected behavior
There should be changed: undefined sort of value in the submission, indicating that it was a change fired due to preloading of submission
## Observed behavior
A change event is fired with valid **changed field**(which is a randomly picked component from the changed fields). This randomness is making it difficult to distinguish from manual change event

**Comment by randallknutson** [comment]
There are a couple items I see here:

1. We debounce the change event which causes the random selection of the changed field when multiple fields change. This could be considered a bug report and we should probably look at either changing this or making it a configurable option to do an update event on each field that changed.

2. A feature request to be able to distinguish whether a change event was the result of user interaction or an automated process such as setting the submission or a calculated value based on a user event.

We can add these items to our development list to be looked at. Is this something you could contribute or are interested in sponsoring?

**Comment by gith-amitm7** [comment]
Closing this as I am able to identify this using: submission > changed > flags > modified.
Cases when it is a non-manual change event, modified flag is not present, whereas for manual changes, it always has value set to true.
Wish these behaviours could be made more accessible to know, through some documentation.
