### ISSUE TITLE
[BUG] [4.1.1] when rendering as HTML, the controls are not removed such as Add Another and "x" buttons

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#1747]
When rendering the form as HTML, the controls are not being removed.   Controls like Add Another are still being shown.  In v4 is there additional config needed?

**Comment by randallknutson** [comment]
I would have thought they were removed with viewAsHtml. You can also set options.readOnly = true and it will remove all of those controls. If that isn't the case it may be a bug.

**Comment by StephenOTT** [comment]
Okay seems to be working with readOnly = true and renderModel as html.  Why would you render as HTML but not have readOnly turned on?

**Comment by randallknutson** [comment]
Not sure why it is like that. Render as html should probably default to read only since it doesn't make sense to ever change anything if there aren't form elements.

**Comment by wag110894** [comment]
Thank you for your patience while we got this issue resolved. The Addreadonly mode Another and "x" buttons are now removed in version 4.7.7.

Thanks.

**Comment by StephenOTT** [comment]
Thanks!!
