### ISSUE TITLE
[QUESTION] Translate FormBuilder

### ISSUE THREAD

**Issue by samswbk** [formio/formio.js#1748]
It's possible translate the formBuilder tool?

**Comment by randallknutson** [comment]
Yes. This is example is the renderer but it is the same for form builder. http://formio.github.io/formio.js/app/examples/language.html

**Comment by gregbown** [comment]
@randallknutson Randall, I am not as familiar, please elaborate. I only see a setter in Webform.js.
Trying to pass it in as an option at builder instantiation has no effect either.  Though I did not see a setter I also tried setting it as described with no effect.

**Comment by randallknutson** [comment]
Webform and WebformBuilder have the same root class that handles the translation so it should work exactly the same. Each string is then passed through the this.t() function to translate it based on the currently selected locale.

**Comment by gregbown** [comment]
@randallknutson Ah, I see. Apologies. In my node application (server side rendering) I have i18next configured to look for a cookie. Surprisingly this is observed by the Formio.js included version despite no client side include or configuration for this. Nice! 

Setting the locale via builder.language = 'zh' also achieves complete localization.

![image](https://user-images.githubusercontent.com/1952728/72316620-afe9be80-364b-11ea-89a8-286a53ce2005.png)

Setting language: 'zh' in my builder config only has partial effects, barely any words are localized indicating most components do not observe the language option passed in at instantiation.

The i18n JSON must be at the root level, or builder level in the options. I initially had it inside the builder level.

correct placement:
```
  builder: {
    data: false,
    ...
  },
  i18n: {
    zh: {
      complete: '提交完成',
      error: '提交前，请更正以下错误。',
      month: '月',
      day: '天',
```

Thank you Randall

**Comment by samswbk** [comment]
@randallknutson i try do like the example but the builder don't translate

formBuilder = new Formio.FormBuilder(document.getElementById("builder"), form, {
        builder: builder,
        language: 'pt',
        i18n: {
            pt: {
                textfield: 'Campo de Texto'
            }
        },
        editForm: editForm
    });

**Comment by randallknutson** [comment]
textfield is not the correct key. It is probably "TextField" or something like that. It is case sensitive.

**Comment by gregbown** [comment]
@samswbk I figured out how to translate form builder internally if you need to do this, [see here](https://github.com/formio/formio.js/issues/1839)
