### ISSUE TITLE
select value fails to preload

### ISSUE THREAD

**Issue by dannymcpherson** [formio/formio.js#175]
Sorry for the short description (in a hurry).  When preloading data, the form correctly renders, but the underlying data for select input types is missing.  This causes form validation to fail on submit, even though it actually looks correct.

**Comment by travist** [comment]
Are you using default values?  If this is the case, there is a fix coming in next release.

**Comment by CyrilHurtado** [comment]
Will a release for the embed version, including this fix, be available soon ?

**Comment by jhen1422** [comment]
This issue has been resolved
