### ISSUE TITLE
[BUG] Required image not validating

### ISSUE THREAD

**Issue by CatBakun** [formio/formio.js#1750]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.2.0-rc.7
- Formio.js version:4.2.0-rc.7
- Frontend framework: bootstrap3
- Browser: Chrome
- Browser version: Version 76.0.3809.100 (Official Build) (64-bit)

## Steps to Reproduce
1. Clone and run the example:
```
git clone https://github.com/CatBakun/test-formio
cd test-formio
npm ci
npm run start
```
2. Open browser and see 1st form page
3. Click next button
4. Observe invalid fields in red

## Expected behavior
The required image is marked invalid

## Observed behavior
The required image does not get the error highlight

![Screenshot from 2019-09-24 18-01-25](https://user-images.githubusercontent.com/4873355/65550700-89fea980-def6-11e9-8b10-e9f1c8048dd2.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:
```
git clone https://github.com/CatBakun/test-formio
cd test-formio
npm ci
npm run start
```

**Comment by jhen1422** [comment]
@CatBakun We tested on the mentioned version of formio.js and are unable to replicate the issue. Please view the jsfiddle for confirmation.

http://jsfiddle.net/6twzcmnd/

**Comment by CatBakun** [comment]
Hi @jhen1422 This is your fiddle, but with my form. This form works in version 2 and 3, but has this bug in version 4: http://jsfiddle.net/ebakunKelsus/xw7kct5v/7/

**Comment by jhen1422** [comment]
@CatBakun 
We will need to dig into your form to understand why the file is not validating like it should. I've opened up a ticket and will prioritize this with our dev team next Monday.

Thanks for the providing the fiddle!

**Comment by CatBakun** [comment]
Hi @jhen1422 where you able to prioritize this problem?

Thanks
