### ISSUE TITLE
[BUG] Editgrid row validation causing components to be marked invalid before "Save" is clicked

### ISSUE THREAD

**Issue by christophermurphy2-allscripts** [formio/formio.js#1758]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: formio-enterprise image 6.6.5
- Formio.js version: 3.28.0
- Frontend framework: vanilla javascript
- Browser: Any
- Browser version: any

## Steps to Reproduce
1. Add an editgrid to a form.
2. Add components (need more than one to see the issue) such as a textfield to the editgrid and make them required.
3. After entering a value in one of the components the rest will be outlined in red as if invalid, but no invalid messages will display.

## Expected behavior

Row validation should be called on save, not when the row is still being filled out.

## Observed behavior

This seems to happen because row validation is returning false even though the components inside the row pass their individual validation checks since they aren't yet dirty. This explains why no error messages are displayed. Could be related to recent changes to the base component around checkValidity().

## Example

Here is a link to a small repo I made that contains the error conditions: <https://github.com/christophermurphy2-allscripts/row-validation-bug>

Note that if you enter a value in any of the textfields, the row validation will fail since the bottom two textfields are required.

**Comment by jhen1422** [comment]
@christophermurphy2-allscripts 
Thank you for the report. We were able to replicate this on our end and have created a ticket for the issue. We will discuss and prioritize this item in our planning meeting next Monday.

**Comment by travist** [comment]
This has been fixed in version 3.28.2
