### ISSUE TITLE
How to render custome PDF label

### ISSUE THREAD

**Issue by kkmaojunx** [formio/formio.js#1762]
Hi ,I am currently reading the source code and I find a problem. In PDF, how can I render  the component  with label name . but got type name to render. 

Thanks a lot

**Comment by kkmaojunx** [comment]
I see the progress and function about PDF  was all in a html of remote response. Not in formio.js

**Comment by randallknutson** [comment]
Can you clarify you question a little? The pdf is generated on the server side. You can also trigger the browser based pdf download functionality if you want to use that instead of our server.

**Comment by kkmaojunx** [comment]
@randallknuston what I mean is  how can does it render components  with label in PDF build. currently,whatever i drop from sidebar.   for example,I drop a TextField component into right iframe .and set it label  named 'test label' and click save button .however it render  to 'textfield'  instead of "test label".   So please help me know how to achieve it. Thanks

**Comment by randallknutson** [comment]
The PDF render should use the labels of the form for each component. If you aren't seeing that, can you provide an example form and pdf output that is different?

**Comment by kkmaojunx** [comment]
sorry  , I didn`t get you. I will show you the whole progress what the issue I met.
1.drag a componet  type 'TextField'
![image](https://user-images.githubusercontent.com/30437104/65810891-3f757980-e1e3-11e9-9be4-1ab534d37dfa.png)
2.modify the label name 'label test'
![image](https://user-images.githubusercontent.com/30437104/65810901-5b791b00-e1e3-11e9-9cb0-6ba4fa285889.png)
3.click save button 
![image](https://user-images.githubusercontent.com/30437104/65810903-6af86400-e1e3-11e9-8865-f90b16537eb2.png)
4.however, the result of rendering is 'textfield' instead of label test 
![image](https://user-images.githubusercontent.com/30437104/65810919-9e3af300-e1e3-11e9-9ad4-c5ba0f45e1f7.png)

So I can`t understand how to setting in formio.js to show the pdf component with it `s label  I defined@randallknutson

**Comment by aiwebb** [comment]
@kkmaojunx, the `textfield` text you're seeing is only visible in PDF builder mode.

When rendering in PDF overlay edit mode, labels are not rendered; this is because labels are generally not useful due to most PDF backgrounds already having the inputs labeled. Labels *are* rendered when creating a non-overlay submission PDF (i.e., a PDF download of a Webform submission).
