### ISSUE TITLE
[BUG]  Checkbox with hyperlinks

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio.js#1769]
Hello,
We would like to create a checkbox component with hyperlinks into the label, but the HTML tags don't seem to be interprated in this attribute. Do you have a solution for that please ?

Regards,

Audrey

**Comment by travist** [comment]
This is probably because we strip out HTML for protection against XSS. The way you accomplish this is to create a custom component that allows for hyperlinks within a checkbox component.

**Comment by AudreyCb** [comment]
OK, thanks for the reply.

**Comment by franke-mc** [comment]
@AudreyCb : When you develop such a custom component, please consider sharing the code...

**Comment by AudreyCb** [comment]
Hi, we didn't have to develop this component, actually, the last version provide the possibilty to display hyperlinks in the checkbox's label.

**Comment by franke-mc** [comment]
Cool, thanks for the hint.

**Comment by SwathiPuskoori** [comment]
How can we add hyperlink in checkbox component? Any help on this ?
