### ISSUE TITLE
[BUG] Error messages remain for Select components even when valid

### ISSUE THREAD

**Issue by gavinorland** [formio/formio.js#1772]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.2.0-rc.7
- Frontend framework: React
- Browser: Chrome
- Browser version: 77.0.3865.90 (Official Build) (64-bit)

## Steps to Reproduce
1. Add a Select component with custom validation
2. Try to submit a form without selecting anything
3. Observe error message and select something
4. Click outside component
5. Try again to submit form

## Expected behavior

Error message should be removed from the component when an item is selected and valid returns true. It should not be present when form is submitted.

## Observed behavior

Error message remains even when valid returns true. Form can however be submitted.

## Example

http://jsfiddle.net/dwo9bq61/2/

**Comment by gavinorland** [comment]
FYI: This issue appears to have been introduced in formiojs version 4.0.9.

**Comment by travist** [comment]
This sounds like a bug. We will investigate on our end.

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/1786

**Comment by wag110894** [comment]
This issue has been resolved in the latest version of formio.js (4.3.3)
