### ISSUE TITLE
[BUG]  select submit issue

### ISSUE THREAD

**Issue by karam-naser** [formio/formio.js#1778]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.30
- Frontend framework: 
- Browser: Chrome
- Browser version: 77.0.3865.90

## Steps to Reproduce
1. making a custom template
2. trying to fill it with data
3. 

## Expected behavior
when removing old selected value it stay when submit the values
## Observed behavior
select list old value it submit the old one

## Example
![1st screenshot](https://ibb.co/W5Zp5Gw)
![2nd screenshot](https://ibb.co/Kj21pw9)
https://ibb.co/W5Zp5Gw
https://ibb.co/Kj21pw9

**Comment by karam-naser** [comment]
any idea how to solve it ??

**Comment by randallknutson** [comment]
I see you are using an old beta version. Can you try the latest stable release and see if this was resolved? We had a few issues with selects back when those betas were released and you may be experiencing one of those issues.

**Comment by karam-naser** [comment]
i've updated it to v4.3.1 but the same issue still there

**Comment by jhen1422** [comment]
@karam-naser 
Could you please provide a jsfiddle of the problem so we can further investigate?

**Comment by heather-formio** [comment]
Closing as this is stale. Please reopen if needed. Thank you for your contributions!
