### ISSUE TITLE
[BUG] Month Placeholder in Day Component not Behaving as Placeholder

### ISSUE THREAD

**Issue by rscallscripts** [formio/formio.js#1785]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: formio-enterprise image 6.6.5
- Formio.js version: 3.28.0
- Frontend framework: vanilla javascript
- Browser: Any
- Browser version: Any

## Steps to Reproduce
1. Drag a new Day Component onto a form
2. Add text in the Month Placeholder textbox
3. Save the form
4. Preview the form
5. Observe the Month field
6. Verify the placeholder is not present
7. Click the Month dropdown
8. Observe the placeholder is now listed as an extra option in the month dropdown

## Expected behavior
Entered placeholder in the month field is present

## Observed behavior
Entered placeholder in the month field is added as an extra option in the month dropdown

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
![MonthPlaceholder](https://user-images.githubusercontent.com/55595545/65978873-0e42b680-e43a-11e9-882c-4b7b314d0075.PNG)
![MonthOption](https://user-images.githubusercontent.com/55595545/65978874-0e42b680-e43a-11e9-94ff-34e43ba735b8.PNG)

**Comment by wag110894** [comment]
Thanks for reaching out!

We are able to replicate this issue on our side.  We have created a ticket and have added this to our backlog. 

We will let you know once this issue is resolved.

Thanks,

**Comment by wag110894** [comment]
After discussing with our developers, this is working as expected.

**Comment by rscallscripts** [comment]
We believe this should still be considered a bug since it behaves as we would expect in version 4 of formio and regular select components in version 3 also support placeholders.

Scott Childs
Associate Software Developer
allscripts.com<http://www.allscripts.com/> | @allscripts <https://twitter.com/Allscripts>

Allscripts: Building open, connected communities of health

**Comment by travist** [comment]
So you are saying that this component works as you would expect in version 4.x and you are just looking for a backport to 3.x?  If so, then we could allocate this as a specific backport effort to 3.x.

**Comment by rscallscripts** [comment]
I believe so, yes. If possible that would be great

Scott Childs
Associate Software Developer
allscripts.com<http://www.allscripts.com/> | @allscripts <https://twitter.com/Allscripts>

Allscripts: Building open, connected communities of health

**Comment by wag110894** [comment]
Thanks for reaching out!

Here is a fiddle showing the month placeholder behaving the same as 4x: https://jsfiddle.net/qLt87y0m/. 

Will you clarify what the difference is between 3x/4x that you are referring to as they appear to be the same?

Please let us know.

Thanks,

**Comment by jhen1422** [comment]
@rscallscripts 
Here is a video link showing the day component being rendered using 
3.28.2 and 4.3.1
https://screencast.com/t/nzzaRRir

In both cases, the day component is displaying the Month place holder when renderer as well as showing the place holder in the option list (as expected).

If you look at the formio.full file, in the jsfiddle linked in the previous comment, we are using version 3.28.2 to render the form.

**Comment by jhen1422** [comment]
@rscallscripts We can confirm the difference between 3x/4x and have created a bug to fix the placeholder text for the Day- Month field in version 3.28.2. This item will get prioritized next week during our strategic planning session.

**Comment by heather-formio** [comment]
This is working as expected in 4.x. Closing Thread.
