### ISSUE TITLE
[BUG] File Upload: Syntax Error: Unexpected token * in JSON at position 1

### ISSUE THREAD

**Issue by daspilker** [formio/formio.js#1789]
## Environment
We are using angular-formio 4.2.4 in an Angular 8 app.

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 4.2.8
- Formio.js version: 4.2.8
- Frontend framework: Angular
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Create a form with a file component, set storage type to 'url'
2. Embed form in Angular app
3. Try to upload file

## Expected behavior

File is uploaded to server.

## Observed behavior

Error message "Syntax Error: Unexpected token * in JSON at position 1" is shown before file is being uploaded.

**Comment by randallknutson** [comment]
4.2.8 had an error introduced with the "content-type" header that was causing requests to fail. This was fixed in 4.2.9. Can you test out the latest version and see if this is fixed?

**Comment by daspilker** [comment]
The upload is still not working with 4.3.2, the error message is slightly different. I filed a new bug report: https://github.com/formio/formio.js/issues/1857
