### ISSUE TITLE
[BUG] missing deleteFile in 4.2.8

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1793]
Hello

I raised a PR https://github.com/formio/formio.js/pull/1688 which was merged and I can see the code in 4.x branch however the code (File.js):
```js
if (fileInfo && (this.component.storage === 'url')) {
          const fileService = this.fileService;
          if (fileService && typeof fileService.deleteFile === 'function') {
            fileService.deleteFile(fileInfo);
          }
          else {
            this.options.formio.makeRequest('', fileInfo.url, 'delete');
          }
        }
```
is missing from 4.2.8.  Is it possible to find out what happened? We need this function.

**Comment by randallknutson** [comment]
I think this got merged into the wrong branch. Master is now our "4.x" branch so it got orphaned out there. I'm moving it over and it will be in the next build.

**Comment by aminmc** [comment]
Thank you!

**Comment by travist** [comment]
This will be in the 4.2.12 release.
