### ISSUE TITLE
[BUG] DateTime component with date format dd/MM/yyyy

### ISSUE THREAD

**Issue by moshefi** [formio/formio.js#1794]
## Environment
- Hosting type
  - [x] Form.io
  - Version: latest
- Formio.js version:
- Frontend framework: JS
- Browser:
- Browser version:

## Steps to Reproduce
https://jsfiddle.net/moshefi/p7bwm1rh/9/

## Expected behavior
The date value preserves on page next/prev
When date format is 'yyyy-MM-dd' works fine.
When date format is 'dd/MM/yyyy' breaks.

## Observed behavior
The date is lost after go next and then go prev
Same is when loading submittion data

## Example
https://jsfiddle.net/moshefi/p7bwm1rh/9/

**Comment by jhen1422** [comment]
@moshefi 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket for the issue. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by marcopollacci** [comment]
Same problem here with 'yyyy-MM-dd'.
I think the problem it's always if you change the default format. Even if form it's not wizard
Formio, can you tell me where i can look to fix it and after make a pull request? :)

**Comment by wag110894** [comment]
This issue has been resolved in the latest version of formio.js (4.4.1).

**Comment by lane-formio** [comment]
<div>Agent Savvas Sidiropoulos linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/49182">49182</a> for this issue.</div><br/>
