### ISSUE TITLE
Placeholder is not coming on “Select” component on renderer [BUG] 

### ISSUE THREAD

**Issue by pardeep224** [formio/formio.js#1798]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Local deployment
    - Version: 4.2.6
- Formio.js version: 4.2.6
- Frontend framework: angular-formio
- Browser: Google Chrome
- Browser version: 77.0.3865.90 (Official Build) (64-bit)

## Steps to Reproduce
1. Drag & drop "Select" component on the form.
2.  Set Placeholder value.
3.  Click on save button.

## Example:
NA

**Comment by heather-formio** [comment]
This is working as expected in 4.14.x.
