### ISSUE TITLE
Submit button needs to be clicked multiple times to submit the form. This issue is coming randomly and we are not able to replicate the exact scenario for this. [BUG] 

### ISSUE THREAD

**Issue by pardeep224** [formio/formio.js#1800]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Local deployment
    - Version: 4.2.6
- Formio.js version: 4.2.6
- Frontend framework: angular-formio
- Browser: Google Chrome
- Browser version: 77.0.3865.90 (Official Build) (64-bit)

## Steps to Reproduce
1.  Create any form with some any components
2.  Try to submit the form.

## Example
NA

**Comment by randallknutson** [comment]
I'm not sure if this is enough information for us to be able to fix it. Can you see if you can isolate the problem a bit more so we could possibly get reproducible steps?
