### ISSUE TITLE
[BUG] Date formatting on renderMode: 'html'

### ISSUE THREAD

**Issue by moshefi** [formio/formio.js#1804]
## Environment
- Hosting type
  - [X ] Local deployment
- Formio.js version: latest
- Frontend framework: JS

## Steps to Reproduce
https://jsfiddle.net/moshefi/p7bwm1rh/14/

## Expected behavior
The value should be formatted.

## Observed behavior
Raw date value is rendered

## Example
https://jsfiddle.net/moshefi/p7bwm1rh/14/

**Comment by themattkenney** [comment]
Another issue on the renderMode: 'html' is that the values are returned as "-" nothing is actually shown. We use this to allow users to print their submissions. Is this on the bug list to be fixed?

**Comment by jhen1422** [comment]
@moshefi 
This is currently the expected way the date/time data renders in HTML. Regardless we have created  at ticket in our backlog. If you're interested in sponsoring a change to the data format, please contact support@form.io. We also welcome pull requests in this library. Thank you!

**Comment by hieuiris1994** [comment]
In the example fiddle: https://jsfiddle.net/moshefi/p7bwm1rh/14/ 

I can't see the form values displayed in the HTML view. Although the form submission has been set.

![image](https://user-images.githubusercontent.com/19341943/75232404-bf7f2a00-57e9-11ea-8719-7fe2dd0a03ed.png)

Did I miss something? Any help will be appreciated. Thanks!

**Comment by hisuwh** [comment]
I've got the same problem as @hieuiris1994

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen as needed.

**Comment by hisuwh** [comment]
@heather-formio is it fixed?  Otherwise its only your (collectively formio) fault that its stale?

**Comment by ensemblebd** [comment]
Given the following: 
```
<Form 
	form={construct} 
	submission={{data: customized_submission}}
	options={{
		readOnly: true,
		renderMode: 'html'
	}}
/>
```

you can put the following somewhere above to prepare the "customized" output as a bandaid to fix this:

```
let customized_submission = submission.data;
let keys = Object.keys(submission.data);
for (let i=0;i<keys.length;i++) {
	var key = keys[i];
	
	for (var ii=0;ii<construct.components.length;ii++) {
		let comp = construct.components[ii];

		if (comp.key == key) {
			if (comp.type == "time") {
				let dt = new Date('01/01/2001 '+customized_submission[key]);
				if (isNaN(dt.getMilliseconds()) || dt.getMilliseconds() == 0 && dt.getHours() == 0 && dt.getMinutes()==0) {
				   // provided value from form isn't parsable based on the "time" component from formio.
				   customized_submission[key] = '';
				}
				else {
					customized_submission[key] = dt.toLocaleTimeString('en-US', time_opts);
				}
			}
			else if (comp.type == "date") {
				customized_submission[key] = new Date(customized_submission[key]).toLocaleDateString('en-US', date_opts);
			}
			else if (comp.type == "datetime") {
				// force it to be text, so the default format formio uses isn't used, rather our own. 
				comp.type='textfield';
				
				customized_submission[key] = new Date(customized_submission[key]).toLocaleDateString('en-US', dt_opts);
			}
			
			break;
		}
	}
}
```
