### ISSUE TITLE
If logic is applied to any control then default value becomes mandatory in builder even if the control is non mandatory [BUG] 

### ISSUE THREAD

**Issue by pardeep224** [formio/formio.js#1807]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Local deployment
    - Version: 4.2.6
- Formio.js version: 4.2.6
- Frontend framework: Angular-formio
- Browser: Google Chrome
- Browser version: 77.0.3865.90 (Official Build) (64-bit)

## Steps to Reproduce
1. Take a select component on form as "Country" and bind some values hardcoded from data tab.
2. Take another Text Field component on form. Add logic to make mandatory to this field on the basis of Country. Add the logic name.
3. In trigger section select type as "Simple".
4. Select "Country" option from "When the form component:".
5. In Action section provide "Action Name".
6. Select option as "Property" from Type options.
7. Select "Required" from Component Property options.
8. Set State true.
9. Save action and save logic.
10. Click on save button.

**Expected behavior:** Component setting should be saved successfully.
**Observed behavior:** On clicking on save button on popup window of component (Text Field) setting, an error message "Default Value is required" is coming.

Example:
NA

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen as needed.
