### ISSUE TITLE
Listen for cancel event with FormRenderer?

### ISSUE THREAD

**Issue by aloisbarreras** [formio/formio.js#181]
I'm successfully using FormioForm and FormioWizard to display forms in my application. However, pressing the cancel button just resets the form...

I would like to be able to listen for a built in event like 'cancel' so I can customize the behavior of clicking the cancel button such as navigating to a different page.

**Comment by travist** [comment]
That fires the ```resetForm``` event, so you can listen for it like this.

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example').then(function(form) {
  form.on('resetForm', function() {
    console.log('Form was reset!');
  });
});
```

**Comment by aloisbarreras** [comment]
@travist does this work with a form that was created by setting the form property using the FormioForm renderer?

```
            this.form = new FormioForm(document.getElementById('new-form-submission'));
          this.form.form = { ... };
          this.form.on('submit', (submission) => {
            console.log('Form submitted');
          });
          this.form.on('resetForm', (e) => {
console.log('hello world');
          });
```

The form renders correctly and the 'submit' event is properly firing, but I'm not getting anything when listening for the 'resetForm' event...

**Comment by aloisbarreras** [comment]
@travist listening for that event just doesn't work...

are there any plans for a bug fix or do you have a working example somewhere?
