### ISSUE TITLE
[BUG] FormBuilder stores the child components of a tab, twice

### ISSUE THREAD

**Issue by MaximeTroiano** [formio/formio.js#1814]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: any
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Go to the builder of Form.io (https://formio.github.io/formio.js/app/builder)
2. Drag & drop a Tabs component and create two empty tabs
3. Drag & drop a datagrid in the first tab, add a simple text field
4. Drag & drop a datagrid in the second tab, add a simple text field
5. Verify the generated schema, there is an error because the schema of the second tab contains both of the datagrids

## Expected behavior
It souldn't store both datagrids in the second tab, as the form builder doesn't show this

## Example
Here you can see both tabs containing a simple datagrid with one field
![1](https://user-images.githubusercontent.com/13046607/66219322-3d238b80-e6cb-11e9-862c-0c562bc1b11e.png)

This is the schema of the second tab, which includes an error (2 datagrids but only one has been added in the builder)
![2](https://user-images.githubusercontent.com/13046607/66219327-3eed4f00-e6cb-11e9-80e0-e668b18cd581.png)

EDIT
I just tested this without datagrid => Same problem
And I tried the same config under Form.io 3.0.0 => it works well

**Comment by MaximeTroiano** [comment]
I just tested this without datagrid => Same problem
And I tried the same config under Form.io 3.0.0 => it works well

**Comment by jhen1422** [comment]
@MaximeTroiano 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
This issue has been resolved on the latest version of our Core Renderer (4.4.1).
