### ISSUE TITLE
[BUG] Can't use the component Data Map in form builder.

### ISSUE THREAD

**Issue by aaron5670** [formio/formio.js#1815]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: any
- Browser: Chrome
- Browser version: 77.0.3865.90

## Steps to Reproduce
1. Go to the builder of Form.io [https://formio.github.io/formio.js/app/builder](https://formio.github.io/formio.js/app/builder)
2. Drag & drop a **Data Map** component and click on the save button.
3. Drag & drop a text field (or any other component).
4. Now the form builder is broken..

## Expected behavior
Another component can be drag & dropped.

## Example
See console error: [Console error](https://prnt.sc/pexwe9)
Current form builder layout: [layout](https://prnt.sc/pexx2w)

**Comment by heather-formio** [comment]
This is resolved and working as expected.
