### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gregbown** [formio/formio.js#1818]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version: 4.2.x
- Formio.js version: 4.2.12
- Frontend framework: NodeJS
- Browser: Chrome
- Browser version: Current

## Steps to Reproduce
1. Build a form with at least two elements
2. Re-order the form elements
3. Observe there is no change event, therefore; any form render cannot update to reflect changes.
4. None the form [render, redraw, renderComponents, triggerChange] methods have any effect.

## Expected behavior
change event should occur not just when adding a component but also when moving.
There should be a working redraw or render method to call on the formio render or the triggerChange method should cause it to update.

## Observed behavior
moving components do not trigger any observable events.
## Example
[Live example, and/or example code to help demonstrate the issue.](https://formio.github.io/formio.js/app/builder)

None the form [render, redraw, renderComponents, triggerChange] methods have any effect.
The only work around I found was to set the form in a builder on render event handler.
```
        builder.on('render', function() {
          instance.form = builder.form;
        });
```

**Comment by jhen1422** [comment]
@gregbown Thank you for the report. We have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by marcus-at-localhost** [comment]
Is there any progress on this?

**Comment by jhen1422** [comment]
@gregbown 
this should be fixed in the latest 4x renderer. Can you please retest and let us know?

**Comment by marcus-at-localhost** [comment]
@jhen1422 moving a component around emits `addComponent` but no `change` event.

```js
  form.on('addComponent', function(info, parent, path, index, isNew) {
    console.log('addComponent', info, parent, path, index, isNew);
    if(!isNew){
    	alert('Moved')
    }
  });
```

https://jsfiddle.net/pmh5091k/

**Comment by jhen1422** [comment]
@marcus-at-localhost After discussion with the team, we have determined that the addComponent triggering in place of the change vent is expected behavior when moving components within the builder.
