### ISSUE TITLE
In grid if we set the required property true/false  of any control dynamically based on logic then asterix (*) sign does not come when required is true [BUG] 

### ISSUE THREAD

**Issue by pardeep224** [formio/formio.js#1820]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Local deployment
    - Version: 4.2.6
- Formio.js version: 4.2.6
- Frontend framework: Angular-Formio
- Browser: Google Chrome
- Browser version: 77.0.3865.90 (Official Build) (64-bit)

## Steps to Reproduce
1. Take a Text Field component on the form.
2. Take a Data Grid component on the form.
3.  Take a Select component within Data Grid and bind some values in this components by calling an API or hard coded.
4. Take a Text Field component within Data Grid. Create a logic to make this field mandatory on the basis of value selection of Select component. Set property required of Text Box field in logic.
5. Run the form.

## Example
NA

**Comment by jhen1422** [comment]
@pardeep224 Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
Hello @pardeep224,

This issue has been resolved. You can use the latest version of formio.js to test 4.11.2.
