### ISSUE TITLE
[BUG] searchField equals issues

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#1823]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create a URL select component
{
  "id": "em4zbq",
  "key": "locationid",
  "data": {
    "url": "{$.environmentContext.referenceDataUrl}/v2/entities/location",
    "json": "",
    "custom": "",
    "values": [],
    "headers": [
      {
        "key": "",
        "value": ""
      }
    ],
    "resource": "",
    "disableLimit": true
  },
  "sort": "",
  "tags": [],
  "type": "select",
  "input": true,
  "label": "Location",
  "limit": 100,
  "logic": [],
  "filter": "",
  "hidden": false,
  "prefix": "",
  "suffix": "",
  "unique": false,
  "widget": "choicesjs",
  "dataSrc": "url",
  "dbIndex": false,
  "lockKey": true,
  "overlay": {
    "top": "",
    "left": "",
    "style": "",
    "width": "",
    "height": ""
  },
  "tooltip": "",
  "dataType": "auto",
  "disabled": false,
  "lazyLoad": false,
  "multiple": false,
  "redrawOn": "",
  "tabindex": "",
  "template": "<span>{{ item.name }}</span>",
  "validate": {
    "json": "",
    "custom": "",
    "select": false,
    "required": true,
    "customMessage": "",
    "customPrivate": false,
    "strictDateValidation": false
  },
  "autofocus": false,
  "encrypted": false,
  "hideLabel": false,
  "indexeddb": {},
  "minSearch": 0,
  "protected": false,
  "refreshOn": "",
  "tableView": true,
  "attributes": {},
  "errorLabel": "",
  "persistent": true,
  "properties": {
    "tooltipTitle": "What to do if your location isn't listed"
  },
  "validateOn": "change",
  "clearOnHide": true,
  "conditional": {
    "eq": "",
    "json": "",
    "show": "",
    "when": ""
  },
  "customClass": "",
  "description": "",
  "fuseOptions": {
    "include": "score",
    "threshold": 0.3
  },
  "placeholder": "",
  "searchField": "filter=name=eq.",
  "authenticate": false,
  "defaultValue": "",
  "disableLimit": false,
  "selectFields": "",
  "selectValues": "data",
  "alwaysEnabled": false,
  "customOptions": {},
  "labelPosition": "top",
  "readOnlyValue": false,
  "searchEnabled": true,
  "showCharCount": false,
  "showWordCount": false,
  "valueProperty": "id",
  "calculateValue": "",
  "clearOnRefresh": false,
  "searchThreshold": 0.3,
  "selectThreshold": 0.3,
  "customConditional": "",
  "allowMultipleMasks": false,
  "customDefaultValue": "",
  "allowCalculateOverride": false
}
2. Start using type ahead in the select box
3. The value being searched is being prefixed with an '=' which is not part of our filter spec.

## Expected behavior
  "searchField": "filter=name=eq.",

When I have the searchField se and then I enter the the letters "MET" I expect the following query to be sent:

$URL/v2/entities/location?filter=name=eq.MET

## Observed behavior
$URL/v2/entities/location?filter%3Dname%3Deq.=MET

Can we please remove the additional '=' sign at the end and also not encode the two '='s signs in the middle as '%3D' but instead pass as a proper \=\ sign.

Thanks

Mark

**Comment by randallknutson** [comment]
"filter=name=eq" is not a valid querystring. You will need to ensure that the value you are sending in the querystring is valid according to the HTML. "=" is a reserved character for a separator between the field and the value. You will need to change your API server to be compatible with the URI syntax for query strings. You can change it to something like:
```
$URL/v2/entities/location?filter_name_eq=MET
```
Set your filter query to "filter_name_eq"
