### ISSUE TITLE
Translation - how to enable returnEmptyString in i18n with formjs renderer

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#1825]
- Formio.js version: 4.2.12

Here's an example of the translation strings that we are trying to implement
Required fields are marked with an asterisk ( * )   --- English
Un astérisque ( * ) indique l'information nécessaire. -- French

What we've done is create an html element with this content:
```
{{ instance.t('Required fields are marked with an asterisk') }} ( * ) {{ instance.t('fr_required2') }}
```
And set fr_required2 translation string for english to empty.
When it's being rendered we got:
```
Required fields are marked with an asterisk ( * ) fr_required2
```

I believe it is by default the empty string false back to the field value.
After a bit of research I found that return empty string can be enabled in i18n but not sure if I can be enabled easily for formio renderer?

Thank you

**Comment by heather-formio** [comment]
https://formio.github.io/formio.js/app/examples/language.html
