### ISSUE TITLE
[BUG] Custom Url should pass all cookies from the client

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#1827]
When file upload configured with custom url it should send all cookies from the client to the server.
See https://github.com/formio/formio.js/blob/master/src/providers/storage/url.js

It already does it it when submitting to dropbox for example, why not for custom url.

**Comment by dolphinsd** [comment]
@randallknutson , happy to help, is there an example how add custom url provider in angular, we will create one and share

**Comment by randallknutson** [comment]
You can probably just modify the existing one and make the changes with regards to cookies. As long as it only adds them if they exist and doesn't crash without them it should be fine. That would make it backwards compatible and not a requirement to have cookies.

**Comment by dolphinsd** [comment]
lets close the issue, as one can create custom uploaders.
