### ISSUE TITLE
[BUG] The label of signature is disappear

### ISSUE THREAD

**Issue by jhihruei** [formio/formio.js#1828]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: formiojs@4.2.2
- Frontend framework: 
- Browser: Google Chrome
- Browser version: 77.0.3865.90

`gh-page` is on  80ba791
https://github.com/formio/formio.js/tree/80ba791c98f1f08f3b03faed50b2ca9346b9e05c

## Steps to Reproduce
1. Go to https://formio.github.io/formio.js/app/builder
2. Drop a signature component to form builder
3. Fill in "Label" field with "Label of Signature"
4. Select "Label Position" field to "Top"

## Expected behavior
Show a label "Label of Signature" at the top of signature pad.

## Observed behavior
Only show signature pad and footer label, no any label at the top of signature pad.

## Example
live example:  [GitHub Page](https://formio.github.io/formio.js/app/builder/) 
screenshot:
<img width="1376" alt="2019-10-08 " src="https://user-images.githubusercontent.com/6468997/66369050-4fecd780-e9cd-11e9-96c9-6f39856c25f7.png">

**Comment by randallknutson** [comment]
Our signature component has never had a visible label as part of the rendered component. We have the label option to be able to use it in places like edit grids and submission grids as column headers. It would make sense to allow this though as some people might want to display a label on the signature. You're the first person to request it. Is that something you could contribute or would you like to engage with our support to see about adding this ability?

**Comment by jhihruei** [comment]
Hi @randallknutson, thanks for you reply. 😃 

That is a bit weird for me, as there are label and label position fields in the signature config dialog. Because of these fields, I suppose there will be a label and we can decide to put it on top or bottom of the signature pad.
Actually I needs to add a label, but I already resolved by `setTemplate`. 
So I think that is up to Formio team want to add the label or not, or maybe we can remove the label position field if it is not actually work. 
I can help to 
- Implement the label of signature component 
- Remove the label position field from signature editForm
- Or both above
I think put the label at the bottom is still weird as there is already a footer label. 
So if you think to add a label is good, maybe we can keep it always on the top of component.

if you can tell me the expected behavior.

**Comment by aiwebb** [comment]
@jhihruei, we may end up modifying components to always support labels, and just update components like Signature to have Hide Label checked by default. We'll have to discuss it internally and figure out if there's a backwards-compatible way of doing that so it's not a breaking change.

**Comment by raefa** [comment]
I will add that the missing label also means that if you make the component required (in validation) that you don't see the asterisk and you don't see an error if you submit the form with it incomplete. It this becomes a priority and we patch we will submit details here (or do a pull request).

**Comment by heather-formio** [comment]
This is resolved and behaving as expected in 4.14.x. Closing thread. Thank you all for your contributions.
