### ISSUE TITLE
Remove default submit button in Builder

### ISSUE THREAD

**Issue by Narsciz** [formio/formio.js#1829]
Hi, 
We using your form builder/renderer, but in our case, we don't need a submit button in most of the form created.
Is it possible to dismiss the submit button appearing by default when no component have been added in the created form in the builder, like an option in the option object given?
Thanks

**Comment by randallknutson** [comment]
You can set options.noDefaultSubmitButton to not automatically add it to an empty form. You can see it in action here: https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L450

**Comment by Narsciz** [comment]
Thanx for the quick answer!
I saw it has been added one week ago, so i will need to update my formio version but it is exactly what i needded.
