### ISSUE TITLE
Translations not loading for Select elements

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#184]
I'm trying to use the i18n translations to enable multiple languages on my forms.
All the components change the language correctly except for the Select and Resource components, that all the labels remain the same.

Is there something particular that we have to do to translate these components?

**Comment by cabrerabywaters** [comment]
Dear @travist ,
Any idea on this? than you.

Best Regards,
Ignacio

**Comment by cabrerabywaters** [comment]
Hello @travist, @douglaselee 

Sorry to keep pushing with this one but its quite important for apps with multilanguage to be able to translate dropdown items.

Any update on this?

Regards!

**Comment by douglaselee** [comment]
Hi @cabrerabywaters,

This would be a good thing and I've mentioned it before in https://github.com/formio/formio/pull/422.  Will try to look at it when time allows but can't predict when that will be.

**Comment by cabrerabywaters** [comment]
@douglaselee ,

What I'm doing now is that I have a "Translations" resource where I manage all the App's translations, then I load those into the FormioJs i18n object. It works perfectly for 90% of the elements.

Now I need to build this functionality for the Select elements of the App that I'm working with. I was thinking about just doing some "brute force" translation of the select elements after rendering, from the i18n object that translates all the rest of the forms, but as Select2 already has multilanguage functionality makes sense to just add it in Formiojs before rendering.

I'm not familiar with the Formiojs library, but if you could point me in the right direction I could try to do it directly on the library an not on my code.

**Comment by douglaselee** [comment]
Hi @cabrerabywaters,

Maybe take a look at...
```
  /**
   * Translate a text using the i18n system.
   *
   * @param {string} text - The i18n identifier.
   * @param {Object} params - The i18n parameters to use for translation.
   */
  t(text, params) {
    params = params || {};
    params.component = this.component;
    params.nsSeparator = '::';
    params.keySeparator = '.|.';
    params.pluralSeparator = '._.';
    params.contextSeparator = '._.';
    return i18next.t(text, params);
  }

```
...in `formiojs\src\components\base\Base.js` and see how it's used in the repository.  Good luck.

**Comment by cabrerabywaters** [comment]
@douglaselee,
What do you think about doing this? https://github.com/formio/formio.js/pull/262

Don't know if its the best approach but works fine for me.

**Comment by douglaselee** [comment]
Hi @cabrerabywaters,

Looks good.  Might be more efficient to consolidate 2 instances of `this.itemTemplate(item).replace(/<\/?[^>]+(>|$)/g, "")` into a single variable but no big deal.

Thanks for the assist!

**Comment by cabrerabywaters** [comment]
Hello @douglaselee,

Oh! sure! I just pushed the fix for that.
Hope it helps!

**Comment by douglaselee** [comment]
Thanks again @cabrerabywaters, this will definitely help!
