### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#1844]
we are working with latest version. 

when we provide custom file uploader, it does not call deleteFile, it is only enable for url uploader. Please check for deleteFile function in provider instead.

See 
  var fileInfo = _this4.dataValue[index];

          if (fileInfo && _this4.component.storage === 'url') {
            var _fileService = _this4.fileService;

            if (_fileService && typeof _fileService.deleteFile === 'function') {
              _fileService.deleteFile(fileInfo);
            } else {
              _this4.options.formio.makeRequest('', fileInfo.url, 'delete');
            }
          }

**Comment by aminmc** [comment]
Strange. It gets called when you remove the file from the file component in preview mode. This has been working fine for me.

**Comment by aminmc** [comment]
Here are a few screen shots showing the delete file being called:

Clicking on the 'x' button:
![Screenshot 2019-10-10 at 07 27 24](https://user-images.githubusercontent.com/290639/66544338-c43f8c00-eb2f-11e9-8b3a-9c0ca78173dc.png)

Debugging my custom method:

![Screenshot 2019-10-10 at 07 27 45](https://user-images.githubusercontent.com/290639/66544357-d1f51180-eb2f-11e9-8808-d30a255dedf0.png)

**Comment by dolphinsd** [comment]
@aminmc - which file provider? bug is for non url  provider, for example s3!!! or others, what you are showing is FOR "url" provider

**Comment by aminmc** [comment]
Ok.my answer is related to url provider. You could look at creating a PR for adding those to the other providers

**Comment by dolphinsd** [comment]
@aminmc , not sure what you mean about "creating a PR", the code clearly allows to delete only 'url' provider files and not 3rd party providers.
