### ISSUE TITLE
[BUG] Nested form with custom conditional logic does not send email from nested form data

### ISSUE THREAD

**Issue by lailapfit** [formio/formio.js#1853]
## Environment
Please provide as many details as you can:
Using the latest version of Form.io

## Steps to Reproduce
1.  Create two forms: 
            1. Contact (first name, last name, address, etc) 
            2. Comment (comment, response). Nest Contact form in the Comment form.
2. Add two email actions: 
            1. Standard email action 
            2. Email action with custom conditional Javascript. I have a field in the Comment form called "Custom Type" and add the conditional statement: 
```js
execute = (data.commentType == "public" || data.commentType == "Public")
```
3. Submit the form with entering the "Custom Type" field with "public".

## Expected behavior
1. Receive two different emails when a form is submitted with all the data from the Contact and Comment form. 

## Observed behavior
1. Two emails were received. One of the email without the custom conditional logic was received as expected, but the email with the custom logic did not display the nested form data.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Email result from the email action without conditional statement:
![Screenshot2](https://user-images.githubusercontent.com/52266239/66597906-e0fab480-eb6d-11e9-90ab-70beea66bce2.png)

Email result from the email action with conditional statement:
![Screenshot3](https://user-images.githubusercontent.com/52266239/66597907-e0fab480-eb6d-11e9-9f4b-239431ab5520.png)

Email action with the conditional statement:
![Screenshot4](https://user-images.githubusercontent.com/52266239/66597908-e0fab480-eb6d-11e9-9e01-a29bfd0e1962.png)

Email action without the conditional statement:
![Screenshot5](https://user-images.githubusercontent.com/52266239/66597909-e0fab480-eb6d-11e9-8c3f-77bf41b1bf2f.png)

**Comment by lailapfit** [comment]
** update: the observed behavior is the result of when the nested form is saved as a reference.

**Comment by wag110894** [comment]
@lailapfit 
Can you try taking out the conditional logic and edit the 2nd email action.
add under Action Conditions (optional)
Select the conditional field: Custom Type
Select comparison: Equals
Enter Value: public

Please let me know if this works?

Thanks

**Comment by lailapfit** [comment]
@wag110894 
Hello, I just tried your recommendation to replace the conditional logic by adding it to the Action Conditions (optional), however, the email still does not show the data from the nested form. If the data is not saved as a reference, it works just fine, which is the solution I will use.

**Comment by wag110894** [comment]
Glad to hear that you figured it out.
