### ISSUE TITLE
[BUG] SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data

### ISSUE THREAD

**Issue by daspilker** [formio/formio.js#1857]
## Environment
We are using angular-formio 4.2.5 in an Angular 8 app.

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 4.3.2
- Formio.js version: 4.3.2
- Frontend framework: Angular
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Create a form with a file component, set storage type to 'url'
2. Embed form in Angular app
3. Try to upload file

## Expected behavior

File is uploaded to server.

## Observed behavior

Error message "SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data" is shown before file is being uploaded. There is no network traffic and nothing is printed to the browser console.

**Comment by daspilker** [comment]
I think the problem is that the component's options are set to `{}`:
https://github.com/formio/formio.js/blob/v4.3.2/src/components/file/File.js#L514

Since `{}` evaluates to true, `JSON.parse` is called with an empty object which results in the error:
https://github.com/formio/formio.js/blob/v4.3.2/src/providers/storage/url.js#L66-L67

**Comment by randallknutson** [comment]
Yeah, we shouldn't be trying to parse an object. That doesn't make sense. There is probably some legacy reason for this. We should probably change it to something like:
```
      if (options) {
        let parsedOptions = options;
        if (typeof options === 'string') {
          parsedOptions = JSON.parse(options);
        }
        for (const prop in parsedOptions) {
          xhr[prop] = parsedOptions[prop];
        }
      }
```

**Comment by aiwebb** [comment]
Thanks @daspilker for linking straight to specific issue in code - very helpful!

**Comment by Steiner-254** [comment]
interesting
