### ISSUE TITLE
Question ID and Label

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#1860]
Hi

We have a form where we use a select box that gets data from a remote url. The data value is ID bit the display label is Name.

All is ok for the first part and we correctly display the drop down. However at the end of the multi page wizard we are doing a check your answers style thing. Here I need to display the label again back to the user. If I use data.apiname as normal then I get the ID. I need the ID as that is what we require to save. As such i am unsure how to display the label the user selected rather than the utf8 ID for the confirmation.

Any ideas?

Thanks

Mark

**Comment by aiwebb** [comment]
@pixie79, you can do this in our 4.x portal (next.form.io) via the `instance` property.

Here's some example form JSON:
https://gonsjuvqvtqdnwp.form.io/wizardlabelexample

And a live example:
https://pro.formview.io/#/gonsjuvqvtqdnwp/wizardlabelexample

And a quick look at some example code that uses the ID of the selected option to grab the associated label:
```js
var options = instance.root.flattenComponents().exampleSelect.downloadedResources;

if (!options) {
  return null;
}

var selectedOption = options.find(opt => opt.id === data.exampleSelect);

if (!selectedOption) {
  return null;
}

value = selectedOption.name;
```

**Comment by aminmc** [comment]
Alternatively you could just leave value property blank and then formio will store the object and then you can do value = data.selectBox.label
