### ISSUE TITLE
Restrict Custom Validation to Change on Specific Component

### ISSUE THREAD

**Issue by du8die** [formio/formio.js#1862]
Scenario: 
  A select box with a list of values. 
  A check box.
  When a user chooses a value from the select box, a custom validation routine runs and determines whether or not the checkbox should be checked. 
  User should be able to override the checkbox value.

Problem:
  When the user checks the checkbox, the "change" event is being fired, causing the select box validation to happen, and that resets the checkbox value back to the "default" value.

How do I inform the select box validation script to only calculate the check box value if the select box value changes. Unfortunately, it doesn't appear that we have access to the change event. (http://formio.github.io/formio.js/app/examples/externalload.html - unless we do have access to event.changed.component.key from within the custom validation environment- and it's not documented? That would be ideal.

Thanks for any insight you can provide.

**Comment by wag110894** [comment]
Will you please provide a  JSFiddle of this issue?
