### ISSUE TITLE
Override schema properties of Form component

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1863]
Hello,

Currently a form component has a default value of 'Save reference' set to true. I would like to override this and make it false by default.  I attempted the following:

```js
import Base from 'formiojs/components/_classes/component/Component';
import FormComponent from 'formiojs/components/form/Form';
import Components from 'formiojs/components/Components';


export class SubFormComponent extends FormComponent {

    static schema(...extend) {
        return Base.schema({
            label: 'Form',
            type: 'form',
            key: 'form',
            src: '',
            reference: false,
            form: '',
            path: '',
        }, ...extend);
    }

    static get builderInfo() {
        return {
            title: 'Nested Form',
            icon: 'wpforms',
            group: 'premium',
            documentation: 'http://help.form.io/userguide/#form',
            weight: 110,
            schema: SubFormComponent.schema()
        };
    }
}

Components.addComponent('form', SubFormComponent);

```
However it's not being applied.  Is there something else I need to do?

Thanks

**Comment by jhihruei** [comment]
Hi @aminmc, 
I have copied your code to test on localhost, and it can work.
Could you help to provide more infomation?
Or try to log after set component to see if it has been set but not applied to the page you would like to use?
```
addComponent('form', SubFormComponent);
console.log(Components.components);
```

**Comment by aminmc** [comment]
hi @jhihruei the console.log output shows my component  but isn't being applied on the page.

**Comment by heather-formio** [comment]
Closing this thread as it is stale. Please feel free to reopen as needed. Thank you!
