### ISSUE TITLE
[FEATURE]  default file uplod provider

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#1864]
Is there a way to set a default file upload provider. If customer setup just s3 provider or dropbox, there is not point of going and configuring it everytime component is dropped.

**Comment by randallknutson** [comment]
This is a good suggestion. The tricky part is that we would either need to set up a call to the server to see which ones are enabled which would be an additional request to the server or provide a way of sending a list of enabled providers in the options object. This could already be accomplished by sending builder options to the form builder and modifying the options in the select component.

**Comment by dolphinsd** [comment]
@randallknutson , can it be one of the configuration options on the builder?

**Comment by randallknutson** [comment]
Yes. We could definitely use the options to override this setting. Is this something you could do a PR for?
