### ISSUE TITLE
Difference between input and value in Custom Validation ?

### ISSUE THREAD

**Issue by fabien-feat** [formio/formio.js#1867]
Hello !

In builder's Custom Validation field (Validation tab), what difference between input and value ?
If I use value I have this error in renderer : 
`An error occured within custom function for prenom ReferenceError: value is not defined`

It was ok in v3.x

Thanks

**Comment by travist** [comment]
It may be possible that this fixes your problem?  https://github.com/formio/formio.js/pull/1869

**Comment by fabien-feat** [comment]
Hum... No, this is not a problem with `Custom value` : 
Example : 
![image](https://user-images.githubusercontent.com/45355921/66760496-84b3cf80-eea2-11e9-9f68-c2824b9cbeaf.png)

**Comment by christophermurphy2-allscripts** [comment]
It's as the descriptions say.
"input" is the value that is being typed or selected by the user.
"value" is what the component actually has stored at that moment. It doesn't have to match input, but in many cases it might. If a value has not been set yet, this will be undefined or a default value.

**Comment by fabien-feat** [comment]
Thanks for the details, but the value is never set... even if I fill my field with text...

The error `An error occured within custom function for prenom ReferenceError: value is not defined` is shown in the javascript console.

I will study the formiojs code in the day.

**Comment by Sefriol** [comment]
This is especially problematic with Select component since it does not respect `required`-attribute when `multiple values` is checked. This could be circumvented if you could observe the `value` in custom validation, but error mentioned by @fabien-feat appears.

**Comment by randallknutson** [comment]
The input is used for searching and not stored. When the user enters an input it will search through the options and allow them to select a value. Until they select a value it won't be validated.

**Comment by Sefriol** [comment]
Value is still never set and will raise an error if you reference it in Custom Validation block.

**Comment by randallknutson** [comment]
I'm actually wrong about this. You should write your validations for "input" so:
valid = value === 'a' ? true : 'must be a';

**Comment by gs11** [comment]
Referencing `value` will still always yield an error
```
console.log(value);
valid = true;
```
