### ISSUE TITLE
Required Select Box Component Does Not Display Field Error in JS Renderer

### ISSUE THREAD

**Issue by ajcolub11** [formio/formio.js#187]
When a required select box is added to a form 
And form is submitted without selecting a select box option
Then a field error does not display on form

The component seems to be missing "p class="help-block">{{ component.label }} is required /p"

example of our front-end:
![selectboxnofielderror](https://user-images.githubusercontent.com/29924975/30744827-d30b9fc8-9f71-11e7-99d3-62d2ce88d87d.PNG)

form.io preview:
![selectboxfielderrorformio](https://user-images.githubusercontent.com/29924975/30744840-e51ccf70-9f71-11e7-81f2-71a82ddf95fa.PNG)

**Comment by travist** [comment]
Fix will be included in next release.

**Comment by travist** [comment]
Fixed with 2.17.6
