### ISSUE TITLE
Convert submission data of  date format to dd-MM-yyyy

### ISSUE THREAD

**Issue by vishaldenzil** [formio/formio.js#1871]
If i want the submission data in other format ... 
For eg. the date format is 2019-10-09T00:00:00+05:30 .. I need the format in 09-10-2019 ..
How i can achieve using the date//time component .. Or any other way?

**Comment by wag110894** [comment]
You can change the format using the Format setting in date/time component to the format the date/time to what you would like.

**Comment by vishaldenzil** [comment]
Am getting the format settings while displaying .. But the submission still the same ..2019-10-09T00:00:00+05:30 .. After submitting the data i need date should store the  09-10-2019  like this

**Comment by wag110894** [comment]
What version of the formio.js are you using?

**Comment by vishaldenzil** [comment]
form io.js 3.16.1

**Comment by indioLatino** [comment]
Any news on this issue?

**Comment by wag110894** [comment]
This fix is currently available on our 4.12.1-rc.7 build of formio.js, which is currently a release candidate. We can let you know once 4.12.1 has a stable release so you can pull this in if you would like.

**Comment by gs11** [comment]
Using 4.12.1 but the issue persists?
Format configured as `yyyy-MM-dd` which looks ok in form but it's still serialized as `2020-12-01T00:00:00+01:00` in the submission.

**Comment by wag110894** [comment]
What version of the server are you using?

**Comment by gs11** [comment]
`Application: 7.1.17-rc.29, Renderer: 4.12.2-rc.5` @wag110894

**Comment by wag110894** [comment]
@gs11 Thank you for providing the app as well the formio.js that you are using. I am using the same versions but using server 7.0.0-rc.56.

**Comment by gs11** [comment]
Indeed, those versions seems to be included in the docker image we use - `formio/formio-enterprise:7.0.0-rc.56`

**Comment by wag110894** [comment]
Can you provide a video of the issue taking place as well as a form?

**Comment by heather-formio** [comment]
Closing as this is stale. Please reopen as needed. Thank you!
