### ISSUE TITLE
[BUG] Radio Button ignores clearOnHide

### ISSUE THREAD

**Issue by unrealsolver** [formio/formio.js#1877]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [X] Local deployment

- Formio.js version: 4.3.x
- Frontend framework: React
- Browser: FF
- Browser version: 69

## Steps to Reproduce
1. Create a radio, make it visible by some condition/switch.
2. Radio should not be visible by default
3. Assign data / submission to the radio (still not visible)
4. Switch visibility of the radio
5, Radio button get visible and ...

## Expected behavior
the value is set according to the assigned data / submission

## Observed behavior
the value is empty

## More info
1. `clearOnHide` does not affect behavior
2. Making radio visible by default helps (unless you toggle visibility)
3. Other input types (`textfield`, `textarea`) work correctly.
4. The newest master dos not have such problem though

**Comment by jhen1422** [comment]
@unrealsolver Thank you for the report. Can you try this use case on version 4.3.5?
If the issue still persists could you please provide a jsfiddle showcasing the problem?

Thank you.

**Comment by unrealsolver** [comment]
The latest v4.3.5 does not have this issue.
Code for testing:
```js
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
  <link rel='stylesheet' href='./formio.form.css'>
  <script src="./formio.form.js"></script>
  <script>
window.onload = function() {
  Formio.icons = 'fontawesome';
  Formio.createForm(document.getElementById('formio'), {
    components: [
      {
        type: 'radio',
        input: true,
        key: 'sw',
        label: 'SW',
        values: [
          { value: 'y', label: 'Yes', shortcut: '', },
          { value: 'n', label: 'No', shortcut: '', },
        ],
      },
      {
        type: 'radio',
        input: true,
        key: 'v1',
        label: 'V1',
        values: [
          { value: '1', label: 'One', shortcut: '', },
          { value: '2', label: 'Two', shortcut: '', },
        ],
        conditional: {
          show: true,
          when: 'sw',
          eq: 'y',
        }
      },
      {
        type: 'textfield',
        input: true,
        key: 'v2',
        label: 'V2',
        conditional: {
          show: true,
          when: 'sw',
          eq: 'y',
        }
      },
    ]
  }).then(function(form) {
    // Provide a default submission.
    form.submission = {
      data: {
        sw: 'n',
        v2: 'test',
        v1: '1',
      }
    }
  })
}
</script>
</head>

<body>
  <div id="formio"></div>
</body>

```
