### ISSUE TITLE
[BUG] Datagrid cannot read property '0' of undefined

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1884]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.3.5
- Frontend framework: react-formic
- Browser:
- Browser version:

Create a simple form with a panel and a data grid inside that panel. Add an input component to the data grid and save the form.

When editing a data grid the following exception is displayed in console logs:

![Screenshot 2019-10-16 at 12 58 47](https://user-images.githubusercontent.com/290639/66917213-df6d3880-f014-11e9-95b1-0719fd1b2bce.png)

**Comment by jhen1422** [comment]
@aminmc Could you please provide a jsfiddle showing the issue? We are unable to replicate on our end using 4.3.5

**Comment by aminmc** [comment]
@jhen1422 hmmm...can't seem to reproduce it myself :(
Closing this issue.

**Comment by antonyagustine** [comment]
I'm also facing the same issue from _**V4.3.2 to V4.6.0**_
![datagrid_issue](https://user-images.githubusercontent.com/39733569/67657342-770b4900-f97c-11e9-9d72-ff33ed5fb816.png)
