### ISSUE TITLE
[BUG]  Data not available in CSV for select component

### ISSUE THREAD

**Issue by handlerne** [formio/formio.js#1888]
## Environment
Please provide as many details as you can:
Formio.js version: 4.2.12

We have the On Premise Enterprise environment,
{
version: "6.7.9",
schema: "3.3.3"
}

**Testing environment**
Browser: Chrome v70.0.3538.67
Platform: Desktop (Windows 10)

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce

1. Go to a form with a select component.
2. Choose a value in the select component.
3. Submit the form.
4. Go to the "Data" tab in the Form.IO publishing interface for the form.
5. Click on "Export CSV" button.
6. Observe value for the select component.

## Expected behavior
The value entered for the form selected component is reported correctly in the CSV file.
![image](https://user-images.githubusercontent.com/44500141/66952574-e2732380-f02a-11e9-9969-98c85cf54d49.png)

## Observed behavior
The value entered for the form selected component is missing in the CSV file.
![image](https://user-images.githubusercontent.com/44500141/66952732-2fef9080-f02b-11e9-9562-7b6b8ecc8d79.png)

Note: When I change 010/1020 to '0 to 10' etc then it starts working.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Could you provide us your Project JSON so we can try to replicate this on our end?

Thanks.

**Comment by handlerne** [comment]
[nelirestaurantform.txt](https://github.com/formio/formio.js/files/3736217/nelirestaurantform.txt)

**Comment by wag110894** [comment]
This is just your data. Could you provide the form that you are using so we can replicate this on our end?

**Comment by handlerne** [comment]
Let me know if this works for you. I had to zip it as it seems GitHub does not allow json files to be uploaded. Thank you!
[Files.zip](https://github.com/formio/formio.js/files/3739925/Files.zip)

**Comment by phucduong86** [comment]
Here's our component:
```
{
autofocus: false,
input: true,
tableView: true,
label: "What is your age?",
key: "whatisyourage",
placeholder: "Please select a value from the list below",
data: {
values: [
{
value: "010",
label: "0-10"
},
{
value: "1120",
label: "11-20"
},
{
value: "2130",
label: "21-30"
},
{
value: "3140",
label: "31-40"
},
{
value: "4150",
label: "41-50"
},
{
value: "50",
label: "50+"
}
],
json: "",
url: "",
resource: "",
custom: ""
},
```


Our custom Html template
```
<div ref="component" class="form-group has-feedback formio-component formio-component-select formio-component-whatisyourage  required form-group" id="e726g5i">
      
      
  
    
    <label for="data[whatisyourage]" class="col-form-label  field-required">
      What is your age?
      
        <i class="fa fa-question-circle text-muted" ref="tooltip"></i>
      
    </label>
    



<select id="data[whatisyourage]" required="" ref="selectContainer" aria-describedby="data[whatisyourage]-message" class="custom-select"><option placeholder="true" value="" selected="selected">
  Please select a value from the list below
</option><option value="'010'">
  <span>0-10</span>
</option><option value="'1120'">
  <span>11-20</span>
</option><option value="2130">
  <span>21-30</span>
</option><option value="3140">
  <span>31-40</span>
</option><option value="4150">
  <span>41-50</span>
</option><option value="50">
  <span>50+</span>
</option></select>



  <div class="form-text text-muted">Age description field</div>


        
          <div class="formio-errors invalid-feedback" id="data[whatisyourage]-message" ref="messageContainer"></div>
        
      
    </div>
```

When I use the default template (formiojs lib) the data is submitted as string (```whatisyourage
:1120```) but with our template it was submitted as number ```whatisyourage:"1120"```
It lead me to believe these things are happening:
- saveSubmission function performs a type check and convert the string values into number when it submits
- The Datagrid component read both 1020 and "1020" value
- The Export CSV function does not export the number value from Select Component specifically

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen as needed. Thank you!
