### ISSUE TITLE
[BUG] Translations: Cannot create new key with same first word as existing key

### ISSUE THREAD

**Issue by handlerne** [formio/formio.js#1895]
## Environment
Please provide as many details as you can:
Formio.js version: 4.2.12

We have the On Premise Enterprise environment,
{
version: "6.7.9",
schema: "3.3.3"
}

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

I am unable to add a key that starts with the same word as an existing key. 

## Steps to Reproduce
1. Click on the gear icon on an existing form.
2. Click the Add Value button and enter in a key and value. (i.e. fr:Chicken / Poulet)
3. Click the Add Value button and enter in a key that starts with the same text as entered in Step 2. (i.e. Chicken tooltip)
4. Observe the page behaviour

## Expected behavior
The new key is entered successfully (i.e. Chicken tooltip)

## Observed behavior
When typing the new key, I am taken to the value field for the existing key as soon as I enter the same first word. The existing value is wiped out.
![image](https://user-images.githubusercontent.com/44500141/66422900-8e3bc400-e9d8-11e9-827c-138ab0602922.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Thanks for reaching out!

This issue will be resolved in the next version of our 4x Portal. 

We will let you know when this is released.

Thanks.

**Comment by phucduong86** [comment]
@wag110894 
This issue has not been resolved on our v4 portal: **Application: 7.0.8, Renderer: 4.9.27-rc.4.**
Can you please let us know which version the fix for this this issue was addressed?
Thank you

**Comment by wag110894** [comment]
@phucduong86 I am seeing that this is back on our latest version as well. We have created a ticket (FJS-1161) and have added this to our backlog.
As you are aware, we do have a process to expedite and you are welcome to create a Pull Request if you are interested.

We will let you know once this has been resolved.

**Comment by jhen1422** [comment]
Our dev team confirmed this issue was resolved in 
Application 7.1.17-rc.13, Renderer: 4.12.1-rc.8
