### ISSUE TITLE
[BUG] Textarea does not preserve newlines in readOnly mode.

### ISSUE THREAD

**Issue by motss** [formio/formio.js#1904]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.5.3
- Frontend framework: React
- Browser: Firefox
- Browser version: 69.0.3

## Steps to Reproduce
1. Go to http://formio.github.io/formio.js/app/examples/custombuilder.html 's `Result` section.
1. Drag and drop a text area component and enter some texts with newlines in the `Preview` section.
1. In the `Display` tab, click to check the `Disabled` checkbox.
1. Content in the text area becomes one-liner and does not respect any newlines.

## Expected behavior

Newlines should be preserved at the very least in text area component when it is disabled or in readOnly mode.

## Observed behavior

Texts with newlines in a text area component gets normalized to become one-liner when the component is disabled or in readOnly mode.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

The image below shows the content in the text area component contains some texts with newlines.
![Texts with newlines in edit mode](https://user-images.githubusercontent.com/10607759/67062657-89280300-f196-11e9-99aa-ab1af68ef890.png)

The image below shows a one-liner text when the text area component is disabled or in readOnly mode.
![Newlines are not preserved in readOnly mode](https://user-images.githubusercontent.com/10607759/67062655-888f6c80-f196-11e9-8682-d81d62a04716.png)

_Do not think code snippet is required to replicate the issue here given the details provided here should suffice._

**Comment by thanhvietnguyen255** [comment]
Hi @motss,
Could you please give me a solution to fix this?

Thanks

**Comment by thanhvietnguyen255** [comment]
Don't worry about that. I fix by this way set CSS white-space: pre-wrap;
