### ISSUE TITLE
[BUG] Radio and conditional logic

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1907]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ ] Local deployment
    - Version:  
- Formio.js version:4.4.1
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Create a form 
2. Add radio with 2 options value true and false
3. Add a panel component
4. Update panel to display when radio option true

## Expected behavior
If I select true the panel should appear
If I then select false the panel should disappear
## Observed behavior
Panel does not disappear 

See Jfiddle
## Example
https://jsfiddle.net/7021xe6h/2/

**Comment by jhen1422** [comment]
@aminmc Thanks for the report and providing the jsfiddle. We have added this item to our 4x backlog and will prioritize this next Monday during our planning meeting.

**Comment by jhen1422** [comment]
@aminmc Looking at your jsfiddle this morning, the issue seems to have been resolved. Can you confirm on your end as well?

**Comment by aminmc** [comment]
@jhen1422 I would like to reopen this. If you use the jfiddle again you'll notice after selecting one option you cannot select the next option again. For example:

1. Click display
2. Click hide
3. Click display again...unable to do so

**Comment by jhen1422** [comment]
Resolved.
