### ISSUE TITLE
[BUG] Extra newline and whitespaces always prefix in each textarea's content

### ISSUE THREAD

**Issue by motss** [formio/formio.js#1908]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.5.3
- Frontend framework: -
- Browser: Firefox
- Browser version: 69.0.3

## Steps to Reproduce
1. Go to http://formio.github.io/formio.js/app/examples/custombuilder.html, drag and drop a text area component.
2. Input some texts with newlines.
3. Disable the text area component and inspect the disabled element with DevTools. `console.log` the `textContent`.

## Expected behavior

No extra newline and whitespaces should prefix in each text area's content.

## Observed behavior

Text area component should render with the value input by the user.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

The following screenshots shows that `.textContent` of a disabled text area component contains extra newline and whitespaces before the actual content value.
<img width="1221" alt="Disabled text area component renders with extra newline and whitespaces" src="https://user-images.githubusercontent.com/10607759/67082569-f609c000-f1cb-11e9-8e95-6a5ab77d5de2.png">

_No code snippet required_

**Comment by jhen1422** [comment]
@motss Thank you for the report.
 We were able to replicate this issue on our end and have added a ticket to our 4x backlog. We will prioritize this during our planning session next week.
If you need this issue expedited, please feel free to contact support@form.io. Additionally, we welcome pull requests in this library for contributed fixes.
Thanks!

**Comment by wag110894** [comment]
Hello @motss,

After investigating this, we believe that this is a CSS issue and not an issue on our side.

**Comment by motss** [comment]
Sorry but when you mean it's a CSS issue what does it exactly refers to? Could you please clarify on what kind of CSS issue is affecting formio before marking this issue as resolved?

**Comment by wag110894** [comment]
Allow me to clarify.

After looking into this issue, we believe that this is a CSS issue located in your styles. 

I hope that this helps clarify where this is. 

Thank you.

**Comment by motss** [comment]
What do you mean by my styles? I'm testing it with formio's own example demo and I was able to reproduce the exact same problem. I don't see myself sharing any of my own code or my styles in this thread. I'm pretty surprised on that.

**Comment by travist** [comment]
We may have thought you were complaining about the visuals of how the "disabled" text looks, which that would be fixed when you embed the form in your own application and apply your own styles. Your end users would not be using our Example application to use your forms, so that is the source of that comment.

About this issue, though, I am not actually seeing any newlines get injected before or after the text... I just walked through what you just did and it seems to work fine for me.

https://monosnap.com/file/96dvgueIM505czRCGnL7ynuuuIZdGH
