### ISSUE TITLE
[BUG] onChange is not fired when a pre-set submission is cleared from select component

### ISSUE THREAD

**Issue by gith-amitm7** [formio/formio.js#1910]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.4.1
- Frontend framework: BS 4
- Browser: Chrome

## Steps to Reproduce
1. Have a select component, whose options are fetched using URL
2. set the submission of the select component programmatically using 
```js
form.submission = {
    data: {
      <selectKey>: <optionValue>
    }
  };
```
3. Clear the value manually.

## Expected behavior
Onchange must be fired

## Observed behavior
It isn't.

**Comment by jhen1422** [comment]
@gith-amitm7 
Hi Gith,

Could you provide a jsfiddle showing the problem? Thanks!

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen at any time if still relevant. Thank you for your contributions and discussion.
