### ISSUE TITLE
Error in v-on handler: "TypeError: Converting circular structure to JSON [BUG] 

### ISSUE THREAD

**Issue by nyirongojr** [formio/formio.js#1911]
Have anyone come across this console error. Its showing up in my console when i try to enter some data in any text field.

![image](https://user-images.githubusercontent.com/30801699/67097647-d4eca380-f1ba-11e9-9c30-3c268c1a9601.png)

**FYI:** I am using vuejs and typescript

**Comment by randallknutson** [comment]
We haven't seen this before. Based on the error it appears that something is being added to the options that includes the options which causes an infinite loop in the json. Can you show how you are embedding the form and any options object you are passing in?

**Comment by nyirongojr** [comment]
I am not passing any options object, i am just retrieving the form schema and displaying the form. when i try to add any data on to the fields thats when i am getting that error in the console.
Here is my code how i am embedding the form. 
![image](https://user-images.githubusercontent.com/30801699/67186993-8a04a300-f3e9-11e9-9b34-fdd66fdc4072.png)
