### ISSUE TITLE
[BUG] Empty HTML element component column in the data view

### ISSUE THREAD

**Issue by handlerne** [formio/formio.js#1913]
Similar to #1888, data is not available for the HTML element component in the data view.

## Environment
Please provide as many details as you can:

Formio.js version: 4.2.12

We have the On Premise Enterprise environment,
{
version: "6.7.9",
schema: "3.3.3"
}

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Go to a form with an HTML element component.
2. Submit the form.
3. Go to the "Data" tab in the Form.IO publishing interface for the form.
4. Observe value for the HTML element component.

## Expected behavior

Either:
1) the HTML element component value should be in data view, or 
2) the HTML element component should be removed from the data view

## Observed behavior
There is no value in the data view for the HTML element component.
![image](https://user-images.githubusercontent.com/44500141/67104256-9d6b0080-f194-11e9-8b33-52077e5febda.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by randallknutson** [comment]
We probably shouldn't have the hidden components be in table views by default. I also see there isn't an option to uncheck tableView. This probably needs to be fixed.

**Comment by jhen1422** [comment]
@handlerne We actually do offer the option to remove the HTML from data view by unchecking the 'Table View' as shown in this screenshot. This setting should be available to you in the builder. Let us know if that resolves your issue

**Comment by phucduong86** [comment]
Hi,

We don't have the option in our portal version 6.7.9.
Is it available in the newer release?
![image](https://user-images.githubusercontent.com/21692768/67418124-397f7800-f598-11e9-9c60-657612a95614.png)

**Comment by jhen1422** [comment]
@phucduong86 
You can change the setting on our next portal found at the URL below
https://next.form.io/#/

**Comment by phucduong86** [comment]
Hi @jhen1422 ,

Which official version of the Portal would have this setting? I've updated to latest stable (6.7.14) and still don't see it.
We have On Prem setup and can't use the next portal.
