### ISSUE TITLE
How to make a column disappear when its contents are made invisible / hidden

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1915]
Hello!

I have a columns component, with column widths 3, 3, and 6. The first column contains a component which is conditionally shown or hidden (in my current case via the simple mechanism "_This component should Display:_ True _When the form component:_ ... _Has the value:_ true", which always evaluates to the same value throughout the form display.)

Is it possible to make the first column "disappear" when that component in the first column is not shown, so that the second column together with the following columns move leftwards by 3 units?

I tried checking both 
- Auto adjust columns ("Will automatically adjust columns based on if nested components are hidden."), and
- Hide Column when Children Hidden ("Check this if you would like to hide any column when the children within that column are also hidden")

but it does not appear to have any effect. I am using formiojs 4.2 with react-formio.

Is the desired behaviour I described above supposed to be possible at all? If so, how?
If not, what is the purpose of the two checkboxes mentioned above?
Do the push and pull values (currently 0) play a role here?

Thanks!

**Comment by wag110894** [comment]
Thanks for reaching out!

This is a known issue in our 4x renderer and is currently in our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.

**Comment by dev-thinks** [comment]
This is still an open issue in current version. trying to overcome with a workaround. let me know please if anyone knows any insights.

Appreciated.

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen at any time if still relevant. Thank you for your contributions and discussion.
