### ISSUE TITLE
[BUG] save/load roundtrip broken for Select Filter-Query containing double-quote characters

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1917]
## Environment
- Hosting type: 
    - [x] Form.io
- Formio.js: 4.5.0, with react-formio
- Browser: Firefox 70.0

## Example on next.form.io:
  - see [this form](https://api.form.io/project/5d1c9ef99cf71913daa0e494/form/5db498531d29d2a19258ed5d) at `component[0].filter`

## Steps to Reproduce
1. Create a form with a Select component
2. In the Data tab, select `Resource` as Data Source Type, and select a Resource, e.g. `Admin`
3. Enter `data.foo="bar"` as Filter Query
4. Save the component and the form.
5. Edit the form again, open the Select component, go to the Data tab

## Expected behavior
- Filter Query is shown as previously entered

## Observed behavior
- The part after `=` is gone.
![selectFilterQueryCutoff](https://user-images.githubusercontent.com/46748541/67624822-32759580-f836-11e9-8e7d-572b19f08b42.png)

Note that the data is stored correctly as `"filter": "data.foo=\"bar\""` .

**Comment by franke-mc** [comment]
@jhen1422 : Could you acknowledge this one as well, please?

**Comment by jhen1422** [comment]
@franke-mc 
Thanks I've added this issue to our backlog list as well.

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/2088
