### ISSUE TITLE
[Question]: Can we add component/components in child of given DOM element by using addComponents/addComponent method

### ISSUE THREAD

**Issue by abhishek1681993** [formio/formio.js#1919]
Hi,
I want to create a new custom component by extending 'PanelComponent'.

We are finding a way to provide to support the custom header/footer section for the panel.

Users can add single or multiple buttons to the panel footer.
And also we want to put the body components into an inner div with 'card-block' bootstrap class.

In the previous version of formio(1.6.4) we are using 'addComponents' and 'addComponent' method and pass the parent div element refrence as its parameter.

Is there any method in formio (4+) that allows adding component /components to the child of given dom element reference?

**Comment by travist** [comment]
As of right now, I don't believe we attach the Form.io instance onto the element. This does seem like something we should do in the future, but until then, we will just need to get the component via the "formio.getComponent" method on the form instance.

**Comment by abhishek1681993** [comment]
@travist I want to create a custom component similar to bootstrap-4 card. 

```
<div class="card">
    <div class="card-header">
        <h4 class="card-text">
            {{label}}
        </h4>
    </div>

    <div class="card-body custom-classes" >
        <div class="card-block">
            Components: This contains body component
        </div>
    </div>

    <div class="card-footer">
        Footer Components: This contains multiple buttons
    </div>
</div>
```

Is this possible to override the existing panel component for this?
