### ISSUE TITLE
Submit button remains disabled after errors are fixed

### ISSUE THREAD

**Issue by ajcolub11** [formio/formio.js#192]
When using the JS renderer, the submit button is disabled when form has errors. However, when valid data is entered into the errored fields and field level errors are dismissed, form level errors remain and submit button is still disabled.

**Comment by travist** [comment]
Will you provide the URL to a form that has this behavior? My simple use case is working for me.

**Comment by silbermm** [comment]
@travist try this link out [https://int.crossroads.net/formiotest](https://int.crossroads.net/formiotest)

Hit submit before filling out the form, then correct any required fields and watch the submit button never re-enable.

**Comment by travist** [comment]
This will be fixed in next release.

**Comment by travist** [comment]
Should be fixed in  2.18.0.
