### ISSUE TITLE
[BUG] When Drag&Drop component on FormBuilder: Uncaught TypeError: Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by fabien-feat** [formio/formio.js#1920]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:4.4.2 (since 4.4.0)
- Frontend framework: vuejs
- Browser:Chrome
- Browser version: Version 77.0.3865.120 (64 bits)

## Steps to Reproduce
1. Drag&Drop any component on builder

## Expected behavior
No error expected

## Observed behavior
Javascript error : 
```js
Uncaught TypeError: Cannot read property 'component' of undefined
    at WebformBuilder.onDrop (WebformBuilder.js:850)
    at Object.<anonymous> (WebformBuilder.js:717)
    at emitter (dragula.js:711)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (dragula.js:710)
    at Object.thing.emit (dragula.js:702)
    at drop (dragula.js:298)
    at HTMLHtmlElement.release (dragula.js:282)
```

**Comment by randallknutson** [comment]
We tested this with 4.4.2 and it works as expected. Can you show how you are using the form within your application? It may be something with the way it is embedded that is causing this issue.

**Comment by aiwebb** [comment]
@randallknutson Reproduced against `latest` in this fiddle: https://jsfiddle.net/vfqcg9wy/6/

I see two issues here:

https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L753

1) need to replace unchecked deep-node access with a `_.get()` call or an explicit check
2) need to fix `_.findIndex(...) || 0` - if not found, `findIndex` will return `-1`, not `null`

**Comment by fabien-feat** [comment]
> We tested this with 4.4.2 and it works as expected. Can you show how you are using the form within your application? It may be something with the way it is embedded that is causing this issue.

I'm using [vue-formio](https://github.com/formio/vue-formio) in v4.0.0

**Comment by ferasA22** [comment]
I've the same issue. Tested multiple versions ,and the issue still persists. 
It started version 4.3.3.

**Comment by ferasA22** [comment]
The bug is solved ,but the behavior is still not the same. There's no indication for the drop similar to the old versions.

v4.7.2
![image](https://user-images.githubusercontent.com/41005014/68267373-448bdb00-0063-11ea-8cea-e143226bbe57.png)

v4.3.2
![image](https://user-images.githubusercontent.com/41005014/68267595-02af6480-0064-11ea-8713-754063c86882.png)

**Comment by jhen1422** [comment]
@ferasA22 
In our testing, we are unable to replicate the drop outline issue shown in your screenshot using version 4.7.2. Could you create a new issue for this and provide more information on how to replicate, like a jsfiddle?
Thanks!
