### ISSUE TITLE
All component IDs are re-assigned upon save

### ISSUE THREAD

**Issue by darabi** [formio/formio.js#1921]
## Environment
- Formio.js version: 4.2

## Steps to Reproduce
1. Create a form with some components and save it
2. Re-open the form in the FormBuilder and change something
3. Save again

## Expected behavior

Component IDs which existed before keep their unique IDs.

## Observed behavior

All components receive a new ID.

The behaviour is observable since 4.0 (presumably introduced with commit 0bb9f394).

This is very annoying when dumping form definitions to files and comparing them.

Is this behaviour absolutely necessary?

**Comment by jhen1422** [comment]
@darabi 
We are unable to produce this issue on our end using v 4.3.3 . Can you provide a js fiddle showing the issue?

**Comment by aminmc** [comment]
@jhen1422 we have experienced this as well.

**Comment by darabi** [comment]
I'm currently travelling and not able to strip down the issue to a jsfiddle.

Maybe the issue is related to formio/react-formio and not to formio.js proper.

@aminmc: do you use formio.js or react-formio?

**Comment by aminmc** [comment]
I’m using react formio but I think it’s a core formio issue.

**Comment by marcus-at-localhost** [comment]
So the assigned key field is persistent through the form?
In my case, I get an ID for form fields from an external source and I save the structure back to that external source (the schema is different so I have to transform back and forth), but I need to use and keep my systems IDs. 

Can this be accomplished in setting the `key` field?

![image](https://user-images.githubusercontent.com/1337223/69433781-e537f700-0d01-11ea-8cf7-61094bcd6798.png)

**Comment by randallknutson** [comment]
You can store the ids in the properties object which allows storing any information that you need. Our ids are not kept between different renders of the form so you can't rely on them. The custom properties is more what you want.

**Comment by marcus-at-localhost** [comment]
@randallknutson you mean in here?
![image](https://user-images.githubusercontent.com/1337223/69440134-d9523200-0d0d-11ea-82ee-e8fd64d2675d.png)

Is there a documentation of all those keys and their usage? I couldn't find one. Just several hint here and there. Thank you!

**Comment by aiwebb** [comment]
@marcus-at-localhost, you might be interested in this if you haven't seen it already:

https://github.com/formio/formio.js/wiki/Form-JSON-Schema

**Comment by marcus-at-localhost** [comment]
@aiwebb thank you so much, I stumbled upon the wiki several times, but didn't connect the dots, yet. This helps a lot!

**Comment by Romakita** [comment]
https://github.com/formio/formio.js/pull/2154
