### ISSUE TITLE
[BUG] Columns.justifyRow: sometimes col.element is undefined

### ISSUE THREAD

**Issue by darabi** [formio/formio.js#1922]
### Environment

- Formio.js version: 4.2

### Steps to Reproduce

We have not been able to pin down a scenario; we have a very complex form with nested columns.

### Observed behavior

Exception because col.element is undefined in [function justifyRow](https://github.com/formio/formio.js/blob/353d431d/src/components/columns/Columns.js#L113)

Sorry for not being able to create a reproducible scenario, but a simple check before calling `setAttribute` would do.

**Comment by travist** [comment]
The commit that @franke-mc created seems fine. If you create a pull request we will accept it in our next renderer.  Thanks @franke-mc!

**Comment by franke-mc** [comment]
This seems to happen deterministically with the following setup:
- An outer form (e.g. [formio1922Outer.json.txt](https://github.com/formio/formio.js/files/3751892/formio1922Outer.json.txt)), containing 
- a nested form (e.g. [formio1922Inner.json.txt](https://github.com/formio/formio.js/files/3751897/formio1922Inner.json.txt)) with a columns component with autoAdjust: true.

Then going to "Enter Data" into the outer form triggers the issue.
