### ISSUE TITLE
Phone number field  does not bring up the number keypad in mobile device

### ISSUE THREAD

**Issue by ajcolub11** [formio/formio.js#193]
Given a user log into form on mobile device (i.e iOS)
Phone number field  does not bring up the number keypad in mobile device

"We believe this is happening because the `type` attribute is set to `text` rather than `number`, e.g.: 'input name="data[phoneNumber]" type="text" class="form-control" lang="en" placeholder="Enter Phone Number" tabindex="7"'"

**Comment by travist** [comment]
This will be fixed in next release.

**Comment by travist** [comment]
Should be fixed in  2.18.0.
