### ISSUE TITLE
[BUG] Logic tab-> Add Action configuration not working

### ISSUE THREAD

**Issue by imshivamchauhan** [formio/formio.js#1931]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.4.2
- Frontend framework: MEAN & angular-formio@latest
- Browser: chrome
- Browser version: any

## Steps to Reproduce
1. In Builder mode, drag any component, open setting, goto Logic Tab.
2. Add Logic, any logic, Add Action -> fill details, in dropdown select properties or value.
3. no further dropdown for true false or properties is displayed.

## Expected behavior
After selecting properties, diff properties like hidden, disabled, etc, dropdown should be visible
## Observed behavior
but dropdown to select properties list is missing as well as textarea to enter value is also missing.

![image](https://user-images.githubusercontent.com/33184564/67272999-3ffbea00-f4db-11e9-8623-d301917d94ff.png)

@travist

**Comment by jhen1422** [comment]
@imshivamchauhan 
Thank you for the report. This is a known issue in our 4x backlog. As a workaround, please save the logic action and then edit the action again. This will display the 'Common Property' field to set your logic action.

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen at any time if still relevant. Thank you for your contributions and discussion.
