### ISSUE TITLE
Registering custom template using new plugin architecture

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1932]
Hello

I'm trying to register a custom template using the new plugin architecture.  

```js
import {Formio} from "react-formio";
import myTemplate from '@digitalpatterns/my-template';
Formio.use(myTemplate);
``` 
However the template is not being applied. When i try to debug I see the following:

![Screenshot 2019-10-22 at 10 50 04](https://user-images.githubusercontent.com/290639/67275253-1aaab400-f4ba-11e9-99a9-60286c06d4a4.png)

The above looks ok in that i got my template...

![Screenshot 2019-10-22 at 10 50 20](https://user-images.githubusercontent.com/290639/67275288-2e561a80-f4ba-11e9-8a41-c915d7fc6660.png)
![Screenshot 2019-10-22 at 10 50 34](https://user-images.githubusercontent.com/290639/67275291-30b87480-f4ba-11e9-8c08-120ee0caa505.png)

The above shows that key is actually the index for example 0, 1.

@randallknutson Have you seen this when using the semantic template?

Edit:
After making a small change to the formiojs code locally i over came the issue with key being '0' by doing:

```js
Object.keys(plugin).forEach(key => {
...
}
```

However what i am noticing is:
![Screenshot 2019-10-22 at 11 32 22](https://user-images.githubusercontent.com/290639/67277957-d4f0ea00-f4bf-11e9-8d09-9937d5d597ca.png)
![Screenshot 2019-10-22 at 11 32 40](https://user-images.githubusercontent.com/290639/67277964-d7ebda80-f4bf-11e9-93d2-c2f2dca42dd1.png)

the default template hasn't is null.

**Comment by aminmc** [comment]
Are the ejs files supposed to be compiled in their separate repo?

**Comment by randallknutson** [comment]
Hi Amin,

I found a few bugs with the current iteration (I'm using for in instead of for of for example). I'll have some working updates here shortly.

**Comment by randallknutson** [comment]
Okay. I pushed up an updated branch. Still working on it but it should work better now. I'll have more by the end of the day.

**Comment by aminmc** [comment]
@randallknutson quick question...do the templates need to be compiled? also is there a branch i should be using to test this or wait?

**Comment by randallknutson** [comment]
Templates should not need to be compiled. We do recommend compiling them though as they run faster and you can disable eval using CSP if you pre-compile them. I've got some examples now up that show how to do this.

https://github.com/formio/semantic
https://github.com/formio/bulma

**Comment by aminmc** [comment]
thanks. I’ll give it a go based on the semantic example.

**Comment by aminmc** [comment]
Hi @randallknutson  I don't see the errors anymore and i've moved my template project to follow the same approach as the semantic one. The issue is that my template doesn't get rendered. It's defaulting to the bootstrap version.  Just playing around with a simple radio component.

I'm noticing the following:
![Screenshot 2019-10-23 at 08 36 56](https://user-images.githubusercontent.com/290639/67369271-a1ba6380-f570-11e9-9bde-22a60c0c3f8b.png)
Which actually does nothing because of:

![Screenshot 2019-10-23 at 08 36 25](https://user-images.githubusercontent.com/290639/67369289-a97a0800-f570-11e9-96c5-0f9d374a05ad.png)
the above is skipped, and I'm not sure if that is intentionally.

**Comment by aminmc** [comment]
This is working now. thanks @randallknutson
