### ISSUE TITLE
Select Box Component Does Not Have Custom Properties Field In API Tab

### ISSUE THREAD

**Issue by ajcolub11** [formio/formio.js#194]
We are expecting the JSON from a form to have a properties value, and select boxes do not have this value at all. This is causing forms with select box components to not save to our database.

![image](https://user-images.githubusercontent.com/29924975/30937039-abb1b2e2-a3a3-11e7-82ce-86226e0c203d.png)

**Comment by travist** [comment]
This will just need to be fixed in the form builder @ https://github.com/formio/ngFormBuilder. Please move this issue over there.

**Comment by ajcolub11** [comment]
moved. Thank you!
