### ISSUE TITLE
[BUG] Radio select fails to work 

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1943]
See below Jfiddle
https://jsfiddle.net/7021xe6h/2/

If you select 'Display hidden' then the panel appears. If you then select hide then panel disappears however if you select 'Display' again it isn't selected.

**Comment by jhen1422** [comment]
@aminmc 
Thank you for the updated report. I've added the jsfiddle to the ticket.

**Comment by sutauma** [comment]
Hi, we have the same behavoir on all radio button components. We use the next.form.io Portal.

**Comment by aminmc** [comment]
Resolved.
