### ISSUE TITLE
[BUG] Tab component template currentTab always 0

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#1946]
Hello,

I'm trying to implement a template for the tab component

```js
 <ul class="xx" role="tablist">
        {% ctx.component.components.forEach(function(tab, index) { %}
            <li class="x-x{{ ctx.currentTab === index ? ' x--selected' : ''}}"
                role="presentation" ref="{{ctx.tabLikey}}">
                <a class="x" role="tab" href="#{{tab.key}}" ref="{{ctx.tabLinkKey}}">
                    {{ctx.t(tab.label)}}
                </a>
            </li>
        {% }) %}
    </ul>
```
However ctx.currentTab is always 0 when i click on different tabs. Interestingly the contents of the tabs appear correctly. So if i click tab 2 then i see the correct tab content but the first tab header is always selected.

**Comment by randallknutson** [comment]
This line should change the currentTab every time the tab is changed: https://github.com/formio/formio.js/blob/master/src/components/tabs/Tabs.js#L126

Any ideas why that doesn't appear to be working?

**Comment by aminmc** [comment]
I’ll add a breakpoint. Interestingly enough the content appears correctly just the header of the tab always stays at 0.

**Comment by aminmc** [comment]
Hi @randallknutson here is my working assumption:
ctx.currentTab is always set to zero and when you select a different tab what's happening is that the setTab method is adding all the necessary css to display and hide the components.

The method render isn't triggered again when you select the tab which means ctx.currentTab is always set to zero.

**Comment by randallknutson** [comment]
If I understand correctly, the header only renders initially and the currentTab is always 0 on the initial render. Then if you switch tabs the classes are updated to switch which one is active. 

There has been some work done on tabs to make them more performant and that may be one of them but it may have introduced some issues such as only adding the bootstrap classes or something like that. I think that is what is happening here https://github.com/formio/formio.js/blob/master/src/components/tabs/Tabs.js#L128-L149

There is probably some cleanup that needs to happen here but I'm not sure what right now without digging deeper into this.
