### ISSUE TITLE
[BUG] Dynamic Select Filtering example broken (v4.5.0)

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1947]
## Environment
Please provide as many details as you can:

https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/ is broken.
Currently it is using https://unpkg.com/formiojs@4.5.0 , as seen on the [Edit in JSFiddle](https://jsfiddle.net/Formio/djsfbLcL/?utm_source=website&utm_medium=embed&utm_campaign=djsfbLcL) link provided with the example.

- Browser: Firefox
- Browser version: 69.0.2

## Steps to Reproduce
1. Select a Make, e.g. Audi
2. Try to select a Model

## Expected behavior
A list of available Models is displayed.

## Observed behavior
- HTTP: 401 Unauthorized
- JS Console: Unable to load resources for model
- Browser: No choices to choose from.

**Comment by jhen1422** [comment]
@franke-mc 
Thank you for pointing this out. It looks like we have a misconfiguration on that form that we will correct.

**Comment by franke-mc** [comment]
Thanks, looking forward to seeing that example working, in particular seeing the Model options update when the Make is changed back and forth...

**Comment by franke-mc** [comment]
I have recreated the example locally. I don't see any problems with "401 Unauthorized" or "Unable to load resources for model", but it still does not work for me. The only thing I can get to work is making the *first* load of model options dependent on the selected make. For this to work, the following conditions must be fulfilled on the "make" component:
- Lazy Load Data is enabled / true.
- Refresh Options On is left blank

If I change "Refresh Options On" to 'Make' or 'Any Change', it all stops working: the client does not even attempt to load the model resources from the server, but simply says 'No choices to choose from'.

@jhen1422 , @travist : Is there any other data we could provide to help you fix this? What would you recommend for a project that absolutely needs this to work? Go back to 3.x? Or can you suggest some places in the code that one might be able to hack to fix (or work around) this problem?

**Comment by franke-mc** [comment]
Thanks @travist, v4.6.2 with #1973 is working fine now.

**Comment by franke-mc** [comment]
@jhen1422 : You can keep this ticket closed, that's fine; just be aware that the example on your website is still broken.
