### ISSUE TITLE
[BUG] New Flatpickr div element is added every time some property of Date/Time component changes

### ISSUE THREAD

**Issue by lionnel8** [formio/formio.js#1949]
## Environment
- Formio.js version: 4.5.0

## Steps to Reproduce
1. Add Date/Time component to the form.
2. Try changing some property of added component, e.g label or placeholder.
3. New Flatpickr div is appended to the HTML body every time some property is changed.

## Expected behavior
No new div will be appended.

## Example
![formioBug](https://user-images.githubusercontent.com/33231575/67497034-a6b90900-f67d-11e9-864e-b6ea943eaa64.PNG)

**Comment by jhen1422** [comment]
This should be resolved in 4.7.3
