### ISSUE TITLE
submit resets submission object

### ISSUE THREAD

**Issue by dannymcpherson** [formio/formio.js#195]
In about the past week, this bug showed up for me:  submitting the form resets the submission data.  However, the data in the change handler, prior to submitting, is correct.

```
form.on('change', function(value) {
    console.log({data: value.data});  // <---- data is correct
});

form.on('submit', function(submission) {
    console.log(submission);  // <---- data is lost
});
```

**Comment by travist** [comment]
I just pushed up 2.18.0 which includes a check on the following page for what you are doing. 

http://formio.github.io/formio.js/app/examples/hosted.html

If you inspect the console, you will see that you do get a submission on submit. Please verify it works for you as well.

**Comment by dannymcpherson** [comment]
It appears to still be broken.  Yes, I get a submission, but its a weird half-data, half-schema object.  It is not the expected json representation of the form values.
