### ISSUE TITLE
[BUG] file select dialog opens twice

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#1950]
latest version "formiojs": "^4.5.0",
1. add file component to form in builder and configure file provider.
2. click browse on that component.
3. click cancel.
4. see select file open again.

**Comment by wag110894** [comment]
Thanks for reaching out!

Could you provide a JSFiddle of this occurring?

Thanks.

**Comment by heather-formio** [comment]
Closing as this is stale. Please feel free to reopen at any time if still relevant. Thank you for your contributions and discussion.
