### ISSUE TITLE
[BUG] Conditional visibility broken when depending on custom default value of nested form

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#1953]
## Environment
- Hosting type
  - [x] Form.io
- Formio.js version: 4.5.0
- Frontend framework: react-formio
- Browser: firefox 
- Browser version: 70.0

## Example on next.form.io:
* [main (= outer) form](https://api.form.io/project/5d1c9ef99cf71913daa0e494/form/5d1e273921470951960b2839)
* [nested (=inner) form](https://api.form.io/project/5d1c9ef99cf71913daa0e494/form/5d1c9f229cf719640ca0e4a6)

## Steps to Reproduce
1. Create an (inner) form with a checkbox component.
2. Add another component, conditionally visible when the checkbox is true.
3. Create an (outer) form with the above form as nested (sub-)form.
4. In that (nested-)form component, specify the custom default value for the inner form to be `{data: {apiKeyOfCheckbox: true}}`
5. Use the main (outer) form to enter data.

## Expected behavior
As the checkbox is correctly checked right from the beginning, the conditionally visible component should be visible from the start as well.

## Observed behavior
The checkbox is correctly displayed as set to true, but the conditionally visible component is still hidden. At some point, that component suddenly becomes visible, for example while typing into an unrelated textfield nearby.

When using custom JS to implement the 'Conditional' behavior instead of simple logic, one can observe that the visibility computation is indeed done, with the correct result in the final round. But that result is not reflected in the display on-screen, until something causes a refresh somehow.

![formioBug](https://user-images.githubusercontent.com/46748541/67571374-138eda80-f734-11e9-8888-dfdbab3a18bb.png)

**Comment by wag110894** [comment]
Thanks for reaching out! We are able to replicate and have added this to our backlog. We will let you know once this issue is resolved.

**Comment by jhen1422** [comment]
@franke-mc 
This should be resolved in the latest version of 4x. Please let us know otherwise, thanks!

**Comment by franke-mc** [comment]
@jhen1422: What makes you think that this has been resolved? Can you point me to specific commits maybe? At first glance, this looks still broken in v4.7.0, and the above example on form.io still demonstrates the problem. I don't see a Changelog entry for this either. Wrong issue maybe?

**Comment by jhen1422** [comment]
@franke-mc 
I apologize for the miscommunication. The default value does appear correctly on my end but the conditional trigger is not being executed. I will move this item back to our issue log.

**Comment by franke-mc** [comment]
Ok. Can you point us to some high-level explanation on how this is supposed to work, i.e. what is usually happening after the assignment "show = true" in some custom 'Conditional' javascript so as to make the component visible on-screen? Any hints, docs, pointers to relevant code, summary explanations etc. are much appreciated...

**Comment by franke-mc** [comment]
Workaround: Use custom validation on `showNumber` to explicitly set `_visible` attribute on dependent components, and `refresh()` them.
```
//console.log('validating showNumber: input = ',input,', data.showNumber = ', data.showNumber);
if (data.showNumber) {
  const comp = instance.root.getComponent('number');
  if (!comp._visible) {
    //console.log('comp = ',comp,', setting _visible to true and refreshing ...');
    comp._visible = true;
    comp.refresh();
  }
}
valid = true;
```

**Comment by franke-mc** [comment]
Unfortunately, the workaround described above breaks down when the checkbox is hidden.

**Comment by franke-mc** [comment]
This is the order of things happening, per JS console:
```
nestedForm : dataValue := defaultValue =  null
onRender
showNumber : dataValue := defaultValue =  false
number: show =  false
number: show =  false
onChange: info.data.showNumber =  false
nestedForm: custom default value :=  {"data":{"showNumber":true}}
nestedForm : customDefaultValue =  {"data":{"showNumber":true}}
nestedForm : dataValue := dataValue =  {"data":{"showNumber":true},"metadata":{}}
showNumber : dataValue := defaultValue =  false
number: show =  false
onRender
number: show =  false
onChange: info.data.showNumber =  false
```
@travist : Is the order of events supposed to be like this? Or can you pinpoint where things should be different?

**Comment by franke-mc** [comment]
Known good/bad versions:
* good: formiojs 4.0.0-rc.23, react_formio 4.0.0-rc.13

**Comment by randallknutson** [comment]
Thanks for the very detailed bug report. We are going to add this to our bug list to be fixed.

**Comment by franke-mc** [comment]
@randallknutson, @travist: Finally, I may have got a workaround for this issue: in `createSubForm()`, 
use `dataValue.data.foo` to override `defaultValue` of (sub)component `foo`. Patch upcoming.

**Comment by franke-mc** [comment]
Unfortunately, while the toy testcase example described here appears to work now, the general case involving more complex forms seems to require a more careful `customConditional` code which avoids setting `show` until the flag checkbox value is actually present in the data:
```
const flagComponentKey = 'showNumber';
if (data.hasOwnProperty(flagComponentKey)) {
    show = !!data[flagComponentKey];
}
```
To me, it seems unintuitive that this should be necessary, though.

NOTE: This implies that the simple conditional logic can't be used here.

Suggestion for improvement: while it would not fully solve this problem, it might be a step forward to treat assigning `undefined` to `show` the same way as not assigning anything to it.  This way, the logic of whether to assign to show or not can be encapsulated in a utility function somewhere and does not need to occur explicitly in the custom JS of each and every conditionally visible component.

Yet another problem: it does not appear to work reliably, if at all, for those components depending on a flag checkbox being false. For them, the behavior is as originally reported in this issue. Maybe I can come up with a testcase for that...

**Comment by travist** [comment]
So are you saying that your code change still does not resolve the issue? Should I hold off on committing the pull request? We do have this in our backlog, but it may take a week or so before it works its way up to the top.

**Comment by franke-mc** [comment]
The pull request is good to go. Regarding further work: my impression is that checkboxes in general have a problem with their values or the visibility of their values, especially when they are hidden. I'm just about to file another issue in that category. I suggest to (1) merge this pr, (2) fix the basic checkbox value issues, and (3) then revisit this issue and see if there is still something left to fix.

I will update this comment with some issue refs I think should be investigated in (2).

**Comment by travist** [comment]
Sounds good. I will include your PR in our next release. We may need to distill a short list of issues with Checkboxes so that we can get them added to our list. @wag110894 and @jhen1422 are responsible for our internal list of items that need to get resolved so they would be the ones to communicate this "short list" to.

**Comment by franke-mc** [comment]
@wag110894, @jhen1422: https://github.com/formio/formio.js/issues/822 sounds like another checkbox issue.

**Comment by franke-mc** [comment]
Right now, this issue still exists in formiojs 4.8.0-rc.2 (and react-formio 4.2.4). Next step is to merge PR #2049 which I can confirm fixes the testcase.

**Comment by travist** [comment]
Sorry everyone.  I had to revert the pull request. I provided explanation in the pull request ^.
