### ISSUE TITLE
[BUG] name property should not be used for storage providers

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#1956]
We run into issue with custom storage provider that was defined as a class. 

Typescript does not allow override name property, see 
https://github.com/OUP/cxsd/commit/8ac66a8d09fb381b42638580b6b7af5618a6dd93
and
https://github.com/microsoft/TypeScript/issues/442

If you leave it without overriding, production version compiles down to a single letter. Thus causing the issue with storage provider that is reference by a full name.

Consider changing to something like 'providerName' instead of 'name' property.

**Comment by travist** [comment]
Agreed, but this would need to be done in 5.x branch of our new renderer.
