### ISSUE TITLE
Datagrid cannot read property '0' of undefined/Cannot read property '0' of null

### ISSUE THREAD

**Issue by antonyagustine** [formio/formio.js#1963]
When I create a custom event for a button and check the checkbox called _Show Validations_ this issue occurred

![datagrid_issue](https://user-images.githubusercontent.com/39733569/67671529-20ae0280-f99c-11e9-8d4d-c7071cebe6c7.png)

**Here is jsfiddle link to reproduce the issue**. [JsFiddle](https://jsfiddle.net/agustine/40bsfm26/3/)

![formio_grid_issue_reproduce_img](https://user-images.githubusercontent.com/39733569/67671368-d3ca2c00-f99b-11e9-9065-d33682b53cfa.png)

**Comment by jhen1422** [comment]
@antonyagustine 
Thank you for the report. Could you please provide the formio.js version you are using and a jsfiddle showcasing the issue?

**Comment by antonyagustine** [comment]
I'm using formio.js v4.6.1. And you can also jsfiddle it will show the console error when you fill the form and click on the submit button.

**Comment by jhen1422** [comment]
@antonyagustine 
Thank you for the report. I've added this item to our 4x backlog. If you need to expedite this item, please contact support@form.io for pricing.

**Comment by antonyagustine** [comment]
Thanks @jhen1422 .

**Comment by jhen1422** [comment]
@antonyagustine 
This issue seems to be resolved using the latest renderer version.
