### ISSUE TITLE
Formio form does not fire beforeSubmit event

### ISSUE THREAD

**Issue by abhishek1681993** [formio/formio.js#1983]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:4.4.1

## Steps to Reproduce
1. Create a formio form
```
<formio #formElemnet [form]="form" [submission]="submission" (render)="onRender(formElemnet )" (submit)="onSave()"></formio>
```
2. Attach beforeSubmit hook handler after form render
```
onRender( form: any): any {
form.options.hooks.beforeSubmit = this.handleBeforeSubmit.bind(this);
}

handleBeforeSubmit(submission, callback) {
console.log(submission);
}
```
3. After clicking on submit button beforeSubmit event does not trigred

**Comment by travist** [comment]
The issue here is that you are not referencing the form instance correctly. It would work like the following.

```
<formio #formElement [renderOptions]="renderOptions" ...>
```

And then you would have the following in your component.

```
this.renderOptions = {
  hooks: {
    beforeSubmit: (submission, next) => this.handleBeforeSubmit(submission, next);
  }
}

```
