### ISSUE TITLE
[Question] Can we override remove button in data-grid

### ISSUE THREAD

**Issue by abhishek1681993** [formio/formio.js#1984]
Hi,

I want to create a new component by extending '**DataGridComponent**' to fulfill the following custom requirement:

- Provide custom icon for remove button
- Show custom confirmation alert before removing the item (row)
- Provide custom icon to add another button
- Add a custom class to the table
- Provide **filtered**/different data source to a column for select control after adding new row

Can you help me to extend DataGridComponent to fulfill my requirements?

Thanks

**Comment by rahulseth625** [comment]
@abhishek1681993 Have you done that requirements. Can you pls share the modified code of DataGridComponent. It will be very helpful for me as I need the same requirements.
Thank you.
