### ISSUE TITLE
renderMode flat not working

### ISSUE THREAD

**Issue by ssrini** [formio/formio.js#1990]
The wiki page documents renderMode and mentions that "flat" will render all tabs/wizards visible so that all the data will be seen.

Here is a simple example from the formiojs page but still renders as a standard wizard and not expanded or flat.  

**How do we get the flat render mode to work?**

```
<html>
  <head>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
    <script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/wizard', {renderMode: 'flat'});
      };
    </script>
  </head>
  <body>
    <div id='formio'></div>
  </body>
</html>
```

**Comment by randallknutson** [comment]
This got changed at some point to be { flattened: true }

This pull request will restore the old way as well. https://github.com/formio/formio.js/pull/2103
