### ISSUE TITLE
[BUG] How to refresh DataGrid's header label

### ISSUE THREAD

**Issue by pardeep224** [formio/formio.js#1994]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.5.0
- Frontend framework: "angular-formio": "4.2.10",
- Browser: Google Chrome
- Browser version: Version 77.0.3865.120 (Official Build) (64-bit)

## Steps to Reproduce
1.  Take a Select component in DataGrid.
2.  Take an Textfield in DataGrid.
3.  Write action in logic tab of Textfield to make this field required on the basis of any value of Select component.
4. Run the form and change value from Select component. Now Textfield within DataGrid becomes required, but (*) asterisk is not coming on header label.

## Observed behavior: Asterisk(*) is not showing on Textfield.
In which file i have to make changes to refresh DataGrid's header label and what changes I should made. Please guide.

**Comment by jhen1422** [comment]
@pardeep224 
We currently have this issue on our 4x backlog. We'll be sure to notify you when this has been resolved. In the meantime, we do offer pull requests for the library. If you need this issue expedited, please contact support@form.io for pricing.

**Comment by wag110894** [comment]
Hello @pardeep224,

This issue has been resolved. You can use the latest version of formio.js to test 4.11.2.
