### ISSUE TITLE
[BUG] DateTime component with date format dd/MM/yyyy broken again

### ISSUE THREAD

**Issue by moshefi** [formio/formio.js#2000]
- Hosting type
  - [X] Local deployment
- Formio.js version: 4.7.0

After fixed, Stopped working again.
See:
https://jsfiddle.net/moshefi/p7bwm1rh/9/

**Comment by travist** [comment]
I suspect @randallknutson broke it with this pull request. https://github.com/formio/formio.js/pull/1997 

We will investigate soon and write some automated tests around it.

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/2005

I added tests to make sure it doesn't break again.

**Comment by pierrick** [comment]
looks like it s still broken  in formiojs@^4.9.0:

**Comment by wag110894** [comment]
@pierrick can you provide a js fiddle or form JSON so that we can investigate this issue? Could you also provide what version that you are seeing this issue on?

**Comment by travist** [comment]
Seems to be working with the latest version.
