### ISSUE TITLE
Is there a way to customize a component's simple conditional to include "starts with", "contains", "greater than", etc. conditions without using *advanced conditions* or *JSONLogic* options?

### ISSUE THREAD

**Issue by Abdalmassih** [formio/formio.js#2002]

**Comment by randallknutson** [comment]
We are currently looking into expanding our conditional system to include an "intermediate" option or making the simple conditionals more functional by adding And/Or nested options as well as more comparisons like you are requesting. This is currently in our backlog but getting closer to being started. Is this something you would be interested sponsoring to move it forward?

**Comment by Abdalmassih** [comment]
Hello @randallknutson,

Thanks a lot for your prompt reply and for taking the mentioned requests into consideration. I have two further questions for which your answers would be much appreciated:

1. Is it possible to guide me to where and how exactly I need to manipulate/extend the current simple conditional system? If we manage to extend the current conditionals, we will be willing to provide the improved code to you right afterwards.

2. If the first request is not possible for any reason, how much does a "sponsoring" cost? What are the actual features and when could we expect results? Please have a look at *GravityForms* (a WordPress plugin which offers form builders with quite complex conditionals for the use of people with no tech background):
https://docs.gravityforms.com/category/user-guides/conditional-logic/

Thank you again for your kind support.

**Comment by randallknutson** [comment]
Absolutely. 

The form that controls the settings for conditional logic exists here: https://github.com/formio/formio.js/blob/master/src/components/_classes/component/editForm/Component.edit.conditional.js. You can modify it to add the additional functionality settings. 

Then, the code to execute the conditionals starts here: https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L1272-L1302 and is actually executed here: https://github.com/formio/formio.js/blob/master/src/utils/utils.js#L269-L294

Can you contact support@form.io about pricing for support?

**Comment by krixerx** [comment]
Hello,

we are interested too to have something similar to
https://querybuilder.js.org/
to build conditions and which can export conditions in JsonLogic format.

Erki

**Comment by travist** [comment]
We have done this with our latest enterprise form builder. If you are looking for an OSS version of this, then it would need to be provided by a third party.
