### ISSUE TITLE
[BUG] Custom Properties Tab Component

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio.js#2004]
## Environment
- Formio.js version: 4.7.0

## Steps to Reproduce
1. Add Custom Properties in a component
2. Save
3. Re Edit the component

## Expected behavior
The Custom Properties tab is displayed

## Observed behavior
The Custom Properties tab is displayed after clicking on the 'Add Another' Button

**Comment by jhen1422** [comment]
@AudreyCb 
I've tested this using the 4.7.0 version of our renderer and are unable to replicate. Custom Properties persist after saving the form. Can you please try using the latest 4x version?

**Comment by AudreyCb** [comment]
My fault, it's indeed ok on this version, sorry for this waste of time
