### ISSUE TITLE
Formio.js IE11 support? Issues running examples - : expected line 4704

### ISSUE THREAD

**Issue by pkorosi** [formio/formio.js#2008]
I cannot run the example code at https://formio.github.io/formio.js/ in IE11 (windows 7). The console logs an error at line 4704 that it is expecting a : (colon). Works fine in chrome and firefox.

I am trying to get the latest version running in my project but have the same error in IE11 as the example above. The last version I had working was 3.17.4, but this has other issues I am trying to fix with an update.

**Comment by wag110894** [comment]
Thanks for reaching out! 

We are able to replicate this issue. We have added this to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.

**Comment by merobal** [comment]
Related: https://github.com/formio/angular-formio/issues/399
The new template libs are breaking the setup in IE (introduced with formio 4.7), so the previous version (v4.6.4) should work.

You may experience that the `CustomEvent` is not available there, then you need to install and import https://www.npmjs.com/package/custom-event-polyfill and it should work.

**Comment by pkorosi** [comment]
Hi Merobal,

thanks for that... that is working for me. 

I do have another IE problem though with CKEditor - when I try and add a Content element to a form, the console is logging a syntax error at line 5, column 3344 in ckeditor.js.

**Comment by wag110894** [comment]
Thanks for reaching out @pkorosi!

We are able to replicate this issue as well. We have added this to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.

**Comment by wag110894** [comment]
Thank you for your patience while we got this issue with IE11 on our github formio.js page resolved. Perform a hard refresh and confirm that the footer hows Renderer v4.8.0-rc9.

Thank you.
