### ISSUE TITLE
[BUG] Radio button default value fails with boolean values

### ISSUE THREAD

**Issue by sutauma** [formio/formio.js#2009]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: next.form.io
- Frontend framework: next.form.io
- Browser: Sarfari
- Browser version: latest

## Steps to Reproduce
1. Create a form with two radio buttons. The first group should be true/false (boolean) options and the default value should be true. The second group should be left/right (string) options and the default value should left.
2. Execute the form
3. Review the data. 

## Expected behavior
Selecting: false&right -> Data: false&right
Selecting: false&left -> Data: false&left
## Observed behavior
Changing the focus or changing the second radio button group causes the switch back to the default value of the first radio button group.
Selecting: false&right -> Data: true&right

**Comment by jhen1422** [comment]
@sutauma 
Thank you for the report. Could you please provide a jsfiddle showing the issue? That would be a great help in our investigation.

**Comment by sutauma** [comment]
Hi, 

https://jsfiddle.net/sutauma/nd9o856p/

**Comment by jhen1422** [comment]
@sutauma 
Thank you for the example. We  have created a ticket in our 4x branch and will review this item during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/2092
