### ISSUE TITLE
Error messages for fields with reg ex validation

### ISSUE THREAD

**Issue by silbermm** [formio/formio.js#201]
When the reg ex validation for a field fails, the error message actually shows the regular expression to the user (see screen shot). Is there anyway we can customize the error message when the reg ex validation fails? Or provide a better generic error message?

![regex_error](https://user-images.githubusercontent.com/42816/31081156-e29a75f6-a758-11e7-96fa-4a33112329dc.png)

**Comment by travist** [comment]
I think that error message is perfectly explanatory. ;)

Yes, I will add a configuration for this.

**Comment by travist** [comment]
I am adding a component level setting for this, but this could be fixed globally on the form using the i18n property like this.

```
Formio.createForm(document.getElementById('formio'), form, {
  i18n: {
    en: {
      "pattern": "{{field}} does not match the pattern {{pattern}}"
    }
  }
}).
```

**Comment by silbermm** [comment]
Thanks! I will give that a try.
