### ISSUE TITLE
[Improvement] Can you set CSS to put the drop-down box in the table outside the scroll bar

### ISSUE THREAD

**Issue by sssxiaocainiao** [formio/formio.js#2018]
![image](https://user-images.githubusercontent.com/26619935/68264970-a4937900-0085-11ea-9cf6-dcc676b88b57.png)
![image](https://user-images.githubusercontent.com/26619935/68264978-a9582d00-0085-11ea-95f9-0000dd234e1d.png)

**Comment by aiwebb** [comment]
I don't believe this is a CSS fix. HTML dropdowns will always be clipped in situations like this if any of their container elements are clipping overflow - the only alternative I've seen is for the dropdown menu element to actually be placed at document root and then aligned with absolute positioning.

I expect that switching that up would be a bit of an endeavor, but I may be wrong - if you have an example or PR that accomplishes it with minimal code changes, we'd be interested in seeing it.

**Comment by franke-mc** [comment]
Have you tried z-index: 999 or something similar?

**Comment by aiwebb** [comment]
`z-index` shouldn't affect it either way - that will control relative paint ordering within a level of the DOM tree, but the root issue is that the ancestors higher up in the DOM tree are clipping it.

**Comment by sssxiaocainiao** [comment]
Sorry, I'm busy at this time. This problem seems to be the DOM structure problem of Formio itself. I used the location to handle it. The process is complicated

**Comment by sssxiaocainiao** [comment]
对不起，因为这段时间比较忙，这个问题好像是formio本身的dom结构问题，我用的定位来处理的。过程比较繁琐

**Comment by travist** [comment]
Closed due to inactivity. This can also be resolved with your own custom template, but it is likely it is resolved with the latest version.
