### ISSUE TITLE
[BUG] Combining verbatim and JS-generated fragments in a tooltip does not work.

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2022]
- works ok: `"tooltip": "{{'hello world'}}"`
- broken: `"tooltip": "{{'hello'}} world"`

## Example
[See this JSFiddle](http://jsfiddle.net/franke_mc/9zuyqoaw/4).

**Comment by jhen1422** [comment]
@franke-mc 
Thanks for the report. We've added this to our backlog and will notify once this is resolved.

**Comment by travist** [comment]
Seems to be working with latest version.
