### ISSUE TITLE
[BUG] Using DataMap within an edit grid loses the data on Edit mode. 

### ISSUE THREAD

**Issue by sunshinesanty** [formio/formio.js#2024]
## Environment
Please provide as many details as you can:
Node: 10.10.0

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: latest.
- Formio.js version: 4.6.2
- Frontend framework: React 16.9.0
- Browser: All (Chrome, Firefox, IE 11, Edge, Safari)
- Browser version: Latest and -2 version, except IE 11

## Steps to Reproduce
1. Add a `DataMap` component in to an `Edit grid` (as form or wizard)
2. Render the form and select `Add Another`, to add an Edit grid entry. 
3. Enter the key value pair in `DataMap` component.
4. Save the iteration for `Edit grid`.
5. Edit the saved value.

## Expected behavior
The `DataMap` component should load with the correct number of Iterations with teh previously entered data.

## Observed behavior
The `DataMap` component loads with the correct number of Iterations but the data is lost.

## Example
https://codepen.io/sunsghinesanty/pen/QWWrvQv 

For code or form JSON, please enclose in a code block:

```js

var formElement = document.getElementById('formio');

var builder = new Formio.FormBuilder(document.getElementById("builder"), {
  display: 'form',
  components: [
        {
            "label": "Edit Grid",
            "disableAddingRemovingRows": false,
            "modal": false,
            "key": "editGrid",
            "type": "editgrid",
            "input": true,
            "components": [
                {
                    "label": "Data Map",
                    "key": "dataMap",
                    "type": "datamap",
                    "input": true,
                    "valueComponent": {
                        "type": "textfield",
                        "key": "key",
                        "label": "Value",
                        "input": true,
                        "hideLabel": true
                    }
                }
            ],
            "path": "editGrid"
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true
        }
    ],
  settings: {
    pdf: {
      "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
      "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
    }
  }
}, {
  baseUrl: 'https://examples.form.io'
});

var onForm = function(form) {
  form.on('change', function() {
    subJSON.innerHTML = '';
    subJSON.appendChild(document.createTextNode(JSON.stringify(form.submission, null, 4)));
  });
};

  Formio.createForm(formElement, {
  display: 'form',
  components: [
        {
            "label": "Edit Grid",
            "disableAddingRemovingRows": false,
            "modal": false,
            "key": "editGrid",
            "type": "editgrid",
            "input": true,
            "components": [
                {
                    "label": "Data Map",
                    "key": "dataMap",
                    "type": "datamap",
                    "input": true,
                    "valueComponent": {
                        "type": "textfield",
                        "key": "key",
                        "label": "Value",
                        "input": true,
                        "hideLabel": true
                    }
                }
            ],
            "path": "editGrid"
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true
        }
    ],
  settings: {
    pdf: {
      "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
      "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
    }
  }
}).then(onForm);
```

**Comment by jhen1422** [comment]
@sunshinesanty Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by sunshinesanty** [comment]
Thank you @jhen1422 for looking into this. We are looking at the code to see if we can identify the bug, but we are a bit busy with our stuff. I will try my best to contribute more towards this and if possible create a PR or at the least provide more findings

**Comment by moogambigai** [comment]
Hi @jhen1422 , we have created a Pull request to address this issue. Looking forward for reviews and  comments. Thank you !

**Comment by airarrazaval** [comment]
@travist @randallknutson As of 4.8.0-rc.2 this issue not only affects DataMap, but any nested component.

Here is an example that uses a DataGrid inside an EditGrid (https://jsfiddle.net/airarrazaval/ehcfm4v8/).  When editing a row, the nested component values are not set, although, saving without any change does not modifies the editgrid data.

**Comment by randallknutson** [comment]
Thanks for the pull request! We will test this out and get it in a build soon.

**Comment by wag110894** [comment]
This issue has been resolved. You can use the latest version of our formio.js 4.11.2.

Have a great day.

**Comment by AnyISalIn** [comment]
> This issue has been resolved. You can use the latest version of our formio.js 4.11.2.
> 
> Have a great day.

Hi, I used it in version 4.11.3，Adding Datamap works fine, But here's where things go wrong

1. Add twice to a Datamap and save
2. Then edit the DataMap and delete one of them
3. Then try to save will report an error  `Please fix the following errors before submitting. Cannot read property 'find' of undefined`

![image](https://user-images.githubusercontent.com/16937838/95835049-53e5cf00-0d70-11eb-80e5-7626499d5530.png)

**Comment by AnyISalIn** [comment]
> Hello @AnyISalIn,
> 
> Can you provide a JSFiddle so that we can take a look at this on our side?
> 
> Thank you.

https://codepen.io/sunsghinesanty/pen/QWWrvQv

Thank for your reply, Follow the operation of this gif to reproduce the exception
![2020-10-13 22-33-21 2020-10-13 22_34_07](https://user-images.githubusercontent.com/16937838/95875645-cffa0a00-0da4-11eb-864d-b9b2bac9aa21.gif)

**Comment by wag110894** [comment]
Hello @AnyISalIn,

Thanks for sending over the Codepen as well as the video. 
We are able to replicate this issue on our side. We have created a ticket and have added it to our backlog. We welcome a pull request or have a process to expedite if you are interested.

For reference, the ticket number is FJS-1329. 

We will let you know once this issue has been resolved.

**Comment by travist** [comment]
5.x has a completely overhauled validation system and I am sure this will be resolved using that version. If not, please open a new PR with latest information.
