### ISSUE TITLE
Hooking into formio's DOM and/or events

### ISSUE THREAD

**Issue by Abdalmassih** [formio/formio.js#2026]
Hello,

I am integrating formio.js code into my project locally as stated in the README file. The library's code exists as a cdn on the url (https://unpkg.com/formiojs@latest/dist/formio.full.js) which I copied to my localhost.

Now I want to somehow get access to the dom (and preferably events) of the library's integrated code in the view file via jquery right from my project's code, e.g. I tried appending some html elements to a component's *Conditionals* tab, but this did not work for some reason.
Thanks a lot.

**Comment by franke-mc** [comment]
For events, see e.g. `form.on('change', ...)` over [here](https://github.com/formio/formio.js/wiki/Form-Renderer#instance-methods).

**Comment by Abdalmassih** [comment]
Hello @franke-mc, thank you for the reference. I had a look at those events. These are actually hooks for the form renderer (at the rendering stage) which of course I made use of. However, I want to also be able to listen for events at the form *building* stage. Like in the example I gave above, I am particularly interested in listening for when the user clicks the *Conditionals* tab and be able to append some html content to the popup window. This did not work via jquery. Do you have any solutions/workaround for this? Again, I appreciate your kind and quick help very much.

**Comment by franke-mc** [comment]
Have you thought about customizing the formio.js library? It might be the simplest way to achieve what you want.
