### ISSUE TITLE
[BUG] SubmissionGrid omits component if "tableView": true is omitted from json representation

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2028]
Formiojs version: latest.

We have a case of a simple text field component where `"tableView": true` has been omitted from the json representation of the form during save.  This omission should be fine as this is the default case.  When the component is loaded in the form builder, the `tableView` checkbox shows up as checked, too.

However, the `getColumns()` call in `SubmissionGrid` does not return the component in question. Adding back `"tableView": true` explicitly to the component in the json representation of the form brings back that component in the `SubmissionGrid`.

**Comment by jhen1422** [comment]
@franke-mc 
We've reviewed this item internally and concluded that this is expected behavior within our renderer.
