### ISSUE TITLE
[BUG] FormioForm does not trigger/emit all events

### ISSUE THREAD

**Issue by fabien-feat** [formio/formio.js#2029]
- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.7.3
- Frontend framework: vuejs (with formio/vue-formio) -> tested in JsFiddle with native formio
- Browser:Firefox (v70.0) and Chrome (v78.0.3904.70)

## Steps to Reproduce
See this JsFiddle :  [JSFiddle](http://jsfiddle.net/fabienfeat/05p62u91/)

I've tested these events : 

- formLoad
- initialized
- render
- build

Thanks

**Comment by jhen1422** [comment]
@fabien-feat 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by randallknutson** [comment]
Can you test this again? We did do some fixes to this a while ago. Some of the events are triggered on the instance that is returned from the class instantiation and some are on the return from the creation promise. The reason why is that the instance from the creation promise is resolved AFTER the formLoad, initialized, render and build events are fired. So if you are waiting till the init promise is resolved it will be after those items. 

https://github.com/formio/react-formio/blob/master/src/components/Form.jsx#L110
https://github.com/formio/react-formio/blob/master/src/components/Form.jsx#L86
You can see here that the listeners are placed on the first instance itself and not after the promise is ready.

**Comment by jason-yong** [comment]
@randallknutson Doesn't work using the following fiddles: http://jsfiddle.net/fabienfeat/05p62u91/49/ and http://jsfiddle.net/fabienfeat/05p62u91/

**Comment by fabien-feat** [comment]
Hello !
We have updated formiojs to 4.9.10, render event seems to be trigger correctly !
Good job !

Nevertheless, there is no object in event...
A good feature would be to add a context objet (ie. in wizard, the page that has just been rendered).
So, how can I know the page that has just been rendered, when the form is rendered ?

Regards.

**Comment by randallknutson** [comment]
Events should send a context object which vue should pass along. You can see in the emitter that we pass them along. https://github.com/formio/vue-formio/blob/master/src/components/Form.ts#L145-L164

It does look like the Wizard is passing some context along with the events. You can see that here: https://github.com/formio/formio.js/blob/master/src/Wizard.js#L407

**Comment by fabien-feat** [comment]
Ok for vue-formio.
Three classes emit render event, Form, Wizard, WebForm, but Wizard and WebForm doesn't send a context object : 
https://github.com/formio/formio.js/blob/master/src/Wizard.js#L186
https://github.com/formio/formio.js/blob/master/src/Webform.js#L971

Form class send context object : 
https://github.com/formio/formio.js/blob/master/src/Form.js#L266

It should be cool to always send a context object, for example Wizard should send the currentPage when emit render event.

I'm sorry i can't create a jsFiddle with vue-formio for live example...

**Comment by fabien-feat** [comment]
I close this issue, see [this one](https://github.com/formio/formio.js/issues/2630)

**Comment by neshiq** [comment]
Hello, this is still problem with version 4.12.7. Mentioned events won't trigger

**Comment by wag110894** [comment]
Hello @neshiq, can you provide a reproducible case?

**Comment by vassabi** [comment]
@wag110894 the fiddler provided in the first comment is still not firing events, is this bug fixed?

**Comment by jlzhou** [comment]
I just met same issue with latest code, is this bug fixed?
