### ISSUE TITLE
[BUG]  userPermissions() function does not account for "Group/Resource access roles"

### ISSUE THREAD

**Issue by bh-adrienne** [formio/formio.js#2030]
## Environment
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 
- Frontend framework: Angular
- Browser: Either Firefox or Chrome
- Browser version:

## Steps to Reproduce
1.  You can follow the Form.io Postman API tutorial to set up an example with Group Permissions here (https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest#1637ccdf-5438-4e3f-a2a9-6584e4f3e90a) 

2. When using Formio.js + Angular-formio + Angular FormioResourceComponent, the check to see if the "Edit" option for a particular submission should be displayed is based on a call to Formio.js function _this.service.formFormio.userPermissions(_this.auth.user, form, resource) (currently line 39 in file resource.component.js in angular-formio)

## Expected behavior
This function should return TRUE for  return value perms.edit if a user has Group permissions role to _edit_ an object.

## Observed behavior
This function returns FALSE for return value perms.edit, if a user has Group permissions role to _edit_ an object.

**Comment by jhen1422** [comment]
@bh-adrienne 
Thank you for the report. We've created a ticket for the issue and have added to our platform backlog. We will review this issue during our planning meeting next week.  If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
Thank you for your patience while we discussed this item internally. After the discussion, we estimate this at 8 hours.  If you would like to sponsor this platform enhancement, please reach out to support@form.io and we will give you a quote.

Thanks,

**Comment by Alena-Levina** [comment]
Hi @bh-adrienne , your issue was fixed in following PR: https://github.com/formio/formio.js/pull/2141

**Comment by wag110894** [comment]
Hello @bh-adrienne This issue has been resolved with the latest version of formio.js 4.8.0-rc3.

Thank you for using Form.io!
