### ISSUE TITLE
Unable to edit custom component.

### ISSUE THREAD

**Issue by 0xMitsara** [formio/formio.js#2038]
I was looking at the documentation when i came across this example:
[https://formio.github.io/formio.js/app/examples/customcomponent.html](https://formio.github.io/formio.js/app/examples/customcomponent.html)

When I drag a checkbox matrix onto the form i'm presented with the popup to populate all the fields, however i do not get the option to edit when i hover over the component once i click on Save. Is this due to the way that the component is configured or an actual bug in the code.

![image](https://user-images.githubusercontent.com/1884783/68620778-3511f500-049c-11ea-8a49-b6542d492669.png)

Thank you and please let me know if you require further details.

**Comment by marcus-at-localhost** [comment]
I can confirm! This is also happening in the examples: http://formio.github.io/formio.js/app/examples/customcomponent.html

**Comment by marcus-at-localhost** [comment]
Here is a way to fix the missing edit button group for custom components if you don't build your own formio.js[1]

The solution is to use the `builderComponent` key in `this.renderTemplate('builderComponent', { html });` and to make sure the edit buttons don't show up in the preview.

That part of the code is taken from the [source](https://github.com/formio/formio.js/blob/90c7c71b315cbc6c6fc21d5544244c5e13beefe0/src/WebformBuilder.js#L122)[2] 

```js
/**
 * Tell the renderer how to render this component.
 * @see https://github.com/formio/formio.js/blob/90c7c71b315cbc6c6fc21d5544244c5e13beefe0/src/WebformBuilder.js#L122
 */
HeaderComponent.prototype.render = function(element) {

	var html = this.renderTemplate('html', {
		component: this.component,
		tag: this.component.tag,
		attrs: this.component.attrs || {},
		content: this.content,
		singleTags: this.singleTags,
	});

	if (this.type === 'form' && !this.key) {
		// The main webform shouldn't have this class as it adds extra styles.
		return html.replace('formio-component-form', '');
	}

	if (this.options.disabled && this.options.disabled.includes(this.key) || this.parent.noDragDrop) {
		return html;
	}
	// wrap component in edit buttons
	return this.renderTemplate('builderComponent', { html });
};
```
here is a working jsfiddle http://jsfiddle.net/0xfwh3cu/11/

[1] I hope the devs reign in and recommend fixes or give some more insight.
[2] painfully reverse engineered from https://unpkg.com/formiojs@latest/dist/formio.full.min.js and the source here on github

**Comment by SalTor** [comment]
@marcus-at-localhost Thanks for this, I too found that with the default Custom Components instructions I couldn't edit the settings once placed and confirmed. Now I can!

**Comment by travist** [comment]
Seems to be working with latest renderer version.
