### ISSUE TITLE
[BUG] Breadcrumbs showing up when hidden when not using form.io

### ISSUE THREAD

**Issue by cymen** [formio/formio.js#2039]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: vanilla JavaScript
- Browser: Chrome
- Browser version: 78.0.3904.87

## Steps to Reproduce
1. Save this gist to local file and open in browser https://gist.github.com/cymen/d121256ba29da41ae102e84ece7f6401

## Expected behavior

Breadcrumbs not present. For example of this on form.io, go to:

https://formview.io/#/udhkdmwfegsesuy/mi

## Observed behavior

Breadcrumbs present.

## Example

https://gist.github.com/cymen/d121256ba29da41ae102e84ece7f6401

OR

```
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
    <script src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>
    <script type="text/javascript">
      window.onload = function() {
        Formio.icons = 'fontawesome';
        Formio.createForm(document.getElementById('formio'), 'https://udhkdmwfegsesuy.form.io/mi');
      };
    </script>
```

**Comment by jhen1422** [comment]
@cymen Thank you for the report. We have created a ticket in our 4x branch for this issue and we will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by muster-mark** [comment]
Still seeing this issue in 4.11 - is this still going to be fixed?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
