### ISSUE TITLE
Strange behavior when using Advanced Logic

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2042]
On next.form.io, a simple form ([e.g. this one](https://api.form.io/project/5d1c9ef99cf71913daa0e494/form/5dcab5849637c63d65666bbd)) with two components exhibits strange behavior:
* a button generates an event when clicked, named `myTestEvent`.
* a number component, initially 0, programmed to increment by 1 when receiving `myTestEvent`.

Observed behavior: 
* Initially being 0, upon each button click the `eventCounter` value changes to 2x+3, where x is the previous value: The sequence is 3, 9, 21, 45, 93, 189, ...
* The JS console shows that the custom logic action code is run about that many times...

Questions: 
* Is this a bug or a feature?
* What about a complex example using Advanced Logic?
* The UI instructs me to return the new value instead of assigning it to the `value `variable, in contradiction to the placeholder text which gives an example of `value = data.myfield;`  Which is the correct one? (The behavior is the same in both cases, except that in the 'return' case there is an additional JS console warning about some code-after-return being eliminated.)
* @wag110894 : Is this combination (button event as sender & advanced logic as receiver) [still recommended](https://github.com/formio/formio/issues/674#issuecomment-434430659) to propagate changes in one component to other components? Is it expected to work across subform boundaries? If not, is there a better mechanism which does work to communicate changes to parent forms and nested subforms?

**Comment by randallknutson** [comment]
Sounds like the event is getting registered too many times. The event should unregister on a redraw but that may not be happening. We can add this to our backlog to look into. If you want to research this, there is a place in Component.js where field logic events are registered. There should be a place where they are unregistered on redraw as well but it probably doesn't exist.

**Comment by franke-mc** [comment]
@randallknutson : When adding code to unregister existing callbacks before registering new ones for the same event on the same component, the behavior improves:
```
   attachLogic() {
+    // Unregister any existing callbacks on events for which we are going to
+    // register new ones.  There may be multiple logics for the same event,
+    // so we can't do this in the attach loop below.
+    this.logic.forEach(logic => {
+      if (logic.trigger.type === 'event') {
+        const event = this.interpolate(logic.trigger.event);
+        this.off(event); // only applies to callbacks on this component
+      }
+    });
     this.logic.forEach(logic => {
       if (logic.trigger.type === 'event') {
         const event = this.interpolate(logic.trigger.event);
+        //console.debug('attaching logic on event ',event);
         this.on(event, (...args) => {
+          //console.debug('processing event ',event, ...args.map(JSON.stringify));
           const newComponent = _.cloneDeep(this.originalComponent);
           if (this.applyActions(logic.actions, args, null, newComponent, null)) {
             // If component definition changed, replace it.
             if (!_.isEqual(this.component, newComponent)) {
               this.component = newComponent;
             }
+            //console.debug('Redrawing after processing event ',event);
             this.redraw();
           }
         }, true);
```

Now, the sequence is 2,4,6,8,.. i.e. the event is either fired twice or processed twice for each click. Bug or feature?

- Initial load:
```
detaching logic from event  myTestEvent
attaching logic on event  myTestEvent
onRender
detaching logic from event  myTestEvent
attaching logic on event  myTestEvent
detaching logic from event  myTestEvent
attaching logic on event  myTestEvent
onRender
detaching logic from event  myTestEvent
attaching logic on event  myTestEvent
```

- first button click:
```
processing event  myTestEvent on Object { generateMyTestEvent: true, eventCounter: 0, ... }
redrawing
detatching logic from event  myTestEvent
attaching logic on event  myTestEvent
processing event  myTestEvent on Object { generateMyTestEvent: true, eventCounter: 1, ... }
redrawing
detatching logic from event  myTestEvent
attaching logic on event  myTestEvent
```

**Comment by randallknutson** [comment]
Can you try moving that to the detach method? It should get called whenever the element is about to be detached. This might be a timing issue where attach isn't the right place to put the code.

**Comment by franke-mc** [comment]
@randallknutson : Thanks, that works.

**Comment by randallknutson** [comment]
Awesome! Thanks for tracking this down and submitting a pull request.

**Comment by franke-mc** [comment]
![testFieldLogicEventsWithNestedForms](https://user-images.githubusercontent.com/46748541/68968024-dcb35e00-07e1-11ea-9672-8ea3a8846d17.png)

So it looks like this feature 
- (a) can be used to communicate events from a nested (inner) form to its (outer) parent form, but
- (b) does not work to communicate events from the (outer) parent form to a nested (inner) form.
Also, right now we find that 
- (c) events emitted in an inner form are processed twice in the outer form.

What of this is by design? Can we rely on feature (a) staying? What is the recommended communication mechanism for direction (b)? Is it `instance.root.getComponent(...).setValue(...)` as mentioned [here](https://github.com/formio/formio/issues/674#issuecomment-434714848)?

**Comment by randallknutson** [comment]
a and b are probably by design. Events bubble up and sideways but nested forms don't receive the events of the parent form. 
c. Sounds like a further bug. The issue is probably either in the nested form component (https://github.com/formio/formio.js/blob/master/src/components/form/Form.js) or the Element.js root where events are set.

Feature (a) should be reliable. We intend this to happen and won't be changing that.

We have a lot of customers that have started to do the instance.root.getComponent...setValue method but we think that this is fundamentally flawed. One of the design architecture decisions of our system is that components are responsible for their own values. That means if component A changes, it doesn't change component B. Component B gets notified that Component A was changed and can change itself as a result. Depending on events and component changes is the best way to go.

**Comment by franke-mc** [comment]
Ok, I see. But to me, this sounds like a contradiction. Let's say
- the parent form FP contains Component A and a 'form' component S with nested form FS,
- the nested form FS contains Component B, and
- B's options depend on the context, part of which is the value of A.

Following your design, S can observe changes in A. And initially, S can set a default value for FS, thus allowing B to configure itself as needed. But once initialized, how can S cause B to update itself, and how can S share with B the new context information that resulted from a changed value of A? As I understand, neither events nor setValue() are intended to be used to directly communicate from A to B, but maybe S can somehow inject this new information into FS so that B can pick it up there?
