### ISSUE TITLE
Data Lost in select fields on submission edit

### ISSUE THREAD

**Issue by CyrilHurtado** [formio/formio.js#205]
When I load a submission using the embed way : 
https://unpkg.com/formiojs@latest/dist/formio.embed.js?src=myurl/form/{formid}/edit

The form is loaded with the submission datas in it. 
If I submit without changing anything, the datas in the select fields are lost in the submission.
If I change the value of a select field its value is kept on the submit.
All others values of other kind of fields are kept anyway.

Can Someone help me or have already see this behavior ?

**Comment by andrewjfoster** [comment]
I can confirm that this is an issue with all libraries based on formio.js.    that being react-formio, angular-formio.     ng-formio is fine.   Also I've noticed that it happens with the grid component and select control.    As you add new rows (even on a new submission) it will clear the value in the select on other rows at random.   It appears to be related to resource based data source for the select.    It tries to set the value before it has retrieved the items.   When adding a new row in a grid with a select it will rebuild all rows in the grid and try and set the value of each rows select again but it may still be getting the select item data.   The same can happen when loading a previous submission on other select elements not in the grid.

**Comment by travist** [comment]
I just pushed up version 2.19.0. Please verify that this issue is fixed.
