### ISSUE TITLE
Convert Custom Components to v4

### ISSUE THREAD

**Issue by jftsaraiva** [formio/formio.js#2057]
Hi,

Is there any document on what needs to be done to convert custom components from v3 to v4?

Thanks

**Comment by aminmc** [comment]
Hi @jftsaraiva 

The [wiki](https://github.com/formio/formio.js/wiki/Custom-Components-API) page provides guidance also there is a [sample project](https://github.com/formio/module-example).

Hope this helps.

**Comment by jftsaraiva** [comment]
Hi @aminmc 

This helps to create new custom components for v4, not so much in conversion. 
I was looking for something more like: a list of removed classes and methods statements like: _use render() instead of build()_, ...

but tkanks anyway. I'll dig through the code.

**Comment by travist** [comment]
Closed due to inactivity.
