### ISSUE TITLE
[BUG] Select Component default dataType 'auto' issues with pre 4.X component schema

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#2060]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version:
- Formio.js version: 4.7.7
- Frontend framework: Vue.js, vanilla JS
- Browser: Chrome
- Browser version: 78

## Steps to Reproduce
1. Build a form with formio.js@3 (component schema will not have dataType property) with a select component with numeric data values as string:

```json
{
  "type": "form",
  "display": "form",
  "components": [{
    "type": "select",
    "label": "Month",
    "key": "month",
    "data": {
     "values": [
        { "value": "01", "label": "Jan"},
        { "value": "02", "label": "Feb" },
        ...
      ]
    },
    "dataSrc": "values"
  }]
}
```

2. Create a submission for that form

```json
"data": {
  "month": "02"
}
```

3. Render the form using formio.js@latest (4.4.7)

4. Pass on the submission object created in (2) to the form instance

## Expected behavior

The updated submission object should be the same as original.

## Observed behavior

The updated submission changes the data type to number as dataType fallbacks to auto, and the component's value is a valid numeric string so it is casts as a number, chaning the original property data type.

## Example
See https://jsfiddle.net/airarrazaval/u4wkphy5/

**Comment by airarrazaval** [comment]
The data type check is done in the normalizeValue function:

https://github.com/formio/formio.js/blob/85d65590c23299b9da5cb1ab2dd5c8e66956a9e5/src/components/select/Select.js#L1070-L1100

For backwards compatibility, it should not assign by default the `auto` dataType.

```js
  normalizeValue(value) {
    switch (this.component.dataType) {
      case 'auto':
        if (!isNaN(parseFloat(value)) && isFinite(value)) {
          value = +value;
        }
        if (value === 'true') {
          value = true;
        }
        if (value === 'false') {
          value = false;
        }
        break;
      case 'number':
        value = +value;
        break;
      case 'string':
        if (typeof value === 'object') {
          value = JSON.stringify(value);
        }
        else {
          value = value.toString();
        }
        break;
      case 'boolean':
        value = !!value;
        break;
    }
    return super.normalizeValue(value);
  }
```

**Comment by jhen1422** [comment]
@airarrazaval 
Thanks for the inquiry. The approach mentioned above will unfortunately not work for 4x as it will not be fully backwards compatible. The best approach we recommend is to add the data type property to your forms that you are porting from 3x that need special data type handling.
