### ISSUE TITLE
spellcheck checkbox option not available

### ISSUE THREAD

**Issue by Narsciz** [formio/formio.js#2061]
Hi there,
I was looking at the documentation to search a feature like this property:
https://help.form.io/userguide/form-components/#enable-spell-check

But i am unable to see this checkbox in my formio builder view under the display tab of my textfields.
Is it normal? is there a way to reactivate this property checkbox display?

I'm using formiojs version 3.24.1 but i tried in 4.2.10 and I have the same problem.

Thank you and please let me know if you require further details.

**Comment by jhen1422** [comment]
@Narsciz 
We have added this setting feature back into the 4.7.7 of our builder. Please try that version for the 'Spell Check' setting which will be included in the textfield and text area component settings.

**Comment by Narsciz** [comment]
Ok thanks!
