### ISSUE TITLE
Use FileService and injecting it into the options for formio

### ISSUE THREAD

**Issue by dcoevoet51** [formio/formio.js#2063]
Hello, 

You closed this issue without answering the user when he was asking for an example: https://github.com/formio/formio.js/issues/1101

I am in the same case, so could you please give an example of using FileService and injecting it into the options for formio ?

Thanks by advance

**Comment by aminmc** [comment]
hi @dcoevoet51 , apologies I must have accidentally closed the issue.

so I have something like:

```js
class FileService {
  async uploadFile(storage, file, fileName, dir, evt, url, options) {
  //do something
 }
 async deleteFile(fileInfo) {
 //do something
}
 async downloadFile(fileInfo, options) {
}
}
```

I then do this when building the Form:
```js
options={
                  {
                   
                      fileService: new FileService()
                  }}/>
```

**Comment by dcoevoet51** [comment]
Thanks a lot for your answer, it will help me a lot!

**Comment by PurpleDuckMedia** [comment]
Sorry but have been searching the documentation and could not find an answer how do we set the options on the form. We are currently using portal.form.io to build the form JSON.

**Comment by randallknutson** [comment]
The file component will automatically set the values on the submission when a file is uploaded. When a file service is selected for a component it will use that service to upload the file and whatever is returned from uploadFile will be set as the value.

**Comment by PurpleDuckMedia** [comment]
Sorry Randal, but still don't understand how the options are set within a form. We do all our creation of the forms on the online portal.form.io and the upload control doesn't appear to have anywhere to set the options?

![FileUpload](https://user-images.githubusercontent.com/28952958/72163218-52d7d980-33bb-11ea-96fa-d9a404d3a370.PNG)

Or is it not done per form?
