### ISSUE TITLE
[BUG] Conditional dependent on hidden checkbox is broken

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2067]
## Environment
- next.form.io current

## Steps to Reproduce
0. create a form on next.form.io.
1. add a hidden text field 'text' with custom default value 'foo'
2. add a hidden checkbox 'flag' with calculated value (data.text === 'foo')
3. turn OFF 'clear value when hidden' on both hidden components created above
3. add a number field 'number' with visibility conditional on 'data.flag'

## Expected behavior
- 'text' is 'foo', 'flag' is true, and 'number' is visible

## Observed behavior
- 'text' is 'foo', 'flag' is assigned true, but 'number' does not see that and is not visible

## Example
See [this JSFiddle](https://jsfiddle.net/franke_mc/tznoh3sk/66) or [this form](https://api.form.io/project/5dd3ca7afcf37f3bf6fa513b/form/5dd3ca998b6323e0d941a192/) on form.io

Debug log in JS console:

> text :=  foo
> number: data.flag =  false
> number.show :=  false
> flag :=  true
> number: data.flag =  false
> number.show :=  false
> number: data.flag =  false
> number.show :=  false
> flag :=  true
> number: data.flag =  false
> number.show :=  false
> flag :=  true
> number: data.flag =  false
> number.show :=  false

Note: The example above works fine when then 'flag' checkbox is not hidden. In that case, the log reads:
> text :=  foo
> number: data.flag =  false
> number.show :=  false
> flag :=  true
> number: data.flag =  true
> number.show :=  true
> number: data.flag =  true
> number.show :=  true
> number: data.flag =  true
> number.show :=  true
> flag :=  true
> number: data.flag =  true
> number.show :=  true
> number: data.flag =  true
> number.show :=  true
> flag :=  true
> number: data.flag =  true
> number.show :=  true
> number: data.flag =  true
> number.show :=  true

**Comment by jhen1422** [comment]
@franke-mc 
If you set the conditions for the number to display when the checkbox flag is true instead of 'undefined' the number should display as expected.

**Comment by franke-mc** [comment]
@jhen1422: Sorry, I can't follow. The customConditional code in the example form is:
```
console.debug('number: data.flag = ',data.flag);
if (data.flag !== undefined) {
  show = !!data.flag;
  console.debug('number.show := ',show);
}
```
What should it be instead?

**Comment by jhen1422** [comment]
@franke-mc 
Try this bit of code

console.debug('number: data.flag = ',data.flag);
if (data.flag == true) {
  show = !!data.flag;
  console.debug('number.show := ',show);
}

**Comment by franke-mc** [comment]
@jhen1422 : That *does* prevent the number field from being hidden, but at the cost of *never* being able to hide it, rendering the example useless: Using the code you suggested I have changed the text from 'bar' to 'foo', now the 'flag' evaluates to false, but the 'number' field is still displayed as number.show is never assigned to false:
> text :=  bar
> number: data.flag =  false
> flag :=  false
> number: data.flag =  false  (3 repeats)
> flag :=  false
> number: data.flag =  false  (2 repeats)
> flag :=  false
> number: data.flag =  false  (2 repeats)

**Comment by franke-mc** [comment]
By the way: this problem is specific to the Checkbox component used as an intermediate value store. Using a Text Field instead of a Checkbox component works as expected, e.g. in [this form](https://api.form.io/project/5dd3ca7afcf37f3bf6fa513b/form/5dd4329060326e66a00d5c6f).

**Comment by franke-mc** [comment]
@jhen1422 : May I ask you to consider reopening this issue, please?

**Comment by travist** [comment]
@jhen1422 please add this to our development backlog.

**Comment by franke-mc** [comment]
Added JSFiddle: https://jsfiddle.net/franke_mc/tznoh3sk/63

**Comment by travist** [comment]
Thanks @franke-mc. We did add this to our backlog, but it looks like it may not make its way up to the top of anyones list until after the new year. We will let you know if that changes, so it we need this resolved soon, then we may ask the community to take a look.

**Comment by franke-mc** [comment]
@travist: Ok. I took a look and this is what's happening in the Checkbox component:
- During [`attach(element)`](https://github.com/formio/formio.js/blob/master/src/components/checkbox/Checkbox.js#L83), `this.refs.input` is 
  - `NodeList[ input.form-check-input ]` when the checkbox is visible, but 
  - an empty `NodeList[]` when the checkbox is hidden.
- As a consequence, `this.input = this.refs.input[0]` is set to undefined when the checkbox is hidden.
- Later on, in [`calculateComponentValue()`](https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L2120), an attempt is made to assign the calculated new value `true` via [`this.setValue()`](https://github.com/formio/formio.js/blob/master/src/components/checkbox/Checkbox.js#L184), which in turn calls [`this.setCheckedState()`](https://github.com/formio/formio.js/blob/master/src/components/checkbox/Checkbox.js#L150) which returns early because of `!this.input`.
- Back in `setValue()`, the subsequent `this.updateValue()` call is then skipped; instead, `false` is returned in the hidden case.
- Finally, back in `calculateComponentValue()`, both `changed` and `this.calculatedValue = this.dataValue` end up being `false` in the hidden case, while they should both be `true` as in the visible case.

So, maybe in `setValue()`, `updateValue()` should not be skipped even though `setCheckedState() === undefined`?  Or should the `this.refs.input` NodeList be non-empty even though the checkbox is hidden (but without `clearOnHide`)?

**Comment by franke-mc** [comment]
It seems that adding `... || !this.component.clearOnHide` to [the condition that allows calling `updateValue()`](https://github.com/formio/formio.js/blob/master/src/components/checkbox/Checkbox.js#L184) fixes this bug. Not sure if that's the right thing (tm)...
