### ISSUE TITLE
[BUG] DataGrid  the name of the add new line button does not change by default

### ISSUE THREAD

**Issue by AndreyOsipkov** [formio/formio.js#2076]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
    - Version: the last
- Formio.js version: the last
- Browser: Browser: Chrome / Firefox
- Browser version:  Google Chrome 78.0.3904.108

## Steps to Reproduce
1. add component "DataGrid"
2. Add Another Text "Custom"
3. Add Another Position "Bottom"
4. add fields
5. the button for adding a new line name "Custom"
6. Add Another Position "Top"
7. the button is called "Add Another" by default, but should be "Custom"

## Example
![image](https://user-images.githubusercontent.com/34154796/69228718-2068e780-0b95-11ea-80dd-aaa740da79b7.png)
![image](https://user-images.githubusercontent.com/34154796/69229192-0bd91f00-0b96-11ea-8905-300d9900d844.png)
![image](https://user-images.githubusercontent.com/34154796/69229263-2dd2a180-0b96-11ea-8ee7-23811da4bd86.png)
![image](https://user-images.githubusercontent.com/34154796/69229324-4a6ed980-0b96-11ea-806f-5e7f53200d3a.png)

**Comment by jhen1422** [comment]
@osipkovandrey Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by travist** [comment]
I just tested this in our latest renderer version and it is working.
