### ISSUE TITLE
[BUG]   select a month on the calendar from the second click

### ISSUE THREAD

**Issue by AndreyOsipkov** [formio/formio.js#2077]
## Environment
Please provide as many details as you can:

Hosting type
  - [x] Form.io
    - Version: the last
- Formio.js version: the last
- Browser: Browser: Chrome / Firefox
- Browser version:  Google Chrome 78.0.3904.108

## Steps to Reproduce
1. add component date/time
2. click on the calendar icon the calendar drops out
3. click redraw a month, crosses
4. click on the field, the calendar falls out
5. click to change the month, does not click, only from the second click

## Example
![ezgif-1-83bf793004fe](https://user-images.githubusercontent.com/34154796/69234807-1a790380-0ba1-11ea-8318-505b2f2eb752.gif)

**Comment by jhen1422** [comment]
@osipkovandrey 
Can you give us a more detailed report on the issue here? We're not experiencing any issues on the calendar redraw.
Thanks!

**Comment by osipkovandrey** [comment]
you need to click on the field itself, not the calendar icon, and then try to select another month as on the gif above

**Comment by wag110894** [comment]
@osipkovandrey 

We are still not seeing this issue in the formio.js builder or using our Next Portal, which is using our 4x Core Renderer. Could you provide any more details that could help us replicate the issue?

Thanks!

**Comment by osipkovandrey** [comment]
![ezgif-1-da60aa8262fe](https://user-images.githubusercontent.com/34154796/69416563-f3990980-0d27-11ea-896c-03f17b11ed70.gif)

a mouse click is indicated by a red circle. pay attention to the name of the month

**Comment by jhen1422** [comment]
@osipkovandrey 
Thank you for the video. That helped us replicate the issue. We've created a ticket in our 4x branch and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
@AndreyOsipkov 

Thank you for your patience while we worked on getting this issue resolved. This issue has been resolved. You can see the fix on the latest version of formio.js (4.11.2).

Thank you.
