### ISSUE TITLE
Does formio.js support Salesforce Lightning Web Component Framework?

### ISSUE THREAD

**Issue by sureshkumarsg21** [formio/formio.js#2079]
Hi Team,

I'm working on a prototype to quickly create forms or surveys and get it embeded in Salesforce application. I tried to use Lightning Web Component to embed forms created through formio but didn't work and it was failing.

Can you guide me if it would work?

**Comment by randallknutson** [comment]
Our form renderer is standard javascript and html. We haven't investigated LWC yet but it may work in it. If this is important, you can contact our support to have us investigate if and how we can support LWC. You can contact them at support@form.io

**Comment by SriLho** [comment]
I have just tried to create a custom form.io component that uses simple web component and that does not seem to be picked up too. 

Can you point me on which area of the code is actually doing the rendering bit or give me some clues around. May be i can help you with some time to debug this issue further.

**Comment by randallknutson** [comment]
The base component for all components and forms is the Component.js file in src/components/_classes/component/Component.js. In there is a render and attach functions. Those are overridden by other components and are used to do the html render and the javascript attach to the resulting dom elements. This is where to look for what is going on.

**Comment by randallknutson** [comment]
More information is here: https://github.com/formio/formio.js/wiki/Templates-API
