### ISSUE TITLE
[BUG] Editing a  select having multiple: true, lazyLoad: true does not update the submission if a value is removed using the 'x' instead of popping up the list.

### ISSUE THREAD

**Issue by gridanjbf** [formio/formio.js#2081]
Editing a  select having multiple: true, lazyLoad: true does not update the submission if a value is removed using the 'x' instead of popping up the list.

## Environment

- Hosting type
  - [x] Local deployment
- Formio.js version: 4.7.3
- Frontend framework: reactjs
- React Version: 16.11.0
- react-formio-version: 4.2.3
- Browser: chrome on Ubuntu 18.04
- Browser version: 78.0.3904.97

## Steps to Reproduce

1. create a select with multiple: true, lazyLoad: true
2. select more than one value
3. submit

- at this point everything works fine

4. edit the select removing one of the value clicking on the "x" _without_ opening the list
5. **the submitted data do not change**

## Expected behavior

The value is removed from the submission

## Observed behavior

The submission (event.data) does not change.

## Example

```json
{
    "label": "Somelabel",
    "hideLabel": false,
    "mask": false,
    "tableView": true,
    "type": "select",
    "input": true,
    "key": "somekey",
    "defaultValue": "",
    "selectValues": "smt.something",
    "lazyLoad": false,
    "multiple": true,
    "data": {
      "url": "http://anApiURLtoFetchValues",
      "headers": [
        {
          "key": "someKey",
          "value": "SomeValue"
        }
      ],
      "values": []
    },
    "dataSrc": "url",
    "template": "<span>{{ item.someAttribute }}</span>",
    "disableLimit": false
```

**Comment by wag110894** [comment]
Thanks for reaching out!

We are unable to replicate this issue on our side as the submission is updating when you click the 'x'.

Here is an embedded form of this working: https://ggtrgfuzoeijwju.form.io/select

Hope that this helps.

Thanks!

**Comment by travist** [comment]
Closed due to inactivity
