### ISSUE TITLE
[Question] Is there a possibility to add common functions for validations?

### ISSUE THREAD

**Issue by jerocon** [formio/formio.js#2083]
Hi,

It is necessary to create the definition of functions for each case of field validation.

Just as there is the possibility of making calls to `FormioUtils`, would it be possible to make calls to a repository of common functions created by us?

For example, in the javascript validation box, write something like

`CustomCommonsFuncions.myCommonFunction();`

The same goes for Field Logic triggers.

**Comment by randallknutson** [comment]
This is a great question! We have recently developed a module system for formio.js which allows adding functionality to lots of parts of the system. Currently it only works with components, templates, plugins and things like that but I could see it adding additional validators and field logic triggers. This would make it easy for you to provide a module that would add additional capabilities as you describe. This is probably going to be a few months before it is ready though.

**Comment by franke-mc** [comment]
@jerocon: Try `window.MyUtils = MyUtils` on startup. MyUtils.foo() is then directly available in each and every custom JS. Works great if you ask me.

**Comment by jerocon** [comment]
@franke-mc, the solution you have proposed works great.

Thank you very much!!

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
