### ISSUE TITLE
[BUG] loadForm not working using ES6

### ISSUE THREAD

**Issue by rmillener** [formio/formio.js#2084]
- Hosting type 
  - [x] Form.io
- Formio.js version:  4.7.8
- Frontend framework: N/A
- Browser: Chrome 
- Browser version: 78

The ES6 syntax of formio.loadForm as provided in the documentation is not working

## Expected behavior
The definition is loaded.

## Observed behavior
The definition isn't loaded.

## Example
https://codesandbox.io/s/infallible-banzai-dhxfd

```
import { Formio } from 'formiojs';
let formio = new Formio('https://examples.form.io/example');
formio.loadForm((form) => {
  console.log(form);
});
```

**Comment by aiwebb** [comment]
@rmillener, what syntax issue are you encountering?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
