### ISSUE TITLE
[BUG] "Clear value when hidden" = clearOnHide does not work

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2091]
This is very similar to issue https://github.com/formio/formio.js/issues/245 , but can be observed with simple conditionals, too: `"clearOnHide": true` does not ensure that the value is cleared when the component is hidden dynamically.  (It is cleared when the form is submitted, though.)
Adding redraw-on-the-field-that-triggers-the-hiding does not help.

### Steps to reproduce:
On next.form.io, using [this form](https://api.form.io/project/5dd3ca7afcf37f3bf6fa513b/form/5dd6c3cf22f1e069d17097b9):
1. enter `foo` in the text field to make the other components visible
2. check the checkbox, enter a number in the number field, and select a radio option
3. change the text field so that the other components are hidden
4. change the text field back to `foo` so that the other components become visible again

### Expected behavior:
the checkbox is clear, and the number field is empty, none of the radio options are selected

### Observed behavior:
the checkbox is checked, and the number field and the radio still contain the values from before

**Comment by randallknutson** [comment]
This is definitely not correct. It should reset when hidden and shown again. We'll add this to get fixed.

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/2096

**Comment by travist** [comment]
You can do this by unchecking "Clear on hide" and then checking "Client" persistence. This will make it so the value is not cleared, sent to the server, but will not be saved.

**Comment by dayalubana10** [comment]
hey @travist I have been using the formio portal to build couple of pdf forms, and there is a strange behavior with select component. I m using conditional logic section for a component to show/hide a dropdown/select field depending upon the checked state of a checkbox. Under the data tab for this dropdown component, I have unchecked the option "Clear Value When Hidden" yet the options for this dropdown are cleared when hiding the dropdown and showing back the dropdown with the help of the checkbox.

**Comment by daneformio** [comment]
@dayalubana10 Can you provide a JSFiddle example of this issue?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
