### ISSUE TITLE
How to translate file component error message?

### ISSUE THREAD

**Issue by SmithXiong** [formio/formio.js#2097]
I want translate file component error message ,
![image](https://user-images.githubusercontent.com/18414430/69405759-7d060700-0d3b-11ea-8c2d-02afec8097bb.png)

like this  
minWords: '{{field}} must have more than {{length}} words.',
maxWords: '{{field}} must have less than {{length}} words.',
https://github.com/formio/formio.js/blob/58b094d50e871d2cfe66ad1e180343d4f87a608a/src/i18n.js#L22
how should i do?

**Comment by aiwebb** [comment]
@SmithXiong, documentation on translation is available here:

https://help.form.io/tutorials/walkthroughs/translations/
https://help.form.io/tutorials/walkthroughs/resource/

**Comment by randallknutson** [comment]
https://github.com/formio/formio.js/pull/2098

**Comment by randallknutson** [comment]
Pull request should fix this missing translation handlers.

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated because it fixed. Please re-open if it is still relevant for you. Thank you for your contribution!

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
