### ISSUE TITLE
[BUG] Conditional not working when property name contains a period

### ISSUE THREAD

**Issue by cymen** [formio/formio.js#2105]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: latest (formiojs v4.7.8)
- Formio.js version: latest (formiojs v4.7.8)
- Frontend framework: None (using formio.js from CDN)
- Browser: Chrome
- Browser version: 78.0.3904.97

## Steps to Reproduce
1. Create a radio button input with values Yes (value: yes) and No (value: no) and property name `something.question`
2. Add another input and set it to conditionally appear when `something.question` is `yes`
3. Load form and observe the conditional input does not appear when clicking Yes on `something.question`

## Expected behavior

The conditional input to appear.

## Observed behavior

The conditional input does not appear.

## Example

Working on form.io:

https://formview.io/#/udhkdmwfegsesuy/test

Not working off of form.io:

https://gist.github.com/cymen/7a21217f7df9b35c243a0a1165126e29

Or:

```html
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
    <script src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>
    <script type="text/javascript">
      window.onload = function() {
        Formio.icons = 'fontawesome';
        Formio.createForm(document.getElementById('formio'), 'https://api.form.io/udhkdmwfegsesuy/test');
      };
    </script>
  </head>
  <body>
    <div id="formio"></div>
  </body>
</html>
```

**Comment by cymen** [comment]
I forgot to mention it is of course easy to work around this with Conditional -> Advanced Conditional > JavaScript.

**Comment by jhen1422** [comment]
@cymen Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
@cymen Thanks for your patience. This issue has been resolved. You can use our latest formio.js version 4.11.1.
