### ISSUE TITLE
[BUG] Hidden field under select box

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2108]
## Environment
Please provide as many details as you can:

- Hosting type
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.7.8
- Frontend framework: React
- Browser: Chrome & Edge

## Steps to Reproduce
1. Add a select box
2. view the rendered form
3. select just below the text box and type some text then hit enter.

## Expected behavior
1. Should be no box to enter data in

## Observed behavior
1. The entered text appears in the select box as a value, which can be submitted

```js
<input type="text"
       class="formio-select-autocomplete-input"
       ref="autocompleteInput"
       {% if (ctx.input.attr.autocomplete) { %}
       autocomplete="{{ctx.input.attr.autocomplete}}"
       {% } %}
       tabindex="-1"
/>
```

Looking at the template it would appear the hidden box is actually the formio-select-autocomplete-input box. Not sure what the purpose of this box is ?

Thanks

Mark, @aminmc

**Comment by randallknutson** [comment]
This had something to do with accessibility and tabbing. I can't remember exactly what it is for but it was needed. You should be able to just hide it without consequence.

**Comment by pixie79** [comment]
Thanks :)
