### ISSUE TITLE
[BUG]  Cannot render form to edit it using Formbuilder

### ISSUE THREAD

**Issue by harshitdkanodia** [formio/formio.js#2109]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.7.7
- Frontend framework: React.js
- Browser: Chrome / Safari / Edge
- Browser version: All versions

## Steps to Reproduce
1. Save a form schema 
2. try to edit it using this 
 Formio.builder(document.getElementById('builder'),formSchema,{}).then((builder)=>{
  }); 

## Expected behavior
Should show a form that can be edited
## Observed behavior
Forms appears for a brief second and then disappears
## Example

For code or form JSON, please enclose in a code block:

```js
 Formio.builder(document.getElementById('builder'),form,{}).then((builder)=>{
            this._builder = builder;
            this._builder.render();
            this._builder.on('error',(err)=>{
                print(err)
            });

        });
```

**Comment by aiwebb** [comment]
@harshitdkanodia, could you add a JSFiddle to demonstrate with an example form?

**Comment by harshitdkanodia** [comment]
> @harshitdkanodia, could you add a JSFiddle to demonstrate with an example form?

I am sorry i am not able to get Form builder to work with JSFiddle, I only see a white screen..

**Comment by harshitdkanodia** [comment]
Hello, I was able to solve this issue by updating library to 4.8.0-beta.1 via npm.
I was able to render a new form using Formio.builder(document.getElementById('builder'),formSchema,{});
