### ISSUE TITLE
Signature component render fails on CRA apps

### ISSUE THREAD

**Issue by josefernand** [formio/formio.js#211]
Yesterday I found a problem in the signature component on a create-react-app application. The component does not render and stops the form rendering process so the form is shown broken. 
Doing some research, I found this `signature_pad` issue related to the new webpack2 export/import process: https://github.com/szimek/signature_pad/issues/257
The problem seems to be fixed pointing the `signature_pad` import to the `.js` file in the `src/components/signature/Signature.js` component. 
```
import SignaturePad from 'signature_pad/dist/signature_pad.js';
```
I have this tested on my fork and it works. Let me know and I will send the PR if you want.

**Comment by travist** [comment]
Fixed in 2.19.3 release. Thanks!
