### ISSUE TITLE
[4.x] Interpolate component labels?

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2117]
Would it be possible to allow templates for field labels, too? Or is it by design that this feature works in tooltips and html element contents, but not in labels?

**Comment by aiwebb** [comment]
I don't think there's any design reason that it's not available on field labels, but it's not on our roadmap to my knowledge. Seems like it would be straightforward - we'd welcome a PR for it.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
