### ISSUE TITLE
[BUG]  field value change after submission

### ISSUE THREAD

**Issue by AndreyOsipkov** [formio/formio.js#2118]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
    -  angular-formio - 4.2.0
- Formio.js version: ~4.7.0
Browser: Browser: Chrome / Firefox
Browser version: Google Chrome 78.0.3904.108

## Steps to Reproduce
1. we use the setting in the component "Data - Calculated Value - JavaScript"
2. call submit form
3. the code that we indicated  "Data - Calculated Value - JavaScript" not called

## Expected behavior
the field in which the code("Data - Calculated Value - JavaScrip") is registered is not called after the submit form, although the field was not filled
## Observed behavior
if the field is untouched, called submit form,  code(Data - Calculated Value - JavaScrip")) must be executed

in the method "onSubmissionError"(node_modules/formiojs/Webform.js) function is called "setPristine(false)", setting pristine for each component the form "pristine = false". 
Further, when calculating the value of the component, it is called "calculateComponentValue"(node_modules/formiojs/components/_classes/component/Component.js) where the condition is triggered `if (allowOverride && !this.pristine) {
        return false;
      }` , not allowing you to call the code specified ("Data - Calculated Value - JavaScrip") although the field was not touched

## Example
![k2r4h-b4t20](https://user-images.githubusercontent.com/34154796/69722212-99cd8080-1127-11ea-9d13-bed5e8d1a0c2.gif)

formiojs/components/_classes/component/Component.js
```js
 key: "calculateComponentValue",
    value: function calculateComponentValue(data, flags, row) {
......

      if (allowOverride && !this.pristine) {
        return false;
      }

.........

      var calculatedValue = this.evaluate(this.component.calculateValue, {
        value: dataValue,
        data: data,
        row: row || this.data
      }, 'value'); // If this is the firstPass, and the dataValue is different than to the calculatedValue.

.......
    }
```
formiojs/Webform.js
```js
key: "onSubmissionError",
    value: function onSubmissionError(error) {
..........
      this.setPristine(false); // Allow for silent cancellations (no error message, no submit button error state)

    ..........
    }
```

**Comment by jhen1422** [comment]
@osipkovandrey 
We appreciate the report however we are having problems replicating the issue. For better clarity on our end, could you provide more detail on the test steps as well as provide a jsfiddle showing the issue?

**Comment by osipkovandrey** [comment]
made a case at your stand (https://formio.github.io/formio.js/app/builder)

**Comment by jhen1422** [comment]
@osipkovandrey 
Thank you for the additional information. We've added this ticket to our 4x backlog and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
@AndreyOsipkov 

We wanted to let you know that this issue is resolved. You can use our latest version 4.11.2.

Thank you for using Form.io!
