### ISSUE TITLE
Custom components are placed in Datagrid components,builder.data not have key

### ISSUE THREAD

**Issue by sssxiaocainiao** [formio/formio.js#2123]
![image](https://user-images.githubusercontent.com/26619935/69854983-6d4f6b00-12c5-11ea-9a6b-1e23c04c99e8.png)
![image](https://user-images.githubusercontent.com/26619935/69855005-79d3c380-12c5-11ea-875a-5200daf02b88.png)

I use V3

**Comment by travist** [comment]
Please share a JSFiddle showing the problem.

**Comment by sssxiaocainiao** [comment]
已解决
