### ISSUE TITLE
[BUG] Select Component not setting correct default value when multiple is true

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#2127]
## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.8.0-beta.2
- Frontend framework: any
- Browser: any
- Browser version:

## Steps to Reproduce
1. Create a form with Select Component 
2. Set Select Component mutliple flag to true
3. Submit an empty submission

## Expected behavior

Default value for the select component should be an empty array

## Observed behavior

Default value for the select component is an empty string, thus triggering nonarray validation error.

## Example

https://jsfiddle.net/airarrazaval/u4wkphy5/

**Comment by airarrazaval** [comment]
Pull Request https://jsfiddle.net/airarrazaval/u4wkphy5/ created to address this issue

**Comment by travist** [comment]
Merged with latest. Thanks @airarrazaval!
