### ISSUE TITLE
[BUG] Wizard not evaluating calculateValue

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#2128]
## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.8.0-beta.2
- Frontend framework: any
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Create a wizard
2. Add the following component:
```json
{
  "type": "textfield",
  "key": "text",
  "calculateValue": "value = 'text'",
}
```
3. Add the following component:
```json
{
  "type": "textfield",
  "key": "required",
  "calculateValue": "value = 'required'",
  "validate": {
    "required": true
  }
}
```
4. Render the form

## Expected behavior

`data.text` should be set to `"text"` and `data.required` should be set to `"required"`. No validation error should be triggered.

## Observed behavior

Both `data.text` and `data.required` set to `""`. Also, a required validation error is triggered for the `required` component.

## Example

https://jsfiddle.net/airarrazaval/6rjocawf

**Comment by airarrazaval** [comment]
Further looking at `Wizard.js` it performs the following check in `checkData` function:

https://github.com/formio/formio.js/blob/46b83b259635a03313f83ff9a548440e1cf9f2be/src/Wizard.js#L426-L429

Here it performs the validation check before the data check.  If validation fails then the data is not calculated.  The order should be the other way around.

**Comment by airarrazaval** [comment]
Created Pull Request https://github.com/formio/formio.js/pull/2129

**Comment by travist** [comment]
Merged in with the latest. Thanks @airarrazaval!
