### ISSUE TITLE
[BUG] FormioUtils.getStrings fails for Edit Grid component

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#2130]
There is a typo in the `getStrings` method in form utils.

https://github.com/formio/formio.js/blob/e05679c4dfd78fac192b1e919e113e137046e3f4/src/utils/formUtils.js#L563-L572

The `this` keyword should be removed in order to fix this bug.

## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.8.0-beta.2
- Frontend framework: any
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Build a form including an Edit Grid component

```json
{
  "type": "form",
  "display": "form",
  "components": [
    {
      "type": "editgrid",
      "key": "siblings",
      "label": "Siblings",
      "tooltip": "List all your siblings",
      "components": [
        {
          "type": "textfield",
          "key": "name",
          "label": "Name",
          "placeholder": "Enter your sibling's name"
        }
      ]
    }
  ]
}
```
2. Use `FormioUtils.getStrings(form)` to retrieve all form strings

## Expected behavior

All form strings should be returned.

```json
[
  {
    "key": "siblings",
    "type": "editgrid",
    "property": "label",
    "string": "Siblings"
  },
  {
    "key": "siblings",
    "type": "editgrid",
    "property": "tooltip",
    "string": "List all your siblings"
  },
  {
    "key": "name",
    "type": "textfield",
    "property": "label",
    "string": "Name"
  },
  {
    "key": "name",
    "type": "textfield",
    "property": "placeholder",
    "string": "Enter your sibling's name"
  }
]
```

## Observed behavior

An Uncaught TypeError is thrown with the message `Cannot read property 'addAnother' of undefined`.

## Example

https://jsfiddle.net/airarrazaval/x1qd86ty/

**Comment by jhen1422** [comment]
@airarrazaval 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting this week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by travist** [comment]
@jhen1422 he just submitted a pull request and we merged it.
