### ISSUE TITLE
[BUG] File Component not opening webcam

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#2132]
Webcam activation is triggered by the toggleCameraMode click event. The component's cameraMode value is toggled, but `startVideo()` is called before triggering the redraw of the component's template, thus not finding the video canvas.

https://github.com/formio/formio.js/blob/9bb9d4a9b72e311cd71e45df1b66c493c966766d/src/components/file/File.js#L336-L345

`this.redraw()` should be placed before starting the video.

## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.8.0-beta.2
- Frontend framework: any
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Create a form with a File component and enable webcam

```json
{
  "type": "form",
  "display": "form",
  "components": [{
    "type": "file",
    "label": "Photo",
    "key": "photo",
    "image": true,
    "webcam": true,
    "webcamSize": "320",
    "storage": "base64",
    "filepattern": "image/*",
  }]
}
```

2. Render the form and click on Camera

## Expected behavior

Video canvas should render on click.

## Observed behavior

Warning message is triggered saying `Video player not found in template.`

## Example

https://jsfiddle.net/airarrazaval/mznpd4yq/

**Comment by airarrazaval** [comment]
After applying the fix, closing the webcam does not stops the video streaming.

**Comment by airarrazaval** [comment]
Created pull request https://github.com/formio/formio.js/pull/2133 fixing both webcam not opening and video stream not stopping.

**Comment by travist** [comment]
Merged in latest.
