### ISSUE TITLE
[QUESTION] about FORM_API_URL/{FORM_NAME}/storage/s3

### ISSUE THREAD

**Issue by sukrit-adhikari** [formio/formio.js#2138]
There is a standard API in form io.

**https://{FORM_IO_URL}/{FORM_NAME}/storage/s3?bucket={BUCKET_NAME}&key={FILE_PATH}**

to get signed URL for files stored in S3.

We are using this as a production solution. Will this API be supported long term ? We need a confirmation. Thank You in advance!!

**Comment by randallknutson** [comment]
The /storage/s3 endpoint will be supported in our enterprise server moving forward. We have many customers using it and have no plans of removing it.

**Comment by sukrit-adhikari** [comment]
Thanks for confirming 👍
