### ISSUE TITLE
[BUG] In Datagrid, in form READONLY mode, data is not rendering in first row for textarea component

### ISSUE THREAD

**Issue by imshivamchauhan** [formio/formio.js#2139]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: angular-formio
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Take a textarea inside a datagrid component.
2. bind data using submission on form load with READONLY true for full form.
3. in textarea data is not binding in first row only, not even in inspect element.

## Expected behavior
data should display in all fields, all rows in Readonly mode
## Observed behavior
data in first row in textarea is not displaying in Readonly mode

**Comment by imshivamchauhan** [comment]
see screenshots  below:
when in readonly=false;
![image](https://user-images.githubusercontent.com/33184564/70038769-d2190700-15de-11ea-9aa1-cb1d923c57b4.png)

when readonly=true;
![image](https://user-images.githubusercontent.com/33184564/70038852-f674e380-15de-11ea-94cb-225b97cd0988.png)

**Comment by jhen1422** [comment]
@imshivamchauhan 
Thank you for the report. We we're able to replicate this issue on our end as well. I have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
Hello @imshivamchauhan 

Thank you for your patience while we worked on getting this issue resolved.

This issue has been fixed in version 4.8.0-rc3 of formio.js.

Thank you for using Form.io.

**Comment by LukasR97** [comment]
I have the same problem in 4.15.0-rc.18, the first field in edit grid readonly mode loads just fine (only in chrome) in mozilla it doesn't. 

If you refresh the page in chrome it's doesn't render it anymore...  frustrating...
