### ISSUE TITLE
Disable Drag and/or Drop for certain components in Formio.js v4

### ISSUE THREAD

**Issue by marcus-at-localhost** [formio/formio.js#2142]
Hi,
I'm using the hosted (cdn) version of latest formio.full.min.js (4.8.x) and wonder if there is an official (build in) way, to disable drag and drop for fieldset elements.

Right now I'm setting `no-drop`and `no-drag` classes after builder is initialized, but those classes are removed, when I rearrange or modify those components in a fieldset and so I have to reattach them on certain events

```js
let formBuilderDisableDragDrop = function(){
	// using https://github.com/kenwheeler/cash instead of jquery
	$("[ref='webform']>.drag-container").addClass('no-drop');
	$("[ref='webform']>.builder-components>[ref='dragComponent']").addClass('no-drag');
}

Formio.builder(document.getElementById('formio'), components, {}).then(function(form) {

  /**
	 * Disable Drag&Drop on load,
	 * and on certain events, when those `no-drag|drop` are getting removed
	 */
  formBuilderDisableDragDrop();

  _.forEach(['render','change','addComponent'], function(value){
    form.on(value, function() {
      formBuilderDisableDragDrop()
    });
  });
});
```

https://jsfiddle.net/emzos5d4/

**Comment by randallknutson** [comment]
I don't think we currently have a way of disabling certain field types from being editable or draggable. If you wanted to make some modifications to allow this we would be interested.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant
