### ISSUE TITLE
field validation error rendering does not render characters corectly

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#215]
![screen shot 2017-10-11 at 4 00 39 pm](https://user-images.githubusercontent.com/1994838/31463839-765b9482-ae9d-11e7-9326-45bb5ccefc22.png)

But it does render correctly at the top of the form.
![screen shot 2017-10-11 at 4 00 44 pm](https://user-images.githubusercontent.com/1994838/31463842-78c5a672-ae9d-11e7-82a1-ff19437be58c.png)

**Comment by jhen1422** [comment]
Closing - outdated issue
