### ISSUE TITLE
[BUG] Component id is always regenerated after a change in formbuilder

### ISSUE THREAD

**Issue by Romakita** [formio/formio.js#2153]
Hello Team,

Since this the 2019-04-15 (commit "Set unique id for each component"), the component id is always regenerated. It's a problem because in our project we use REST API to generate the front-end app and we use this id to store data in db (instead of the key).

In the code  of Element.js, I found that:

```javascript
    /**
     * The ID of this component. This value is auto-generated when the component is created, but
     * can also be provided from the component.id value passed into the constructor.
     * @type {string}
     */
    this.id = FormioUtils.getRandomComponentId();
```
The comment isn't aligned with the implementation. Originally the code was that:
```javascript
/**
     * The ID of this component. This value is auto-generated when the component is created, but
     * can also be provided from the component.id value passed into the constructor.
     * @type {string}
     */
    this.id = id || FormioUtils.getRandomComponentId();
```

## Expected behavior

- [] The component should not change when the component is already created.

Thanks for your job and your framework ;)

See you 
Romain

**Comment by franke-mc** [comment]
Related: issue #1921

**Comment by Romakita** [comment]
PR https://github.com/formio/formio.js/pull/2154

**Comment by Romakita** [comment]
PR https://github.com/formio/formio.js/pull/2154

**Comment by sagargg** [comment]
some projects required persisted unique keys, it is better if we make it configurable.

**Comment by brendanbond** [comment]
I think the idea here (per [this pull request](https://github.com/formio/formio.js/pull/2154)) is that the `id` property isn't stored with the component definition and therefore should be regenerated each time the form is instantiated (unless the DOM already has an id). In other words, the `id` property is used internally by the renderer and isn't designed to be persisted anywhere else. I"m closing this as a "won't fix," although I'm curious why anyone fetching JSON from the Formio REST API or even from their own REST API can't just key into another property or store their own id.

**Comment by Romakita** [comment]
Yes I totally agree. It was a bad idea to use id for our project ^^ sorry for this mistake!

see you
