### ISSUE TITLE
Display previous submitted data

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio.js#2157]
Hi, I would like to display (on the lastl form page) in html component (not input) some data previously submitted (like a summary). How can I do that ?
Thanks for the reply,

**Comment by jhen1422** [comment]
@AudreyCb 
Hi you can utilize the Content component to display submitted data on the last page of a wizard. Here's an example to follow
https://formio.github.io/formio.js/app/examples/customwizard.html

**Comment by AudreyCb** [comment]
Thanks, this is exacttly what I was looking for.
