### ISSUE TITLE
[BUG] [4.x] Custom JS called excessively often

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2183]
Recently I noticed the number of calls to custom JS code multiply.
JSFiddle: https://jsfiddle.net/franke_mc/tznoh3sk/68/
You can see that the custom JS is called a lot more often than it used to be. Just have a look at the JS console and count the debug prints...

**Comment by travist** [comment]
Yes I can see that. I will add this to our planning.

**Comment by franke-mc** [comment]
@aiwebb: Bisection shows that this started with [your "isomorphic validator"](https://github.com/formio/formio.js/commit/3f90afc15f44e9afc31d84177fde4bb8fe69de8e).

**Comment by travist** [comment]
@franke-mc we will add this to our planning today and get it allocated... It seems like a regression so it would probably be a "high" priority.

**Comment by jhen1422** [comment]
@franke-mc This should be resolved on formio.js version 4.9.13
