### ISSUE TITLE
How to change properties of component based on other component state

### ISSUE THREAD

**Issue by parabmahesh** [formio/formio.js#2185]
I am using formio 3.22.11 version, I came across one requirement where in i have two formio component such as Currency and Select which holds available currencies in it.

I want to change currency type of currency component  based on currency selected in select component, so the currency field automatically formats based on currency selected.

![image](https://user-images.githubusercontent.com/49534106/70769927-662e5f80-1d91-11ea-8ede-751f8052735f.png)

I tried using providing Logic but did not found relevant examples of using javascript in Logic

What is best way to implement this dynamic behaviour?

**Comment by travist** [comment]
This is a new feature in our 4.x renderer which uses Logic to merge component JSON based on triggers. This will not be backported to 3.x.

**Comment by parabmahesh** [comment]
Just to elaborate more that i am not interested in merging JSON but was looking for example on how to change property of one component based on other component's change event

In my case i was interested in changing currency type of currency component based on currency selected in drop down component.

@travist any ideas? to achieve this?

**Comment by randallknutson** [comment]
As Travis mentioned, this is exactly what the Logic tab of the 4.x branch is designed to do. You can set up a trigger for other component changes and then do an action like changing a property on the component. This works really well in our 4.x renderer and builder but will not be back ported to 3.x.

**Comment by parabmahesh** [comment]
Thank you @randallknutson
