### ISSUE TITLE
[BUG] Textfield with mask has red border in Firefox because of pattern attribute

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2193]
Formiojs version: latest 4.x, e.g. 4.8.0-rc.2
Browser: Firefox (70.0.1)
- Create a form with the following component:
```
        {
            "key": "example",
            "type": "textfield",
            "input": true,
            "label": "Enter a month as MM/YYYY",
            "inputMask": "99/9999",
            "inputType": "text",
            "spellcheck": false
        }
```
- Enter e.g. "12/2020" (without the slash which is part of the mask)
- Leave the input by tabbing out of it or clicking elsewhere.
- Observe that a red border around the input field is displayed:
![textfieldMaskRedBorder](https://user-images.githubusercontent.com/46748541/70869639-5dee4400-1f8c-11ea-813d-a96c5fa937f9.png)

The problem is caused by the pattern attribute of the input element:
```
<input value="" spellcheck="false" placeholder="MM/YYYY" 
  class="form-control" type="text" name="data[example]" 
  ref="input" pattern="\d*" lang="en">
```
By editing the DOM (replacing `pattern="\d*"` with `pattern="\d\d/\d\d\d\d"`) the red border can be made to disappear.

**Comment by jhen1422** [comment]
@franke-mc I can't seem to replicate this following the example you have provided. Did we miss something here? https://share.getcloudapp.com/Jru7bO0o

**Comment by franke-mc** [comment]
@jhen1422: Which browser are you using? (I saw it in Firefox but not in Chrome.)

**Comment by wag110894** [comment]
We are able to replicate this using Firefox. We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.

**Comment by travist** [comment]
@franke-mc does it work if we change the pattern to ```[\d\/]*```?  This would make it generic enough that we could change it easily in the renderer if you can verify that it removes the red border in Fire.

**Comment by wag110894** [comment]
After retesting this item. We are not seeing this on Firefox. We were not setting this up the same on the component.

Apologies.

**Comment by franke-mc** [comment]
@travist: Yes, it does. But it needs to include all "normal" characters in the inputMask string, i.e. all except `9`, `a`, `*`.
For the MM/YYYY mask of "99/9999", both `pattern="\d\d/\d\d\d\d"` and `pattern="[\d/]*"` work well.
For the example telephone mask of "(999) 999-9999", both `pattern="[(]\d\d\d[)][ ]\d\d\d[-]\d\d\d\d"` and `pattern="[\d() -]*"` work well (but `-` can't be at arbitrary positions in the character class...).

So I guess, the easiest solution is to compute the pattern with something like:
```
function derivePatternFromInputMask(inputMask) {
  var pattern = "";
  for (i=0; i<inputMask.length; i++) {
    switch (inputMask[i]) {
      case "9": pattern += "\\d"; break;
      case "a": pattern += "[a-zA-Z]"; break;
      case "*": pattern += "[a-zA-Z\\d]"; break;
      default:  pattern += ("[" + inputMask[i] + "]");
    }
  }
  return pattern;
}
```
Examples:
```
new RegExp(derivePatternFromInputMask("(999) 999-9999")).test("(123) 456-7890");
true
new RegExp(derivePatternFromInputMask("aaa999***")).test("abc123dX9");
true
```

**Comment by franke-mc** [comment]
@wag110894: Which version of Firefox are you using? Which steps did you perform to test this?

**Comment by franke-mc** [comment]
@wag110894 , @jhen1422 : I'm still seeing this today on your https://formio.github.io/formio.js/app/builder with Renderer v4.8.0-rc.3 and Firefox 71.0 . Are you sure that this issue should stay closed?

**Comment by wag110894** [comment]
@franke-mc 

I tested using version 71.0 of firefox and just tested again using the same version v4.8.0-rc.3 and am unable to replicate. I followed the directions that you provided above.
