### ISSUE TITLE
Missing UI for array-valued "redrawOn": ["component1", "component2", ...]

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2195]
Specifying that a form component depends on multiple other components is already possible in JSON:
`"redrawOn": ["comp1", "comp2", ...]`
While processing of such array-valued "redrawOn" specifications is already implemented [in checkRefreshOn() in Component.js](https://github.com/formio/formio.js/blob/e5c5c099b4bb866f9e72b394d7a988ea9d718008/src/components/_classes/component/Component.js#L964), the form builder UI [does not seem to support this yet.](https://github.com/formio/formio.js/blob/e5c5c099b4bb866f9e72b394d7a988ea9d718008/src/components/_classes/component/editForm/Component.edit.data.js#L63)

**Comment by travist** [comment]
This may be as easy as just turning the builder element to have the ```multiple``` flag.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
