### ISSUE TITLE
[BUG] [4.x] "internal": true in form components can break "redrawOn"

### ISSUE THREAD

**Issue by franke-mc** [formio/formio.js#2197]
`redrawOn` stopped working for me between formiojs versions 4.7.7 and current pre-4.8.0 HEAD.
Is this a known issue?

**Comment by randallknutson** [comment]
I don't have any information on anything like this yet. Can you send an example?

**Comment by franke-mc** [comment]
What's the deal with `"internal": true`? When I edit the column width in my example and save the result, `"internal"; true` gets removed from the components and the breakage stops:
```
$ git diff -U0 debugRedrawOn.json
diff --git a/data/form/debugRedrawOn.json b/data/form/debugRedrawOn.json
index ebed30a..8b2a7d2 100644
--- a/data/form/debugRedrawOn.json
+++ b/data/form/debugRedrawOn.json
@@ -23 +23 @@
-    "modified": "2019-12-16T16:33:59.007Z",
+    "modified": "2019-12-16T16:42:20.688Z",
@@ -28 +28 @@
-            "tags": "",
+            "tags": [],
@@ -43 +43 @@
-                    "width": 9,
+                    "width": 3,
@@ -80 +79,0 @@
-                            "internal": true,
@@ -183 +181,0 @@
-                            "internal": true,
```

Does `"internal": true` have a legitimate purpose in saved form JSON at all?

**Comment by franke-mc** [comment]
I guess I was unlucky to use the form editor after Mon Dec 2 13:59
https://github.com/formio/formio.js/commit/e6a0b8b567392331e916c9361b21f86320e92673#diff-2a069e6d35c42be753c79c6da75dccf2
where this line was added:
```
clonedComp.internal = true;
```
but before Wed Dec 4 13:42
https://github.com/formio/formio.js/commit/fd48d12b3a0cb2603cfd20b3ee5d3ffe300279fe#diff-2a069e6d35c42be753c79c6da75dccf2
where the following line was added:
```
delete component.component.internal;`
```

Nothing to see here, move along...

**Comment by travist** [comment]
So does our form editor today erroneously put an "internal" property on the component? If so, then this is a bug that should be handled in a separate ticket maybe.

**Comment by franke-mc** [comment]
No, it doesn't. When using cc7f643de70611bb923be85f4dccc8d8f9eb7351 from Friday Dec 13 09:52, 
it *removes* any `"internal"` property on a component inside a column when it gets a chance, which is fine.
(But it also adds back lots of default values again, which is slightly annoying... this back-and-forth between default values in and out tends to completely drown out any meaningful form JSON diffs... That was issue #558 previously, which is closed. Do you want a new issue for that?)

**Comment by randallknutson** [comment]
Hi Franke,

We're still in the process of getting the form definitions to only have the overridden values saved. It is only half pushed out at the moment which is why it is causing things to go back and form depending on where you save the form. In the future it should only save the short version of the form definition, not the one with all the default values in it as well. In the most recent version does it revert back to saving the full definition with defaults again?

**Comment by franke-mc** [comment]
In columns, with https://github.com/formio/formio.js/commit/cc7f643de70611bb923be85f4dccc8d8f9eb7351 : yes, it does.
