### ISSUE TITLE
[BUG] Calling $.val(value) on SELECT element does not set selected value

### ISSUE THREAD

**Issue by HarveyCortell** [formio/formio.js#2199]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: Application: 6.8.6, Renderer: 2.38.3
- Frontend framework: Default
- Browser: Brave
- Browser version: Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a basic html page that renders a form containing a SELECT element
2. In the .then() function, jquery select any SELECT element in the form (eg $elem = $("[name='data[select]'")
3. Call the val() function on the element, passing a valid string from the list (eg $elem.val("selectOption3"))

## Expected behavior
The SELECT element should set it's selected value to the item that matches the string passed to the val() function.

## Observed behavior
The SELECT element does not update. No error is reported.

## Example
https://jsfiddle.net/HarveyCortell/n7jh25Lw/

**Comment by HarveyCortell** [comment]
If anyone has a workaround for this, I would be interested to hear about it. I have tried the following:

- Remove choices.js from form.io, as this seems to be producing the invalid html that stops val() from functioning normally
- Override render template for SELECT element. I have been able to set a template, but cannot locate enough information about the template syntax to render the select as standard HTML
- Various others calls, such as "setValue". I could not find any combination that would programmatically set the value of the SELECT element.

Personally, I think including choices.js in the standard js renderer is a mistake. UI plugins should maintain the integrity and functionality of the underlying html elements.

**Comment by randallknutson** [comment]
You shouldn't use jquery to get the dom elements to set values. You can either pass the submission object in with the value set or use (instance variable) formio.getComponent('key', formio.form.components) and then set the value on that.

**Comment by HarveyCortell** [comment]
Thanks for the reply, I feared that was the case. However, I have a jquery plugin which manipulates form values directly (it knows nothing of form.io), so I will have to rethink my solution if setting form values is not possible.

**Comment by franke-mc** [comment]
This is the utility we are using; you may find it useful, too.
```
function setValue(instance, key, val, data) {
  if (data) {
    _.set(data, key, val);
  }
  // see https://github.com/formio/formio/issues/674#issuecomment-434714848
  const component = instance.root.getComponent(key);
  return component.setValue(val);
}
```

**Comment by HarveyCortell** [comment]
This seems to be resolved in the latest version by exposing an option to set Choices JS or HTML5 as the Widget Type. Closing issue.
