### ISSUE TITLE
[BUG] Form.io not generating Valid Swagger API

### ISSUE THREAD

**Issue by romain-rhieu** [formio/formio.js#2210]
We are starting to work with Form.io API. In order to call api, we use library swagger codegen (https://github.com/swagger-api/swagger-codegen).

But it seems that the spec.json does not provide a valid swagger Json file. Even using an empty project the file gets rejected http://online.swagger.io/validator/debug?url=https://lapezheplkzsigv.form.io/spec.json

Best!

**Comment by randallknutson** [comment]
Our swagger is version 2, not 3. We would like to upgrade this at some point to the latest version and add a lot of new functionality to it. If you would like to either do this or sponsor the development of this feature you can contact support@form.io and we can work through the details.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
