### ISSUE TITLE
Disable Dates in Date/Time Component?

### ISSUE THREAD

**Issue by tbednarickSW** [formio/formio.js#2212]
Can dates be disabled in the date/time component? I found [documentation](https://flatpickr.js.org/examples/#disabling-dates) on how to do it in flatpickr, but can't find how to apply it to my form controls.

**Comment by wag110894** [comment]
Hello,

Inside the date/time component settings, you will see tabs labeled Date and Time. There are settings in both to either Enable Date Input or Enable Time Input. Both are checked at creation. This is how you can disable one or the or the other. You will also need to ensure that the Format on the Display tab is changed base on what you disable. 

I hope that this helps.

Thank you.

**Comment by tbednarick** [comment]
Thank you. 

What I'm looking for is how to disable individual days.

**Comment by randallknutson** [comment]
Unfortunately we don't expose the flatpickr option settings in our form builder edit form. We've done something similar with the select component where you can customize the choices.js options and add any customizations you want. We could do the same thing for flatpickr where there is a place to add any custom options you want and the renderer would use those when instantiating flatpickr.

Is this something you could either add in a pull request or would you like to support the development of it?

**Comment by tbednarickSW** [comment]
Hi Randall,

 

Could you give me an idea of the cost for supporting this feature?

 

Thanks,

 




	Tonya Bednarick 
Solutionwhere, Inc


 <tel:231-935-3000> 231-935-3000


 <http://solutionwhere.com> solutionwhere.com

 


 <http://www.linkedin.com/in/tonya-bednarick-b044826/> 

 <http://twitter.com/TonyaBednarick> 


 <http://solutionwhere.com/>

**Comment by airarrazaval** [comment]
> Unfortunately we don't expose the flatpickr option settings in our form builder edit form. We've done something similar with the select component where you can customize the choices.js options and add any customizations you want. We could do the same thing for flatpickr where there is a place to add any custom options you want and the renderer would use those when instantiating flatpickr.
> 
> Is this something you could either add in a pull request or would you like to support the development of it?

@randallknutson I created Pull Request https://github.com/formio/formio.js/pull/2215 adding custom options (flatpickr) for Date / Time component.

**Comment by randallknutson** [comment]
This is great! We should probably also expose that option to the edit form as well like this: https://github.com/formio/formio.js/blob/master/src/components/select/editForm/Select.edit.data.js#L587-L597

**Comment by tbednarickSW** [comment]
I'm trying to add disabled dates to the new Flatpickr options and it doesn't seem to be implemented on front end. 
https://flatpickr.js.org/examples/#disabling-dates

Any suggestions as to what I might be doing wrong?

![Calendar Form Builder](https://user-images.githubusercontent.com/54586314/75386359-8ad5a600-58af-11ea-8529-7c79b8283f3c.png)
![Calender Front End](https://user-images.githubusercontent.com/54586314/75386360-8b6e3c80-58af-11ea-86b6-52acebd03526.png)

**Comment by tbednarickSW** [comment]
I figured out my problem. I needed something like this:
{
  "dateFormat": "MM/dd/yyyy",
  "disable": [
    {
      "from": "08/31/2020",
      "to": "09/04/2020"
    },
    {
      "from": "09/07/2020",
      "to": "09/11/2020"
    },
    {
      "from": "09/14/2020",
      "to": "09/18/2020"
    }
  ]
}
