### ISSUE TITLE
[BUG] Changing projectUrl does not work

### ISSUE THREAD

**Issue by efortes** [formio/formio.js#2220]
**Problem**
We are using the formmanager for our company. All the request to form.io need to go trough our proxy domain name + path for security reasons before going live.

Our formio url **dev-xxx.form.io** will be mapped to **https://xxx.nl/consumers/formio/adapter**

The formmanager uses `/node_modules/formiojs/Formio.js` to create the back-end requests to formio.
I used the following configuration: 
```
const Formio = require('formiojs').Formio
Formio.setProjectUrl(environment.appUrl)
Formio.authUrl = environment.appUrl
```
In our angular provider we used this settings:

```
  providers: [
    FormioAuthService,
    {
      provide: FormioAppConfig,
      useValue: { appUrl: environment.appUrl, apiUrl: environment.apiUrl }
    },
    {
      provide: FormioAuthConfig,
      useValue: {
        app: {
          appUrl: environment.appUrl,
          apiUrl: environment.apiUrl
        },
        login: {
          path: `${environment.appUrl}/user/login`
        },
        register: {
          path: `${environment.appUrl}/user/register`
        }
      }
    },
```

When I set the auth and project url I expect the project url to be used as base domain name. Now many requests to the form.io are not working as expected.

**Comment by efortes** [comment]
Extra info: Many of those requests done by the formmanager are working if I temporary change one line in the `node_modules/formiojs/Formio.js` contructor (`this.projectUrl = '';` to `this.projectUrl = Formio.projectUrl || '';` ). But many still don't work. Saving a new form is one of the not working http requests.

**Comment by travist** [comment]
The FormManager uses angular-formio as its framework. We have seen it many times where there are multiple "instances" of the Formio object that could get included into the application and anytime you think you are changing settings of Formio, it is the wrong instance.  Try changing...

```js
import { Formio } from 'formiojs';
Formio.setProjectUrl(environment.appUrl)
Formio.authUrl = environment.appUrl;
```

To this...

```js
import { Formio } from 'angular-formio';
Formio.setProjectUrl(environment.appUrl)
Formio.authUrl = environment.appUrl;
```

They are both the same thing, but one is pulled in from the Angular wrapper, and the other one is from the root module (which I suspect is not the right one).

**Comment by efortes** [comment]
@travist I did what you suggested. The issues are still present. Example of one of the wrong links:

`https://XXX.nl/form?tags=common&type=form&limit=10&skip=0` should be `https://xxx.nl/consumers/formio/adapter/form?tags=common&type=form&limit=10&skip=0`.
Its getting the base domain instead of the whole path defined.

**Comment by travist** [comment]
You also need to set the base Url... like this.

```
Formio.setProjectUrl('https://xxx.nl/consumers/formio/adapter');
Formio.setBaseUrl('https://xxx.nl/consumers/formio');
```

**Comment by efortes** [comment]
Yes I already tried this. 
In the `/node_modules/formiojs/Formio.js` file I can see that the hostName is often used. It will work if a base domain is used. So if I use the same example ( one of the errors )

**https://XXX.nl**/form?tags=common&type=form&limit=10&skip=0` should be **https://xxx.nl/consumers/formio/adapter**/form?tags=common&type=form&limit=10&skip=0. 

If you look at the example you see that its skipping path **consumers/formio/adapter**. ( Some of the urls are working: GET https://xxx.nl/consumers/formio/adapter, GET  https://xxx.nl/consumers/formio/adapter/access etc )

**Comment by travist** [comment]
Ok, it seems your application must be configured differently than what we have seen before. Is the API server Open Source server or are you running on Enterprise. The suggestions I made above were assuming you were using the Enterprise server.

**Comment by efortes** [comment]
@travist we are using the enterprise version. Is this something that can be picked up?

**Comment by travist** [comment]
@efortes you mentioned you are using the Form Manager. Is this our hosted Form Manager application, or are you using the Angular Form Manager module within your own application? If it is the latter, then this may be that the AppConfig is not getting provided to the application correctly. Sorry for so many questions, it is just there are a number of different configurations that we need to figure out. If we must we can jump on a call with you to iron all these out. Contact support at form.io if you would like to go down that road.

**Comment by efortes** [comment]
@travist we are hosting the form manager application our selfs. Reason to create the bug here is that I saw something in the code that might cause the issues. I will contact support to setup a call.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
