### ISSUE TITLE
File type not part of submission

### ISSUE THREAD

**Issue by hosney** [formio/formio.js#2229]
If a file component has file types configured the selected file type is not included in the submission.

**Comment by randallknutson** [comment]
It should be included in the file object if selected. Can you give us an example form of where this is occurring?

**Comment by hosney** [comment]
Try selecting a type (e.g. Type B) in this form. The submission object does not include this information. https://jsfiddle.net/b0fejphc/

There doesn't seem to be a ref for the fileType in the code. It should probably be added in the attach method.

e.g.
```
attach(element) {
    this.loadRefs(element, {
      ...
      fileType: "multiple",
    });
    ...
    this.refs.fileType.forEach((fileType, index) => {
      this.addEventListener(fileType, 'change', (event) => {
        this.dataValue[index].fileType = this.value;
      });
    });
    ...    
}
```

**Comment by randallknutson** [comment]
I don't know where this code went but it used to exist at one point. I've created a PR to add it back. https://github.com/formio/formio.js/pull/2238

**Comment by hosney** [comment]
I think this has to be `fileType.value` instead of `this.value` here;

`this.dataValue[index].fileType = fileType.value;`
