### ISSUE TITLE
Errors when using signature component

### ISSUE THREAD

**Issue by aloisbarreras** [formio/formio.js#223]
I am using formiojs version 2.20.1 and the signature component throws a bunch of errors when trying to use it.

This is how I am rendering the form:

```
import FormioFormWizard from 'formiojs/wizard';

const form = new FormioFormWizard(document.getElementById('report'));
form.src = 'myformurl';
```

The component itself seems to render properly but when dragging the mouse when trying to make a signature, no black line is drawn along the path and the console just shows a bunch of errors.

![screenshot from 2017-10-15 20-29-41](https://user-images.githubusercontent.com/15008940/31590971-fe2e5726-b1e7-11e7-83f0-0428978351a2.png)

Let me know what other information I can give to help with this.

**Comment by travist** [comment]
I am trying to reproduce this, but cannot. Can you provide a js fiddle to show this happening.

I am making some updates to the Signature component right now, but this one I am not able to reproduce.

**Comment by aloisbarreras** [comment]
@travist nevermind scratch that theory, it does work with the webpack dev server in a fresh repo, but it does not work how I have it set up. My project structure is using the vue-cli so there's a million different configurations that it came with that could be causing this :(
