### ISSUE TITLE
signature component issue

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#2232]
@travist  Is there anyway to redraw signature again once we submit form with previous signature.?

**Comment by randallknutson** [comment]
There should be a reset button that will reset the signature back to empty.

**Comment by sureshece9999** [comment]
Reset is fine but is there any way to redraw signature with already existed signature. I don't want to reset previous signature.

**Comment by randallknutson** [comment]
This may be a bug where it sets to read only after the field has a value. We can look into a fix for it.

**Comment by sureshece9999** [comment]
**Here is the issue, you can look into the signature component.**

![sign_issue](https://user-images.githubusercontent.com/48546522/71654756-79619900-2d59-11ea-9755-e18c5ec6952b.PNG)

**Comment by randallknutson** [comment]
Thanks. I'm adding this to our backlog to get fixed. It shouldn't work this way.

**Comment by jhen1422** [comment]
@sureshece9999 This issue has been resolved in 4.8.0.
