### ISSUE TITLE
[BUG] On render event isn't triggered for wizard forms

### ISSUE THREAD

**Issue by jason-yong** [formio/formio.js#2239]
At the time of this post, using latest version of renderer (4.8.0-rc.10): https://unpkg.com/formiojs@4.8.0-rc.10/dist/formio.full.min.js

Steps to reproduce:
1) Use the following JSFiddle: https://jsfiddle.net/fr3xc12k/1/
2) Update the form URL to use: https://examples.form.io/example (instead of wizard)
3) Run the fiddle

Actual results:
- When loading a regular form, render event is triggered after form has loaded (alert pops up)
- When loading a wizard form, render event is NOT triggered after form has loaded (no alert for form render pops up)

Expected results:
- Render event should be triggered after form has loaded, regardless of type of form

**Comment by jason-yong** [comment]
Related to https://github.com/formio/formio.js/issues/2029 and https://github.com/formio/formio/issues/881

**Comment by jhen1422** [comment]
@jason-yong Since we have an open ticket already for #2029, I have added the information from your report to that ticket.  Thank you for the report.

**Comment by wag110894** [comment]
@jason-yong Thank you for your patience while we worked on getting this issue resolved. This issue has been resolved on version 4.9.26 of formio.js.

Thank you for using Form.io and let us know if you have any further questions.

**Comment by krixerx** [comment]
I am trying to catch any event on wizard panel without success.
I created a field-logic and i tried different events: my custom event, change and render event.

In normal form panel they work well but no success on wizard panel.
