### ISSUE TITLE
(Question) Trigger validation

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#224]
I'm running some long forms using the wizard component. Sadly the validation only runs on the "Next" and on the final "Submit" but only for the currently rendered page. Is there a way to trigger or get the status of the validation for the all of the wizard?.  I need my users to skip from one page from another without the need to have the validation in place, but the form should not be submitted unless all validation has passed.

Best Regards!

**Comment by pageza** [comment]
Hi Ignacio, 
This is how our renderer is intended to behave. If you are needing a different behaviour from the wizard validation, we can have our devs implement this, but it would need to be part of a support package, using some of the time for custom development. I would be happy to send you pricing information on support packages.
 
Let me know if this is something you would like us to develop, or if I can assist any further.--Zach

**Comment by cabrerabywaters** [comment]
Hello @pageza,

Thank you for your response. For the moment just wondering if there is a way of triggering the full validation of the Wizard manually using the formiojs library.

Regards!

**Comment by cabrerabywaters** [comment]
Dear @travist 

Any way to trigger the form validation for the Full Wizard using the library?. I want to give the user some feedback on the percentage of fields left (or percentage of completeness). 
But as some of the required fields are only required on conditional cases, I have to trigger the validation or have some way to get all the required fields that are currently active (visible)

As far as I have been digging, the form wizard only loads one "step" at the time, so the validation is only triggered for the current page.

Do you know any workaround or could you give me some directions on how I could change this behavior to create a PR for this?

Best Regards!

**Comment by colons** [comment]
This would also be extremely useful to me.

**Comment by travist** [comment]
Yes this can be done. Here is a snippet that could achieve this.

```js
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example').then(function(form) {
  form.on('change', function(value) {
    // This will tell you if it is valid.
    console.log(value.isValid);
  });

  // Or you can check it manually with.
  var isValid = form.checkValidity(form.submission.data);
});
```

**Comment by colons** [comment]
This appears to also only validate the currently visible page. Is there _any_ way, client-side or not, to tell if any given form.io submission is valid against a complete wizard form definition?

**Comment by colons** [comment]
Is this something I'm missing? Does [the platform](https://github.com/formio/formio) handle this some way we can reproduce, or is all we can do just trust browsers?
