### ISSUE TITLE
[BUG] (Simple) Conditionals in Formbuilder Have No Form Components Listed

### ISSUE THREAD

**Issue by marcus-at-localhost** [formio/formio.js#2240]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: v4.8.0-rc.11 

## Steps to Reproduce
Create some fields
Make one depending on another
Go to tab "Conditional" 
"When the form component:" is empty 

## Expected behavior

List of Components

## Observed behavior

No List

## Example

From the Formbuilder Test Page https://formio.github.io/formio.js/app/builder

![image](https://user-images.githubusercontent.com/1337223/71719305-33223d80-2e1e-11ea-92ec-2ee35280baf2.png)

**Comment by jhen1422** [comment]
@marcus-at-localhost Thank you for the report. We'll get this fixed.

**Comment by marcus-at-localhost** [comment]
Just checked, v4.8.0-rc.10 works fine.

**Comment by travist** [comment]
Fixed with 4.8.0-rc.12
