### ISSUE TITLE
Handle Timestamps in Datepicker

### ISSUE THREAD

**Issue by marcus-at-localhost** [formio/formio.js#2242]
My dates are in Unix Timestamps, but unfortunately, the datepicker has a weird way to handle that (or none at all).

I can set `U` (according to https://flatpickr.js.org/formatting/) but the submit data doesn't accept `U` instead it uses these  https://github.com/angular-ui/bootstrap/tree/master/src/dateparser/docs#uibdateparsers-format-codes formatting strings, which is a bit confusing.

![image](https://user-images.githubusercontent.com/1337223/71752119-29302700-2e7e-11ea-8c97-b6e752c128d4.png)

I hoped I can send and receive a timestamp, but show any human readable format in the date picker. Has anybody tried that? 

https://codepen.io/localhorst/pen/gObXzZK

just as reference: #2212
related #1871

**Comment by randallknutson** [comment]
I believe what you will want to do is set the format to "U" and the customOptoins.dateFormat to something readable. The first controls the way the data is stored and loaded from the api. The second controls the way the date is displayed to the end user.

**Comment by marcus-at-localhost** [comment]
It's not working (see codepen.io/localhorst/pen/gObXzZK)

`format` is used for the picker and `customOptions.dateFormat` for the submit and `customOptions.dateFormat:'U'` just renders the `U`in the submit, any other formatting string (like `yyyy`) works though.

![image](https://user-images.githubusercontent.com/1337223/71830068-36c7f580-30a6-11ea-961c-c0918b148294.png)

vs

![image](https://user-images.githubusercontent.com/1337223/71830307-c53c7700-30a6-11ea-80fd-f7d49d2b53ab.png)

**Comment by randallknutson** [comment]
Looks like I have them backwards. I'm not sure what the correct configuration for this would be based on what you are looking for. You may want to keep trying and see if you can get a configuration that works. If not, we can make a change somewhere to allow something like this.

**Comment by marcus-at-localhost** [comment]
I tested it back and forth :) In the docs/source, you referring to https://github.com/angular-ui/bootstrap/tree/master/src/dateparser/docs#uibdateparsers-format-codes which doesn't provide timestamp format, but it also takes flatpickr.js (`U`) at least in the `format` key, so it's a bit confusing and Timestamps were nice to use.

**Comment by randallknutson** [comment]
As we originally built the datetime component with angular1 we were using the uibdateparser library to format the dates. Since then we've changed out the component entirely. We have a bit of code that will update the formats from the old system to the new but you are better off using the flatpickr formats along with moment formats. "U" is fairly universal at this point to mean timestamp I believe.

**Comment by marcus-at-localhost** [comment]
But unfortunately, `U` doesn't get parsed in the form submission object as my example shows. It just outputs `"dateTime": "U"`

```
{
  "data": {
    "dateTime": "U"
  },
  "metadata": {}
}
```

**Comment by randallknutson** [comment]
It might be because we are converting from the old format to the new and there is no rule for "U". Can you check here to see if changing it makes a difference? https://github.com/formio/formio.js/blob/master/src/utils/utils.js#L664-L725

**Comment by marcus-at-localhost** [comment]
I solved it ➡️ working example: https://codepen.io/localhorst/pen/gObXzZK

Just use the [moment.js](https://momentjs.com/docs/#/parsing/string-format/) `X` for timestamp in `customOptions.dateFormat`

![image](https://user-images.githubusercontent.com/1337223/71992851-66a60300-3236-11ea-9e62-8ebde8b3c02f.png)

I'll send a PR for this.
