### ISSUE TITLE
[BUG] Component settings can't be changed after adding

### ISSUE THREAD

**Issue by hosney** [formio/formio.js#2243]
## Environment
Please provide as many details as you can:

- Formio.js version: v4.8.0-rc.11
- Browser: Google Chrome
- Browser version: 79.0.3945.88

## Steps to Reproduce
1.  Add 2 text fields
2. Try to change either of the text field settings (e.g. update label)
3. Try to delete any one of the text fields.

## Expected behavior
Settings should be updated.
Component should be deleted.

## Observed behavior
Settings not updated.
Component not deleted.

## Example
Issue can be reproduced at https://formio.github.io/formio.js/app/builder

**Comment by jhen1422** [comment]
@hosney Thank you for the report. We are aware of this issue and will get this fixed. In the meantime, please use version 4.8.0-rc.10

**Comment by travist** [comment]
Fixed with 4.8.0-rc.12
