### ISSUE TITLE
[BUG] File type dropdown not disabled when component is disabled

### ISSUE THREAD

**Issue by hosney** [formio/formio.js#2244]
## Environment
Please provide as many details as you can:

- Formio.js version: v4.8.0-rc.11
- Browser: Google Chrome
- Browser version: 79.0.3945.88

## Steps to Reproduce
1.  Create a file component with types
2.  Upload a file
3.  Disable file component

## Expected behavior
Type drop down should be disabled.

## Observed behavior
Type drop down is enabled even though component is disabled

## Example
https://jsfiddle.net/wh4tj8ay/

**Comment by wag110894** [comment]
Hello @hosney,

Thank you for reaching out. We are able to replicate this issue on our side. We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please contact us at support@form.io if you would like the price to expedite this for you.

Thank you,

William Gay

**Comment by jhen1422** [comment]
@hosney 
This issue has been resolved in V 4.9.0 of formio.js
