### ISSUE TITLE
[Question] Can I disable removal of the default submit button?

### ISSUE THREAD

**Issue by lschwalf** [formio/formio.js#2249]
Hi, 

I am looking at configuring the formio form builder for project, and I'm wondering if there is a way to make it so that the default submit button cannot be removed i.e. 
these controls
![Screen Shot 2020-01-07 at 10 15 21 AM](https://user-images.githubusercontent.com/26337778/71915119-50198200-3138-11ea-9094-f9207c3f0106.png)
are not visible just for the default submit button component.

**Comment by marcus-at-localhost** [comment]
Someone correct me if I'm wrong but there are two ways to do it:

1. hide it with CSS

```css
.builder-component .formio-component-button .component-btn-group {
    display: none;
}
```

2. remove submit button completely from builder

```js
Formio.builder(document.getElementById('builder'), {}, {
		noDefaultSubmitButton: true,
		builder: {
			//
		}
});
```

and add the button, when you render the form

```js

const submit_button = {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false,
            "validate": {
                "unique": false,
                "multiple": false
            }
        };

// the schema from your database
var saved_components = [{
            "label": "Text Field",
            "spellcheck": true,
            "tableView": true,
            "validate": {
                "unique": false,
                "multiple": false
            },
            "key": "textField",
            "type": "textfield",
            "input": true
        },
		{
			//...
		}
];

// add submit button to the end
saved_components.push(submit_button)

// render the form
Formio.createForm(document.getElementById('formio'), {
 components: saved_components;
});
```

I would probably go for the second option, so you have 100% control over the button.

**Comment by lschwalf** [comment]
Thanks for the response Marcus. 

What ended up working for me was using a queryselector: `querySelector('.formio-component-submit').previousElementSibling.setAttribute('hidden', true);` which is then called when the different formio events ('saveComponent', 'removeComponent' and 'render'. ) are fired.

**Comment by marcus-at-localhost** [comment]
@lschwalf that's interesting. I used a similar approach to prevent layout elements from getting dragged https://codepen.io/localhorst/pen/BayYrBg

```js
builder.instance.ready.then(function() {
    // Disable Drag and Drop for fieldsets
  	formBuilderDisableDragDrop();

	_.forEach(['render', 'change', 'addComponent'], function(value) {
		builder.instance.on(value, function() {
			formBuilderDisableDragDrop()
		});
	});
});

formBuilderDisableDragDrop = function(){
	$("[ref='webform']>.drag-container").addClass('no-drop');
	$("[ref='webform']>.builder-components>[ref='dragComponent']").addClass('no-drag');
}
```

I was just lazy and used jQuery :)

If I remember right, you had to set the class on every event fired, because it got reset all the time, right?

**Comment by lschwalf** [comment]
Yeah, I did have to set the class on every event fired.
