### ISSUE TITLE
[Question] Edit and builder mode

### ISSUE THREAD

**Issue by midrissi** [formio/formio.js#2251]
Actually, I am facing a little problem.

How can I check that I am in ( or not in ) build mode?

I have found a flag "**this.builderMode**", but it is "falsy" when I edit the properties (In the edition modal) of the component.

In other words: Is there a way to separate these three scenarios:

1. **Builder mode**: when displaying the component in the builder
2. **Edition mode**: While editing the properties of the component
3. **Usage mode**: While using the component by the end-user

Your help is much appreciated.

**Comment by randallknutson** [comment]
this.builderMode is set if options.attachMode is set to "builder". See here: https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L540-L542

This is set here in the builder: https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L333

You can differentiate the different types of modes you are in by looking at this.options.attachMode. There is also this.options.renderMode I believe.

**Comment by midrissi** [comment]
Thank you for the response.

Actually, the problem I am facing is that: I cannot know if the form was rendered in the properties modal or in the resulting form.

In both cases: **builderMode** = false, and **attachMode** is set to "**full**".

**Comment by gertaylor** [comment]
@midrissi did you manage to find an option to let you know your in "Edition mode"?

**Comment by midrissi** [comment]
@gertaylor Yes. Actually, we have added a method with this implementation:

```javascript
/**
 * Check if FormIO is in builder mode
 */
get isBuilderMode() {
	const { element: pEl, id, root } = this.parent;
	if (this.builderMode) {
		return true;
	}

	if (id !== root.id) {
		return false;
	}

	return !pEl || pEl.getAttribute('ref') === 'preview';
}
```

If you have a better way, I can take it.

Thank you.

**Comment by gertaylor** [comment]
@midrissi nice, will check this out.

Cheers

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
