### ISSUE TITLE
[BUG] Multi-select select components show nothing in html render mode

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#2253]
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.7.4 & 4.8.0-rc.12

## Steps to Reproduce
1. Create a select with `multiple: true,`
2. Set the `renderMode: 'html'`
3. Set the submission data to include data for the select

## Expected behavior
Expect multiple values to be displayed

## Observed behavior
Nothing is displayed (however removing the renderMode does show the input with multiple values selected)

## Example
https://jsfiddle.net/p51v0L9z/1/

**Comment by jhen1422** [comment]
@paulfalgout Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by jhen1422** [comment]
@paulfalgout 
This issue should be resolved in the 4.9.0 version of formio.js.
