### ISSUE TITLE
[BUG] Circular dependency 

### ISSUE THREAD

**Issue by voltrexpl** [formio/formio.js#2255]
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.8.0-rc.11
- Frontend framework: React

## Steps to Reproduce
1. Use circular-dependency-plugin in webpack

## Expected behavior

Compiled successfully.

## Observed behavior

ERROR in Circular dependency detected:
node_modules/formiojs/utils/builder.js -> node_modules/formiojs/utils/utils.js -> node_modules/formiojs/utils/builder.js

ERROR in Circular dependency detected:
node_modules/formiojs/utils/utils.js -> node_modules/formiojs/utils/builder.js -> node_modules/formiojs/utils/utils.js

**Comment by randallknutson** [comment]
We should probably get this fixed. Is it causing any issues right now?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
