### ISSUE TITLE
Interpolate defaultValue / customDefaultValue

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#2263]
I've noticed that interpolation does not work for defaultValue...is this by design? Is it possible to apply it on defaultValue? Also I noticed in the Component class:
```js
if (this.component.customDefaultValue && !this.options.preview) {
      defaultValue = this.evaluate(
        this.component.customDefaultValue,
        { value: '' },
        'value'
      );
    }
```
Doesn't the evaluate need the data? Otherwise it doesn't apply the interpolation...unless I'm wrong..

**Comment by randallknutson** [comment]
I think this is by design. For default value the idea is that it is a static value to set as the default. Interpolation doesn't make sense since the default only gets set once when the form is first initialized and does not change again. For Custom Default Value the same is true that it only gets set once but you do have access to the data variables when calculating the default value.

**Comment by aminmc** [comment]
@randallknutson  i understand that defaultValue will be set once when the form is initialised but in some cases we might want that default value to be pulled from the submission data (on initialisation). I can think of a few cases (user id pre set, etc). My current use case requires me to add some fields that the user sees but can't be edited and these values are dynamic and being able to do {{data.userContext.id}} makes it convenient.

**Comment by randallknutson** [comment]
Can you use hidden components with calculated values? This can use data.userContext.id.

**Comment by aminmc** [comment]
I can but we need to update a whole lot of forms. Also I think this is confusing in this case:

![Screenshot 2020-01-15 at 09 16 01](https://user-images.githubusercontent.com/290639/72421088-c725ca80-3777-11ea-918a-e6ffb4c39183.png)

As data doesn't work as it's never passed in.

**Comment by randallknutson** [comment]
I agree this is confusing. We should remove the data as a listed value from default value. It isn't going to be available since defaults are set before any data is set in the form.

**Comment by aminmc** [comment]
Worked through a solution with Randall

**Comment by besmiralia** [comment]
@aminmc do you mind sharing the solution?

**Comment by markfili** [comment]
@randallknutson hi, could you share a solution for this or tell us if data is still available or should it be available in defaultValue/customDefaultValue calculations?
