### ISSUE TITLE
BuilderInfo 'help' text not exposed

### ISSUE THREAD

**Issue by szmeti** [formio/formio.js#2267]
The default form builder template supports displaying a help text for the component (https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builderEditForm/form.ejs#L38), but this property is not exposed on the BuilderInfo interface (https://github.com/formio/formio.js/blob/master/types/components/schema.d.ts#L232), so it cannot be used in Angular projects. For the same reason, the Angular wrapper component does not deal with the property either.

Is this intentional?

**Comment by randallknutson** [comment]
I don't think this is intentional. We've just never gotten around to exposing it as an option to be customized. You could do this through editing the templates. We would also love a pull request that fixes this.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. 

If you feel the issue is still relevant, please re-open it. Thank you for your contribution!
