### ISSUE TITLE
Radio button with numeric values is not shown when a submission is set

### ISSUE THREAD

**Issue by josefernand** [formio/formio.js#227]
Hi, I don't know if this is related to #202.
When you have a radio button with numeric values as option values like:
```
"values": [{
      "label": "Number 100",
      "value": "100"
    }, {
      "label": "Number 200",
      "value": "200"
    }],
```
The value is not displayed properly when you set a submission.
I found this line in `src/components/radio/Radio.js` in the `setValueAt` function
```
this.inputs[index].checked = (inputValue === value);
```
is always false because it is trying to compare `inputValue` that is parsed int and `value` that is string

**Comment by bradswanson1** [comment]
Any update on this issue? This is pretty serious because form questions appear to be unanswered when in fact they are answered.

**Comment by jhen1422** [comment]
Fixed with https://github.com/formio/formio.js/issues/202
