### ISSUE TITLE
Adding a svg html balise is not working

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio.js#2273]
Hi, I'm trying to add an html component with a svg balise in the content but the renderer does not render it. Is it normal ?

**Comment by travist** [comment]
Please provide a jsfiddle so we can see the issue you are having.

**Comment by AudreyCb** [comment]
Thanks for  replying, I send you a form example, maybe it will be the most explicit example.
`{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "HTML",
            "tag": "div",
            "attrs": [
                {
                    "attr": "",
                    "value": ""
                }
            ],
            "content": "<svg width=\"400\" height=\"180\">\n  <rect x=\"50\" y=\"20\" width=\"150\" height=\"150\" style=\"fill:blue;stroke:pink;stroke-width:5;opacity:0.5\" />\n  Sorry, your browser does not support inline SVG.  \n</svg>",
            "refreshOnChange": false,
            "tableView": false,
            "key": "html",
            "type": "htmlelement",
            "input": false,
            "validate": {
                "unique": false,
                "multiple": false
            }
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false,
            "validate": {
                "unique": false,
                "multiple": false
            }
        }
    ]
}`

**Comment by travist** [comment]
What version of the renderer are you rendering this in?

**Comment by randallknutson** [comment]
All rendered output is passed through domsanitize to sanitize the output before being displayed to the end user. It could be that the src attribute is being stripped out for security reasons. Also, the pdf referenced in your src doesn't exist. I tried going directly to it and the url failed. Could you provide us with an example of this in a jsfiddle or something like that which demonstrates the issue?

**Comment by AudreyCb** [comment]
Actually, the pdf parameter is automatically generted when I drag and drop component using your page https://formio.github.io/formio.js/app/builder, so I'm not sure this is the reason ? 
I will send you a jsfiddle example as soon as possible. Thanks

**Comment by AudreyCb** [comment]
Hi, here is a jsFiddle example.
https://jsfiddle.net/r5h9zx2n/

**Comment by randallknutson** [comment]
The svg is being stripped by dom purify that removes any dangerous html elements. You should be able to add svg as an allowed tag using options.sanitizeConfig.addTags. You can see the code https://github.com/formio/formio.js/blob/853d00b03189f941d2aada615160c5441338eb80/src/utils/utils.js#L1079 that implements this.

**Comment by AudreyCb** [comment]
Thanks, this is working now !

**Comment by waterbuckit** [comment]
I have been trying to do just this, and using the SVG that @AudreyCb  used, it worked, however providing an SVG with a path element inside seems to cause problems, the `d` attribute seems to just get deleted?
My options look like this:
```js
{
sanitizeConfig : {
        addTags : [
           "svg", 
           "path"
        ]
    }
}
```
The svg I was testing is this:
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
  <path fill-rule="evenodd" d="M4 4a2 2 0 012-2h8a2 2 0 012 2v12a1 1 0 110 2h-3a1 1 0 01-1-1v-2a1 1 0 00-1-1H9a1 1 0 00-1 1v2a1 1 0 01-1 1H4a1 1 0 110-2V4zm3 1h2v2H7V5zm2 4H7v2h2V9zm2-4h2v2h-2V5zm2 4h-2v2h2V9z" clip-rule="evenodd" />
</svg>
```

**Comment by travist** [comment]
This is probably more of an issue with dompurify library @ https://github.com/cure53/DOMPurify

You may need to ask your question there.

**Comment by AudreyCb** [comment]
Hi, actually, to make it work, I had to add all the attr like this : 

`sanitizeConfig: {
        allowedTags: ['svg', 'title', 'path'],
        addTags: ['svg', 'title', 'path'],
        allowedAttr: [
          'onclick',
          'onpaste',
          'd',
          'transform',
          'fill',
          'viewBox',
          'xmlns',
        ],
        addAttr: [
          'd',
          'transform',
          'fill',
          'viewBox',
          'xmlns',
        ],
      },`

**Comment by Otrozone** [comment]
> Hi, actually, to make it work, I had to add all the attr like this :
> 
> `sanitizeConfig: { allowedTags: ['svg', 'title', 'path'], addTags: ['svg', 'title', 'path'], allowedAttr: [ 'd', 'transform', 'fill', 'viewBox', 'xmlns', ], addAttr: [ 'd', 'transform', 'fill', 'viewBox', 'xmlns', ], },`

Hello, I believe it's `allowedAttrs`, not `allowedAttr`.

```
sanitizeConfig.addAttr
sanitizeConfig.addTags
sanitizeConfig.allowedAttrs
sanitizeConfig.allowedTags
```
