### ISSUE TITLE
Problem with progressbar in file upload

### ISSUE THREAD

**Issue by Svitra** [formio/formio.js#2275]
Hi,

I encountered a problem with FileUpload component and if I see correctly there is an error in the code (file formio.js/src/templates/bootstrap/file/form.ejs). The progressbar width is set without the "+%" (line 88) which causes the browser to interpret it as invalid value and ignore it - making the progressbar always render fully gray. Could you possibly fix it in the next version? Or is it possible it is some problem on my side?

Kind regards

**Comment by randallknutson** [comment]
I don't see the % being added to the progress on that line.
https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/file/form.ejs#L88

I checked the value of progress which is set here: https://github.com/formio/formio.js/blob/master/src/components/file/File.js#L610

Neither of them show a percent being added. Is this in a different framework template or an override?

**Comment by Svitra** [comment]
Hi,

First of all thank you for your prompt response. :)

I am using an Angular wrapper in this case but I am quite sure that is not the problem.

My problem is exactly that the % is not added in the rendered template and hence the width property is being ignored (the unit is required by the browser). The rendered template in my case has e.g. style="width: 50" (browser ignores the width due to missing unit). The calculation of the value in File.js is also performed correct in my case (also, if I manually fix the inline style in the dev tools by adding the "%" to: style="width: 50%" the file uploader appears to work just fine).

The text with the % in my case is rendered correctly, it is just the progressbar that cannot render the blue area due to missing width unit in the inline style.

When I check the progressbar template by bootstrap it has always the % in their examples so I assumed someone overlooked it and forgot to add the "%" in the form.ejs file in your project.

Is my explanation more clear now?

**Comment by randallknutson** [comment]
Ah, so you are saying that it NEEDS the % in the width setting. We can definitely add this. If you want to make a pull request to the template we would happily pull that in. I'm curious on why this hasn't been noticed before.

**Comment by Svitra** [comment]
According to your suggestion I created a pull request #2282.

**Comment by Svitra** [comment]
Thank you for merging my changes. Now it works perfect (also with the angular wrapper).
