### ISSUE TITLE
[BUG] Cannot set default value on checkbox

### ISSUE THREAD

**Issue by Zengage** [formio/formio.js#2279]
## Steps to Reproduce
1. Add a checkbox component
2. Set JavaScript Default to value = true;
![image](https://user-images.githubusercontent.com/9194241/72552089-6c36c500-3896-11ea-95cf-7a3a5d0e491c.png)

## Expected behavior
Checkbox should render with checkbox ticked.
In Preview mode it does
![image](https://user-images.githubusercontent.com/9194241/72552273-cf285c00-3896-11ea-95ea-0acac0d481e5.png)

## Observed behavior
It does not render with checkbox ticked when in "Enter Data" tab.
![image](https://user-images.githubusercontent.com/9194241/72552326-e8310d00-3896-11ea-9ba4-9f3417b98f1b.png)

**Comment by wag110894** [comment]
Hello @Zengage, what version are you using?  We are unable to replicate this issue using version 4.8.0-rc.13.  Could you also provide a JSFiddle of this issue taking place?

**Comment by Zengage** [comment]
Hi Will,
I am using the latest version as well.
I have this form build with formio.io https://afkihurshwamffu.form.io/signatureform

I render it with following code:
<html>
  <head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css'>
    <script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.createForm(document.getElementById('formio'), 'https://afkihurshwamffu.form.io/signatureform');
      };
    </script>
  </head>
  <body>
    <div id='formio'></div>
  </body>
</html>

The checkbox is not ticked.
Am I setting the value of the checkbox incorrectly?

**Comment by wag110894** [comment]
You can also accomplish this by changing the Default Value at the top of the Data tab and change it from 'false' to 'true'.

**Comment by Zengage** [comment]
Yes, thanks. 
I actually do want to put some logic in there and it is working fine for a text box for instance.
Just for simplicity I wanted to show that even setting it straight to true does not work.

I have found another way in the meanwhile as a work-around but it is more user-friendly if one can put the logic directly when building the form.
Formio.createForm(document.getElementById('formio'),form).then(function(form) {
			  form.submission = {
				data: {
				  email: gZenFormValuesLoaded.Email,
				  mail: gZenFormValuesLoaded.Mail,
				  phone: gZenFormValuesLoaded.Phone,
				  sms: gZenFormValuesLoaded.SMS
				}
			  };
			});

**Comment by sp193** [comment]
I believe this has been resolved with #3856, which is available with 4.14.x. I can see the customDefaultValue function getting called.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
