### ISSUE TITLE
[BUG] Default Value hidden when Conditional Field

### ISSUE THREAD

**Issue by marcus-at-localhost** [formio/formio.js#2286]
## Environment

- Formio.js version: 4.8.0-rc14
- Frontend framework: Vanilla JS

## Steps to Reproduce
1. Create fields with simple conditions and hide them initially

## Observed behavior

Default Value parameter gets hidden in Data Tab

## Expected behavior

Should not affect field

JSFiddle https://jsfiddle.net/hg0y8saz/4/

![ezgif com-optimize](https://user-images.githubusercontent.com/1337223/72668019-89000380-3a22-11ea-9034-d093424b0df0.gif)

**Comment by jhen1422** [comment]
@marcus-at-localhost 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
