### ISSUE TITLE
[BUG] Currency component regex pattern not compensating for "$", " Please match the requested format" error

### ISSUE THREAD

**Issue by joakim-emagine** [formio/formio.js#2291]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.8.0.rc14 
- Formio.js version: 4.8.0.rc14
- Frontend framework: none
- Browser: Chrome, and Firefox
- Browser version:  79.0.3945.117 (Official Build), 72. 01 (FF)

## Steps to Reproduce
1. Create a currency component
2. Save the form.
3. Enter a numerical value
4. Observe the error " Please match the requested format"

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Generated html:
```html
<input value="" class="form-control" type="text" name="data[currency]" ref="input" pattern="[0-9.,]*" lang="en">
```
For code or form JSON, please enclose in a code block:

```
```js
// your code here
```
Screenshot:

![image](https://user-images.githubusercontent.com/31224638/72759075-f9d22780-3baa-11ea-8600-bb7f63e45c1f.png)

**Comment by jhen1422** [comment]
@joakim-emagine 
I tried replicating this using the rc14 and was unable to replicate. Please see the fiddle below

https://jsfiddle.net/sLufaz10/

If this issue persists for you, could you please provide a fiddle showing the issue? Thanks!

**Comment by joakim-emagine** [comment]
@jhen1422 Not sure why it's not giving the prompt, but i'm guessing it's because you are submitting via ajax thus ```e.preventDefault();``` gets called (which disables the browser validation bubbles). 

But nonetheless, the pattern regex is still ```[0-9,.]*```, which supposedly makes values such as $40,000.00 invalid.
