### ISSUE TITLE
Populate DataGrid Dynamically

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2292]
Hello FormIO team,

I try to populate the DataGrid dynamically with a json object. It works fine the first time I build the form but when the "default" values are set it only loads the default values and not the new dynamic json.

Hope you understand my issue and you can help to point me in the right direction.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello travist,

Thanks but I haven't got the data yet at form.submission.
This is what I did and after mucho trials and errors it seems to work:
in the datagrid -> Calculated Value I added:
`$.ajax({
		url : "<my rest service url>"
	}).then(function (data) {
		console.log('data: ' + JSON.stringify(data));
		window.containerData = data;
	});
value = containerData;`

If you see any reason to do it different please advise.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello travist,

The above method has an issue: With the first load of the form the datagrid is not populated probably because it takes time to get the data and the grid is already rendered?

Any advise how to overcome this? I have not read about a component redraw or refresh.

Kind regards,
Mario

**Comment by randallknutson** [comment]
While you can do it in a calculated value like that, we don't really intend to support async setting of data in the calculated value. It could cause issues somewhere else. You would probably have better luck doing it in a form controller with something like this:
http://formio.github.io/formio.js/app/examples/externalload.html

**Comment by KyooMario** [comment]
Hello Randall and Travist,

I worked it out as follows: I use a datagrid and a textfield. The textfield is using logic to set the a datastream variable and a trigger variable. When the textfield (trigger) value gets "1" the datagrid condition is set to Show and the datagrid calculated value is set to the datastream variable.

It seems to work fine but any remarks are welcome.

See builder code below:
`builder.schema : {
	"components" : [{
			"label" : "datagridTrigger",
			"hidden" : true,
			"spellcheck" : true,
			"tableView" : true,
			"clearOnHide" : false,
			"calculateValue" : "value = thisValue;",
			"validate" : {
				"unique" : false,
				"multiple" : false
			},
			"key" : "datagridTrigger",
			"logic" : [{
					"name" : "SetTrigger",
					"trigger" : {
						"type" : "event",
						"event" : "render"
					},
					"actions" : [{
							"name" : "SetValue",
							"type" : "value",
							"value" : "$.ajax({\r\n\t\turl : \"https://kyoodatrest-developer-edition.eu19.force.com/services/apexrest/kyoodat/rest?query=SELECT%20Id%2CName%20FROM%20kyoodat__CustomRecord__c%20ORDER%20BY%20CreatedDate%20DESC%20NULLS%20FIRST%20LIMIT%205\"\r\n\t}).then(function (data) {\r\n\t\twindow.containerData = data;\r\n\t\twindow.thisValue = \"1\";\r\n\t});"
						}
					]
				}
			],
			"type" : "textfield",
			"input" : true
		}, {
			"label" : "Data Grid",
			"disableAddingRemovingRows" : false,
			"reorder" : false,
			"addAnotherPosition" : "bottom",
			"defaultOpen" : false,
			"layoutFixed" : false,
			"enableRowGroups" : false,
			"tableView" : true,
			"calculateValue" : "//data.dataGrid2 = containerData;\nvalue = containerData;",
			"allowCalculateOverride" : true,
			"validate" : {
				"unique" : false,
				"multiple" : false
			},
			"key" : "dataGrid2",
			"conditional" : {
				"show" : true,
				"when" : "datagridTrigger",
				"eq" : "1"
			},
			"type" : "datagrid",
			"removePlacement" : "col",
			"mask" : false,
			"alwaysEnabled" : false,
			"input" : true,
			"components" : [{
					"label" : "Name",
					"spellcheck" : true,
					"tableView" : true,
					"allowCalculateOverride" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "Name",
					"type" : "textfield",
					"alwaysEnabled" : false,
					"input" : true,
					"reorder" : false,
					"row" : "0-0"
				}, {
					"label" : "save",
					"spellcheck" : true,
					"tableView" : true,
					"defaultValue" : "true",
					"redrawOn" : "dataGrid2.Name",
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "save",
					"logic" : [{
							"name" : "SetTrigger",
							"trigger" : {
								"type" : "event",
								"event" : "render"
							},
							"actions" : [{
									"name" : "SetValue",
									"type" : "value",
									"value" : "value = \"false\";"
								}
							]
						}
					],
					"type" : "textfield",
					"input" : true
				}, {
					"label" : "Id",
					"spellcheck" : true,
					"tableView" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "Id",
					"type" : "textfield",
					"input" : true
				}, {
					"label" : "sobjectType",
					"spellcheck" : true,
					"tableView" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "sobjectType",
					"type" : "textfield",
					"input" : true,
					"defaultValue" : "kyoodat__CustomRecord__c"
				}
			],
			"groupToggle" : false,
			"path" : "dataGrid2"
		}, {
			"type" : "button",
			"label" : "Submit",
			"key" : "submit",
			"disableOnInvalid" : true,
			"input" : true,
			"tableView" : true,
			"validate" : {
				"unique" : false,
				"multiple" : false
			}
		}
	]
}
`

**Comment by randallknutson** [comment]
That should be fine. What you are asking is coming up more and more and we have a developer looking into it as well. I'll ask him to post a solution here if he finds a different one.

**Comment by KyooMario** [comment]
Hello Randall,

Perfect. Thanks.
Mario

**Comment by KyooMario** [comment]
Hello Randal,

While I have your attention. In a datagrid row (2 fields) I want to change a row field value (to a specific value) when the other row field changes (to whatever value) . I cannot seem to get this working.
How do I do this?

Kind regards,
Mario

**Comment by randallknutson** [comment]
Use a calculated value on the field you want to change the value of (NOT the one the user is modifying). Then use value = row.otherfield * 2; or however you want to calculate it. Notice that row is used instead of data.

**Comment by KyooMario** [comment]
Thanks. Will test.

Question about the datastream: In my url I try to capture another fields value so I included it like {{dataId}} but is this the correct way? Because it seems not to work.

`$.ajax({
		url : "https://kyoodatrest-developer-edition.eu19.force.com/services/apexrest/kyoodat/rest?query=SELECT%20Id%2Ckyoodat__ParentId__c%2CName%20FROM%20kyoodat__CustomRecord__c%20WHERE%20kyoodat__ParentId__c%20%3D%20%27{{data.Id}}%27%20ORDER%20BY%20CreatedDate%20DESC%20NULLS%20FIRST%20LIMIT%205"
	}).then(function (data) {
		window.containerData = data;
		thisValue = "1";
	});`

**Comment by KyooMario** [comment]
I tested to get another field value like this:
`var filterValue = data.Id;
console.log('filterValue: '+filterValue);`

But there is NO result.
I use it in a field logic triggered in the "render" event.

**Comment by KyooMario** [comment]
In my attempt to get it done I thought I use a timeout which works but from inside this function I try to set a field value but that causes an issue. Basically I don't know how. Can you help?

`setTimeout(function(){ 
var filterValue = data.Id;
console.log('filterValue: '+filterValue);
$.ajax({
		url : "https://kyoodatrest-developer-edition.eu19.force.com/services/apexrest/kyoodat/rest?query=SELECT%20Id%2Ckyoodat__ParentId__c%2CName%20FROM%20kyoodat__CustomRecord__c%20WHERE%20kyoodat__ParentId__c%20%3D%20%27"+filterValue+"%27%20ORDER%20BY%20CreatedDate%20DESC%20NULLS%20FIRST%20LIMIT%205"
	}).then(function (data) {
	  console.log('data'+data);
		window.containerData = data;
		window.thisValue = "1";
		data.datagridTrigger = "1";
	});
}, 3000);`

**Comment by travist** [comment]
Something like this should work. 

https://jsfiddle.net/travistidwell/qdr2jfx3/13/

**Comment by KyooMario** [comment]
Hello Travis,

I have tested this and it works fine but I need to "execute" it from inside the form because in the form I need to capture a query filter value.
Can this be done?

Question: I used to use: form.on('render', function () { do some stuff here });
But in the latest release this does not work anymore. Do I need to use another event name?

Kind regards,
Mario

**Comment by travist** [comment]
We are introducing a Form controller feature in the next couple of weeks that will be able to solve this problem for you, so stay tuned for that to become a reality.

**Comment by KyooMario** [comment]
Thanks so far. Looking forward.

**Comment by KyooMario** [comment]
This is what I ended up with finally.
One thing to overcome and maybe needs your attention in future releases:

1. When calling a server side function from inside the calculated value the option "Allow Manual Override of Calculated Value" does not work because with every field update the calculated value function is executed and overwrites the manual change made.
I had to workaround this including a variable that changes after the first call and prevents the data update.
2. Another small thing was that in select box url including a variable can be done using {{myVariable}} but in the calculated value this is not allowed.

On serverside I used the suggestion from Travis:
`window.fetchDataStream = function(url,component,triggerValue){
	console.log('triggerValue: '+triggerValue);
	if(triggerValue != "1") {
		fetch(url).then(function (response) {
			response.json().then(function (dataRecords) {
				console.log('dataRecords: ' + JSON.stringify(dataRecords));
				const dataGrid = form.getComponent(component);
				dataGrid.setValue(dataRecords.map(function (dataRecord) {
					return dataRecord;
					/*return {
						Id: dataRecord.Id,
						Name: dataRecord.Name
					};*/
				}));
			});
		});
	}
}`

The datagrid calculated value looks like:
`{
	"components" : [{
			"label" : "RecordId",
			"spellcheck" : true,
			"tableView" : true,
			"validate" : {
				"unique" : false,
				"multiple" : false
			},
			"key" : "Id",
			"type" : "textfield",
			"input" : true
		}, {
			"label" : "Name",
			"spellcheck" : true,
			"tableView" : true,
			"validate" : {
				"unique" : false,
				"multiple" : false
			},
			"key" : "Name",
			"type" : "textfield",
			"input" : true
		}, {
			"label" : "Data Grid",
			"disableAddingRemovingRows" : false,
			"reorder" : false,
			"addAnotherPosition" : "bottom",
			"defaultOpen" : false,
			"layoutFixed" : false,
			"enableRowGroups" : false,
			"tableView" : false,
			"allowCalculateOverride" : true,
			"validate" : {
				"unique" : false,
				"multiple" : false
			},
			"key" : "dataGrid",
			"type" : "datagrid",
			"input" : true,
			"components" : [{
					"label" : "Id",
					"spellcheck" : true,
					"tableView" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "Id",
					"type" : "textfield",
					"input" : true
				}, {
					"label" : "Name",
					"spellcheck" : true,
					"tableView" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "Name",
					"type" : "textfield",
					"input" : true
				}, {
					"label" : "sobjectType",
					"spellcheck" : true,
					"tableView" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "sobjectType",
					"type" : "textfield",
					"input" : true,
					"defaultValue" : "kyoodat__CustomRecord__c"
				}, {
					"label" : "kyoodat__ParentId__c",
					"spellcheck" : true,
					"tableView" : true,
					"calculateValue" : "value = data.Id;",
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "kyoodat__ParentId__c",
					"type" : "textfield",
					"input" : true
				}, {
					"label" : "save",
					"spellcheck" : true,
					"tableView" : true,
					"validate" : {
						"unique" : false,
						"multiple" : false
					},
					"key" : "save",
					"type" : "textfield",
					"input" : true,
					"defaultValue" : "true"
				}
			],
			"path" : "dataGrid"
		}, {
			"type" : "button",
			"label" : "Submit",
			"key" : "submit",
			"disableOnInvalid" : true,
			"input" : true,
			"tableView" : false,
			"validate" : {
				"unique" : false,
				"multiple" : false
			}
		}, {
			"label" : "dataTrigger",
			"spellcheck" : true,
			"tableView" : true,
			"calculateValue" : "if(!data.Id)return;\r\nvar filterValue = data.Id;\r\nvar url = \"https://kyoodatrest-developer-edition.eu19.force.com/services/apexrest/kyoodat/rest?query=SELECT%20Id%2Ckyoodat__ParentId__c%2CName%20FROM%20kyoodat__CustomRecord__c%20WHERE%20kyoodat__ParentId__c%20%3D%20%27\"+filterValue+\"%27%20ORDER%20BY%20CreatedDate%20DESC%20NULLS%20FIRST%20LIMIT%205\";\r\nfetchDataStream(url,'dataGrid',data.dataTrigger);\r\nvalue = \"1\";",
			"validate" : {
				"unique" : false,
				"multiple" : false
			},
			"key" : "dataTrigger",
			"type" : "textfield",
			"input" : true
		}
	]
}
`

Kind regards,
Mario

**Comment by utkarshmttl** [comment]
@travist Your fiddle is perfect!
Could you suggest a way to achieve the following:
My form has a "select" component and a "dataGrid" component. I want to populate the "dataGrid" with some rows based on the value of the "select" component. Example, if "select"==1, add two rows with certain values; else add three rows with certain different values.

Thanks a lot in advance!
