### ISSUE TITLE
LabelPosition options removed?

### ISSUE THREAD

**Issue by Narsciz** [formio/formio.js#2294]
Hi formio teams.

I've tried to upgrade formio version from 3.24.1 to 4.7.8 to see what possible regression will be caused by the upgrade.
Is it normal that the possible LabelPosition are now restricted to top and bottom?

Will the previous options be added in the future of the 4.x.x version (left (Left aligned), etc.))? 

Thanks in advance, best regards.

Olivier Montes

**Comment by travist** [comment]
This will be resolved in a future 4.x release. It is currently being developed.

**Comment by Narsciz** [comment]
Thanks! Any idea on which version this will be added?

**Comment by jhen1422** [comment]
@Narsciz We don't have a specific version # this feature will be added to at this time.

**Comment by Narsciz** [comment]
Okay,
thanks for your time, i will close the issue
