### ISSUE TITLE
Is it possible integrated it with my app?

### ISSUE THREAD

**Issue by caz-marcelosilva** [formio/formio.js#2297]
Hi,

My question is:

Is it possible integrated it with my app without to use the formio resourses?
Actually i create a new project with a component where I do "inject" the formio-builder form but...

I am trying to do the binding of input fields in my component but without success that's because on html generated I do not see the #id or the ng[(id)] to make the binding.

Is it possible to do it of any way? (Through the json... for example.)

Also is it possible to make the same thing for a button with (click) option to execute some function?

Thanks in advanced!!

Best Regards,
Marcelo Silva

**Comment by randallknutson** [comment]
You can definitely use the form builder and renderer directly within your own app without using our resources. However, you shouldn't connect directly to the form elements themselves since they are dynamic and may change on you. You should probably use the events generated by the form instance to manage change and submit events.

**Comment by marcelo-vsilva** [comment]
![formio](https://user-images.githubusercontent.com/60115933/72907287-860b5880-3d2b-11ea-8500-46bf829de97f.png)

This is the point i got: 
- First blue line is the form to edit and generate the same and print it with form-builder tag.
- Second blue line is the form no editable that i generate and save the json and print it with formio tag.
- And the third blue line is the json generate - the same i copied and use to get the second form.

You already told me that is possible however I am not achieve the point to do the binding properly.

Could you give me an example?

Here's my code in component:

**Comment by travist** [comment]
This belongs in the angular-formio issue queue. Also, will you provide a JSFiddle instead of just pasting code? It is easier to see what is going on.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
