### ISSUE TITLE
RadioGroup on edit form does not show the selected value 

### ISSUE THREAD

**Issue by Heja0007** [formio/formio.js#2301]
So basically i created an app in cordova where we can render and fill forms created from formiojs.
the issue is that after i fill a form which has a radio group it works just fine but when i try to edit the form the radio group does not show the selected value.
![Screenshot from 2020-01-23 10-49-32](https://user-images.githubusercontent.com/25169452/72958184-74c75800-3dce-11ea-9304-b4e469f5ea22.png)

**Comment by randallknutson** [comment]
We aren't able to replicate this as it appears to be working correctly in standard web view. We have lots of customers using cordova and haven't heard of this issue before. Is there something with styling or a bug in cordova that could be causing this? Radio components are just standard html so they should work just fine.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
