### ISSUE TITLE
Copy and Paste Rows From Data Grid/ Edit Grid

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#2309]
Hi All,

Is there a way to copy and past rows on a data grid on a rendered form?
I imaging this might be possible using button components with custom logic but i'm unable to get this working. 

Any guidance of examples would be appreciated :)

**Comment by travist** [comment]
You could do this...

```js
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/SOMEFORM').then(function(form) {
  
   // Copy data from one field to another.
   const dataGrid = form.getComponent('myDataGrid');
   const editGrid = form.getComponent('myEditGrid');
   editGrid.setValue(dataGrid.getValue());
});
```

**Comment by AnthonyPhan** [comment]
Seems like the code provided is meant for a button placed on page that contains an embedded formio renderer. 
What I require is something I can do from within the logic of a form.io button component or within the framework of the formio Builder.

![image](https://user-images.githubusercontent.com/12785492/73328518-0cc4b600-4295-11ea-835f-206ca2e62def.png)

**Comment by blochealth** [comment]
In case anyone else is still looking for a way to do this, in the latest version of form.io I did this by placing the following logic in the Buttom Custom Logic field (obviously swap out your own variables for source and destination rows and columns). In my case the 'paste' was going into the 3rd column in my 'destination' datagrid, which is why my 1st and 2nd columns are blank,

```
let numItemsToCopy = _.get(data, 'mysourcedatagrid.length', false);

if (numItemsToCopy) {
   let itemsToCopy = _.get(data, 'mysourcedatagrid', [])
     if (!_.get(data, 'destinationdatagrid.length', false)) {
       data['destinationdatagrid'] = [];
       
     } 
    for (let i= 0; i < numItemsToCopy; i++){
      data['destinationdatagrid'].push({'column1': "", 'column2': "", 'column3': itemsToCopy[i]['sourceColumn3']});
       
    }
    form.getComponent('destinationdatagrid').setValue(data['destinationdatagrid']);
    
}

```
