### ISSUE TITLE
Question: panel navbar

### ISSUE THREAD

**Issue by RobertCrash** [formio/formio.js#2310]
Hi,

is it possible to enable validation (e.g. required) when changing/leaving a panel via "panel navbar" and NOT via buttons(next,prev) ?

If so how? Example ?

Thanks

**Comment by travist** [comment]
What is a "panel navbar"?

**Comment by RobertCrash** [comment]
"panel navbar" = wizard panel/page navigationbar
(see pic)
![Screenshot 2020-01-24 18:10:08](https://user-images.githubusercontent.com/42676950/73088711-0f11c380-3ed5-11ea-8997-b81b57c1321c.png)

**Comment by travist** [comment]
Wizard pages should check the validity of the page before moving on... is this not working?

**Comment by RobertCrash** [comment]
- page validation works using next / previous buttons
- page validation using wizard panel/page navigation bar is NOT working.
  should i provide a screencast ?

**Comment by wag110894** [comment]
A screencast would be great! What version are you running this in?

**Comment by RobertCrash** [comment]
formiojs v4.8.0 (formio.full.min.js), both renderer and builder, same issue (of course) -:)

It is also not working on your "Builder Demo Page".

Screencast:
https://drive.google.com/open?id=1GoXx_9QQ4s32oynoi4NMZNk6J5vJUa1c

let me know if you need more.

Thanks

**Comment by randallknutson** [comment]
We may have to make this a configurable setting. Most of our users do not want to stop people from navigating via the tabs even if navigation doesn't pass. This tends to frustrate users since they want to skip or go back between pages when using the top navigation.

**Comment by RobertCrash** [comment]
Got it.

So ...
I will try my best to implement it on my own and maybe make a pull request.

In the meantime: 
1) Is there any possible workaround using events (like onPageChange), hooks or custom actions to enable validation when using wizard panel/page navigation bar?
2) How can i disable wizard panel/page navigation bar?

Thanks

**Comment by randallknutson** [comment]
I believe those buttons do a "setPage" directly. 
https://github.com/formio/formio.js/blob/master/src/Wizard.js#L215-L222
https://github.com/formio/formio.js/blob/master/src/Wizard.js#L294-L315

There is a "wizardNavigationClicked" event but it doesn't look cancellable.

**Comment by RobertCrash** [comment]
thanks

**Comment by dev-thinks** [comment]
> I believe those buttons do a "setPage" directly.
> https://github.com/formio/formio.js/blob/master/src/Wizard.js#L215-L222
> https://github.com/formio/formio.js/blob/master/src/Wizard.js#L294-L315
> 
> There is a "wizardNavigationClicked" event but it doesn't look cancellable.

Yes. can we get a fix for this issue, 
https://github.com/formio/formio.js/blob/master/src/Wizard.js#L396

Page has been set directly without honoring the 'wizardNavigationClicked' response and the other event (wizardPageSelected) is called after new page has been set.

Thank you

**Comment by dev-thinks** [comment]
Meanwhile, below workaround works by overriding attachHeader function in wizard.js

`import { Formio } from 'formiojs';
const Wizard = Formio.Displays.displays.wizard;

class ExtendedWizard extends Webform {
  attachHeader() {
// validate checkvalidity before emit both events (wizardNavigationClicked, wizardPageSelected) OR we can ignore these events call our own events, if we need.
  }
}

ngOnInit(): void {
Formio.use({
  displays: {
    wizard: ExtendedWizard
  }
});
}
`
