### ISSUE TITLE
[QUESTION] Translation on custom component 

### ISSUE THREAD

**Issue by mrcportillo** [formio/formio.js#2312]
I've been working on some custom components for my project, which is already using the translation feature. I wonder if there is any way to make use of the translation flow of the base component to implement translations on my custom components.

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.7.7

For this specific component I'm adding some HTML labels, which I wanna be translated:
```js
import BaseComponent from 'formiojs/components/_classes/field/Field';

class IconedRating extends BaseComponent {
  constructor(component, options, data) {
    super(component, options, data);
    this.inputGroup = this.ce('div', { class: 'iconed-rate' });
    const icons = component.rates.map(item => {
      return this.ce('i', {
        class: 'far fa-star',
        'data-value': item.value,
        'data-label': item.label
      });
    });

    this.input = this.ce('input', {
      type: 'hidden',
      ref: `${this.component.key}-input`,
      attr: {
        id: `${this.component.key}-input`
      }
    });
    this.inputGroup.appendChild(this.input);
    const maxLabel = this.ce('label', { class: 'min-max-label' });
    maxLabel.textContent = component.maxLabel;
    this.inputGroup.appendChild(maxLabel);
}

```

I found a filter function in `ng-formio` for this purpose in angular applications  https://github.com/formio/ngFormio/blob/2.x/src/filters/translate.js#L8
Does anyone know if there is something similar for plain js version?

**Comment by randallknutson** [comment]
You have to make sure that anywhere in your template or code where you render a string you use this.t() in code or ctx.t() in the templates. When you wrap the strings with that function it will handle the translations using the normal process. If you output the strings directly then there is no mechanism to translate them.

**Comment by mrcportillo** [comment]
It worked! thanks 👏
