### ISSUE TITLE
formio.loadSubmissions(<query>)

### ISSUE THREAD

**Issue by chandranalini** [formio/formio.js#2317]
formio.loadSubmissions(<query>) is not working. I am using below code for reference. getting 400 (Bad Request) error. Could you please help on this?

var formio = new Formio('https://myproject.form.io/myform');

// Load all submissions whose first name is "Travis"
formio.loadSubmissions({params:{'data.firstName':'Travis'}}).then(function(submissions) {
  console.log(submissions);
});

**Comment by wag110894** [comment]
Could you please inspect the Network and share the actual API call that is being made.  This will give us a better idea if the url is structured properly.

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
