### ISSUE TITLE
Question: How does formio validate file uploads?

### ISSUE THREAD

**Issue by Berkan1** [formio/formio.js#2318]
I am writing a custom component to recreate/modify the file upload component and wanted to know how the 'required' validator currently works on these components. Using the default file upload component, if the component is marked as 'required', the form is set to invalid if the form is submitted when nothing is uploaded by the user and there are therefore no table rows in the file upload table. How is this achieved without the use of an input tag? I have looked through your repository but unfortunately haven't found a solution on how I can recreate this.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
