### ISSUE TITLE
How to construct form back from JSON Schema?

### ISSUE THREAD

**Issue by iHamzaKhanzada** [formio/formio.js#2323]
I am using Formio's formbuilder, I have created a form using formbuilder and saved the JSON Schema in my database. Now I want to modify the form which is recently created, because of this I have to open the formbuilder back in the same state as it was when I first created it, I want to ask how can I reconstruct all the components back using the builder's generated JSON Schema?

**Comment by randallknutson** [comment]
You should be able to load the form definition from the API and then send it back to the form builder. How this happens depends on which framework you are using (react, angular, etc).

For generic javascript it would look like:
`
// loaded from api
const form  = {
  display: 'form',
  components: [],
  ...
}

Formio.builder(document.getElementById('formid', form, options);
`

**Comment by fdurna** [comment]
hey , @randallknutson 
I'm writing the json data here, but it doesn't work. Is it wrong? Can you help ?
![image](https://user-images.githubusercontent.com/15355851/111084045-9f6bf700-8521-11eb-837c-6bf59d73aa4d.png)
