### ISSUE TITLE
[BUG] Select box raw JSON results in builder crash.

### ISSUE THREAD

**Issue by waltersdmh** [formio/formio.js#2341]
Hello. I have experienced problems trying to use raw JSON in a select box. I want to add JSON for all countries for a select box but the builder crashes. It looks like it could be a problem with the ace.js dependancy used in the builder.

## Steps to Reproduce
1. Go to https://formio.github.io/formio.js/app/builder
2. Drag Select Box
3. Data > Data Source Type > Raw JSON
4. Add values from https://dzone.com/articles/list-of-all-countries-in-json
5. Save

## Observed behavior
The browser then crashes with console erorrs:
- ace.js:1 misspelled option "modules" x2000
- Maximum call stack size exceeded

**Comment by aminmc** [comment]
Hi @waltersdmh I just tested the scenario you mentioned both on the portal and on our own builder and not seeing the issues you mentioned. True on the portal I did see the following:
![Screenshot 2020-01-30 at 11 09 57](https://user-images.githubusercontent.com/290639/73444785-393e0800-4351-11ea-9084-1a36be5dad55.png)

But not x2000

The below is the config:

![Screenshot 2020-01-30 at 11 09 08](https://user-images.githubusercontent.com/290639/73444801-41964300-4351-11ea-9174-0f0fb8aecc93.png)

Rendered:
![Screenshot 2020-01-30 at 11 09 25](https://user-images.githubusercontent.com/290639/73444812-45c26080-4351-11ea-802a-8c33c266577b.png)

Are you able to send a screen shot of the configuration for the select component? So I can try to reproduce?

**Comment by waltersdmh** [comment]
> Hi @waltersdmh I just tested the scenario you mentioned both on the portal and on our own builder and not seeing the issues you mentioned. True on the portal I did see the following:
> ![Screenshot 2020-01-30 at 11 09 57](https://user-images.githubusercontent.com/290639/73444785-393e0800-4351-11ea-9084-1a36be5dad55.png)
> 
> But not x2000
> 
> The below is the config:
> 
> ![Screenshot 2020-01-30 at 11 09 08](https://user-images.githubusercontent.com/290639/73444801-41964300-4351-11ea-9174-0f0fb8aecc93.png)
> 
> Rendered:
> ![Screenshot 2020-01-30 at 11 09 25](https://user-images.githubusercontent.com/290639/73444812-45c26080-4351-11ea-802a-8c33c266577b.png)
> 
> Are you able to send a screen shot of the configuration for the select component? So I can try to reproduce?

Hi @aminmc . Thank you for looking into this.

Here is is a GIF of me adding in the select box. When the console errors for ace.js get above 400 the builder freezes, and my browser crashes. The recording stops when the browser crashes. 

This is on incogneto. 

![2020-01-30_13-49-09](https://user-images.githubusercontent.com/8880852/73455733-87aad100-4368-11ea-8ad4-80e553ae683f.gif)

**Comment by aminmc** [comment]
@waltersdmh Ok.  You are putting the json in the wrong place. The choicesjs configuration is related to options that you can provide to the underlying select library. If you want to put the json in as values then you do the following:

![Screenshot 2020-01-30 at 14 28 19](https://user-images.githubusercontent.com/290639/73458189-cc386b80-436c-11ea-9066-b686fdcb0e95.png)

If you hover over the choicesjs box you should see it's related to choicesjs configuration.

![Screenshot 2020-01-30 at 14 28 44](https://user-images.githubusercontent.com/290639/73458249-e2462c00-436c-11ea-948c-f3cd25ea520b.png)

Can you put the data in 'Data Source Raw JSON' box and try it again?

**Comment by waltersdmh** [comment]
@aminmc Thanks for spotting this. I now paste the json into the correct area, and the select box works for a few seconds. The page then continues to crash at ace.js after 400ish warnings. 

![2020-01-30_14-41-24](https://user-images.githubusercontent.com/8880852/73459581-06a30800-436f-11ea-935c-edc5cddbf9ee.gif)

**Comment by aminmc** [comment]
@waltersdmh I'll have another bash at seeing if I can reproduce it. I did notice some unexpected token in JSON on the select js based on your video.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
