### ISSUE TITLE
? How to return values from data.custom to Select?

### ISSUE THREAD

**Issue by falkenbach** [formio/formio.js#2342]
Can you provide working example of setting values from data.custom function? I tried code below, getting [] regardless of data returned, allmanufacturers have data and by itself works fine:
	  const getModels = (values, m) => {
		  console.log(values, m);
		  values = allmanufacturers.slice(0, 10);
		  return values;
	  };

**Comment by aminmc** [comment]
@falkenbach I'm not sure I quite understand. Are you trying to populate a select component using custom data? 

If so you need to do the following:
![Screenshot 2020-01-30 at 14 42 56](https://user-images.githubusercontent.com/290639/73459473-d65b6980-436e-11ea-8797-66574c9a90f1.png)

![Screenshot 2020-01-30 at 14 37 41](https://user-images.githubusercontent.com/290639/73459484-d8bdc380-436e-11ea-98c0-7e90f6028238.png)

Not sure if this is what you're looking for...

**Comment by falkenbach** [comment]
Hi!
Yes, trying to populate select with custom data in FormioJS, code above just does not work, I attached full html source, see "model" inside.
[live_view20190131.zip](https://github.com/formio/formio.js/files/4137353/live_view20190131.zip)

**Comment by randallknutson** [comment]
You need to set the values function in the main javascript. It looks like you are just defining a function but never calling it. At the end of execution whatever values is set to will be used.

**Comment by falkenbach** [comment]
Nope, function is called, you can see console output in example, but returned values always ignored no matter of what.

**Comment by randallknutson** [comment]
This could be that the Item Template does not match the underlying data. For example, if each item has the form: { id: 1, label: 'foo'} but your template has something else, it won't show any results. You Item Template should be something like '<span>{{item.label}}</span>' so that it displays the label.

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
