### ISSUE TITLE
[BUG] Select component with 'url' endpoint with search query causing duplicate items

### ISSUE THREAD

**Issue by adamturtle** [formio/formio.js#2347]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
- Formio.js version:
    - Version: 4.7
- Frontend framework:
None
- Browser: All
- Browser version:

## Steps to Reproduce
1. Configure a Select component with a 'url' data source:
- Data source should contain a 'Search Query Name'
- Data source should not display any results unless a query has been provided
2. Using the search input, search for a value from the list and select it
3. Click the component to open the results dropdown again

## Expected behavior
The previous search results should load, with the selected option highlighted

## Observed behavior
The search results are replaced by a duplicate of the current selection

## Example
We recently updated our application from formio.js v2 to v4 and noticed this behaviour change. 

We have an API with a large dataset that can be searched by passing `?term=query` to the endpoint. It shows no results by default, so you must specify a query.

This seemed to work fine with the older version of formio.js, but since upgrading the search does not seem to function as before.

See below for a simple example I put together. I'm using a simple country search endpoint here.
![formio-bug](https://user-images.githubusercontent.com/547114/73479420-f3d80580-4365-11ea-9289-e3f1662f6eea.gif)

Note the search history disappears. The component doesn't appear to be making any additional API calls, it just seems to be forgetting the search state and creating a duplicate of the selected option.

Form definition:
```
{ 
   "title":"Select Test",
   "name":"e2cdf517-646e-4b88-a3c0-77a5da151fc6",
   "path":"grants-16",
   "display":"form",
   "type":"form",
   "components":[ 
      { 
         "autofocus":false,
         "input":true,
         "tableView":true,
         "label":"Select Field",
         "key":"selectField",
         "placeholder":null,
         "data":{ 
            "values":[ 
               { 
                  "value":null,
                  "label":null
               }
            ],
            "json":null,
            "url":"https:\/\/forms.test\/api\/countries",
            "resource":null,
            "custom":null,
            "headers":[ 
               { 
                  "value":null,
                  "key":null
               }
            ]
         },
         "dataSrc":"url",
         "valueProperty":null,
         "defaultValue":null,
         "refreshOn":null,
         "filter":null,
         "authenticate":false,
         "template":"<span>{{ item.label }}<\/span>",
         "multiple":false,
         "protected":false,
         "unique":false,
         "persistent":true,
         "hidden":false,
         "clearOnHide":true,
         "validate":{ 
            "required":false
         },
         "type":"select",
         "labelPosition":"top",
         "tags":[ 

         ],
         "conditional":{ 
            "show":null,
            "when":null,
            "eq":null
         },
         "properties":[ 

         ],
         "searchField":"term"
      },
      { 
         "properties":{ 
            "":null
         },
         "conditional":{ 
            "eq":null,
            "when":null,
            "show":null
         },
         "tags":[ 

         ],
         "type":"button",
         "theme":"primary",
         "disableOnInvalid":true,
         "action":"submit",
         "block":false,
         "rightIcon":null,
         "leftIcon":null,
         "size":"md",
         "key":"submit",
         "tableView":false,
         "label":"Submit",
         "input":true,
         "hideLabel":false,
         "autofocus":false
      }
   ],
   "page":0
}
```

**Comment by jhen1422** [comment]
@adamturtle Could you please provide a jsfiddle showing the issue?

**Comment by adamturtle** [comment]
@jhen1422 Sure, https://jsfiddle.net/tw9h0puL/1/

**Comment by jhen1422** [comment]
@adamturtle 
Thanks for the fiddle. In your example, the select component is not returning any results. Could you update?

**Comment by adamturtle** [comment]
The data source uses a search term which must be 3 chars or longer. Have you tried search for 'land', for example?

**Comment by randallknutson** [comment]
The issue here is that the object of the value is not matching the object being returned by the url. We try to match them and if they don't match we add the item to the dropdown. This is so that if you were to search again it won't remove the currently selected item. The issue then is why it isn't matching and we'd have to dig into it to figure it out.

**Comment by prekoc** [comment]
![multiselect_bug](https://user-images.githubusercontent.com/3585768/80021423-c4efac80-84da-11ea-894f-863706a4a0e7.png)
same jsfiddle just updated to multiple select

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
