### ISSUE TITLE
Modal popup component issue

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#2351]
Hi @randallknutson and @travist, we are using the signature component as a modal pop up. when we do refresh/ reload the form renderer page then the modal pop up always showing up and this is not closing when we click on the close button. 

![image_2020_01_31T05_11_41_361Z](https://user-images.githubusercontent.com/48546522/73516775-88526e80-441f-11ea-90cc-0bc7e7eec9ac.png)

**Comment by jhen1422** [comment]
@sureshece9999 
We are unable to replicate this issue. Can you confirm what environment and renderer version you are using.

**Comment by sureshece9999** [comment]
@jhen1422 @travist @randallknutson  
I am using **angular-formio": "^4.5.1** version.

**Comment by wag110894** [comment]
We have added this item to our backlog. We welcome a pull request or have a process to expedite. If you are interested, please contact support@form.io.

Thank you.

**Comment by srinisubramanian** [comment]
> We have added this item to our backlog. We welcome a pull request or have a process to expedite. If you are interested, please contact [support@form.io](mailto:support@form.io).
> 
> Thank you.

The development of feature for Modal Signature popup was sponsored by us.  Please expedite the fix as without it the feature development is not complete.

**Comment by srinisubramanian** [comment]
Any updates on this since it was added to your backlog?

**Comment by wag110894** [comment]
@srinisubramanian,

Thank you for your patience while worked on getting this issue resolved. Please confirm that this issue with the x button is resolved on the latest version of formio.js (4.9.0).

Looking forward to your response.

Thank you,

William Gay
