### ISSUE TITLE
Class name "required"

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2353]
Hello FormIOjs team,

You use the class name "required" when validation is required. Of course.
But I am embedding the form and the parent style also uses the class name which distorts the layout of the form components and I cannot switch it off.
Can you tell me where in the code you assign the "required" class name so I can rename it? I have searched but cannot find it.

Kind regards,
Mario

**Comment by KyooMario** [comment]
I think I found it after all: I have changed "required" to "component-required"

if (this.hasInput && this.component.validate && (0, FormioUtils.boolValue)(this.component.validate.required)) {
        className += ' component-required';
      }

Please comment if I got it wrong.

Kind regards,
Mario

**Comment by randallknutson** [comment]
You can also override this in the cssClass.js mapping function. https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/cssClasses.js

If you do it this way you can override using a module and not need to fork the code. 
https://github.com/formio/formio.js/wiki/Modules

**Comment by KyooMario** [comment]
Thanks ;-)
