### ISSUE TITLE
[BUG] Input Mask doesn't trigger relative error

### ISSUE THREAD

**Issue by tecnoel** [formio/formio.js#2354]
## Environment

- Hosting type
  - [X] Local deployment
- Formio.js version: 4.8.1
- Frontend framework: angular-formio
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Set Input Mask on a Text Field
2. Enter any data to the input mask

## Expected behavior
If the data doesn't apply mask , the relative error should appear

## Observed behavior
Nothing happens

## Solution Proposal
Problem is due to the "mask" Validator

```js
mask: {
    ...
    check: function check(component, setting, value) {
        ...
          } else {
            inputMask = component._inputMask; //_inputMask doesn'exists
          }
        ...
    }
}
```

component._inputMask doesn'exists

I think you should use "component.defaultMask" instead.
```js
mask: {
    ...
    check: function check(component, setting, value) {
        ...
          } else {
            inputMask = component.defaultMask;
          }
        ...
    }
}
```

**Comment by jhen1422** [comment]
@tecnoel Do you mind providing a jsfiddle to show the issue?

Thanks!

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
