### ISSUE TITLE
Radio component missing label options for justification

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#2356]
We make use of the left justification for labels when using radio components in v3.15 now. We are looking to upgrade our version to 4.8.1 and noted that the extra options are missing and only Top/Bottom are options. Was this intentional? Any plans to bring it back?

I have a screenshot showing how it looks to us in the previous version.
<img width="600" alt="Screen Shot 2020-01-31 at 5 27 27 PM" src="https://user-images.githubusercontent.com/1413491/73579044-4b05d500-444f-11ea-9e71-f7d7e453a65a.png">

**Comment by randallknutson** [comment]
We had to remove this since the new templating supports many different frontend frameworks and the left/right was not natively supported by any of them. We have a developer working right now to add this back. You can follow the pull request here: https://github.com/formio/formio.js/pull/2330

**Comment by ProteanHub** [comment]
You guys rock, thanks Randall.
