### ISSUE TITLE
Populating form values in renderer

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2357]
I am storing my form's json into database and when my page loads I get that json and use renderer to display the form. 

I would like to know if there is any easy way of Populating data into fields after form has rendered. I know I can use ```"defaultValue: "myvalue"``` for each field in my form, but this will involve iterating over each json key and setting defaultValue to the relevant value.  

I can use following code to populate data for all my fields but the problem that I encountered with form.submission approach is that when I change value directly in a control then the new value is not submitted. I guess I am looking for a way similar to form.submission for populating all values but if user changes any value in the control then the updated values are submitted. Is there a way of achieving this?
```
form.submission = {
                data: {
                    "client.forename": 'ABC',
                    "client.surname": 'DEF'                    
                }
            };  
```

**Comment by randallknutson** [comment]
The "dot" in the names means it should be an object. So the data would look like:

```
form.submission = {
                data: {
                   client: {
                      forename: 'ABC',
                      surname: 'DEF',
                   }
                }
            };  
```

**Comment by learner291** [comment]
Perfect, thank you.
