### ISSUE TITLE
[BUG] Datagrid defaultValue issues

### ISSUE THREAD

**Issue by pmanu93** [formio/formio.js#2364]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: formiojs v4.9.0-beta.1
- Frontend framework:none
- Browser: Firefox Nightly
- Browser version: 74.0a1 (2020-02-03) (64-bit)

## Steps to Reproduce
1. Go to [form builder demo](https://formio.github.io/formio.js/app/builder)
1. Add datagrid to form
2. Add 2 textfields to the datagrid
3. Set `defaultValue` of some textfield in the datagrid
4. Change the `dataKey` of that textfield

## Expected behavior
When you change de `dataKey` of some field, the change should be reflected in the `defaultValue` of the referred field
## Observed behavior
The `defaultValue` key doesn't change which makes the user loose the data he filled in.
Even If you remove de field from the datagrid, its `defaultValue` remains in the datagrid's `defaultValue` data.. which ends up being submitted.

## Example
I attached a video
[formio-datagrid-defaults.webm.zip](https://github.com/formio/formio.js/files/4152808/formio-datagrid-defaults.webm.zip)
 showing the issue.

**Comment by jhen1422** [comment]
@pmanu93 Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by suportecaso1** [comment]
I have the same issue

**Comment by jhen1422** [comment]
@pmanu93 This issue has been resolved in version 4.9.20
