### ISSUE TITLE
Wizard Step Names are not hiding

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2367]
I have two questions regarding wizards:

1) Is it possible to hide wizard step names/labels which appear at the top? I have changed `breadcrumb:none` but I guess it is not for hiding step labels. Please see the [fiddle](https://jsfiddle.net/zj4hmduk/), it shows Page1 as step name.

2) Wizard step names/labels appear at the top of the wizard horizontally, is it possible to change their location so that step names appear vertically on the left side of each step?

**Comment by YuryRybakSoftensity** [comment]
Hey @learner291,
Both should be configured via templates and styles in Formio.js 4.x.
Example on question 1: https://jsfiddle.net/yLbr7hwa/
Example on question 2: https://jsfiddle.net/yLbr7hwa/1/

Please let me know if you have any other questions.

**Comment by learner291** [comment]
Thank you
