### ISSUE TITLE
Display components under submit button

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio.js#2372]
Hi, is there a way to display some components (like html component with cnil mentions) under submit button ?

**Comment by jhen1422** [comment]
@AudreyCb You can simply add components underneath the submit button within the builder.

**Comment by AudreyCb** [comment]
Hi, thanks for the reply, but in wizard mode we can not do this !

**Comment by randallknutson** [comment]
In wizard mode the buttons are outside of the regular page context. All components must be in the page context for switching between pages so there currently isn't any way to add items below the buttons.
