### ISSUE TITLE
Calculated value is triggered by all components

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2376]
When I set a calculated value on a component A with a redraw on component B it is also triggered when changing component C.
In my case scenario component C is a Text Area which gives the typing hick ups because of the calculation trigger.

**Comment by KyooMario** [comment]
I tried using the "Advanced logic" to update a value in A when B changes but again this is also triggered when C is changed.
This is a worrying performance inefficiency. Any advise on this.

Kind regards,
Mario

**Comment by randallknutson** [comment]
Calculated values do trigger on any change since the value may update based on the change of any other component so we can't make it more efficient. Advanced logic will also work this way if you set the event to 'change' since there is no way to limit the components it is listening to. We could add an option to the change event to filter down based on the component type/key so it only triggers for some fields.

While it is a little inefficient, we have some really large and complex forms running the calculated values on each change and typically haven't seen a noticeable impact on the form. Is this something that is causing problems or only calculated more than desired?

**Comment by KyooMario** [comment]
I experience the most hinder in the text area when typing. It is not fluent.

Would it be a workaround to play with creating an event on a component and listen to it?

On component A we add some javasscript like:
`document.getElementsByName("data[Id]")[0].addEventListener('change', doThing);`

Then on component B we set advanced logic triggered by the event "doThing"

I tried it by adding the code snippet in the javascript "calculate value" box but that did not work ;-(

Or does above make no sense?

Kind regards,
Mario

**Comment by KyooMario** [comment]
What helps immediately is putting the validation in the text area (and other fields) to blur instead of change

**Comment by KyooMario** [comment]
A small simple question: Can I set another components value? data.componentB = "Xxx" does not work.

**Comment by KyooMario** [comment]
Hum actually it works it just is not rendered:

![image](https://user-images.githubusercontent.com/38975838/73861071-ce9f3780-483c-11ea-934d-6dc2b5ab00dd.png)

**Comment by KyooMario** [comment]
Ah. And here the "Redraw On" comes in handy (or is meant to be) ;-)

**Comment by KyooMario** [comment]
Earlier I wrote:
"What helps immediately is putting the validation in the text area (and other fields) to blur instead of change"

I was to quick. In a more complex form it does not work this way.

**Comment by AnthonyPhan** [comment]
> Calculated values do trigger on any change since the value may update based on the change of any other component so we can't make it more efficient. Advanced logic will also work this way if you set the event to 'change' since there is no way to limit the components it is listening to. We could add an option to the change event to filter down based on the component type/key so it only triggers for some fields.
> 
> While it is a little inefficient, we have some really large and complex forms running the calculated values on each change and typically haven't seen a noticeable impact on the form. Is this something that is causing problems or only calculated more than desired?

Is there any plans to add the capability described above where you can set onChange and select the component key?

**Comment by bilogic** [comment]
Same issue here, either 

1. Change and redraw other components (we can't access other components)
2. OR be able to tell which component was triggering the change event and ignore the ones we don't want (unable to tell which component was triggering the event)

**Comment by daneformio** [comment]
@bilogic We were unable to reproduce in our latest version. Can you provide a jsfiddle with an example of this happening?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
