### ISSUE TITLE
tooltip and description do not show again when edited [BUG] 

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#2377]
Using latest version https://formio.github.io/formio.js/app/builder
![cb4e3cc1a7e7580d9567e7d1a46e62f1](https://user-images.githubusercontent.com/3460517/73879290-098b7600-4811-11ea-87af-10926bebe405.png)

1. Add any field in the form builder
2. Open field settings.
3. Add description and tooltip. All is good.
4. Click save.
5. Open field settings again and see that description and tooltip fields are empty.

**Comment by wag110894** [comment]
We are aware of this issue and currently have a developer working on it. We will update you once this has been resolved.

Thank you.

**Comment by wag110894** [comment]
@dolphinsd Thank you for your patience while we got this issue resolved. This issue has been resolved on the latest version of formio.js: 4.9.0-beta.4.
