### ISSUE TITLE
How to display text instead of Id in select drop down in lazy load?

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2378]
I have a select drop down which populates data in lazy mode from a URL. The key for the drop down is called `Model_ID` and is an `int` type. I get this key from the server and populate the drop down with this key. It works fine, however because of lazy load drop down may not have all the values so it cannot match `Model_ID` with corresponding `Model_Name`, therefore it display the `Model_Id` instead. How can I display `Model_Name` in above scenario. I have to use `Model_ID` as a key because it is linked to a lookup table.  I have tried to use `Model_Name` in addition to `Model_ID` in MyData variable and `labelProperty: 'Model_Name'` in a unsuccessful attempt to achieve my goal but I guess that is not a correct way.

Code can be checked in the [fiddle](https://jsfiddle.net/xo4zha5u/) as well as below.

```
var MyData = 
{
 "Model_ID": 1863  ,//database stores int so I have to return int to link with key: Model_ID
 'Model_Name': 'Civic'//An attempt to display name
 };

Formio.createForm(document.getElementById('formio'), {
  components: [
    {
      type: 'select',
      label: 'Model',
      key: 'Model_ID',
      placeholder: 'Select your model',
      dataSrc: 'url',      
      data: {
        url: 'https://vpic.nhtsa.dot.gov/api/vehicles/getmodelsformake/honda?format=json'
      },
      valueProperty: 'Model_ID',
      labelProperty: 'Model_Name',//This may be wrong
      template: '<span>{{ item.Model_Name }}</span>',
      selectValues: 'Results'
    }
  ]
}).then((form) => {
                form.submission = {
                    data: MyData
                };});
```

**Comment by randallknutson** [comment]
I think we still have a bug around this where if you have a valueProperty set and load data from an external url it won't properly find the item the first time and adds it to the options as the value. I'll bump this issue in our todo list and see if we can get it resolved.

**Comment by learner291** [comment]
There is one other thing, I want to know if it is possible. In the fiddle mentioned in my question, if the Model_ID 1234 is not returned by web service (which means it may not be a valid option for selection but it may have been in the past so we may need to display the previous value), is it possible to dynamically add Model_ID:1234 (Model_Name: optionNoLongerExistForNewRecordsButNeedToDisplay)?

```
var MyData = 
{
 "Model_ID": 1234,
 'Model_Name': 'optionNoLongerExistForNewRecordsButNeedToDisplay'
 };
```

**Comment by randallknutson** [comment]
What you describe can also be explained by selecting an item on the second page of results. When the form reloads the option won't be there so it will display by id still. This is actually extremely difficult to solve which is why we haven't fixed it yet. The best way to do it is to store the whole value of the object so all the data is there to be rendered. In the other fields where you need the data you can refer to the sub property of the value so you shouldn't lose any functionality.

**Comment by learner291** [comment]
Do you have a small example (fiddle) for the solution that you described that you can share please? It will help me understand it fully.

**Comment by randallknutson** [comment]
Here's an example form: https://jxijnknquwhvpuv.form.io/selectobjectdemo

**Comment by learner291** [comment]
Thank you, I will give it a go.
