### ISSUE TITLE
How to re-render form - from read only to non read only

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2386]
I am loading a form in read only mode. I have an edit button, so when I click on it I would like it to become editable. I am setting readonly property to false and then calling render() function but form remains read only. The [fiddle](https://jsfiddle.net/efcs92ky/1/) shows the way I am trying to implement it, is this the correct way?

**Comment by randallknutson** [comment]
You may be able to do this with redraw(). The render function just returns the html of the form whereas redraw will cause it to redraw and attach.

**Comment by learner291** [comment]
`redraw()` is not working either, please see the updated [fiddle](https://jsfiddle.net/w1th7r8b/). I click on edit and form remains in read only mode.

**Comment by randallknutson** [comment]
I'm not sure we support dynamically switching from read only to editable within the same form render. Your best bet is probably to destroy the form and re-render.

**Comment by learner291** [comment]
Yes, it seems like dynamic switching is not possible. I am now redirecting to edit mode. Thanks for your help anyways.

**Comment by McGern** [comment]
@learner291 @randallknutson I know it's 3 years later and the issue is closed, but am facing a similar requirement but this is the only info I could find about it. was wondering if there was a simple example showing the correct way to destroy and recreate the form with all the previous values? My use case is to switch to readonly mode after the form submission.

Thanks.

**Comment by brendanbond** [comment]
Here you go @McGern https://jsfiddle.net/brendanbond/0f92nwxh/7/

**Comment by McGern** [comment]
@brendanbond Wow, that's fantastic!!! Thanks very much, didn't expect such a quick response. Is that an example you had lying around, or did you whip it up just now?
