### ISSUE TITLE
Currency Component - Duplicate Sign

### ISSUE THREAD

**Issue by mkrienke** [formio/formio.js#239]
The currency prefix is duplicated when the form is rendered using formio.js.
![image](https://user-images.githubusercontent.com/12241774/32328672-12f65bfa-bfb1-11e7-9261-00889d298d65.png)

**Comment by travist** [comment]
This is on purpose so that it works with international numbers. What we may be able to do is provide a configuration where you could turn this off. @randallknutson implemented this so maybe he has an opinion.
