### ISSUE TITLE
[BUG] Data Grid, can remove last element on required grid

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2395]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework: React

## Steps to Reproduce
1. Add a data grid to the form and set it and a field within it to required
2. Load the form, then select the X to remove the last data grid row
3. you can still submit the form

## Expected behavior

You should get a validation error, due to not having a row of data in the data grid

**Comment by jhen1422** [comment]
@pixie79 I can't seem to reproduce this on 4.8.0. Can you verify what version you are using?

**Comment by pixie79** [comment]
Hi,

We are using 4.7.8 at the moment

Mark

**Comment by jhen1422** [comment]
@pixie79 Could you try upgrading to see if that resolves your issue?
