### ISSUE TITLE
[BUG] Two placeholders conflicting in javascript textarea

### ISSUE THREAD

**Issue by dfnjy** [formio/formio.js#2397]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.8.1
- Frontend framework: React
- Browser: Chrome
- Browser version: UpToDate

## Steps to Reproduce
1. Pick any component
2. Edit, then go to 'Logic' tab
3. Select 'Javascript' as trigger, check the js textarea

## Observed behavior
![image](https://user-images.githubusercontent.com/5002016/74197173-b69c2f00-4c13-11ea-89c1-0331581d02c7.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @dfnjy 

Thank you for reaching out! We are able to replicate this on our side. We have created a ticket and have added this to our backlog. We welcome a pull request or have a process to expedite. If you are interested in expediting this issue,  please contact support@form.io.

Thank you.

**Comment by jhen1422** [comment]
@dfnjy 
This issue has been resolved in the 4.9.0-rc2 of our builder.
