### ISSUE TITLE
How to get data by calling a class function using ajax instead of url

### ISSUE THREAD

**Issue by nexawo** [formio/formio.js#2398]
I am getting a data using URL as show in fig below.

I want to get the data direct from the method which I made in  my cs class instead of using Url 

![Capture](https://user-images.githubusercontent.com/55268813/74219076-92048d80-4ccd-11ea-809f-e40390f752b7.JPG)

**Comment by nexawo** [comment]
I want to get data as I am getting data using  app service as seen in below img.
![Capture](https://user-images.githubusercontent.com/55268813/74219184-ec055300-4ccd-11ea-8b8b-2e61e5df2ace.JPG)

**Comment by randallknutson** [comment]
I'm not sure what you mean by "cs class". If you want to get it from a variable, use the "Custom" option instead of url. Custom does not allow using ajax though as it is a synchronous function.

**Comment by nexawo** [comment]
> I'm not sure what you mean by "cs class". If you want to get it from a variable, use the "Custom" option instead of url. Custom does not allow using ajax though as it is a synchronous function.

let me correct my self it's a '.cs file' c# file I have a method define in .cs file and I want to call that method instead of URL
