### ISSUE TITLE
Tailwind CSS support?

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2401]
I'm wondering if there are any plans to add [Tailwind CSS](http://tailwindcss.com/) to the list of available [modules](https://github.com/formio/formio.js/wiki/Modules) at some point?

**Comment by randallknutson** [comment]
We are definitely open to supporting it but don't have any plans to resource it at the moment. Would this be something you would be interested in ether contributing or supporting development of?

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson. We're considering internally if this is something we're interested in pursuing right now.

**Comment by Romakita** [comment]
Hello Team and @randallknutson,

I worked on the adaption of tailwind/formio. You can found the repository here: https://github.com/TypedProject/tsed-formio/tree/master/packages/tailwind-formio
And a storybook to visualize all components: https://formio.tsed.io/

I also worked on a fork of react-formio to add more features (like your awesome saas solution). You can find a working example here: https://tsed-formio.herokuapp.com/backoffice/ (contact me for the login / password if you are interested)

Here some captures:

<img width="1005" alt="Capture d’écran 2021-03-05 à 09 19 37" src="https://user-images.githubusercontent.com/1763311/110087549-18d24f80-7d94-11eb-9e88-94a0d508de2d.png">
<img width="1226" alt="Capture d’écran 2021-03-05 à 09 19 51" src="https://user-images.githubusercontent.com/1763311/110087550-196ae600-7d94-11eb-95af-f982770f9d35.png">
<img width="1226" alt="Capture d’écran 2021-03-05 à 09 20 00" src="https://user-images.githubusercontent.com/1763311/110087552-1a9c1300-7d94-11eb-91d0-18d5ee874868.png">
<img width="1226" alt="Capture d’écran 2021-03-05 à 09 20 05" src="https://user-images.githubusercontent.com/1763311/110087555-1a9c1300-7d94-11eb-9047-f80617331f54.png">
<img width="1226" alt="Capture d’écran 2021-03-05 à 09 20 15" src="https://user-images.githubusercontent.com/1763311/110087559-1bcd4000-7d94-11eb-8b1c-42cd4eea2101.png">
<img width="1226" alt="Capture d’écran 2021-03-05 à 09 20 25" src="https://user-images.githubusercontent.com/1763311/110087561-1c65d680-7d94-11eb-8f62-1386962519f4.png">

if you are interested for the tailwind-formio template, tell me :)

See you
Romain

**Comment by Romakita** [comment]
Hello @peterycky 
Yes, plan a demo can be possible. 

I destroyed the backoffice given in my previous comment, but I can give you an access to the staging backoffice in PM. Just tell me how I can share you the access with you :) (I have also a Ts.ED slack access if it's ok for you: https://api.tsed.io/rest/slack/tsedio/tsed).
See you
Romain

**Comment by ThembaMahlangu** [comment]
I am using Vite to bundle react and for styling i use tailwindcss, since i integrated form.io I have this issue that the styling of the forms does not match the UI since im using Tailwindcss globally and isolating bootstrap to the component that has to do with form.io. Is there a solution to making the forms custom in tailwind or just a way to use tailwind?

**Comment by kmmastermind** [comment]
@Romakita or @peterycky I would also like to colab for react and angular. Can you provide me access for demo project?

**Comment by chaitanya-lakra** [comment]
> Hello Team and @randallknutson,
> 
> I worked on the adaption of tailwind/formio and more generally to the integration of formio with the Ts.ED framework. You can found the repository about tailwind template here: https://github.com/TypedProject/tsed-formio/tree/master/packages/tailwind-formio And a storybook to visualize all components: https://formio.tsed.io/
> 
> I also worked on a fork of react-formio to add more features (like your awesome saas solution). You can find a working example here: https://tsed-formio.herokuapp.com/backoffice/ (contact me for the login / password if you are interested)
> 
> Here some captures:
> 
> <img alt="Capture d’écran 2021-03-05 à 09 19 37" width="1005" src="https://user-images.githubusercontent.com/1763311/110087549-18d24f80-7d94-11eb-9e88-94a0d508de2d.png">
> 
> <img alt="Capture d’écran 2021-03-05 à 09 19 51" width="1226" src="https://user-images.githubusercontent.com/1763311/110087550-196ae600-7d94-11eb-95af-f982770f9d35.png">
> 
> <img alt="Capture d’écran 2021-03-05 à 09 20 00" width="1226" src="https://user-images.githubusercontent.com/1763311/110087552-1a9c1300-7d94-11eb-91d0-18d5ee874868.png">
> 
> <img alt="Capture d’écran 2021-03-05 à 09 20 05" width="1226" src="https://user-images.githubusercontent.com/1763311/110087555-1a9c1300-7d94-11eb-9047-f80617331f54.png">
> 
> <img alt="Capture d’écran 2021-03-05 à 09 20 15" width="1226" src="https://user-images.githubusercontent.com/1763311/110087559-1bcd4000-7d94-11eb-8b1c-42cd4eea2101.png">
> 
> <img alt="Capture d’écran 2021-03-05 à 09 20 25" width="1226" src="https://user-images.githubusercontent.com/1763311/110087561-1c65d680-7d94-11eb-8f62-1386962519f4.png">
> 
> if you are interested for the tailwind-formio template, tell me :)
> 
> See you Romain

can i use this in angular project

**Comment by Romakita** [comment]
@randallknutson it should be possible to reuse the tailwind configuration just by installing `@tsed/tailwind-formio`:

See:
https://github.com/tsedio/tsed-formio/tree/master/packages/tailwind-formio
