### ISSUE TITLE
storage provider issue

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#2409]
You used to be able to override storage providers for formio, but this fix broke that feature.

You used to be able to do:
        if (Formio.Providers) {
            if (Formio.Providers.providers) {
                Formio.Providers.providers.storage = { MyStorageProvider };
            }
        }

This fix https://github.com/formio/formio.js/commit/ae1e15e3610f3b5ed83abc0516f140cc7d067436#diff-a2a5f59c37aef0e9934fdf486149f6cf

Instead of MyStorageProvider it displays default list.

How do we override a default list of File Storage providers?

**Comment by randallknutson** [comment]
The reason we made that change was to create a custom way to override providers. You can now override them with modules. 

https://github.com/formio/formio.js/wiki/Modules
https://github.com/formio/module-example

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
