### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by praveenmadishetty** [formio/formio.js#2421]
## Environment
In my application, requirement is to save a form with elements( like TEXTBOX, CHECKBOX, and SELECT) as custom component in formio, which i have achieved. but the problem here raises when i have to edit the individual elements inside custom component(like CHECKBOX) which i saved.  How can we achieve this?

**Comment by wag110894** [comment]
Hello @praveenmadishetty, We do offer Support Packages that are for training, support or development services. The hours can be used in one hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please contact support@form.io if you are interested.

Thank you.
