### ISSUE TITLE
[BUG] Formbuilder cannot set default value for Address Field Component

### ISSUE THREAD

**Issue by dcoevoet51** [formio/formio.js#2431]
Hello,

I would like to set a default value for the Address Field Component in the builder but it doesn't work.

I have tried the default value field and the Custom Default Value in javascript but nothing works.

Do you have any information or trick to solve that?

I have created a similar ticket which was closed last year but the problem remains: https://github.com/formio/react-formio/issues/168

Thanks by advance,

Best regards,

**Comment by jhen1422** [comment]
@dcoevoet51 We are currently in the process of refactoring our Address component which will allow you to set a default value for this component. This refactor should be pushed out to our 'Next' portal soon which will contain the change.

**Comment by blochealth** [comment]
@jhen1422  refactor is now complete and this still does not work.

**Comment by wag110894** [comment]
@blochealth, 

It seems that is was working at one point but is not currently.
We have created a ticket for this issue and have added this to our backlog. We welcome a pull request or have a process to expedite this issue. For Reference, the ticket number is FJS-1098.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
