### ISSUE TITLE
Get curent tab

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2432]
Is it possible to get the tabkey when clicked?

Kind regards,
Mario

**Comment by randallknutson** [comment]
I'm not sure what you mean by this. Do you mean the tab index on the element during the click event?

**Comment by KyooMario** [comment]
Hello Randall,

I covered it using a server side script I call from a calculated value:

`window.getCurrentTab = function(component){
                        const tabs = form.getComponent(component);
                        //console.log('currentTab: '+tabs.currentTab);
                        return tabs.currentTab;
                    }`

Thanks.
Mario

**Comment by randallknutson** [comment]
Awesome. I didn't realize you meant the current tab of the tabs component. What you did looks correct.
