### ISSUE TITLE
[QUESTION] radio button roles

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2434]
Hi,

Is there a way to control the payload of 'Values' inside the radio button component.

I would like to display different Value options dependant on other data in the form.

I.e then if somewhere else on my form ( or via a role ) I can then say something like:

if (data.user === 'admin') {
 "values" = [
    {
      "label": "Print everything",
      "value": "admin"
    },
    {
      "label": "Print redacted",
      "value": "printRedacted",
      "shortcut": ""
    },
    {
      "label": "Print summary",
      "value": "printSummary",
      "shortcut": ""
    }
]
} else {
"values" = [
    {
      "label": "Print redacted",
      "value": "printRedacted",
      "shortcut": ""
    },
    {
      "label": "Print summary",
      "value": "printSummary",
      "shortcut": ""
    }
]

Thanks

Mark

**Comment by randallknutson** [comment]
In radio components this currently isn't possible. We have plans to create a "List" parent class that will handle a list of items similar to how the select component handles options and then base Select, Radio, Checkboxes and similar components on it so they all share this functionality.

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
