### ISSUE TITLE
Select dropdown box will not open

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2437]
I have got a strange situation. I have included FormIO including the select box in multiple pages where it works fine. But in one page the dropdown will not open, even when I choose for the modal edit.
Using the select widget type Html5 works also fine on this page.

So something that is also included (loaded) on the page is blocking this function.
Can you advise how I can investigate this?

Kind regards,
Mario

**Comment by KyooMario** [comment]
More info: The select box choices are in the html but the class "choices__list--dropdown" display is "none" so the choices are not revealed. In the parent div the "aria-expanded" stays "false"
So question: What may block the pointer event to change the class/aria-expanded.

Kind regards,
Mario

**Comment by travist** [comment]
We just upgraded the Choices.js version in the latest release 4.9.0-beta.6. Please try this version and see if this issue goes away.

**Comment by KyooMario** [comment]
I will give it a try. Thanks

**Comment by darshanc94** [comment]
I'm having the same issue on IE11. I think it may be an issue with choices.js.

**Comment by KyooMario** [comment]
I have installed and tested the latest release 4.9.0-beta.6 but my issue is still there unfortunately.
Second: this release introduced a rather annoying style issue caused by the Select box:
When I add several choice values with every addition the form height increases even with the select box closed. When I integrate the form in a div on a page this div gets a vertical scroll bar and when scrolling down I see an empty area with the height of the select choices.

**Comment by KyooMario** [comment]
Addition: The style issue occurs with the Select -ChoicesJS option. and does not occur with the Html 5 option.

**Comment by KyooMario** [comment]
Addition: When using Select - ChoicesJS option in "Modal Edit" mode the choices are hidden behind the modal height borders and thus not showing.

**Comment by KyooMario** [comment]
Hello Guys,

Any update on the choicesjs height issue in 4.9.0-beta.6 "When I add several choice values with every addition the form height increases even with the select box closed."

Kind regards,
Mario

**Comment by wag110894** [comment]
Hello @KyooMario,
Thank you for your patience while we got this issue resolved. This issue has been resolved with our latest version of formio.js: 4.9.20.

**Comment by KyooMario** [comment]
I will check. Thanks a lot.
