### ISSUE TITLE
Radio button check uncheck issue

### ISSUE THREAD

**Issue by webz2feel** [formio/formio.js#2438]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: js
- Browser: All browsers

I have a radio button question with options male and female where user can choose his gender by selecting one of the option. But the issue is if i select any of the radio option then click on it again it gets unchecked. While this should not be unchecked again once it is selected.

How i can stop this behavior? Is there any flag available for this or this is bug in code?

**Comment by randallknutson** [comment]
We actually added this functionality since someone else reported it as a bug that it couldn't be unselected. We think that this is the correct functionality since some users may want to unselect options if they accidentally click them. If a radio component needs to be required you can mark it as required in the validation and it will prevent saving without a value being selected.

**Comment by webz2feel** [comment]
> We actually added this functionality since someone else reported it as a bug that it couldn't be unselected. We think that this is the correct functionality since some users may want to unselect options if they accidentally click them. If a radio component needs to be required you can mark it as required in the validation and it will prevent saving without a value being selected.

It's good if this is the functionality, but it would be more better if there is flag introduce to turn on or off this functionality. User must has choice to enable or disable this behavior.

**Comment by randallknutson** [comment]
We are definitely open to adding an option to allow configuration of this feature. Is that something you would be able to add? It would involve adding a checkbox for the setting here: https://github.com/formio/formio.js/blob/master/src/components/radio/editForm/Radio.edit.display.js and then based on that setting you can bypass the uncheck functionality here https://github.com/formio/formio.js/blob/master/src/components/radio/Radio.js#L152-L158 by checking this.options.yournewsetting
