### ISSUE TITLE
Submit form button caption change

### ISSUE THREAD

**Issue by webz2feel** [formio/formio.js#2442]
I have wizard form and i want to change the caption of submit form button, default it is Submit Form so i want to change this with something else. I didn't find anything in documentation related to this. How i can change this text?
Also i want to hide cancel button but don't know how to do this. Someone help me.

**Comment by jhen1422** [comment]
@webz2feel Please review our docs on customizing wizards found here - https://formio.github.io/formio.js/app/examples/customwizard.html
