### ISSUE TITLE
[Question] Switching controls between build and render mode

### ISSUE THREAD

**Issue by gopi-sedin** [formio/formio.js#2443]
Is it possible to have the designer display a Select Control during build mode and have it rendered as a checkbox during the render mode? 

I have a scenario where during the form design the user need to select a value from a dropdown and once he sets that value. After this during the render mode, a checkbox needs to be rendered based of the value the user had set previously. 

Is this achievable?

**Comment by randallknutson** [comment]
You could do this with a custom component. Our built in components don't have any functionality like this but you could definitely do it with a custom component.

**Comment by gopi-sedin** [comment]
Thanks @randallknutson
How can I get the selected value in design mode to store it in the schema? 
I assume, I can use this stored value to render the other component in the render mode.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. 
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
