### ISSUE TITLE
Clear values on hidden not working

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#245]
I have some forms using custom/advanced logic conditionals and for every input in the form, I have the option Clear values on hidden. The functionality of hiding the elements on the condition works perfect, but when I display again the elements, the value remains unchanged (It doesn't clear).

I realized also that with simple conditional the clear functionality works intermittently.

The weird thing is that when using the Form.io preview it works perfectly.

Any ideas?

You can check the form in here. https://uiorzjzflxyccmo.form.io/household

Best Regards, 
Ignacio

Best Regards!

**Comment by MVTalent** [comment]
+

**Comment by wag110894** [comment]
Hello, 
Can you please clarify what exactly is the issue? We are unable to replicate this issue while using the latest formio.js as the values are being cleared. Here is a screencast of it working on our end.  https://www.screencast.com/t/3hunVnWP1sxQ 
Please let us know if you have any further questions or concerns.
 
Thanks,
William Gay 
Form.io Developer Support
