### ISSUE TITLE
Change labels for localization

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#2451]
## Environment
Please provide as many details as you can:

- Hosting type
- Formio.js version: "4.9.0-beta.8"
- Frontend framework: -
- Browser: Chrome
- Browser version: 79.0.3945.130

## Example
--Can you add localization for some labels/placeholders/content ?

1. path: "src/Webform.js" line: 1298
```if (shouldReset && (noconfirm || confirm('Are you sure you want to cancel?'))) {```
replace on
```if (shouldReset && (noconfirm || confirm(this.t('Are you sure you want to cancel?')))) {```

2. path: "src/components/_classes/component/Component.js" line: 930
```<button lang='en' class='btn btn-light btn-md open-modal-button' ref='openModal'>Click to set value</button>```
replace on 
```<button lang='en' class='btn btn-light btn-md open-modal-button' ref='openModal'>${this.t('Click to set value')}</button>```

3. path: "src/components/_classes/input/Input.js" line: 151
```this.setCounter('words', this.refs.wordcount[index], _.words(value).length, maxWords);```
replace on
```this.setCounter(this.t('words'), this.refs.wordcount[index], _.words(value).length, maxWords);```

4. path: "src/components/_classes/input/Input.js" line: 157
```this.setCounter('characters', this.refs.charcount[index], value.length, maxChars);```
replace on
```this.setCounter(this.t('characters'), this.refs.charcount[index], value.length, maxChars);```

5. path: "src/templates/bootstrap/componentModal/form.ejs" line: 12
```<button class="btn btn-success formio-dialog-button" ref="modalSave">Save</button>```
replace on
```<button class="btn btn-success formio-dialog-button" ref="modalSave">{{ctx.t('Save')}}</button>```

--Add localization for strings in Formio Builder
1. 'Basic components' -> 'Password' ->  In editor tabs(data)
 "Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API."
2. 'Advanced' -> 'Address' -> In editor tabs(display/data)
 "Can't find address? Switch to manual mode"
3. 'Premium' -> 'Resource' -> In editor tabs(display)
 "The Resource component is deprecated. Use the Select component with data source of "Resource" instead."
4. 'Premium' -> 'Custom' 
 "Custom components can be used to render special fields or widgets inside your app. For information on how to display in an app, see custom component documentation."

Thanks

**Comment by homashevchenko** [comment]
@travist You don't mind, if i create pull request for this?
Thanks

**Comment by wag110894** [comment]
@homashevchenko We welcome a pull request. 

Please let us know if you have any questions.

Looking forward to seeing what you come up with.

Thank you!

**Comment by homashevchenko** [comment]
@wag110894 Are there any possibilities to localize this: 
1. 'Basic components' -> 'Password' -> In editor tabs(data)
"Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API."
2. 'Advanced' -> 'Address' -> In editor tabs(display/data)
"Can't find address? Switch to manual mode"
3. 'Premium' -> 'Resource' -> In editor tabs(display)
"The Resource component is deprecated. Use the Select component with data source of "Resource" instead."
4. 'Premium' -> 'Custom'
"Custom components can be used to render special fields or widgets inside your app. For information on how to display in an app, see custom component documentation."

**Comment by randallknutson** [comment]
We want all strings to be able to localize so if there are any strings that don't pass through the t() function, please submit a pull request to fix it. Here is an example of a good pull request to do this: https://github.com/formio/formio.js/pull/2770

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
