### ISSUE TITLE
How to target wrapper div of select element in a module

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2455]
I'm writing a [Tailwind-based module](https://github.com/formio/formio.js/issues/2401) for formio.js, and I'm having trouble targeting the wrapper div for a `<select>` element. I've attached a screenshot showing the markup output by formio.js without a module used; the element I'm attempting to modify is the div with a `formio-choices` class name. I'd like to figure out how to alter the rendering of this element so I can add/remove class names.

Any guidance on how to target that element from my module would be extremely appreciated!
![CleanShot 2020-02-20 at 16 27 16@2x](https://user-images.githubusercontent.com/796639/74989592-0a6dfb80-53fe-11ea-9800-9532a5d924f5.png)

**Comment by randallknutson** [comment]
We are using the choices.js library to render the select components. This means that there is a line where the rendering switches from our library to the choices.js library. I did a quick search and found where that class is being added. https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L749. It is part of the choicesOptions passed to the choices component. You can modify the choices.js options in the settings of the select component or if you want to do it globally you will need to override the Select.js component.

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson, that's very helpful.

I see from [the docs](https://github.com/formio/formio.js/wiki/Custom-Components-API) how to register a custom component, but am not clear on how I should go about modifying the choices.js options in the settings of the select component. Any direction you can provide would be most welcome.

**Comment by randallknutson** [comment]
If you go to next.form.io, add a Select component and go to the "Data" tab you will see Choices options as a configuration option. That's the main way to set these right now. To do it programmatically would involve extending the Select component and overriding the defaults. We would be open to making it more customizable though.

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson – I was using portal.form.io which explains why I couldn't see that option.

Do you by chance have an example string I can paste in there that's tested as working? What I'm doing right now seems to be completely ignored; not sure where I'm going wrong:
```
"{ classNames: { containerOuter: 'form-input' } }"
```

**Comment by randallknutson** [comment]
This line right here should allow you to override the standard settings. https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L773

What you are doing looks correct. You may need to set a breakpoint in the select.js at that point and see if the settings are getting applied and if not, why not.

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson. Turns out my syntax was just off; for the sake of posterity here's an example of what works:
```
{
  "classNames": {
    "containerOuter": "classnames-go-here space-separated",
    "containerInner": "classnames-go-here space-separated"
  }
}
```

**Comment by TriStarGod** [comment]
@tnorthcutt Did you create tailwind module? Is it publicly available?
