### ISSUE TITLE
Formio Select component Number value issue

### ISSUE THREAD

**Issue by IrfanAli54** [formio/formio.js#2457]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version:  3.2.0
- Formio.js 3.2.0:
- Frontend framework Angular 7:
- Browser: Mozila Firefox, Google Chrom, Android , iOS
- Browser version:

## Steps to Reproduce
1. Add a select component on form
2. Set data source type to Values
3. Add some integer values in data
4. Set storage type to number
5. Submit form with 0 values selected for dropdown
6. Reload data in the form schema

## Expected behavior
User submitted 0 value should be set in the select component after reloading the  data into that form.

## Observed behavior
Form save 0 in the database but does not set 0 values to the select component after reloading form data in the form.

**Comment by wag110894** [comment]
Hello @IrfanAli54 

Can you try upgrading to the latest version of the 3x renderer and see if this issue still occurs? The latest version is 3.29.9.

Please let us know.

Thank you.

**Comment by gnoose** [comment]
Hello @wag110894 

Above issue happening on my side even thought I am using the latest version. Could you please update here what should i do?

Thank you.

**Comment by wag110894** [comment]
@gnoose,

Can you provide a JSFiddle of the issue?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
