### ISSUE TITLE
[BUG] Formio ES6 application 

### ISSUE THREAD

**Issue by samswbk** [formio/formio.js#2458]
I'm trying to do like the example:

`import Formio from 'formiojs';

formio = new Formio('https://examples.form.io/example');
formio.loadForm((form) => {
  console.log(form);
  formio.saveSubmission({data: {
    firstName: 'Joe',
    lastName: 'Smith',
    email: 'joe@example.com'
  }}).then((submission) => {
    console.log(submission);
  });
});`

but i'm getting this error:
Cannot find module './classes' from 'C:\Users\es6-gulp\node_modules\dragula\dist'

Any tip?

**Comment by randallknutson** [comment]
We aren't seeing this error when building es6 and typescript apps using formio.js. One thing you can try is to use destructuring with import { Formio } from 'formiojs'; That might fix it.

**Comment by samswbk** [comment]
@randallknutson getting the same error.

i use npm install --save-dev formiojs

**Comment by randallknutson** [comment]
I'm really not sure what is going on with your build tools. We don't really use browserify anymore as we pretty much just use typescript and webpack at this point. If you find something in our system that is causing this, let us know and we can fix it.

**Comment by samswbk** [comment]
@randallknutson i will try find out. Thank you for the support.

**Comment by marcus-at-localhost** [comment]
@samswbk did you find a solution?
