### ISSUE TITLE
[BUG] DataGrid: "rebuild" object property is misspelled

### ISSUE THREAD

**Issue by azizk** [formio/formio.js#2459]
Just a quick report. The property "rebuild" is misspelled in DataGrid.js as "rebuld".

https://github.com/formio/formio.js/blob/61a6951c3abf2ddf0aef3e5b3995c6091230719a/src/components/datagrid/DataGrid.js#L477

**Comment by randallknutson** [comment]
Thanks. I did a quick fix. https://github.com/formio/formio.js/commit/acb5c875f79f80b3585afe5a5a62919f99841d43#diff-f068ff3923fb05ef8c7b1e977123ca28
