### ISSUE TITLE
How define size for columns in datagrid?

### ISSUE THREAD

**Issue by bigjorjao** [formio/formio.js#2460]
I have a datagrid for example with three fields(columns).
I wanted to define the size of each one.
For example, the first occupy 10%, the second 60 and the third 30%.
How can I do this?

**Comment by randallknutson** [comment]
The datagrid uses a table component and there currently aren't any options in the UI for defining width. You can override this in the template to add your own classes or styles directly. https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/datagrid/form.ejs#L32-L36

If all you want to do is define some hard coded widths, you can do that directly by writing some CSS to set the width of the columns for that component.

**Comment by qodrinzo** [comment]
+1

**Comment by emmanuel2804** [comment]
+1

**Comment by cezavaletal** [comment]
+1

**Comment by prashantsail** [comment]
+1

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
