### ISSUE TITLE
redraw (component

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2466]
The basic problem is that I am having a hard time to redraw a specific container -> field in the form. Other containers work fine but one container -> field is not redrawn when a value is set.
It might be that I am using the field api "Id" more then once but I need to because I read/write from/to multiple data sources that use an "Id".

Now my solution is to use "redraw" but I have a strange behavior on this.
My function looks like:
`window.redrawThis = function(component){
	console.log('component: '+component);
	const thisComponent = form.getComponent(component);
	thisComponent.redraw();
}` 

Now when I call the function with a component name in quotes like redrawThis('componentName'); It does not work but if I call the function without quotes like redrawThis(componentName);
the component or the form (I cannot tell) is redrawn fine.
But this cannot be right because the componentName without quotes should read as a variable.

So the main question is can you tell me the correct way to redraw a component?

Kind regards,
Mario

**Comment by randallknutson** [comment]
You are correct that without the quotes it would read the variable which doesn't seem right. I guess the question is what is being passed into the function as the component name when that happens. It is possible that when you use the componentName without quotes it is passed in as null which would cause the redraw to redraw the form instead of the individual component which would explain why it appears to work.

**Comment by KyooMario** [comment]
If I want to target a field inside a container how do I find this component?

**Comment by travist** [comment]
```getComponent``` traverses even other nested components. Let us know if it is not, but even in containers it should work.

**Comment by KyooMario** [comment]
Hello Travis,

Suppose I have multiple Fields with api "Id". What do I get returned?

Kind regards,
Mario

**Comment by randallknutson** [comment]
You are going to get the first one it encounters. If you are trying to get one nested in a container, you can do that by first getting the container by ID and then getting the component from within it using getComponent from within that container.

**Comment by KyooMario** [comment]
Hello Randall,

Can you pass a small code snippet on how this would work?

Kind regards,
Mario

**Comment by randallknutson** [comment]
It would be something like this:

const containerComp = form.getComponent('myContainer');
const myComp = containerComp.getComponent('myComponent');

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
