### ISSUE TITLE
Can I do serverside validation before sumission and display the errors under each field?

### ISSUE THREAD

**Issue by gfPedro** [formio/formio.js#2467]
Hello,

I have been messing around with serverside validation.
With similar code to the one showed in the wiki, I get all my errors to be displayed at the top of my forms. 

Sometimes there could be a lot of errors. In order to make my forms more user-friendly I would like to know if those errors can be displayed near the corresponding field.

As mentioned before, I managed to display all errors at the top by passing an array of strings or an array of objects with property _message_ as argument to the function next.

Reference code from the wiki:

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
  hooks: {
    beforeSubmit: (submission, next) => {
      // Make a custom ajax call.
      $.ajax({
        url: 'https://myserver.com/validate',
        method: 'POST',
        data: submission,
        complete: (errors) => {
          let submitErrors = null;
          if (errors) {
            submitErrors = [];
            errors.forEach((error) => {
              submitErrors.push({
                message: error.toString()
              });
            });
          }
          next(submitErrors);
        }
      });
    }
  }
})

```

**Comment by randallknutson** [comment]
You should probably use the customValidation hook instead. https://github.com/formio/formio.js/blob/master/src/Webform.js#L1353-L1371

If you return an array of errors where the errors are objects with the message and key, it will find the field with the key and add highlighting to the field.

**Comment by donnyv** [comment]
@randallknutson Is there documentation for this customValidation hook? Like a small sample?
