### ISSUE TITLE
wizard breadcrumb click event

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#2470]
Hi @randallknutson @travist, Is there any way to get a change event when clicking on the breadcrumb in the wizard. I find some **Next Page and Previous page events** when clicking on the next and previous buttons. But I want some requirements to hide components when chicking on breadcrumb.

![image](https://user-images.githubusercontent.com/48546522/75258511-91f7a800-580c-11ea-9e63-a95c4771c0ad.png)

**Comment by randallknutson** [comment]
There is an event called here that you can use: https://github.com/formio/formio.js/blob/master/src/Wizard.js#L218

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by lakim** [comment]
The wizard events are documented here:
https://github.com/formio/formio.js/wiki/Form-Renderer/b1af7f7d8f9857cb2dbf72756c75d3d75a89e60b#events

Quick reference:
- prevPage
- nextPage
- wizardNavigationClicked
- wizardPageSelected
