### ISSUE TITLE
[Help] Setting language FormBuilder

### ISSUE THREAD

**Issue by samswbk** [formio/formio.js#2473]
There's a way to set the builder language dynamically without new instance of Formio.FormioBuilder();?
Something like the setDisplay?

formBuilder.setDisplay(display).then(onReady);

**Comment by randallknutson** [comment]
You should be able to set the language directly on the formBuilder with formBuilder.language = '';

**Comment by samswbk** [comment]
@randallknutson  thanks for reply! 
I try:
`function setLanguage(lang) {
    formBuilder.language = lang;
    formBuilder.instance.redraw().then(onReady);
};`
but didn't work, here's my builder instance:
`formBuilder = new Formio.FormBuilder(document.getElementById('builder'), form, {
        noDefaultSubmitButton: true,
        builder: builder,
        language: language,
        i18n: defaultTranslate,
        editForm: editForm
    });`

**Comment by randallknutson** [comment]
I'm not entirely sure how to do this off the top of my head. Looking at the code there doesn't seem to be a language setting on WebformBuilder so it can't be modified directly. You can try setting formBuilder.webform.language and see if that works. Other than that you could try changing the language in the options and calling redraw() or rebuild() on the form builder.

**Comment by samswbk** [comment]
@randallknutson  thanks again for reply! I got it, used it:

`formBuilder.instance.webform.language = lang;`  

instead of:

 `formBuilder.webform.language = lang`

then redraw's the builder:

`formBuilder.instance.redraw();`
