### ISSUE TITLE
[BUG] Cleari

### ISSUE THREAD

**Issue by helmantel** [formio/formio.js#2476]
## Environment

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 1.70.0
- Formio.js version: 4.8.1
- Frontend framework: Vue or Plain HTML
- Browser: Chrome
- Browser version: 79.0.3945.130 (Official Build) (64-bit)

## Steps to Reproduce
1. Add a Day Component to the form in Form.io
2. Adjust it so that it isn't required and uses custom validation like: `valid = '00/00/0000' || /^([0-2][0-9]|(3)[0-1])(\/)(((0)[0-9])|((1)[0-2]))(\/)(19|20)\d{2}$/.test(input);` In other words, the date must be a valid date or the default value.
3. Render the form using Formio.js and fill in a valid day, month and year
4. Clear day, month and year

## Expected behavior
Clearing the day, month and year should result in a valid date since we're back to the default value.

## Observed behavior
The result after clearing day, month and year is an invalid date. The last change event isn't fired because clearing the last character of either day, month or year results in the default value, making it unchanged.
 
## Example
Example video: https://drive.google.com/file/d/14Ss_mblCwKOl_fNTC_EIPElwaIF-V_AU/view

**Comment by wag110894** [comment]
Hello @helmantel, 

We have created a ticket and have added this to our backlog. We welcome a pull request or have a process to expedite if you are interested.  Please contact support@form.io if you are interested in expediting this for you.

Thank you,

William Gay

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
