### ISSUE TITLE
[BUG] Hidden field defaultValue inherits type of 'hidden'.

### ISSUE THREAD

**Issue by jheagle** [formio/formio.js#2477]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.8.1
- Frontend framework: JS
- Browser: Firefox, Chrome
- Browser version:

## Steps to Reproduce
1. In the form builder, add a hidden component
2. Open the config menu and in the data tab, the defaultValue input field is not visible
3. 

## Expected behavior
The defaultValue is very useful on the hidden component as there may be some additional values to be sent with the form submission. The alternative of customDefaultValue is needlessly cumbersome for this use-case.

## Observed behavior
In WebformBuilder, the updateComponent function updates the defaultValue to have the same type and inputType as the hidden component it corresponds to.

## Example

This line:
```js
_lodash.default.assign(defaultValueComponent.component, _lodash.default.omit(component, ['key', 'label', 'placeholder', 'tooltip', 'hidden', 'autofocus', 'validate', 'disabled', 'defaultValue', 'customDefaultValue', 'calculateValue', 'conditional', 'customConditional']));
```

Might be better if preceded as follows:
```js
let omitArray = ['key', 'label', 'placeholder', 'tooltip', 'hidden', 'autofocus', 'validate', 'disabled', 'defaultValue', 'customDefaultValue', 'calculateValue', 'conditional', 'customConditional']
if (component.type === 'hidden'){
  omitArray = omitArray.concat(['inputType', 'type'])
}
_lodash.default.assign(defaultValueComponent.component, _lodash.default.omit(component, omitArray));
```

I can create a PR for this, but there may be some advantage to making this configurable via the editForm settings. As-is, any customization with regards to the defaultValue are immediately overridden in this one line.

**Comment by jhen1422** [comment]
@jheagle This issue is resolved in the latest version of formio.js
