### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jacklau88** [formio/formio.js#2480]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:4.X
- Frontend framework:
- Browser:Chrome
- Browser version: 80

Why does not work with the option 'viewAsHtml=true' in ver 4.x.?

**Comment by tnorthcutt** [comment]
@jacklau88 FYI, it would make the issues listing here more useful and usable for everyone if you included a short description of the problem you're experiencing in the title of the issue.

N.B. I'm just a user of Form.io, not associated with their organization.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
