### ISSUE TITLE
[BUG] Unknown component: datasource

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2482]
Reproduction here: https://jsfiddle.net/tnorthcutt/rq6tf14v/3/

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: `4.9.0-rc.2`
- Frontend framework: n/a
- Browser: Chrome/Mac
- Browser version: `80.0.3987.122`

## Steps to Reproduce
1. Load a form with a `datasource` component

## Expected behavior
The datasource component will be rendered

## Observed behavior
An error message is shown: "Unknown component: datasource"

## Example
https://jsfiddle.net/tnorthcutt/rq6tf14v/3/

**Comment by randallknutson** [comment]
Datasource is a premium component that is not included with our open source renderer or builder. If this is a component you would like to use, we can connect you with sales on how to get it.

**Comment by tnorthcutt** [comment]
Thanks @randallknutson. We're on an enterprise plan; I'll email our support contact for details on how to use this.

**Comment by timpamungkasudemy** [comment]
Hi, any update on this? I also use enterprise plan, and still got this error

**Comment by wag110894** [comment]
Hello @timpamungkasudemy, 

Please contact sales@form.io in order to have access to our premium components. 

Thank you.
