### ISSUE TITLE
Clear on submit

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2484]
Hi,

Is there an option to only clear hidden fields on submit and only fields that were hidden as a result of conditional logic.

For example if there is a panel component and the end user colapses the panel then these are technically not hidden and should be submitted (not sure what the action at the moment is).

But is a user answers a question with a yes, that unhides a textbox which the user then completes. Later they then change their mind and select no. The textbox hides due to the conditional logic correctly but at that point should retain the data. On submit as the textbox is still hidden we should then not submit the data.

By doing that we allow for the user to change their mind again and not have to retype any data they had previously entered.

Thanks

Mark

**Comment by randallknutson** [comment]
There is an option on all fields of "Clear Value When Hidden". This will do exactly what it says. However, we don't consider a collapsed panel or tab page that is out of view as hidden. Those are just not displayed. So, if a not displayed component switches from visible to hidden, it will clear its value if "Clear Value When Hidden" is selected. If not, it won't clear.

**Comment by gavinorland** [comment]
Hi @randallknutson. I'm working on the same project as Mark, above. Just having another look at this one now. I've written out the flow mainly just to remind myself and will paste it here:

In the Data setting for a component, if "Clear value when hidden" is selected, then the component is hidden via a conditional, its property and value are _not_ submitted with the payload. However, if the user reveals the component again via a conditional, the the previous value is not remembered.

If "Clear value when hidden" is _not_ selected, then when the user hides the component via a conditional, its value is still submitted with the payload. The benefit is that if they choose to show the component again via a conditional, the previous value they selected (or entered) is shown.

What we want is to be able to say that if a previously selected component is hidden via a conditional, the form should remember its value in case we open it again, but it should not include that value in the payload _unless the component is visible at submission time_. Best of both worlds!

The trouble is, it seems the form remembers the value of a component _because_ it is stored in the payload - or at least these two seem very tightly related, so perhaps the functionality we're describing is not supported?

**Comment by randallknutson** [comment]
I think I understand your question better now. We don't explicitly support what you are asking for. The ability to store and save the value doesn't take into account whether a component is visible or not (but does if it is conditionally hidden or not). I thought it might be possible to use default values to have values that only show up if a user views a component but I think even that triggers too soon.

**Comment by gavinorland** [comment]
Hi @randallknutson. Yes, I'm not sure default values would work for us as we would really want to to be "live" and reflect whatever the user had last entered.

It looks like if we don't want to be submitting values of components which have since been conditionally hidden, we'll have to use "Clear value when hidden" and accept that the user will have to enter any values again when "un-hiding". Thanks anyway!

**Comment by randallknutson** [comment]
Sure thing! Good luck!
