### ISSUE TITLE
[BUG] Translate component options

### ISSUE THREAD

**Issue by samswbk** [formio/formio.js#2485]
I changing the language of the builder dinamically, in the first time, its working fine outside(builder components list) and inside(component options). 

But if i change the language for the second time, applies only outside of builder, inside of component options previous translate remains.

Here's the function that change language:

`function setLanguage(lang) {
    formBuilder.instance.webform.language = lang;
    formBuilder.instance.redraw();
};`

Here's my default translation:

`export default {
    "pt": {
        "Text Field": "Campo de texto"
	}
}`

Here's builder configuration:

`formBuilder = new Formio.FormBuilder(document.getElementById('builder'), form, {
        noDefaultSubmitButton: true,
        builder: builder,
        language: language,
        i18n: defaultTranslate,
        editForm: editForm
    });`

**Comment by randallknutson** [comment]
Sounds like the i18n object or some other object is not passing down correctly into the form builder. Either that or the whole thing is not redrawing correctly. We can add this to our backlog to look into, send you some information to expedite a fix for it, or we would love someone to take a look and submit a pull request to fix it.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
