### ISSUE TITLE
[ASK] How customise formbuilder with editForm 

### ISSUE THREAD

**Issue by starker-xp** [formio/formio.js#2489]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.7.8
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
I want to customize the form editor. On a field of type 'select' I want to delete the data sources 'resource' and 'indexeddb'. Do you have an example?
``` {
   editForm: {
    textfield: [
      {
        key: 'logic',
        ignore: true,
      },
      {
        key: 'layout',
        ignore: true,
      },
    ],
    select: [
      {
        key: 'data',
        ignore: false,
        components: [
          {
            key: 'dataSrc',
            ignore: false,
            tooltip: 'My new tooltip',  // Not working
            label: 'Custom Label', // Not working
            data: {  // Not working
              values: [ // Not working
                {label: 'Values',value: 'values'}, // Not working
                {label: 'URL',value: 'url'}, // Not working
                {label: 'Custom',value: 'custom'},  // Not working
                {label: 'Raw JSON',value: 'json'} // Not working
              ]
            }
          },
        ],
      },
    ],
  },
}```

## Expected behavior
I want remove option in Data Source Type select

**Comment by wag110894** [comment]
Hello @starker-xp , Have you taken a look at this example: https://formio.github.io/formio.js/app/examples/custombuilder.html?

Looking forward to your response.

**Comment by starker-xp** [comment]
Hello @wag110894, I have already seen this example. The documentation does not cover my request. I want to customize certain fields not to deactivate them.

I want customise this select with remove 2 options.
[https://imgur.com/a/6al6xNV](url)

**Comment by wag110894** [comment]
Can you resend the imgur?

**Comment by starker-xp** [comment]
sorry 
https://imgur.com/a/MmvIDKa

**Comment by starker-xp** [comment]
Do you have an idea @wag110894 ?
Looking forward to your response.

**Comment by wag110894** [comment]
Hello @starker-xp,

We would need to investigate how to accomplish this a part of a support package.  Please let us know if you are interested by reaching out to support@form.io.

The other option would be to read the source code and try to figure it out how to accomplish this.

I hope that this helps.

Thank you.

**Comment by yuzdeng** [comment]
Hello,  @wag110894,
Is there any update here. I checked the source code. The default config of the system can not be changed by outside. The `unifyComponents` function only merge the `key` that system don't have. If the key that system already have the config from outside will not take effect. 

So is there any possible that changing the `unifyComponents` function to make it merge the config from outside?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
