### ISSUE TITLE
Datagrid start with null rows

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#2490]
My use case is a datagrid with som datetime and text fields. 
I have disabled add/remove rows and added a custom add button.
All works well but I want to start the datagrid with null rows.
I don't find an option how to do this?
Please advise.

Kind regards,
Mario

**Comment by randallknutson** [comment]
We've been able to accomplish this by setting the minlength and maxlength to however long you want it to be. It was either that or setting the calculated default value to an array of empty objects to the length you want the rows.

**Comment by KyooMario** [comment]
Hum. "setting the minlength and maxlength to however long you want it to be"
Not sure I understand. Do you mean the row length?
Can you give me the FormNuilder Json schema?

Kind regards,
Mario

**Comment by randallknutson** [comment]
In the validation there should be a minlength and maxlength setting for the datagrid. If you set those to the same number it should preset the rows to that length.
