### ISSUE TITLE
Button Configuration Issues in Wizard form Type

### ISSUE THREAD

**Issue by Abd-Zinghr** [formio/formio.js#2492]
When I keep form type as Wizard in formio default submit button configurations are not available
Also if I can handle Next & Previous button would be great help 

Kindly help !!

**Comment by randallknutson** [comment]
Because of the nature of the wizard buttons they are a little more opinionated on how they work on the form. There are a few ways of modifying them which you can find here: https://github.com/formio/formio.js/blob/master/src/Wizard.js#L13

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
