### ISSUE TITLE
[BUG] nested form with required field - Spinning Next button

### ISSUE THREAD

**Issue by gismomtl** [formio/formio.js#2497]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io

- Formio.js version: 1.9.0-rc3

if we have a wizard, with a nested form at specific page. Inside the nested form, a required field is required.
if we click directly the Next button, the required error message is displayed.. and the Next Button is spinning.. without being able to restore the state (even if we resolved the required field, the button remain spinning...)

if I change to formio.js 1.8.0-rc12 issue is not occuring.. 

https://jsfiddle.net/rguich/3f24dcx1/4/

everything is perhaps linked to 
https://github.com/formio/formio.js/issues/2496

**Comment by wag110894** [comment]
Hello @gismomtl, 

We are able to replicate this issue on our side. We have created a ticket and have added this to our backlog. We welcome a pull request or have a process to expedite if you are interested. Please contact support@form.io if you are interested. 

Thank you,

William Gay

**Comment by gismomtl** [comment]
latest formio.js versions 4.9.0-rc.8 and up solved the issue
