### ISSUE TITLE
[Question] How to add a nested form

### ISSUE THREAD

**Issue by 4gsim** [formio/formio.js#2498]

**Comment by 4gsim** [comment]
I am trying to create a nested form within a parent form. It should work something like adding a button in the parent form. When you click the button a modal should open with the nested form. When you press the submit button on the modal an action should be executed without interfering with the parent form. Is this possible?

**Comment by randallknutson** [comment]
This depends on what you mean by "action". Our buttons have the ability to do several different things such as fire events or submit the form. Some of these operate independently of the parent form but I'm not sure if submitting the form can be done separate from the parent form. You can try it out and see how it works.

**Comment by 4gsim** [comment]
When I am trying to add the nested form with the modal edit option set, nothing is visible on the parent form. You cannot open the nested form.

**Comment by wag110894** [comment]
@4gsim,

We are able to replicate the issue on our side. We have created a ticket and have added it to our backlog. We welcome a pull request or have a process to expedite this issue. If you are interested, please contact support@form.io. 

Have a great day.

William Gay

**Comment by jhen1422** [comment]
@4gsim This issue has been resolved in version 4.10.0-rc9
