### ISSUE TITLE
CustomProperties does not get saved in a revision form definitions

### ISSUE THREAD

**Issue by Yobikap** [formio/formio.js#2502]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework: Angular
- Browser: Chrome
- Browser version: Version 80.0.3987.122 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a form in devPortal or form manager
2. Go to devPortal and go to the settings of the form
3. In custom properties, add some values
4. Save the form
5. Do a API /form request with the formID to form.io
6. properties key is showing the data
7. Do again a API to /form/v call
8. You get all the revisions and none of the revisions will have the properties key

## Expected behavior
Each form revision has it's own properties

**Comment by randallknutson** [comment]
You are correct. Revisions were created before we had custom properties and so haven't taken them into account.

**Comment by Yobikap** [comment]
@randallknutson will this be in the planning?

**Comment by wag110894** [comment]
Hello @Yobikap, 

Thank you for your patience. We think that this would be a great addition to our platform. Please contact support@form.io if you are interested in sponsoring this platform enhancement.

Thank you.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
