### ISSUE TITLE
Camera issue with file upload component 

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#2504]
Hi, @travist @randallknutson I am using the file upload component in the form the file component showing with two options i.e upload and use camera. When I render the form in android devices, it's picking front camera only there is no such option to switch the rare camera. When  I render the form in IOS devices then the camera option is not working.

**Comment by randallknutson** [comment]
I'm not sure this is something we have control over. Our library just asks the browser for an image and it is up to the browser to provide access to the cameras. If Android is working strangely, there isn't a lot we can do about it.

**Comment by srinisubramanian** [comment]
@randallknutson We observe different behavior on iOS and Android.
iOS :  The link does not work.  However when the file option is chosen both File and Camera options are available and work correctly.
Android:  The link works but allows only front camera.  The file option does not show camera at all.
Suggestion:  Maybe remove the link altogether and make Android/iOS same?  Choose File and show both Gallery/Camera and Files?

**Comment by wag110894** [comment]
Hello all,

This issue has been resolved on version 4.9.0-rc.3 of our Core Renderer.
