### ISSUE TITLE
[BUG] Handling array as value returns only first element

### ISSUE THREAD

**Issue by dorianEXOR** [formio/formio.js#2506]
Hey form.io,

I am trying to receive an array with a custom component. 
The issue is that I was only able to get the first array value. Multiple is set to true, that's why I did some debugging.

The loop is breaking after setting the first element and I can't figure out why.
this.refs.input has size 2 and this.refs.input.hasOwnProperty(i) returns true for both elements. 
isArray returns true as well. 

The loop of concern is at Component.js:2034:
```
      for (var i in this.refs.input) {
        if (this.refs.input.hasOwnProperty(i)) {
          this.setValueAt(i, isArray ? value[i] : value, flags);
        }
      }

      return changed;
    }
{
    key: "setValueAt",
    value: function setValueAt(index, value, flags) {
      flags = flags || {};

      if (!flags.noDefault && (value === null || value === undefined) && !this.component.multiple) {
        value = this.defaultValue;
      }

      var input = this.performInputMapping(this.refs.input[index]);

      if (input.mask) {
        input.mask.textMaskInputElement.update(value);
      } else if (input.widget && input.widget.setValue) {
        input.widget.setValue(value);
      } else {
        input.value = value;
      }
    }
  }
```
The debugger also executed the following if.
```
else if (input.widget && input.widget.setValue) {
        input.widget.setValue(value);
```

Kind regards,
Dorian

**Comment by wag110894** [comment]
Hello Dorian,

Thank you for reaching out!

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please contact support@form.io for more information.

Thank you,

William Gay

**Comment by travist** [comment]
The easiest way to fully control your custom component to accept different data structures for a data type is to override the setValue method to force the value to whatever you need it to be.  The DataMap component kind of does this already (but with a object as its data type). Here is some pseudocode on how you can override the setValue method to fully control how values are set.

```js
class ArrayComponent extends Component {
    ...
    ...  NORMAL COMPONENT EXTEND CODE HERE ...
    ...

    get emptyValue() {
      return [];
    }

    setValue(value, flags = {}) {
       const changed = this.hasChanged(value, this.dataValue);
       this.dataValue = value;

       // Update the DOM elements here....  like input.value = value[0];

       this.updateOnChange(flags, changed);
       return changed;
    }

}
```

**Comment by dorianEXOR** [comment]
Thank you. This directly worked. 

Best regards,
Dorian

**Comment by Mkaith** [comment]
@dorianEXOR how did it worked can you pls share the repo?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
