### ISSUE TITLE
How to sort rows in DataGrid

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#2510]
Hi,

Is there any way sort the rows in a data grid? 
For example can a user grab a row from the bottom of the list to the top of the list in form.io renderer?

**Comment by randallknutson** [comment]
When using our current version of the renderer/builder there is an "Allow Reorder" option that adds drag and drop capabilities. You can see this on next.form.io.

**Comment by AnthonyPhan** [comment]
@randallknutson That worked perfectly Thanks!

Amazed at how easy that was..

**Comment by rahulseth625** [comment]
hi ....i am using formio react redux  starter kit there is an option for Allow Reorder but its not working. How can i sort and filter the data grid ...can you please help me .

Thanks in advance...!!

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
