### ISSUE TITLE
[BUG] Hidden text field does not contain an <input> element

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2513]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
    - Version: 
- Formio.js version: latest
- Frontend framework: n/a
- Browser: Chrome
- Browser version: v80

## Steps to Reproduce
1. Add a text field to a form and check "Hidden" in the field's settings
2. Render the form: https://jsfiddle.net/tnorthcutt/rq6tf14v/4/

## Expected behavior
A hidden `<input>` element will exist

## Observed behavior
No `<input>` element exists

## Example
https://jsfiddle.net/tnorthcutt/rq6tf14v/4/

## Screenshot: 
![CleanShot 2020-03-09 at 14 40 11@2x](https://user-images.githubusercontent.com/796639/76255618-14706680-6214-11ea-9331-6f645e8605b3.png)

**Comment by travist** [comment]
We are curious why this is a problem. If you need to set the value of the input, you should be doing this from the renderer like this.

```js
const textField = form.getComponent('textfield');
textField.setValue('hello');
```

**Comment by tnorthcutt** [comment]
@travist thanks, I wasn't previously aware of that option. I'll go that route.
