### ISSUE TITLE
Font Awesome v5 icons issue

### ISSUE THREAD

**Issue by sureshece9999** [formio/formio.js#2516]
Hi, @travist @randallknutson I am using Font Awesome 5 pro version in my application when I render the Form some Font Awesome icons are missing and not rendering properly. For your reference please check the below attachments.

![image](https://user-images.githubusercontent.com/48546522/76324240-bb83f980-630b-11ea-8d95-c8f81a83ea5c.png)

![image](https://user-images.githubusercontent.com/48546522/76324324-d8b8c800-630b-11ea-90b7-d5f4b2f83eb0.png)

**Comment by randallknutson** [comment]
Is there something that can be done to fix this? You can always override the icon classes by writing a module that implements iconClass like this: https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/iconClass.js

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
