### ISSUE TITLE
[Question] custom scripts added to form-io components giving syntax error in IE

### ISSUE THREAD

**Issue by ullas1989** [formio/formio.js#2520]
It looks like we cannot use modern javascript methods (e.g. forEach, find) for scripts written inside formio custom components (e.g. data, conditional) specifically for IE (11).

Can anyone please confirm if that is true or not. If true is there a way to resolve this?

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
