### ISSUE TITLE
[BUG] XSS issue in tooltip filed of component

### ISSUE THREAD

**Issue by uppalabharath** [formio/formio.js#2523]
## Environment
Please provide as many details as you can:
- Formio.js version: version hosted on http://formio.github.io/formio.js/app/builder

## Steps to Reproduce
1.  Drag and drop a component like text field
2. in the tooltip add {{constructor.constructor("alert('xss')")() }}
3. try to save the component

## Observed behavior
The expression is evaluated
## Example

Gif showing the issue.. 

![xss_formio](https://user-images.githubusercontent.com/16371262/76520243-8cdf5d80-6488-11ea-9fcc-dd1113e2586a.gif)

**Comment by jhen1422** [comment]
@uppalabharath 
Thank you for the report. We were able to replicate this issue on our end as well and have added this issue high on our priority list.

**Comment by randallknutson** [comment]
Thanks for the report. Due to this being security related, we are going to remove it from the site while we work on a fix.
