### ISSUE TITLE
Get updated json  value while change component using drag and drop

### ISSUE THREAD

**Issue by Akash1842** [formio/formio.js#2528]
![Survey](https://user-images.githubusercontent.com/51994133/76619934-10b14c80-6552-11ea-9b4a-0e38be855b91.png)

While i am change place of  Radio component and put in place of Text Field where i can get updated json in form io builder

**Comment by randallknutson** [comment]
There should be an event triggered. I believe it is "addComponent" (https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L829) that you can listen to.

**Comment by Akash1842** [comment]
If it possible to called this event in my javascript code

**Comment by randallknutson** [comment]
You don't call the event, you listen for the event which is fired when the save or drop occurs. You can listen by using either using whatever framework wrapper you are using's event system or if you are using formio.js directly you can use formio.on('addComponent', () => {})
