### ISSUE TITLE
How to add an action button in DataGrid 

### ISSUE THREAD

**Issue by HajarMousavi** [formio/formio.js#2535]
hi,
How to add an action button in DataGrid(dataGrid1), 
and by click on this button, fill another DataGrid(dataGrid2)...
plz help me...

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
