### ISSUE TITLE
[BUG] Select element dropdown not fully shown in edit modal (CSS)

### ISSUE THREAD

**Issue by dfnjy** [formio/formio.js#2540]
## Environment
Please provide as many details as you can:

reproducible in https://formio.github.io/formio.js/app/builder
I'm trying to create a custom component that contains only a label and a dropdown component in edit modal but encountered this issue.

## Steps to Reproduce
1. drag and drop a component
2. in edit modal, remove everything else except a select component (make modal smaller)
3. expand the dropdown

![image](https://user-images.githubusercontent.com/5002016/76809372-d214cf80-67a7-11ea-9e26-06d2fc0d00aa.png)

**Comment by Clode03** [comment]
Hello,

I have the same problem as you....
Have you found a solution? 

Thank you

**Comment by Clode03** [comment]
Hi
I solved this problem by applying CSS rules

    .choices__list--dropdown.is-active {
        visibility: visible;
        position: relative;
    }


this way you will have an expansion of the main panel when you open the Select Dropdown.

bye

**Comment by marcus-at-localhost** [comment]
I managed to get the dropdown over the modal by adding this:

```css
.component-edit-container {
    overflow: visible;
}
```

Before:

![image](https://user-images.githubusercontent.com/1337223/107856610-9821d280-6e29-11eb-824c-730a1c58cb5d.png)


After:

![image](https://user-images.githubusercontent.com/1337223/107856662-ed5de400-6e29-11eb-92f9-e107772bd92c.png)

Not sure if this has implications somewhere else :)

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
