### ISSUE TITLE
[BUG] Radio buttons with numeric value not persisting on page change

### ISSUE THREAD

**Issue by adamturtle** [formio/formio.js#2547]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: vanilla js
- Browser: all
- Browser version:

## Steps to Reproduce
1. Create a wizard form with two pages
2. On the first page, create a radio field with values that are numeric. Labels don't matter
3. One the next page, create any field type. Doesn't matter
4. View the rendered form, choose an option from the radio field on the first page
5. Navigate to the second page, then navigate back

## Expected behavior
The radio field should still contain the user selection

## Observed behavior
The radio field has been cleared

## Example
https://jsfiddle.net/wvq92o4r/

You can use this form definition:

```js
{
  "display": "wizard",
  "components": [
        {
            "title": "Page 1",
            "label": "Page 1",
            "type": "panel",
            "key": "page1",
            "components": [
                {
                		"dataType": "number",
                    "label": "Radio",
                    "optionsLabelPosition": "right",
                    "inline": false,
                    "tableView": false,
                    "values": [
                        {
                            "label": "one",
                            "value": "1",
                            "shortcut": ""
                        },
                        {
                            "label": "two",
                            "value": "2",
                            "shortcut": ""
                        },
                        {
                            "label": "three",
                            "value": "3",
                            "shortcut": ""
                        }
                    ],
                    "calculateServer": false,
                    "key": "radio1",
                    "type": "radio",
                    "input": true
                }
            ],
            "input": false,
            "tableView": false
        },
        {
            "title": "Page 2",
            "label": "Page 2",
            "type": "panel",
            "key": "page2",
            "components": [
                {
                    "label": "Text Field",
                    "spellcheck": true,
                    "tableView": true,
                    "calculateServer": false,
                    "key": "textField",
                    "type": "textfield",
                    "input": true
                }
            ],
            "input": false,
            "tableView": false
        }
    ]
}
```

I've noticed this appears to be an issue relating to the `dataType` property. Setting it to `number` does not fix the issue, nor does leaving it empty. Setting it to `string` does resolve the issue, but it isn't correct.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
