### ISSUE TITLE
[BUG] Logic Tab : When the trigger type is event, cannot set property "hidden" in the Action

### ISSUE THREAD

**Issue by Vedhachala** [formio/formio.js#2553]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: Angular
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Configure a textfield's logic tab to trigger on an event and set the hidden property of the textfield to true
2. Add a button to trigger the event 
3. Click the button

## Expected behavior
Textfield to hide
## Observed behavior
Textfield does not hide

## Example
![event_hidden_bug](https://user-images.githubusercontent.com/15833345/77044427-70da3f80-69e5-11ea-8382-52842ac2dc49.gif)

Note: You can see in the gif that the same thing work when the trigger type is a simple component's value
This is an important defect for us as a majority of our form actions are event triggered.

**Comment by jhen1422** [comment]
@Vedhachala 
Thank you for the report. We were able to replicate this issue on our end as well and have created a ticket in our 4x branch. We will review this item during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
