### ISSUE TITLE
The fuzzy search in the drop-down box is not fully displayed

### ISSUE THREAD

**Issue by sssxiaocainiao** [formio/formio.js#2555]
![image](https://user-images.githubusercontent.com/26619935/77049616-5e6efe80-6a03-11ea-9fab-541159586c91.png)
The fuzzy search in the drop-down box is incomplete, only four choices are displayed

**Comment by jhen1422** [comment]
@sssxiaocainiao 
We utilize the 'Choices.js' library for our Select components. You can modify the options for this component, including the number of values that are displayed,  by inputting elements inside the 'Choices.js option' setting field. 

Here's a read me on choices.js 
https://github.com/jshjohnson/Choices/blob/master/README.md

**Comment by sssxiaocainiao** [comment]
thank you,let me see
