### ISSUE TITLE
[BUG] 4.9.0 Upgrade causing infinite loop

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#2557]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 4.9.0
- Formio.js version: 4.9.0
- Frontend framework: react-formio
- Browser:
- Browser version:

Just upgraded to 4.9.0 and dragging a component on the form is causing an infinite loop behind the scenes. I can't fill any properties. Seeing:

![Screenshot 2020-03-20 at 07 49 02](https://user-images.githubusercontent.com/290639/77145109-8c922400-6a7f-11ea-9a19-3689f246bb92.png)

Thanks

**Comment by iamsid** [comment]
Can also see this on the builder demo here: https://formio.github.io/formio.js/app/builder

**Comment by jhen1422** [comment]
@aminmc This should be resolved in version 4.9.5

**Comment by gregbown** [comment]
Unsure why this is closed? [Demo using 4.9.8](https://stackblitz.com/edit/formio-builder-rncrmy?file=index.js)
