### ISSUE TITLE
[QUESTION] Action API and hooks

### ISSUE THREAD

**Issue by Romakita** [formio/formio.js#2558]
Hello guys :)

I would like to know if you have a documentation about action API. I would like to implement my own Action (like Email action, or Login action) and load it on the server (we hosting our own formio instance).

Other questions, have you a documentation about hooks mechanism and a list of the hooks which can be intercepted ? 
There is a hook name who can be able to attach data to the component when we calling rest API to get a form schema ?

Thanks for your amazing dev ;)

See you
Romain

**Comment by jhen1422** [comment]
@Romakita 
Please find our API documentation which should cover your inquiries 
[API Docs](https://documenter.getpostman.com/view/684631/formio-api/2Jvuks?version=latest#402b3260-e57e-4565-bd21-8a6f6b2394ce)

**Comment by randallknutson** [comment]
Yes, the formio repo is the better place to ask this. We don't really have any more documentation than you can already see. The best way to develop them is to inspect other actions and make sure you implement the same functions. 

There are only a few functions required. One to define the action, one to give the settings form and one to execute the action.

**Comment by Romakita** [comment]
@randallknutson Thanks for your reply :). I'll keep this conversation on the right repo.

See you
