### ISSUE TITLE
[BUG] can not get rid of header template of edit grid

### ISSUE THREAD

**Issue by Uysim** [formio/formio.js#2561]
## Environment
You can try on this. 
https://formio.github.io/formio.js/app/builder

## Steps to Reproduce
1. add edit grid
2. add text field to edit grid 
3. click on setting of edit grid
4. To go templates tab
5. Clear header template -> click save
6. click on setting of edit grid again
7. Still see the header there

## Expected behavior
Should remove header template completely

**Comment by jhen1422** [comment]
@Uysim 
Thank you for the report. We have added this to our 4x backlog and will review this item during our planning meeting next week. Please note, we welcome pull requests in this library. 

If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by wag110894** [comment]
Hello @Uysim,  
Can you try clearing out the header template and just add an empty span inside the header template to remove the header?
