### ISSUE TITLE
default wysiwig and ace settings - non breaking bugs

### ISSUE THREAD

**Issue by gregbown** [formio/formio.js#2569]
## Environment
- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version:  4.10.0-beta.1
- Frontend framework: Node Express
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Drag textarea component to form builder
2. ace tries to load theme-snow.js
3. ace warns modules is misspelled

## Expected behavior
ace should load it's own theme, not the quill theme name
## Observed behavior
404
![ace-editor-errors](https://user-images.githubusercontent.com/1952728/77370618-82da1c00-6d1e-11ea-874c-401f9acf8aa2.jpg)

 - note: debug console must be open to see errors
[live example](https://stackblitz.com/edit/formio-builder-zw4dkm?file=index.js)

The 404 error from trying to load theme-snow.js is indirectly caused by the [wysiwygDefault settings](https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L1827) being passed into ace. Since "theme" is an actual ace setting, it tries to load a file following it's schema called theme-snow.js which obviously doesn't exist.

The misspelled warning is caused by the [modules for quill](https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L1829) below being passed in to ace settings
```
  get wysiwygDefault() {
    return {
      theme: 'snow',
      placeholder: this.t(this.component.placeholder),
      modules: {
```
I verified that changing the theme here to an ace theme like "xcode" and moving the quill modules settings to the addQuill method corrects both of these issues. A few other changes are needed though... the ace theme must be initialized when the editor is, in the addAce method
```
editor.getSession().setMode(`ace/mode/${settings.mode}`);
editor.setTheme(`ace/theme/xcode`);
. . .
```
On a side note, when I tested quill, it complained that the "source" option in the toolbar settings was not supported, removing this from the quill settings resolves the error.

**Comment by travist** [comment]
This is also related https://github.com/formio/react-formio/issues/291

**Comment by jhen1422** [comment]
@gregbown This issue should be resolved in formio.js version 4.9.16

**Comment by gregbown** [comment]
I agree with closing this, however; one item I mentioned is still occurring. 
"On a side note, when I tested quill, it complained that the [source] option in the toolbar settings was not supported, removing this from the quill settings resolves the error."
Thank you for the great work and the pace of all the commits!
