### ISSUE TITLE
"Field Set" component with a "Property Name" in API tab

### ISSUE THREAD

**Issue by victorperez2911** [formio/formio.js#2608]
Hello

Although the Field Set Component has a "Property Name" field in the API tab, the elements that are nested in that Field Set are not nested in this property in JSON to submit

Do you have any properties I need to set up correctly for this to work?

**Comment by azizk** [comment]
I think what you're really looking for is the Container component located in the "Data" group. The Field Set is just for layout and grouping other components.

**Comment by victorperez2911** [comment]
that's exactly it, thank you.
