### ISSUE TITLE
Latest fixes to wysiwyg reveal broken image upload and still emit ace warnings

### ISSUE THREAD

**Issue by gregbown** [formio/formio.js#2611]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment

- Formio.js version: 4.10.0-beta.5
- Frontend framework: NodeJS
- Browser: Chrome
- Browser version: latest

ace editor is still being passed configuration from other editors + formio is null on root
![image-upload](https://user-images.githubusercontent.com/1952728/78458873-8bf5b200-7669-11ea-8526-e62260ad1105.jpg)

## Steps to Reproduce
1. Drag a text area to builder form
2. Already notice ace warnings in console as it tries to make  sense of all the other editor configurations
3. Select quill editor, save and try to upload an image. This throws error because formio is null on root

## Expected behavior
The upload was literally just working on Thursday April 2nd. Obviously I cannot say for sure if it was just the wysiwyg updates caused this, it may have been one of the unrelated changes. Just seems odd. I specifically remember checking it prior to merging changes from March 30 on.
## Observed behavior
Upload fails
## Example
[Your own demo](https://formio.github.io/formio.js/app/builder)

Unsure why formio is null [here](https://github.com/formio/formio.js/blob/master/src/components/textarea/TextArea.js#L251)

A slight tweak in the code fixes the ace warnings.  Unsure why formio is null error
```
// settings = _.merge(this.wysiwygDefault.ace, _.get(this.options, 'editors.ace.settings', {}), settings || {});
settings = _.merge(this.wysiwygDefault.ace, _.get(this.options, 'editors.ace.settings', {}), settings.ace || {});
```

**Comment by rohitcoder** [comment]
I am also facing a problem with image upload here.

![Screenshot 2020-04-08 at 5 21 20 PM](https://user-images.githubusercontent.com/17665703/78781139-5fb99880-79bd-11ea-8b4c-458defa892bb.png)

**Comment by wag110894** [comment]
Hello @rohitcoder and @gregbown,

We are not seeing this on the latest version of our core renderer: 4.9.15.  Our demo is running on 4.9.15. Here is a screencast of it working: https://share.getcloudapp.com/6qu5mGrG

**Comment by gregbown** [comment]
@rohitcoder Wonderful! I believe you, also just verified that it is now working. The warnings also appear to be cleaned up. Great work.
