### ISSUE TITLE
[BUG] Form validation

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2613]
## Environment
If you have a disabled or hidden field validation logic has stopped working on those fields. With FormIOJS 4.9.5 you can validate a disabled or hidden field but no longer. Whilst initially this may seem logical. We do have a form where we ask users to enter total number of hours worked. e.g 10. Then we ask them to give us the break down of the hours. At the bottom we have a text box with a calculated value to ensure that they have allocated all 10 hours. If not then upon submission with raise a validation error telling them the totals do not match.

Can we please revert this function?

- Hosting type
  - [X ] Local deployment
    - Version: 
- Formio.js version: 4.9.8

**Comment by jhen1422** [comment]
@pixie79 Is this issue occurring on version 4.9.13?

**Comment by pixie79** [comment]
Yes, Tested with latest as well

**Comment by randallknutson** [comment]
Hidden components (components that are hidden and the actual hidden components) should not have validations since they by definition aren't active on the form. Disabled components SHOULD have validations since like in your use case they can be modified by other components.

**Comment by pixie79** [comment]
Ok, It is not working with Disabled ones currently it appear the validation logic is not firing.

**Comment by jhen1422** [comment]
@pixie79 
Thank you for the report. We were able to replicate this issue on our end as well and have added a ticket to our developer backlog. We will review this item during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.
