### ISSUE TITLE
[Question]  Manual override of calculated value

### ISSUE THREAD

**Issue by abigtoe** [formio/formio.js#2614]
I'm currently using the server version of Formio and I have a use case where a user will need to over-ride the calculated value of a field.   I noticed that in the standalone form builder, such a feature exists.  

Are there any plans to include the 'manual override of calculated value' as part of the API used by the server version?  

![Screen Shot 2020-04-06 at 1 24 38 PM](https://user-images.githubusercontent.com/4334565/78586906-2d1b6e80-780a-11ea-95dc-0d670b05ebea.png)

**Comment by abigtoe** [comment]
Hi Randall, 

Thanks for the quick reply.  Before I take a deep dive into the repo  is there any documentation on how to upgrade to the latest version of ng-formio? If not, can you point to the correct folder(s) which have the file(s) in question?  

Thanks

**Comment by randallknutson** [comment]
Inside formio/formio the client is downloaded from formio-app-formio. This is a separate frontend application which contains the ng-formio library. In there should be a bower.json file which contains the verison of ng-formio being included. I haven't actually looked at this repo (or many angularJS 1.x applications) in a while so there isn't a lot beyond that I can help with. 

At some point we want to upgrade the formio client application to a newer react or angular (9.x or later) based application to make it more up to date.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
