### ISSUE TITLE
File upload, File Name Template variables

### ISSUE THREAD

**Issue by vdcrea** [formio/formio.js#2621]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 7.0.0-rc.82
- Formio.js version: 3.20.17
- Frontend framework: vue
- Browser: chrome
- Browser version: 80.x

## Steps to Reproduce
1. create a file upload field
2. to to tab File
3. fill in the File Name Template with a {{

## Expected behavior
Documentation about that feature, return of a filename with variables

## Observed behavior
The renamed file contains a javascript function stringifyed

**Comment by jhen1422** [comment]
@vdcrea 
Can you verify if this is an issue with our 4.9.X version of formio.js?

**Comment by vdcrea** [comment]
I suppose it's also in 4.10, probably around this line https://github.com/formio/formio.js/blob/master/src/components/file/File.js#L569

I guess your issue is probably in the client yes, no idea how you implemented the template interpreter and I didn't find any documentation about the field "File Name Template".

**Comment by travist** [comment]
We are working on expanding out our documentation, so stay tuned for that, but in the meantime, it looks like you can edit the JSON of the component and add the following.

```
"fileNameTemplate": "{{ submission._id }}-testing"
```

Or something like that... this uses ```evalContext``` which is the common method to bring in all variables documented in the Calculate Value section of the form builder.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
