### ISSUE TITLE
Use Bootstrap 3 with FormIO Javascript 4

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#2622]
We are currently using v4.9.15 and would like to use Bootstrap 3 with it. I know it has been mentioned that you can switch from bootstrap 4 (which we are doing in the next several months) to bootstrap 3, but I can't find a workable solution to get it done.

I see the repository for bootstrap 3, but the first import line gives an error. Not sure if that was meant for the angular version, or if perhaps I am missing something.

Just looking for a simple example to get Bootstrap 3 working with FormIO Javascript 4.9.15 to get us through until we can upgrade to BS4. Thanks!

**Comment by randallknutson** [comment]
You should be able to set options.template = 'bootstrap3' and it will render in bootstrap 3. If you are experiencing an error, can you post it here so we can get it fixed? We still support bootstrap 3 and have automated tests around it so if something is broken we need to understand what.
