### ISSUE TITLE
hideComponents is not working -  formio render[BUG] 

### ISSUE THREAD

**Issue by satheeshpandian** [formio/formio.js#2623]
Hi,

Am using angular-formio version 3.14.0. Am using viewOnly mode for preview of pages created by wizard. In that need to hide some fields  while displaying as preview.

i have tried hideComponents as per document. But its not hiding fields.

**Comment by wag110894** [comment]
Hello @satheeshpandian,

Can you provide a JSFiddle of this issue occurring?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
