### ISSUE TITLE
How to set default value for "stoarge" in File Component [Question]

### ISSUE THREAD

**Issue by rohitcoder** [formio/formio.js#2625]
Hi There,

I want to set the default value of "Storage" to "URL" and remove all other fields like s3, dropbox...

I want to do this on `Formio.builder()` and as well as on `Formio.createForm()`

Thanks,
Rohit

**Comment by wag110894** [comment]
Hello @rohitcoder,

The following documentation should help you along
https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by rohitcoder** [comment]
Hi @wag110894 

I checked this documentation multiple times, still, I am not able to achieve what i want to do. I can see documentation only for disabling/enabling any component or if i want to create my own component.

However, I just want to hardcode (default selected and disable other options) values for "storage" and "URL" in "file" component.

see this picture (I want to set these values by default) 

![Screenshot 2020-04-10 at 6 32 29 PM](https://user-images.githubusercontent.com/17665703/78992757-a6dc9080-7b59-11ea-9c76-1750c5eeb973.png)

**Comment by rohitcoder** [comment]
If i create a new custom component using this then i can set a default value for this stuff, but is it possible to override main component? 

```
   "components":   {
      "file":{
         "schema":{
            "type":"file",
            "storage":"url",
            "url":"https://google.com"
         }
      }
   }
```

**Comment by rohitcoder** [comment]
Closing this thread, as i already got my answer from [this thread](https://github.com/formio/angular-formio/issues/241)

We can set default values as i mentioned above and if we want to remove any tab then we can use 

```
editForm: {
    textfield: [
      {
        key: 'api',
        ignore: true
      },{
        key: 'data',
        ignore: true
      }        
    ]
  }
```

**Comment by yuzdeng** [comment]
Hello, @roflanKisel.

I meet the same issue so could you tell me how did you overwrite system config? I saw the source code it seems like you can only ignore a system config but you cannot overwrite the system config. So how do you resolve this issue? look forward to your reply.

**Comment by rohitcoder** [comment]
@yuzdeng 

You could acheive this by setting a default option to this kind of fields using 

```
"components":   {
      "file":{
         "schema":{
            "type":"file",
            "storage":"url",
            "url":"https://google.com"
         }
      }
   }
```

and then you can hide this using

```
editForm: {
    textfield: [
      {
        key: 'api',
        ignore: true
      },{
        key: 'data',
        ignore: true
      }        
    ]
  }
```

Just keep chaining this method in different components, at the end, you'll be able to achieve whatever you want.

Obviously, you can also change the system config from the core library, but that won't be easy task compared to this method.

**Comment by Nabinsharma123** [comment]
@rohitcoder 

this code is working fine

```
phoneNumber: {
    title: "Mobile Phone",
  key: "mobilePhone",
 icon: "phone-square",
  schema: {
  label: "Mobile Phone",
  type: "phoneNumber",
 key: "mobilePhone",
 defaultValue: 4587,
  input: true,
},
 },
```

but this is not working
```
"components":   {
      "file":{
         "schema":{
            "type":"file",
            "storage":"url",
            "url":"https://google.com"
         }
      }
   }
```
plz help
