### ISSUE TITLE
Add context object while emit render event

### ISSUE THREAD

**Issue by fabien-feat** [formio/formio.js#2630]
As I said in another issue, 

In formiojs, 3 classes emit render event : 

- Form
- Wizard
- WebForm

but Wizard and WebForm doesn't send a context object : 

https://github.com/formio/formio.js/blob/master/src/Wizard.js#L186
https://github.com/formio/formio.js/blob/master/src/Webform.js#L971

Form class send context object : 
https://github.com/formio/formio.js/blob/master/src/Form.js#L266

It should be cool to always send a context object, for example Wizard should send the currentPage when emit render event.

_Originally posted by @fabien-feat in https://github.com/formio/formio.js/issues/2029#issuecomment-607532242_

**Comment by wag110894** [comment]
Would you be able to submit a pull request for this?

**Comment by fabien-feat** [comment]
Yes, I've created this issue to push a PR ;)
The code is ok, I submit the PR today !
