### ISSUE TITLE
[BUG] File component does not stops video stream on destroy

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#2633]
## Environment

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: `2.0.0-beta.4`
- Formio.js version: `4.10.0-beta.6`
- Frontend framework: `vuejs`
- Browser: `Google Chrome`
- Browser version: `80.0.3987.163`

## Steps to Reproduce
1. Create form (**form A**) with file component (**component A**)
2. Create form (**form B**) with resource component (**component B**) targeting **form A**
3. Enable `Add Recourse` in **component B**
4. Render **form B**
5. Click on `Add Resource` button of **component B** (**form A** will render in formio dialog)
6. Click on `Use Camera` in **component A**
7. Close formio dialog with **form A**
8.  Video stream is still active after **form A** is destroyed

## Expected behavior
When the file component is destroyed, the video stream must stop if active.

## Observed behavior
Form is destroyed but video stream is still active (can verify with webcam light indicator)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
