### ISSUE TITLE
Add Formiojs SCSS files to NPM package

### ISSUE THREAD

**Issue by Andrey-Pavlov** [formio/formio.js#2636]
I want to isolate bootstrap and formio builder styles on the page. I'm using SCSS for it and in the next example css specifity of  boostrap higher than formio.js
```
@import "../../../styles/variables";

.formio-container-required {
  $theme-colors: (
    "primary": $color-success,
  );

  @import "~bootstrap/scss/bootstrap";
// doesn't work
//@import '~formiojs/dist/formio.builder.min.css';

// this works
  // WARNING Formiojs doesn't provide SASS file in node_modules. Have to copy-paste Formio SCSS styles to work with bootstrap variables.
  // @import "./formio.form.builder";
}
```

**Comment by randallknutson** [comment]
Do you have a suggestion for how we could make this better? We would like to support importing the custom styles with SCSS.

**Comment by Andrey-Pavlov** [comment]
Hi. You can check how Bootstrap did it and do similar.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
