### ISSUE TITLE
[BUG] Select component showing item value instead of label when selected

### ISSUE THREAD

**Issue by przzz27** [formio/formio.js#2639]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: formiojs v4.10.0-beta.3.1
- Frontend framework: Vanilla Javascript
- Browser: Google Chrome
- Browser version: 80

## Steps to Reproduce
1.  Add a select component to your form
2.  Configure the data source as URL
3.  Set a limit of 10 records
4. Set search parameter name as "search"
5. Configure the value property (ex: id)
6. Configure the item template to show another field (ex: `<span> {{item.name}} </span>` )
7. Either select an option by using the search input or from the infinite scroll

## Expected behavior
Select component should show the name/label of the option selected

## Observed behavior
Let's say we used the infinite scroll or the search input to find the following option
`<option value="123">ABC</option>`
When selected, it should show "ABC" on the component, but instead it shows "123"
## Example
Added [JSFiddle](https://jsfiddle.net/am8yc5s7/) example, search for "Blake Kunze"
![image](https://user-images.githubusercontent.com/61523021/79004136-f8106400-7b08-11ea-96bf-032097c56e99.png)

![image](https://user-images.githubusercontent.com/61523021/79004152-00689f00-7b09-11ea-9094-fca782ec8ea4.png)

**Comment by przzz27** [comment]
Maybe i'm misunderstanding something, the inner text of the option selected and the value should be two different things, but it seems like the value property overrides the item template, why is that?

Removing the id value property as suggested appends an object to the value, and in the submission data we can see the text of the option selected, but i want to save the value property, which must be an id.
![image](https://user-images.githubusercontent.com/61523021/79258696-62ded980-7e40-11ea-8d9c-ada60c17886a.png)
![image](https://user-images.githubusercontent.com/61523021/79259015-e00a4e80-7e40-11ea-9d7b-6600efe66adb.png)


As i said, this issue only happens when the option selected came either by using the infinite scroll feature, or by searching it with the input.

Selecting "Abbigail schneider" or any of the first 10 records of the dropdown results in the expected behavior.

![image](https://user-images.githubusercontent.com/61523021/79256804-7d638380-7e3d-11ea-90b8-e220f7cd1f8f.png)

![image](https://user-images.githubusercontent.com/61523021/79259420-8a827180-7e41-11ea-892c-8106c426aa2b.png)


But searching for "Blake Kunze" or scrolling down to that option causes this result
![image](https://user-images.githubusercontent.com/61523021/79257717-e1d31280-7e3e-11ea-9abd-2dab767b2801.png)

This can be replicated in the jsfiddle i provided.
as a note, the endpoint returns an array of objects like this:
`[ {"id": 123, "name": "Some name"}, { ...n}]`
Thanks for responding, hope this helps

**Comment by mrcandu** [comment]
I can replicate this issue. It occurs when trying to use a numeric as a select value. When using alpha numerics (e.g x0001), things work as expected.

**Comment by przzz27** [comment]
Hi, i'm closing this issue not because it was solved, but because i opened another one really similar to this one on formio repo, which is getting more attention than this one.

For more details go to:
https://github.com/formio/formio/issues/966
