### ISSUE TITLE
ClearOnRefresh and Dynamic Select Linking is not working fully

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2643]
I have Category and SubCategory selects along with some other fields on a form. The sub category select allows multiple options. I have set `refreshOn` to  `myObj.CategoryId`. When I select a  Category then it clears **selected** values from Sub category so that aspect is working fine. However, it doesn't update sub category values in the select as per the selected category.  I am using `custom` as `dataSrc` for populating.

The full example is in the following [**fiddle example.**](https://jsfiddle.net/keLt3w40/)

I tried manually setting the values in onchange event of the form and called redraw and refresh functions but of no use, as shown below. The `getSubCategoryValues` function returns updated values in `change` event, but these are not being applied to the select.

```
form.on('change', (event) => {

    if (event.changed && event.changed.component.key === 'myObj.CategoryId' && event.changed.value) {
      var myComp = form.getComponent('myObj.SubCategory');
      console.log(myComp);
      console.log("1");
      selectedCategoryId = event.changed.value;
      console.log(event.changed.component.key);
      console.log(event.changed.value);
      var valuesArray = getSubCategoryValues();
      console.log(valuesArray);
      console.log("2");
      myComp.data.custom = valuesArray;
      console.log(myComp);
      myComp.refresh();
      myComp.redraw();
      console.log("3");
    }
  });
```

**Comment by wag110894** [comment]
@learner291, 

Can you provide test steps in order to replicate this issue?

**Comment by learner291** [comment]
> @learner291,
> 
> Can you provide test steps in order to replicate this issue?

Hi @wag110894 , thanks for your reply.

The code is provided in the fiddle, mentioned in my question, please have look. I have added link here again: [Code to replicate this issue is in this fiddle](https://jsfiddle.net/keLt3w40/).

When I select Parent 2 from the category select, the sub category select should show children for Parent 2, but it is showing whatever was loaded initially i.e children for parent 1, see screenshot below.

![image](https://user-images.githubusercontent.com/40409548/79137387-8b1bf900-7daa-11ea-9697-5d19ffe4cd65.png)

**Comment by wag110894** [comment]
Hello @learner291,

Thank you for providing test steps on this issue that you are facing.  In order for us to get involved, it would require that we allocate one of our developers to investigate the specific use case. This is accomplished by our support packages. Our Support Packages are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please contact support@form.io if you are interested in more information regarding our Support Packages. 

We would appreciate any feedback/ideas from the community on this issue.

Have a great day!

**Comment by learner291** [comment]
Can anyone from the community help with this issue please?

Thanks

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
