### ISSUE TITLE
[BUG] Custom Component no longer rendering from 4.9.1

### ISSUE THREAD

**Issue by mrcandu** [formio/formio.js#2645]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version:
- Formio.js version: 4.9.9
- Frontend framework: n/a
- Browser: Chrome
- Browser version: 80.0.3987.163

## Steps to Reproduce
The following basic custom component is no longer rendering in FormioJS from v 4.9.1.
This code worked in a previous versions up to and including 4.9.0.
This code is adapted from your example which also no longer works from 4.9.1:  http://formio.github.io/formio.js/app/examples/customcomponent.html

```
var textComponent = Formio.Components.components.textfield;

function TestComponent(component, options, data) {
  textComponent.prototype.constructor.call(this, component, options, data);
}

TestComponent.prototype = Object.create(textComponent.prototype);  
Formio.Components.addComponent('testcomponent', TestComponent);
```

The JSON in the form.io hosted custom component is:

```
{
  "type": "testcomponent",
  "key": "custom",
  "label": "custom",
  "hideLabel": true,
  "input": true,
  "tableView": false,
  "conditional": {
    "show": "",
    "when": null,
    "eq": ""
  },
  "protected": false,
  "persistent": true
}
```

## Observed behaviour
The form fails to load with the console error:

`Cannot read property 'readOnly' of undefined`

**Comment by marcus-at-localhost** [comment]
I can second that.
Here is a fiddle (see error in console)
https://jsfiddle.net/wuka0n9q/2/

**Comment by wag110894** [comment]
Thanks reaching out!

We have added this to our backlog. We welcome a pull request or have a process to expedite if you are interested. Please contact support@form.io if you are interested. For reference, the ticket number is FJS-893.

We will let you once this has been resolved.

**Comment by wag110894** [comment]
Can you confirm that you have read through the documentation and ensure that you are doing things correctly?
https://github.com/formio/formio.js/wiki/Custom-Components-API
https://github.com/formio/contrib

**Comment by marcus-at-localhost** [comment]
Thanks for getting back
The custom component is made the "old" way: 
https://github.com/formio/formio.js/issues/2708
https://github.com/formio/formio.js/blob/6b19a89673d56cd516062778abd000d5933fe053/app/examples/customcomponent.md

Is it not possible to write custom components without setting up a build process?

**Comment by randallknutson** [comment]
You shouldn't technically need a build process, it just makes it a lot easier. We didn't intentionally change something recently to break custom components but without digging in to what is going wrong it is going to be hard for us to know how to fix this. It might be as simple as passing the options variable through the constructor or something like that. Is this something you can pinpoint the source of the issue and suggest a solution?

**Comment by marcus-at-localhost** [comment]
I debugged this like a caveman :) this is what I came up with:

![image](https://user-images.githubusercontent.com/1337223/80514474-d7f1f900-8980-11ea-9f5e-15f26a9cca33.png)

This fiddle jsfiddle.net/wuka0n9q/2 contains only the code for a custom component, derived from the HTML Component.

I can't tell where this goes wrong. :/

But good to know, custom components are still possible as simple javascript. (I need more time to dig into the new ways)

**Comment by SalTor** [comment]
@marcus-at-localhost Did you ever resolve this?

**Comment by marcus-at-localhost** [comment]
@SalTor unfortunately not. Since my component was very basic (nothing really custom, just a HTML component called "Header") I dropped it in favor of the native HTML component and it worked as well.
But I would like to see this resolved in some way and I wish the devs could offer a solution.

**Comment by SalTor** [comment]
@marcus-at-localhost Are you able to upgrade your version? I'm able to render Custom Components in portal.form.io as well as on my own web page and I'm using version 4.10.5

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
