### ISSUE TITLE
[QUESTION] Third Party JS library conflicts. Trim unused libraries out. 

### ISSUE THREAD

**Issue by NathanielSmithAU** [formio/formio.js#2647]
Apologize if this is not the right spot to ask questions, but as I could not find a better spot.

I am working on a project which involves just the FormIO JS render part of the library, in which we are provided the layout JSON structure from an external source, and we just have to render it on a page.
The layout contains custom components, in which I have created the components for on our end, and they are rendering correctly. We do not need to use getValue or setValue for any of them, we do not use any of the Built-in formio input elements, as what we receive are all custom components.

Now, the only issue I am currently facing, is conflicting third party JS libraries within the formio-full.js found at https://unpkg.com/formiojs@4.9.0/dist/formio.full.min.js, mainly the Lodash library as that conflicts with our existing underscore.js. 
The environment we have is a grails based web application, with most of our existing JS code/libraries combined in the 'asset pipeline' into a single JS, which is included on every page in our application. Currently solution to this issue is to not include the formio JS and CSS files into this asset pipeline, and just include it in the individual page we wish to use it on. Now this is fine for now, but not optimal solution and does not follow our existing processes.

**Question:**
What parts of the formio.js use those third party libraries, and is it possible to trim some of them out of the final JS file which are not used for the layout of the components. 

Current code. Now 'componets' map is generated server side and contains html string.
```
  /**
 * This is the function that is called to render each component.
 * The FormIO library is responsible for laying out each component, but the
 * content of each component comes from the server, and passed into this
 * page within the components map, which contains a key of component.key, and value
 * is the HTML String to render.
 * @returns String HTML.
 */
var renderComponent = function renderBoxComponent(){
	return components[this.component.key];
};

// Declare the component to be the base class for the CustomComponent
var HtmlElementComponent = Formio.Components.components.htmlelement;
// Declare a custom component to be used by the 3 components in the layout.
function CustomComponent(component, options, data) {
	HtmlElementComponent.prototype.constructor.call(this, component, options, data);
}
// Perform typical ES5 inheritance. Allows the creation of custom FormIO component.
// All of the components will use the same CustomComponent, as the content
// is already generated
CustomComponent.prototype = Object.create(HtmlElementComponent.prototype);
CustomComponent.prototype.constructor = CustomComponent;
CustomComponent.prototype.render = renderComponent;

// Register the custom components with FormIO. Each custom component will use the
// same render method.
Formio.Components.addComponent('component1', CustomComponent);
Formio.Components.addComponent('component2', CustomComponent);
Formio.Components.addComponent('component3', CustomComponent);

// Create the formio form. This will parse the layout and call the render method on each
// component.
Formio.createForm(document.getElementById('form'), layout, {
	noAlerts: true
});
```

Thankyou in advance.

**Comment by randallknutson** [comment]
If you are using the prebuild "dist" folder, that exists to bundle everything together so you don't need to build it yourself. If you are getting a conflict, I'd recommend using the formio.js library directly and building using a module bundler or build tool like webpack or typescript. That way you can build it exactly like you want.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
