### ISSUE TITLE
Limiting number of files for multi upload file component

### ISSUE THREAD

**Issue by moeVdm** [formio/formio.js#2649]
Hello,

is there a way to limit the number of files that can be uploaded when using a multi upload file component?

We would like to prevent a user that would upload, let's say, thousands of files on a single file component.

**Comment by randallknutson** [comment]
There does not appear to be a way to do this right now. It definitely makes sense that we could add this as a validation for the file component as a new feature on the platform. Is this something you would be able to contribute or sponsor?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
