### ISSUE TITLE
[BUG] Data Grid's 'valid' property not marking the component as invalid when not true

### ISSUE THREAD

**Issue by paffle** [formio/formio.js#2650]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.7.8
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 80.0.3987.163

## Steps to Reproduce
1. Create a form and drag a Data Grid onto it. Drag a Text Field (or anything) into the grid.
2. In the Validation > Custom Validation part of the Data Grid component, set the 'value' property to other than true, e.g. to error text. 
3. Preview the form (optionally entering a value in the first row's text field).

## Expected behavior
Submit button is disabled and data grid shows as invalid, with error message.
## Observed behavior
Data grid shows as valid, Submit button is enabled - on clicking it, no error is indicated and it simulates submission.
## Example

```json
{
  "label": "Data Grid",
  "labelPosition": "top",
  "description": "",
  "tooltip": "",
  "disableAddingRemovingRows": false,
  "reorder": false,
  "addAnother": "",
  "addAnotherPosition": "bottom",
  "defaultOpen": false,
  "layoutFixed": false,
  "enableRowGroups": false,
  "tabindex": "",
  "hidden": false,
  "hideLabel": false,
  "autofocus": false,
  "disabled": false,
  "alwaysEnabled": false,
  "defaultValue": null,
  "persistent": true,
  "protected": false,
  "redrawOn": "data",
  "clearOnHide": true,
  "customDefaultValue": "",
  "calculateValue": "",
  "allowCalculateOverride": false,
  "validateOn": "change",
  "validate": {
    "required": false,
    "customMessage": "",
    "custom": "valid = 'This Data Grid is invalid!';",
    "customPrivate": false,
    "json": "",
    "strictDateValidation": false
  },
  "errorLabel": "",
  "key": "dataGrid",
  "tags": "",
  "properties": {},
  "conditional": {
    "show": null,
    "when": null,
    "eq": "",
    "json": ""
  },
  "customConditional": "",
  "logic": [],
  "attributes": {},
  "overlay": {
    "style": "",
    "page": "",
    "left": "",
    "top": "",
    "width": "",
    "height": ""
  },
  "type": "datagrid",
  "input": true,
  "placeholder": "",
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "unique": false,
  "refreshOn": "",
  "tableView": false,
  "dbIndex": false,
  "widget": null,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "allowMultipleMasks": false,
  "tree": true,
  "components": [
    {
      "label": "Text Field",
      "labelPosition": "top",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "inputMask": "",
      "allowMultipleMasks": false,
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "alwaysEnabled": false,
      "multiple": false,
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "case": "",
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "minLength": "",
        "maxLength": "",
        "strictDateValidation": false
      },
      "errorLabel": "",
      "key": "textField",
      "tags": "",
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textfield",
      "input": true,
      "customClass": "",
      "unique": false,
      "refreshOn": "",
      "tableView": true,
      "dbIndex": false,
      "encrypted": false,
      "inputType": "text",
      "defaultValue": null,
      "id": "eou8c6j"
    }
  ],
  "id": "e5fucu5",
  "path": "dataGrid"
}
![DataGridValidity](https://user-images.githubusercontent.com/63660373/79252958-5e371700-7e7a-11ea-85cd-eb9b549229f5.PNG)
```

**Comment by wag110894** [comment]
You need to use double quotes so that it  shows like so: valid = "This Data Grid is invalid!"; 

I hope that this helps.

**Comment by paffle** [comment]
Thanks but that doesn't work either. 

Also, form.io's own example indicates single quotes, so I assume that should also work: 
valid = (input === 'Joe') ? true : 'Your name must be "Joe"';

**Comment by randallknutson** [comment]
We do not require using double quotes. You can use either single or double.

**Comment by wag110894** [comment]
@paffle 

We are able to replicate this issue on our side. We have created a ticket and have added this to our backlog. We welcome a Pull Request and also have a process to expedite this issue. If you are interested in expediting this issue, please contact support@form.io.

We will let you know once this issue has been resolved.

**Comment by paffle** [comment]
Thanks @wag110894

**Comment by wag110894** [comment]
@paffle Thank you for your patience while we took a look at this issue. You need to add the Custom Validation to the Text Field and not to the Datagrid for this to submit. 

I hope that this helps.

**Comment by paffle** [comment]
I need validity of the overall grid to be based on more than one field though. E.g. only valid if the oldest row.somedate is >= 5 years ago. Is there a way to do that?

**Comment by randallknutson** [comment]
You can do that in custom validation for the data grid where you can refer to each row and check to see if they are valid.

**Comment by paffle** [comment]
But you can't set the valid flag for the datagrid itself, right? E.g. this scenario: the datagrid is not valid unless the submitter has entered at least 5 years' worth of address history. So I need to say datagrid.valid=true if start date of any row is > 5 years ago. If datagrid not valid, then the submitter can't submit.

**Comment by travist** [comment]
You can refer to the datagrid from within the calculated value.  This is harder that you are using dates meaning "5 years ago" which requires our moment support, but here is what it would look like if these were just number fields..

```js
valid = row.dataGrid.reduce(function(valid, rowData) {
  return valid && (rowData.number > 5);
}, true) || 'No row can have a number less than 5.';
```
