### ISSUE TITLE
PDF generation with text search capability

### ISSUE THREAD

**Issue by JayashreeKrishanveni** [formio/formio.js#2651]
Lets say In my application , I have created some 5 forms altogether.
At the end of the 5th form , on clicking Submit button , a PDF should be generated (a single PDF for all 5 forms ). It is better if the form has text search capabilities.
Is there a provision for the above functionality in formio?

**Comment by randallknutson** [comment]
If you are using a wizard form with nested forms on each page you can nest them all together into a single pdf. These pdfs use text so they should be searchable.
