### ISSUE TITLE
[BUG] Date / Time Component with only Date illogical interpretation of minimum date

### ISSUE THREAD

**Issue by Svitra** [formio/formio.js#2654]
## Environment
- Formio.js version: 4.9.17
- Frontend framework: Angular 9

## Steps to Reproduce
1.  Configure in the builder the minimum date for Date / Time Component for tomorrow: moment().add(1,'day')
2. Configure in Time tab that time is disabled (Enable Time Input is false)
3. Try to select the date of tomorrow.

## Expected behavior
- The date is selected and considered correct

## Observed behavior
- The date can be selected but then is removed as invalid. My assumption is we are checking the date like if it was a dateTime object so selecting "tomorrow" does not necessarly mean 24h later depending on the implementation of this condition. Selecting the date after tomorrow works fine. A workaround is to write moment() but then users have the false impression they can select today, which in the end is removed if they do with the current behaviour. For my use-case this workaround is not acceptable.

My request:
It would be good if when using this calendar as "Date Only" picker only date value is considered in minimum/maximum value conditions. E.g. selecting minimum date - tomorrow: moment().add(1,'day') should always let me select tomorrow, otherwise such simple use case like "the user cannot select a date earlier than tomorrow" cannot be configured with this component.

Please let me know if a solution or adequate workaround can be provided for this problem.

**Comment by wag110894** [comment]
Hello @Svitra,

We have added this item to our backlog. We welcome a Pull Request from you or the community to resolve this issue.

**Comment by Svitra** [comment]
Thanks a lot. :) If I will find some time to check how this is implemented, I will try to post a PR.

**Comment by srinisubramanian** [comment]
This issue still seems to be occurring.  For e.g. if minimum date is set to Today, on losing focus its cleared out.  In effect for any date field that needs to have a minimum this is an issue and strange that it does not seem to be still fixed.

Any updates on when this will get resolved please?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
