### ISSUE TITLE
[BUG] defaultValue still stays if no value in select options

### ISSUE THREAD

**Issue by thenixtone** [formio/formio.js#2658]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.9.7+
- Formio.js version: 4.9.7+
- Frontend framework: JS
- Browser: Chrome
- Browser version: Latest

## Steps to Reproduce
1. Set a default value of a select component that doesn't have the value in its options
2. Submit form or view the components value/data

## Expected behavior

I'm upgrading from 3.X.X and this worked fine, if I set a defaultValue that wasn't in the options of the select, it wouldn't recognize it and it would be blank or it wouldn't 'set' etc. 

Is there some option to enable/disable this, am I missing something or is this a bug?

## Observed behavior

Default value becomes the value of the field regardless of it's options

**Comment by jhen1422** [comment]
@thenixtone Can you provide a screenshot of this issue? From our end, the default values options derive from the Select value options (see screenshot https://share.getcloudapp.com/jkulo6gr) so I'm unsure how you are setting Default Values for the select that are not already value options.

**Comment by thenixtone** [comment]
I'm doing it via changing the schema pre form load

![image](https://user-images.githubusercontent.com/40050751/79513547-79c33d00-8087-11ea-829d-786414834f43.png)

Previously if 'test' didn't exist in the options it wouldn't set it, I actually noticed yesterday it sets it in the submission data as well, which is where the issue becomes an issue.

**Comment by randallknutson** [comment]
I think this works as expected. If you set a value (default or otherwise) that isn't included in the select dropdown, it will be added to the select list. We don't want to just throw the value away if it is missing.

Can you help us understand why you would want to set a default value to something not in the list?

**Comment by thenixtone** [comment]
Because I've got a custom schema of data for a user, and I want to overlay it into the form, so if data is not valid anymore or missing, they have to update etc. 

I think the new default functionality doesn't make sense. Why would you add a value to a list if it wasn't there in the first place, there's other functionality to add values to a select. This would be good if it was an opt in toggle for the selected field, or if had some archived values settings, who knows.

**Comment by randallknutson** [comment]
There are cases where data is in default value or an existing submission but doesn't exist in the dropdown such as if it is on the second page of limited results from a url. In that case we don't want to lose the data which is what would happen if we didn't add it to the list.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
