### ISSUE TITLE
[BUG] Number fields have no way to set the datatype

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#2659]
When adding a number component to a form I should be able to set the value save data type to either Int or Float.

Currently If i enter a value of 1 and have decimals turned on then i get a float. However if i set a default value of 1.0000 or assign a custom value to 1.0000 it save it as a string with a value of "1"

Secondly when doing a calculation on a number field if the original field is a float for example 0.0002 and we times by 1 we correctly store a float of 1.0002 however, if the multiplier is 0.5 and we times by 2 we store and int of 2 rather than a float of 2.0000

This causes problems especially if numbers are part of a datagrid, for example where we are recording cash paid in different currencies and calculating a conversion back to a base currency. As the converted amount keeps changing type even with in single data payload.
We have been then saving this to elastic search which complains that the types are not consistent thus causing the save to fail.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
