### ISSUE TITLE
[BUG] Select component fails to fill up

### ISSUE THREAD

**Issue by munchkindev** [formio/formio.js#2662]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.9.18
- Formio.js version: 4.9.18
- Frontend framework: Angular
- Browser: Newest Firefox, Chrome
- Browser version: 76.0b4, 81.0.4044.113

## Steps to Reproduce
1. I followed the tutorial here https://help.form.io/userguide/form-components/#select
2. I setup the URL thru the Angular demo app

## Expected behavior

The select component should show all the US states and be selectable.

## Observed behavior

![selectfail](https://user-images.githubusercontent.com/62607227/79460103-a1b59080-7ff4-11ea-80a9-004492f6919b.png)
Also in the formio.js deployment while trying to submit data a validation error occurs on the select component.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
{"_id":"5e7a22039633f730ba349206","type":"form","tags":["common"],"owner":"5e7a10eb2639a62f6dce2bbd","components":[{"autofocus":false,"input":true,"tableView":true,"inputType":"text","inputMask":"","label":"Text","key":"text","placeholder":"","prefix":"","suffix":"","multiple":false,"defaultValue":"","protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"spellcheck":true,"validate":{"required":false,"minLength":"","maxLength":"","pattern":"","custom":"","customPrivate":false},"conditional":{"show":"","when":null,"eq":""},"type":"textfield","labelPosition":"top","inputFormat":"plain","tags":[],"properties":{}},{"autofocus":false,"input":true,"tableView":true,"label":"Bundesland","key":"select","placeholder":"","data":{"values":[{"value":"","label":""}],"json":"","url":"https://cdn.rawgit.com/mshafrir/2646763/raw/states_titlecase.json","resource":"","custom":"","headers":[{"value":"","key":""}]},"dataSrc":"url","valueProperty":"abbrevation","defaultValue":"","refreshOn":"","filter":"","authenticate":false,"template":"<span>{{ item.name }}</span>","multiple":false,"protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"validate":{"required":false},"type":"select","labelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{"":""},"customConditional":"","lockKey":true,"selectValues":""},{"autofocus":false,"input":true,"tableView":true,"inputType":"number","label":"Number","key":"number","placeholder":"","prefix":"","suffix":"","defaultValue":"","protected":false,"persistent":true,"hidden":false,"clearOnHide":true,"validate":{"required":false,"min":"","max":"","step":"any","integer":"","multiple":"","custom":""},"type":"number","labelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{}},{"autofocus":false,"input":true,"label":"Submit","tableView":false,"key":"submit","size":"md","leftIcon":"","rightIcon":"","block":false,"action":"submit","disableOnInvalid":false,"theme":"primary","type":"button"}],"display":"form","submissionAccess":[{"roles":["5e7a10d72639a62f6dce2bb0"],"type":"create_own"},{"roles":["5e7a10d72639a62f6dce2bb0"],"type":"read_own"},{"roles":["5e7a10d72639a62f6dce2bb0"],"type":"update_own"},{"roles":["5e7a10d72639a62f6dce2bb0"],"type":"delete_own"}],"title":"test34","name":"test34","path":"test34","access":[{"roles":["5e7a10d72639a62f6dce2baf","5e7a10d72639a62f6dce2bb0","5e7a10d72639a62f6dce2bb1"],"type":"read_all"}],"created":"2020-03-24T15:06:43.813Z","modified":"2020-04-06T11:59:40.261Z","machineName":"test34"}
```

**Comment by munchkindev** [comment]
UPDATE: It seems that the choices.js library is at fault here. If I change in the form manager the widget type to HTML5 it appears to be working correctly.

**Comment by jhen1422** [comment]
@munchkindev We're not experiencing any issues with the Select component using Choices.js on version 4.9.19.

Can you confirm if this is still an issue after upgrading the renderer and provide a fiddle of showing the issue?

**Comment by munchkindev** [comment]
@jhen1422 Thanks for replying. How do I upgrade the renderer? Using `npm update`?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
