### ISSUE TITLE
[BUG] Issue with Location/Address Google Map API

### ISSUE THREAD

**Issue by mayankrungta** [formio/formio.js#2663]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 2.0.0-beta.4 (from Changelog)
- Formio.js version: "formiojs": "^4.9.0-rc.10",
- Frontend framework: Angular
- Browser: Chrome
- Browser version: Version 81.0.4044.92 (Official Build) (64-bit)

## Steps to Reproduce
1. Trying to fill a form using Address widget from FormIO
2. Warning noticed in console
3. Is there a way to record the lat/long after this address has been filled?

## Expected behavior
1. Clean console
2. Ability to choose lat/long instead of well formatted address or both.

## Observed behavior
This message - js?v=3&libraries=pla…CUo&region=India:64 open_now is deprecated as of November 2019 and will be turned off in November 2020. Use the isOpen() function from a PlacesService.getDetails() result instead.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

![image](https://user-images.githubusercontent.com/1388979/79464817-2ebe1100-8018-11ea-8b49-39e202c06b66.png)

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by travist** [comment]
This may be that your are running a really old version of the Google Maps API (which needs to be pulled in separately).

**Comment by mayankrungta** [comment]
I just did the following steps for the local setup -

1. Pulled the git repo for formio
2. npm install
3. npm main

At client end we are using the <formio></formio> tag with or without submission(for edit).

If this is due to an old API, how do I upgrade the same? The access of the map happens due to the formio Address widget against a google API key which we generated last week.

Kindly advise.

Thanks,
Mayank

**Comment by travist** [comment]
Then this may be an issue with the Open Source portal @ https://github.com/formio/formio-app.  Pull requests welcome.

**Comment by mayankrungta** [comment]
Moved to a later version of Angular and hence the later version of Angular Formio. I am getting new warnings when running ng serve -

Warning: Entry point 'angular-formio' contains deep imports into '/home/mayank/repo/covidResponse/frontend/covidapp/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to b
e out of order.                                                                                                                                                                                                                              
Warning: Entry point 'formio-manager' contains deep imports into '/home/mayank/repo/covidResponse/frontend/covidapp/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to b
e out of order.                                                                                                                                                                                                                               Warning: Entry point 'formio-grid' contains deep imports into '/home/mayank/repo/covidResponse/frontend/covidapp/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to be o
ut of order.                                                                                                                                                                                                                                 
Warning: Entry point 'formio-resource' contains deep imports into '/home/mayank/repo/covidResponse/frontend/covidapp/node_modules/formiojs/utils/Evaluator'. This is probably not a problem, but may cause the compilation of entry points to 
be out of order.

These ^^^ warnings are showing now and there are ways to suppress mentioned but I also see a bulk of following errors which look related -

Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/formio.config.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /home/mayank/repo/covidR
esponse/frontend/covidapp/node_modules/angular-formio/formio.config.d.ts.                                                                                                                                                                     This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.                   
You should check other entry-points in this package and set up a config to ignore any that you are not using.                                                                                                                                 
Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/loader/formio.loader.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /home/
mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/loader/formio.loader.d.ts.                                                                                                                                 This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.                                                                                                                                
Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/custom-component/custom-tags.service.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /
home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/custom-component/custom-tags.service.d.ts.                                                                                                                       This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.                                                                                                                                
Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/FormioBaseComponent.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /home/mayank/repo/
covidResponse/frontend/covidapp/node_modules/angular-formio/FormioBaseComponent.d.ts.                                            
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.                                                                                                                                 
Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/formio/formio.component.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, /ho
me/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/formio/formio.component.d.ts.              
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.                                                                                                                                 
Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/formbuilder/formbuilder.component.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backi
ng up, /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/formbuilder/formbuilder.component.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.                                                                                                                                 
Error: Tried to write /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/loader/formio.loader.component.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing
up, /home/mayank/repo/covidResponse/frontend/covidapp/node_modules/angular-formio/components/loader/formio.loader.component.d.ts.                                                                                                             
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.

Is this something that can be fixed at FormIO end or is it to be ignored. Kindly confirm.

I am familiar with Angular and getting around FormIO. Look forward to the NEXT version of the open source portal as well.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
