### ISSUE TITLE
Select component ignores values and set the label as value

### ISSUE THREAD

**Issue by sutauma** [formio/formio.js#2664]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: next.form.io
- Browser: Safari, Firefox
- Browser version: latest

## Steps to Reproduce
1. Create a Select Component
2. Set Data Source Type to Values
3. Set Storage Type to Number
4. Create 2-3 Values
 * Label: I Value: 1
 * Label: II Value: 2
 * Label: III Value: 3
5. Save the component
6 Reopen the properties of the component and look at the values

## Expected behavior
The values should be listed like:
 * Label: I Value: 1
 * Label: II Value: 2
 * Label: III Value: 3

## Observed behavior
The values are listed like:
 * Label: I Value: **i**
 * Label: II Value: 2
 * Label: III Value: 3

Switching the third item to the first will cause:
 * Label: III Value: **iii**
 * Label: II Value: 2
 * Label: I Value: 1

## Example
<img width="1148" alt="Bildschirmfoto 2020-04-16 um 16 55 13" src="https://user-images.githubusercontent.com/56014788/79475072-8011d480-8007-11ea-940e-f3f0d87045d8.png">

**Comment by wag110894** [comment]
Hello @sutauma, We are aware of this issue and have added it to our backlog. We welcome a Pull Request and have a process to expedite. If you are interested in expediting, please contact support@form.io.
We will let you know once this issue has been resolved.

**Comment by nhohb** [comment]
I have the same issue here, on radio, select, selectboxes, try many solutions, such as after rendering modal, I try to setItems to [], but it didn't work.

**Comment by wag110894** [comment]
This issue has been resolved on the latest version of formio.js 4.10.3.

Thank you.
