### ISSUE TITLE
[BUG] Infinite loop in wizard mode

### ISSUE THREAD

**Issue by gregbown** [formio/formio.js#2666]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version: 4.9* +
- Formio.js version: 4.9.* +
- Frontend framework: NodeJS
- Browser: Chrome
- Browser version: Latest

## Steps to Reproduce
1. Open debug console
2. Build any wizard form
3. Observe infinite loop

## Expected behavior
Should behave the same as form mode
Using builder.instance.on('change', onBuild); while also using builder.instance.schema getter should not trigger an infinite loop in wizard mode
## Observed behavior
![formio-infinite-loop](https://user-images.githubusercontent.com/1952728/79534344-21f8e780-802f-11ea-8a54-429e211ad4ed.jpg)

## Examples
https://formio.github.io/formio.js/app/builder
https://stackblitz.com/edit/formio-builder-rncrmy?file=index.js
## Previous mention
https://github.com/formio/formio.js/issues/2557
https://github.com/formio/formio.js/issues/2389
https://github.com/formio/formio.js/issues/2546

This was my fix for it [in Webform.js ](https://github.com/formio/formio.js/blob/master/src/Webform.js#L1281) but I defer to your experience.

```
    // if (!flags || !flags.noEmit) {
    if ((!flags || !flags.noEmit) && changed) {
      this.emit('change', value, flags);
      isChangeEventEmitted = true;
    }
```
[Your demo](https://formio.github.io/formio.js/app/builder) finally exhibited the same behavior as my stackblitz after the [commit ](https://github.com/formio/formio.js/commit/d76058f1fbb146a7db7ed7a91c56fdd802429ae7) because the infinite loop trifecta is using builder.instance.on('change', onBuild); while also using builder.instance.schema getter and wizard mode.
```
  - builder.instance.on('saveComponent', onBuild);
  - builder.instance.on('editComponent', onBuild);
  + builder.instance.on('change', onBuild);
```

**Comment by pjmuller** [comment]
@randallknutson +1, this is blocking for us, and I guess it should be blocking for everyone ;)

**Comment by wag110894** [comment]
@pjmuller @gregbown 

Thank you both for reaching out. We are able to replicate the issue and have created a ticketed and have assigned this to one of our developers as a high priority item.

We will let you know once this issue has been resolved. For reference, the ticket number is FJS-986.

**Comment by wag110894** [comment]
@pjmuller @gregbown,

Thank you for your patience while we worked on getting FJS-986 resolved. You will no longer get the infinite loop error when you use our Formio.js builder, which is now running on 4.10.0-rc11.
