### ISSUE TITLE
[HOW-TO] How to preserve component id on editing save?

### ISSUE THREAD

**Issue by Andrey-Pavlov** [formio/formio.js#2677]
Hello.

I want to rely on component id to distinct new, removed or updated components but on each "Edit" save action the id is changed. Is it possible to do? To save initial id for an edited component?

**Comment by randallknutson** [comment]
We intentionally do not save Ids as they are not meant to be preserved. The reason for this is that there may be more than one of the same form on a webpage. If we store the ids as part of the component definition the two forms would use the same ids in the rendered components which would not be valid html. Instead, we generate new ids each time a component is instantiated and use the component key as the unique identifier.

**Comment by Andrey-Pavlov** [comment]
> We intentionally do not save Ids as they are not meant to be preserved. The reason for this is that there may be more than one of the same form on a webpage. If we store the ids as part of the component definition the two forms would use the same ids in the rendered components which would not be valid html. Instead, we generate new ids each time a component is instantiated and use the component key as the unique identifier.

It makes impossible to store answers history for removed questions because new created questions reuse the same Keys. Is there a way to distinct old questions (removed) and new questions (added) of the same types (input, textarea)? My goal is to save and show history of questions with answers with a revert operations support.

**Comment by randallknutson** [comment]
Property names (keys) can be set to whatever you want to set them to. They don't have to be reused to the type of the fields. They just default to the label of the component but can easily be changed.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
