### ISSUE TITLE
Request: Support for a different CSS framework

### ISSUE THREAD

**Issue by srinisubramanian** [formio/formio.js#2682]
Refer the CSS frameworks supported here: https://github.com/formio/formio.js/wiki/Templates-API

We need to support a different CSS framework.  Is there some documentation on how this can be done or examples?

**Comment by randallknutson** [comment]
Absolutely! You have the primary documentation there already. We have lots of examples of this as well. Here are some CSS frameworks that we have examples for:

https://github.com/formio/formio.js/tree/master/src/templates/bootstrap
https://github.com/formio/semantic
https://github.com/formio/bootstrap3
https://github.com/formio/bulma
https://github.com/formio/uswds

Those should provide lots of examples of how to do this. What framework are you looking at implementing and would you be interested in adding it to our list of frameworks?

**Comment by srinisubramanian** [comment]
Was considering OpenUI5. Will check if we are able to do it.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
