### ISSUE TITLE
[BUG] fileService is not inherited by nested forms.

### ISSUE THREAD

**Issue by llaurentiu** [formio/formio.js#2686]
- Formio.js version: 4.9.5
- Frontend framework (pure JS)
- Browser: All

## Steps to Reproduce
1. Configure a form that has embedded a nested form that contains a file upload field
2. Render the configured form passing a custom fileService in options.
3. Try to upload a file in the nested form

## Expected behavior
configured fileService upload function should be called.

## Observed behavior
the custom fileService is not inherited from the parent form and it falls back to the default implementation.

**Comment by wag110894** [comment]
Hello @llaurentiu, 

Can you try upgrading to the latest version of our Formio.js and see if you are still able to replicate?

If so, then can you provide a JSFiddle as well as a screencast of the issue occurring?

Thank you.

**Comment by elibus** [comment]
Hi @wag110894 , @llaurentiu submitted the PR #2687 to fix this.

**Comment by elibus** [comment]
@wag110894 this can be closed as #2687 was merged
