### ISSUE TITLE
Optimal approach to customize API property names

### ISSUE THREAD

**Issue by zakarea-Tfaili** [formio/formio.js#2693]
Hi guys ..

I'm wondering how to change the API "property name" value during the drop event or even on competent creation.

Property name should be configured automatically when we add a component not manually.

I have a list of values for each component type that I should use.

Thanks.

**Comment by randallknutson** [comment]
We've had people request this before. You should be able to do this by modifying the editform for components and replacing the property name textfield with a select dropdown.

**Comment by zakarea-Tfaili** [comment]
I really do not want to change the textfield to dropdown as the user can later change the name to whatever he wants the name will be used only during initiation and to override the added number when 2 components of the same name exists.

**Comment by randallknutson** [comment]
This is the code that sets the auto generated property name: https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L1163-L1168

You can either modify it or if you are able, contribute back a way to customize the generated key.

**Comment by zakarea-Tfaili** [comment]
Thank you @randallknutson.
I'll check the best way to achieve the above.

Regards

**Comment by rahabchung** [comment]
@zakarea-Tfaili Any good news?
@randallknutson I saw in line 1163-1168 highlighted rebuild function, could tell in rebuild function where change the key(Property Name)? thanks!
