### ISSUE TITLE
How to trigger validation from one form to another form on submit button click.

### ISSUE THREAD

**Issue by soumyamishra12** [formio/formio.js#2698]
```
<formio id="Fields"  [refresh]="refreshForm2" [form]="form1" [submission]="submissionData2" (change)="customChange2($event)" (customEvent)="customButton($event)">
    </formio>
```

  ```
  <formio id="formFields"  (submit)="Add()" [form]="form2" [submission]="submissionData3" (customEvent)="customButton($event)">
    </formio>
```

I have a submit event which validated all the field for mandatory and etc in form1 and form 2
The submit action only gets attached to form 2.
Until i change something in form1 the validation field field it doesn't fire .
Any way i can fire it manually to show inline errors also?

formiojs version : 3.6.11

**Comment by soumyamishra12** [comment]
Any body has any idea how to do this .
Does formio supports any custom things to achieve this.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
