### ISSUE TITLE
Datagrid not triggering  ON change event (on row delete)

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#270]
I'm having a problem with the Datagrid component. When I delete a row, the On change event is not triggered. Any clue about this?

Regards!

**Comment by cabrerabywaters** [comment]
I think https://github.com/formio/formio.js/pull/271 could fix it

**Comment by Aiso786** [comment]
Yes, it works now. But the row isn't deleted from the form values. I'll open an issue.

**Comment by travist** [comment]
Fixed both issues.
