### ISSUE TITLE
[help wanted] [question] Can I tie into a components on change event?

### ISSUE THREAD

**Issue by chapmasc** [formio/formio.js#2701]
formio.js - using latest version.

I tried to use labels of help wanted and question. I did something wrong though and it was given a label of bug. Sorry, if you know how I can change this, please let me know.

I want to set a default value of a dropdown list, based on the selection of another dropdown list. Not cascading, as I'm not filtering the available options in the secondary list, rather defaulting the value.

In my use case, I have the requestor of the form. I've tied this with an API call to allow querying of AD. Once the requestor value is selected, I want to default the second dropdown list for manager; to the manager of the requestor. I can do this by making another API call. I need this to only be done when the requestor value changes though, as the user could select a different manager than the one that I defaulted it to for them. I've attempted to do this with the Advanced logic, however, it seems that is fired every time the form is changed (any component in the form is changed), not just when the component listed in the trigger logic changes. So when I go to select a manager other than the default one, it resets it back to the default manager of the requestor, not the new one I selected.

**Comment by tnorthcutt** [comment]
@chapmasc You can absolutely do this. Here's an example. This is taken from inside a Vue component, thus using `this.form =`, but you should be able to adapt this.

```
this.form = Formio.createForm(document.getElementById(this.id), this.formUrl, {});

this.form.then( form => {
  form.on('change', event => {
    // 'location' is the property name from the API tab of the component settings we want to watch for a change on 
    if (event.changed && event.changed.component.key === "location" && event.changed.value) {
      // Set your default value here. Not sure, but this might work:
      const secondary = form.getComponent('secondary');
      secondary.setValue('newDefault');
    }
  }
});
```

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
