### ISSUE TITLE
Loading spinner gone?

### ISSUE THREAD

**Issue by thenixtone** [formio/formio.js#2704]
Hi guys,

I've upgraded from 3.X.X to latest 4.X.X, I've noticed the blue loading spinner is now gone. Is there an option somewhere to enable this or is it gone for good?

Cheers

**Comment by randallknutson** [comment]
I'm not sure which spinner you are referring to. The loading process is quite different between 3.x and 4.x so it may be that the loading icon has changed. It should still work though if the form is waiting on a load.

**Comment by thenixtone** [comment]
The form would be sorta greyed out with a blue spinner overlaying where the form usually displays and no fields until the spinner goes away and the fields appear.

It seems my forms now just load onto the page with no spinner.

Here is a screenshot from 3.X.X https://i.imgur.com/GvPqXX5.png
On my updated version, I do not have that at all

**Comment by randallknutson** [comment]
I'm not entirely sure what changes we made around this. We haven't had any other issues from other customers related to it. Is it something that is causing issues for you?

**Comment by thenixtone** [comment]
Well yeah... I don't want people seeing fields load in, stuff change, etc.

As a work around I was going to make my own but the 'render' event doesn't get triggered, 

https://github.com/formio/formio.js/wiki/Form-Renderer

form.on('render'), 'change' works, unsure why render doesn't?

**Comment by randallknutson** [comment]
The render doesn't work that way because it triggers before the initial promise is resolved so by the time you have the "form" variable it is already triggered.

I believe the initial object returned can listen for the render event though and since it exists early enough it can trigger.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
