### ISSUE TITLE
Old Docs for Customcomponent 

### ISSUE THREAD

**Issue by marcus-at-localhost** [formio/formio.js#2708]
Is it possible to keep the docs for how to create custom components without build process?

https://github.com/formio/formio.js/blob/6b19a89673d56cd516062778abd000d5933fe053/app/examples/customcomponent.md

Is is creating custom components this way, obsolete?

**Comment by randallknutson** [comment]
This was just updated with the most recent: https://github.com/formio/formio.js/wiki/Custom-Components-API

**Comment by marcus-at-localhost** [comment]
I'll close this, the old docs are not completely gone. Just harder to find :)
