### ISSUE TITLE
[ASK] Wrapper for FormioJs Component

### ISSUE THREAD

**Issue by dorianEXOR** [formio/formio.js#2711]
Hello formiojs community, 

we would like to implement a wrapper for a formiojs component. This could be a vanilla number field and also a custom component extending from a formiojs base component. 

Is there a possibility to wrap these components like a regular angular component, preferably using a html-tag? Can you set a selector for a formiojs component? 

It could be similar to the following example where the component is registered to the DOM. In constrast to this example, I would like to be able to do the same for an extended formiojs component. 

```
const PopupElement = createCustomElement(PopupComponent, {injector});
    // Register the custom element with the browser.
    customElements.define('popup-element', PopupElement);

```

The problem is similar to the problem described in (https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075) where several commentators were having a similar issue that still seems to be unresolved.

Thank you!

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
