### ISSUE TITLE
How to modify the validation error message ?

### ISSUE THREAD

**Issue by mustafabutt** [formio/formio.js#2718]
Hello,

I have been working with Form.io Angularjs version. The problem I have been facing is that, form validation error message appears inline.
<img width="1176" alt="Screen Shot 2020-04-28 at 7 59 11 PM" src="https://user-images.githubusercontent.com/13907970/80503085-d6c5c980-898a-11ea-91b3-f153ab6d964e.png">

Whereas, I want this message to appear like in floating position. 
<img width="669" alt="Screen Shot 2020-04-28 at 7 59 30 PM" src="https://user-images.githubusercontent.com/13907970/80503174-f1983e00-898a-11ea-8880-a7827892ad7e.png">

Looking forward for the help. Thanks

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
