### ISSUE TITLE
First value os select component doesn't accept value inputed

### ISSUE THREAD

**Issue by ricardoruntask** [formio/formio.js#2719]
When you add a Select component, with Data Source Type = Values, the first value of Data Source Values doesn't accept the value were inputed. 
When you create a list of item and save, close and open, this value become the same value as label value (in lowercase). The others values accept what you want to input.

**Comment by wag110894** [comment]
This is a known issue that has been resourced to one of our developers.  For reference, the ticket number is FJS-887.

**Comment by mohlendo** [comment]
Is there a timeframe when this bug is fixed? 
I could also provide a PR since our project is seriously affected by this bug.

**Comment by wag110894** [comment]
Hello @mohlendo We do have a PR up for this build, but we are still working on adding tests around it to make sure that this issue does not happen in the future. We will let you know once this issue has been resolved. The PR is here: https://github.com/formio/formio.js/pull/2705

**Comment by wag110894** [comment]
Hello @mohlendo, this issue has been resolved on the latest version of formio.js. (4.10.3)

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
