### ISSUE TITLE
Form is submitted when 'enter' key is pressed on a Text Area

### ISSUE THREAD

**Issue by josefernand** [formio/formio.js#272]
I just noticed that now the form is submitted on an 'enter' key is pressed on a Text Area component and it doesn't allow create a new line. This was not happening in previous versions.
Also I was wondering if there is any option to prevent the submit when I hit the enter key on a Text Input component. Thanks.

**Comment by bradswanson1** [comment]
I don't like to have 'enter' submit the form by default. A lot of users may press enter when the focus is on some element inside the form, and the form will submit before they are finished completing it. I think it's much better to prevent accidental submissions, than to make it possible to submit at any time by pressing 'enter'.

**Comment by masmerino13** [comment]
I'm having the same issue, my customer have too many accidental submission.

Please help with that issue!

**Comment by josefernand** [comment]
I've been debugging a bit and I found something. The TextArea component (when it's not a `wysiwyg` component) is adding a submit listener in the `addInput` via its base component. I think a fix can be override the `addInput` in the `TextArea` component removing the `addInputSubmitListener`:
```
  addInput(input, container) {
    if (input && container) {
      this.inputs.push(input);
      input = container.appendChild(input);
    }
    this.hook('input', input, container);
    this.addInputEventListener(input);
  }
```
Please, let me know if this would work or If I can help in any other way. Thanks!

**Comment by travist** [comment]
This is serious. I will investigate tonight and should have new version soon.

**Comment by travist** [comment]
I agree to not have it on by default. I added this to the latest build ```2.24.5``` but if you wish to have this functionality you can enable it with the ```submitOnEnter``` flag like so.

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
  submitOnEnter: true
});
```
