### ISSUE TITLE
[BUG] URL encode url before caching key

### ISSUE THREAD

**Issue by pavlkara1** [formio/formio.js#2732]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [X] Local deployment
- Formio.js version: 4.9.24 but also present in master
- Frontend framework: Angular
- Browser: All
- Browser version:

## Steps to Reproduce
1. Create a form with SelectComponent 
2. Enable search
3. Type a non latin character

## Expected behavior

We would expect the cacheKey to be generated by encoding the url first and the cache key to be generated successfully

## Observed behavior
We are getting an error: 
```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

This is fixable just by changing [this line](https://github.com/formio/formio.js/blob/master/src/Formio.js#L811) 

to its url encoded counterpart. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

**Comment by wag110894** [comment]
Hello @pavlkara1,

Thanks for reaching out! We have created a ticket and have added this to our backlog. We welcome a pull request and have a process to expedite. We will let you know once this issue is resolved.

**Comment by pavlkara1** [comment]
I have opened a pull request which seems to solve this issue.
