### ISSUE TITLE
Have a button in my page where the form is using the json from formio.But I want to clear all my fields when the button is pressed. Initially when the page loads the button would not appear. Once I make changes to any of the field inside then it would appear. Now My question is how to clear the form fields with the errors when I am pressing that button.

### ISSUE THREAD

**Issue by developersatyajit** [formio/formio.js#2737]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework: React
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Page Loads the form will open
2. Now I am making changes to any field of the form
3. Once I change a button would appear for example say Clear
4. Now if I press the clear button my form field value should clear alongwith the errors.
5. Just like reset button.
6. The clear button is not inside the json schema
7. Please explain your answer as I am new to this formio.

## Expected behavior
It should work like a reset button

## Observed behavior
The form remains the same. Once any error generates its just hold that position along with the value. Nothing is removing.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
@developersatyajit, can you provide a video or a jsfiddle of the issue occurring?

**Comment by developersatyajit** [comment]
Let me know which section you have problem. Cant provide you a video or jsfiddle. I am in the middle of my codebase.

**Comment by developersatyajit** [comment]
Let me simplify this:
I have a form in my page which coming from the schema but the buttons are not there in the schema. I am adding those buttons when the page renders. Two buttons are there one is save and another is cancel. On changing any field the cancel button would appear which is not visible at the time of render. While saving the form it works perfectly. But when cancelling, the errors are still there in the form. I want to remove those errors. How to do that?
Clicking on cancel should remove those errors that's what I need.

**Comment by developersatyajit** [comment]
Can you help me please?

**Comment by wag110894** [comment]
Thank you for reaching out!

We are able to replicate this issue on our side. We have created a ticket and have added this to our backlog. For reference, the ticket is FJS-908. We welcome pull requests and have a process to expedite. If you are interested in expediting,then please contact support@form.io.

We will let you know once this issue has been resolved.

**Comment by wag110894** [comment]
@developersatyajit Thank you for your patience while we worked on getting this issue resolved. 

This issue has been resolved in version 4.10.0-rc.3.

Thank you for using Form.io!

**Comment by developersatyajit** [comment]
I made it through by using some other predefined function. By the way
thanks for your time and help. Really appreciate it.
