### ISSUE TITLE
Proper way to show/hide components?

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2738]
I've searched the docs fairly extensively but haven't found anything on this. Is there a "Right Way" to programmatically hide and show components?

I've tried using:

```
let myComponent = form.getComponent('componentName');

// To hide:
myComponent.component.hidden = true;

// And to show:
myComponent.component.hidden = false;
```

While this works for hiding a component, I'm having some trouble with showing it later on. Sadly a jsfiddle reproduction doesn't work; it shows there just fine, so there must be something about my scenario that's more complicated.

Is there another, or better, way of hiding and showing a component?

**Comment by marcus-at-localhost** [comment]
I'm not a 100% sure, but could it be that you need to trigger a redraw? There must be a `redraw()` function or `triggerRedraw()` somewhere on some object...

**Comment by tnorthcutt** [comment]
@marcus-at-localhost thanks for the suggestion; unfortunately that isn't working for me.

I'm now running into a related issue, where setting a component to `hidden = true` isn't sufficient, because if that component (or any child components, if it's a layout component) are required, then submitting the form fails completely.

I've tried deleting the component entirely from the form object, but that doesn't work – it neither hides the component (even with a `form.redraw()`), nor does it eliminate validation/required errors if the fields in the component are not filled out.

I'm hoping @randallknutson or @travist might have a suggestion here... 😄

**Comment by travist** [comment]
Here is what I would suggest. The way to get around server side validations is to utilize the Conditionals on that field to indicate that the field is conditionally hidden. If that is the case, then it will not trigger validations on both client and server. So to solve this problem, I would do the following.  Add a conditional statement on the component, or the parent component, that determines its visibility based on the value of a hidden field like so.

show = data.hiddenValue;

You will then set the component hidden by altering the value of that hidden component like so.

```
const component = form.getComponent('hiddenField');
component.setValue(false);
```

This will then make the fields conditioned on that hidden field hide, but the difference here is that the hidden field value will get passed along to the server and it will ensure based on conditions that the required field is not validated because of the conditions. I have not tried this personally, but am pretty sure it will work.

**Comment by tnorthcutt** [comment]
@travist Thanks for the suggestion! 

One potential problem with this approach: we have several forms with a dozen or more components, that will need to be programmatically shown/hidden based on earlier interactions our users have with our application.

It sounds like with the strategy you're suggesting, we'd need a hidden field for each field in our form. That starts to feel a bit fragile to me – is it possible there's a more direct approach that could work?

**Comment by randallknutson** [comment]
The other way to do this would be to use the config on the form and set the conditional based on the config. For example, You can set form.config = {myvalue: true} when instantiating the form. Then in the custom conditionals you can make it conditional based on "show = config.myvalue === true"

Either that or you can pass a hidden component value into the form in the submission and make fields conditional based on that value.

**Comment by tnorthcutt** [comment]
@randallknutson that method sounds very appealing, thanks!

After some experimenting, it looks like once the form is rendered, any changes to e.g. `form.config` won't trigger a component to be hidden based on a conditional set in the form.io form editor.

E.g. if I do:

```
this.form = Formio.createForm(element, url);

this.form.then( form => {
  form.config = {
    show: false
  }
});
```

That doesn't result in hiding a form component that has this as its advanced conditional: 
```
show = form.config.show;
```

I did try following the `form.config = {}` block with `form.redraw()` in the hopes that it would trigger hiding the conditional component, but that didn't work.

**Is there some way to set values for `form.config` before the form is rendered?**

I am really hoping I can get this method to work, as it sounds a lot more feasible for our use case than the hidden component value method.

If you have any suggestions, I'd appreciate it very much!

Thanks.

**Comment by randallknutson** [comment]
I think it will work if you intercept in the onFormLoad (or formLoad depending on your platform) and make modifications there. That happens before the instantiation and rendering.

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson.

Unfortunately, it looks like the `formLoad` event may not be firing. Here's a jsfiddle showing that: https://jsfiddle.net/tnorthcutt/kj1ou9s3/3/

Is it possible I'm misunderstanding how I should be intercepting the `formLoad` event? From looking at the source code, it looks like that's the proper event name; we're using the vanilla js library, not React or Vue (though we are using the vanilla formio.js library in a Vue component; though I don't think that would matter here...?).

Thanks for any suggestions.

**Comment by tnorthcutt** [comment]
@randallknutson any chance of an update on this? Thanks!

**Comment by randallknutson** [comment]
This is because the form instance is returned AFTER the formLoad event has been fired. You may need to instantiate the Form directly and put the event listener on the root instance. 
https://github.com/formio/react-formio/blob/master/src/components/Form.jsx#L56
https://github.com/formio/react-formio/blob/master/src/components/Form.jsx#L87

**Comment by tnorthcutt** [comment]
Thanks, @randallknutson.

Do you happen to have an example of how to do that with the vanilla JS library? I'm struggling to connect the dots between the code you linked and using just the vanilla library... long week 😁

**Comment by randallknutson** [comment]
I don't have a good example of this and tried to do it yesterday. Looks like in the ngFormio library we are just manually calling formLoad. https://github.com/formio/ngFormio/blob/master/src/directives/formio.js#L56-L61

You can probably do something like this where you just set the form again after the promise resolves.
