### ISSUE TITLE
Broken docs page for Component class

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2739]
Clicking the link for `components/_classes/component/Component` in the [generated docs](https://formio.github.io/formio.js/docs/) leads to this URL, which produces a 404: https://formio.github.io/formio.js/docs/class/src/components/_classes/component/Component.js~Component.html

![CleanShot 2020-05-01 at 16 35 20@2x](https://user-images.githubusercontent.com/796639/80846586-f26ae300-8bc9-11ea-9519-4fb0dc268a08.png)

It would be pretty handy to be able to read those docs, though! Is there any way to fix that?

**Comment by tnorthcutt** [comment]
Same thing for the Formio class; it leads to this URL: https://formio.github.io/formio.js/docs/class/src/Formio.js~Formio.html

![CleanShot 2020-09-29 at 12 53 22@2x](https://user-images.githubusercontent.com/796639/94602936-c88a1b00-0252-11eb-8422-89bdde58009a.png)

**Comment by wag110894** [comment]
Hello @tnorthcutt, 

Sorry about that. We will work on getting that fixed.
