### ISSUE TITLE
[BUG]  Call custom logic

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#2741]
- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: latest
- Browser: Chrome 
- Browser version: 81.0.4044.129

## Steps to Reproduce
1.  Create two text fields
2. Add custom logic on first text field

## Expected behavior
Call custom logic when use text field with custom logic
When use another text field - logic is not called
## Observed behavior
When use another text field - logic is called
## Example
https://jsfiddle.net/d05ve6ou/
--Add value on second textfiled
--Logic in first textfield call console.log()

**Comment by wag110894** [comment]
@homashevchenko Thank you for providing the JSFiddle. It does not look like there is an action attached to the Logic. Can you try adding action and let me know if the issue still occurs.

Thank you.

**Comment by homashevchenko** [comment]
Why is the component logic invoked each time while it does not even change?
How can I invoke logic of component once when change value?

Thanks

**Comment by randallknutson** [comment]
I just tested your JSFiddle and the custom trigger javascript was triggered when I entered a value in either field. This is how it is supposed to work. On any form change event the custom javascript is run to determine whether or not to trigger the logic.

**Comment by homashevchenko** [comment]
How can I invoke logic of component once when change value?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
