### ISSUE TITLE
[BUG] Select with Storage Type Number and no default value shows and saves 0

### ISSUE THREAD

**Issue by mohlendo** [formio/formio.js#2742]
Using a select component with storage type set to 'number' and no default value leads to unexpected value. The select then shows a '0' and when saving the form, this value is also submitted.
I would rather expect to have no value submitted. Using storate type set to 'auto' and it works.

**Comment by wag110894** [comment]
@mohlendo,

Can you provide a form embed or a JSFiddle of the issue taking place?

Thank you.

**Comment by mohlendo** [comment]
`<script src="https://unpkg.com/formiojs@latest/dist/formio.embed.js?src=https://hwqkykwnapqshan.form.io/selecttest"></script>`

**Comment by wag110894** [comment]
Hello @mohlendo,

Thank you for providing your form embed. We are able to replicate this issue on our side. We have created a ticket and have added this to our backlog. For reference, the ticket number is FJS-914. We welcome a pull request or have a process to expedite if you are interested.  Please contact support@form.io if you are interested in having this issue expedited.

**Comment by mohlendo** [comment]
@wag110894 I think this issue is related to #2705

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
