### ISSUE TITLE
[BUG] address field provider is overridden during address component initialization

### ISSUE THREAD

**Issue by deniszo** [formio/formio.js#2755]
## Environment
- Formio.js version:  >= 4.9.24
Originally discovered using `angular-formio@4.7.9`

## Steps to Reproduce
1. Add an address field with `Azure maps` provider
2. Render this form with formiojs of version `>=4.9.24`
3. Try to search an address

## Expected behavior
Azure maps api is called

## Observed behavior
Google maps api is called

## Example
https://jsfiddle.net/658vpsez

The reason is this line, which sets the provider value to `google`: https://github.com/formio/formio.js/blob/v4.9.24/src/components/address/Address.js#L116

The form field structure in jsfiddle example is provided without any modifications (apart from subscription key) from what is generated by form.io form builder. In this case `this.component.map` has the value of
```
  "map": {
    "region": "",
    "key": ""
  },
```
so the condition `if (this.component.map) {}` is always true and `provider` value gets changed

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
