### ISSUE TITLE
[BUG]  Number component does not save null value after having a value filled in the field.

### ISSUE THREAD

**Issue by ricardophone2b** [formio/formio.js#2756]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:4.9.14
- Frontend framework: React
- Browser: Chrome
- Browser version: 81.0.4044.129

## Steps to Reproduce
1. Insert a Number Component
2. Fill with any value
3. Save
4. Edit the form, clear value and save
5. Then you will see that value doesn't change. It doesn't happens with Text Component.

## Expected behavior
Clear value. 

## Observed behavior
Value doesn't clear. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
@ricardophone2b We are not able to replicate using the latest version formio.js (4.9.20). Can you upgrade to this version and see if the issue persists?
