### ISSUE TITLE
Signature Component

### ISSUE THREAD

**Issue by JayashreeKrishanveni** [formio/formio.js#2759]
How I get the signature component in my rendered PDF ?  ( Generating PDF using separate application using itext7)

**Comment by randallknutson** [comment]
The signature component should work with pdfs just fine. The one place where it tends to trip people up is that the signature is not returned in index requests (where you request multiple submissions at the same time). Instead, you need to request them individually by id. The reason for this is that the response gets very large if you include the signatures in the index.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
