### ISSUE TITLE
Missing component: "editgrid"

### ISSUE THREAD

**Issue by Aiso786** [formio/formio.js#276]
Hello, the "Edit Grid" component is missing in the the "formio.js" form renderer.

Is it going to be released ?

This component is provided in the Angular form renderer:
https://github.com/formio/ngFormio/blob/master/src/components/editgrid.js

Thank you very much for your help.

**Comment by cabrerabywaters** [comment]
+1

**Comment by Aiso786** [comment]
I close the issue because @randallknutson is working on it
