### ISSUE TITLE
[BUG]  tinymce change value

### ISSUE THREAD

**Issue by kist80hu** [formio/formio.js#2764]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.10.0-beta.14
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

this.addTiny(element, settings, (newValue) => this.updateEditorValue(newValue))
// your code here
this.addTiny(element, settings, (newValue) => this.updateEditorValue(index, newValue))

**Comment by randallknutson** [comment]
Can you help us understand what the issue is?

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
