### ISSUE TITLE
[Question] extending Webform class in custom renderer

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#2765]
Hi,

I'm just wondering if there is away to extend the Webform.js class
I'm hoping to be able to add translation to message like "Are you sure you want to cancel?" that is hardcoded in this class. Since our application is billingual these pop up confirmation should be able to be translated as well.

Thank you

**Comment by randallknutson** [comment]
First, we'd like these messages to be translated as there should be nothing that is hard coded to english within our application. If you want to submit a pull request for this we would gladly accept it. The solution should be to wrap the text in this.t() to enable translations on them.

Second, if you do want to override the class, you can do it by creating a module and registering a new display for webform. https://github.com/formio/formio.js/wiki/Modules. What you are looking for is called "displays" https://github.com/formio/formio.js/blob/master/src/formio.form.js#L47-L50. You can override the webform display with this.

**Comment by phucduong86** [comment]
Awesome thank you @randallknutson
