### ISSUE TITLE
[BUG] Select component empty until 3 characters are typed

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#2769]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.9.27-rc.1
- Frontend framework: N/A
- Browser: Chrome
- Browser version: 81

## Steps to Reproduce
1. https://jsfiddle.net/tnorthcutt/s06wzqmt/5/
2. Click the select component
3. No options are loaded until at least 3 characters are typed

## Expected behavior
Options should be loaded when the component is first loaded

## Observed behavior
No options are loaded until 3 characters are typed

This form component is using `URL` as its data source type, with a URL that returns json.

![CleanShot 2020-05-08 at 12 59 39@2x](https://user-images.githubusercontent.com/796639/81439820-36ab3580-912c-11ea-8d4d-fb0d3a02ce45.png)

**Comment by wag110894** [comment]
@tnorthcutt,

This is because the Minimum Search Length on the Data tab is set to 3 as a default. Here is a screenshot of the settings: https://share.getcloudapp.com/GGukJAyN 
You can make this blank in order for all options to be available. Here is 
I hope that this helps.

**Comment by tnorthcutt** [comment]
@wag110894 That's perfect, thank you!

FYI, that option doesn't seem to be present on the `portal.` subdomain, only the `next.` subdomain.

**Comment by wag110894** [comment]
@tnorthcutt Great to hear! That is correct. This is a new setting so it is not included in our Current Portal and is only available using our Next Portal.
