### ISSUE TITLE
Basic Question regarding Form Builder - How to generate the JSON? How to edit an existing Form?

### ISSUE THREAD

**Issue by davidkohcw** [formio/formio.js#2773]
Hi! Great Library, really enjoy using it and thanks so much for it. I've some really basic questions regarding the Form Builder but it seems i'm not the only one who has it (https://github.com/formio/formio.js/issues/2637 and https://github.com/formio/formio.js/issues/2583 )

**1. How to generate the Form JSON from the form builder?**
On the example [form builder ](https://formio.github.io/formio.js/app/builder), I see there is a JSON output column.

However, in the form builder generated from the code which I copied from the docs, I don't see a way to save/preview the JSON?

![image](https://user-images.githubusercontent.com/15072849/81524780-1fb35000-9385-11ea-915a-686f07332b00.png)

![image](https://user-images.githubusercontent.com/15072849/81524419-b8e16700-9383-11ea-91f0-bd008b2f7060.png)

The above screenshot is all I see.

Should I be using the example form builder instead?

**2. How to edit an existing Form using the Form Builder (can I upload JSON of its previous output?**

As you can see from both the screenshots I uploaded (one from the example Form Builder and one more generated from the code in the docs), I don't see clear way for me to upload a JSON to edit a form?)

![image](https://user-images.githubusercontent.com/15072849/81524709-c9461180-9384-11ea-8091-810e4f5946fd.png)

**Comment by travist** [comment]
You can either pass in the form in the constructor like so...

```
Formio.builder(document.getElementById('builder'), {
  components: [
    {
      type: 'textfield',
      key: 'firstName',
      label: 'First Name'
    }
  ]
});
```

Or you can call ```setForm``` on the builder instance.

```
Formio.builder(document.getElementById('builder')).then((builder) => {
  builder.setForm({
    components: [
       ...
    ]
  });
});
```

**Comment by randallknutson** [comment]
There is an example page at http://formio.github.io/formio.js/app/builder if you look at the source.

**Comment by davidkohcw** [comment]
Thanks so much @travist for that tip, it was a great help!

Thanks @randallknutson too! I didn't realize that it was saved as a markdown file in the source. I manage to find what I need :)
