### ISSUE TITLE
[BUG] Radio component with duplicate option values

### ISSUE THREAD

**Issue by sharique5** [formio/formio.js#2786]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
    - Version: formiojs@latest
- Formio.js version: latest
- Frontend framework: Vanilla JS
- Browser: Any
- Browser version: Any

## Steps to Reproduce
1. Create a formio form with **Radio** Component 
2. Add options in radio component with a duplicate key
3. Click on the option label with duplicate key
GIF with steps to reproduce: https://gifyu.com/image/n3ug

## Expected behavior
Clicked label option should get selected

## Observed behavior
First option with the key is getting selected

## Example
https://codepen.io/sharique_5/pen/gOajgGg

Form Config:
```js
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Radio",
            "optionsLabelPosition": "right",
            "inline": false,
            "tableView": false,
            "values": [
                {
                    "label": "First",
                    "value": "first",
                    "shortcut": ""
                },
                {
                    "label": "Second",
                    "value": "second",
                    "shortcut": ""
                },
                {
                    "label": "FirstDuplicate",
                    "value": "first",
                    "shortcut": ""
                }
            ],
            "calculateServer": false,
            "key": "radio1",
            "type": "radio",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by wag110894** [comment]
@sharique5 This is occurring because of the values of First and FirstDuplicate must be unique.

I hope that this helps.

**Comment by sharique5** [comment]
Thank you @wag110894
