### ISSUE TITLE
Problem when deleting rows on Datagrid component

### ISSUE THREAD

**Issue by Aiso786** [formio/formio.js#279]
Hello guys, i have the following issue on the latest verison of formiojs (v2.25.2).

I have a Datagrid component with a list of rows:
![image](https://user-images.githubusercontent.com/22521614/33718560-2206a96a-db5e-11e7-9f2e-9dd20c178c4c.png)

If i delete the second row, when i save and come back into the form, i still have 3 rows:
![image](https://user-images.githubusercontent.com/22521614/33718641-7274c314-db5e-11e7-8467-f7249c725f3f.png)

When i look at the the form values submitted, i second that the third row has been is dupliated:
![image](https://user-images.githubusercontent.com/22521614/33718696-976874a4-db5e-11e7-87c1-5c2f39b135c8.png)

I'm trying to figure out where the bug is, but I need help.

**Comment by travist** [comment]
I found the problem. The issue was how the Lodash merge method treats nested arrays. 
Here is the fix https://github.com/formio/formio.js/pull/280

Going to release 2.25.3 with the fix.

Thanks!
