### ISSUE TITLE
[QUESTION] i have run "npm run serve" but It's not watch files change

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#2792]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: lasted
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

I have run "npm run serve" or "gulp". And i change the js files,but the web is not refresh.It is not watch files change. 
Can you tell me how to run?

**Comment by travist** [comment]
We don't perform a watch in our npm run serve method. This would need to be added as a feature request.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
