### ISSUE TITLE
Contrbution guide

### ISSUE THREAD

**Issue by iknityanand** [formio/formio.js#2803]
Hey would i be able to get new developer contribution guide to setup on local.
I have already clone on my local and unable to know where to start from to understand formiojs development flow.
Or if you have already have one can u please point me there.

**Comment by wag110894** [comment]
@iknityanand, have you taken a look at this documentation: https://help.form.io/userguide/environments/?

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
