### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by Bdestasio33** [formio/formio.js#2811]
Is there any way to possibly prevent having nested data array components inside of each other. For instance prevent a Panel from being embedded in a panel but you can put two panels in the same form component. Thanks for any help.

**Comment by randallknutson** [comment]
Panels are purely layout and don't affect the data of a form submission. We don't currently have any mechanism for preventing someone from putting a panel into a panel.

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
