### ISSUE TITLE
How to use Formio's Built-In Form Validation without Writing to Server?

### ISSUE THREAD

**Issue by Austinchambers1** [formio/formio.js#2827]
I am trying to write our formio submissions to a separate database on submit, without writing to the server that hosts our formio instance, while also still displaying formio's built-in validation error messages if the form is incomplete or invalid.

![image](https://user-images.githubusercontent.com/13229467/82580645-019fd980-9b55-11ea-9740-66f2eb6aaf6a.png)

One work around I have found is calling the beforeSubmit hook and manually checking all of the fields while only invoking next() if a required field is missing, otherwise I send it to to my custom post function. This does not scale well for large forms with a lot of required fields. Is there a better way of achieving this? 

```          
beforeSubmit: (submission, next) => {
            // check for invalid fields manually and call next. Next will notice the missing/invalid values and trigger Formio's validator
            if (submission.data.badge == "") {
              next();
            } else {
              // call my own submission function
              this.submitForm(submission);
            }
          }

**Comment by randallknutson** [comment]
There is another hook called "customValidation" that is probably more what you are looking for. 

https://github.com/formio/formio.js/blob/master/src/Webform.js#L1362

It occurs after all "before" functionality and the regular form validations have occurred. You can also easily return an error that is set on the form (or form component)

**Comment by Austinchambers1** [comment]
Thank you for your quick response. To clarify, I want to print the error messages that Formio gives on submit by default and it looks like that hook is for making custom ones. I essentially just want it to validate the input as normal without actually writing to our server if that is possible. I am trying to avoid manually writing out conditional statements for the required fields. If I am misunderstanding "customValidation" and it can achieve that, are you able to link to some kind of documentation?

For example is there a way to create this logic

```
if required fields empty:
  show error messages
else
  trigger our own function and ignore the formio backend

**Comment by randallknutson** [comment]
That's exactly what this hook will do. It will fire AFTER all built in validations fire so they will all pass before it gets to this hook. You can then call async code to run your code and return any custom validations. 

If you don't want to run your own validations, you can also set nosubmit = true and listen to the "submit" event for when the validations are run. 

Here is an example: http://formio.github.io/formio.js/app/examples/customendpoint.html

**Comment by Austinchambers1** [comment]
Hello,

After tinkering a bit more I understand how to use custonValidation now and it works as intended. Thanks!
