### ISSUE TITLE
[BUG] Inacurate Remaining word count 

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#2847]
## Environment
Please provide as many details as you can:

- Hosting type
N/A
- Formio.js version: 4.9.26
- Frontend framework: Javascript
- Browser: Chrome
- Browser version: 81.0.4044.129 (Official Build) (64-bit)

## Steps to Reproduce
1.  Example form: https://codepen.io/duongph/pen/PoPvPVe?editors=1010
2.  Type in some data into text field

## Expected behavior
If the data is "I chose option d1 and", the Word count should be 0 and there is no error
If the data is "I chose option d1 and other", the Word count should be -1 and max word error shows up
The word count shouldn't change if the word contains both digit and character.

## Observed behavior
If the data is "I chose option d1 and", the Word count is -1 and there is no error
If the data is "I chose option d1 and other", the Word count is -2  and max word error shows up
The word count goes up (remaining words goes down) everytime the character switch to digit of vice versa (eg: e1t3g would count as 5 words)

## Example
https://codepen.io/duongph/pen/PoPvPVe?editors=1010

**Comment by wag110894** [comment]
Hello @phucduong86, this issue is actually resolved using the latest version of our formio.js (Renderer: 4.10.0-rc.3). Please let me know if you have any further questions.

Thank you.

**Comment by phucduong86** [comment]
Hi @wag110894 ,
I tried both 4.10.0-rc3 and 4.10.0-rc4 and the issue still persists.

![image](https://user-images.githubusercontent.com/21692768/83099039-24148400-a07a-11ea-92b9-628c113d6985.png)

**Comment by wag110894** [comment]
@phucduong86 does the errors not allow you to submit the form? We are able to replicate this item and have created a ticket to have this issue resolved. We welcome a PR and also have a process to expedite. 

The ticket number is FJS-967.

**Comment by phucduong86** [comment]
Thank you @wag110894 
It does not stop me from submitting the form so right now we just don't use that feature.

**Comment by jhen1422** [comment]
@phucduong86 issue should be resolved in version 4.10.0-rc.11
