### ISSUE TITLE
[BUG] formio.js requires unsafe-eval tag to operate

### ISSUE THREAD

**Issue by Sefriol** [formio/formio.js#2849]
## Environment
Please provide as many details as you can:
Adding CSP headers will raise an error and forms won't render:
![image](https://user-images.githubusercontent.com/6150958/83110778-446d2e80-a0cc-11ea-84e8-bffc6a6bab94.png)

Which refers to:
https://github.com/EventEmitter2/EventEmitter2/blob/master/lib/eventemitter2.js#L306

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Nginx 1.7.8
- Formio.js version: 4.9.26
- Vue-Formio version: 4.0.2
- Frontend framework: VueJS 2.6.11
- Browser: Chrome
- Browser version: 81.0.4044.138

## Steps to Reproduce
1. Apply CSP headers without `unsafe-eval` tag
2. Run the environment

## Expected behavior
I guess formio should work without unsafe-eval tag.
## Observed behavior
It does not.

So, I just wonder if this is fixable by using some other library.

**Comment by randallknutson** [comment]
You can turn off unsafe-eval for a web page and most of the form.io functionality will still work. There are some places where you can write custom javascript (such as default values and custom conditionals) that will not work if you do that but the system is designed to degrade gracefully and just not execute the javascript if that is the case.

We are finishing up some new functionality in the next major version that will allow configuring almost any contitional, validation and other functionality without needing to write any javascript. This should nearly completely remove the need for eval at all.

**Comment by Sefriol** [comment]
Maybe it's related to how things are loaded in Vue, but for me forms do not render at all. I need to checkout if this happens with simple forms as well, but also FormBuilder does not work for now.

**Comment by randallknutson** [comment]
Let us know what you find. We haven't had that issue before and have tested this without unsafe-eval and it worked.

**Comment by Sefriol** [comment]
From my initial testing, forms and from generator do not render / work even when using very simple forms. I just added a from which only has a text field and a submit button without editing it otherwise and when trying to view it, CSP raises an error within browser pointing to eventemitter. Otherwise, site is working normally.

I have not tested this in vue-formio-base-app, but our current implementation should not be that much different.

**Comment by randallknutson** [comment]
It appears there may need to be a setting to fully disable the eval by setting Formio.Utils.Evaluator.noeval = true; Apparently you need to set this to stop the evaluator.

**Comment by Sefriol** [comment]
That seems to work as mentioned as expected without CSP headers, but it does not seem to make a difference when headers are present. Maybe it will break when ever eventemitter is imported.

**Comment by randallknutson** [comment]
I believe we did make some changes recently around eventemitter and it is possible that we didn't test it with csp settings for no eval. This might have broken this functionality. Is this something you can make a recommendation on how to fix? We do want this to work.

**Comment by Sefriol** [comment]
I can try downgrading the library to the point which you made the changes. Do you have specific version in mind? I am also unsure if these issues are just related to my environment. Are you able to test this with Vue?

**Comment by Sefriol** [comment]
There was also an old commit back in 4.0rc where you used EventEmitter3 instead of 2. Any reason why this was changed back? I think EventEmitter3 is CSP compliant.

https://github.com/formio/formio.js/commit/589d5fc3c08f50bc6da093719546a396e5023526
https://github.com/primus/eventemitter3/

**Comment by Sefriol** [comment]
Well I tried to just change to EventEmitter3, but another issue arised. Formio also uses lodash where some of the functions like `template` use eval:
https://github.com/lodash/lodash/issues/832

lodash would need to be built in CSP mode.

**Comment by travist** [comment]
Lodash is not an issue because we "pre-compile" all of our templates so it should never be calling "_.template" in runtime mode (unless you try to change EditGrid templates). As for us removing EventEmitter3, I am not sure what the reason was, but we would consider using it again since it is CSP compliant. What other issue arised from using it?

**Comment by Sefriol** [comment]
So far was not able to produce any other errors when testing EventEmitter3 without CSP headers and written tests went through with it (but unsure if the current tests are sufficient).

For Lodash, not sure where the issue is. Forms do not render with CSP and it points to it, but it might be some other library (doubt it) or just how Vue renders forms.

**Comment by Sefriol** [comment]
> It appears there may need to be a setting to fully disable the eval by setting Formio.Utils.Evaluator.noeval = true; Apparently you need to set this to stop the evaluator.

Using this and EventEmitter3. It seems that I was able to make formio.js CSP complient.

**Comment by travist** [comment]
Ok thanks @Sefriol. We will explore using EventEmitter3 for our version 5.x renderer we are working on at the moment.

**Comment by Sefriol** [comment]
A few functions seem to be missing compared to Eventemitter2:
https://github.com/primus/eventemitter3/issues/114

**Comment by jemann75** [comment]
This has been fixed in EventEmitter2 6.4.2 (https://github.com/EventEmitter2/EventEmitter2/commit/1e521f908c967c4d9774f803e05ab3272b54a75c)

**Comment by Sefriol** [comment]
Just to update this: `unsafe-eval` is no longer required when setting `Evaluator.noeval = true`, but this prevents the usage of custom validation functions. Unfortunately, we require these custom functions.

@travist @randallknutson Any estimate when the next major release is going live?

**Comment by randallknutson** [comment]
The 5.x branch is under development now but has a lot more features to be completed first. We are looking at around the end of the year for a release of it.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
