### ISSUE TITLE
[BUG] Angular app with formiojs not working on Mozilla, IE 11, Edge

### ISSUE THREAD

**Issue by MihaiRebegea** [formio/formio.js#2850]
## Environment
I have an Angular app where I integrated formiojs.
I'm not using the formio-angular component because I need to authenticate the user via token swap and I'm using formIOFetch plugin to fetch some data from my backend.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.9.26
- Frontend framework: Angular version 8
- Browser: Mozilla, Internet Explorer 11, Edge
- Browser version: Mozilla 76.0.1, IE 11, Edge 44.18362.449.0

## Steps to Reproduce
1. Create simple Angular component
2. Import formiojs
3. Use anything related to formio in the component for ex: Formio.logout(); 

## Expected behavior
App should start without issues like on Chrome or Opera

## Observed behavior
Blank screen appears in Mozilla, IE11, Edge.

Following error appears in the console:

_Error: "Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)"_

I found this ticket which states the same error https://github.com/formio/angular-demo/issues/15
However updating to formiojs version 4.9.26 didn't do the trick for me.

Thank you in advance for your help

**Comment by travist** [comment]
I believe this was resolved with the latest version of angular-formio.

https://github.com/formio/angular-formio/issues/552
