### ISSUE TITLE
[BUG] Unable to save images from mobile in S3  

### ISSUE THREAD

**Issue by oneserve** [formio/formio.js#2851]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.9.25
- Frontend framework: Angular 8
- Browser: Ionic mobile app
- Browser version: 

## Steps to Reproduce
1. Create Formio form with File component. Tick 'Display as images'.
2. Configure storage for this component to S3 bucket.
3. Create Ionic mobile app including cordova-plugin-camera and FormIO form.
4. Launch app on mobile device. 
5. In form, try to save photo with either "Gallery" or "Camera" buttons on FormIO form.

## Expected behavior
Photo is uploaded to S3 and displayed on form.
## Observed behavior
Photo not uploaded and broken image link displayed. Only 15 bytes of data uploaded to S3. 

## Example
See https://github.com/oneserve/formio-ionic4. 
The problem is with the uploadFile function in FormIO's s3.js. The 'file' object is serialized so that [Object object] is uploaded via PUT to S3. To resolve, the files need to be wrapped in a FormData object or returned from storage via FileReader.readAsArrayBuffer or similar.

**Comment by randallknutson** [comment]
This is going to be fairly difficult for us to set up a test environment to reproduce and fix this issue. Would it be possible to make a PR with some suggested changes to fix this?

**Comment by oneserve** [comment]
Sure, I can create a PR to demonstrate the desired outcome.

**Comment by oneserve** [comment]
I don't have enough knowledge of the code to create a solution/PR but hopefully the attached, modified s3.js adequately explains the problem. I expected the modifed code to resolve the situation but the sequence of callbacks isn't exactly as I expected.  
[s3.js.zip](https://github.com/formio/formio.js/files/4701940/s3.js.zip)

**Comment by oneserve** [comment]
I'm not sure there's good equivalent to test against. Any recommendations?  By altering File.js (see below) to block access to the native mobile camera I can force the app to use HTML e.g. File input for gallery access and getUserMedia to access the camera. When doing this the photo is uploaded to S3 as expected. However, we rely on the native camera for certain features so this isn't suitable for the production env'.

`var webViewCamera = navigator.camera || Camera;` => `var webViewCamera = Camera;`

**Comment by travist** [comment]
My guess is this is happening for all frameworks and we would be able to reproduce it for a javascript rendered form. We will put it on our planning list to discuss on monday.

**Comment by oneserve** [comment]
We can get the image upload to work as expected by modifying the getPicture functions in components/File.js to return a Blob (also attaching a 'name'). This means no changes required in s3.js and seems a cleaner solution. 

[File.js.zip](https://github.com/formio/formio.js/files/4710857/File.js.zip)

          webViewCamera.getPicture(function (success) {
            window.resolveLocalFileSystemURL(success, function (fileEntry) {
              fileEntry.file(function (file) {
                var reader = new FileReader();
                reader.onloadend = function(evt) {
                  var blob = new Blob([new Uint8Array(this.result)], { type: file.type });
                  blob.name = "photo-".concat(Date.now(), ".png");
                  _this5.upload([blob]);
                }
                reader.readAsArrayBuffer(file);
              });
            });
          }

**Comment by oneserve-alh** [comment]
This issue is resolved in the 4.10.2 release.
