### ISSUE TITLE
[BUG] - Datepicker/ Signature component do not display properly on pdf forms with zoom applied 

### ISSUE THREAD

**Issue by sebastianscatularo** [formio/formio.js#2856]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.7.7
- Frontend framework: Javascript
- Browser: Chrome
- Browser version: 83.0.4103.61 (Official Build) (64-bit)

## Steps to Reproduce

1. Create a PDF form and add a date pick and signature components
2. Open the pdf form, click over date picker or signature component
3. The components display correctly in a visible area.
3. Zoom out and click components again
4. The date picker does not appear in a visible area. 

## Expected behavior

Display date picker or signature widget in a visible area.

## Observed behavior

The date picker or signature component does not appear in a visible area when the form has a different zoom value than 100% (zoom in or zoom out).

## Example

https://jsfiddle.net/jsscatularo/0nfprxk9/8/

**Comment by wag110894** [comment]
@sebastianhaberey Thank you for reaching out as well as providing a JSfiddle for us to replicate this issue. We have created a ticket and have added this to our backlog. We will let you know once this issue has been resolved. For reference, the ticket number is PDF-74.

**Comment by sebastianscatularo** [comment]
Hi @wag110894 do you have an update on this?

**Comment by wag110894** [comment]
@sebastianscatularo,

The work on it this is completed, but has not been tested. We will let you know once testing has been completed.

Thank you for your patience.

**Comment by sebastianscatularo** [comment]
Hi @wag110894, do you have an update on this?

**Comment by wag110894** [comment]
@sebastianscatularo we will we working on a new PDF build soon. We will let you know once this issue has been resolved. 

Thank you for your patience.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
