### ISSUE TITLE
select dropdown list , the effect that switch value to label is not friendly.

### ISSUE THREAD

**Issue by lizakk** [formio/formio.js#2867]
I have a datagrid and put several select components in it . When loading data, all the select component display key value first then later changed to label value. We used the url data source. 
Whether there has a workround for this problem? 

![display key value](https://user-images.githubusercontent.com/4607261/83509193-a62efd80-a4fd-11ea-9b64-da1db1a1c0ad.jpg)
![display label value](https://user-images.githubusercontent.com/4607261/83509208-aaf3b180-a4fd-11ea-951d-f9b0f086f5e9.png)

**Comment by wag110894** [comment]
Hello @lizakk, 

Could you provide a JSFiddle of the issue so that we can replicate on our side? Also, what version of formio.js are you running?

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
