### ISSUE TITLE
[BUG] Conditional Mandatory Field Logic is not Working

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2877]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: Latest
- Frontend framework: javascript
- Browser: all
- Browser version:

## Steps to Reproduce
1. Create a new select field, label it 'Make Gender Mandatory'. API Property name is `myObject.genderMandatory`.
2. Create a second field, add logic to make this field mandatory if specified value is selected in the above field. API property name is `myObject2.genderId`.
3. Select Yes from the first field.

## Expected behavior
If we select Yes from 'Make Gender Mandatory' select box then the Gender field should become mandatory.
## Observed behavior
The field is not becoming mandatory. If I remove object notation for API property then it works but not if I use property API as `myObject.genderMandatory` or `myObject2.genderId`.
## Example
A live example (via [JSFiddle](https://jsfiddle.net/trsy8Lje/)) demonstrating this issue.

Code is below as well.

```js

Formio.createForm(document.getElementById('formio'), 
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Make Gender Mandatory",
            "widget": "choicesjs",
            "tableView": true,
            "data": {
                "values": [
                    {
                        "label": "Yes",
                        "value": "1"
                    },
                    {
                        "label": "No",
                        "value": "2"
                    }
                ]
            },
            "selectThreshold": 0.3,
            "key": "myObject.genderMandatory",
            "type": "select",
            "indexeddb": {
                "filter": {}
            },
            "input": true
        },
        {
            "label": "Gender",
            "widget": "choicesjs",
            "tableView": true,
            "data": {
                "values": [
                    {
                        "label": "Male",
                        "value": "male"
                    },
                    {
                        "label": "Female",
                        "value": "female"
                    }
                ]
            },
            "selectThreshold": 0.3,
            "key": "myObject2.genderId",
            "logic": [
                {
                    "name": "GenderIdLogic",
                    "trigger": {
                        "type": "simple",
                        "simple": {
                            "show": true,
                            "when": "myObject.genderMandatory",
                            "eq": "1"
                        }
                    },
                    "actions": [
                        {
                            "name": "GenderIdActionOn1",
                            "type": "property",
                            "property": {
                                "label": "Required",
                                "value": "validate.required",
                                "type": "boolean"
                            },
                            "state": true
                        }
                    ]
                }
            ],
            "type": "select",
            "indexeddb": {
                "filter": {}
            },
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
},  {
    templates: {
      wizard: {
        form: `
          <div style="position: relative;">
            <div class="wizard-page" ref="{{ctx.wizardKey}}">
              {{ctx.components}}
            </div>
            {{ ctx.wizardNav }}
          </div>
        `,
      },
    },
  }
).then((form) => {
  
});
```

**Comment by wag110894** [comment]
@learner291 Thank you for reaching out.

When using the Field Logic, you will not be able to set up the Keys using  myObject.genderMandatory.

**Comment by learner291** [comment]
Thank you @wag110894 for your response.

Is there a work around or any other way to set up a field mandatory based on another field's value?

**Comment by randallknutson** [comment]
When you use a dot in the property name it will assign the value inside an object and can mess up some of the logic like in this case.

Instead what you can do is place the field within a container, instead of using a dot, which is the other way of creating an object. This should then work with field logic correctly.

**Comment by travist** [comment]
I believe we just pushed up a fix for this issue this morning.  It includes this PR https://github.com/formio/formio.js/pull/2887

**Comment by learner291** [comment]
Downloaded the latest version (v4.10.0-rc.10) and the entity.FieldName notation works as expected, thank you.
