### ISSUE TITLE
Cannot read property 'then' of null at Form.js:292 [BUG] 

### ISSUE THREAD

**Issue by robertaird** [formio/formio.js#2878]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.10.0-rc.7
- Frontend framework: React
- Browser: n/a
- Browser version: n/a

## Steps to Reproduce
1. Create form with multiple subforms
    1. Subforms are conditionally toggled so only one is visible and in use at a time
    1. Some subforms should contain conditional components (and may also contain additional subforms)
1. Fill out form, trigger a subform with conditional components to show
1. Check that subform's conditional components will show
1. Trigger a different subform to show
1. Fill out subform
1. Trigger original subform to show
1. Check that subform's conditional components will show 

## Expected behavior
Form continues to function

## Observed behavior
An error is thrown, conditional components stop working in certain subforms

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
Uncaught (in promise) TypeError: Cannot read property 'then' of null
    at Form.js:292
```
It looks like that originates in the attach function here:
https://github.com/formio/formio.js/blob/master/src/components/form/Form.js#L219

I made a change locally to the `destroy` function in the Form component that 'seemed' to resolve the issue, but I don't think the approach is correct on it's own:
```
-this.subFormReady = null;
+this.subFormReady = NativePromise.reject(null);
```
See https://github.com/formio/formio.js/blob/master/src/components/form/Form.js#L260

There are a few places where the code checks for whether `subFormReady` is truthy, so alternatively maybe `attach` could be modified to check whether `subFormReady` is null, and if so either skips the return or calls `createSubForm()` before proceeding. I was looking to submit a pull request, but I'm unsure of the overall call flow, and I'm unfortunately a bit short on time to fully debug it. 

The issue is not present in 4.9.26, so I've rolled back to that.

**Comment by randallknutson** [comment]
Thanks for the report. We should look into getting this fixed. Would it work if we changed out "subFormReady" on this line for "ready"? Ready will either return subFormReady or a Promise.resolve();

https://github.com/formio/formio.js/blob/master/src/components/form/Form.js#L220

**Comment by wag110894** [comment]
@robertaird 

For reference, the ticket number is FJS-987.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
