### ISSUE TITLE
In old version of formio.js in that getAllComponents() method available. But in newer version of formio.js it not available

### ISSUE THREAD

**Issue by sand-bh** [formio/formio.js#2881]
I used old version of formio.js in that getAllComponents() method available. i used that method to get all components in the form. I upgrade formio.js to newer version, but in newer version getAllComponents() method not available. Is there another method to get all components of the form

**Comment by airarrazaval** [comment]
Using the Webform / Wizard instance you can access both the schema components and the components instances.

Example:

```js
Formio.createForm(document.getElementById('formio'), form).then((formio) => {
  // Components Schema
  console.log(formio.form.components);

  // Components Instances
  console.log(formio.getComponents();
});
```

If you are trying to access the form components through a component custom script (default / calculated value, validation, etc) remember the following:

The following variables are available in all scripts.

|Variable | Description |
|-----------|------------------|
| **form** | The complete form JSON object |
| **submissions** | The complete submission object.|
|**data** | The complete submission data object. |
| **row** | Contextual `row` data, used within DataGrid, EditGrid, and Container components |
| **component** | The current component JSON |
| **instance** | The current component instance. |
| **moment** | The [moment.js](https://momentjs.com/docs/) library for date manipulation. |
| **_** | An instance of [Lodash](https://lodash.com/docs/).|
| **utils** | An instance of the [FormioUtils](http://formio.github.io/formio.js/docs/identifiers.html#utils) object. |
| **util** | An alias for **utils**. |

In this case you can use the following depending on what you want to achieve.

---

### Get Form Components (Schema)

```js
const components = form.components;
```

---

### Get Form Components (Instance)

```js
const components = instance.root.getComponents();
```

---

### Nested Component Components (Schema)

```js
const components = component.components;
```

---

### Nested Component Components (Instance)

```js
const components = instance.getComponents();
```

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
