### ISSUE TITLE
How can i add id and onChange function for each input (text, checkbox etc..)?

### ISSUE THREAD

**Issue by cristo1985** [formio/formio.js#2890]
Hi,
i've built this using fantastic formio.js plugin!

http://jsfiddle.net/travistidwell/v38du9y1/

But my questions is as I already mentioned in the title.

Sorry for my bad english.

I need this help early.

Thanks
Cristian

**Comment by travist** [comment]
This is already done using the event emitter on each component. You just need to listen for the change event.

```js
form.on('change', function(event) {
  // Called for every component.
  console.log(event);
});
```

**Comment by cristo1985** [comment]
Ok but...if I wanna associate with my own id for each component how can I do that? 
For example:

` { "label": "NC chiusa positivamente",
                               **"id": "myownid",**
                                "tableView": false,
                                "key": "ncChiusaPositivamente",
                                "type": "checkbox",
                                "input": true,
                                "defaultValue": false

}`
Thanks

**Comment by travist** [comment]
What is the purpose of adding your own ID? You can just set this on the component JSON passed to the event.

```js
form.on('change', function(event) {
  // Called for every component.
  console.log(event);
  event.component.id = 'myownid';
});
```

**Comment by cristo1985** [comment]
> What is the purpose of adding your own ID? You can just set this on the component JSON passed to the event.
> 
> ```js
> form.on('change', function(event) {
>   // Called for every component.
>   console.log(event);
>   event.component.id = 'myownid';
> });
> ```

Ah ok so I just put id as indicated by you. I try thanks :)

**Comment by cristo1985** [comment]
Hi @travist , i've also tried to make simple page with this code:

`<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title> 

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
<script src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>

</head>

<body>
  <div id="formio"></div>
  <script type="text/javascript">
  	
  	Formio.icons = 'fontawesome';
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example').then((form) => {

  // Default the submission.
  form.submission = {
    data: {
      firstName: 'Joe',
      lastName: 'Smith'
    }
  };

  form.on('change', function(event) {
   
  console.log(event.component.key);
 
   
});
 

});

  </script>
</body>
</html>`

But give me an error as:
test.html:35 Uncaught TypeError: Cannot read property 'key' of undefined
    at n.<anonymous> (tets.html:35)
    at n.y.emit (formio.full.min.js:27)
    at n.r.emit (formio.full.min.js:20)
    at p.value (formio.full.min.js:27)
    at p.value (formio.full.min.js:14)
    at formio.full.min.js:14
    at h (formio.full.min.js:10)
    at g (formio.full.min.js:10)
    at v (formio.full.min.js:10)

Thanks for any help :) 
Cristian
