### ISSUE TITLE
[Feature] Import/Export XML Forms Data Format (XFDF)

### ISSUE THREAD

**Issue by nichtich** [formio/formio.js#2893]
It should be possible to convert between XML Forms Data Format (XFDF) and [Form JSON Schema](https://github.com/formio/formio.js/wiki/Form-JSON-Schema). This may also be implemented as independent application but integration into form.io would be best for useability.

**Comment by randallknutson** [comment]
This is not something we have a lot of familiarity with but are definitely open to. Is this something you could help us implement?

**Comment by nichtich** [comment]
We have some PDF forms (or try e.g. https://www.jotform.com/ to create PDF forms), I'll try to extract XFDF and convert to form.io JSON

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
