### ISSUE TITLE
[BUG] accessibility

### ISSUE THREAD

**Issue by almogn55** [formio/formio.js#2903]
There is a problem with the forms accessibility affecting users with disabilities that uses Screen Readers programs.
Users can't know the input name.

The <label> need to have property of "for" that contains the "id" of the input.

For example:
<label for="myInput">Name</label>
<input id="myInput" />

https://www.w3.org/TR/WCAG20/
https://www.w3.org/WAI/tutorials/forms/labels/

**Comment by randallknutson** [comment]
We may need some more specifics about this issue. We do add a "for" on labels linked to the "id" on inputs for all of our components. This can be overridden by templates though and we have many different templates like bootstrap, semantic and material. Can you tell us which template you are using, which component isn't working and what the html actually looks like that needs to be fixed?

**Comment by almogn55** [comment]
for example look in the demo:
https://formio.github.io/formio.js/

Look at the image attached:
https://i.imgur.com/nxU72ob.png

**Comment by VikkiAlenn** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
