### ISSUE TITLE
[BUG] set dynamic content to  HTML component based on Text area value 

### ISSUE THREAD

**Issue by viswateja1992** [formio/formio.js#2904]
Hi  

I have text area where I will enter data or html code and it needs to be set to content of HTML component.

Basically Html component will preview the data entered in Text area 

![image](https://user-images.githubusercontent.com/9268673/84145629-dd5e5b00-aa77-11ea-8b33-0d3e3fdb3cff.png)

I tried setting calculated value of html component but its not working 

![image](https://user-images.githubusercontent.com/9268673/84145861-4940c380-aa78-11ea-89ec-e463e1ed38ce.png)

**Comment by wag110894** [comment]
Hello @viswateja1992,

Here is an example of how you can accomplish this: https://evzowcsidcifltd.form.io/formiojsissues2904

I hope that this helps.

Thank you.

**Comment by viswateja1992** [comment]
It's working . Thank you
