### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AndreyOsipkov** [formio/formio.js#2905]
Hello! I looked for errors, they were similar, but I did not find with such a case

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
    - Version: the last
- Formio.js version: the last
- Browser: Browser: Chrome
- Browser version:  Google Chrome 81.0.4044.138

## Steps to Reproduce
1. add to the form Radio Component
2. on the data tab add the following values
label: value
label1: value1
3. change the order

## Expected behavior
label1: value1
label: value
## Observed behavior
label1: label1
label: label

## Example
[2020-06-10 09:32:50.mp4.zip](https://github.com/formio/formio.js/files/4756708/2020-06-10.09.32.50.mp4.zip)

**Comment by wag110894** [comment]
@AndreyOsipkov 

Thank you for your patience, this issue is resolved in the 4.10.0 build of formio.js.
