### ISSUE TITLE
Form.io angular Component tab modal edit

### ISSUE THREAD

**Issue by gape16** [formio/formio.js#2912]
Hi,
I use formio angular (2) and i just need to define in option.ts file, the position of a component. FOr example, in textfield, the protected field is in data tab but in need this in display tab...
How can i do that ?

Thanks !!! :)

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. Please re-open if it is still relevant. Thank you for your contribution!
