### ISSUE TITLE
[BUG] Focus on checkbox component

### ISSUE THREAD

**Issue by Narsciz** [formio/formio.js#2921]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.10.0
- Frontend framework: Angularjs
- Browser: Chrome
- Browser version: Version 83.0.4103.97 (Build officiel) (64 bits)

## Steps to Reproduce
1. Display a form with a checkbox and a textfield
2. suscribe to the focus event of the form, bind it with a console.log function

## Expected behavior
When focusing the checkbox or the textfield, the console log should appear in the console

## Observed behavior
The checkbox is not firing the focus event

## Example
https://jsfiddle.net/mt18365L/5/

**Comment by randallknutson** [comment]
I ran the JS Fiddle you provided and I'm seeing the event get triggered. Can you help explain what is the issue?

<img width="1307" alt="VanillaJS_Form_io_Renderer_-_JSFiddle_-_Code_Playground" src="https://user-images.githubusercontent.com/246735/84515667-63ee8480-ac92-11ea-9a41-a5e365de6db1.png">

**Comment by Narsciz** [comment]
Hi randall thanks for your time,

The event is triggered when you focus the textfield, but not when you focus the checkbox.

**Comment by Narsciz** [comment]
I have added the textfield only to show the correct behavior and to highlight that it doesn't work with the checkbox, like i said in the observed behavior, it's the checkbox the problem

**Comment by cmcortez** [comment]
Appreciate you bringing this t our attention we have placed this issue on dev ticket **FJS-1010 Github Focus on Checkbox does not fire Console log message**. Once the fix has been resolved and deployed we will update this comment string.

**Comment by Narsciz** [comment]
Thx, by the way, after further investigations, this bug also occured with radio and selectboxes components

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
