### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pronaykanti19** [formio/formio.js#2929]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: Current
- Frontend framework: JS
- Browser: Chrome
- Browser version:83.0.4103.97 

## Steps to Reproduce
1. Putting AJAX call in Custom Default Value
2. 
3. 

## Expected behavior
Expecting return after onload of the page. Expecting that I can put any javascript in the Custom and Calculated default value

## Observed behavior
AJAX Call not going through. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by gape16** [comment]
Hi,

You can just put that in your calculated value filed : 
let xhr = new XMLHttpRequest();
xhr.open('GET', 'http://jsonplaceholder.typicode.com/posts/1');
xhr.responseType = "json";
xhr.addEventListener("load", function () {
	instance.setValue(xhr.response.title);
});
xhr.send();

**Comment by pronaykanti19** [comment]
Thanks a ton!!
