### ISSUE TITLE
How to scroll a form back to the top of the page when the "next" button/link is clicked?

### ISSUE THREAD

**Issue by AudreyCb** [formio/formio.js#2931]
Hi ! 
We would like to scroll a form back to the top of the page when the "next" button/link is clicked? Is there an option for that ?

Thanks for the reply,

**Comment by airarrazaval** [comment]
In your application you could listen to the `nextPage` and `prevPage` events and programatically scroll to top.

```js
Formio.createForm(document.getElementById('formio'), form).then((formio) => {
  formio.on('prevPage', () => window.scrollTo(0,0));
  formio.on('nextPage', () => window.scrollTo(0,0));
});
```

Here is a working example: https://jsfiddle.net/airarrazaval/8rmwnvkq/
