### ISSUE TITLE
[BUG] Datagrid can't add component inside after changed `type`

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#2936]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.10.0-rc.6
- Frontend framework: none
- Browser: Chrome
- Browser version: 83.0.4103.97 (Offical Build) (64it)

## Steps to Reproduce
1. I am try to create new datagrid, so i copy Datagrid, then rename to MyDatagrid, like beblow

2. **Copy:** src/templates/bootstrap/datagrid/* --> src/templates/bootstrap/myDatagrid/*
**Copy:** src/templates/datagrid/* --> src/templates/datagrid/*

src/components/MyDatagrid/Datagrid.js
```diff
return NestedArrayComponent.schema({
      label: 'Data Grid',
      key: 'datagrid',
-      type: 'datagrid',
+      type: 'myDatagrid',
      clearOnHide: true,
      input: true,
      tree: true,
      components: []
    }, ...extend);
  }
// .....
  constructor(...args) {
    super(...args);
-    this.type = 'datagrid';
+    this.type = 'myDatagrid';
  }
```

src/components/builder.js
```diff
-import DatagridForm from './datagrid/Datagrid.form';
+import MyDatagridForm from './myDatagrid/Datagrid.form';
// .....
-Components.datagrid.editForm = DatagridForm;
+Components.myDatagrid.editForm = MyDatagridForm;
```

src/components/index.js
```diff
-import DatagridComponent from './datagrid/Datagrid';
+import MyDatagridComponent from './myDatagrid/Datagrid';
// .....
-  datagrid: DataGridComponent,
+ myDatagrid: MyDataGridComponent,
```

src/templates/bootstrap/index.js
```diff
-import datagrid from './datagrid';
+import myDatagrid from './myDatagrid';
// .....
-  datagrid,
+ myDatagrid,
```

2. Build & Run
3. Drop down MyDataGrid component
4. Drop down Textbox component inside MyDataGrid

## Expected behavior
Textbox can drop into MyDataGrid

## Observed behavior
Textbox can't drop into MyDataGrid

## Other
I think this issue is same with #2173,
And i have try copy Panel --> MyPanel, that is no problem, but why only datagrid is not work

![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_2936.gif?raw=true)

**Comment by randallknutson** [comment]
You may want to check out how to extend the form builder and renderer by checking out https://github.com/formio/formio.js/wiki/Modules

**Comment by bleungAtGTI** [comment]
But #2173 is using "Right" way to implement, but it still not work

**Comment by randallknutson** [comment]
Datagrid has an attach override in the webformbuilder.js file here https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L200-L211

This can also be done by adding similar code to the regular attach method but wrap in this.builderMode check.

**Comment by bleungAtGTI** [comment]
Cause:
`Component.js` will call attachXXX by your type, e.g: attachDatagrid
If you change/create a `type`, it haven't call original attachXXX

https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L1024

Walkaround:
After add a new type, check all `xxxBuilder.js` any `attachXXX` method,
If yes, you should call original `attachXXX`

e.g: `WebformBuilder.js`
```javascript
    this.options.hooks.attachDatagrid = (element, component) => {
        // ..............
    };
    // call original atachXXX
    this.options.hooks.attachMyDatagrid = (element, component) => {
      this.options.hooks.attachDatagrid(element, component);
    };
```


Thank @randallknutson  :)
