### ISSUE TITLE
[Issue]  Can we get form back from JSON Schema in form builder So we can start where we left ?? 

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio.js#2949]

**Comment by randallknutson** [comment]
Yes. The form builder has a "form" property on it where you can pull the form definition. You can also set it to reload the form definition.

**Comment by bilogic** [comment]
```JAVASCRIPT
builder.instance.form = jsonObject;
```

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
