### ISSUE TITLE
Tap on files list not downloading the file in cordova app

### ISSUE THREAD

**Issue by raghavendrav6** [formio/formio.js#2951]
In a form we have a list of files. In browser when we tap on it it's downloading the file.
But in cordova app when we tap on the file name nothing happens. 

So, for us to able to download the file do we need to do something? or Is it even supported?

**Comment by randallknutson** [comment]
We don't have any reason to think this shouldn't work. Is there an error happening within the app or something?

**Comment by airarrazaval** [comment]
This seems to be a misconfiguration on the cordova side.  Make sure to enable the file / media and permissions plugin.  For Android, for example, make sure to have the following in your build script:

```sh
cd /path/to/cordova/dir

cordova plugin add cordova-plugin-android-permissions && \
cordova plugin add cordova-plugin-file --force && \
cordova plugin add cordova-plugin-media && \
cordova plugin add cordova-plugin-camera
```

* **cordova-plugin-android-permissions**:
Enables Android permission request

* **cordova-plugin-file**:
Enables the file plugin allowing you to access or creating files (use `--force` to make sure no other option disables it)

* **cordova-plugin-media**:
Enables the media plugin allowing you to access photo gallery (saving / reading media files)

* **cordova-plugin-camera**:
Enables the camera plugin allowing you to use your phone camera to take pictures with file component.

You may also want to use the `cordova-plugin-whitelist` if you wish to control the URLs your app is allowed to access (security measure).

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
