### ISSUE TITLE
Builder Question: How do I skip the modal popup for components

### ISSUE THREAD

**Issue by besmiralia** [formio/formio.js#2969]
I have created some predefined textfield components (ex. First Name, Last Name, etc). I would like to drag them on the form without needing to hit Save on the modal popup. How can I achieve that? Is there a property I can pass to these components to avoid the modal when dropped on the form?
Thank you

**Comment by jhen1422** [comment]
@besmiralia 
On our 'Next' portal, you can pass options to the 'Form Module' settings found in the Custom CSS/JS within your project settings

{
options: {
builder: {
noNewEdit: true
}
}
}

**Comment by besmiralia** [comment]
Thank your @jhen1422for your answer.
Is there any way to make this option only for predefined components and not every component?
Referring to the custom builder example https://formio.github.io/formio.js/app/examples/custombuilder.html, I would like this option to be available for components under the custom group, and keep regular (modal popup) behavior for other components.

**Comment by randallknutson** [comment]
I don't believe there is a way to have certain components that don't open a modal. We did have this in older versions where we had one or two components that didn't open modals but those got more complex and we ended up adding the modal back.

**Comment by besmiralia** [comment]
Hi @randallknutson 
Thank you for your feedback. I played around and I think I was able to achieve what I asked for. I also submitted a PR ( #2977 ) in case you think this is something valuable for other people.
