### ISSUE TITLE
How I can get field‘s  value and setting value by js

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#2976]
now,i can get select by ``` $('select[name="data[com]"]').val(); ```

But,It is not common.

Does it have event options similar to buttons？

**Comment by travist** [comment]
You need to use the Formio SDK to get a components value. If you want to do this via global script, then you will need to first get the Form instance. You can find the form instance by referencing the ```Formio.forms``` object like so.

```js
const myform = Object.values(Formio.forms)[0];
```

This just assumes you have one form on the page...  You can then do the following to get the value of a component.

```js
myform.getComponent('com').getValue();
```

**Comment by snaik09** [comment]
Hi,
where(in which property) do I need to set the value myform.getComponent('com').getValue();
I want to read a form textfield data on submit and display that data on submit.
Any help will be appreciated.

Thank you
