### ISSUE TITLE
[BUG] Signature component has overlapping asterisks when it is rendered as required field in read mode

### ISSUE THREAD

**Issue by motss** [formio/formio.js#2980]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.10.4
- Frontend framework: react@16.13.1
- Browsers: Chrome 85, FF 79

## Steps to Reproduce
1. Create a Signature component in read-only form
2. Make the Signature component a required field
3. See the rendered component to have distorted UI

## Expected behavior

The following screenshot should the expected output when signature component is set to be required:

![Screen Shot 2020-06-22 at 16 28 07](https://user-images.githubusercontent.com/10607759/85266397-60cf7180-b4a6-11ea-917b-fe62f40a5420.png)

When a signature component is a required field, asterisk should render in the canvas at the top right corner as well as one right after the signature label.

## Observed behavior

The following screenshot shows how the current render with formio.js:

![alpha crm ntuchealth cloud_forms_88f7ba67-1bb7-4170-a8a1-754a4babeb75_clientId=6dc2a421-d4de-e611-8189-3863bb2e6bb0 planId=1e2b99c3-96ae-4635-ac85-c8afe2fb5087 source=plan](https://user-images.githubusercontent.com/10607759/85266414-675de900-b4a6-11ea-9db2-43d0d6179b5e.png)

There are 2 signature components: Not required field (top) and Required field but overlapping asterisks and asterisk is not showing right after the sign label (bottom)

## Demo

Overlapping symbols appear only in read-only form.

https://jsfiddle.net/3e8z9ucL/

**Comment by wag110894** [comment]
Hello @motss,

Thank you for reaching out!  We are not able to replicate this issue on our side. Can you provide a JSFiddle of this issue occurring?

**Comment by airarrazaval** [comment]
@motss It seems its an issue on your end.  Maybe a css style conflicting with form.io styles.  Mekae sure to import in the following order:

* Framework (bootstrap 3 / bootstrap 4 / semantic)
* Load Formio styles
* Load application styles

Here is an example of three different renderings using bootstrap 4.

https://jsfiddle.net/airarrazaval/2b9hs08f/


Finally, make sure you have no custom css defined in the component which may cause conflicts.

**Comment by motss** [comment]
@wag110894 @airarrazaval I've tried to find out why it cannot be reproduced in your example. I managed to reproduce it with `readOnly: true` and it does show what I presented in the screenshot above.

So the real issue was caused by when the form is in read mode.

Updated demo with `readOnly: true`: https://jsfiddle.net/3e8z9ucL/

**Comment by airarrazaval** [comment]
I am seeing that the icon is rendered under the `form-control-feedback` element, thus implying that a validation is triggering the render of the icon (which shouldn't happen).  You can use the following CSS hack to remove the asterisk and the refresh button (which shouldn't be there either in read-only mode).

```css
.formio-read-only .formio-component-signature .signature-pad-refresh,
.formio-read-only .formio-component-signature .form-control-feedback.field-required-inline{
  display: none;
}
```

Also, I noticed another bug.  When you are editing the form (not in read-only) if you resize the browser window, the signature canvas gets recalculated, thus changing the component value.  Lets say the image is currently 500x500px.  If you resize the browser window and you scale up or down the signature component, the canvas will be recalulated not scaled.  If by resizing your browser window the signature canvas was resized form 500x500px to 250x500px, then the component's value will change:

**Original Signature**

![image](https://user-images.githubusercontent.com/9391489/86258616-02328380-bb89-11ea-91d7-a1f4b670ab46.png)

**After Resizing**
![image](https://user-images.githubusercontent.com/9391489/86258714-20987f00-bb89-11ea-90dd-7dc68b41ead4.png)


Now, if you are in read-only mode, the component's value is not changed, but the image is not stretched accordingly when resizing the browser window:

**Original Signature (read-only)**

![image](https://user-images.githubusercontent.com/9391489/86258981-74a36380-bb89-11ea-934f-92c6b79f3434.png)

**After Resizing (read-only)**

![image](https://user-images.githubusercontent.com/9391489/86259087-9270c880-bb89-11ea-801d-505d2a245be9.png)

Image doesn't change, but this is how it looks:

![image](https://user-images.githubusercontent.com/9391489/86259195-b7fdd200-bb89-11ea-8b72-8e895ee46412.png)

**Comment by jhen1422** [comment]
@airarrazaval 
Can you try version 4.12.0rc19 of formio.js to see if this is resolved?
