### ISSUE TITLE
[BUG] reCaptcha does not load on Wizard Form

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#2986]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: Application: 7.0.25, Renderer: 4.10.3
- Formio.js version:  Renderer: 4.10.3(built-in Pro Viewer)
- Frontend framework: n/a
- Browser: Chrome
- Browser version: 81

## Steps to Reproduce
1. Navigate to a standard form with recaptcha:
https://pro.formview.io/#/stvhlgwezdsousj/test4?header=1&reset=1
2. Navigate to a wizard form with recaptcha
https://pro.formview.io/#/stvhlgwezdsousj/wizard1?header=1&reset=1
3. Check network tab and bottom of the screen to see if reCaptcha is loaded

## Expected behavior
On both form, recaptcha logo should show up at the bottom right.
Network tab should show recaptcha_en.js being loaded
## Observed behavior
Standard form: logo shows up and recaptcha is loaded
Wizard form: no logo, no sign of script being loaded. When I check the html code, the recaptcha component is present.
## Example
Please check the links above, both forms are public.

**Comment by wag110894** [comment]
Thanks for reaching out @phucduong86,

We are able to replicate this issue on our side. Thank you for providing examples. We have created a ticket (FJS-1029) and have added this to our backlog. We welcome a PR or have a process to expedite if you are interested. 

Please contact support@form.io if you are interested in expediting.
We will let you know once this issue has been resolved.

Thank you.

**Comment by phucduong86** [comment]
This issue has been resolved. Thank you.
