### ISSUE TITLE
Wizard Steps are not appearing correctly in embed form

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#2998]
I have created a form on your portal. It is a wizard form. When I view the form using the Use button on your portal, it displays the wizards steps like a time line, as shown in the figure below.

![image](https://user-images.githubusercontent.com/40409548/85923181-deb5c300-b880-11ea-9047-865c7ac54bdb.png)

Similarly, if I use formview URL to view the form in a new browser window, it still shows the wizard steps correctly like a time line.

![image](https://user-images.githubusercontent.com/40409548/85923238-6d2a4480-b881-11ea-9b86-1f86c8593a7f.png)

However, if I embed this form the wizard steps are not shown in a time line format. What changes do I need to make wizard steps appear like a time line? The [Fiddle Click Here](https://jsfiddle.net/1hprsLt9/) shows the issue, as well as the screenshot below.

![image](https://user-images.githubusercontent.com/40409548/85923264-bc707500-b881-11ea-8618-856c5ff0baa3.png)

**Comment by wag110894** [comment]
Hello @learner291, we have made a change to our Wizard layouts to change it to the way you see in the JSfiddle when using Formio.js. So this is not a bug, but a change to the Wizard layout. We have gotten feedback from this change and are moving back to the old Wizard option in 5x of our formio.js. 

I hope this helps.

Thank you.

**Comment by learner291** [comment]
Hi @wag110894 , thank you for your reply.

Is it possible to keep both formats and we can choose which one to use?

**Comment by randallknutson** [comment]
That's what is coming in 5.x

**Comment by learner291** [comment]
OK thanks for the confirmation.
