### ISSUE TITLE
Custom not editable component

### ISSUE THREAD

**Issue by mtpersonalfile** [formio/formio.js#2999]
Hi, I'm using formio builder for quite some time and we as a company are now upgrading to the latest formio and I'm now re-creating some custom blocks that were created for use with ngFormBuilder in new formio.js 4 using Contrib library. I like this approach, but this one example of CheckMatrix doesn't explain everything. If anyone can save me some time of research and endless trying and answer:

1. Can I create a custom component that is not editable or at least to hide complete tabs like you can fields?
2. Can I define the JSON model of my custom component or what is the minimum that I must inherit from base class?

In ngFormBuilder I used to have a component that can only be present or not when you create a form. Additional logic would prevent you to have multiple and in some business process later that block if exists and based on other inputs would be replaced with other form elements. We cannot just use conditional because another external service will dictate what is needed instead. 
That is why it can't be editable and shouldn't contain all those additional attributes, so it should be easy to parse the whole form JSON and identify that block and replace it with something else. 

I'm trying to keep the same business logic, for now. 
If anyone has a suggestion or a different approach, I would be happy to hear.

Thank you

**Comment by wag110894** [comment]
Hello @mtpersonalfile, are you still experiencing issues?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
