### ISSUE TITLE
[QUESTION] how to add select components resource

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#3004]
In the select component,how can i to create resource and setting this option.

**Comment by wag110894** [comment]
The Select component when the Data Source Type is set to Resource uses data from an existing form that adds the values. Here is a quick video on how to accomplish using the Select Resource: https://share.getcloudapp.com/jkuQXnlZ

I hope that this helps.

**Comment by QThans** [comment]
Thanks.
And can you teach me how to setting the file-component's upload url?

**Comment by QThans** [comment]
@wag110894 
and how can i select resource‘s label and when i save i can save the resource’s value?

**Comment by wag110894** [comment]
@QThans Apologies on the delay, could you clarify what you mean by your question?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
