### ISSUE TITLE
how can i to hide options

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#3005]
like this:table view

How can i hide all components's table view option?

**Comment by cmcortez** [comment]
Within each component, you will have to uncheck the Table View Setting on the Display Tab of the component.

**Comment by rickcaudill** [comment]
I can help with this a bit... I was not able to find a way to do this for all components without doing each component (I might create a patch for this)...

Basically you want something like the following (javascript object here but you should get the gist):
  formBuilderOptions = {
    "noDefaultSubmitButton": true,
    "builder": {
      "premium": false,
      "basic": {
        "components": {
          "password": false,
        }
      },
      "advanced": {
        "components": {
          "file": true
        }
      },
      "layout": {
        "components": {}
      },
      "resources": {
        "title": "Resources",
        "weight": 10000,
        "groups": {},
      },
    },
    "editForm": {
      "textfield": [
        {
          "key": "display",
          "ignore": false,
          "components": [
            {
              "key": "modalEdit",
              "ignore": true,
              "value": false
            },
            {
              "key": "tableView",
              "hidden": true
            }
          ]
        },
        {
          "key": "api",
          "ignore": false,
          "components": [
            {
              "key": "tags",
              "ignore": true
            },
            {
              "key": "properties",
              "ignore": true
            },
            {
              "key": "key",
              "label": "Key/Name",
              "editForm": true
            },
          ]
        },
        {
          "key": "data",
          "ignore": false,
          "components": [
            {
              "key": "persistent",
              "ignore": true
            },
            {
              "key": "protected",
              "ignore": true
            },
            {
              "key": "dbIndex",
              "ignore": true
            },
            {
              "key": "case",
              "ignore": true
            },
            {
              "key": "encrypted",
              "ignore": true
            },
            {
              "key": "redrawOn",
              "ignore": true
            },
            {
              "key": "clearOnHide",
              "ignore": true
            },
            {
              "key": "calculateServer",
              "ignore": true
            },
            {
              "key": "allowCalculateOverride",
              "ignore": true
            },
            {
              "key": "customDefaultValuePanel",
              "ignore": true
            },
            {
              "key": "calculateValuePanel",
              "ignore": true
            }
          ]
        },
        {
          "key": "validation",
          "ignore": false,
          "components": [
            {
              "key": "unique",
              "ignore": true
            },
            {
              "key": "custom-validation-js",
              "ignore": true
            },
            {
              "key": "json-validation-json",
              "ignore": true
            },
            {
              "key": "validateOn",
              "ignore": true
            }
          ]
        },
        {
          "key": "layout",
          "ignore": false,
          "components": [
            {
              "key": "overlay",
              "ignore": true
            }
          ]
        },
        {
          "key": "conditional",
          "ignore": false,
          "components": [
            {
              "key": "customConditionalPanel",
              "ignore": true
            }
          ]
        }
      ],
    }
}

You can also override the editForrm with your own stuff...  I can find a link if you need it but I chose not to do that for my implementation.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
