### ISSUE TITLE
[BUG] DateTime component prevents selection on mobile device (form.io v3)

### ISSUE THREAD

**Issue by s08cz1** [formio/formio.js#3008]
## Environment
Please provide as many details as you can:

- Formio.js version: 3.29.17
- Frontend framework: none (pure js)
- Browser: Chrome (Android)
- Browser version: Chrome 83.0.4103.44 (Android 11)

## Steps to Reproduce
1. Create form with DateTime component
2. Open on a mobile device (not mobile view on desktop PC)
3. Select a date

## Expected behavior
Date/time is successfully populated

## Observed behavior
Validation error, value not populated

## Example
github repo with issue - [https://github.com/s08cz1/formio-broken-datepicker](https://github.com/s08cz1/formio-broken-datepicker)

Screenshot:
![image](https://user-images.githubusercontent.com/8421443/86361568-f7045400-bc6b-11ea-9313-9255554ef7db.png)

**Comment by jhen1422** [comment]
@s08cz1 This issue is resolved in the 4x version of formio.js. Is it possible for you to upgrade to this version?

**Comment by s08cz1** [comment]
Thanks @jhen1422, we are investigating upgrading to v4 but it may not be a quick process, minor version upgrade would be a much easier solution

**Comment by jhen1422** [comment]
@s08cz1 you may try using a 'Textfield' and setting the widget setting to 'Calendar' to see if that works on mobile.

Alternatively, feel free to contact support@form.io if you would like to report this issue and receive info on supporting a fix.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
