### ISSUE TITLE
[HELP]how to validate form and no submit 

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#3010]
Can i only validate form data,and not submit data.
My mean is active verification,not event

**Comment by randallknutson** [comment]
You can call form.checkData() to see if it is valid or not.

**Comment by QThans** [comment]
```
var submitForm = webForm.submitForm();
    submitForm.then(function(v){
    }).catch(function(e) {
    })

```
I have use this method to check form.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
