### ISSUE TITLE
[HELP-WANTED] Proper way to programmatically set fields value

### ISSUE THREAD

**Issue by PhilCliv** [formio/formio.js#3011]
Hi FormIO team!
I'm using formio.js and the browser "speach recognition" to fill the fields of my forms.  
What is the proper way to set dynamically the value of a specific field in my form?
I intensively searched in the doc but could not find the solution.

For now I use jquery to set the value of the HTML element 
_$(currentElement).val(value);_

And then set the submission value like this because formio.js does not recognise values set programmatically:
_form.submission.data['fieldName'] = value_

I tried this but with no effect.
_form.setContent(currentElement[0], value);_

Thank you!

**Comment by randallknutson** [comment]
You can do form.getComponent('componentKey').setValue('myvalue');

**Comment by PhilCliv** [comment]
Working perfect! Thanks

**Comment by MalkyTheKid** [comment]
Hi, sorry for opening this again but how exactly do you implement the above?

I have tried both 
 form.getComponent('brand').setValue('myvalue');
and
 Formio.getComponent('brand').setValue('myvalue');

but it does not change the value of my input

**Comment by travist** [comment]
```Formio.createForm()``` returns a promise. You must wait for that to resolve and then it hands you the form instance like this.

```js
Formio.createForm(document.getElementById('formio'), 'https://vopxbjfifjgomcz.form.io/ccparequest').then((form) => {
  form.getComponent('brand').setValue('thatvalue');
});
```

**Comment by sriram275** [comment]
Hi Travist,

Is it possible to get same form object inside custom default value script of a component?
Background of this - I wanted to update component1's value from component2's custom default value script based on some logic.

is there way to update like this?

Thanks,
Sriram

**Comment by DonAmit197** [comment]
Hi @travist,

Apologies to open this again.

Trying to **setValue** dynamically in the address component. It actually sets the value in the submission JSON, but it is not rendering in the UI. Is there any fix for this? 

The following code is a snippet for which I'm currently working, where I'm introducing "nextPage" and "prevPage" event to do the UI change, but this actually I don't want to do. Wondering is there any other workaround.

Any thoughts would be highly appreciated.
`` 
if(address.addressType === addressTypeValue ){
   fullAddress = `${(address.address1 ? address.address1 : "")}, ${(address.address2 ? address.address2 : "")}, ${(address.address3 ? address.address3 : "")}, ${(address.address4 ? address.address4 : "")} , ${(address.countryCode ? address.countryCode : "")}, ${(address.postCode ? address.postCode : "")}, `; 
               component.setValue(fullAddress);
              if(component.component.type==="address"){
                var addressComponent = component.element.querySelector(`input[type="text"]`);
                _FORM.on("nextPage",()=>{
                  if(component.element && addressComponent){
                   addressComponent.value = fullAddress;
                }
                })
               _FORM.on("prevPage",()=>{
                  if(component.element && addressComponent) ){
                  addressComponent.value = fullAddress;
                }
                })
               }
            }
``
