### ISSUE TITLE
Removing EditJson Component Hover Option

### ISSUE THREAD

**Issue by JRiggenbach** [formio/formio.js#3019]
I'm not having much luck with how to toggle the hover options, specifically the edit json option, for the components added to the form builder.  
![hoveroptions](https://user-images.githubusercontent.com/1473610/86933957-23efb580-c109-11ea-82e6-90a5f1e12ad2.png)

There appears to have been the idea of adding an "enableButtons" property to the form options, but I don't see that in the main branch

![webformbuilder](https://user-images.githubusercontent.com/1473610/86933751-e25f0a80-c108-11ea-81d6-b01959fe5f5c.png)

Any suggestions?  Thanks in advance.

**Comment by wag110894** [comment]
Hello @JRiggenbach 

We are not experiencing any issue with hovering over the options. Are you using our Production portal? If not, what version of formio.js are you running on?

**Comment by JRiggenbach** [comment]
@wag110894  My apologies, I'm not experiencing any issue with hovering over the options...I was curious if there was a way to remove any of them?  I've found the rest of the form builder to be highly configurable so I naturally assumed I'd be able to configure these options as well.

**Comment by randallknutson** [comment]
You can remove them by overriding the buildercomponent template at https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builderComponent/form.ejs

Here is information on how to override templates: https://github.com/formio/formio.js/wiki/Templates-API

**Comment by JRiggenbach** [comment]
@randallknutson Thanks for pointing me in the right direction. I'll give this a shot.
