### ISSUE TITLE
[HELP] Is it possible to login as another user?

### ISSUE THREAD

**Issue by przzz27** [formio/formio.js#3020]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.10.5
- Frontend framework: Javascript
- Browser: Google Chrome
- Browser version: Version 83.0.4103.116 (Official Build) (64-bit)

Currently i have 2 resources:

1. Managers

2. Employees

In my application each manager can have many Employees, each employee has one manager assigned to them. I was wondering if its possible that a manager can authenticate as one of its employees to see my application exactly as an employee and troubleshoot any problems they have from there.

I think i could manage to do that by saving their password somewhere else as plain text but i think that is insecure and maybe there is a better way to do it.

**Comment by cmcortez** [comment]
Please review the following documentation: https://help.form.io/userguide/roles-and-permissions/#roles-and-permissions

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
