### ISSUE TITLE
[HELP-WANTED Dynamically populate value on form after .createform

### ISSUE THREAD

**Issue by MalkyTheKid** [formio/formio.js#3021]
Hi,

How does one dynamically set the value of the form's elements once it's been embedded in the html?

I have tried both
form.getComponent('brand').setValue('myvalue');
and
Formio.getComponent('brand').setValue('myvalue');

I have also tried via jQuery:
var value = $('#form input[name=data[brand]]').val("Terrapass")

but it does not change the value of my input..

My implementation is below:

```
<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />
	                    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' />
	                    <link rel='stylesheet' href='https://unpkg.com/formiojs@latest/dist/formio.full.min.css' /> 
	                    
	                    <script src='https://unpkg.com/formiojs@latest/dist/formio.full.min.js'></script>
	                     
	                    <!--Reference the form now-->
	                   <div id='formio' class='css-1l98hjp' ></div>

       
<script>         
function loadFormio() { //below script MUST be on a window.onload event
            console.log('loadFormio() function!');
            Formio.icons = 'fontawesome';
            Formio.createForm(document.getElementById('formio'), 
           'https://vopxbjfifjgomcz.form.io/ccparequest?_ga=2.262094541.1190475087.1593702800-1158075197.1588294505');

           form.getComponent('brand').setValue('thatvalue');

          }; 
          
 window.onload = loadFormio();
<script>


	  		   <link rel='stylesheet' href='https://forms.justenergy.com/justenergy/ccpa/ccpa.css' />

```

**Comment by przzz27** [comment]
You were close, i left you a fiddle [here](https://jsfiddle.net/h39v7tu4/):
https://jsfiddle.net/h39v7tu4/

createForm returns a promise so your code should execute when the promise is complete.
Your code was executing earlier while the form has not been "rendered" yet

**Comment by MalkyTheKid** [comment]
Lovely, thank you

Will experiment for now and see if the above works with other controls as well (ie: select, date, etc.)

**Comment by MalkyTheKid** [comment]
Hi Josue,

Thanks for the great response.
I tried playing around as well with the Layout components, namely the "HTML_Element" and the "Content" components,
but it does not seem to have the same `.setValue()` function.

How do you change the `html` value for the "HTML_Element" component and how do you change the `content` value of the "Content" component  thru the same implementation above?

**Comment by MalkyTheKid** [comment]
Closing this and opened another issue https://github.com/formio/formio.js/issues/3043
