### ISSUE TITLE
DateTime popup does not provide value?

### ISSUE THREAD

**Issue by ssdhaliwal** [formio/formio.js#303]
Below configuration shows the datetime field and the popup works, but there is no way the value is being provided back to the form field - it stays empty.

`{
    type: 'datetime',
    key: 'dueDate',
    label: 'Due Date',
    placeholder: 'Enter Due Date?',
    input: true,
    tooltip: 'Enter date the item is <strong>due</strong>',
    description: 'Enter <strong>Due Date</strong>'
}`
  
Additional info:
1/ the popup will show the last selected value but the edit/input field stays null

**Comment by travist** [comment]
You are missing some things in the JSON that are needed. This should work for you.

```
{
      type: 'datetime', 
      key: 'dueDate', 
      label: 'Due Date', 
      placeholder: 'Enter Due Date',
      datepickerMode: 'day',
      enableDate: true,
      enableTime: true,
      format: 'yyyy-MM-dd hh:mm a"', 
      input: true, 
      tooltip: 'Enter date the item is <strong>due</strong>', 
      description: 'Enter <strong>Due Date</strong>'
    }
```

**Comment by ssdhaliwal** [comment]
Thank you - was looking at the example to get full JSON spec for form :)

**Comment by ssdhaliwal** [comment]
Thank you.
