### ISSUE TITLE
[BUG]the radio input is save component's id 

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#3032]
the radio input has save component's id .
and when i run setValue ,it's not work;
the id value is always change,how i can setting value?

**Comment by QThans** [comment]
when the Values only one,the data is error

**Comment by wag110894** [comment]
@QThans, can you provide a jsfiddle of this issue so that we can test and investigate? 

Thank you.

**Comment by QThans** [comment]
I have not using formio's submiit or  like
```
form.on('change', function(event){
  	console.log(event.data);
  });
```
I have submiting data with html's element form.Because i need to use other function.
Can you give me somthing good idea for this data formating?

**Comment by randallknutson** [comment]
The value in the submission of the radio should be key of the option selected. We don't ever set the id anywhere in the submission object so I'm not sure what is going on.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
