### ISSUE TITLE
[BUG] Form submits while file upload in progress

### ISSUE THREAD

**Issue by yioMtz** [formio/formio.js#3036]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:4.10.5
- Frontend framework:Javascript
- Browser:Mozilla Firefox
- Browser version:78.0.2(64-bit)

## Steps to Reproduce
1. Create a form with a file component with storage setup to URL
2. Upload a large file
3. Submit form while file is in the process of uploading.

## Expected behavior
Form should not be able to be submitted while uploading is still in progress
## Observed behavior
Form submits with error if the upload component is required or submits without storing the reference of the uploaded file since it was still uploading and did not received a reply from the storage service

**Comment by wag110894** [comment]
Hello @yioMtz,

Thank you for reaching out!

We are aware of this issue and have this item in our backlog to resolve. We are making the submit button disabled while you are uploading files. For reference, the ticket number is FJS-1054. We welcome a PR or have a process to expedite this issue if you are interested. 

Our developers estimate that it will take 4 hours to resolve this item. Please contact support@form.io if you are interested in expediting this issue.

We will let you know once this issue has been resolved.

**Comment by YioMtz31** [comment]
Hi @wag110894,

Any update on this?

Thank you

**Comment by wag110894** [comment]
Hello @YioMtz31,

This issue has been resolved in 4.12.1-rc.2. We do have a stable build which is 4.12.1. 

Closing this ticket.
