### ISSUE TITLE
[Question] What is the "components" section in a column component definition for?

### ISSUE THREAD

**Issue by Pathfinder9021** [formio/formio.js#3038]
I've just upgraded formio.js from v3.29.2 to v4.11.0 and noticed that recently created forms don't have "components" property in column component definition, there is only "columns" property. Does anyone know what the “components” is for? 

![image](https://user-images.githubusercontent.com/43930265/87389273-1fb31480-c5af-11ea-9514-c639244ddedb.png)

With that section defined, I have an issues with existed forms. If phone number is entered, is not requred and matches input mask, user is not able to pass form validation (checkData) of phone number component and gets the message that entered value doesn't match the phone number mask. This message returnes as an error of submitForm method.
```
instance,submit()
         .then(function(v){   })
         .catch(function(e) {  })
```
Submit method throws this error message and also phone input is not highlighted and doesn't have a validation message below it.

**Comment by randallknutson** [comment]
The column component should only have a columns property which contains the columns and components for that component. If the columns component set the components property in the past, this was a bug that would have been fixed. Components should not be on the top level but within the columns property.

**Comment by Pathfinder9021** [comment]
I see. Thank you for the answer
