### ISSUE TITLE
form.reset(); not setting to default values

### ISSUE THREAD

**Issue by ssdhaliwal** [formio/formio.js#304]
Per documentation; form.submission is used to set default values - this is provided and works on initial creation of the form.

After the form.reset() is executed; the form shows empty fields, not the values from prior form.submission setting.  Another call to form.submissions is required to reset the form fields?

Also after the form.reset(); if the form has been previously submitted; the alert is not cleared showing form has been submitted even after fields are reset.

**Comment by ssdhaliwal** [comment]
figured it out; defaultValue is in the JSON form spec; is there a page which describes the JSON form spec?  Wiki did not show it.

**Comment by francesco-gallo** [comment]
Is a "reset to default value" logic usable with select components? If so, how?

**Comment by dwgreen1** [comment]
@ssdhaliwal Can you tell me how you got your form to use default values again after form.reset()?
