### ISSUE TITLE
[HELP WANTED] changing parameters for Layout components on runtime

### ISSUE THREAD

**Issue by MalkyTheKid** [formio/formio.js#3043]
Hi,

I got a great answer here (https://github.com/formio/formio.js/issues/3021) as to how I can change my component's values on runtime. I tried it on layout components, namely the "HTML_Element" and the "Content" components,
but it does not seem to have the same .setValue() function.

How do you change the html value for the "HTML_Element" component and how do you change the content value of the "Content" component thru the same implementation above?

I tried the following from here (https://formio.github.io/formio.js/docs/class/src/formio.form.js~FormioForm.html#instance-member-element) but to no effect.
form.getComponent('brand').setElement('WORKS');
form.getComponent('brand').render('WORKS');
form.getComponent('brand').element('p>works');

**Comment by randallknutson** [comment]
HTML and Content both don't rerender by default for performance reasons. You can either manually call redraw() on them to force them to redraw or add the "Refresh on change" checkbox option to have it listen for changes and redraw.

**Comment by MalkyTheKid** [comment]
Hi Randall, 

Thanks for the response.

I did as you suggested and checked "Redraw on change" property of my "Content" component
However, I still can't seem to change the html content at runtime...

How do I properly implement this?
Please see below code:
```
<script>
                     function loadFormio() { //below script MUST be on a window.onload event
            console.log('loadFormio() function!');
            Formio.icons = 'fontawesome';
            Formio.createForm(document.getElementById('formio'), 
           'https://vopxbjfifjgomcz.form.io/formiodevjustenergycomccparequest?_ga=2.11912820.1766944344.1594131649-1158075197.1588294505')
                    .then(form =>{
						form.getComponent('brand').setValue('Just Energy');
						
						form.getComponent('contentBrand').setElement('<p>WORKS</p>');
//Also didn't work...						
//form.getComponent('contentBrand').setValue('<p>WORKS</p>');
//form.getComponent('contentBrand').render('<p>WORKS</p>');		
						
					}
                );  
                 
          }; 
          
                        window.onload = loadFormio();
        </script>
```

**Comment by randallknutson** [comment]
HTML and Content components also don't have values on a submission. They are representational only meaning that they display text to the user but don't store a value in the submission. You can set their value to {{data.somefield}} and it will render based on the value of another field.

**Comment by MalkyTheKid** [comment]
Thanks Randall, can you give me a gist or a simple script on how to implement that based on the implementation above?

**Comment by MalkyTheKid** [comment]
Or any guide in the wiki, or documents illustrating this simple use case, or a reference ticket at all. Please.

**Comment by randallknutson** [comment]
Create a form and add a field with the property name of "firstname". Add a content component and put "{{data.firstname}}" in the content somewhere. Check the "Refresh on change" checkbox on the content component. Render the form and enter a value in the firstname field. The content component should automatically update.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
