### ISSUE TITLE
[BUG] editgrid: row data replaced when click edit after delete row

### ISSUE THREAD

**Issue by gks66** [formio/formio.js#3045]
Formio.js version: 4.11.1 -> editgrid

sample from web: https://formio.github.io/formio.js/app/examples/editgrid.html

## Steps to Reproduce
1. Add a new record
2. Delete second record
3. Click edit on last record after delete (last record data will replace first record)

## Expected behavior
- First record shouldn't get replaced by last record.

## Observed behavior
- suspect function is editRow, goes wrong in this line "return this.redraw();"

## Example
![editgrid_issue_c1](https://user-images.githubusercontent.com/37319481/87504698-c96ed000-c699-11ea-8cbb-0d16fa3f138f.JPG)
![editgrid_issue_c2](https://user-images.githubusercontent.com/37319481/87504713-cd9aed80-c699-11ea-89ab-1918fe23044e.JPG)
![editgrid_issue_c3](https://user-images.githubusercontent.com/37319481/87504720-cffd4780-c699-11ea-8e7f-ee57e3b10c9f.JPG)
![editgrid_issue_c4](https://user-images.githubusercontent.com/37319481/87504723-d12e7480-c699-11ea-8212-2932ecd5f7ca.JPG)

**Comment by wag110894** [comment]
@gks66,

Thank you for providing a jsfiddle as well as screenshots or the issue taking place. We are able to replicate and have created a ticket for this issue (FJS-1072). 

We welcome a pull request and have a process to expedite. If you are interested in expediting, please contact support@form.io.

**Comment by gks66** [comment]
tested solved in version 4.12.0-rc.14
