### ISSUE TITLE
FORMIO: Hide a field using logic is not working 

### ISSUE THREAD

**Issue by NiteshNagar** [formio/formio.js#3047]
I have create a logic to change the Hidden property from hidden true to false but it is not working....

**Comment by wag110894** [comment]
Hello @NiteshNagar 
We are aware of this item and is currently in our backlog. We welcome a pull request or have a process to expedite this issue if you are interested. If you are interested in expediting, please contact support@form.io. The reference number is FJS-873.

We will let you know once this issue has been resolved.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
