### ISSUE TITLE
[BUG] Components not triggering the destroy lifecycle method as described in Templates-API

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3049]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version:
         - `formiojs@4.10.5`
         - `@formio/premium@1.14.0`
- Formio.js version: 4.10.5
- Frontend framework: none
- Browser: Google Chrome
- Browser version: 83.0.4103.116 (Official Build) (64-bit)

## Steps to Reproduce
1. Load form which is set to render as a wizard
2. Create custom component which extends any component
3. Create destroy method which calls `super.destroy()` so as to piggyback off intended implementation
4. Add console log which should be called when destroy is called

## Expected behavior
Navigate to new page in wizard and have destroy triggered

## Observed behavior
Navigate to new page in wizard where custom component is not on and have destroy lifecycle method triggered

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

![Screen Shot 2020-07-15 at 12 32 08 PM](https://user-images.githubusercontent.com/3672698/87570962-5cf2d180-c697-11ea-84ab-42d185a19b94.jpg)
![Screen Shot 2020-07-15 at 12 32 19 PM](https://user-images.githubusercontent.com/3672698/87570960-5cf2d180-c697-11ea-821f-4b67e40e6632.jpg)

For code or form JSON, please enclose in a code block:

```js
import { Components } from 'formiojs'

const FileComponent = (Components as any).components.file

export default class CardSnapshot extends (FileComponent as any) {
    constructor(component, options, data) {
        super(
            {
                ...component,
                storage: 'base64',
            },
            options,
            data
        )
    }

    static schema() {
        return FileComponent.schema({
            type: 'cardsnapshot',
        })
    }

    init() {
        super.init()

        this.cameraMode = true // Default camera mode to be on
    }

    render() {
        // Using custom template to render markup as we wish it to be rendered
        return this.renderTemplate('cardsnapshot', {
            fileSize: this.fileSize,
            files: this.dataValue || [],
            statuses: this.statuses,
            disabled: this.disabled,
            support: this.support,
        })
    }

    attach(element) {
        super.attach(element)

        this.refs.removeLink.forEach((removeLink) => {
            // When user removes the upload we want the default experience to have the camera be on
            removeLink.addEventListener('click', this.handleRemoveLinkClick.bind(this))
        })
    }

    handleRemoveLinkClick() {
        if (!this.cameraMode) {
            this.cameraMode = true
        }
    }

    upload(files) {
        super.upload(files)

        // When user uploads a file whether that's through the camera or file upload option the camera should be turned off
        if (this.cameraMode) {
            this.cameraMode = false
        }
    }

    destroy(...params) {
        super.destroy(...params)

        // When component is destroyed the camera should not remain turned on
        if (this.cameraMode) {
            this.cameraMode = false
        }
    }
}
```

## Template referenced as "cardsnapshot"
```js
const template = `
    <div ref="component" class="file m_overrides">
        {% if (ctx.files.length > 0) { %}
            <img ref="fileImage" class="image" alt="">
        {% } else { %}
            <video ref="videoPlayer" autoplay="true" class="video"></video>
        {% } %}

        <div class="file__ctas">
            {% if (ctx.files.length > 0) { %}
                <div>
                    <button class="btn btn-primary" ref="removeLink">Retake</button>
                    <button class="btn btn-primary" ref="removeLink">Save</button>
                </div>
            {% } else { %}
                <button ref="takePictureButton" class="takePictureButton">
                    <span><i class="fa fa-camera"></i></span>
                </button>
                <a ref="fileBrowse" href="#">Upload a File (file size < 10MB)</a>
            {% } %}
        </div>
    </div>
`
export default template
```

**Comment by travist** [comment]
Destroy should only be called when the component is being completely removed from the renderer (i.e. destroyed). Wizards actually do not destroy components between pages so that conditionals as well as calculated values can span across pages. I think the method you are wanting is called ```detach``` which does get called between wizard pages.

**Comment by SalTor** [comment]
I noticed that `detach` gets called multiple times (along with `attach`) when my custom component above receives a file. Is this the expected behavior?

**Comment by randallknutson** [comment]
Detach gets called every time a redraw occurs. When adding a file, a redraw occurs so that the new file can be displayed on the page. If you set up the attach/detach functions correctly, it shouldn't matter how many times they get called.
