### ISSUE TITLE
trim leading and trailing spaces in text input box

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3050]
I am new to Form.io and am trying to use form.io.js library for our implementation.

I have a input text box that accepts text.  I want to remove leading and/or trailing spaces if added and have the captured data with trimmed values.  I do not want to show validation message to user but simply trim the input value.

Can you please suggest, how this can be achieved.  Thank you in advance.

regards,
Mallikarjuna

**Comment by travist** [comment]
You can achieve this with a change event.

```js
form.on('change', function(event) {
  if (event && event.changed && event.changed.component && event.changed.component.type === 'textfield') {
    event.instance.setValue(event.changed.value.trim());
  }
});
```

**Comment by arjuna71** [comment]
Thank you for the update.
Is there a possibility of this functionality achieved as part of the component captured data JSON.

I observed custom validation OR field logic options in formio builder for text field.  Can this be achieved?

We are rendering the formio JSON fields on a web page.  The user inputs in the field will be stored in JSON as string.
Before storing, we want to trim data that has leading or trailing spaces before generating data JSON as string.

**Comment by travist** [comment]
Yes, I bet you can do this with the Calculated Value portion of the component. Something like this I bet would work.

```js
value = value.trim();
```

**Comment by arjuna71** [comment]
It is trimming the text, but NOT allowing spaces between the text.  The requirement is to trim only leading and trailing spaces of given word or sentence.

Thank you for option mentioned, is there any other way to get the result.

**Comment by arjuna71** [comment]
Seems there is no solution of trimming only leading and trailing spaces and NOT in between the words using javascript in formio component.  Expecting a solution atleast in the next update of Formio.js.

If there is any, let me know else, the ticket can be closed.

**Comment by wag110894** [comment]
@arjuna71 Appologies on the delay. We have created a ticket (FJS-1127) and have added this to our backlog. We welcome a PR and have a process to expedite if you are interested. If you are interested in expediting, please contact support@form.io.

Thank you.

**Comment by lane-formio** [comment]
Resolved with https://github.com/formio/formio.js/pull/4086
