### ISSUE TITLE
[BUG] Form with EditGrid component fails to render in IE11

### ISSUE THREAD

**Issue by llaurentiu** [formio/formio.js#3054]
- Formio.js version: v4.11.1-rc.3
- Browser: IE
- Browser version: 11

## Steps to Reproduce
1. Create & render a form that has an edit grid component using IE11

## Expected behavior
Form renders
## Observed behavior
Creation of the form throws a `DOMException `- Syntax error

The reason for it is the EditGrid component, line 188: https://github.com/formio/formio.js/blob/v4.11.1-rc.3/src/components/editgrid/EditGrid.js

":scope" is not a valid IE selector.

Possible fixes:
- use a `querySelector` polyfill
or
- workaround using lodash: `this.refs[`${ massageContainerRef }`] = _.find(_.toArray(element.children), function(p){ return p.getAttribute("ref") == "messageContainer"; });`

**Comment by elibus** [comment]
@TanyaGashtold @heather-formio

**Comment by wag110894** [comment]
Hello @llaurentiu and @elibus 
Thank you for your patience while we were working on resolving some issues with IE11 that were blocking us from testing this issue. We are unable to replicate this issue on our side using our latest version of formio.js (4.11.1-rc.8). We started from building the component on IE11 and are seeing it render in IE11. 

If you are still experiencing this issue on your end, can you please provide a form embed as well as a screenshot of the errors as well as the Edit Grid not rendering?

Looking forward to your response.

Thank you.

**Comment by llaurentiu** [comment]
Hi @wag110894 ,

It seems it was fixed 3 days ago in 4.11.1-rc8,  by adding a polyfill. With this checkin: https://github.com/formio/formio.js/commit/1edf3fc68be208ba357bf0f33da2e6ba5e533433

I am closing the issue.

Thanks for help.
