### ISSUE TITLE
[BUG] select component - Incorrect display and duplication of the list.

### ISSUE THREAD

**Issue by dispbd** [formio/formio.js#3056]
## Environment
Please provide as many details as you can:

- Hosting type: Local deployment
- Formio.js version: Last
- Frontend framework: Bootstrap
- Browser: All
- Browser version: Last

## Steps to Reproduce
1. Goto Link to: https://codepen.io/WebPoet/pen/qBbJMrX
2. Select the "group" component. Then select the component "send_userID". The values will be duplicated in the drop-down list (BUG).
3. The "send_userID" component after selection will display "data.value", although it should display "data.label". Then it will delete the entire array of values in the drop-down list and duplicate the displayed value (BUG).

## Expected behavior
With predefined values, the dropdown list behaves correctly. This can be seen in the example of a field with the group key.

## Observed behavior
If the value in the drop-down list is set after the initialization of the form (for example, at an event), then the component works incorrect (described in the example and paragraph 3).

## Example
Goto Link to: https://codepen.io/WebPoet/pen/qBbJMrX
All steps are also demonstrated in the animation: https://i.vgy.me/O8mbax.gif

I suspect that it is precisely because of duplication that there are problems with displaying in the field.
I understand that the fix may not be quick, but is there any way to work around this problem?
I will clarify that I cannot set the value in the second field in advance, since it depends on the first field.

**Comment by dispbd** [comment]
Can anyone suggest anything?

**Comment by wag110894** [comment]
Hello @dispbd,

Thanks for reaching out!

We are unable to replicate this issue outside of the codepen you provided. Here is a link to our Sandbox, where you can load in the example of this working on our side: http://formio.github.io/formio.js/app/sandbox 

You will add: 5f16fbbdc6051022f749042e to the load form section and you will see the form appear. You will see our formio.js builder and then see the form render below. 

I hope that this helps.

Thank you.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
