### ISSUE TITLE
JSON form spec?

### ISSUE THREAD

**Issue by ssdhaliwal** [formio/formio.js#306]
Is there a place in Wiki which provides full JSON form supported spec?  I have looked at the Kitchen Sink example but that does not provide all options or how they apply to each component.

Is this something I can help with, unless already done - then let me know where to look please.

**Comment by travist** [comment]
https://github.com/formio/formio.js/wiki/Form-JSON-Schema

**Comment by ssdhaliwal** [comment]
Thank you.
