### ISSUE TITLE
File component with S3 storage not signing requests for thumbnail image

### ISSUE THREAD

**Issue by finitor** [formio/formio.js#3066]
## Environment
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
- Formio.js version: 4.10.5
- Frontend framework: JS
- Browser: Chrome 83.0.4103.116 MacOS

## Steps to Reproduce
1. Set up S3 integration using form.io recommended bucket policies
2. Create a form containing a File component
3. Enable "Display as image" component setting
4. Publish form, drag a jpeg file to the File component
5. In Chrome dev tools, observe that there is a successful POST to S3 using a signed URL
6. In Chrome dev tools, observe that there is a failed GET to S3 using an unsigned URL (401 Unauthorized)
7. In the form renderer, observe that the display thumbnail shows as a broken image

## Expected behavior
In step 6-7 above, we expect a successful GET to S3 using a signed URL, followed by the form renderer correctly showing a thumbnail of the uploaded image. This is the behavior observed in the live preview of form builder's 'Use' tab.

<img width="1006" alt="Screen Shot 2020-07-21 at 6 16 44 PM" src="https://user-images.githubusercontent.com/148494/88112712-6cce5200-cb7e-11ea-974e-cfa3390706e1.png">
<img width="186" alt="Screen Shot 2020-07-21 at 6 15 41 PM" src="https://user-images.githubusercontent.com/148494/88112751-79eb4100-cb7e-11ea-9fd8-77b3617f11a2.png">

**Comment by travist** [comment]
This is most likely an S3 permissions configuration. Will you confirm what permission configurations that you have configured on this S3 bucket? It needs to allow "Public" access if you do not want to use "signed" urls.

**Comment by finitor** [comment]
We definitely want to use signed urls for both the initial upload of the file and the download that File component seems to want to do to render the thumbnail. The issue seems to be that File component is not signing the download request. Public access is not an option because these files contain HIPAA PII. Our current bucket policy is as follows (some identifiers disguised):

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::999999999999:root",
                    "arn:aws:iam::999999999999:user/user-whose-key-and-secret-we-put-in-formio-s3-integration-settings"
                ]
            },
            "Action": [
                "s3:PutObjectAcl",
                "s3:PutObject",
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::our-bucket-name/*"
        }
    ]
}

**Comment by finitor** [comment]
Also note that this whole flow works with these same S3 settings in the form builder's 'Use' tab, so there must be some difference in the storage provider implementation that it is using vs the one in formio.js 4.10.5 which our own clients are using.

**Comment by finitor** [comment]
Closing this issue, resolved by adding the user's role (Anonymous in our case) to "Read Own Submissions" in form builder "Access" tab.

<img width="413" alt="Screen Shot 2020-07-23 at 5 04 48 PM" src="https://user-images.githubusercontent.com/148494/88339135-864ed580-cd07-11ea-9baa-381b9b212550.png">
