### ISSUE TITLE
Multiple Select not working properly

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#307]
I just updated to the newest version 2.27.0 and I have a weird behavior with the multiple select.
I have some conditional logic to show or hide a page given the values selected on the multiple select elements.
In version 2.27.0 if I select one of the options, all the other options get selected and the option that I selected gets selected twice (shouldn´t be possible in multiple select)

I downgraded to version 2.25.3 and everything works normally.

You can check the form JSON here: https://efqbsqrkscuzlpi.form.io/scoutingtraps

(Try the select in the What data do you want to collect (select at least one) question)
CodePen: https://codepen.io/cabrerabywaters/pen/zppZPw

Best Regards!

**Comment by travist** [comment]
Thanks for providing the form. I can definitely see the problem. We will look into it very soon.

**Comment by travist** [comment]
I just tested your form with the latest version and it seems to be working now. Please verify.

**Comment by cabrerabywaters** [comment]
Working! 
Thank you
