### ISSUE TITLE
[BUG] Datagrid min length > Added wrong row, and no error message

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3075]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ ] Local deployment
    - Version: 
  - [x] https://formio.github.io/formio.js/app/builder
- Browser: Microsoft Edge
- Browser version: Version 84.0.522.40 (Offical build) (64bit)

## Steps to Reproduce
1. Create a data grid
2. Valdiation > Minimum Length = 3
3. Click "Add Another Row" [Observed behavior 1]
4. Click "Delete" Icon  [Observed behavior 2]

## Expected behavior
1. Added 3 row
2. Should be show error message like "At least 3 row" or hide delete button

## Observed behavior
1. Added 4 row
2. Removed 4 row without error message

## Example
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3075.gif?raw=true)

Schema:
```json
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Data Grid",
            "reorder": false,
            "addAnotherPosition": "bottom",
            "defaultOpen": false,
            "layoutFixed": false,
            "enableRowGroups": false,
            "tableView": false,
            "defaultValue": [
                {}
            ],
            "validate": {
                "minLength": 3
            },
            "key": "dataGrid",
            "type": "datagrid",
            "input": true,
            "components": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by wag110894** [comment]
This is because the Data Grid component is empty. Try adding a component into the Datagrid and you will see that it shows 3 rows of that component.

**Comment by bleungAtGTI** [comment]
OK, thanks a lot 👍
