### ISSUE TITLE
File Component - Edit uploadOnly 

### ISSUE THREAD

**Issue by jftsaraiva** [formio/formio.js#3084]
How can I edit `uploadOnly` on file component? I can't find it in component's configuration in the form builder.

Shouldn't it be in  [src/components/file/editForm/File.edit.file.js](https://github.com/formio/formio.js/blob/master/src/components/file/editForm/File.edit.file.js) ?

**Comment by randallknutson** [comment]
It should be in there but it appears we haven't added a config for it yet. You can set it with the JSON edit for the field or if you want to submit a Pull Request to add that setting.
