### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hisuwh** [formio/formio.js#3090]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: vue-formio@4.0.4
- Formio.js version: 4.11.0
- Frontend framework: vue
- Browser: Chrome
- Browser version: 84.0.4147.89

## Steps to Reproduce
1. Build form with datetime on formio.github.io
2. Render form with vue-formio

```html
<formio :form="form" />
```

```js
import { Form, Templates } from "vue-formio";

Templates.framework = "bootstrap";

const form = {
    display: "form",
    components: [
         ....
         {
              label: "Date of birth",
              labelPosition: "left-left",
              displayInTimezone: "utc",
              format: "dd-MM-yyyy",
              tableView: false,
              enableMinDateInput: false,
              datePicker: {
                   disableWeekends: false,
                   disableWeekdays: false
              },
              enableMaxDateInput: false,
              enableTime: false,
              key: "dateOfBirth",
              type: "datetime",
              input: true,
              widget: {
                   type: "calendar",
                   displayInTimezone: "utc",
                   language: "en",
                   useLocaleSettings: false,
                   allowInput: true,
                   mode: "single",
                   enableTime: false,
                   noCalendar: false,
                   format: "dd-MM-yyyy",
                   hourIncrement: 1,
                   minuteIncrement: 1,
                   time_24hr: false,
                   minDate: null,
                   disableWeekends: false,
                   disableWeekdays: false,
                   maxDate: null
              },
              hideOnChildrenHidden: false
          },
      ...
      ]
}

export default {
    name: "MyComponent",
    components: {
        formio: Form
    },
    data: () => ({
        form
    })
};
```

## Expected behavior

Should display a datepicker

## Observed behavior

Datepicker not displayed and giant icons displayed after form.  (Also `labelPosition: "left-left"` is ignored).

![image](https://user-images.githubusercontent.com/4470351/88795443-f04bfc80-d197-11ea-8b2e-bea840660bb6.png)
![image](https://user-images.githubusercontent.com/4470351/88795543-1d98aa80-d198-11ea-9804-5222b25cd415.png)
![image](https://user-images.githubusercontent.com/4470351/88795556-24272200-d198-11ea-9687-6eba2e4b11f6.png)

**Comment by hisuwh** [comment]
I've got the same problem with selects as well:
![image](https://user-images.githubusercontent.com/4470351/88803636-acabbf80-d1a4-11ea-840b-557499678b02.png)

**Comment by wag110894** [comment]
Hello @hisuwh,

It looks like you have not pulled in the CSS files into your application. Once you pull this in, then everything will look correct. 

I hope that this helps.

**Comment by hisuwh** [comment]
🤦‍♂️ thanks.
This should probably mentioned in the docs for vue-formio though

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
