### ISSUE TITLE
[BUG] Input fields lose focus on key press when using columns + auto_adjust and field logic

### ISSUE THREAD

**Issue by annunn** [formio/formio.js#3097]
We turned auto_adjust off, so this is not affecting us anymore.

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.11.0
- Frontend framework: Angular
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Focus input control
2. Press key

## Expected behavior
Not lose focus

## Observed behavior
Focus lost on every key press

## Example
https://jsfiddle.net/annunn/xyhvenws/17

## Cause (I think)
originalComponent has width: 0
Columns sets the width of the component to that of the column.
isEqual(this.component, newComponent) returns false as the width is different.
the input control is replaced with newComponent. (focus is lost)

Component.js: 1631

      var newComponent = (0, FormioUtils.fastCloneDeep)(this.originalComponent);
      var changed = logics.reduce(function (changed, logic) {
        var result = FormioUtils.checkTrigger(newComponent, logic.trigger, row, data, _this10.root ? _this10.root._form : {}, _this10);
        return (result ? _this10.applyActions(newComponent, logic.actions, result, row, data) : false) || changed;
      }, false); // If component definition changed, replace and mark as changed.

      if (!_lodash.default.isEqual(this.component, newComponent)) {
        this.component = newComponent; // If disabled changed, be sure to distribute the setting.

        this.disabled = this.shouldDisabled;
        changed = true;
      }

Columns.js: 226
value: function justifyRow(columns) {
      var visible = _lodash.default.filter(columns, 'visible');

      var nbColumns = columns.length;
      var nbVisible = visible.length;

      if (nbColumns > 0 && nbVisible > 0) {
        var w = Math.floor(this.gridSize / nbVisible);
        var totalWidth = w * nbVisible;
        var span = this.gridSize - totalWidth;

        _lodash.default.each(visible, function (column) {
          column.component.width = w;
        }); // In case when row is not fully filled,
        // extending last col to fill empty space.

**Comment by cmcortez** [comment]
This configuration is causing a redraw on each keypress. As part of a support package, we would be happy to take a deeper look. If you are interested in going down this path please contact support@form.io

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
