### ISSUE TITLE
[BUG] Translated Error Message not displaying at the top of the page

### ISSUE THREAD

**Issue by JeStud** [formio/formio.js#3105]
## Environment
- Hosting type: found it locally, also on Form.io
- Formio.js version: 4.11
- Browser: I tested with Chrome and Firefox

## Steps to Reproduce
1. Create a form with a translation and a required field
2. Create a translation for the required field (for example 'required': '{{field}} est requis.', )
3. Submit without filling in the required field

## Expected behavior
The translation displays correctly next to the Form Component and in the Alert Message at the top of the page.

## Observed behavior
The translation displays correctly next to the Form Component, but at the top of the page it only shows "alertMessage" (copied from the Form.io Translation Walkthrough) :

Veuillez corriger les erreurs suivantes avant de l'envoyer.
 - alertMessage
 - alertMessage
 - alertMessage

## Example
[Form.io Translation Walkthrough](https://help.form.io/tutorials/walkthroughs/translations/)
[JSFiddle](https://jsfiddle.net/Formio/yvg8zweh/)
![image](https://user-images.githubusercontent.com/43845954/89156554-2a881600-d56b-11ea-9988-49f773474129.png)

**Comment by kzhang-dsg** [comment]
I am facing the same issue. Downgrading to version 4.10.2 fixed the issue. Looks like it is a new bug introduced in the new 4.11 version.

**Comment by wag110894** [comment]
@JeStud @kzhang-dsg Thank you both for reaching out! We are able to replicate this issue on our side. We have created a ticket. For reference, the ticket number is FJS-1128. We have assigned this item as a high priority. We will let you know once this issue has been resolved.

Thank you!

**Comment by JeStud** [comment]
Thanks @kzhang-dsg, using 4.10.2 works as a solution
Thanks @wag110894, appreciate it

**Comment by wag110894** [comment]
Hello all,

The issue with the JSFiddle above was that needed need to add 'alertMessage': '{{label}}: {{message}}' in their list with translations for each language. Here is working JSFiddle: https://jsfiddle.net/231ygthz/6/.
