### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by praveenmadishetty** [formio/formio.js#3107]
## Environment
Please provide as many details as you can:

I Have created a custom input text component using formiojs,
and it is not detecting default value entered from settings to display in custom input text, Please help me regarding this. 

Thanks in Advance
Praveen Madishetty

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort,
closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
