### ISSUE TITLE
[BUG] Wizard Breadcrumb visible on first step even though set to "Hidden"; `this.currentPanel` is `null`

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3111]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 4.11.0-rc.4
- Formio.js version: 4.10.5
- Frontend framework: None
- Browser: Chrome
- Browser version: 84.0.4147.105 (Official Build) (64-bit)

## Steps to Reproduce
1. Create a form
2. Set panel settings to display breadcrumb as hidden
3. Load form

## Expected behavior
Breadcrumb should not be visible on the first page on first load.

## Observed behavior
Breadcrumb is visible on initial load, but if you create a second page and navigate to the next page and then back to the first page you will see that the breadcrumb is **no longer*** visible.

This bug is likely related to tickets [formio/formio.js#34](https://github.com/formio/vue-formio/issues/34) and [formio/formio.js#2039](https://github.com/formio/formio.js/issues/2039)

### Suspected Bug
In [Wizard.js line 154](https://github.com/formio/formio.js/blob/master/src/Wizard.js#L154) the render code refers to `this.currentPanel` but during development of semi-related work I noticed that `this.currentPanel` is null during form initialization and there's no render event emitted form formio on first render.

**Comment by wag110894** [comment]
@SalTor Can you provide a JSFiddle of the issue taking place?

**Comment by SalTor** [comment]
@wag110894 Here's a JSFiddle demonstrating the issue taking place: https://jsfiddle.net/saltorcivia/31724re6/3/

**Comment by SalTor** [comment]
I updated the comment to accurately reflect the problem: the breadcrumb bar is visible on first load of the first page but subsequent visits to the page properly hide it.

**Comment by wag110894** [comment]
@SalTor Thank you for reaching out! We are able to replicate this issue on our side. We have created a ticket and have added this to our backlog. For reference, the ticket number for this issue is FJS-1131. We welcome a Pull Request or have a process to expedite if you are interested.

Please let me know if you are interested in expediting and I can provide you information on the process.

We will let you know once this issue has been resolved.

**Comment by jhen1422** [comment]
@SalTor 
This should be resolved in formio.js 4.12.0-rc13>
