### ISSUE TITLE
[BUG] Can't resize table column / row / components on "Merge component schema"

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3132]
## Environment
- Hosting type
  - [ ] Form.io
  - [ ] Local deployment
    - Version: 
  - [x] https://formio.github.io/formio.js/app/builder
- Browser: Google Chrome
- Browser version: Version 84.0.4147.105 (Official Build) (64-bit)

## Why?
I want to make a component can add row & column programmatically by form value
Maybe "survey" can help me do that?

## Steps to Reproduce
1.  using this schema
```json
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "columns",
            "mask": false,
            "spellcheck": true,
            "tableView": false,
            "delimiter": false,
            "requireDecimal": false,
            "inputFormat": "plain",
            "key": "columns",
            "type": "number",
            "input": true
        },
        {
            "label": "rows",
            "mask": false,
            "spellcheck": true,
            "tableView": false,
            "delimiter": false,
            "requireDecimal": false,
            "inputFormat": "plain",
            "key": "rows",
            "type": "number",
            "input": true
        },
        {
            "label": "Table",
            "cellAlignment": "left",
            "tableView": false,
            "key": "table",
            "logic": [
                {
                    "name": "updateWhenNumberChanged",
                    "trigger": {
                        "type": "javascript",
                        "javascript": "result = data.rows * data.columns;"
                    },
                    "actions": [
                        {
                            "name": "updateSchema",
                            "type": "mergeComponentSchema",
                            "schemaDefinition": "schema =  {\r\n  numRows: 1,\r\n  numCols: 1,\r\n  rows: [\r\n    [\r\n      {\r\n        components: [\r\n          {\r\n            label: \"Text Field\",\r\n            key: \"textField\",\r\n            type: \"textfield\",\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  ]\r\n}"
                        }
                    ]
                }
            ],
            "type": "table",
            "numRows": 1,
            "numCols": 1,
            "input": false,
            "rows": [
                [
                    {
                        "components": []
                    }
                ]
            ]
        }
    ]
}
```
2.  Change columns and rows number box, it will trigger "Merge component schema"

## Expected behavior
Table row / column / components will update, because it merged new schema

## Observed behavior
[Table.js:300 Uncaught TypeError: Cannot read property 'components' of undefined](https://github.com/formio/formio.js/blob/3d8592bcfa37cf0fe88039057316447dab81eb8a/src/components/table/Table.js#L157)

`this.component.rows[rowIndex][columnIndex]` is undefined

## Explain
Because after merge schema, it haven't re-run `init()`
so in `attach()` `this.table` size not match with `this.component.rows` size

## Example
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3132.gif?raw=true)

**Comment by wag110894** [comment]
@bleungAtGTI Can you provide a jsfiddle of the issue taking place as well as a video? This will help us replicate the issue.

**Comment by bleungAtGTI** [comment]
@wag110894 
1. Updated screenshot
2. Finally, i created a custom component like `Survey` to walkaround

**Comment by wag110894** [comment]
Hello @bleungAtGTI. Thank you for reaching out! We are able to replicate this issue on our side. We have added this issue to our backlog. We welcome a pull request or we have a process to expedite this issue if you are interested. Please let me know if you are interested in pursuing the expediting and we can get this process going. The ticket number for this issue is FJS-1166.

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
