### ISSUE TITLE
[BUG] Select component visualization bug

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#3133]
## Environment
Please provide as many details as you can:

- Hosting type
- [x] Local deployment
    - Version: 
- Formio.js version: formiojs@4.11.1
- Frontend framework:
- Browser: Chrome
- Browser version: 84.0.4147.105

## Steps to Reproduce
1. Create form with select component
2. Add data in select component

## Expected behavior
Normal height form
## Observed behavior
Select component increase the height
## Example
https://jsfiddle.net/9zj3pcto/
![image](https://user-images.githubusercontent.com/22855299/89902875-aa5b5380-dbef-11ea-8431-7b659d4c745d.png)

**Comment by wag110894** [comment]
Hello @homashevchenko Thank you for reaching out! We are able to replicate this item and have added this to our backlog. For reference, the ticket number is FJS-1146. We welcome a pull request or have a process to expedite if you are interested. Please let me know if you are interested in expediting this fix and I can get that process started.

We will let you know once this issue has been resolved.

Thank you!

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
