### ISSUE TITLE
[BUG] Select html5 can't have a value "<"

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3140]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] https://formio.github.io/formio.js/app/builder
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Drag and Drop `Select` Component
Widget Type = html5
Data Source Type = Values
3.  Type Data Source Values > Label  ">"

## Expected behavior
1. Type Data Source Values > Value should be ">"
2. In `Preview`, have a item ">"

## Observed behavior
1. Type Data Source Values > Value is empty
2. In `Preview`, no item

## Example
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3140.gif?raw=true)

**Comment by randallknutson** [comment]
This is probably by design. The value is what is stored in the database and it is restricted to numbers and letters. Would it be possible to use "gt" or something like that instead of the < character?

**Comment by bleungAtGTI** [comment]
using `&gt;` `&lt;` can display and using in calculating value normally

@randallknutson Any concerns?

![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3140_1.png?raw=true)

![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3140_2.png?raw=true)

**Comment by travist** [comment]
Seems reasonable.
