### ISSUE TITLE
There is no way to remove eventHandler added through onAny()

### ISSUE THREAD

**Issue by j-perl** [formio/formio.js#3154]
I'm using react-formio and it happens that I have to remove the eventHandler added by means of onAny(). However, looking at the source code of Element.js, I haven't found any (EventEmitter does have an offAny(), I believe).

A bit of context : whenever I pass a new function onSubmit down to the Form component, I've noticed that the event handler is using a stale version of the props. I had to implement my own Form wrapper for there was nothing else I could do. I managed to add a new event handler by means of useEffect() whenever the reference to props would change. However, the previous handlers are still there so the callback is called several times both with stale props and new props.

**Comment by randallknutson** [comment]
I'm not entirely following the issue here. Is there a change we can make to either formio.js or react-formio to fix this problem?

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
