### ISSUE TITLE
Dynamic Values for Survey Component

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#3159]
I have a requirement to generate questions and responses from a list of questions in a lookup table. I thought that Survey component would fulfill that requirement, however I am unable to achieve what I want with the survey component. There are two issues:

1) Using the form builder, I am unable to provide a link to web API for loading questions, as it is asking me to add questions manually. I thought that I could use something similar to 'custom' data source that we use for Select component but I don't see any option on the form builder. Please see screenshot below for manually adding questions and responses.

2) The second issue is that the each question has the same responses, however, in my case some questions may not have all the responses, e.g. third question may have an added response of Unknown. So I would like to use a **select** component with it's own responses against each question. Is this possible?

Can I achieve above two items with a survey component or is there an alternative approach that I can use? I explored using Data Grid but I don't think that is suitable for my scenario as the data grid uses common labels for each column. Any help would be very helpful.

![image](https://user-images.githubusercontent.com/40409548/90693616-0d438f00-e26f-11ea-94b5-ebd6217c4ebf.png)

**Comment by kzhang-dsg** [comment]
Have you seen this example: https://formio.github.io/formio.js/app/examples/external.html

**Comment by randallknutson** [comment]
1. The survey component does not yet have the ability to load in questions from a URL. This is something we would be interested in adding.

2. Currently the survey component has the same questions and values for all items in the table. Again, if this makes sense we would be interested in adding some additional functionality around this.

**Comment by learner291** [comment]
> Have you seen this example: https://formio.github.io/formio.js/app/examples/external.html

Yes, I have. It has edit button for editing which is not required in my case. The first column should be a label, but it doesn't provide any label component. I would require something like survey with dynamic answers for each question or batch edit grid with labels (asking question) in the first column and select component as a second column where user can simply select a value (answer).

**Comment by learner291** [comment]
> 1. The survey component does not yet have the ability to load in questions from a URL. This is something we would be interested in adding.
> 2. Currently the survey component has the same questions and values for all items in the table. Again, if this makes sense we would be interested in adding some additional functionality around this.

I believe these both changes will really enhance the survey component, and provide flexibility. Do you think, you will be building these functionalities in the near future?

**Comment by randallknutson** [comment]
We don't currently have a plan to. Typically we can add features for customers in one of two ways. First, customers can sponsor new features to move them up the priority list and second, they can contribute a pull request with the new feature.

Another thing to look at might be the Logic tab on the survey component. In the logic action, there is a "merge component schema" which can be used to modify the definition based on values in the form. This might work but would require some figuring out how to set up the schema changes.

**Comment by travist** [comment]
You can "simulate" a survey component to give you more flexibility by using a Table component. The first thing you will need to do is to simulate the data structure. This can be done using a Container with the name of the survey. Then every component within that Container will be contained at that namespace, like so..

```
{
  "data": {
    "survey": {}
  }
}
```

Next, you will drag a Table component inside the container, and then build out how you would like to show it. To achieve the split up Radio components, this is simply the Checkbox component, and then select Input Type as "Radio" and provide any component in the same row as the same Radio Key. This will ensure that each row is capturing the same survey value like so.

```
{
   "data": {
    "survey": {
       "areYouHavingFunYet": "Yes!!!"
    }
  }
}
```

This then gives you the flexibility to make the table what you want to make it. As for making this API generated, this may need to be done using Logic, but I have not gone that deep into prototyping this out.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
