### ISSUE TITLE
[BUG] hide / show not work in modalEdit correctly

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3160]
## Environment
- Hosting type
  - [x] https://formio.github.io/formio.js/app/builder

## Steps to Reproduce
1.  drag and drop a checkbox
2.  drag and drop a textfield with:
  - Modal Edit: true
  - conditional.show: true
  - conditional.when: checkbox
  - conditional.eq: true
3. change the checkbox value

## Expected behavior
It will hide / show the textfield (label + modal button)

## Observed behavior
It only hide / show the textfield (label + textbox) **inside the modal dialog**

## Example
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3160.gif?raw=true)

**Comment by wag110894** [comment]
Hi @bleungAtGTI, 
Thanks for reaching out.

Based on the video that you provided, the text field is not showing when the checkbox is false. The modal still opens  but the hidden component is not.

**Comment by bleungAtGTI** [comment]
@wag110894  Hi, any planning to fix this bug?

**Comment by wag110894** [comment]
Hello @bleungAtGTI, this functionality is working on how we intended it to work. If you think this should function differently, then we can add this item to our planning meeting to discuss further.
