### ISSUE TITLE
clearOnRefresh doesnot work inside Data grid

### ISSUE THREAD

**Issue by Jerry1990258** [formio/formio.js#3162]
I have two dropdowns  
- Type
- Sub Type
(both populated using 'URL')
The Sub Type should populate based on the Type.
It works when both fields are outside data grid.
For it to work,  I have enabled Clear Value on Refresh Options and given 'Type' field in Refresh Options On.

But if I have the same two fields outside  Data Grid and follow the above steps - the previously selected subtype is populating twice and getting appended with the existing sub type for a newly selected Type . It is not getting refreshed.

**Comment by wag110894** [comment]
@Jerry1990258 Can you provide a form embed or a JSfiddle so that we can test on our side?

**Comment by kzhang-dsg** [comment]
This is the same issue as https://github.com/formio/formio.js/issues/3108

Demo: https://formio.github.io/formio.js/app/examples/external.html

The Clear Value on Refresh does not work on "Model" if you change the "Make".
