### ISSUE TITLE
Populate Select Component Data from Async Request

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#3167]
Hi All, 

I would like to populate the items available in a select component (drop down menu) with values that are returned form an async JavaScript function. How can I go about doing this? 

I have tried using "Custom Data Source Type" and writing an async java script to set the "values" property but this does not work. 

![image](https://user-images.githubusercontent.com/12785492/90864496-5ad11080-e3c3-11ea-9cc3-3cf14af9cef0.png)

I have previously populated text boxes using async functions using the `instance.setData(resourceString)` function. Is there an equivalent for select compoents?

**Comment by randallknutson** [comment]
There is a "setItems" function that works similarly. https://github.com/formio/formio.js/blob/1f864ffa3a0880aae0a4d5ff40eb351450e47baf/src/components/select/Select.js#L289

**Comment by AnthonyPhan** [comment]
Thanks @rahatarmanahmed 

It does not seem to be working for me. Do you mind confirming if I am using the function correctly? 

```
let items = [{label:"Item1"},{label:"Item2"}];
instance.setIteams(items, true)

```

I did notice from the select.js that the "fromSearch" parameter is not used.

**Comment by randallknutson** [comment]
This is tricky to debug without getting the error message in the browser but I would bet that it is being caused by the async function. Async may not be supported in your browser yet and you will need to use a promise instead.

**Comment by AnthonyPhan** [comment]
Thanks @randallknutson , 
I can confirm this is now working after refactoring my code to user .then instead of async awaits. 

![image](https://user-images.githubusercontent.com/12785492/91533262-2e2c7400-e942-11ea-84f7-4f95132d5228.png)

**Comment by wag110894** [comment]
@AnthonyPhan Great news! 

Please let us know if you have any further questions.

Have a great day!
