### ISSUE TITLE
[QUESTION] url data source for select form component, anyway to manipulate the json for it to work with select component?

### ISSUE THREAD

**Issue by kokkoon** [formio/formio.js#3174]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:any
- Frontend framework: reactjs
- Browser:any
- Browser version:any

I am trying to see how to get a list of currency from any currency api available out there, they all returns json similar to below:

GET https://api.exchangeratesapi.io/latest HTTP/1.1

{
  "base": "EUR",
  "date": "2018-04-08",
  "rates": {
    "CAD": 1.565,
    "CHF": 1.1798,
    "GBP": 0.87295,
    "SEK": 10.2983,
    "EUR": 1.092,
    "USD": 1.2234,
    ...
  }
}

how do I get the list of currency in this example? with select options of ["CAD","CHF","GBP","SEK","EUR","USD",..] ?

I see no way to manipulate the given to a format accepted by the options here...

Regards,

**Comment by randallknutson** [comment]
The one requirement of the API response is that it needs to be an array. In this example it is actually an object with key/value pairs which our component doesn't know how to interpret. There are a few ways to work around this. First, we could add the ability in the component to read a response object key/value pairs but this would take some work. You could also do the fetch outside of the form and set the values on the form object automatically. Additionally, you could proxy the api request and change the data in the proxy into an array.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
