### ISSUE TITLE
CK Editor - Hiding Image and Media from the toolbar

### ISSUE THREAD

**Issue by learner291** [formio/formio.js#3181]
I would like to hide image and media buttons from the toolbar. Do I need to remove them as plugins by adding the following line?

`removePlugins: [ 'Image', 'Media' ]`

If yes, where would I add this line of code as I don't see any option on the component configuration dialog. There is an Editor's setting but that only accepts true or false.

The second query is, how can I use inline CK editor? Is their a configuration settings on the configuration dialog?

**Comment by travist** [comment]
All we provide is the ability to configure CK Editor. The actual support and what configurations to provide to make it behave in a certain way is a little bit out of scope from support in this library. You may try opening a ticket within the CK Editor channels.

**Comment by namti** [comment]
> All we provide is the ability to configure CK Editor. The actual support and what configurations to provide to make it behave in a certain way is a little bit out of scope from support in this library. You may try opening a ticket within the CK Editor channels.

Could you please give us some clue of configuring CK Editor? I cannot find any documentation of it. Thanks

**Comment by russell-coviu** [comment]
I've done the following to do some configuration to remove some items in the toolbar for CKEditor

```
export const formBuilderOptions = {
	noDefaultSubmitButton: true,
	editors: {
		ckeditor: {
			settings: {
				toolbar: [
					'heading',
					'fontSize',
					'|',
					'bold',
					'italic',
					'link',
					'bulletedList',
					'numberedList',
					'|',
					'insertImage',
					'blockQuote',
					'insertTable',
					'insertMedia',
					'undo',
					'redo'
				]
			}
		}
	}
}
```

Do note that CKEditor provides an ability to remove items from a toolbar by doing something more like the below, however the version of CKEditor5 that is used with formio (v19) doesn't have removeItems which was added in v25

```
settings: {
		toolbar: {
                    removeItems: ['fontFamily']
                }
	}
```

**Comment by namti** [comment]
> I've done the following to do some configuration to remove some items in the toolbar for CKEditor
> 
> ```
> export const formBuilderOptions = {
> 	noDefaultSubmitButton: true,
> 	editors: {
> 		ckeditor: {
> 			settings: {
> 				toolbar: [
> 					'heading',
> 					'fontSize',
> 					'|',
> 					'bold',
> 					'italic',
> 					'link',
> 					'bulletedList',
> 					'numberedList',
> 					'|',
> 					'insertImage',
> 					'blockQuote',
> 					'insertTable',
> 					'insertMedia',
> 					'undo',
> 					'redo'
> 				]
> 			}
> 		}
> 	}
> }
> ```
> 
> Do note that CKEditor provides an ability to remove items from a toolbar by doing something more like the below, however the version of CKEditor5 that is used with formio (v19) doesn't have removeItems which was added in v25
> 
> ```
> settings: {
> 		toolbar: {
>                     removeItems: ['fontFamily']
>                 }
> 	}
> ```

Thanks. It works

**Comment by vadykoo** [comment]
![image](https://github.com/user-attachments/assets/000c3e8f-5ba4-42b2-871d-1cc68a167655)

```
{
  "rows": 3,
  "base64Upload": false,
  "mediaEmbed": {
    "previewsInData": true
  },
  "toolbar": [
    "heading", "Font", "fontSize", "Bold", "Underline", "Strike",
    "NumberedList", "BulletedList","|",
    "Link", "Unlink",
    "Blockquote", "|", "Undo", "Redo"
  ],
  "allowedContent": true
}
```
