### ISSUE TITLE
[BUG] unable to see sketchpad component 

### ISSUE THREAD

**Issue by manjunathreddyr** [formio/formio.js#3191]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. go to form builder
2. open  premium components
3. check for sketch pad

## Expected behavior
sketchpad should be available
## Observed behavior
no sketchpad is availabe but it is present in formio website
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
![sketchpad](https://user-images.githubusercontent.com/47288360/91316156-2223a380-e7d6-11ea-8f9e-c5cae61c6e08.png)

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
@manjunathreddyr 

The Sketchpad component is only available as part of the enterprise package which is why you do not see it on the formio.js builder and will see it on the

**Comment by manjunathreddyr** [comment]
@wag110894 

Thanks @wag110894 ,is there any other example or way where custom component can be created similar to this.

**Comment by wag110894** [comment]
@manjunathreddyr As this is part of our enterprise package, we cannot provide an example of a custom component like this. We recommend using our enterprise package and using the sketchpad component.

**Comment by 0liver** [comment]
Does the Enterprise package allow us to use the Sketchpad component with `formio.js`? How is the license managed there?

**Comment by wag110894** [comment]
You will need access to our Premium Components. Please contact sales@form.io for more information.

**Comment by 0liver** [comment]
I suggest closing this issue.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
