### ISSUE TITLE
Vertical Wizard pages

### ISSUE THREAD

**Issue by SumitRAgrawal** [formio/formio.js#3192]
Is it possible to render wizard  pages vertically instead horizontal pages ? If there are too many pages, vertical tabs seems a better alternative.

**Comment by learner291** [comment]
Yes, you can display wizard step names horizontally, you need to set this up in the templates.

```
    templates: {
      wizard: {
        form: `
          <div class="wizard-container">
          	{{ ctx.wizardHeader }}
            <div class="wizard-page-container">
              <div class="wizard-page" ref="{{ctx.wizardKey}}">
                {{ctx.components}}
              </div>
              {{ ctx.wizardNav }}
             </div>
          </div>
        `,
      },
    }
```

The fiddle is below.

https://jsfiddle.net/yLbr7hwa/1/

**Comment by SumitRAgrawal** [comment]
Thanks! @learner291  Will try this

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
