### ISSUE TITLE
Allow override of calculate value for date/time component does not work as expected

### ISSUE THREAD

**Issue by AmeeBhadania** [formio/formio.js#3196]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
 
- Formio.js version: v4.12.0-rc.9

## Steps to Reproduce
1.  Drag and drop a number component and a date/time component.
2.  In the date/time component's calculate value set 
     `value = moment().add(data.number, 'days');`
3. Set allow calculate value override option to true for date/time component
4. Go to the renderer and provide a value for the number component, say 2.

## Observations : 
The value is set correctly for the date/time component based on the value provided for the number field. 
But.. when we try to manually set the value for the date/time field, a calendar dropdown does open, but we are unable to select a value.

## Expected behavior
We should be able to set the value for the date/time field by selecting a value from the calendar dropdown.

## Example
Below is the json for form components: 

```js
"components": [
        {
            "label": "Number",
            "mask": false,
            "spellcheck": true,
            "tableView": false,
            "delimiter": false,
            "requireDecimal": false,
            "inputFormat": "plain",
            "key": "number",
            "type": "number",
            "input": true
        },
        {
            "label": "Date / Time",
            "tableView": false,
            "enableMinDateInput": false,
            "datePicker": {
                "disableWeekends": false,
                "disableWeekdays": false
            },
            "enableMaxDateInput": false,
            "calculateValue": "value = moment().add(data.number, 'days');",
            "allowCalculateOverride": true,
            "key": "dateTime",
            "type": "datetime",
            "input": true,
            "widget": {
                "type": "calendar",
                "displayInTimezone": "viewer",
                "locale": "en",
                "useLocaleSettings": false,
                "allowInput": true,
                "mode": "single",
                "enableTime": true,
                "noCalendar": false,
                "format": "yyyy-MM-dd hh:mm a",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disableWeekends": false,
                "disableWeekdays": false,
                "maxDate": null
            }
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by travist** [comment]
I don't believe this is an issue. The issue is that the Calculation is always changing (because the date time value is also always changing), so it is caught in a calculation loop. Does this work if you move the moment() calculation to the Custom Default Value instead?

**Comment by randallknutson** [comment]
The issue comes from the fact that every time the datetime is calculated the time has changes (new time!) thus it always looks like it changed. You can try adding setTime() to midnight or something like that so every millisecond the time doesn't change on the calculated value.

**Comment by AmeeBhadania** [comment]
Thank you for the inputs.
Will set the value as  `value = moment().startOf('day').add(data.number,'days')`
