### ISSUE TITLE
Ability to access Default Value from Create Form in Custom Default Value JS?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3201]
So from the examples, i created something like:

```js

Formio.createForm(document.getElementById('formio'), mySchema)
                    .then(function (form) {

                        form.submission = {
                            data: {...}
                        }
...
```

If is possible to inject a default submission object (for field pre-population) before the "customDefaultValue" JS executes?  The use case is the ability to inject some values into submission, and then let the form modify those values.

When i do the above, the customDefaultValue executes and the "value" argument is `""`

**Comment by StephenOTT** [comment]
ya it seems the validations of customDefaultValue run before the .then().

It also appears the validations are executed twice?

**Comment by randallknutson** [comment]
This is correct. We do not know if a submission is going to be assigned when the form is created. The createForm function creates the form, sets the defaults and checks the validations. Then the submission is set which sets the values and re-checks the validations.

**Comment by StephenOTT** [comment]
Is it possible to know which validation check in the lifecycle is occurring within a customDefautValue check?

**Comment by StephenOTT** [comment]
Or is it possible to inject additional variables into the customDefaultValue execution? (through browser side config? with the default lib)

**Comment by travist** [comment]
You can always implement the "component" hook to set the customDefaultValue.

```js
Formio.createForm(document.getElementById('formio'), mySchema, {
  hooks: {
    component: function() {
      this.component.customDefaultValue = 'value = "wooohooo!"';
    }
  }
})
```

**Comment by StephenOTT** [comment]
Use case is more to be able to write some default value js based on existing data in the scope.  

Is there somewhere I could dumb variables in a object that would be easily accessible within the Custom Default Value Js ?

**Comment by randallknutson** [comment]
Config is a good place for this. It can be added at form.config and when using our server you can configure the Public Configuration and enable it to be set on forms. Once set up it is available in default values as the config variable. This will map to whatever is set in form.config, either by our server or manually.

**Comment by StephenOTT** [comment]
@randallknutson  thanks will try that out!
