### ISSUE TITLE
Using field logic uncheck clears the list but does not allow for individual select later

### ISSUE THREAD

**Issue by arjuna71** [formio/formio.js#3205]
Hi,

I am using formio.js in my project for on-the-fly controls using predefined field definitions in JSON generated from form.io builder.

- "Select All" as one of the option and on click should select all of the dropdown list
- "Unselect All" for all selected values that should be unselected from dropdown list
- Should also allow to select individual options from the list as the select component allows for multi-select.

OR

Checkbox next to select component that i have tried using field logic but has issue after unselect where in it is not allowing for individual selection from the list.

[select all using field logic.txt](https://github.com/formio/formio.js/files/5168868/select.all.using.field.logic.txt)

Can you please suggest if this can be achieved using the formio.js OR can i inject my own custom JS code?
Please provide samples of either or both of the options.

Thanks in advance.

regards,
Mallikarjuna

**Comment by randallknutson** [comment]
You might have better luck with a button with custom logic that sets the values of each checkbox. Logic runs continuously in the background and won't allow customizations to the checking.

**Comment by arjuna71** [comment]
> You might have better luck with a button with custom logic that sets the values of each checkbox. Logic runs continuously in the background and won't allow customizations to the checking.

I got the solution by adding a custom value to the check-box and used it in field logic.  This worked for me.
Thank you for the suggestion.
