### ISSUE TITLE
BootStrap.css conflicts with the project

### ISSUE THREAD

**Issue by maryamgharibi** [formio/formio.js#3210]
We are using formio.js in our form, but bootstrap.min.css causes some conflicts with existing css. So ,we wrapped bootstrap.scss and add a new namespace(iso-bootstrap), then used new iso-bootstrap link in the form, and also used the new class inside builder and formio divs, but this approach causes another issues with  formio components  styles and functionality. Is there any way for resolving such conflicts?

![image](https://user-images.githubusercontent.com/12015368/91912376-5aefdb00-ecf6-11ea-957e-c1bc33769004.png)

**Comment by randallknutson** [comment]
You are on the right track. If you recompile the SCSS with the iso-bootstrap as the top level item, like this:

```
.iso-bootstrap {
  // import all bootstrap and formio.js css here.
}
```

This will cause all the CSS to only apply within a div that has the class of iso-bootstrap. You can also create your own custom templates that conform to your CSS if you don't want to use bootstrap. We have pre-defined templates for bootstrap3, bootstrap4, semantic, bulma, uswds and ukgov. You can create your own custom one with this information: https://github.com/formio/formio.js/wiki/Templates-API

**Comment by VikkiAlenn** [comment]
We're currently addressing a backlog of GitHub issues.
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
