### ISSUE TITLE
[BUG] Error when trying to edit custom EditGrid in FormioBuilder

### ISSUE THREAD

**Issue by pmanu93** [formio/formio.js#3211]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:4.12.0-rc.9
- Frontend framework: plain js
- Browser: Firefox
- Browser version:  81.0b4 (64-bit) 

## Steps to Reproduce
1. Create a custom EditGrid Component (code below)
2. Create a form with the component above and a textfield called `a`;
3. Add `value = Promise.resolve([{a:'foo'}, {a:'bar'}])` to editGrid calculateValue;

I created a custom `calculateComponentValue` which handles promise based values.

That implementation can be found here: 
https://gist.github.com/pmanu93/6cd65dcae33522fdd037afcd424c15eb#file-custom-utils-ts

Custom edit grid is there as well: 
https://gist.github.com/pmanu93/6cd65dcae33522fdd037afcd424c15eb#file-custom-edit-grid-ts

As you can see, the component is an extension of formio's editGrid being the `calculateComponentValue` the only difference.

## Expected behavior
 - [x] Show data resolved by promise;
 - [ ] Possibility to open `editGrid` edit dialog after setting promise based calculateValue;

## Observed behavior
After setting promise based calculateValue, the data is shown as it should... but after that I cannot edit the component anymore because when I try to open the edit dialog, an error ocurrs and sometimes an infinite loop.

## Example
Video showing the problem:
https://drive.google.com/file/d/1TauFwGybe8Ae6EmGRuVzLZY576aPcdu4/view?usp=sharing

---
**EDIT**
After some debugging, I saw that when opening the edit dialog, formio `editGrid` uses **Component** `calculateComponentValue` instead the one implemented in the custom component!
I've extended the `select` component the same way as the above, and in that case it works as expected.

**Comment by wag110894** [comment]
Hello @pmanu93,

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please let me know if you are interested and we can provide you with information on our Support Packages.
