### ISSUE TITLE
[BUG] Hidden labels shown in FormioBuilder

### ISSUE THREAD

**Issue by niklas1893** [formio/formio.js#3212]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.12.0-rc.12
- Frontend framework: plain js
- Browser: Google Chrome
- Browser version: 84.0.4147.125

## Steps to Reproduce
1.  Create a component 
2.  Select hide label

## Expected behavior
In previous versions the label was hidden
## Observed behavior
Label is shown in FormBuilder, in FormRenderer it is still hidden

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
