### ISSUE TITLE
How to use the public configuration (config.json)

### ISSUE THREAD

**Issue by besmiralia** [formio/formio.js#3215]
Hi
Is there any example on how to make use of the public configuration(`/config.json`). How do I use the `testKey` in a form?
Normally for any submission data I would go by `{{data.testKey}}`. Is there anything similar for config keys?

I am talking about this part:
```
{
	"_id": "...",
	"type": "project",
	"tag": "1.0.1",
	"owner": "...",
	"plan": "basic",
	"framework": "javascript",
	"title": "test",
	"description": "test",
	"config": {
		"testKey": "testValue"
	}
}

```

**Comment by randallknutson** [comment]
This is added to all the places you either use javascript or interpolate values. For example, you can set the select url to "{{config.testKey}}/mytest" and it will replace the value from the form config. In javascript you can use config.testKey in your calculations.

**Comment by besmiralia** [comment]
Thank you @randallknutson 
I'll give it a try

**Comment by besmiralia** [comment]
Hi @randallknutson 
What would be the simplest way to change the `config` dynamically, ex. `Formio.setConfig(configObj);`

**Comment by randallknutson** [comment]
The config is part of the form object (form.config) so you can change it by listening to the formLoad event and edit the form.

**Comment by besmiralia** [comment]
That is very helpful, thank you!
