### ISSUE TITLE
[HELP] Datagrid component with Button, custom logic capabilities

### ISSUE THREAD

**Issue by MalkyTheKid** [formio/formio.js#3216]
Currently we have a button on our Data Grid:
![image](https://user-images.githubusercontent.com/15683727/92060395-a55a7180-ed61-11ea-8da5-7c2a61da91aa.png)

Inside it we have the following custom button logic:
![image](https://user-images.githubusercontent.com/15683727/92060475-d76bd380-ed61-11ea-9ad5-a405abe674bc.png)

Using custom logic...can we:
 1. Also go to the next step by custom logic?
 2. How do we submit? (Let's say in a scenario we want to skip the rest of the steps)
 3. can we make an async API call, then store the response in these buttons?

**Comment by randallknutson** [comment]
The instance variable has basically full access to do stuff on the form. For example, you can access the form with instance.root and then call executeSubmit on it. You can't really store data in a button but you can find another component (instance.root.getComponent('key')) and setValue in that component.

**Comment by MalkyTheKid** [comment]
Thanks Randall,

so instance.root.executeSubmit() submits the form.

In a multistep form, how do we go to next step? how do we return to previous?

**Comment by MalkyTheKid** [comment]
Actually, figured it out here...
https://github.com/formio/formio.js/blob/master/src/Wizard.js#L218

Above extends Webform, 

saw implementation for 'prevPage()' and 'nextPage()' that worked.

I think we can also script api calls within these buttons then, and then store a response on a component like you suggest here. Will try...

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
