### ISSUE TITLE
Custom value in checkbox is not working

### ISSUE THREAD

**Issue by nandhagit** [formio/formio.js#3223]
I am trying to check the checkbox or un-check it based on some value from the API. I have tried using for eg: customDefaultValue = "value = 1>2", but it did not work. Also tried calculated value. Could someone help

**Comment by randallknutson** [comment]
You should be able to do this with calculated value

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
