### ISSUE TITLE
[BUG] Timezone features in DateTime Component all ignored.

### ISSUE THREAD

**Issue by blochealth** [formio/formio.js#3225]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [] Local deployment
    - Version: Application: 7.0.40, Renderer: 4.11.3
- Formio.js version: Application: 7.0.40, Renderer: 4.11.3
- Frontend framework: Tested broken in Angular and in Base Form.io portal host
- Browser: Tested broken in Chrome and firefox  
- Browser version: Any

## Steps to Reproduce
1.  On the portal, Create a new form with 4 DateTime components
2. Set the Timezone setting on each component to a different value: UTC, Submission, Viewer, Location (and use a different location from your local). 
3. Set the values on the 2nd, 3rd, 4th components with "value= data.dateTime" so that all components are pulling from 1 data value.
3. Save your form.
4. Create a new submission. 
5. View your submission. 

## Expected behavior
Date times for Location and UTC should show time in specified location time and in UTC. 

## Observed behavior
All date times will be displayed with the same value: the Viewer timezone. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Sample form JSON for testing it yourself: 
https://blochealth.form.io/timezonedebug

**Comment by AnthonyPhan** [comment]
I'm also experience this issue. Any updates on this issue? were you able to find a work around?

**Comment by wag110894** [comment]
@AnthonyPhan What version of formio.js version are you using?

**Comment by AnthonyPhan** [comment]
Hi @wag110894,

I am using Renderer v4.14.1-rc.7

I have also raise a similar issue with a sandbox example to demonstrate in the issue below. 

https://github.com/formio/formio.js/issues/4549

**Comment by AnthonyPhan** [comment]
@wag110894 just wondering if you were able to replicate her issue in both bug reports?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
