### ISSUE TITLE
[BUG] Shortcut key is not working for the first time after form loading

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#3226]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: v4.12.0-rc.13
- Formio.js version:v4.12.0-rc.13
- Frontend framework:VanillaJS
- Browser:Chrome
- Browser version:84.0.4147.135

## Steps to Reproduce
1. Create a form with checkbox ( and select some shortcut key)
2. After rendering this form try using the shortcut key with keyboard

## Expected behavior
Shortcut key should work even for first time after initial load of the form

## Observed behavior
Shortcut key is not working for the first time after initial load of the form.
It is working after manual selecting the checkbox. 

## Guess
Is it because of no focus on the component?

## Example
[https://jsfiddle.net/sriram/b4nw5rd7/](https://jsfiddle.net/sriram/b4nw5rd7/)

**Comment by wag110894** [comment]
Hello @sriram275,

We are able to replicate this issue and have added this to our backlog. We welcome a PR or have a process to expedite the issue if you are interested. For reference, the ticket number is FJS-1216. 

We will let you know once this issue has been resolved.

**Comment by wag110894** [comment]
Hello @sriram275,

This issue has been resolved in FJS 4.12.1.
