### ISSUE TITLE
Drag and dropping fields not working in pdf builder for Chrome on MAC.[BUG] 

### ISSUE THREAD

**Issue by mujtaba1016** [formio/formio.js#3228]
Hello! Anyone know why https://formio.github.io/formio.js/app/builder PDF builder does not work?
Drag and dropping fields not working
this is only happening for Chrome on MAC.

**Comment by doublegrey** [comment]
Confirmed, PDF builder is broken, however there are no errors or warnings in console.
![formio_pdf (1)](https://user-images.githubusercontent.com/25150523/94001186-d77b5400-fda0-11ea-9b9a-4e020a66ff2d.gif)

**Comment by erichunt94** [comment]
Are there any updates on this bug? We are running into this with the PDF Builder as well. Only for Chrome on Mac.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
