### ISSUE TITLE
Form io override drag drop

### ISSUE THREAD

**Issue by cskr11** [formio/formio.js#3229]
Hi, We want to override the existing drag and drop framework of formio. Instead of having set of controls from builder to drag drop, the server will provide us the form control data (search and select) in some form. We will drag drop the data provided from the server which will contain what is the control to be rendered. On drop, the appropriate form io control is required to be rendered based on the type provided by the selection (server data). The idea is the server will provide the control data in some form and drag and drop of that data, the formio builder will be shown the appropriate control. Please let me know if this is possible in the current formio.

**Comment by randallknutson** [comment]
I'm not sure exactly what you are looking to do. Our platform depends on JSON definitions for forms. The form builder fundamentally builds this JSON which is then rendered by the form renderer. Right now there is no easy way to break the form JSON into pieces and serve it from the server. You could look into different ways of modifying the process though.

**Comment by cskr11** [comment]
@randallknutson Thank you for your reply. 

In the current formio, we drag and drop control like textfield, select etc to create the form. 
In our case, we don't know the type of the control yet and that will be provided by the server (based on the search results).
When a selection happens from the search results, we want to dynamically create the textfield, select etc. We would like to know if there are any API available to intercept and consume the drag drop event to dynamically create the control on the form at that point. Hope what I provided here is clear.

**Comment by randallknutson** [comment]
You're probably going to have to look at the code for the drag and drop and see what is possible. The code for it is here: https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js
