### ISSUE TITLE
Using kickbox

### ISSUE THREAD

**Issue by niklas1893** [formio/formio.js#3230]
Hey,

I´d like to use kickbox email validation in formio.js email components.
![image](https://user-images.githubusercontent.com/60409711/92581980-ad01a500-f290-11ea-965e-1fd05e11d25d.png)

On the form.io website you can set an api-key, but how can i set it in formio.js?

https://help.form.io/integrations/email/

**Comment by randallknutson** [comment]
This requires our enterprise server with projects to enable.
