### ISSUE TITLE
[BUG] formiojs folder had node_modules inside it

### ISSUE THREAD

**Issue by Ankita-G-Mudgal** [formio/formio.js#3238]
## Environment

while installing formiojs through npm I could see node_modules folder inside formiojs folder. Also, it does not install all the dependencies like dragula.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.11.3
- Frontend framework: webcomponents
- Browser: All
- Browser version:

## Expected behavior
it should contain only dist folder

## Observed behavior
it has node_modules and all other components folder

## Example
![image](https://user-images.githubusercontent.com/35997906/92761973-cea57e00-f3af-11ea-850c-cebfeaefab77.png)

```

**Comment by randallknutson** [comment]
This is handled by npm. If there is a different version than the containing app it will install a different version in the nested node_modules folder. Otherwise it is in the root node_modules.

**Comment by Ankita-G-Mudgal** [comment]
Can you explain it? Different version as in

**Comment by randallknutson** [comment]
This is how npm works, not form.io.
