### ISSUE TITLE
[BUG] Regular expression validation - error messages does not show field & pattern

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#3243]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ ] Local deployment
    - Version: N/A
- Formio.js version: 4.11.3
- Frontend framework: JS
- Browser: Chrome/Firefox/IE
- Browser version:

## Steps to Reproduce
1. Navigate to form https://codepen.io/duongph/pen/KKVdLxe
2. Type "abcd"
3. Read error message

## Expected behavior
Error message should be "Regex /abc/ does not match the pattern abc."

## Observed behavior
Error message is "does not match the pattern ."

## Example
https://codepen.io/duongph/pen/KKVdLxe

**Comment by wag110894** [comment]
@phucduong86 

We are able to replicate this issue and have added this to our backlog. As you know, we welcome a PR or have a process to expedite the issue if you are interested. For reference, the ticket number is FJS-1217. 

We will let you know once this issue has been resolved.
