### ISSUE TITLE
When have to redraw?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3247]
I have something like this:

```js
Formio.createForm(document.getElementById(formioDivId), mySchema)
                        .then(function (form) {

                            setDefaultValues(form.submission.data)
...
```

The setDefaultValues(..) updates the submission.data object.  But the form does not redraw.  I was expecting it to detect the change?  

if i call form.redraw() the value appears.  

Is this expected?

Thanks!

**Comment by StephenOTT** [comment]
It seems it will only detect updates at the form.submission level.

**Comment by randallknutson** [comment]
If you update the submission object directly then it won't detect it. You have to do 
form.submission = {
 data: setDefaultValues(form.submission.data)
}

This will trigger the update since the submission object is new and reassigned.

**Comment by StephenOTT** [comment]
thank you
