### ISSUE TITLE
Datagrid Removing Values

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#325]
I'm having some problems with the Datagrid component. I have some logic associated with the DG to calculate some scores on top of the DG information.
Every time I add a new row the previous row information gets removed

You can check the form JSON here: https://uiorzjzflxyccmo.form.io/animalproductionpractices
Please answer Yes to the first question and you will see the table with the problem

CodePen: https://codepen.io/cabrerabywaters/pen/zppZPw

Thanks a lot!

**Comment by cabrerabywaters** [comment]
Just to narrow a little bit more the search. I found out that the problem was in the conditional rendering inside each of the elements of the Datagrid.
They all depend on a value from outside of the grid to check if it should or not show.

I removed the conditional an it seems to work...but of course the current behavior is not right, as in Form.io displays correctly.

**Comment by jhen1422** [comment]
This issue has been resolved
