### ISSUE TITLE
[BUG] Day component cannot be localized

### ISSUE THREAD

**Issue by mohlendo** [formio/formio.js#3251]
## Environment
 "angular-formio": "^4.9.6",

## Steps to Reproduce
Provide a custom translation.json file with the following keys set:

```
    "month": "Monat",
    "day": "Tag",
    "year": "Jahr",
    "january": "Januar",
    "february": "Februar",
    "march": "März",
    "april": "April",
    "may": "Mai",
    "june": "Juni",
    "july": "Juli",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "Dezember",
```

## Expected behavior
Labels of Fields "Day", "Month" and "Year" are localized.

## Observed behavior
All other localization work - so I suspect that it is a problem with the "Day" Komponent.

**Comment by travist** [comment]
I am looking at the templates and it looks like it is translating.

https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/day/form.ejs#L5

Try adding the keys as ```Day```, ```Month```, and ```Year``` with the uppercase first character.

**Comment by mohlendo** [comment]
@travist  I have tried that - but had no success. I have created an unit test in this branch which shows, that the Day component does not apply the translation: https://github.com/mohlendo/formio.js/tree/day-i18n

**Comment by randallknutson** [comment]
The day component seems to be translating. You can see this by going to http://formio.github.io/formio.js/app/sandbox and loading the sandbox 5f622112896ba92c87a91916 (You may need to reload the page after loading). All the strings seem so translate just fine.

**Comment by mohlendo** [comment]
@randallknutson  thanks for your help! Yes, I see that it works in the sandbox. But I am a little lost why it is not working for me. I have adapted my Unit test - with all variations of where to put the 'Day' key and it is still not working. 
Also in my app with angular-formio it is still not working. Do you have any idea what I am doing wrong?

**Comment by mohlendo** [comment]
Arg - it was an error with the setup of my angular app. The translation file was not loaded correctly.

**Comment by e-gauthier** [comment]
> I am looking at the templates and it looks like it is translating.
> 
> https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/day/form.ejs#L5
> 
> Try adding the keys as `Day`, `Month`, and `Year` with the uppercase first character.

@travist 
I know the bug is closed but I have to mention that.

Formio provide camelCase label  :
...
"month": "Month",
"day": "Day",
"year": "Year"
...

The link you provide sure translate the label of the component but not the specified labels Day, Month and Year.

The translation look for {{ctx.t('Day')}}, {{ctx.t('Month')}} and {{ctx.t('Year')}}.  

It's PascalCase,  the translation didn't occurs.

Is it something easy to fix?
