### ISSUE TITLE
[BUG] Some classname are currently hardcoded

### ISSUE THREAD

**Issue by svenvandescheur** [formio/formio.js#3253]
Some classnames (used for styling components) are currently hardcoded. This makes styling forms more difficult, especially when dealing with different naming conventions like BEM.

Soms classnames can be overridden on some way, others are deeply nested in methods.

A possible solution is to have:

- An inventory of classnames which can be customized.
- An overridable method (either via an extend or `Object.defineProperty`) that implements the logic of adding the class. 

This allows for:

- Custom classes by customizing the inventory.
- Altering classes to match a naming convention by overriding the method used to actually place the class names.

**Comment by randallknutson** [comment]
We definitely don't want to have any hard coded class names but probably do still have some. We have a method that each framework template should have to swap classes. https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/cssClasses.js

If there is a place where a class is hard coded, we should at least pass it though the css class transform.

**Comment by svenvandescheur** [comment]
Thanks for your reply, how would this work exactly? I tried adding a "transform" property to my template library and I expect every class to be transformed to "foo" (for now).

```js
const OFLibrary = {
    component: {form: component},
    field: {form: field},
    label: {form: label},
    message: {form: message},

    button: {form: button},

    input: {form: text},
    multipleMasksInput: {form: multipleMasksInput},

    checkbox: {form: checkbox},
    radio: {form: radio},

    transform: (type, text) => {
        console.log("transform", type, text);
        return "foo";
    }
};

Templates.current = OFLibrary;
```

I'm expecting to see at least a message in my console regarding the transform and having all my classnames transformed to "foo".  But unfortunately nothing like this happens. Am I incorrectly defining my template?

**Comment by randallknutson** [comment]
The transform function should work. 
https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L743-L745

However, the class needs to be passed through it like this:
https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L1534

If the class is not passed through the transform then it won't change.

If the class is in a template, you should just override the template and change it to whatever you want.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
