### ISSUE TITLE
[QUESTION] Manipulate response of URL for Select component?

### ISSUE THREAD

**Issue by pocketcap** [formio/formio.js#3262]
I am trying to call an endpoint to get list of options for Select component like below:

```
[
   {
      "label":"Test1",
      "value":"TEST1     "
   },
   {
      "label":"Test2",
      "value":"TEST2    "
   }
]
```

As you noticed, the value contains spaces at the end, is there any way to get them removed? I tried to change them in selectOptions and defaultDownloadedResources of Select component, but it doesn't help. Because of those spaces, Select component has issue to match value to label as the saved value of Select component doesn't contain spaces at the end.
Any help would be appreciated.
Thanks.

**Comment by wag110894** [comment]
@pocketcap, You can remove the spaces inside of the builder. It will save your data correctly if you get rid of the spaces.

**Comment by pocketcap** [comment]
@wag110894 could you please provide more details? Did you mean I can remove spaces somewhere in this page when I choose "URL" as Data Source Type?
![image](https://user-images.githubusercontent.com/1475774/93372586-1306a300-f822-11ea-88ba-3072046f7476.png)

**Comment by wag110894** [comment]
@pocketcap, Could you provide the link to the data source URL that you are using for this form?

**Comment by pocketcap** [comment]
> @pocketcap, Could you provide the link to the data source URL that you are using for this form?

Yes, I could. With link as date source URL, I am able to get list of values for drop down when I launch the form, but they would contain spaces.

**Comment by wag110894** [comment]
@pocketcap Do you have access to the URL and able to take out the spaces from the values?

**Comment by pocketcap** [comment]
> @pocketcap Do you have access to the URL and able to take out the spaces from the values?

Yes, I do have access to URL and can take out the spaces there. But I am just wondering if FormIO provides any data manipulation for the values of Select component.

**Comment by wag110894** [comment]
@pocketcap Not when the select component is set to URL.

**Comment by pocketcap** [comment]
@wag110894  understood. Thanks~

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
