### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by muster-mark** [formio/formio.js#3263]
Would it be possible to change the markup for checkboxes to allow adding custom styles for them?

Currently the mark up is like:

```
<label for="elvxgql-teaching_staff" class="form-check-label label-position-right">
      
      <input id="elvxgql-teaching_staff" value="teaching_staff" class="form-check-input" type="checkbox" name="data[roles][]" ref="input" style="width: 20px;height: 20px;" lang="en">
      
      <span>Teaching staff</span>
      
    </label>
```

With the input in the label it is not possible to style the input. Putting the label after the input would allow this.

**Comment by randallknutson** [comment]
You can already modify the output of each template by using our template system. You can get more information on it here: https://github.com/formio/formio.js/wiki/Templates-API

You can then create your own templates to move the elements around, add your own, or do whatever you want with it.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
