### ISSUE TITLE
[BUG] Builder: Nested Form configuration does not allow a custom form name/ID value

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3264]
When you build a form with a nested form, the nested form component does not allow for a custom value to be provided.  It only works with the drop drown list.  A custom value should be allowed.

Thanks!

**Comment by wag110894** [comment]
@StephenOTT, can you provide a JSFiddle of what you are seeing?

**Comment by StephenOTT** [comment]
<img width="1121" alt="Screen Shot 2020-09-16 at 2 36 34 PM" src="https://user-images.githubusercontent.com/1994838/93379659-23bc1680-f82c-11ea-8d7e-abdd7964c775.png">

**Comment by randallknutson** [comment]
How would you see this working? Our select component doesn't have the ability to add custom values. Would this be a url to the form definition or something?

**Comment by StephenOTT** [comment]
Most basic would just for setting the `form` property in the json.  So you basically can set a "custom" form id.  Let the person who is using that interpret it at as see fit.

A more advanced scenario may be a specific URL or maybe even the form schema json object?

The scenario I am looking at is where you can define some custom IDs which will be processed when the parent form is loaded, and the nested form schemas will be gathered by another thread and injected into the parent form.

**Comment by travist** [comment]
The form component already supports a ```src``` property that will render the subform using the API endpoint of that form. I think to support this we would just need to add that as a configuration in the edit form (which is not complicated). Alternatively, you could just edit the JSON directly on that component and add it.

**Comment by StephenOTT** [comment]
@travist is the Src prop tied to a specific API request/response format?

**Comment by StephenOTT** [comment]
@travist additional point about the current configuration of nested forms is the src property cannot be set if you cannot select from the drop down.  In the current builder UI you are basically forced to select from the dropdown if you want to save the component.

**Comment by randallknutson** [comment]
Have you tried the editJSON button directly? That may work although it is not a good solution for end users.

**Comment by StephenOTT** [comment]
The problem is you cannot do the initial save of the component.  So you cannot use the "edit Json" button.  The workaround is to find a sample of the json, and then use a "custom component" instance... (which is even worse for end users :) )

**Comment by randallknutson** [comment]
Yup. I'm trying to picture how the UI for this should work. Would there be a way to switch to a textfield or something?

**Comment by StephenOTT** [comment]
as @travist mentioned, if you already support a "src" prop, then if there was a requirement for either a url/src field or a selection from the drop down that would be an easy compromise.

Though i am still unclear on:
>is the Src prop tied to a specific API request/response format?

If custom json is being provided for a parent form, can custom json be provided for nested forms?

**Comment by StephenOTT** [comment]
@travist how do you use the `src` property?

I am trying to trial with https://formio.github.io/formio.js/app/builder, but i cannot seem to get the src prop to be read.

**Comment by randallknutson** [comment]
This is the setting that controls the form: https://github.com/formio/formio.js/blob/master/src/components/form/editForm/Form.edit.form.js#L2-L21

**Comment by StephenOTT** [comment]
@randallknutson should this configuration be possible through the UI?
https://github.com/formio/formio.js/blob/master/src/components/form/fixtures/comp2.js

If i try here, it gets stripped https://formio.github.io/formio.js/app/builder

**Comment by travist** [comment]
Yes, we should add this as a configurable option, although it concerns me that it is getting stripped away within JSON editor. That would require separate investigation.

**Comment by StephenOTT** [comment]
From some usage testing, It would be good if a custom url could be provided.  At the moment it appears it uses the project base url.  Would be great maybe if it reused the same sort of logic as the Dropdown lists: where you can define a url, headers, etc.

**Comment by wag110894** [comment]
@StephenOTT, 

We would welcome a PR or would love to come up with some sort of solution for a fee. Please contact support@form.io if you are interested in paying for this feature.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
