### ISSUE TITLE
[HELP] How to change the language of the builder (i18n)

### ISSUE THREAD

**Issue by detygon** [formio/formio.js#3266]
Hi, thanks for this great library. I would like to use it in my project but I can't find anywhere in the docs how to change the language of the builder itself / the whole UI. Can someone help me ?

**Comment by randallknutson** [comment]
Should be the same process as with the form. Here is an example. http://formio.github.io/formio.js/app/examples/language.html

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
