### ISSUE TITLE
Builder: support "Paste Into" option for layout components

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3268]
When working in the builder and you copy a form component, if the form is large, it is difficult to navigate the page.
Would be great if the copy/paste buttons supported "Paste Into" so you can copy a component and paste it into a layout (such as moving a `fieldset` into a `container`.  Currently if you do a Copy and "Paste Below" it pastes under the desired layout, rather than inside.

Would also be great if there was a Tree view of the hierarchy of components, and allow movement of the components from the hierarchy/tree view.  This would enable easier reformatting of a large form.

Thanks!

**Comment by randallknutson** [comment]
This would be great. I've experienced this myself recently. This should be fairly straightforward to develop. Is it something you could either do a PR for or sponsor?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
