### ISSUE TITLE
Builder: Add key and/or component type info on hover over component next to "edit, move, copy, paste, etc" buttons

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3270]
When dealing with complex forms with layouts, containers, etc, there can be many components that stack up and it can be difficult to select the specific component / select the edit button/gear icon, or any icon in that space.

Furthermore it is difficult to know which component you are about to edit.  You currently have to click the edit button and figure out if it is the correct component.

it would be great if there was some additional textual data shown when hovering over a component such as the component's key and the type of component.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
