### ISSUE TITLE
Feature Req: Provide explanation set that Container nests the submission json

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3272]
Users often do not realize or remember that container component will nest their json within the submission.  Would be great to have a additional explanation text on the component's edit ui as it is fairly different than other component's usage.

Thanks!

**Comment by randallknutson** [comment]
That's fair. Is that something you could provide? This would be as easy as adding an html component in the editform here https://github.com/formio/formio.js/blob/master/src/components/container/editForm/Container.edit.display.js

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
