### ISSUE TITLE
[BUG] FJS-1250 Calendar picker set wrong date after blur event

### ISSUE THREAD

**Issue by elibus** [formio/formio.js#3277]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12.0-rc.14+
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Go here: https://jsfiddle.net/w4fcjpm7/
2. Select a date
3. Click on the text component
4. Check the date is now wrong

## Expected behavior
Date is set correctly
## Observed behavior
Date is updated with a wrong value

## Example
https://jsfiddle.net/w4fcjpm7/

This seems to be introduced by this: https://github.com/formio/formio.js/pull/3227/files
`altFormat` is not matching the format of `input`

**Comment by wag110894** [comment]
Hello @elibus, We are aware of the issue and have added this back to our developer to work on. 

The ticket number is FJS-1103. We will let you know once this is resolved.

**Comment by elibus** [comment]
#3237

**Comment by jhen1422** [comment]
@elibus 
This should be resolved on 4.12.0-rc19 of formio.js

**Comment by elibus** [comment]
@jhen1422 it does not look to me like it's solved. Have a try here: https://jsfiddle.net/619qyebf/1
Pick any date on any datetime component and click on any other field

**Comment by jhen1422** [comment]
@elibus 
You're completely right. Looks like the issue is only occurring when the date is reformatted. I've escalated this issue as a high priority ticket for us. Will let you know as soon as we have a resolution.

Please note that textfield set to calendar widget seems to be working correctly. I'm not sure if that helps your use case

**Comment by elibus** [comment]
Fixed with #3237
