### ISSUE TITLE
[BUG] Menu carousel stop working after search/filtering fields

### ISSUE THREAD

**Issue by Quartzbell** [formio/formio.js#3278]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment

## Steps to Reproduce
1.  Go here : http://formio.github.io/formio.js/app/sandbox
2.  In the search field, type anything.
3.  Clear search field.
4. Carousel will stop working.

## Expected behavior
Menu carousel working after menu filter is cleared.

**Comment by Ankita-G-Mudgal** [comment]
I am facing the same issue with version: 4.12.0

**Comment by jhen1422** [comment]
Thank you for the report. Looks like this is isolated to the builder outside of the form.io portal. We have added a ticket to our backlog and will be fixed in a future 4.12.x build. This issue will be notified when a resolution is in place. Thank you!

**Comment by jhen1422** [comment]
Should be resolved in 4.12.2 version of formio.js

**Comment by Anandks1993** [comment]
Same issue with latest version too.

formiojs: 4.14.3
@formio/react: 5.2.0

Issue replicated in codesandbox: https://codesandbox.io/s/aged-butterfly-j6v2kq?file=/src/App.js

Let me know if I need to do something to fix this.

**Comment by e-gauthier** [comment]
Same issue.  After investigation, it's appear that doign a search render a template "builderSidebarGroup" that break the reference of sidebar-group.

Initialisation of refs actions : https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L584-L611
Render of a new template that break the refs. : https://github.com/formio/formio.js/blob/fd55c909f9b47f7c7ba523c15cbbe0efb6f5f3bb/src/WebformBuilder.js#L701-L703
