### ISSUE TITLE
BUG: Field that is validate.Required = true and persistent = false allows omission of field

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3281]
Trying to get clarification if this is intended or a bug:

```json
{
    "display": "form",
    "components": [
        {
            "label": "F1",
            "tableView": true,
            "validate": {
                "required": true
            },
            "key": "f1",
            "type": "textfield",
            "input": true
        },
        {
            "label": "F2",
            "tableView": true,
            "persistent": false,
            "validate": {
                "required": true
            },
            "key": "f2",
            "type": "textfield",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}

```

and then submit the following:

```json
{
        "data": {
            "f1": "1",
            "f3": "2"
        }
}
```

I would expect that `f3` is removed as it is a "extra field", and it would throw a validation error as `f2` is missing from the submission and it is marked as a required field.  But the above submission is accepted and only `f1` is returned.

I would expect f2 to be available for server side validations even though it will not be persisted.

**Comment by randallknutson** [comment]
You scenarios are correct. 

If a component is required but not persistent it should throw an error if it is not included on each submission. What version are you checking this for? In formio v1.x it has a custom validator and in 2.x it has isomorphic validator and is using formio.js on the server side. If this is a bug on the older validator could you check it on the newer validator?

**Comment by StephenOTT** [comment]
@randallknutson I have tested with 1.90.9.  I will have to look how to adapt the code for 2.x
https://github.com/StephenOTT/Form-Validation-Server/blob/master/app/src/validator.js

I had issues before using 2.x

**Comment by StephenOTT** [comment]
@randallknutson doing a quick test against 2.0 RC14 it still appears to be a issue/bug

**Comment by StephenOTT** [comment]
@randallknutson were you able to confirm it as a bug?

**Comment by randallknutson** [comment]
I believe this is a bug. Let me get it tested internally to verify.

**Comment by wag110894** [comment]
Hello @StephenOTT,

We have created a ticket and have added this to our backlog. We welcome a PR or have a process to expedite this issue if you are interested. We estimate that this will take 4 hours to resolve this issue.

For reference, the ticket number is FOR-2781.  Please let us know if you are interested in expediting and we can get the process started.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
