### ISSUE TITLE
[BUG] Property names should not be allowed to start with a number

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3283]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] https://formio.github.io/formio.js/app/builder
- Browser: Any

## Steps to Reproduce
1. Drag and drop a TextField
2. Type label: 1. bla bla bla
3. API > property name is `1blablabla`

## Expected behavior
Maybe escape the name start from number

## Observed behavior
property name is `1blablabla`,
it can't used as javascript variable
because it's can't start from number
I know user can rename the variable
but maybe escape it will better?

![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3283_1.png?raw=true)
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3283_2.png?raw=true)
![](https://github.com/bleungAtGTI/misc/blob/master/formio_issue_3283_3.png?raw=true)

**Comment by randallknutson** [comment]
We should do a better job filtering the property name so it can't start with a number.

**Comment by wag110894** [comment]
@bleungAtGTI For reference, the ticket number for this is FJS-1261.

Have a great day!

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
