### ISSUE TITLE
[BUG] Not able to set attributes for Tags component using HTML Attributes under Layout tab

### ISSUE THREAD

**Issue by AmeeBhadania** [formio/formio.js#3285]
## Environment

- Hosting type
  - [x] Form.io
- Formio.js version: v4.12.0-rc.16

## Steps to Reproduce
1. Add a Tags component
2. Go to edit -> Layout -> HTML Attributes
3. Add an attribute 'style' with the value 'background: blue' and Save

## Expected behavior
The background for the tags input must be changed to blue.

## Observed behavior
The background for the tags input is still grey

```js
 "components": [
        {
            "label": "Tags",
            "tableView": false,
            "key": "tags",
            "attributes": {
                "style": "background: blue"
            },
            "type": "tags",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
```

** When the same steps are followed for a textfield component, the background is changed to blue.

**Comment by wag110894** [comment]
Hello @AmeeBhadania 

We are able to replicate this issue on our side and have added it to our backlog. We welcome a pull request and also have a process to expedite this issue if you need it soon. For reference, the ticket number is FJS-1260.

Please let us know if you are interested in expediting by contacting support@form.io.

Thank you.

**Comment by wag110894** [comment]
Hello @AmeeBhadania, after discussing this further with our developers, this is not an issue as the HTML Attributes are not able to be styled for visuals.

**Comment by Rishikap123** [comment]
Hello wag110894,

Can you please elaborate it .. why HTML Attributes are not able to be styled for visuals?
