### ISSUE TITLE
QUESTION- Is there a way to customize the accordion. left-sidebar of formio

### ISSUE THREAD

**Issue by Ankita-G-Mudgal** [formio/formio.js#3292]
How can I add search field inside components list using form builder.

like in this example https://formio.github.io/formio.js/app/examples/custombuilder.html search field is at the top. I want it to be inside userfields. Can this be possible.

Help is very much appreciated

**Comment by randallknutson** [comment]
I don't think we have anything like that built in currently but would be open to adding it.

**Comment by Ankita-G-Mudgal** [comment]
thanks for the response..

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
