### ISSUE TITLE
[BUG] removeComponent() does not work for nested Panels

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3293]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.10.5
- Frontend framework: Javascript
- Browser: Mozilla Firefox
- Browser version: 81.0 64-bit

## Steps to Reproduce
1. Create a form with a Panel nested inside of another Panel
2. Call removeComponent on the child panel

## Expected behavior
The child panel should be completly removed leaving only the parent Panel
## Observed behavior
The contents of the child component are removed but the child panel is still part of the form and the child panel label is visible
## Example
This is the form:
![theForm](https://user-images.githubusercontent.com/44456650/94056329-025eab80-fd93-11ea-8429-dc498cf83558.PNG)

The form renders correctly
![render](https://user-images.githubusercontent.com/44456650/94056404-1bfff300-fd93-11ea-9373-f44904208074.PNG)

When I add the code to remove the child component I get this:
![render2](https://user-images.githubusercontent.com/44456650/94056453-2a4e0f00-fd93-11ea-8c82-72364fdc9e26.PNG)

```
`window.onload = function () {
  let form = Formio.createForm(
    document.getElementById("formio"),
    "https://xxxxxxxxxxx.form.io/mytest"
  );

  form.then((form) => {
    FormioUtils.eachComponent(
      form.components,
      (component) => {
        if (component.path === "childPanel") {
          form.removeComponent(component);
        }
      },
      true
    );
    form.triggerRedraw();
  });
};
`
```

**Comment by jhen1422** [comment]
@YioMtz31 
Thank you for the feedback. We've been working on a formio.js 4.12.0 build that we are close to releasing. Can you please check if latest version of 4.12.x resolves this issue?

**Comment by YioMtz31** [comment]
@jhen1422
Tested with https://unpkg.com/formiojs@4.12.0/dist/formio.full.min.js and got the same result.
As a workaround I added a well component inside the parent panel, moved the child panel inside the well and then call removeComponent on the well.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
