### ISSUE TITLE
Is it possible to remove specific fields from the tabs when using a custom form builder

### ISSUE THREAD

**Issue by rustymcg9000** [formio/formio.js#3294]
I would like to remove certain fields within the "Display" tab, as they are just not useful for our clients i.e. Hidden, Hide Label, Show Word Count etc. ??

I've seen how you can hide entire tabs such as:

```
Formio.builder(document.getElementById('builder'), {}, {
                builder: {
                    data: false,
                    premium: false,
                    layout: false
                },
                editForm: {
                    textfield: [{
                        key: 'api',
                        ignore: true
                    }, {
                        key: 'validation',
                        ignore: true
                    }, {
                        key: 'logic',
                        ignore: true
                    }, {
                        key: 'layout',
                        ignore: true
                    }]
                }
            });
```

But not how to hide individual fields with tabs.

Thanks

**Comment by Ankita-G-Mudgal** [comment]
You can do it by adding this to editForm

 `{
        key: 'display',
        label: 'DISPLAY',
        components: [
          { key: 'placeholder', ignore: true },
          { key: 'label', ignore: true },
          { key: 'labelPosition', ignore: true },
          { key: 'description', ignore: true },
      ]
}`

Formio.Components.components.textfield.editForm() print this in console you will get all the keys present in display tab.

**Comment by SalTor** [comment]
Like Ankita said, you have to do that on the components property of the tab. Here's another way you can do it
```javascript
import ComponentEditAPI from 'formiojs/components/_classes/component/editForm/Component.edit.api'
export default function (...extend) {
    return nestedComponentForm([
        {
             key: 'api',
             components: ComponentEditAPI.map(component => {
                 if (component.key === 'key') {
                     component.ignored = true
                     return component
                 }
                 return component
             })
        }
    ])
}
```

**Comment by rustymcg9000** [comment]
Thanks both Ankita and SalTor, appreciate the help.
