### ISSUE TITLE
update form builder custom options

### ISSUE THREAD

**Issue by cskr11** [formio/formio.js#3295]
Hi, We are in need of updating the existing components already rendered. Say if the below are the formbuilder options being set at the initial render time to have components firstName and lastName textfields. 

"builder":{"custom":{"title":"User Fields","components":{"first Name":{"title":"First Name","key":"firstName","icon":"terminal","schema":{"label":"First Name","type":"textfield","key":"firstName","input":true}},"lastName":{"title":"Last Name","key":"lastName","icon":"terminal","schema":{"label":"Last Name","type":"textfield","key":"lastName","input":true}}}},"layout":false}

![image](https://user-images.githubusercontent.com/38510627/94096488-36b58480-fdf2-11ea-8be8-0b2aadc801ec.png)

We need to dynamically update the builder components to a new set of values, for example like the below (to have only middleName textfield)

"builder":{"basic":false,"advanced":false,"data":false,"premium":false,"custom":{"title":"User Fields","components":{,"middleName":{"title":"Middle Name","key":"middleName","icon":"terminal","schema":{"label":"Middle Name","type":"middleName","key":"lastName","input":true}}}},"layout":false}

I am setting the below values and expecting the component to be updated like the below shown image
![image](https://user-images.githubusercontent.com/38510627/94096566-6a90aa00-fdf2-11ea-98f1-62d204a1a42a.png)

formioBuilder.options.builder.custom.components = {middleName: {
        title: 'Middle Name',
        key: 'middleName',
        icon: 'terminal',
        schema: {
          label: 'Middle Name',
          type: 'textfield',
          key: 'middleName',
          input: true,
        },
      }}
formioBuilder.build()
This doesnt seem to take effect. 

What is the current way of updating the components at the runtime?

**Comment by SalTor** [comment]
```javascript
Formio.use({
    options: {
        builder: {
            builder: {
                custom: {
                    title: 'Custom Components',
                    weight: 1000,
                    default: true,
                    components: {
                        middleName: {
                            title: 'Middle Name',
                            key: 'middleName',
                            icon: 'terminal',
                            schema: {
                                label: 'Middle Name',
                                type: 'textfield',
                                key: 'middleName',
                                input: true,
                            },
                        },
                    },
                },
            },
        },
    },
})
```

**Comment by cskr11** [comment]
But this we would be able to do only the initial time. Looks like we can accomplish this like the below. 

`this.formBuilder = new FormBuilder(this.formCreator, {}, options);
      this.formBuilder
        .build()  .then((webformBuilder) => {
//value is WebformBuilder promise
//addBuilderGroup or updateBuilderGroup based on the existence of the group
webformBuilder.addBuilderGroup("testGroup", {
            title: "variables",
            key: "variables",
            weight: 10,
            subgroups: [],
            componentOrder: [],
            components: {//components required to render},
          });
}`

**Comment by SalTor** [comment]
Good to know!
