### ISSUE TITLE
[BUG] Select Field: Default value is not retained when multiple values option and clear value on refresh option is set to true.

### ISSUE THREAD

**Issue by kunaljain611** [formio/formio.js#3298]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment

## Steps to Reproduce
1. Drag and drop Select Field and any other component. Ex: text field.
2. For Select Field, go to the Data tab:
- set multiple values option to true.
- set a default value 
- for refresh options on, add the Textfield component and set a clear value on the refresh option to true.
3. Go to Renders as a Form
4. Set any other value for a select field other than default and enter some data in the text field.

## Expected behavior
The select field must set back to the default value when the component gets refreshed.

## Observed behavior
All the data in the select field is getting cleared.

**Comment by wag110894** [comment]
@kunaljain611 can you provide a JSFiddle of the issue taking place?
