### ISSUE TITLE
[BUG] Date\time->Modal Edit: In Firefox , after selecting a value, its shown as Invalid Date

### ISSUE THREAD

**Issue by kunaljain611** [formio/formio.js#3299]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Browser: Fierfox

## Steps to Reproduce
1. Drag and drop a Date\Time with the following format yyyy-MM-dd HH:mm a
 and check Display -> Modal Edit options

## Expected behavior
It should show the date\time.
The same steps on Chrome and Edge browsers work properly.

## Observed behavior
For Date\Time, after selecting a value, it is shown as invalid

## Example
Find the attached screenshot for the same.
<img width="618" alt="ScreenShot" src="https://user-images.githubusercontent.com/20204757/94149099-18ed2b80-fe95-11ea-8d2d-baad747ec5d3.PNG">

**Comment by jhen1422** [comment]
Thank you for the report. We are aware of this issue and currently working on a fix. We will update this ticket when a resolution is in place. Thanks!
