### ISSUE TITLE
Wizard - hidden pages do not show submission values

### ISSUE THREAD

**Issue by ssdhaliwal** [formio/formio.js#330]
When display type of "wizard" is used- and values are set using submission, the hidden pages when made visible by pressing the "next" button do not show the values in submission only the first page works fine.

**Comment by travist** [comment]
Will you create a JSFiddle of your problem. You can fork it from https://jsfiddle.net/travistidwell/ko4vna57/.

I am looking @ http://formio.github.io/formio.js/app/examples/submissions.html and it seems to be working.

**Comment by ssdhaliwal** [comment]
Thanks - i tested it, everything is working; think there is conflict between something I am importing...  Really appreciate you looking at it.
