### ISSUE TITLE
[BUG] Value, few properties shown under Logic -> Action are irrelevant for Layout components

### ISSUE THREAD

**Issue by AmeeBhadania** [formio/formio.js#3312]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: Renderer v4.12.1-rc.4

## Steps to Reproduce
1. Add a layout component, say well
2. Go to Edit -> Logic -> Add Logic -> Add Action
3. Under the Action -> Type, we see 3 options in the dropdown; Property, Value and Merge Component Schema.

I believe Value is not applicable for Layout components. Component properties like Prefix, Suffix are applicable for Text Field,Text Area, Number, Password, Email, URL, Phone Number, Currency and not other components. 

Do correct me if I am wrong. 

## Expected behavior
Value option under Logic -> Action, component properties under Logic -> Action -> Property should be shown only if relevant.

## Observed behavior
Value option under Logic -> Action, component properties under Logic -> Action -> Property are shown for Layout components even if they are irrelevant.

## What is the use of component property Title under Logic -> Action -> Property? 
I don't see any change in the UI when the below steps are followed.

1. Add a number component
2. Add a TextField component. Add a simple logic that is triggered when the component Number has the value 1. In the Action -> Type -> Property, set Component property Title to 'abc'.
3. In the renderer, type 1 in the Number field. 

No change in the UI is observed.

**Comment by randallknutson** [comment]
You are correct that having a Value option does not make sense for layout components. Right now there is no easy way to customize the Action options per component type so these are all the same. In the 5.x branch we are revamping the whole way this works so it may be fixed there.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
