### ISSUE TITLE
How to override default validation messages in angular or through formio portal?

### ISSUE THREAD

**Issue by neharagh** [formio/formio.js#3313]
Hi Team,
I'm using angular-formio package in my project and wanted to know how and where should I override the custom validation messages. I'm creating forms through formio portal and with the help of the above package, integrating it to angular.

Html looks something like this
`<formio [form]="Form" (submit)="formSubmit($event)" (customEvent)="formCustomEvent($event)"></formio>`

In formio documentation there's a solution on how to override default error messages when we're creating forms in javascript.
`Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/translations', {
readOnly: false,
language: 'en',
i18n: {
  'en': {
    Submit: 'Complete'
  }
}`

But I can't do it this way since I'm not creating forms in angular but with their portal. Could anyone tell me if there's any simple way which I completely missed to override the default messages from portal or in angular? I could modify these messages from the package itself (updating i18n.js file in formiojs) but I don't want to change anything from the package files since that isn't a good way.

Thank you in advance.

**Comment by randallknutson** [comment]
The error messages can be overridden using the "Custom Error Message" option. If you are on the old angular1 renderer and builder it may not show up but if you use the latest formio.js it is there.

**Comment by neharagh** [comment]
@randallknutson I'm sorry but I didn't get where to use Custom Error Message option. I'm using angular-formio package version 4.9.6.
I want to over write default of error key in the file -- i18n.js(node_modules\formiojs\i18n.js)
`resources: {
    en: {  error: 'Please fix the following errors before submitting.'}
}`
I couldn't find this option in components from formio portal. Should I edit the json of a particular component from portal?
![image](https://user-images.githubusercontent.com/32258171/94780018-6ca3cb80-03e5-11eb-8c69-bb8fdf99752e.png)
![image](https://user-images.githubusercontent.com/32258171/94781338-4f6ffc80-03e7-11eb-87ff-5a29c74ff57c.png)

If yes, then could you please share the key for overriding the error message? I've tried assigning value to  "errorLabel" and that doesn't work. 

Could you provide an example or share link for documentation on how to use Custom Error Message option in formio portal?
Thank you again.

**Comment by randallknutson** [comment]
The Custom Error Message option is on the Validations tab in the component settings. 

<img width="780" alt="Form_IO" src="https://user-images.githubusercontent.com/246735/94823163-2a6c9100-03c9-11eb-8f6c-eea3955488c1.png">

If you are looking to translate the error messages, you should use the i18n support to translate it which we do not have a UI on portal to enter.
http://formio.github.io/formio.js/app/examples/language.html

**Comment by Sahil-Sayyed** [comment]
I am using Angular Material and registered a custom component which is a text field, i want formio to validate that field based on custom validation and my custom message. 
How can i achieve this?

**Comment by paulmartinjoy** [comment]
I would like to change the error message that is displayed in situations where we click the submit button, but some compulsory fields are empty. The message that I receive by default is "Please check the form and correct all errors before submitting the form". I want to use instead a custom message. Is there a way to achieve this ?

**Comment by wag110894** [comment]
@Sahil-Sayyed @paulmartinjoy Could you open a new ticket for your questions?

Thank you.

**Comment by Sahil-Sayyed** [comment]
Created issue #4129

**Comment by fvillarrealp** [comment]
Hi.
Excuse me form.io team, but I have the same @paulmartinjoy issue. I don't know how to set the error and success messages inside the form.io platform, and not using form.io js in my application. In adition, Im not only looking for setting the deffault error message, but to modiffy it deppending of the mistake (for example either is unique or another). I undersatand the custom error messages of each field, but I mean the main one.
Thank you for your help.
