### ISSUE TITLE
Question: How do I render the current user's email as a default value of a textfield

### ISSUE THREAD

**Issue by besmiralia** [formio/formio.js#3319]

**Comment by randallknutson** [comment]
In the Custom Default Value option in the textfield you can grab the email from wherever it is (possibly in Formio.getUser()) and then set it as the value.

**Comment by besmiralia** [comment]
Thank you @randallknutson I was trying the regular `defaultValue` and it wasn't interpolating it.
I'll give it a try with 'customDefaultValue`
