### ISSUE TITLE
EditGrid not storing Data

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#333]
Hello again!
I'm starting to work with the EditGrid component (really nice by the way). But I found an important issue. Even when the behavior is correct when we are editing, the component itself is not showing in the Data array, so it does not get stored.
I realized that the fields inside of the Edit grid get stored as if they were a regular field and not inside an array (as the Datagrid). 

Best regards!

**Comment by jhen1422** [comment]
This issue has been resolved
