### ISSUE TITLE
Modify component value externally

### ISSUE THREAD

**Issue by usselite** [formio/formio.js#3333]
I am attempting to modify my form.io component value with some **external javascript**.

```
var id = Object.keys(Formio.forms)[0];
FormioUtils.getComponent(Formio.forms[id].originalComponents, "sampleComponent").value = "just a sample"
```

What I expected is that my 'sampleComponent' would get the value "just a sample". I am aware though that orginalComponents might be wrong, but 'Formio.forms[id].components' does not expose the ability to set a value. 

I am attempting to set this once the form has already rendered. I have no clue on how to proceed from here.

**Comment by randallknutson** [comment]
Try this:
```
FormioUtils.getComponent(Formio.forms[id].originalComponents, "sampleComponent").setValue("just a sample");
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
