### ISSUE TITLE
[BUG] DATE field keeps defaulting or reverting back to year 2025

### ISSUE THREAD

**Issue by crivera305** [formio/formio.js#3334]
## Environment
Please provide as many details as you can: chrome, firefox, safaro

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.0
- Frontend framework: Bootstrap
- Browser: Chrome
- Browser version:85.0.4183.121

## Steps to Reproduce
1. Goto https://jsfiddle.net/mr24hour/fg7vzj41/1/
2. Change the date value of ID Expiration Date
3. Click off the component - on blur - the date gets changes to year 2025

## Expected behavior
if i choose a date the date i chose should be displayed - even after clicking on other components

## Observed behavior
when i chose a date i am shown the date until i click off the component then it changes the year to 2025

## Example
print screen of the field on load - https://prnt.sc/utsxs0
print screen of the field after change and blue - https://prnt.sc/utsxwh

For the form please grab the script from https://jsfiddle.net/mr24hour/fg7vzj41/1/

**Comment by wag110894** [comment]
Hello @crivera305, 

Thanks for reaching out. We are aware of the issue and this issue has been resolved using formio.js version 4.12.1-rc.8. I tested the JSFiddle you provided by changing the formio.full.min.css to https://unpkg.com/formiojs@4.12.1-rc.8/dist/formio.full.min.css as well as the formio.full.min.js https://unpkg.com/formiojs@4.12.1-rc.8/dist/formio.full.min.js and the issue does not occur anymore.

**Comment by hisuwh** [comment]
@wag110894 this is a critical issue having major impact on systems.  When can we expect 4.12.1 to go RTM?  And do you know what version this was introduced in so we can downgrade?

**Comment by hisuwh** [comment]
It seems to be 4.12.0 - pinning to 4.11.3 fixed this for me

**Comment by wag110894** [comment]
We are still working on getting 4.12.1 to a stable release. We will let you know once this 4.12.1 is marked as stable.

**Comment by yavisht** [comment]
Locking version to `4.13.13` for now fixes this for now

Using this via vue-formio so had to add this via resolutions
`
"resolutions": {
    "formiojs": "4.13.13"
  }
  `
  Will test to see if this is fixed in newer versions.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
