### ISSUE TITLE
[Question] How to set TextArea width lager in Datagrid

### ISSUE THREAD

**Issue by bleungAtGTI** [formio/formio.js#3337]
- Hosting type: https://formio.github.io/formio.js/app/builder
- Browser: Any

## Steps to Reproduce
1. Drag and drop Datagrid
2. Drag and drop Textfield into Datagrid
3. Drag and drop TextArea (Editor = ACE) into Datagrid

## Question
How to set TextArea width lager?

## Example
![image](https://user-images.githubusercontent.com/51389769/95186286-6b670a00-07fc-11eb-8fea-609a352c260f.png)

PS: How to remove [Bug] tag?

**Comment by wag110894** [comment]
Hello @bleungAtGTI, 

You can add a columns component inside of the Data Grid so you can set the width of the Text Area.  I hope that this helps.

**Comment by bleungAtGTI** [comment]
Thanks a lot.
