### ISSUE TITLE
Content Component is Adding additional characters! [BUG] 

### ISSUE THREAD

**Issue by mhamadhdeib** [formio/formio.js#3339]
Bug: 
Whenever I press on space when editing content component, several A acute appears instead.

Most recent version of the Library is installed and referenced on my local machine. 
This error is in displayed in the most recent version of chrome.

Steps :
Form Builder -> Layout Section -> Content Component

![image](https://user-images.githubusercontent.com/48261240/95264917-dafaea80-0838-11eb-84ea-e245e900f27a.png)

**Comment by wag110894** [comment]
Hello @mhamadhdeib, Can you provide a JSFiddle of this issue taking place as well as the version of formio.js that you are using?

**Comment by mhamadhdeib** [comment]
@wag110894  Unfortunately I cannot provide a json fiddle, however the version is the latest one downloadable as I tried re-downloading the source code and still get this error.

**Comment by wag110894** [comment]
We are not seeing this on the latest version of our formio.js. We have tested this issue on the https://formio.github.io/formio.js/app/builder, which is running on 4.12.1.rc.9. Can you confirm what version you are using?

**Comment by besmiralia** [comment]
This looks like a keyboard issue to me.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
