### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by mhamadhdeib** [formio/formio.js#3344]
I need to get a direct list of all the input elements from a builder.schema object, without any object that is non-related to user-input such as columns, tabs or text
So assuming I have something like this:

{"components":
[{"label":"Columns","columns":[{"components":[{"label":"First name","key":"middleName","type":"textfield",
    "input":"true","tableView":"true","hideOnChildrenHidden":"false"}],"width":"6","offset":"0","push":"0","pull":"0","size":"md"}
    ,{"components":[{"label":"Last name","key":"lastName","type":"textfield","input":"true","tableView":"true","hideOnChildrenHidden":"false"}]
    ,"width":"6","offset":"0","push":"0","pull":"0","size":"md"}],"type":"columns","input":"false","key":"columns","tableView":"false"}]}

What I need is a version of the json that only keeps user-input related objects:, and would ideally return something like this
{"components":[
    {"label":"First name","key":"firstName","type":"textfield","input":"true","tableView":"true"},
    {"label":"Last name","key":"lastName","type":"textfield","input":"true","tableView":"true"}
]}

**Comment by randallknutson** [comment]
The easiest way to do this is to iterate over the form components using "eachComponent" and check the type. This will traverse layout components correctly. For example:

```
Formio.utils.eachComponent(form.components, function(component) {
  if (component.type === 'textfield') {
    // do something with the textfields.
  }
});
```

**Comment by mhamadhdeib** [comment]
@randallknutson Thank you for the help
