### ISSUE TITLE
[BUG] jsonLogic library is unmaintained with a high security alert

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#3351]
## Environment
Please provide as many details as you can:

https://npmjs.com/advisories/1542
https://github.com/jwadhams/json-logic-js/issues/86

## Steps to Reproduce
1. `npm i formiojs` will show alert

Not sure what workarounds there might be.

**Comment by randallknutson** [comment]
Thanks Paul. We need to figure out something on this as we can't leave json logic where it is right now.

**Comment by wag110894** [comment]
Thank you Paul for bringing this to our attention. We have created ticket FJS-1321. We will let you know once this issue has been resolved.

**Comment by paulfalgout** [comment]
Looks like the latest release resolves this. FWIW installing Snyk on this repo would help find these auto-magically and for free.
