### ISSUE TITLE
Customization of alert box shown on validation error

### ISSUE THREAD

**Issue by sisselfladby** [formio/formio.js#3353]
We started using the default alert box that lists the validation errors, but we have some problems with it.

1. The aria-label “Click to navigate to the field with following error.” is not possible to translate using the i18n and language props on the webforms, which is a problem for us since we use Norwegian everywhere else.

2. We would like the li-elements to have anchor links, and we would like to customize the appearance of the box, and we were thinking that this is a good candidate for the template system?

**Comment by randallknutson** [comment]
Yes. You should be able to use templating to change the html rendered in the alerts. The default template is here: https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/message/form.ejs. However, the container is one of the very few items that is rendered the old way and can be found here: https://github.com/formio/formio.js/blob/master/src/Webform.js#L1082-L1092

This should really be converted to a template.

**Comment by it-vegard** [comment]
I don't think the message template is used here. That one renders a div, which is the error message below the input field, wheras the alert box renders `li` elements.

The error messages we want to change is created using JS in [line 1188-1209 in Webform.js](https://github.com/formio/formio.js/blob/a21d8498c5e66e7a0400e590188cf886d86b377c/src/Webform.js#L1188).

Having the whole alert (created in the setAlert function) converted to a template would help a lot!

**Comment by wag110894** [comment]
Hello @it-vegard,

We think that this would be a great feature to add to our platform. We estimate that it would take 6 hours to add this functionality. 

Please let us know if you are interested by contacting support@form.io, and we can get the process started. For reference, the Ticket number for this Feature Request is FJS-1342.

**Comment by Christian-Haslund** [comment]
Does this estimate includes everything that needs to be done, e.g. testing?

**Comment by wag110894** [comment]
Hello @Christian-Haslund,

Yes, the estimate does include everything that needs to be done.

**Comment by Christian-Haslund** [comment]
I suppose we will get a chance to review the change before publication?

**Comment by wag110894** [comment]
We can let you know which version that this feature would be added so you can pull it in prior to us pushing to production so you can test on your side.

**Comment by Christian-Haslund** [comment]
Hi
Suppose Form.io has received payment for NA's contract (Crayon) broker for impementation of this feature by now.

Can you give us a status report / estimated time for completion?

Regards
Christian Haslund
