### ISSUE TITLE
Web components inside Formio

### ISSUE THREAD

**Issue by cskr11** [formio/formio.js#3360]
Hi, We are in need to put web components (example: https://github.com/mdn/web-components-examples) inside Formio. This can be accomplished by creating a custom component which contains this web component if I am not wrong. Do we have any documentation by which we can accomplish this functionality (how to register webcomponent inside Formio etc)?

**Comment by wag110894** [comment]
Hello @cskr11,

Here you go: https://formio.github.io/formio.js/app/examples/customcomponent.html

I hope that this helps.

**Comment by DamianSoltys** [comment]
Did someone have a solution for that?.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
