### ISSUE TITLE
Question: How to skip required but leave other validations

### ISSUE THREAD

**Issue by besmiralia** [formio/formio.js#3367]
I would like to pass a flag to a form to skip validating for required fields but leave the rest of validations in place.
Is there any way I can do this?

**Comment by randallknutson** [comment]
If you listen on the "formLoad" event you can get the form definition, make the modifications you are looking for and then set the required to true or false. This does make it static at load time.

If you need dynamically required, check out the "Logic" tab for each component. You can set the Trigger condition and the in Action, set the property of "Required" to true or false.

**Comment by besmiralia** [comment]
Hi @randallknutson 
Thank you for your suggestion. The `formLoad` approach works well, but it still renders the fields as mandatory (red asterisk) although they are not required.

I was looking at FormUtils and noticed this method `applyFormChanges`
Is there any example for it?

**Comment by travist** [comment]
This is still problematic because the server will still execute a "pristine" version of the form json that will make it so that you cannot submit the data to the server. I believe the best course of action for this is to introduce some new hooks into the form modules (since those also get executed on the server) and then allow you to "alter" the form schema from that hook.

**Comment by besmiralia** [comment]
Agreed, there should be a way to change a component or refresh the whole form on demand, whether its a hook on before formLoad or an instance method to redraw a certain component or the entire form. Maybe there is something in place that I am not aware of. The builder does something similar when editing a component.

**Comment by travist** [comment]
The builder places the renderer in "builder" mode which changes many behaviors throughout the renderer so I don't believe that is a viable option. I do think that what you are asking for is not able to be resolved without modifying the renderer. You could make a change to the ```checkComponentValidity``` method to force the behavior to something different.
