### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by buseodaci** [formio/formio.js#3369]
Hello, i want to  save simple js that like sum of 2 values from 2 input and use this saved js for other components whenever i want. I want to see all saved js  under 'Javascript'.   Is there any way that i can ?

**Comment by randallknutson** [comment]
You should use a Hidden component with a calculated value. This will store the value in the submission with the property name of the Hidden component which can then be used anywhere else in the form.

**Comment by buseodaci** [comment]
Sorry for my late reply but i want to use that js for my other forms that i will create. How can it be possible ?

**Comment by travist** [comment]
You can do this with the form module feature where you can introduce a "global" function that can be used within the evalContext. Here is how it works.

```
{
  options: {
    form: {
      evalContext: {
        validatePhone: function(input) {
          return input.match(/^[2-9]\d{2}-\d{3}-\d{4}$/);
        }
      }
    }
  }
}
```

And then you can use the following in your evaluation code.

```js
valid = validatePhone(input) ? true : 'Phone number is invalid';
```

**Comment by buseodaci** [comment]
@travist Sorry im new to Formio which place to define that code for creating global function ? Also how can i see all global functions that i willl be create ? Can i show them inside dropdown ?

**Comment by travist** [comment]
This could be added when you embed the form like so.

```js
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
 evalContext: {
   validatePhone: function(input) {
      return input.match(/^[2-9]\d{2}-\d{3}-\d{4}$/);
    }
  }
});
```

**Comment by buseodaci** [comment]
can i use it in Angular ?

**Comment by travist** [comment]
<formio ... [formioOptions]="{
 evalContext: {
   validatePhone: function(input) {
      return input.match(/^[2-9]\d{2}-\d{3}-\d{4}$/);
    }
  }
}"></formio>

**Comment by buseodaci** [comment]
I use function like u : 

`                    <formio [form]="formSrc" (submit)="onSubmit($event)" formioOptions="evalContext: {validatePhone: function (input) {return input.match(/^[2-9]\d{2}-\d{3}-\d{4}$/);}"></formio>
`


When i create form, i define Custom Validation for phone number component like up:

`valid = validatePhone(input) ? true : 'Phone number is invalid';`

It gives error:

 An error occured within custom function for phoneNumber ReferenceError: validatePhone is not defined
    at eval (eval at evaluator (webpack-internal:///./node_modules/formiojs/utils/Evaluator.js), <anonymous>:3:1)
    at Object.evaluate (webpack-internal:///./node_modules/formiojs/utils/Evaluator.js:136)
    at Object.evaluate (webpack-internal:///./node_modules/formiojs/utils/utils.js:304)
    at PhoneNumberComponent.evaluate (webpack-internal:///./node_modules/formiojs/Element.js:668)
    at ValidationChecker.check (webpack-internal:///./node_modules/formiojs/validator/Validator.js:736)
    at ValidationChecker.checkValidator (webpack-internal:///./node_modules/formiojs/validator/Validator.js:921)
    at ValidationChecker.validate (webpack-internal:///./node_modules/formiojs/validator/Validator.js:954)
    at eval (webpack-internal:///./node_modules/formiojs/validator/Validator.js:1037)
    at arrayMap (webpack-internal:///./node_modules/formiojs/node_modules/lodash/lodash.js:639)
    at Function.map (webpack-internal:///./node_modules/formiojs/node_modules/lodash/lodash.js:9580)

**Comment by travist** [comment]
Your code is wrong.  Copy what I did above and it should work. formioOptions does not look like a valid json object.

**Comment by buseodaci** [comment]
When i use that way in html it gives error like this;

![image](https://user-images.githubusercontent.com/25960852/98330101-beee9280-200a-11eb-864a-a799f80d0c65.png)


I also try formioOptions:FormioOptions in constructor like this;

![image](https://user-images.githubusercontent.com/25960852/98330979-aaab9500-200c-11eb-9abf-4556ed5c38e4.png)

**Comment by acordobamo** [comment]
Hello, I am interested in having a solution to this problem, since I am at the same point. I use react, and I need to pass global functions to be able to collect them in the components and to be able to do validations with these functions. How can I collect these functions in the form?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
