### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#337]
I'm trying to use the File upload component, but no matter what I use (Dropbox, S3, URL, Base64) I always get the same message when I try an upload "File Service not provided."
I did all the configuration for Dropbox and S3 at the project level, but nothing seems to work.

Any idea?

**Comment by travist** [comment]
I assume you are setting the form IS IN directly on the form

You need to set the form url of the form in order to upload so it can create a signed upload url. You can do this using...

```
Formio.createForm(....).then((form) => {
   form.url = '......';
});

**Comment by cabrerabywaters** [comment]
Thank you @travist 
That was it!

**Comment by cabrerabywaters** [comment]
OK, so at least now I can upload a file as Base64 and it gets stored in the submission. 
Now if I save that and I go again to "Edit" (load the previous submission) I can see the files in the array but the File component does not show them.

Is there another trick for that?

**Comment by StephenOTT** [comment]
@travist your comment should be a Help text in the Upload component:
https://github.com/formio/formio.js/issues/337#issuecomment-360161652

as this is a SUPER easily missed and a easy blocker to run into!

**Comment by StephenOTT** [comment]
@travist also what is used at the `form.url` value when you inject a form object instead of a url to a form?

**Comment by StephenOTT** [comment]
For Base64 we made some changes to support it in the File.js

On like 137 of File.js we changed:

```
get fileService() {
    return this.options.fileService || this.options.formio;
  }
```

to:
```
get fileService() {
  if (this.options.fileService) {
    return this.options.fileService;
  }
  if (this.options.formio) {
    return this.options.formio;
  }
  return new Formio();
}
```

and added at the top of File.js

```
import Formio from ‘../../formio.js’;
```

all as per recommendation from @travist 


But now we are seeing duplicate base64 values being stored.  Is this expected?


```json
{
    "somefile": [
        {
            "storage": "base64",
            "name": "screenshot-b08ad188-422e-40c2-9384-6a0655623684.png",
            "url": "data:image/png;base64,iV....",
            "size": 67380,
            "type": "image/png",
            "data": "iV....",
            "originalName": "Screen Shot 2018-01-26 at 2.50.43 PM.png"
        }
    ],
    "textArea": "",
    "submit": false
}
```

**Comment by travist** [comment]
Agreed this needs to be resolved. We will add it to the list of items to focus on next.

**Comment by StephenOTT** [comment]
@travist any progress on this?

**Comment by jhen1422** [comment]
@StephenOTT This was closed by mistake, reopening
