### ISSUE TITLE
[Date Field settings not displaying correctly after upgrade] 

### ISSUE THREAD

**Issue by srama2020** [formio/formio.js#3377]
Added details
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.0 and 4.7.8
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 86.0.4240.75

## Steps to Reproduce
1. With Version 4.7.8, Created a form with Date/Time component involving settings as below
<img width="573" alt="Screenshot 2020-10-15 at 5 07 01 PM" src="https://user-images.githubusercontent.com/72935791/96156412-f2a53380-0f08-11eb-9833-a47a7ff317a6.png">

2. Upgraded the form io version to 4.12.0.

3. Access the form created above and check the settings created on the Date component

## Expected behavior
Form should have similar settings as created
<img width="573" alt="Screenshot 2020-10-15 at 5 07 01 PM" src="https://user-images.githubusercontent.com/72935791/96156412-f2a53380-0f08-11eb-9833-a47a7ff317a6.png">

## Observed behavior
Settings were not displaying correctly on UI
<img width="568" alt="Screenshot 2020-10-15 at 5 17 28 PM" src="https://user-images.githubusercontent.com/72935791/96157575-61cf5780-0f0a-11eb-9e4a-f5e4cd06d9f8.png">
<img width="576" alt="Screenshot 2020-10-15 at 5 17 38 PM" src="https://user-images.githubusercontent.com/72935791/96157584-63008480-0f0a-11eb-9664-198dc1bef21f.png">

**Comment by wag110894** [comment]
Hello @srama2020,

Apologies on the late response. We are sorry that this occurred to you. Were you able to get this working again after the upgrade?

**Comment by srama2020** [comment]
Hi @wag110894 

Thanks for your response.

I am experiencing the above posted issues after formio version upgrade i did recently. it would be very appreciated if you can help me to fix those issues.

**Comment by wag110894** [comment]
Hello @srama2020,

Are you able to add the moment() into the Minimum date in the 4.12.0 version or is there an issue that it is not saving? Or is the issue that it did not save the settings when you updated from 4.7.8 to 4.12.0?

**Comment by srama2020** [comment]
it didn't save the settings on date field when i updated from 4.7.8 to 4.12.0.

**Comment by wag110894** [comment]
@srama2020, I understand that this is the issue that you are experiencing. Are you able to add the old settings back and confirm that it is working? We have created a ticket and have added it to our backlog so that this does not happen again. For reference, the ticket number is FJS-1418.

**Comment by srama2020** [comment]
@wag110894 , Yes, i can confirm that i am able to add old settings for Date field manually and they are working as expected.

Thank you for your response on this issue. Is there a way to check the status of these tickets?

**Comment by wag110894** [comment]
@srama2020, you can just post here on github asking for an update and we can provide you with one.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
