### ISSUE TITLE
choices.js is included from github instead of npm

### ISSUE THREAD

**Issue by gradorsys** [formio/formio.js#338]
I have a problem with the referenced package "choices.js".
As it is now referenced as github project.
The github project is as far as I can see an identical fork of the original "choices.js" npm package.

Our internal policy does not allow us to download npm dependencies from github.
What is the reason behind using the forked version?
Are there plans to use the original version in the future again? When will that be?

**Comment by PlaidTactician** [comment]
This is also an issue for us. Any plans?

**Comment by travist** [comment]
We did this because we implemented some fixes that did not get merged into choices. I will talk with the developer who did this and determine if we can revert back to the npm version of Choices since I would MUCH rather not be branched.

**Comment by travist** [comment]
This will be resolved with https://github.com/formio/formio.js/pull/347. Should be included in next release, but need to run some tests first.

**Comment by travist** [comment]
This is now resolved with the latest.
