### ISSUE TITLE
Reset on Panel component not resetting to default state

### ISSUE THREAD

**Issue by raghavendrav1210** [formio/formio.js#3383]
I have designed a form that has panel components and a button. 
Initially, the panel component is hidden but based on some selection from a drop-down I am showing the panel.
But, I have a reset button in the form which is clearing the data but not hiding the panel. 

How to hide the panel component on click of the reset button?

**Comment by wag110894** [comment]
Hello @raghavendrav1210, Thanks for reaching out! We are able to replicate this issue on our side. We have created a ticket and have added it to our backlog. For reference, the ticket number is FJS-1369.  We welcome a pull request or we have a process to expedite this issue if you are interested. 

Please let us know if you are interested in expediting and we can get the process started.

Have a great day!
