### ISSUE TITLE
Check validation without form instance

### ISSUE THREAD

**Issue by Narsciz** [formio/formio.js#3387]
Hi!
I would like to know if it's possible to check if a submission is valid with a given form without generating the form.

For the context, I have a nodejs backend, and an angular frontend. I have a submission coming from another application, and i need to check with the backend if the submission is valid with a given form in order to display the form in front end side if there is any correction to do.
I can't see any utils function to do this, have I missed it? Or maybe the form generation is mandatory.

Thanks for your time and sorry for my english.

Have a good day,
Olivier Montes

**Comment by randallknutson** [comment]
This is essentially what our server already does. We use a form instance to validate the form. While the class is instantiated, it is never rendered so it only exists as a javascript class on the server. See the code here: https://github.com/formio/formio/blob/master/src/resources/Validator.js#L51

**Comment by Narsciz** [comment]
Thanks for the answer!
