### ISSUE TITLE
[BUG] Formio.js sets Ace options incorrectly when ace is imported outside Formio.js

### ISSUE THREAD

**Issue by Sefriol** [formio/formio.js#3392]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.1.12
- Frontend framework: VueJS
- Browser: Chrome
- Browser version: Version 86.0.4240.75

## Steps to Reproduce
1.  Install Ace and Formio.js within webpack environment
2. Open FormEditor. Try to edit a button.
3. Error will appear where it tries to use HTML file as a mode file.

## Expected behavior
It should use `ace-builds/webpack-resolver`'s file path
## Observed behavior
It uses HTML file

## Conclusion and how to solve
I do not go deeply into what is causing the problem, or how to trigger it. I will go through your code and explain why this happens:

https://github.com/formio/formio.js/blob/38fc9c184f0785285e0a2abd86f5d143990fc810/src/components/_classes/component/Component.js#L2066
Here you try to set a settings object into the editor. Unfortunately this settings object also includes mode, which is in format `html`, `json`, `javascript` or so on.
This will work if you have a non-webpack environment. However in other cases, mode path needs to be defined similarly as in
https://github.com/formio/formio.js/blob/38fc9c184f0785285e0a2abd86f5d143990fc810/src/components/_classes/component/Component.js#L2071
For example `ace/mode/html`. Otherwise it will raise an error on line 2069, because it tries to use `html` as key for the mode instead of `ace/mode/html`. 

i.e It could be fixed something like this (Fast MVP):
```javascript
return Formio.requireLibrary('ace', 'ace', _.get(this.options, 'editors.ace.src', ACE_URL), true)
      .then((editor) => {
        editor = editor.edit(element);
        editor.removeAllListeners('change');
        const settingsObj = Object.assign({}, settings);
        settingsObj.mode = `ace/mode/${settings.mode}`
        editor.setOptions(settingsObj);
        editor.getSession().setMode(settingsObj.mode); //Most likely not needed
        editor.on('change', () => onChange(editor.getValue()));
        return editor;
      });
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
