### ISSUE TITLE
Advanced Logic, Actions, Set State False not displayed[BUG] 

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#3395]
- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: last
- Formio.js version: last
- Browser: Chrome
- Browser version: 85.0.4183.121

## Steps to Reproduce
1. Add action 
  type = Property
  Component Property = Disabled
 Set state = False
2. Save
3. Open and Edit Action

## Expected behavior
In field "Set state" value "False"
## Observed behavior
In field "Set state" value "" (Just visualization value). In schema value=false

**Comment by wag110894** [comment]
Hello @homashevchenko,

This is a known issue in our backlog. We will let you know once this issue is resolved. For reference, the ticket number is FJS-873. We will let you know once this issue has been resolved. 

Have a great day!

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
