### ISSUE TITLE
Possible to programmatically disable validation on a component?

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#3408]
I am conditionally hiding some components in our forms. This is working fine (via `removeComponent()`). However, if a removed component has either a custom validation rule OR is marked required, then that validation fails on submit, and prevents the form from being submitted.

Is there a way I can programmatically disable custom validation rules and "required" validation on a component before or while removing it, to prevent this from happening?

**Comment by travist** [comment]
Making a component conditionally hidden (with conditionals) also makes it conditionally required. Why does this not work for you?

**Comment by tnorthcutt** [comment]
@travist I think you're asking why we're removing components in our application code, instead of using conditionals in the form builder; is that right?

If so, the answer is that we have complex requirements for what parts of certain forms to display, based on things like user attributes, selections they've made earlier in our sign up flow, information received from third-party APIs, etc. So, that information isn't readily available in the form builder, as it's not things like "if user checked yes above, then don't show this field". We certainly do use some simpler conditionals and for those, we make use of conditionals inside the form builder, but other places that isn't a feasible option.

Does that answer your question?

**Comment by besmiralia** [comment]
This looks a lot like my question: [#3367](https://github.com/formio/formio.js/issues/3367)
Another cool feature would be if we had the capability in the builder to show/hide a field based on an event being emitted .

**Comment by travist** [comment]
It may be a little pre-mature to mention this, but it does sound like what you are asking for is the new "rules" engine that we created for the 5.x version of this renderer. You can take a look at it in the 5.x branch, but we are still a ways off of release for that version. The biggest new feature is a rules engine that allows you to achieve what you are asking for.

**Comment by tnorthcutt** [comment]
@travist Thanks, that sounds like something we'll look forward to.

In the meantime, is there a way to accomplish this on 4.x? Perhaps some way to set `required: false` on a component?

**Comment by travist** [comment]
You can use field logic to achieve this using the "Merge Component Schema" action. Let me know if that works for you since I have not had a chance to try myself.
