### ISSUE TITLE
Feature: Builder: Add ability to refresh API property / "key" property based on updated Label name field

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3421]
VERY often people will copy configurations of a field (via copy button), and then update the label, but they will forget to update the key/API property.

Would be great if there was a button and/or some logic that would update the `key` property / API property when updating the label.  

(would be great too if there was a minimal text view (like greyed text) next to or under/near the label to indicate that the API/`key` will have XYZ value based on the label.

The label + `key` are VERY VERY often the two most updated properties, and they currently are on different tabs so easy to miss!! 👍

**Comment by travist** [comment]
I agree I like this feature request. We will add it on our backlog, but welcome contributions from the community on this one.

**Comment by oliverbj** [comment]
What is the status of this request?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
