### ISSUE TITLE
[BUG] Date is displayed incorrectly within Edit Grid modal

### ISSUE THREAD

**Issue by ks-mkd** [formio/formio.js#3427]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.1-rc.18
- Frontend framework: VanillaJS
- Browser: Chrome
- Browser version:  86.0.4240.111

## Steps to Reproduce
1. Create a form with an Edit Grid containing a Calendar Picker
2. Set modal property of the Edit Grid to true
3. Set the format of the Calendar Picker to "yyyy-MM-dd"
4. Render the form with readOnly set to true
5. Open and close the modal for one of the entries
6. Reopen the same entry again

## Expected behavior
The date value/format should not change after having opened the modal once.

## Observed behavior
The month is reset to 01. E.g. the date 2020-10-25 will be shown as 2020-01-25.

## Example
https://jsfiddle.net/ksffm90/wyu3q1pv/20/

**Comment by wag110894** [comment]
Hello @ks-mkd,

Thank you for reaching out and providing a JSFiddle that we were able to replicate the issue on. We have created the ticket (FJS-1382).

We will let you know once this issue has been resolved. 

Thank you for reaching out!

**Comment by HCMF** [comment]
I have this issue as well

**Comment by wag110894** [comment]
This issue was resolved on 4.13.0.
