### ISSUE TITLE
Question: Conditionally rendering required fields in a Custom Component

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3429]
### Problem

Conditionally rendering fields in a form which are required

### Question

Is there a better way to do this as described below? Or a recommended way to do this?

### Constraint

Using a custom component rather than the form builder

### Solution

Store a form instance with the desired fields within a class property which is set when the Custom Component runs `init()`. Then during `attach()` render the form element onto the page. From here, in order to achieve required'ness we alter the `checkValidity()` if we're rendering the extra fields.

### Example

```jsx
class CustomComponent extends SomeFormioComponent {
    async init() {
        super.init()
		
        this.extraFields = await Formio.createForm(div, { components })
    }
	
    attach(element) {
        this.loadRefs(element, { extraFields: 'single' })
        super.attach(element)
		
        if (this.someConditionIsMet && this.refs.extraFields.innerHTML === '') {
            this.refs.extraFields.appendChild(this.extraFields.element)
        }

        this.addEventListener(nextBtn, 'click', () => {
            if (this.someConditionIsMet && !this.checkValidity()) {
                // trigger the showing of "fields are required"
                this.extraFields.submit().catch(() => {})
            }
        })
    }

    checkValidity() {
        if (this.someConditionIsMet) {
            return this.extraFields.checkValidity()
        }
        return true
    }
}
```

**Comment by travist** [comment]
What is the question?

**Comment by SalTor** [comment]
The question more succinctly would be: what's your recommended approach for conditionally rendering and requiring fields within a custom component?

**Comment by travist** [comment]
A custom component can extend "NestedComponent" where it can then include additional components that are within that component. Take a look at the Address component. I believe it does this.

https://github.com/formio/formio.js/blob/master/src/components/address/Address.js

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
