### ISSUE TITLE
How to show data from Db in multiselect

### ISSUE THREAD

**Issue by nexawo** [formio/formio.js#3430]
I am using formio multi select which is working fine for inserting and updating data but it doesn't show the saved value from Db.

**public class Students
{
public int? StudentId{get; set;}
public string StudentName{get; set;}
}

public readonly List<Students> studentDto**

I am showing the student name as a label and saving id in DB. In formio multi-select, I give property name studentDto when I submit the data I get data in this form 

**studentDto: {
0: {StudentId: 1, StudentName:"John"}
1: {StudentId: 2, StudentName:"Smith"}
}**
This data save in Db perfectly

Now I want when users come to the index page there they can see these record as the selected value in multi-select Column but when I visit the page I see the data in this form [object Object]

So how can I show these two records as selected values.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
