### ISSUE TITLE
[BUG] Input validate on Blur

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#3448]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Browser: Chrome
- Browser version: 86.0.4240.111

## Steps to Reproduce
1. Create input (type number or textfield)
2. Add validation on Blur event
3. Try to call

## Expected behavior
Apply validation on Blur event
## Observed behavior
Applied validation on Change
## Example
https://jsfiddle.net/ksLwbtx8/

**Comment by wag110894** [comment]
It looks like you are running rather old formio.js. Can you try upgrading and see if you are still experiencing this issue?

The latest stable version of formio.js 4.12.0.

Thank you.

**Comment by homashevchenko** [comment]
Same on 4.12.0
https://jsfiddle.net/09qpxs8n/

**Comment by wag110894** [comment]
@homashevchenko, we are not seeing any in your jsfiddle that would cause the On Blur to occur. You can do this by adding a min and max length.

Here is a form that has On Blur working using 4.12.0: https://knmmlxomyyvzbrp.form.io/onblur

I hope that this helps.

**Comment by homashevchenko** [comment]
Add min and max value
https://jsfiddle.net/09qpxs8n/1/
Still call "console.log(input)" like "change" event

**Comment by wag110894** [comment]
We are not able to replicate this issue using the JSFiddle that you provided. Can you provide a video of what you are seeing?

**Comment by homashevchenko** [comment]
https://jsfiddle.net/09qpxs8n/1/
When type 123456
![image](https://user-images.githubusercontent.com/22855299/101790519-37190e00-3b0b-11eb-9086-051258e19edf.png)

**Comment by wag110894** [comment]
Hello @homashevchenko,

We are still unable to replicate this issue.

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.  Please let us know if you are interested by contacting support@form.io.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
