### ISSUE TITLE
Is it possible to change API tab property name field to dropdown from textfield ?

### ISSUE THREAD

**Issue by UmarEhsan** [formio/formio.js#3452]
![image](https://user-images.githubusercontent.com/14802705/97866782-6ed3af80-1d2e-11eb-90cd-a5fe485788a4.png)

**Comment by UmarEhsan** [comment]
Basically, what I need here whenever I drop any control I have to check it's type and then finds that type in my JSON schema that only gives me those elements whose dataType is a text field. So instead of showing property name as a text field in API tab, i have to display a dropdown of those fields whose type is text field so a user can select that property from JSON schema

**Comment by wag110894** [comment]
Hello @UmarEhsan, You can accomplish this by editing the Base edit form. I hope that this helps.

**Comment by UmarEhsan** [comment]
Ok let me try.
Thanks.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
