### ISSUE TITLE
Advice: Best way to append into a textarea the value from a dropdown

### ISSUE THREAD

**Issue by besmiralia** [formio/formio.js#3456]
I have this form http://jsfiddle.net/0jL476vn/ with two simple components.
I want the textarea which contains some text (ex. a formula) to include 

textarea value before selecting an item from dropdown:

`value = data.c + 10;`

after selecting option a from dropdown I want the textarea to render

`value = data.c + 10 + a();`

I tried using logic, but it seems that it keeps appending `a()a()a()a()...` infinitely. Is there any way to achieve this using logic?

**Comment by wag110894** [comment]
Hello @besmiralia,
It looks like you have accidentally added a + on line 56     "value": "value **+**= data.select + \"()\";".
You take out the + sign and the repeating will stop so it will show as in the test area as a().

**Comment by besmiralia** [comment]
Hi Will, no the plus is jot accidental. The idea is that I want to append
to the value multiple times. If I select A then B then C then A again, I
want them all to be in.
Basically,
Append the selected value to the existing value

**Comment by wag110894** [comment]
We will see if anyone inside the community has any thoughts on how this could work.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
