### ISSUE TITLE
[BUG] [FormBuilder] Property name in API page don't allow Chinese but will be changed automatically once Label in Display Page is typed with Chinese.

### ISSUE THREAD

**Issue by huangchinlin** [formio/formio.js#3457]
angular-formio: 4.11.0
formio: 4.12.0-rc.19

When build a new form, the Property name in API page don't allow Chinese but will be changed automatically once Label in Display Page is typed with Chinese in New Form process.

So, I'd like to suggest that can make a global setting to assign the prefix for "Key" value. When it be setted, related processes can reference it to generate the "Key" value in "New Form process".

for example:
if prefix != "" or undefined or null, the result of Key will be prefix1~N.
else: key = Label || Title || ... || ...

**Comment by huangchinlin** [comment]
original post: https://github.com/formio/angular-formio/issues/644

**Comment by wag110894** [comment]
Hello @huangchinlin, 

Thanks for providing the example, but we are looking for a Pull Request with code that we can add to our formio.js repo to resolve this issue.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
