### ISSUE TITLE
[TypeError] null is not an object (evaluating '(new window.DOMParser).parseFromString...

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3460]
## Environment
Please provide as many details as you can:
- Hosting type
  - [x] Form.io
    - Version: Application: 7.0.41, Renderer: 4.12.0
  - [ ] Local deployment
- Formio.js version: 4.10.5
- Frontend framework: No framework, vanilla JS
- Browser: iOS Safari
- Browser version: 14.1

## Error from our error-reporting service
> null is not an object (evaluating '(new window.DOMParser).parseFromString(e,"text/html").documentElement.textContent')

## More info
It appears that these lines from utils.js (lines 370 and 371)
```js
// src/utils/utils.js
const doc = new window.DOMParser().parseFromString(str, 'text/html');
return doc.documentElement.textContent;
```

get converted into
```js
// formio.utils.min.js
return(new window.DOMParser).parseFromString(t,"text/html").documentElement.textContent
```

**Comment by SalTor** [comment]
To clarify: The problem is `return(new window.DOMParser).parse...` because it should instead be `return(new window.DOMParser()).parse...` since it's creating a new instance of window.DOMParser

**Comment by travist** [comment]
Looks like an easy fix... Please submit a pull request and we will accept it to change it to...

```js
const doc = (new window.DOMParser()).parseFromString(str, 'text/html');
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
