### ISSUE TITLE
Duplicate value on dropdown

### ISSUE THREAD

**Issue by Fkhp** [formio/formio.js#3466]
hey guys..
I am new on formio.
i am trying to set array to dropdown ( select ) . I used this code at Calculatedvalue:
`**var html = [];
for (var i = 0; i < 3; i++) 
{
        html.push("<option>" + i + "</option>")  
}
value = html;**
i excepect the result be 1,2,3 on dropdown items but unfortunately the result has duplicate value

could you please help me what should i do?

Thanks

![image](https://user-images.githubusercontent.com/74006774/98481389-2d9c3d80-220f-11eb-938a-5132c7a73378.png)

`

**Comment by wag110894** [comment]
Hello @Fkhp, can you provide a form embed or a JSFiddle of this form?

**Comment by Fkhp** [comment]
> Hello @Fkhp, can you provide a form embed or a JSFiddle of this form?

hello @wag110894 here is the screen of  JsFiddle and formio ( Calculated Value on Select component)

![image](https://user-images.githubusercontent.com/74006774/98566050-8fb67a80-22c3-11eb-9846-8ced4afc1505.png)


![image](https://user-images.githubusercontent.com/74006774/98566078-96dd8880-22c3-11eb-92d4-4441257e1366.png)

**Comment by wag110894** [comment]
Can you provide the JSFiddle address so that I can test or the form JSON?

**Comment by Fkhp** [comment]
hi @wag110894 here is the code :

[https://jsfiddle.net/fakhp/uh39c2sf/6/
](url)
in this link , the code and result are ok but when i use that on Json the result has duplicate value
Here is The Json code:


`{
  "label": "Select",
  "widget": "choicesjs",
  "tableView": true,
  "data": {
    "values": [
      {
        "label": "",
        "value": ""
      }
    ],
    "json": "",
    "url": "",
    "resource": "",
    "custom": ""
  },
  "selectThreshold": 0.3,
  "calculateValue": "var html = [];\r\nfor (var i = 0; i < 3; i++)\r\n{\r\nhtml.push(\"<option>\" + i + \"</option>\")\r\n}\r\nvalue = html;",
  "key": "select",
  "type": "select",
  "indexeddb": {
    "filter": {}
  },
  "input": true,
  "placeholder": "",
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "defaultValue": null,
  "protected": false,
  "unique": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "modalEdit": false,
  "labelPosition": "top",
  "description": "",
  "errorLabel": "",
  "tooltip": "",
  "hideLabel": false,
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateServer": false,
  "attributes": {},
  "validateOn": "change",
  "validate": {
    "required": false,
    "custom": "",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false
  },
  "conditional": {
    "show": null,
    "when": null,
    "eq": ""
  },
  "overlay": {
    "style": "",
    "left": "",
    "top": "",
    "width": "",
    "height": ""
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "properties": {},
  "allowMultipleMasks": false,
  "idPath": "id",
  "clearOnRefresh": false,
  "limit": 100,
  "dataSrc": "values",
  "valueProperty": "",
  "lazyLoad": true,
  "filter": "",
  "searchEnabled": true,
  "searchField": "",
  "minSearch": 0,
  "readOnlyValue": false,
  "authenticate": false,
  "template": "<span>{{ item.label }}</span>",
  "selectFields": "",
  "searchThreshold": 0.3,
  "uniqueOptions": false,
  "fuseOptions": {
    "include": "score",
    "threshold": 0.3
  },
  "customOptions": {},
  "id": "e5oetgp"
}`

**Comment by travist** [comment]
There should be a way to provide an ID Path for the select component where you can provide the path of the "identifier". This will make it so that there are no duplicates based on that path. Have you tried to configure this?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
