### ISSUE TITLE
Overwrite the formio component inside formio dialog

### ISSUE THREAD

**Issue by dwips** [formio/formio.js#3469]
Hi All,
is there a way to overwrite the formio dialog component?
i have tried to use the same key and it is still showing the default formio dialog

**Comment by wag110894** [comment]
Hello @dwips, can clarify what you mean by the Dialog component as well as a video of what you are trying to accomplish? 

Thank you.

**Comment by dwips** [comment]
hi @wag110894 Thank for replying

so currently when i load the Formio component it will have field in the modal popup like this
![image](https://user-images.githubusercontent.com/6791049/98556922-27bd5f80-22d6-11eb-8484-0f2e22e11c6d.png)

what i want is to edit that field tooltips
i tried editing the conponent with the same key. And it still showing the default one
![image](https://user-images.githubusercontent.com/6791049/98557672-12950080-22d7-11eb-8e46-961e5a762947.png)

But when i tried using the below code, the component disappear, so i thought i can override the tooltip by using the same key  "label"

<code>{
   key: "label",
   ignore: true
}
</code>


is there a way to achieve that?

Thank you

**Comment by wag110894** [comment]
Hello @dwips,

Thanks for clarifying your issue. You can customize the formio builder in order to edit the Tooltips: https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by dwips** [comment]
hi @wag110894 
i already tried that as it shown in the screenshot i tried to overwrite one of the popup field, but it still showing the default one

Thank you

**Comment by wag110894** [comment]
Hello @dwips, 

This would require developer support for us to work up an example of this working. Please let me know if you are interested, and I can send you our developer support package information

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
