### ISSUE TITLE
Get Form Components full path/key ? (such as nested path?)

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3470]
When iterating over a list of components using FormioUtils eachComponent, when you are on a component, how do you determine what the full path of that component is?

Such as if a Text field component (key: `myTextField`) is nested within a Container Component (`myContainer`), the full path would be `myContainer.myTextField` / aka:

```
{
   myContainer: {
      myTextField: "132432"
   }
}
```

Use case if we want to understand where that component is looking for data when in the submission object

**Comment by travist** [comment]
The second argument is the path of the component.

```
FormioUtils.eachComponent(form.components, function(component, path) {
  console.log(path);
});
```

**Comment by StephenOTT** [comment]
thank you
