### ISSUE TITLE
How do i get all id with Formio?

### ISSUE THREAD

**Issue by NoobLTv** [formio/formio.js#3471]
I am trying Formio.builder in Laravel. 

And i want to add every Formio.Builder on fb-editor-{{$section->id}}. 
![afbeelding](https://user-images.githubusercontent.com/43806934/98652003-4c97ee00-233b-11eb-8f39-ccbbedd498eb.png)

I tried many thing but without result.

**Comment by NoobLTv** [comment]
I have used Formio.builder(document.getElementById("fb-editor-{{$section->id}}"),
    But than he only pick the last id

**Comment by travist** [comment]
It is not clear what you mean by "I want to add every Formio.Builder"?...

**Comment by NoobLTv** [comment]
Hallo,

What i mean is that i want to add a Formbuilder on every id. See picture above.

**Comment by NoobLTv** [comment]
@travist 

I found the solution for that.

![afbeelding](https://user-images.githubusercontent.com/43806934/98909960-cc03f980-24c2-11eb-899a-f0007d45f4c1.png)
