### ISSUE TITLE
Visual Studio and Formio

### ISSUE THREAD

**Issue by Fkhp** [formio/formio.js#3479]
Hey guys.
Is it posible to use Formio in Visual Studio ( Asp Classic or Mvc )?
it means : i have solution project and i need to add a form builder for my user in the project. how can i do that? 
thanks

**Comment by blakecodes** [comment]
Yes, why would it not be? Just drop the JavaScript file into the layout or view and go from there.

**Comment by Fkhp** [comment]
Dear @blakecodes  Thank you for your reply, the link [https://s17.picofile.com/file/8413750218/WebApplication2.rar.html](url) is the project , i added the formio files, but unfortunately the result is not correct, here is the picture of the result
![image](https://user-images.githubusercontent.com/74006774/98968220-a27aba80-2522-11eb-9348-bc120d2dd964.png)

i need the project result be the page like this link:

https://formio.github.io/formio.js/app/builder

could you please check it and tell me why the result is not correct?

sorry i am new at this topic

**Comment by blakecodes** [comment]
@Fkhp  Just to be clear, are you using Razor for the views? Also, are you wanting to use Angular or Vanilla JS?

**Comment by Fkhp** [comment]
Dear @blakecodes . no It's Asp Classic By C#, it`s not MVC .. I want to use angular js.
Thanks

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
