### ISSUE TITLE
Open custom URL by clicking on a Button

### ISSUE THREAD

**Issue by zoka-bl** [formio/formio.js#3480]
Hi,

I have a question regarding the custom action for the Button component. 

1. URL is build up by using the custom data from other form components and is dynamic
2. URL is created as calculated value within the HTML form component by using couple of other form components, where the data are fetched from a DB
3. Button shall open the external web app by using the URL link from HTML form component

I have used custom action on Button and following code for button's custom logic, but cannot make it operational.
form.getComponent("getURL");

What am I doing wrong?

Thanks.

**Comment by travist** [comment]
Try using....

```
instance.root.getComponent("getURL");
```

The form variable is just the JSON of the form.  ```instance``` points to the Button Component instance, and ```instance.root``` points to the Webform instance.  Calling "getComponent" on the webform instance will search all components for that component.

**Comment by zoka-bl** [comment]
Thanks Travis. It worked.
