### ISSUE TITLE
[BUG] Starting with v4.12-rc1 form is not immediately available

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#3489]
## Environment

- Hosting type n/a
  - [] Form.io
  - [] Local deployment
    - Version:
- Formio.js version:  4.12-anything
- Frontend framework: none
- Browser: at least chrome
- Browser version: latest 3 versions

## Steps to Reproduce
1. Render a form
2. Immediately (faster than 100ms?) use the form
3. Test form input

## Expected behavior
Form should work

## Observed behavior
At least typing in an input will miss the first few keystrokes

## Example
https://dashboard.cypress.io/projects/ep9zr6/analytics/top-failures/fb279420-72f0-d0b2-92c2-5962b4f9f7f1-52d69a4f-6945-a3fb-f543-0223bd73f42f

I noticed this via cypress testing.  Updating to v4.12-anything fails consistently.  Going back to v4.11-anything always works.  The form.io version is the only thing that changes to cause and fix the issue.

The fix for using v4.12-anything was to wait 100ms before using the form input.

Not the end of the world, but figured it might be worth opening an issue.

**Comment by travist** [comment]
I am curious why our automated tests do not catch this since we also test this in our automated tests. Regardless, it is something that should be looked into. Do you have a test or jsfiddle that shows the problem?

**Comment by paulfalgout** [comment]
https://github.com/RoundingWell/care-ops-frontend/tree/example/form-io-test-example

It's a bit bulky, but I tried to reduce it to the bare minimum.  This runs the tests in cypress.
To reproduce from this branch it should just be `npm i` `npm test` 

I'd say it fails for me 80% of the time.  And when it fails that first line types "ello" or "llo" so it's definitely some sort of race condition.  It's worth noting this is a kitchen sink test so there's a lot on this form.  Simpler forms haven't failed.

To see the fix you can uncomment this line:
https://github.com/RoundingWell/care-ops-frontend/blob/example/form-io-test-example/test/integration/forms/formapp.js#L23

Or change the form.io version in package.json to 4.11.x and in either of those case it seems to pass 100% of the time.

**Comment by travist** [comment]
Ok thanks. We will investigate on our end.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
