### ISSUE TITLE
[HELP] FormioUtils.getComponent Question

### ISSUE THREAD

**Issue by pocketcap** [formio/formio.js#3490]
Hi,

I am trying to get component by key, but only this way works:
`FormioUtils.getComponent(form.components[1].components[1].components[0].components, "XYZ", true);
`
That I have to know where  the target component is located.

While below approach doesn't work:
`FormioUtils.getComponent(form.components, "XYZ", true)
`
That I want to get the component without knowing where it is.

Is it expected?

Thanks.

**Comment by travist** [comment]
As long as XYZ is the "key" of the component, then ```getComponent``` should work just fine. Please provide a jsfiddle showing the issue and maybe we can investigate on our end.

**Comment by pocketcap** [comment]
@travist Thanks for reply. Yeah XYZ is the key, but it contains dot, like "X**.**YZ".
Here is the jsfiddle, that I tried to alert FormioUtils.getComponent(form.components, "XYZ", true):
https://jsfiddle.net/yahuiwang/9y5oraj8/9/

**Comment by travist** [comment]
So you have a component keyed "YZ" within a container component "X"?  Then you will just use "YZ" as the key of the component to get.

**Comment by pocketcap** [comment]
@travist unfortunately, that's not the case, we have the key as "X.YZ", The form json is `"key":"X.YZ"`
because we defined property API like:
![image](https://user-images.githubusercontent.com/1475774/99854458-da04ea80-2b52-11eb-9a64-f95e95fd2d75.png)

**Comment by travist** [comment]
This is probably a bug then where getComponent is confused when you use "periods" in the key names. Does it work if you remove the period?

**Comment by wag110894** [comment]
@pocketcap, can you provide a video of the issue taking place?

**Comment by pocketcap** [comment]
@travist It works if no "periods". But "periods" is allowed as API property. Would you consider to get it fixed?

**Comment by pocketcap** [comment]
@wag110894 
Here is the jsfiddle, that I tried to alert FormioUtils.getComponent(form.components, "XYZ", true):
https://jsfiddle.net/yahuiwang/9y5oraj8/9/
Note: XYZ is Cstm_PF_ADG_Discharge_Note.success_comp_treatment in the jsfiddle, which has periods.

**Comment by wag110894** [comment]
Hello @pocketcap,

Apologies on the delay.

We have created a ticket in order for this functionality to work when periods included inside the API property.  For reference, the ticket number is FIO-1016. We welcome a pull request. We also do have a process to expedite if you are interested. Please let me know if you are interested and we can get the process started.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
