### ISSUE TITLE
Easy way to remove default values and conditionals

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#3493]
Right now we are using regex to strip out default values and conditionals/logic from the form when presenting it for the purposes of generating a report. So while the default values are used when filling the form out, we want to present the form to a manager with all defaults removed and showing all available options without having to click through things to see them.

Just curious if there is a config option we can use to do this work before the form gets presented using createForm without having to resort to finding all possible permutations with regex.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
