### ISSUE TITLE
Is there any way which we can inherit directly the Formio's components to achieve custom component?

### ISSUE THREAD

**Issue by guopine** [formio/formio.js#3495]
I want to inherit the File component to do something. But I found that there was a problem when overriding the 'render' method. Because I need to change the template name, I have to change the render method. In my render method, when I call super.render(template), actually the super.render is the File.render but we hope it is the Field.render. So it caused a wrong result.

**Comment by travist** [comment]
Why not do something like this?

```
render(...args) {
  return Field.prototype.render.apply(this, args);
}
```

**Comment by guopine** [comment]
OK, I got it. Thank you so much!
