### ISSUE TITLE
[BUG] Form Builder - File component - editForm image (Display as image) defaultValue not set/checked

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#3498]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.9.26, 4.12.1
- Frontend framework: N/A, Javascript
- Browser: Firefox, Chromium
- Browser version: Firefox 82.0.3, Chromium 83.0.4103.116

## Form Builder

In the screenshot below, you'll see a **file component** with **editForm** options (checkbox components) and respecting the overrides of the **defaultValue**.
However the **image (Display as image)** checkbox component, strangely doesn't work.

![image](https://user-images.githubusercontent.com/328803/99527267-d0d21d00-299c-11eb-873a-c9a64baa322a.png)

**Comment by wag110894** [comment]
@bobslee, 

Thanks for reaching out! We are not seeing this issue on our side. Can you please provide the versions of formio that you are using?

**Comment by bobslee** [comment]
@wag110894 thanks for answering. 
Also see above in my report...

Formio.js version: 
4.9.26, 4.12.1-rc.28

I didn't tested yet on 4.12.1

**Comment by bobslee** [comment]
Affirmative, 4.12.1 also has this issue.

Maybe it's just a small bug in the **file** component's **editForm (display: image)?**

I shall analyze further and report here.

**Comment by wag110894** [comment]
@bobslee Sounds great! If you do find the issue, we do welcome pull requests. 

Please let us know if you have any further questions.

**Comment by bobslee** [comment]
Unfortunately I'm still not able to install a simple `formio.js` development env, with just some HTML and including the modules from the `node_modules` path.
Any help would be appreaciated, so I can analyse and PR.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
