### ISSUE TITLE
[HELP]Unmasking possible?

### ISSUE THREAD

**Issue by pocketcap** [formio/formio.js#3501]
Hi,
is there a way to unmask text field? Like I have mask (999)999-9999 on a text field with value (123)456-7890, I want to save 1234567890 into database.
Thanks.

**Comment by travist** [comment]
This is actually a feature request that we have had for a while, which is to have a Display Mask and a Data Mask. One would be for input, and the other would be how it is saved. Default would be to make them the same (which is how it works today), but they would be given the option to change one against the other.

**Comment by pocketcap** [comment]
@travist  Thanks for update.

I noticed that when I apply a mask to a text field, it mentioned jQuery inputmask, does it mean I can use it for unmasking?
![image](https://user-images.githubusercontent.com/1475774/99725839-ad35d200-2a83-11eb-8119-5e7c8683b235.png)

**Comment by besmiralia** [comment]
I had this issue with my project where the form was sending `(123) 456-7890` and the backend was stripping the mask characters, so when I reopened the form, the data was coming as `1234567890` and it was throwing a validation error.
What I did to overcome it, is to format the `validatationValue` if there is a mask applied. 
This is not a thorough solution though.

Code changed in TextField.js
```
  get validationValue() {
    //convert value to match the mask before validating it
    var dataVal = this.dataValue;
    if (dataVal !== '' && !this.isMultipleMasksField && this.component.inputMask) {
      dataVal = conformToMask(dataVal, FormioUtils.getInputMask(this.component.inputMask), { guide: false }).conformedValue;
      this.dataValue = dataVal;
    }
    return dataVal;
  }
```

**Comment by pocketcap** [comment]
@besmiralia Thanks for sharing your code change.
Actually I am looking for stripping the mask characters before sending to backend. But I may need to do the same thing as you did, when backend send me unmasked value.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
