### ISSUE TITLE
[BUG] TypeError: this.refs.padBody is undefined

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3508]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: 4.10.5
- Frontend framework: None
- Browser: Firefox on Android 10
- Browser version: 82.0

## Steps to Reproduce
Unclear but related to the Signature component.

Based on our error reporting we have identified this line as the culprit: https://github.com/formio/formio.js/blob/0525a143a5b17f6b4f499206ad9d8dd1fda76bab/src/components/signature/Signature.js#L131

We believe what happened is the user signed, clicked "Submit" or "Previous" quickly after rotating their phone. Such a scenario would be a possible source of calling the `checkSize` method and it no longer being on the screen.

This is our first time seeing this in the 6 months of our product being live and if such conditions are required for reproducing it, it makes sense we haven't seen it before as I wasn't able to reproduce it on my own after a bunch of attempts.

I believe a fix would be to check that this.refs.padBody is present similar to the check [on line 191 of the same file](https://github.com/formio/formio.js/blob/0525a143a5b17f6b4f499206ad9d8dd1fda76bab/src/components/signature/Signature.js#L191)

**Comment by travist** [comment]
Feel free to submit a pull request to resolve this. Otherwise, we will add it to our developer backlog.

**Comment by wag110894** [comment]
For reference, the ticket number is FJS-1468.

**Comment by jhen1422** [comment]
This issue should be resolved in V 4.13.0-rc.7
