### ISSUE TITLE
[Question] Knowing when a component becomes visible

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3509]
I have some external JS that would benefit from knowing whether a component is on the screen.

We have event methods like nextPage, prevPage, render, initialized, changed, etc. But is there any way to check if a component suddenly becomes revealed? Like when a condition is met for some conditional logic to render a component we don't get notified that it is now on screen.

The best I can think to do is check during the change event and checking to see if that change resulted in the component being rendered.

**Comment by travist** [comment]
We do not have any events fire, but you can add the following code to your application to determine this. This extends the "set visible" property of the base component.

```js
const visibleProp = Object.getOwnPropertyDescriptor(Formio.Components.components.component.prototype, 'visible');
const setVisible = visibleProp.set;
visibleProp.set = function(visible) {
  if (visible) {
    console.log(this.component.key + ' is now visible!!!');
  }
  return visibleProp.set.call(this, visible);
};
Object.defineProperty(Formio.Components.components.component.prototype, 'visible', visibleProp);
```

**Comment by SalTor** [comment]
Thanks Travis! Neat solution
