### ISSUE TITLE
You can add files to a multi-file File component even when the form is read-only

### ISSUE THREAD

**Issue by colons** [formio/formio.js#351]
- Add a File component to a form
- Check the 'Multiple Values' box on the component and save it
- Render the form, with `readOnly: true`
- Observe that your multi-file File component can still have files uploaded to it

I've attached a screenshot of a form demonstrating this behaviour. File uploads work both by dragging and hitting browse, and the files are uploaded to the field's storage provider. Note that this problem seems to be exclusive to multi-file File components.

<img width="1165" alt="a read-only form with a multi-file field" src="https://user-images.githubusercontent.com/1394710/35808980-78081736-0a7f-11e8-8544-8ec094a8ad24.png">

**Comment by colons** [comment]
You can also remove files if you're using 'Display as images'; the remove button still appears and is functional.

**Comment by jhen1422** [comment]
This issue has been resolved
