### ISSUE TITLE
Only the last loaded plugin will see its options used

### ISSUE THREAD

**Issue by Baloche** [formio/formio.js#3514]
Hi !
I would like to create several plugins providing custom builder groups to the Formio Builder.
The problem is, the way this is implemented today, only the last loaded plugin will see its options used.

https://github.com/formio/formio.js/blob/4cd7749ea22a3344b91f48cdce8ba4c14f8fa151/src/formio.form.js#L22-L24

I think each new `options` object should be merged with the previous one instead of overriding it.
Or is this the expected behaviour ?

**Comment by travist** [comment]
I agree. Please suggest a change via pull request and we will look into merging. I would recommend using the Lodash ```_.merge``` method.
