### ISSUE TITLE
Custom file upload url returning "correct" json, but file component not

### ISSUE THREAD

**Issue by rustymcg9000** [formio/formio.js#3520]
I'm using the quick embed method of using setting a script src to:

"https://unpkg.com/formiojs@latest/dist/formio.embed.js?src=https://localhost:44323/view/8eb5be08-5407-4e60-97f5-df44fc7930d2"

I've implemented a simple custom url endpoint for uploading files to, which returns json as follows:

{"url":"https://localhost:44323/file/8cda5157-9a58-4fd2-97ed-8395300b7ceb", "name":"QRAH Boarding Agreement 101420.pdf", "size", 266438}

However, the Upload component on the form (and the data submitted) shows a file link of:

https://localhost:44323/file?baseUrl=https%3A%2F%2Flocalhost%3A44323&project=&form=/QRAH%20Boarding%20Agreement%20101420-1a709aa8-cc79-425d-9762-3a492469c565.pdf

For some reason, the "name" of the file as posted to the url is:
"QRAH Boarding Agreement 101420-1a709aa8-cc79-425d-9762-3a492469c565.pdf"

When the actual filename is:
"QRAH Boarding Agreement 101420.pdf"

Am I missing something

**Comment by Nabinsharma123** [comment]
@rustymcg9000 
did you solve the problem?
