### ISSUE TITLE
[BUG] Issue with Email template - File upload inside Edit Grid component

### ISSUE THREAD

**Issue by phucduong86** [formio/formio.js#3524]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Application: 7.0.40, Renderer: 4.11.3
- Formio.js version:  4.11.3
- Frontend framework: N/A
- Browser: Chrome
- Browser version: 

## Steps to Reproduce
1. Navigate to https://formsportalqa.ottawa.ca/iivzksgcodkbrbi/manage/view/#/form/editgridfileupload?header=0
2. Enter your email address
3. Upload a file inside the editgrid and one outside
4. Submit form

## Expected behavior
You should receive an email in the mailbox with:
- 2 attachments
- File links with the download token

## Observed behavior
- Only 1 attachment (from the component outside EditGrid) is received
- The URL for the File component inside Edit Grid does not have the download token

**Comment by travist** [comment]
Thanks for the report. We will take a look on our end and try to reproduce and let you know.

**Comment by wag110894** [comment]
Hello @phucduong86,

We are not seeing this issue while testing Application: 7.0.41, Renderer: 4.12.0. The form that you provided above is not working. Can you provide a video of the issue as well as the JSON. What File Storage are you using?

**Comment by phucduong86** [comment]
Hi sorry about that we update the dns recently.
Please try
https://formsportalqa.ottawa.ca/iivzksgcodkbrbi/manage/view/#/form/editgridfileupload?header=0

**Comment by wag110894** [comment]
Hello @phucduong86, 

Thank you for providing the form. We are able to replicate on our side. We have created a ticket and have added it to our backlog. We welcome a pull request. We also have a process to expedite if you are interested. 

For reference, the ticket number is FJS-1482.

**Comment by phucduong86** [comment]
Thank you. I've disabled that form now. Please keep us posted.
