### ISSUE TITLE
[BUG] externalId is not defined

### ISSUE THREAD

**Issue by dbalik17** [formio/formio.js#3529]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Create a Webhook action in the form
2. Look for the Response Payload panel

## Expected behavior
The field for externalId should be there

## Observed behavior
Field externalId displays an error in rendering.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
<img width="1586" alt="externalId" src="https://user-images.githubusercontent.com/50362157/100388494-0f19ad00-302b-11eb-9222-311e735a0739.png">

**Comment by wag110894** [comment]
Hello @dbalik17,

This issue has been resolved in server 7.0.0-rc.54.
