### ISSUE TITLE
[BUG] Radio buttons are not re-rendered when selected value changes

### ISSUE THREAD

**Issue by zzdjk6** [formio/formio.js#3530]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.1
- Frontend framework: Bootstrap 4
- Browser: Chrome
- Browser version: 86

## Steps to Reproduce
1. open the form with browser's devtools and inspect the elements
2. select an option in radio
3. observe the HTML changes

## Expected behavior

According to the `template` file ( https://github.com/formio/formio.js/blob/ac0966b2e2154c03c795f3df08c1bb06f3699e25/src/templates/bootstrap/radio/form.ejs#L14-L16), the `checked` attr should be set according to the `ctx.value`.

## Observed behavior

However, when I change the selected option, the `checked` attr didn't change.

The only HTML change is the `class` on the `<div ref="wrapper">`. While debugging it with custom template for `radio`, I found that the template is not called when changing selected option.

I am not relying on the `checked` attr, but I want to re-render the radio with template when selected option changes. The reason behind it is that I want to use `ctx.component.properties` in template to extend the display and behaviour of `radio`. If the `radio` is not re-rendered, I am not able to display my extended version correctly.

## Example

demo: https://pro.formview.io/#/ehdkompeqarzcuk/radiobug?header=1&reset=1

![image](https://user-images.githubusercontent.com/3908516/100405987-a7666f00-30c9-11eb-9781-9b1be59816e1.png)

**Comment by zzdjk6** [comment]
A workaround is detected for this one -- adding an empty logic can trigger the re-render correctly when selected option changes.

![image](https://user-images.githubusercontent.com/3908516/100555761-a53b2500-3302-11eb-921c-d3162e57627e.png)

...and the trigger component can be a `Hidden`:

![image](https://user-images.githubusercontent.com/3908516/100555925-85f0c780-3303-11eb-8869-fcb3ccc71538.png)

**Comment by zzdjk6** [comment]
Potential fix for `checked` attribute update is:

1. Add...

```js
input.setAttribute("checked", "true");
```

...after this line:

https://github.com/formio/formio.js/blob/e419302e8054c244f6e575841ea77b3a2e4e005c/src/components/radio/Radio.js#L146

2. Add...

```js
input.removeAttribute("checked");
```

...after this line:

https://github.com/formio/formio.js/blob/e419302e8054c244f6e575841ea77b3a2e4e005c/src/components/radio/Radio.js#L149

**Comment by wag110894** [comment]
Hello @zzdjk6, We welcome a PR with the potential fix that you have provided above. We will take a look at it and we will then add it to our next build.

**Comment by zzdjk6** [comment]
@wag110894 Thanks, I will submit a PR for this. 

Meanwhile, I am wondering what is the prefered way to update UI of rendered components? It seems we can update the UI in `updateValue` method, or we can make another `render` call -- `Radio` is taking the former approach.

**Comment by zzdjk6** [comment]
Spotted the same issue with `Checkbox`, created a PR #3698
