### ISSUE TITLE
[BUG] Time component under IE 11 won't display time picker

### ISSUE THREAD

**Issue by pocketcap** [formio/formio.js#3552]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12.1
- Frontend framework: vanilla JS
- Browser: IE
- Browser version: 11

## Steps to Reproduce
1. Have a Time component in the form
2. Open the form in IE 11

## Expected behavior
Time picker would appear on the right, by clicking it would allow me to choose time.
![image](https://user-images.githubusercontent.com/1475774/101051646-bc248600-3553-11eb-8022-8f2a1ddf70ae.png)

## Observed behavior
No time picker icon is shown under IE 11.
![image](https://user-images.githubusercontent.com/1475774/101051798-dd857200-3553-11eb-85ec-e83997882f26.png)

**Comment by wag110894** [comment]
Hello @pocketcap, Thanks for reaching out! We are able to replicate this issue on our side. We have added this ticket to our backlog. For reference, the ticket number is FJS-1490. We welcome a pull request. We also have a option to expedite if you interested.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
