### ISSUE TITLE
Issue in Running test Script

### ISSUE THREAD

**Issue by Zash0012** [formio/formio.js#3555]
When i am running npm  run test the below error is coming
'TZ' is not recognized as an internal or external command,
operable program or batch file.

**Comment by travist** [comment]
What OS are you running the tests within?

**Comment by Zash0012** [comment]
> What OS are you running the tests within?

Windows

**Comment by travist** [comment]
It may be the case that our build and tests scripts are not compatible with Windows. We all use Unix based systems @ form.io, so we would welcome a fix to this to support windows as a pull request.

**Comment by Zash0012** [comment]
Please help!!!!!!!!!!

**Comment by mathiasgraabeck** [comment]
@Zash0012 I fixed the problem by deleting tz;
before: TZ=Etc/UTC cypress run --browser firefox
after: cypress run --browser firefox

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
