### ISSUE TITLE
[BUG] Select Boxes component - not applying selected class

### ISSUE THREAD

**Issue by adventmedia** [formio/formio.js#3557]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: react-formio: 4.3.0
- Formio.js version: 4.12.1
- Frontend framework: React 16.9.0
- Browser: Chrome
- Browser version: 87.x

## Steps to Reproduce
1. Create a form with a Select Boxes component
2. Load & run the form
3. Select an option

## Expected behaviour
Compared with Radio component - when a radio button is selected, the div changes from:
`<div ref="wrapper" class="form-check">` to `<div ref="wrapper" class="form-check radio-selected">`
This makes it possible to restyle the css for the child elements.

## Observed behavior
However in the case of the Select Boxes component, the div:
`<div ref="wrapper" class="form-check">` does not have any class added.

According to https://github.com/formio/formio.js/pull/1136, it would appear that this issue was addressed some time ago, though probably only for the Checkbox component — but it appears that this is not working either.

**Comment by travist** [comment]
We will add this as a bug in our backlog, but it may be considered a low priority. If you submit a pull request to fix this, we will gladly include it in our next version of our renderer. We also have ways of expediting resolution if you want to go down that road.

**Comment by adventmedia** [comment]
working on it. The Select Boxes component actually uses the Radio component but the code currently doesn't work on the underlying checkbox. Will do a pr when I think our solution is ready.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
