### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MosabAbuzaid** [formio/formio.js#3559]
Hi I am trying to use formiojs in my vue js project so I installed formio ^4.12.1 using npm 
then I import it in my component like in the documentation 

`import Formio from "formiojs";`

then I tried to create a form builder through fomio constructor 

`var builder = new Formio.FormBuilder(myValuse);`

but I got an error Cannot read property 'FormBuilder' of undefined
I tried to consol.log(Formio) itself and get it value is undefined too so what should I do?

**Comment by travist** [comment]
Try this...

```js
import { FormBuilder } from 'formiojs';
var builder = new FormBuilder(myValue);
```

**Comment by MosabAbuzaid** [comment]
@travist 
thx a million ♥

**Comment by MosabAbuzaid** [comment]
Hi @travist 

![Capture](https://user-images.githubusercontent.com/38281155/101619725-55541080-3a1c-11eb-8722-b7eca148108f.JPG)

I want to customize these tabs is it possible to do that?

**Comment by wag110894** [comment]
Hello @MosabAbuzaid you can accomplish by creating a custom builder. Here is an example: https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by MosabAbuzaid** [comment]
hi @wag110894 
I saw this example before and it's a good example to customize the component on the left and there is a case to remove the API tab from the dialog in the text field.
I tried to add a new tab 
![Capture](https://user-images.githubusercontent.com/38281155/101760081-0d4bf100-3ae3-11eb-8292-6791f1a42ced.JPG)

but the new tab won't show even if I tried to edit a property label or tooltip, for example, it won't change 

thx in advance

**Comment by MosabAbuzaid** [comment]
Is there an example show the full object that filled in builder by default?

**Comment by travist** [comment]
You can completely make this edit form what you want it to be with the following code.

```js
import { Formio } from 'formiojs';
Formio.Components.components.textarea.editForm = function() {
  return {
    components: [
      {type: 'textfield', label: 'Label', key: 'label'}
    ]
  };
};
```

This code will remove all tabs and only show a single field called label. You can then build the form you want using the form builder and then just paste that JSON into the editForm function.

**Comment by MosabAbuzaid** [comment]
@travist 
you are my hero ♥

**Comment by MosabAbuzaid** [comment]
hi @travist 
it is possible to edit a specific tab and reflect the changes to all components with one function?
