### ISSUE TITLE
[HELP] How to set form's language?

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3563]
I'm trying to find a way to set a language on an individual form.

How can it be done?
Adding `language' property to form definition JSON doesn't seem to work.

Th goal is that if I set the language on an individual form, it's displayed using translations from this language by `Form` and `FormBuilder` components, ignoring Form or FormBuilder languages.

Is that currently possible?

**Comment by LucasPanetto** [comment]
Hi, i usage i18n with two different implementations:

• First usage in VueJs project using a existent component in library, like this:

![image](https://user-images.githubusercontent.com/25806409/102229540-ad7e8d00-3eca-11eb-8de5-74033ed85a16.png)

• In other implementation i instanced the Formio in pure JS and call builder method, like this:

`Formio.builder(
      document.getElementById("builder"),
      {},
      {
        builder: {
          basic: false,
          advanced: false,
          data: false,
          customBasic: {
            title: "Basic Components",
            default: true,
            weight: 0,
            components: {
              textfield: true,
              textarea: true,
              email: true,
              phoneNumber: true
            }
          },
          custom: {
            title: "User Fields",
            weight: 10,
            components: {
              firstName: {
                title: "First Name",
                key: "firstName",
                icon: "terminal",
                schema: {
                  label: "First Name",
                  type: "textfield",
                  key: "firstName",
                  input: true
                }
              },
              lastName: {
                title: "Last Name",
                key: "lastName",
                icon: "terminal",
                schema: {
                  label: "Last Name",
                  type: "textfield",
                  key: "lastName",
                  input: true
                }
              },
              email: {
                title: "Email",
                key: "email",
                icon: "at",
                schema: {
                  label: "Email",
                  type: "email",
                  key: "email",
                  input: true
                }
              },
              phoneNumber: {
                title: "Mobile Phone",
                key: "mobilePhone",
                icon: "phone-square",
                schema: {
                  label: "Mobile Phone",
                  type: "phoneNumber",
                  key: "mobilePhone",
                  input: true
                }
              }
            }
          },
          layout: {
            components: {
              table: false
            }
          }
        },
        editForm: {
          textfield: [
            {
              key: "api",
              ignore: true
            }
          ]
        },
        language: "ptBR",
        i18n: {
          ptBR: {
            Submit: "Enviar",
            "Basic Components": "Componentes Básicos",
            required: "{{field}} é obrigatório.",
            invalid_email: "{{field}} inválido.",
            error: "Por favor, corrija os seguintes erros antes de enviar."
          }
        }
      }
    ).then(function(builder) {
      builder.on("saveComponent", function() {
        console.log(builder.schema);
      });
    });    
  }`

*I couldn't format code here

try this

**Comment by mm-dsibinski** [comment]
Thanks @LucasPanetto. I know this way, but you are setting the language of the FormBuilder, not the form itself.
I'm looking for a way to set language A for given, individual form, independently from FormBuilder's language.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
