### ISSUE TITLE
[HELP] Override selectList options values

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3564]
I'd like to override the way how `select` component's values are rendered.
More precisely, I want to alter rendering of the text in this place:

![image](https://user-images.githubusercontent.com/49182064/101486527-1317ca00-395d-11eb-9a3a-40057b7e1e42.png)

I tried with a [custom template](https://github.com/formio/formio.js/wiki/Templates-API) for `select-selectList`, but it allows to replace the whole `select` component. My goal is to only replace rendering of the `select`'s values.
How can I achieve that?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
