### ISSUE TITLE
[BUG] File component does not handle failed downloads gracefully

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3569]
## Environment
Please provide as many details as you can:

We received the following error: Unhandled Rejection: Non-Error promise rejection captured with value: undefined

And after some digging it is likely to occur when the user is on a slow cellular network and as the file is downloading the network connection is severed for some amount of time before the browser decides to not bother resuming the download.

- Hosting type
  - [x] Form.io
- Formio.js version: 4.10.5
- Frontend framework: None
- Browser: All
- Browser version: Presumably all

## Steps to Reproduce
1. Visit https://jsfiddle.net/SalTor/rajynq5g/
2. Set network speed to slow 3G
3. Upload an image and watch the network tab
    - Once the upload's PUT is finished it will fire off the GET request
    - Set network speed to offline when this happens
    - Observe the error in the console: `Uncaught (in promise) undefined`

## Expected behavior
I expect this to confirm visually that the upload took place but the preview download could not be fetched.

## Observed behavior
No confirmation to the user what happened.

## Example
https://jsfiddle.net/SalTor/rajynq5g/

## Additional notes
It appears in 4.11.3 but doesn't emit the error to the console in 4.12.3. In either case there's still no visual indication as to what's happened.

Is there any plan to have some messaging here in this regard?

**Comment by wag110894** [comment]
Hello Sal, 

Thank you for reaching out! We have created a ticket and have added this to our backlog. As you know, we welcome a pull request as well as have an option to expedite this if you are interested. We estimate this fix at 6 hours. Please let us know if you are interested and we can get the process started.

**Comment by SalTor** [comment]
Thanks Will. I'll keep keep an eye out for updates on this thread. In the mean time I'm planning on opening a PR for a similar issue with the upload mechanism under similar network conditions.

**Comment by wag110894** [comment]
Sounds Great.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
