### ISSUE TITLE
PDF Generation not working

### ISSUE THREAD

**Issue by danyob** [formio/formio.js#3574]
Enabling PDf attachments on a form stops emails from being sent with submission data.

When trying to download the PDF of a form submission the following error shows: `x-file-token is invalid.`

**Comment by wag110894** [comment]
Can you confirm that your x-file-token is correct?

**Comment by vikanirav** [comment]
Hello, 
I am also getting same error at the time of click on PDF icon to view PDF file on Portal.

I also tried to download PDF file usign their API but I am getting `{ "message": "Token expired." }` in API response.
I am following their API document and tried below two API.
1. Get a temporary download token (https://documenter.getpostman.com/view/684631/formio-api/2Jvuks#4ea8b1f7-a100-f4af-387d-6a74bb69ef1b) and use token in next download PDF file API
2. Download a Submission as a PDF (https://documenter.getpostman.com/view/684631/formio-api/2Jvuks#0e4214b1-4e35-f22c-3a0c-0a5e01c62126)

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
