### ISSUE TITLE
[BUG] textarea RTE editor validation not working as expected

### ISSUE THREAD

**Issue by dwips** [formio/formio.js#3576]
## Environment
Please provide as many details as you can:
The validation for textarea with editor not working as expected. the gif showing error for validation no more than 15 characters, but inside the editor only have 10 characters.

- Hosting type
  - [x] Form.io
  
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. go to https://formio.github.io/formio.js/app/builder
2.  try add validation maximum length to textarea component with CKeditor editor
3. try typing the form renderer

## Expected behavior
should show error if the character more than maximum length validation

## Observed behavior
![83F9B5F7-F1AF-45F6-A344-EADED34570A6](https://user-images.githubusercontent.com/6791049/101800834-4bc3c900-3b40-11eb-80ec-27c43f061deb.GIF)

### CKeditor
![image](https://user-images.githubusercontent.com/6791049/101802910-90e8fa80-3b42-11eb-8203-a0a73ff3f2e6.png)
### Quill
![image](https://user-images.githubusercontent.com/6791049/102034916-c404e580-3df1-11eb-9492-68e5538af745.png)

**Comment by wag110894** [comment]
Can you clarify which Editor you mean when you say RTE?

**Comment by dwips** [comment]
the one in the screenshot is CKeditor

**Comment by wag110894** [comment]
Hello @dwips,

Thank you for the clarity. We are aware of this issue and it is currently in our backlog. We welcome a pull request. We also have a process to expedite this for you if you are interested. For reference, the ticket number is FIO-350. Please let us know if you are interested in expediting and we can get the process started.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
