### ISSUE TITLE
[Question] How to calculate Hours Worked based on Start Time and Finish Time automatically? 

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3590]
Hello @travist 

Hope you can give me a solution to handle the below requirement.

When a user fills Start Time and Finish Time then Hours Worked should be calculated and fill on it.
![image](https://user-images.githubusercontent.com/58280615/102338836-f156bc80-3fc6-11eb-8659-a33e40cdc0da.png)

Best Regard

**Comment by wag110894** [comment]
Hello @thanhvietnguyen255 can you provide the form so that we can take a look?

**Comment by thanhvietnguyen255** [comment]
Hi @wag110894,

I have attached the form, it's JSON string so please use JSON.parse() to parse it back JSON.
[form.txt](https://github.com/formio/formio.js/files/5714194/form.txt)


And here is the requirement:
Hours worked should be calculated as the difference from start time to end time. The maximum allowed time difference is 23 hours and 45 minutes. Anything over this time should not be allowed.

Best Regard
