### ISSUE TITLE
[Help/Question] Defer the page schema, seek to a different page and ability add sub pages

### ISSUE THREAD

**Issue by shujathkhan** [formio/formio.js#3591]
### Part 1 : Defer page schema
In the example [multiform workflow](http://formio.github.io/formio.js/app/examples/multiform.html), the pages are being loaded in using 'src' from a hosted json form link. They are all being loaded on page load. Is there a way to defer it ? Like only when 'Next Page' is clicked it loads the form from hosted url?

![image](https://user-images.githubusercontent.com/13440061/102368430-d8f39b80-3fe0-11eb-848a-35816d797a80.png)

### Part 2 : Seek to a different page
I was able to find event like wizard.next and wizard.previous. Is there a way to seek to a page in the wizard by firing a defined function using javascript, like seekTo('page2') ?

![image](https://user-images.githubusercontent.com/13440061/102368762-38ea4200-3fe1-11eb-989d-b57996fce72c.png)

### Part 3 - Ability add sub pages
Is there a way where we can sub pages like,

page 1
->sub-page 1
page 2
->sub-page 1
->sub-page 2

**Comment by travist** [comment]
I thought it should work like this by default. The fact that it is not means there is a bug here. We will add it as a bug to investigate, but something like this may be a while before we can get to it. Would be helpful if the community could debug why it is not lazy loading the forms.

**Comment by wag110894** [comment]
For reference the ticket for this issue is FIO-1015.

**Comment by shujathkhan** [comment]
Closing this as I feel this is in works and this thread is going to be stale for a while.
