### ISSUE TITLE
[Question] How to collapse or expand the panel component based on data inside it?

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3595]
Hello everyone!

How to collapse or expand the panel component based on data inside it?
If a user enters some data to components inside the panel component then it should expand, else collapse.

![image](https://user-images.githubusercontent.com/58280615/102586760-4f0d1500-413d-11eb-81da-40357cfb9468.png)

Best Regard.

**Comment by sureshyadaw437** [comment]
I guess we can set any component's property dynamically by using trigger event. 
1. use _javascript_ trigger type  & set result = data['yesComponnet']?true:false
2. use _property_ as action type & set the collapsible prop true/false

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by krixerx** [comment]
> I guess we can set any component's property dynamically by using trigger event.
> 
> 1. use _javascript_ trigger type  & set result = data['yesComponnet']?true:false
> 2. use _property_ as action type & set the collapsible prop true/false

Doesn't look to work:
{
                            "trigger" : {
                                "type" : "json",
                                "json" : {
                                    "==" : [ 
                                        {
                                            "var" : "data.applicantisCollapsed"
                                        }, 
                                        true
                                    ]
                                }
                            },
                            "actions" : [ 
                                {
                                    "type" : "property",
                                    "name" : "collapseThePanel",
                                    "state" : true,
                                    "property" : {
                                        "label" : "collapsed",
                                        "value" : "true",
                                        "type" : "boolean"
                                    }
                                }
                            ]
}
