### ISSUE TITLE
[Question] How to generate html based on form and submission in C# code?

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3596]
Hi,

I need to export the form to PDF. However, as I know, formio doesn't support generating PDF same 100% as the form is designed.
Therefore, I need HTML to convert to PDF.

So how to generate html based on form and submission in C# code?

Thanks

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
