### ISSUE TITLE
addItem in single select component

### ISSUE THREAD

**Issue by shadyphp** [formio/formio.js#3598]
Hey, is there a way for single select component to give the possibility of adding new items when the search query has no matches?

**Comment by wag110894** [comment]
Hello, you can accomplish this when using the select component using when the Data Source Type is set to Resources. 

Steps:
1. Create a resource with a Text Field. 
2. Fill out the data that you want in the dropdown.
3. Create a form.
4. Drag over a select component.
5. Change the Data Source Type to Resources
6. Change the Resource to the correct Resource.
7. Change the Value Property to the name of the Text Field that you added to the resource.
8. Scroll down and you will see a checkbox 'Add Resource '. Check this check box. Note you will see a conditional Textfield show with an option to change the label of the 'Add Resource' button.

Video of this functionality working:  
https://share.getcloudapp.com/6quxZpO4

**Comment by shadyphp** [comment]
I'm sorry i don't think that's what i'm looking for. I use json instead of a builder. And I can already pre-populate my input however i want.

Single select examples: [https://formio.github.io/formio.js/app/examples/select.html](url)

If you type in the search box and the option doesn't exist, it displays an error message "No results found", but what i'm looking for is for the ability to add a non existing option to the dropdown. So instead of "No results found" should be "Add [query]" or something like that.

**Comment by Maximjon** [comment]
@wag110894 
> Hello, you can accomplish this when using the select component using when the Data Source Type is set to Resources.
> 
> Steps:
> 
> 1. Create a resource with a Text Field.
> 2. Fill out the data that you want in the dropdown.
> 3. Create a form.
> 4. Drag over a select component.
> 5. Change the Data Source Type to Resources
> 6. Change the Resource to the correct Resource.
> 7. Change the Value Property to the name of the Text Field that you added to the resource.
> 8. Scroll down and you will see a checkbox 'Add Resource '. Check this check box. Note you will see a conditional Textfield show with an option to change the label of the 'Add Resource' button.
> 
> Video of this functionality working:
> https://share.getcloudapp.com/6quxZpO4

Did as written and shown in the video. In developer mode, everything works.
However, in user mode, HTTP error 400 occurs
Problem with permissions?

**Comment by AlexeyDavyd** [comment]
@Maximjon What do you mean by user mode?

**Comment by Maximjon** [comment]
> @Maximjon What do you mean by user mode?

I mean the form open by url from the Launch section
Using on premise the installation

Russian's:
Имею ввиду форму открытую по url из раздела Launch
Используется on premise инсталляция

**Comment by sanjeetkumarit** [comment]
> I'm sorry i don't think that's what i'm looking for. I use json instead of a builder. And I can already pre-populate my input however i want.
> 
> Single select examples: [https://formio.github.io/formio.js/app/examples/select.html](url)
> 
> If you type in the search box and the option doesn't exist, it displays an error message "No results found", but what i'm looking for is for the ability to add a non existing option to the dropdown. So instead of "No results found" should be "Add [query]" or something like that.
> 
> I looked into choices.js that formio select uses and this library has the ability to add custom items using parameter "addItems:true" which i specify in my json config like this:
> `"customOptions": { "addItems": true },`
> 
> But unfortunately this does not work for me

Did u got the solution??

**Comment by Maximjon** [comment]
> Did u got the solution??
No. Support opened case
