### ISSUE TITLE
[Question]Adding a New Component

### ISSUE THREAD

**Issue by Zash0012** [formio/formio.js#3602]
How to add a map component in this project.

**Comment by wag110894** [comment]
Here is an example of how you can accomplish this: https://formio.github.io/formio.js/app/examples/customcomponent.html
Here is additional documentation: https://github.com/formio/contrib

**Comment by Zash0012** [comment]
Thank You So Much!!!!!!!!!

**Comment by dcmadushani** [comment]
Hello @Zash0012, Are you able to add new component to formio.js project

Hello @wag110894 I'm able to add new custom component to contrib project. And also I tried to same thing in formio.js project, but It's not working.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
