### ISSUE TITLE
[QUESTION] What is the use of documentation?

### ISSUE THREAD

**Issue by Zash0012** [formio/formio.js#3604]
documentation: '/userguide/#textfield'
in the schema function

**Comment by Zash0012** [comment]
documentation: '/userguide/#textfield'
in the schema function

**Comment by travist** [comment]
I don't know if I understand your question.

**Comment by Zash0012** [comment]
Got the Answer.
It was for creating a url for documentation
Thanks..........

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
