### ISSUE TITLE
[BUG] I have converted pdf to html and uploaded.I has set the pdf src but it is fail.

### ISSUE THREAD

**Issue by QThans** [formio/formio.js#3610]
When I set the src of the pdf model, the loading component is always in loading.

**Comment by QThans** [comment]
`
<html>

<head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
    <script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
    <script type='text/javascript'>
        window.onload = function () {
            var jsonElement = document.getElementById('json');
            var formElement = document.getElementById('formio');
            var subJSON = document.getElementById('subjson');
            new Formio.FormBuilder(document.getElementById("builder"), {
                display: 'pdf',
                components: [],
                settings: {
                    pdf: {
                        "id": "ycxcybt",
                        "src": "http://ynorgdept.uinge.cn:10104/pdf/ycxcybt"
                    }
                }
            }, {
                baseUrl: 'http://ynorgdept.uinge.cn:10104'
            });
        }
    </script>
</head>

<body>
    <div id="builder"></div>
</body>

</html>
`

**Comment by QThans** [comment]
` window.onload = function () {
            new Formio.FormBuilder(document.getElementById("builder"), {
                display: 'pdf',
                components: [],
                settings: {
                    pdf: {
                        "id": "ycxcybt",
                        "src": "http://ynorgdept.uinge.cn:10104/pdf/ycxcybt"
                    }
                }
            }, {
                baseUrl: 'http://ynorgdept.uinge.cn:10104'
            });
        }`

**Comment by QThans** [comment]
```
 window.onload = function () {
            new Formio.FormBuilder(document.getElementById("builder"), {
                display: 'pdf',
                components: [],
                settings: {
                    pdf: {
                        "id": "ycxcybt",
                        "src": "http://ynorgdept.uinge.cn:10104/pdf/ycxcybt"
                    }
                }
            }, {
                baseUrl: 'http://ynorgdept.uinge.cn:10104'
            });
        }
```

**Comment by travist** [comment]
I am assuming that you are pointing this to our Enterprise PDF Server?  This will only display if it is pointing to our enterprise pdf server.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
