### ISSUE TITLE
[Question] Can we use other icons?

### ISSUE THREAD

**Issue by oliverbj** [formio/formio.js#3612]
Hi there!

Let me start by saying that Form.io is awesome! What a wonderful and well-crafted package 👍🏽 

I was wondering if it was possible to use another icon set than FontAwesome in the builder?:

![Skærmbillede 2020-12-28 kl  15 40 02](https://user-images.githubusercontent.com/7851696/103221469-0581ae80-4923-11eb-9621-0953d584a18a.png)

And if yes, how can I define the icons?

**Comment by travist** [comment]
Currently we do require font-awesome, but the templates can be overridden to provide your own iconset. See https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/iconClass.js.  This method can be overridden to provide different icon sets to show different icons.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
