### ISSUE TITLE
Custom conditionals and Custom validation not working (v.2.29.0)

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#362]
I did an upgrade from version 2.28.5 to 2.29.0 and all custom conditionals and custom validations that I had for the projects stopped working.
All components show even when they should not and validation errors are not triggered.

Downgraded to 2.28.5 and everything works fine again.

**Comment by travist** [comment]
Will you provide an example of the JSON of your form that started breaking? We changed these methods to use ```new Function``` instead of ```eval``` and I am sure we are not passing in a variable that you need.

**Comment by cabrerabywaters** [comment]
Of course, sorry that I cannot provided a shorter version for now, but find attached the codepen

https://codepen.io/cabrerabywaters/pen/zppZPw

You need to select "Field scouting" in the second question and then go all the way to the second page to see that all validations for the table are not working. Values in the cells should not be greater than the first cell of the row.
Another thing that I notice is that default values are also not showing.

**Comment by cabrerabywaters** [comment]
@travist is it possible that we could set up some testing for this basic functionalities? I would love to at least have some functional testing with cyress.io for the basics things that you can do in Form.io. Would love to help on that if needed/wanted.

**Comment by travist** [comment]
I would be very happy to get some testing with these things and would welcome your help. We already have a few unit tests in place within the test folder using Karma + Mocha. If that is sufficient, then feel free to add a test that breaks with this use case.
