### ISSUE TITLE
[Question]How to add a image in a question?

### ISSUE THREAD

**Issue by Zash0012** [formio/formio.js#3621]
Prepopulated Image in Question.

**Comment by travist** [comment]
You would need to just have an HTML Element component above the input, and then just hide the label on the input element. HTML Element components allow for images.

**Comment by oliverbj** [comment]
As @travist said, you can just do this:

**Element:** HTML
![Skærmbillede 2021-01-05 kl  11 16 51](https://user-images.githubusercontent.com/7851696/103634581-8ce4a880-4f47-11eb-8f69-650d4d13612e.png)

**Comment by travist** [comment]
You could also just skip the "div" tag and make the tag "img" with the attributes "src" and "alt" provided in the attributes section, but this works as well. Thanks for the help @oliverbj
