### ISSUE TITLE
[BUG] Change theme of the ACE editor

### ISSUE THREAD

**Issue by oliverbj** [formio/formio.js#3624]
I am trying to change the theme in the Ace editor:

I am using the code snippet from the issue #3464 as below:
 
```javascript
const addAce = Formio.Components.components.component.prototype.addAce;
          Formio.Components.components.component.prototype.addAce = function (element, settings, onChange) {
          return addAce.call(this, element, settings, onChange).then(function (editor) {
                 editor.setTheme('nord-dark');
                 return editor;
          });
};
```

Next, I initialize the builder:

```javascript
let builder = Formio.builder(document.getElementById('builder'), {}, {....
```

The builder and everything is rendering fine, but the theme of the Ace editor has not changed.

**Comment by travist** [comment]
You probably need to include the CSS and JS of that theme along with your application. Can you verify that you are also including those files to apply the theme?

**Comment by oliverbj** [comment]
That was indeed the error, thanks Travis!
