### ISSUE TITLE
[BUG REPORT] Overriding custom component title not working

### ISSUE THREAD

**Issue by oliverbj** [formio/formio.js#3629]
I have created a custom component, that is extending the `NestedArrayComponent`, and I am trying to override the title in the Edit Form modal:

```javascript
static schema(...extend) {
     return NestedArrayComponent.schema({
         type: 'editgrid',
         title: 'Apply to Each',
         key: 'applyToEach',
     }, ...extend);
}
```

As you can see, I have added the `title: Apply to Each`, in the schema that I am extending. However, this is not reflected in the builder:

![Skærmbillede 2021-01-02 kl  17 17 08](https://user-images.githubusercontent.com/7851696/103461383-5ed05000-4d1e-11eb-90f0-c7d8f9d39b0d.png)

**Comment by travist** [comment]
It should be ```label: 'Apply to Each'```` not ```title```
