### ISSUE TITLE
[Question] How to evaluate javascript from custom component

### ISSUE THREAD

**Issue by oliverbj** [formio/formio.js#3631]
Hi guys

I have build a custom component around the `selectboxes` called `DynamicSelectBoxes`. In the data tab of this custom component, I would like to allow my users to input custom javascript, which should be rendered as select boxes (just like you can in the Select dropdown component. For example:

```javascript
values = [{
  "label": "Label 1",
   "value": "val1"
},{
  "label": "Label 2",
   "value": "val2"
}];
```

Should be rendered as two checkboxes:

```html
<input type="checkbox" value="{{values[0]['value']}}"> {{values[0]['label']}}
<input type="checkbox" value="{{values[1]['value']}}"> {{values[1]['label']}}
```
However, I am not sure how I can accomplish this, as I do not know how to evaluate the inputted string as javascript. 
I've been looking through the source code for multiple components, and I cannot see where/how this is done.

This is my progress so far:

**1. I have defined the template**:

```javascript
Templates.templates.bootstrap.dynamicSelectBoxes = {
    form: `<div class="form-check checkbox">
    {% ctx.values.forEach(function(item){ %}
       <input type="checkbox" value="{{item.value}}"> {{item.label}}
    (% }) %}
    </div>`
};
```

**2. I have extended the schema**:

```javascript
static schema() {
      return FieldComponent.schema({
          type: 'dynamicSelectBoxes',
          inputType: 'checkbox',
          key: 'dynamicSelectBoxes',
          label: 'Select Boxes (Dynamic)',
          dataGridLabel: true,
          labelPosition: 'right',
          data: {
              javascript: ''
          },
      });
}
```

**3. I have added a javascript editor to the data tab**:

```javascript
{
      key: 'data.javascript',
      type: 'textarea',
      as: 'javascript',
      editor: 'ace',
      input: true,
      label: 'Dynamic Values',
      tooltip: 'Javascript expression'
},
```

**4. I have added this to the render function**:

```javascript
public render(children) {
        const info = this.inputInfo;
        return super.render(this.renderTemplate('dynamicSelectBoxes', {
            input: info,
            checked: this.checked,
            values: this.component.data.javascript //this I have added <--
        }));
}
```

Now when rendering this, obviously I get the error `values.forEach is not a function`, as it is interpreting it like a string:

![Skærmbillede 2021-01-05 kl  10 53 00](https://user-images.githubusercontent.com/7851696/103632203-42156180-4f44-11eb-8f93-de5d80c7e5f6.png)

Can someone guide me in the right direction here? How can I allow the users to input custom javascript and evaluate that and use it in the render?

**Comment by travist** [comment]
This probably means that ```this.component.data.javascript``` is not an Array since you are trying to iterate over it using "forEach" in the template.

**Comment by travist** [comment]
You will need to call "eval" on it.  https://www.w3schools.com/jsref/jsref_eval.asp

But be careful, this really opens up issues with XSS.  You can also consider using the Form.io evaluation system with ```instance.evaluate``` which adds protections around JS evaluations.

**Comment by oliverbj** [comment]
@travist Thanks! I did not know about `instance.evaluate`. However, I am not complety sure I understand how Form.io does it.

For example, in the Custom Default Value, you must specify `value = ` in order to set the default value.

How can I specify in my custom component, that users must write `values = `? And where should I add the `instance.evaluate`?

To the render, like so:

```javascript
public render(children) {
        const info = this.inputInfo;
        return super.render(this.renderTemplate('dynamicSelectBoxes', {
            input: info,
            checked: this.checked,
            values: this.instance.evaluate(this.component.data.javascript) //this I have added <--
        }));
}
```

**Comment by travist** [comment]
I believe the code should look like the following.

https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L2238

Also, ```instance``` is only used inside of the eval function. If you are overriding a method, then "instance" is not needed and you can just use "this"
