### ISSUE TITLE
[Bug Report] Resetting currency field

### ISSUE THREAD

**Issue by oliverbj** [formio/formio.js#3635]
I have a form with a simple currency field and a reset button:

![Skærmbillede 2021-01-06 kl  22 05 37](https://user-images.githubusercontent.com/7851696/103819750-543def80-506b-11eb-911d-83047481b784.png)

When I click on the "Reset" button, I get the below error:

> Uncaught Error: The 'value' provided to Text Mask needs to be a string or a number. The value received was [null]

It seems like the input mask on the currency field does not allow for `null` values, which is what the `reset` button component will set all component's values to.

**Comment by wag110894** [comment]
Hello @oliverbj, can you provide a JSFiddle of the issue occurring?

**Comment by oliverbj** [comment]
Weirdly enough, I tried to recreate this issue this morning in JSFiddle, but couldn't. It also works in my own application now. I will keep an eye out if it occurs and re-open this. 

For now, all is good :)
