### ISSUE TITLE
[QUESTION] How to import the components in formiojs/contrib?

### ISSUE THREAD

**Issue by waterbuckit** [formio/formio.js#3637]
I've been browsing through all the issues to find an example of how I can use the components from `formiojs/contrib`, namely the location component but I cannot find a conclusive example of how to import it?

I've looked at https://formio.github.io/formio.js/app/examples/customcomponent.html but I am struggling to glean much in regards to this.

So far I've been trying: 
```js
import { Formio } from 'formiojs';
import Location from 'formiojs/contrib/location/Location';

Formio.use(Location);

Formio.builder(document.getElementById('builder'), {}
{
    builder : {
        custom: {
            title: 'location',
            components: {
                location : true
            }
        },
    },
}).then((builder) {
   //
});
```
I've tried also just importing `formiojs/contrib` but then it says about unknown plugins? 

Best regards and many thanks

**Comment by travist** [comment]
As the documentation @ https://github.com/formio/contrib states, it should be

```js
import { Formio } from 'formiojs';
import FormioContrib from '@formio/contrib';
Formio.use(FormioContrib);
```

Once you do that, you can then see the Location component class added to the components list like so...

```js
console.log(Formio.Components.components.location);
```

If you need to extend it, you would do the following.

```js
const LocationComponent = Formio.Components.components.location;
class MyLocation extends LocationComponent {

}
```

**Comment by waterbuckit** [comment]
I'm afraid to say that [https://github.com/formio/contrib](url) only contains the "CheckMatrix" component, which I can see in the builder as per your instruction, however ;location is in the actual formio.js package, which has a `contrib` directory containing edittable, location, modaledit and stripe, location is not in [https://github.com/formio/contrib/tree/master/src](url).

**Comment by travist** [comment]
Those were 3.x components. The code is still there, but they would need to be migrated to the 4.x codebase.  Here they are.

https://github.com/formio/formio.js/tree/3.x/src/contrib

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
