### ISSUE TITLE
[BUG] Datagrid columns do not adjust to content size

### ISSUE THREAD

**Issue by elibus** [formio/formio.js#3638]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.13.0-rc.5
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Go here: https://jsfiddle.net/zvn03yq2/
2. Check out section 4.a. The datagrid has equally sized columns. Width do not adjust to content size anymore.

## Expected behavior
Column width adjusts to content size.
We would expect this behavior with "Equal column width" option checked. 

## Observed behavior
`td` HTML elements get a `col-md-2` class which is forcing the content to fit two bootstrap columms.

## Example
https://jsfiddle.net/zvn03yq2/

Introduced with PR #3544

**Comment by elibus** [comment]
Hi @heather-formio I am tagging you so you this is Marco

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
