### ISSUE TITLE
Feature Request - add evalContext to data available in html component

### ISSUE THREAD

**Issue by jbarrus** [formio/formio.js#3640]
The evalContext provided to scripts has a lot of useful pieces of information to use in scripts. As far as I can tell, the HTML component has a more limited set of data provided to it. Is there any reason the whole evalContext couldn't be given to the html element for interpolation? 

https://github.com/formio/formio.js/blob/master/src/components/html/HTML.js#L65
https://github.com/formio/formio.js/blob/master/src/Element.js#L513

As a side note, I found it useful that the evalContext can be added to from the "options" property on the form editer/renderer. I couldn't find any examples/documentation of this.

e.g.
```javascript
{
  "evalContext": {
    "currentUser": "jeffrey"
  }
}
```

**Comment by travist** [comment]
We are happy to add other variables to this evalContext. Feel free to submit a pull request to this library and we will commit them for a future release.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
