### ISSUE TITLE
[Question] How to only allow select time is 00, 15, 30, 45?

### ISSUE THREAD

**Issue by ghost** [formio/formio.js#3644]
Hi,

For the **Time Component**, how to only allow user to select a time with 00, 15, 30, 45?
Besides, how to calculate total time based on start time -> end time?

For example (please see the attached picture): 07:30 PM -> 09:30 PM => 2 hours

Thanks

![image](https://user-images.githubusercontent.com/58280615/104169483-3b01be00-5432-11eb-9204-c00432e48cdc.png)

**Comment by wag110894** [comment]
Hello @thanhvietnguyen255, 

Thank you for reaching out! We currently do not support this feature. However, we offer the option to sponsor the development of a Custom Feature. We estimate this effort at 12 hours. If you are interested in moving forward, contact support@form.io and we can provide you a formal quote. For reference, the ticket number is FIO-1127.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
