### ISSUE TITLE
[Question] How to set scroll down body for the Table Component?

### ISSUE THREAD

**Issue by thanhvietnguyen255** [formio/formio.js#3646]
Hi,

How to set scroll down the body for the Table Component so it can keep the Header?

Here is form-builder
![image](https://user-images.githubusercontent.com/58280615/104170523-db0c1700-5433-11eb-87cb-7fd46b97ea58.png)

Here is form
![image](https://user-images.githubusercontent.com/58280615/104171018-93d25600-5434-11eb-8dd6-f3d320dd8540.png)

Thanks.

**Comment by travist** [comment]
This would require some custom CSS to be added to your application that embeds the Form.io rendered form. There are several tutorials online with how to do this with HTML.

**Comment by thanhvietnguyen255** [comment]
Thanks for your answer @travist
However, it doesn't have thead and tbody tags so cannot set scroll for tbody and keep thead.

I have designed that table by way use the Table Component, then set **Number of Rows** and the header is the first row.

![image](https://user-images.githubusercontent.com/58280615/104259128-5eb91880-54b3-11eb-8b1f-22c224a6e333.png)

![image](https://user-images.githubusercontent.com/58280615/104259636-63ca9780-54b4-11eb-9fa4-2f8a95b0e71f.png)

**Comment by travist** [comment]
You will then need to just override the table template, which can be found @ https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/table/form.ejs and you can use the following documentation to know how to accomplish this. https://github.com/formio/formio.js/wiki/Templates-API#overriding-templates
