### ISSUE TITLE
What is the best way to integrate this plugin styles with postcss pirgecss ?

### ISSUE THREAD

**Issue by Samanoova** [formio/formio.js#3649]
hi I am using tailwind and purgecss in my project 
and there is just bootstrap and semantic templates I hope if there is someway to use tailwind instead of bootstrap you can consider that as a request feature but the real problem now that I cant controlling the purge operation on formio dom in the correct way because the dom is coming from js files if any body have some good idea help me please 

here is my postcss.config.js file 

```
module.exports = {
  plugins: [
    require("tailwindcss"),
    require("autoprefixer"),
    require("@fullhuman/postcss-purgecss")({
      content: ["./src/**/*.vue", "./public/index.html","./node_modules/**/*.vue"],
      defaultExtractor:content=>content.match(/[A-Za-z0-9-_:/]+/g) || [],
    })
  ]
};

```

I tried the following 

```
module.exports = {
  plugins: [
    require("@fullhuman/postcss-purgecss")({
      content: ["./node_modules/@formio/bootstrap3/lip/templates/bootstrap3/**/*.ejs.js"],
      defaultExtractor:content=>content.match(/[A-Za-z0-9-_:/]+/g) || [],
    })
  ]
};
```
but I think that the default extractor didn't work with js files or something like that

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
