### ISSUE TITLE
[Question] How to focus on wrong/invalid field when submitting?

### ISSUE THREAD

**Issue by thanhvietnguyen255** [formio/formio.js#3650]
Hi,

As the title, how to focus on wrong/invalid field when submitting?
For example: when user clicks the submit button if there are any fields that are invalid then it will focus on that field instead of I need to scroll up to find.

Thanks.

**Comment by travist** [comment]
There is a method on the component instances called ```scrollIntoView```.  You can use something like the following.

```js
form.on('componentError', (error) => {
  var comp = form.getComponent(error.component.key);
  if (comp) {
    comp.scrollIntoView();
  }
});
```

**Comment by thanhvietnguyen255** [comment]
It works, thanks for your answer.
