### ISSUE TITLE
FEATURE REQUEST - Variables exposed in Logic Tab of a component configuration

### ISSUE THREAD

**Issue by kamaloush** [formio/formio.js#3653]
I am writing this issue in order to propose a PR on formio/formio.js repository.
Original issue from wrong repository (@formio/angular):
[FEATURE REQUEST - Variables exposed in Logic Tab of a component configuration](https://github.com/formio/angular/issues/638#issue-728519016)

- Hosting type
  - [] Form.io
  - [x] Local deployment
- Angular Formio version: 4
- Frontend framework: ionic

I would like to propose an feature wich could be very usefull. Let me explain :
Currently, in the tabs of a component configuration, they are two tabs : Validation and Logic.
In Validation, we can define a custom validation with this variables :
![image](https://user-images.githubusercontent.com/26444823/97052572-874f0780-1581-11eb-8628-70ef6bafa896.png)
This variables are very usefull if we want to create XMLHttpRequest, play with the angular application exported functions etc.
But, in Logic Tab, wich is more interesting because we define a trigger customised, we have only access to 3 type of actions :
![image](https://user-images.githubusercontent.com/26444823/97052908-2b38b300-1582-11eb-9e24-43926c2bfa62.png)
And no ones of this 3 actions permits to use variables as the Validation tab.
Add a trigger could prevent to write redondant javascript code if else in our Validation tab.
I will may create a fork to implemente this in next months but it will be interesting to see your point of view about that.

Thanks for reading !

**Comment by travist** [comment]
Thanks for your pull request! We will evaluate it for a future release.

**Comment by kamaloush** [comment]
Glad to serve you :-)
