### ISSUE TITLE
[Question] formio.js version compatible with bootstrap 3

### ISSUE THREAD

**Issue by jiteshjethwa** [formio/formio.js#3659]
## Environment
Hi there, I am able to use formio.js for rendering custom form on standalone page. We have integrated theme which is using bootstrap 3 version in our project. I need to integrate formio.js on one of existing page where bootstrap 3 version is added. I can not upgrade to bootstrap 4 as current theme is dependent on bootstrap 3 version.

Can anyone tell me do we have formio.js version compatible with bootstrap 3 ? If yes please share details.

- Formio.js version : 4.12.2-rc.5
- Browser : Chrome

## Steps to Reproduce
1. Use bootstrap 3 version libraries instead of bootstrap 4 for wizard with multiple tabs form

## Expected behavior
For bootstrap 3 version wizard with multiple tab should be rendered properly without breaking ui

## Observed behavior
When bootstrap 3 version is used wizard with multiple tabs is not getting rendered properly. Also date fields are not rendered properly

## Example
PFA which contains screenshot of broken(formUsingBootstrap3.png) and working(formUsingBootstrap4.png) ui.
![formUsingBootstrap3](https://user-images.githubusercontent.com/55083420/104633590-605a2a80-56c5-11eb-8327-a6d11718b41d.png)
![formUsingBootstrap4](https://user-images.githubusercontent.com/55083420/104633593-618b5780-56c5-11eb-88a6-3f9989fffc83.png)

**Comment by travist** [comment]
You just need to do the following.

```
Formio.Templates.framework = 'bootstrap3';
```
