### ISSUE TITLE
Datagrid rendering on adding around 10 rows becomes very slow

### ISSUE THREAD

**Issue by Navpreet2289** [formio/formio.js#366]
I have used Datagrid in formio wizard and Datagrid rendering on adding around 10 rows becomes very slow.

<img width="1280" alt="screen shot 2018-02-14 at 2 48 31 pm" src="https://user-images.githubusercontent.com/23264074/36201728-2b13d1ae-1196-11e8-82a9-ada53aed2877.png">

**Comment by jhen1422** [comment]
We have been unable to replicate this on our end.

Are you still experiencing issues with the data grid rendering?
