### ISSUE TITLE
calculated text field based on selected option

### ISSUE THREAD

**Issue by framatt** [formio/formio.js#3663]
I know simple question, but I am unable to get this working.

I want a text field in a datagrid to be updated with the value of a select field in the same grid.

What I have as a calculated field is "value = data.select1.value"

What should be the correct calculation?

**Comment by wag110894** [comment]
Hello @framatt,

Here is an example of how to accomplish this:
`https://nmgcbrljtnzpzxw.form.io/gh3663`

I hope that this helps.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
