### ISSUE TITLE
select component type URL issue

### ISSUE THREAD

**Issue by fadelsahmarani** [formio/formio.js#3668]
## Environment

- Hosting type
  - [x] Local deployment
- Formio.js version: v4.13.0-rc.6
- Frontend framework: JavaScript
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. Drag and drop a select component
2. Click on tab "Data"
3. Select URL in "Data Source Type" 
4. Insert into "Value Property" value ( id )
5. Insert into "Limit " value ( 15 )

## Expected behavior
When selecting a value that isn't displayed in the first page it should show the text as first page results.
![image](https://user-images.githubusercontent.com/41676532/104908456-2ae86200-598f-11eb-8524-fba86dd8e24e.png)

## Observed behavior
When selecting a value that isn't displayed in the first page it shows the id.
![image](https://user-images.githubusercontent.com/41676532/104908825-aba75e00-598f-11eb-97b9-8b2989bf7e95.png)

When searching inside after selecting as the previous issue
![image](https://user-images.githubusercontent.com/41676532/104909374-6b94ab00-5990-11eb-863e-56dbb60b7472.png)

**Comment by wag110894** [comment]
hello @fadelsahmarani,
Can you provide a form embed URL or a sandbox of the form so we can take a look at your settings?

**Comment by fadelsahmarani** [comment]
hello @wag110894 ,
Here is my sandbox id 6006931894b96b03903e667f but my API is private and will not work ,I think the issue because my API returns 15 record and when you search it gives more data related to text searched.
for example it will show 15 records of countries with letter "A" when you search for country "Z" the bug will be shown.
Knowing that when selecting item from first 15 record with letter "A" the bug will not be shown as attached.
![image](https://user-images.githubusercontent.com/41676532/105006135-e5836d80-5a3e-11eb-9469-7f4cd8abed15.png)

**Comment by wag110894** [comment]
Hello @fadelsahmarani,
We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. Please contact support@form.io if you are interested in a support package.

**Comment by sergiikifiak** [comment]
We are facing with the same issue. Any update on this one?
