### ISSUE TITLE
programmatically set field value of component1 from isnide custom default value scripts of component2

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#3672]
Hi Travist,

Is it possible to get same form object inside custom default value script of a component?
Background of this - I wanted to update component1's value from component2's custom default value script based on some logic.

is there way to update like this?

Thanks,
Sriram

_Originally posted by @sriram275 in https://github.com/formio/formio.js/issues/3011#issuecomment-762901122_

**Comment by travist** [comment]
The Logic system should be able to do this. There is a "Merge Component Schema" action that allows a component schema to alter based on an event that it is responding to. This should achieve what you are looking to do.

**Comment by sriram275** [comment]
We tried this way and it is working. But this is kind of writing more scripts to achive this.  Do you have any plan to expose whole form object like you have suggested ( https://github.com/formio/formio.js/issues/3011#issuecomment-656352014 ) with in custom default scripts area? So we can achive everything in one place.

Thanks.

**Comment by travist** [comment]
That is exposed.  You can use ```instance.root``` to gain access to the form instance.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
