### ISSUE TITLE
Select data

### ISSUE THREAD

**Issue by ActiveBaby** [formio/formio.js#3673]
Hello. I want use response from out server to values in "Select". I make this in button, but its don't work :(

      fetch('url_here',{method: "POST", body: data.serviceId})
      .then(function (response) {
        return response.json()
        })
      .then(function (data) {
        var datez = data;
        if (datez == 1){
          data.select = [
          {value: 'apple', label: datez},
          {value: 'banana', label: 'Banana'},
          {value: 'pear', label: 'Pear'},
          {value: 'orange', label: 'Orange'}
           ]
          alert("okay" + datez)
        }});

But if i create a button with code:

          data.select = [
          {value: 'apple', label: 'apple'},
          {value: 'banana', label: 'Banana'},
          {value: 'pear', label: 'Pear'},
          {value: 'orange', label: 'Orange'}
           ]

its work. Maybe i do something wrong? Thanks!

**Comment by travist** [comment]
This can be done with the Logic tab of the Select component, and using the Merge Component Schema.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
