### ISSUE TITLE
[BUG] Duplicate Select

### ISSUE THREAD

**Issue by ActiveBaby** [formio/formio.js#3674]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: Application: 7.0.42, Renderer: 4.12.4
- Frontend framework:
- Browser: Google Chrome / Safari
- Browser version:

## Steps to Reproduce
1. Create a button and "Select"
2. Paste button custom logic 

data.select = [
          {value: 'apple', label: 'Appleрр'},
          {value: 'banana', label: 'Banana'},
          {value: 'pear', label: 'Pear'},
          {value: 'orange', label: 'Orange'}
        ]

3. See result 

<img width="1011" alt="Снимок экрана 2021-01-20 в 1 39 17" src="https://user-images.githubusercontent.com/8532143/105102783-66cf1480-5ac0-11eb-9ad8-106ba14d1d41.png">

**Comment by wag110894** [comment]
Hello @ActiveBaby,

Thanks for reaching out. We are able to replicate this issue on our side. We have created a ticket. For reference, the ticket is FIO-1207.

We have added this to our backlog. We welcome a pull request or a process to expedite. We will let you know once this issue is resolved.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution! The ticket is in 'Done' status
