### ISSUE TITLE
Data grid component responsive design

### ISSUE THREAD

**Issue by fadelsahmarani** [formio/formio.js#3676]
## Environment

- Hosting type
  - [x] Local deployment
- Formio.js version: v4.13.0-rc.6
- Frontend framework: JavaScript
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. Drag and drop a data grid component
2. Add up to 6 7 components inside

## Expected behavior
on small screen scroll must be added
![image](https://user-images.githubusercontent.com/41676532/105175511-b814ed80-5b2c-11eb-8d9d-375b0a56f323.png)

## Observed behavior
on small screen without scroll
![image](https://user-images.githubusercontent.com/41676532/105175405-88fe7c00-5b2c-11eb-980a-f66db17aea2a.png)

**Comment by wag110894** [comment]
Hello @fadelsahmarani, 

We are not able to replicate this issue on our side. Can you provide a JSFiddle so that we can try and replicate it?

Looking forward to your response.

Thank you!

**Comment by fadelsahmarani** [comment]
Dear,
600e76906c552bf551b3f2b2 here is sandbox of this issue but you must make your browser to the smallest screen
![image](https://user-images.githubusercontent.com/41676532/105675548-f5dd9180-5ef1-11eb-94e8-d1a3340ab93e.png)
Knowing that grid have more columns like this:
![image](https://user-images.githubusercontent.com/41676532/105675684-202f4f00-5ef2-11eb-80a6-c5595022b2b3.png)

**Comment by wag110894** [comment]
I am not able to replicate on the sandbox using chrome. 
Video: https://share.getcloudapp.com/8LukBJoD
Version 88.0.4324.96

**Comment by fadelsahmarani** [comment]
Dear @wag110894 ,
I appreciate your reply kindly note my fix in the video uploaded
Video: https://share.getcloudapp.com/p9u8gkAR
.formio-component-dataGrid{
    overflow: auto;
}
but this may affect another inputs inside data grid but that's my try

**Comment by wag110894** [comment]
Hello @fadelsahmarani, 

Great to see you got the issue resolved!

**Comment by fadelsahmarani** [comment]
Hello @wag110894 ,
yes but affects the other components like dropdown will be opened under the data grid
sandbox: 60118251410ebf2a0c519310
![image](https://user-images.githubusercontent.com/41676532/106010631-54f20080-60c2-11eb-9275-8be956a20534.png)

**Comment by afirulaf** [comment]
Any update on this? Dropdown in datagrid is making the whole datagrid wonky.

**Comment by kkaragki** [comment]
Is there any update on this at all?? 
I used the `overflow: auto;` CSS rule in my DataGrid, but I couldn't get past the issue of the dropdown that will be opened under the DataGrid.

![Untitled](https://user-images.githubusercontent.com/15421575/166895896-36ba7350-6510-4e24-94ad-72e10b6ec67d.png)

**Comment by nazmul-prince** [comment]
Choice Js select component will have this overflow issue. If you use HTML 5 select component then the issue should be resolved. But again this is not the solution because there are cases where you might need choice Js select component.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
