### ISSUE TITLE
Form.IO how to form.on('change', function(event) for component inside then "editgrid" component 

### ISSUE THREAD

**Issue by HLSAW** [formio/formio.js#3681]
Formio.icons = 'fontawesome';
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/customerload')
  .then(function(form) {
    // Triggered when they click the submit button.
    form.on('change', function(event) {
      if (event.changed && event.changed.component.key === 'customerNumber' && event.changed.value) {
        Formio.fetch('https://examples.form.io/customers/submission?data.number=' + event.changed.value, {
          headers: {
            'content-type': 'application/json'
          },
          mode: 'cors',
        })
        .then(function(response) {
          response.json().then(function(result) {
            if (Array.isArray(result) && result.length > 0) {
              var submission = { data: event.data };
              submission.data.name = result[0].data.name;
              submission.data.phoneNumber = result[0].data.phonenumber;
              form.submission = submission;
            }
          });
        });
      }
    });
  });

The above example get from https://formio.github.io/formio.js/app/examples/externalload.html.

if i need to trace the form component change inside the component "editgrid", it is possible and how?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
