### ISSUE TITLE
Create a form with a submission

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#3687]
We're programmatically creating forms and passing the json objects to them.  When running `createForm` it would be preferred if both the definition and submission could be instantiated simultaneously.

Currently changing the submission in the `then` allows for the possibility of some custom javascript on a component acting based on no submission data, where it's already done its action by the time the submission data is immediately applied.

I'd like:
```js
Formio.createForm(document.getElementById('formio'), formDef, { submission })
```

Instead of
```js
Formio.createForm(document.getElementById('formio'), formDef).then(form => form.submission = submission);
```

**Comment by travist** [comment]
I agree with this. I actually would not be that difficult of an addition. If anyone submits a PR for it, we would be happy to accept it.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
