### ISSUE TITLE
How to remove required components and allow form submission?

### ISSUE THREAD

**Issue by tnorthcutt** [formio/formio.js#3689]
A while after [this issue](https://github.com/formio/formio.js/issues/2738), I worked out a way to remove components after a form is rendered. The short version:

```
let thisForm = Formio.createForm(document.getElementById("form"), "https://url-of-the-form");

thisForm.then(form => {
	let componentToRemove = form.getComponent("componenttoremove");
	form.removeComponent(componentToRemove);
	form.redraw();
}
```

However, if the component being removed is a required component, then submitting the form fails.

Is there a way to both remove a component and programmatically/dynamically make it not required?

I know there was [a suggestion in the issue I linked above](https://github.com/formio/formio.js/issues/2738#issuecomment-635386955) to add hidden components to the form, which could then have their value set programmatically, and use conditionals based on those hidden components to control visibility of the actual components I want to hide... Unfortunately, that solution is untenable for our use-case as it introduces so much additional complexity and configuration steps; we'd end up needing a half dozen or more hidden "control" components on some forms.

Any suggestions on ways to proceed would be very much appreciated!

**Comment by travist** [comment]
The only way to have the server cooperate is to use "conditionals" to remove a component. I understand it adds complexity, but unfortunately the server does not care if a field is Hidden or not, it will validate a field as long as it is conditionally relevant. By making the component hide through conditionals is the only way to make both client and server happy.
