### ISSUE TITLE
[HELP] Label Doesn't Render for HMTL Checkboxes

### ISSUE THREAD

**Issue by narutopoa14** [formio/formio.js#3697]
## Environment
Please provide as many details as you can:

I'm trying to use form.io without hosting within a Vue.js app to render a checkbox. I've got prebuilt json that I'm handing to the renderer. I'm using custom components but I've removed them from the form and just left the default HTML checkbox component. When I render the form, all I see is the checkbox with no label next to it. Please let me know if there are any other details that might be helpful or if there's any tips for debugging an issue like this. 

- Hosting type
  - [] Form.io
  - [] Local deployment
    - Version: 
- Formio.js version: 4.12.5
- Frontend framework: Vue.js
- Browser: Chrome
- Browser version: 87.0.4280.141

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

No label next to checkbox:
![image](https://user-images.githubusercontent.com/77999398/105780349-3c58dd80-5f3e-11eb-9877-ad1db2201339.png)

For code or form JSON, please enclose in a code block:

Form 
```js
{
    "components": [
        {
            "label": "Checkbox",
            "tableView": false,
            "key": "checkbox",
            "type": "checkbox",
            "input": true
        }
    ]
}
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
