### ISSUE TITLE
[BUG] FormioUtils.eachComponent not working for Panel with nested Columns components

### ISSUE THREAD

**Issue by valentinmarinro** [formio/formio.js#3719]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ x] Local deployment
    - Version: 
- Formio.js version: v4.12.4
- Frontend framework: Vanilla JS
- Browser: Edge (Chromium)
- Browser version: Version 88.0.705.50 (Official build) (64-bit)

## Steps to Reproduce
Create a schema with Collapsible Panel that with -> Columns split in 2 columns with widths 2 and 10 -> in the second column(the one with width 10)  add another Columns component that I split in 4 columns with width 3 each

FormioUtils.getComponent and FormioUtils.searchComponents failed to get the textfield components that's inside the second Columns component and this is because FormioUtils.eachComponent fails to find the salutation component.

## Expected behavior
Ability to find all textfield components with FormioUtils.searchComponents

## Observed behavior
In my scenario the following methods in FormUtils are not working correctly, except form.GetComponent
                
```js
// !!!FAIL!!! does not return the component inside the second Columns component
let flattenComponents = FormioUtils.flattenComponents(form.components, true);
console.log("flattenComponents", flattenComponents);

// !!!FAIL!!! to return the salutation component
let component = FormioUtils.getComponent(form.components, 'salutation', true);
console.log("getComponent", component);

// !!!FAIL!!! to find any text field component                
let components = FormioUtils.searchComponents(form.components, {
  'type': 'textfield'
});                                
console.log("searchComponents", components);
    
// !!!FAIL!!! finds the 'salutation' component twice             
FormioUtils.findComponent(form.components, 'salutation', null, function (component, newPath, components){
    let id = component.id;   
    console.log("findComponent", component);
});
                
// WORKS :)  the only one that works is form.getComponent;                
let salutation = form.getComponent('salutation');
```

## Example
I've created a sandbox: [601319c98aa7c24a94dd1b00](https://formio.github.io/formio.js/app/sandbox)
Also attached a the same schema as text file [schema.txt](https://github.com/formio/formio.js/files/5889748/schema.txt)

**Comment by valentinmarinro** [comment]
Hi @travist , in this scenario also the highlightInvalidComponents() does not function correctly, I think it is using the same everyComponent method.
I can set multiple text field component to have the same API Key, no unique key validation will be triggered

**Comment by valentinmarinro** [comment]
Hey, it seems the same issues happen if you nest Data Grid with Panels and Columns or just with Columns, the validation for unique key is not triggered and the FormioUtils functions fails to find any component inside the Data Grid

**Comment by wag110894** [comment]
Hello @valentinmarinro,

Thank you for your patience. I have connected with our developer that is looking at this issue. 

Methods from FormioUtils such as flattenComponents, searchComponents, findComponent, getComponent are created to use with components' schemas (NOT instances). form.components returns an array of components instances. Pass form.component.components instead with FormioUtils' methods. 
If you need to iterate through instances, use form.everyComponent((componentInstance) => {
// Do something here
}) 

I hope that this helps.

Thank you.

**Comment by valentinmarinro** [comment]
> Hello @valentinmarinro,
> 
> Thank you for your patience. I have connected with our developer that is looking at this issue.
> 
> Methods from FormioUtils such as flattenComponents, searchComponents, findComponent, getComponent are created to use with components' schemas (NOT instances). form.components returns an array of components instances. Pass form.component.components instead with FormioUtils' methods.
> If you need to iterate through instances, use form.everyComponent((componentInstance) => {
> // Do something here
> })
> 
> I hope that this helps.
> 
> Thank you.

Hi @wag110894, thanks for feedback, but there is still the issue with my particular scenario with nested components where:
1. API key unique validation is not triggered
2. Internal highlightInvalidComponents does not work correctly because everyComponent does not traverse the entire graph of components, it stop at least on Columns component does not check the child components

**Comment by ccontour** [comment]
In the case of **searchComponents**, here is a type definition:

`type searchComponents = (componentList: FormComponent[], query: string): FormComponent[];`

This line here is specifically where the query argument is being used: https://github.com/formio/formio.js/blob/bf486692a652fe1747f9cbf4dd4e68bc3e35d1bd/src/utils/formUtils.js#L128

In the case of the code above, you are passing an object instead of a string, so my expectation would be no results should be returned. An object cannot be compared against another object for equality in this fashion.

---- 

The other calls you have above require more replication / investigation work
