### ISSUE TITLE
[BUG] 404 on 'https://cdn.form.io/ace/1.4.10/mode-js.js' causing loss of form builder functionality

### ISSUE THREAD

**Issue by Squiff-cmd** [formio/formio.js#3726]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: v4.12.4
- Frontend framework: Angular 11
- Browser: Chrome
- Browser version: Chrome 88 on Windows 10

## Steps to Reproduce
On the form builder (In Angular package or Vanilla) drag and drop a 'Data Grid' component from the data component collection. There is no way to configure the input fields that will be rendered as columns of the grid. 

Data grids are still able to be rendered correctly if valid JSON is provided, the issue only occurs in the Form Builder.

I believe this is due to a 404 Not Found when attempting to retrieve mode-js.js at the following which is no longer available 'https://cdn.form.io/ace/1.4.10/mode-js.js'

## Expected behavior
Ability to configure column components within a Data Grid component

## Observed behavior
No ability to configure column components within a Data Grid component

## Example
![image](https://user-images.githubusercontent.com/56453153/106452758-37d17f00-6480-11eb-92b0-3b7a4fad3244.png)

The Issue occurs on all form.io Demos also 
https://formio.github.io/formio.js/app/builder
https://formio.github.io/angular-demo/#/forms/builder

**Comment by travist** [comment]
I do not believe the ace editor bug is related. That should still be fixed, but I don't think that applies here. I am a little confused by how you are trying to "edit" these components within the data grid overview page. You edit the column components within the form builder itself and not in the datagrid page. I don't think there is an issue here and this can be closed.

**Comment by Squiff-cmd** [comment]
I have realised my mistake and I am incorrectly using the data grid component as you mentioned. 
Thank you for responding and closing the item quickly.  :)
