### ISSUE TITLE
[QUESTION] it is possible to use R2L settings ? 

### ISSUE THREAD

**Issue by chiragkanhasoft** [formio/formio.js#3731]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Expected behavior

It is possible to display form in R2L view for such languages like Arabic, Hebrew etc.

## Example

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @chiragkanhasoft,

Apologies on the delay.

You can accomplish this by setting the Form Controller code like so: 
instance.options.language = 'ar-SA'

**Comment by chiragkanhasoft** [comment]
hey @wag110894 ,
Thanks for the reply. i'll try  this.

**Comment by chiragkanhasoft** [comment]
Hey @wag110894,

Could you please share any example for the same , i didn't found how to change it. as well as its not available in this document link as well [https://help.form.io/developers/rtl-forms](https://help.form.io/developers/rtl-forms)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
