### ISSUE TITLE
[QUESTION] Conditional view at complex components.

### ISSUE THREAD

**Issue by tkalanek90** [formio/formio.js#3735]
Hi,

i'd like to ask how i choose condition at complex data types as file, or signature, if i want to show for example textField component, when is file uploaded, or document signed ? 

Thank you. 

![image](https://user-images.githubusercontent.com/29900557/106753527-0eeded00-662c-11eb-874c-9c3cbe663822.png)

**Comment by travist** [comment]
You would need to use the Advanced Conditions to do this, where you can write you own condition (using javascript) which can easily handle complex data types and conditions.

**Comment by tkalanek90** [comment]
Ok thank you for reply.
