### ISSUE TITLE
Security issue with dompurify in v4

### ISSUE THREAD

**Issue by jamesots** [formio/formio.js#3736]
v4 of formio.js has a dependency on dompurify 2.0.11, which has a security advisory against it: https://npmjs.com/advisories/1591. I see that it will be updated in v5, but in the meantime it would be really helpful if v4 of this library could have its dependency updated to at least 2.0.17.

**Comment by travist** [comment]
We had some issues with this upgrade where it broke our portal application. We will revisit the upgrade to see if the issues we ran into have been resolved with the latest version.

**Comment by abhilash-aot** [comment]
any updates on this issue ? getting the same error. 
![image](https://user-images.githubusercontent.com/61222674/108989159-4dbb1400-76bb-11eb-8072-8f9279edc0a7.png)

**Comment by travist** [comment]
No updates, but we are going to attempt to upgrade it in the 4.13.x release. That is still in RC at the moment.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
