### ISSUE TITLE
[BUG]  auto complete for conditions "when" does not show all values when using containers

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3747]
When using the condition builder on a component in the condition tab, the when field has a auto complete to search for a field name. When using containers you can have many fields with the same name/label. The auto complete only seems to return Max 4 results.   The auto complete should return all results and provide scrolling. 

 Urgent workaround is to search by the components path such as : "myContainer.myField".  But it is very buggy feeling as the result only appears once there is a perfect complete match.

**Comment by wag110894** [comment]
Hello @StephenOTT,

Could you provide a JSFiddle or a Sandbox?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
