### ISSUE TITLE
[BUG] If you copy a series of components (such as copying the json of a container) into a new container with a new/different container name, component conditions (when condition) become invalid, but there is no error messaging in the builder to indicate a problem

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3748]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: latest
- Formio.js version: all
- Frontend framework: all
- Browser: all
- Browser version: all

If you copy a series of components (such as copying the json of a container) into a new container with a new/different container name, component conditions (when condition) become invalid, but there is no error messaging in the builder to indicate a problem.

Would expect errors similar to how duplicated component keys will show errors.

As a future feature (or paid feature) would be good to have a linter tooling that runs all sort of checks on depend.  Would help with larger forms!

**Comment by AlexeyDavyd** [comment]
Could you please specify or record a video with problem explained?

One thing that I was able to achieve is component conditions reacting to old trigger after being moved together to a new container.

Like it this form: https://devtest.form.io/condsindiffcontainers

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
