### ISSUE TITLE
[BUG] quill config as content component in the builder

### ISSUE THREAD

**Issue by stormbinary** [formio/formio.js#3749]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [ x] Local deployment
    - Version: 
- Formio.js version:4.12.x
- Frontend framework:
- Browser:Firefoxx
- Browser version: 85.0

## Steps to Reproduce
1. 
2. 
3. 

## Expected behavior
that setting the wysiwyg does not affect the configurations of the editor.

` {
                            title: 'Editor',
                            key: 'editor',
                            icon: 'fal fa-edit',
                            schema: {
                                label: 'Content',
                                type: 'textarea',
                                key: 'editor',
                                editor: 'quill',
                                wysiwyg: {                                  
                                    theme: 'snow',
                                    modules: {
                                        toolbar: [
                                            [{ 'font': [] }],
                                            [{ 'size': ['small', 'medium', 'large', 'huge'] }],
                                            ['bold', 'italic', 'underline', 'strike', { 'script': 'sub' }, { 'script': 'super' }],
                                            [{ 'color': [] }, { 'background': [] }],
                                            [{ 'align': [] }],
                                            [{ 'list': 'ordered' }, { 'list': 'bullet' }],
                                            [{ 'indent': '-1' }, { 'indent': '+1' }],
                                            [{ 'direction': 'rtl' }],
                                            ['clean']
                                        ]
                                    }
                                },
                                input: true,
                                inputType: 'text',
                            }
                        }`

## Observed behavior
 A lot fewer toolbar items in the Quill toolbar

**Comment by wag110894** [comment]
Hello @stormbinary, can you provide a JSffilde of this issue taking place?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
