### ISSUE TITLE
[QUESTION] Setting a default calculateValue for my angular custom component

### ISSUE THREAD

**Issue by paulbors** [formio/formio.js#3753]
I have my own angular custom component and would like to be able to access the full form data that's currently on the screen. How can we go about that?

Here's my simple Save Button for example (this is just an example, component is much more complex but needs access to full form data):

`
    import { Injector } from '@angular/core';
    import { FormioCustomComponentInfo, registerCustomFormioComponent } from '@formio/angular';
    import { SaveButtonComponent } from './save-button.component';

    const DOC_UPLOAD_COMPONENT_OPTIONS: FormioCustomComponentInfo = {
        type: 'saveButton',         // custom type. Formio will identify the field with this type.
        selector: 'save-button',    // custom selector. Angular Elements will create a custom html tag with this selector
        title: 'Save Task',         // Title of the component
        group: 'basic',             // Build Group
        icon: 'stop',               // FontAwesome.com Icon
    //  template: 'input',          // Optional: define a template for the element. Default: input
    //  changeEvent: 'valueChange', // Optional: define the changeEvent when the formio updates the value in the state. Default: 'valueChange',
    //  editForm: Components.components.textfield.editForm, // Optional: define the editForm of the field. Default: the editForm of a textfield
    //  documentation: '',          // Optional: define the documentation of the field
    //  weight: 0,                  // Optional: define the weight in the builder group
    //  schema: {},                 // Optional: define extra default schema for the field
    //  extraValidators: [],        // Optional: define extra validators  for the field
    //  emptyValue: null,           // Optional: the emptyValue of the field
    //  fieldOptions: ['values'],   // Optional: explicit field options to get as `Input` from the schema (may edited by the editForm)
    };
    let initSaveButtonComponent = true;
    export function registerSaveButtonComponent(injector: Injector) {
        if (initSaveButtonComponent) {
            registerCustomFormioComponent(DOC_UPLOAD_COMPONENT_OPTIONS, SaveButtonComponent, injector);
            initSaveButtonComponent = false;
        }
    }
`

`
    <button (click)="onSave()" class="btn btn-primary btn-md">Save</button>
`

`
  export class SaveButtonComponent implements FormioCustomComponent<number> {
    @Input()
    public value: any;

    @Output()
    public valueChange = new EventEmitter<any>();

    @Input()
    public disabled: boolean;

    public updateValue(event) {
        this.value = event.target.value;
        this.valueChange.emit(event);
    }

    public onSave() {
        console.log('Form Data Btn: ', this.value); // How can I access the full form data here not just the API field set for this form field???
    }
}
`

Current working solution is to set a calcualtedValue on the custom form field that's as simple as:
`
value = data;
`

But I would like to set this by default if my custom component settings if possible.

**Comment by wag110894** [comment]
Hello Paul,

Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you have a great day!

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
