### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by praveen5959** [formio/formio.js#3757]
I want to change the look and feel of the forms-builder. I know Templating is available to use Bootstrap, semantic or bulma CSS. But I want to use my own custom theme to change the look and feel of forms-builder. 

Is it possible?

**Comment by AlexeyDavyd** [comment]
You can set up your project to use custom css file. Open project on portal and go 'Settings -> Stage Settings -> Custom JS and CSS'
Or you can create your own tempalte plugin just like we have for bootstrap3 or bulma:
https://github.com/formio/bootstrap3
https://github.com/formio/bulma

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
