### ISSUE TITLE
[BUG] URL component: entering an email address does not trigger error validation

### ISSUE THREAD

**Issue by lakshman-anusha** [formio/formio.js#3758]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:4.11.3
- Frontend framework: JS
- Browser: Chrome/Firefox/Edge
- Browser version:

## Steps to Reproduce
1. Create a form with URL component
2. In the URL field, enter the email address like "abc@test.com"
3. Tab to the form fields
4. Observe the behaviour

## Expected behavior
As "abc@test.com" is not a valid URL, the error validation is triggered when tabbing out of the URL field. The error "The URL field must be a valid url." is displayed below the URL field.

## Observed behavior
When "abc@test.com" is entered in the URL field, the error validation is not triggered when tabbing out of the URL field. No error messages are displayed on the form page.

## Example
![image](https://user-images.githubusercontent.com/53343602/107515254-c62cbb80-6b78-11eb-8bb6-5433d63bd111.png)

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @lakshman-anusha,
Thank you for reaching out!

We have created a ticket and have added it to our backlog. We welcome a pull request and we also have a process as you know that can be expedited. For reference, the ticket number is FIO-1503.

**Comment by VennilaCity** [comment]
@wag110894 Any update on this issue?

**Comment by wag110894** [comment]
This issue has been resolved on Formio.js version 4.13.0.
