### ISSUE TITLE
[BUG] HTTP 404 trying to fetch https://cdn.form.io/ace/1.4.10/mode-undefined.js

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3760]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment (only FormIO JS)
- Formio.js version: 4.12.7
- Frontend framework: React
- Browser: Google Chrome
- Browser version: Version 88.0.4324.150 (Official Build) (64-bit)

## Steps to Reproduce
1. Open FormBuilder and insert Date/Time component, so the component's edition popup is opened
2. Go to "Date" tab
3. Scroll down to and click on "+" icon next to "Custom Disabled Dates"
4. See the error in Google Chrome Console (F12)
5. Start typing something in "Disabling dates by a function" section and see many more warnings/exceptions in the console

## Expected behavior
No error is logged in the console

## Observed behavior
Error is logged in the console after expanding "Custom Disabled Dates" with "+" icon:
```
GET https://cdn.form.io/ace/1.4.10/mode-undefined.js net::ERR_ABORTED 404
t.loadScript @ ace.js:1
t.loadModule @ ace.js:1
setMode @ ace.js:1
set @ ace.js:1
setOption @ ace.js:1
setOption @ ace.js:1
(anonymous) @ ace.js:1
setOptions @ ace.js:1
(anonymous) @ formio.full.min.js:14
Promise.then (async)
value @ formio.full.min.js:14
(anonymous) @ formio.full.min.js:120
value @ formio.full.min.js:120
(anonymous) @ formio.full.min.js:53
value @ formio.full.min.js:53
value @ formio.full.min.js:16
value @ formio.full.min.js:120
(anonymous) @ formio.full.min.js:16
value @ formio.full.min.js:16
value @ formio.full.min.js:16
value @ formio.full.min.js:14
set @ formio.full.min.js:16
(anonymous) @ formio.full.min.js:16
```

More similar errors to this one when typing something in "Disabling dates by a function" section:
```
An error occured within custom function for unknown ReferenceError: asd is not defined
    at eval (eval at evaluator (formio.full.min.js:16), <anonymous>:3:1)
    at Object.evaluate (formio.full.min.js:16)
    at Object.b [as evaluate] (formio.full.min.js:10)
    at n.value (formio.full.min.js:29)
    at formio.full.min.js:102
    at Q (flatpickr.min.js:2)
    at H (flatpickr.min.js:2)
    at R (flatpickr.min.js:2)
    at B (flatpickr.min.js:2)
    at flatpickr.min.js:2
```

## Example
[JSFiddle example](https://jsfiddle.net/dsibinski/bx62h7uj/1/)
Reproduce with steps mentioned above

**Comment by wag110894** [comment]
Hello @mm-dsibinski 

Can you try retesting using the latest version of the renderer and see if the issue still occurs? Renderer v4.13.0-rc.9

**Comment by mm-dsibinski** [comment]
Hi @wag110894 ,
I tested with v4.13.0-rc.9. The first error about `mode-undefined.js` is gone, but there are still errors in the console when typing something in "Disabling dates by a function" section.

**Comment by travist** [comment]
@mm-dsibinski this is a new ticket. Please create a separate ticket and close this one since the original issue that was reported in this ticket is resolved.
