### ISSUE TITLE
Change event not fired on quickly moving text fields.

### ISSUE THREAD

**Issue by FA-Abhishek** [formio/formio.js#3764]
For some text field change event is not fired on moving quickly in text fields by entering tab key.

**Comment by wag110894** [comment]
Hello @FA-Abhishek Can you provide a video of this issue occurring?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
