### ISSUE TITLE
[BUG] Weird behaviour of Date/Time control settings with customization

### ISSUE THREAD

**Issue by mm-mgustowski** [formio/formio.js#3765]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment: only formio.js
- Formio.js version: 4.12.6
- Frontend framework: React
- Browser: Chrome
- Browser version:  88.0.4324.150

## Steps to Reproduce
1. Go to your sandbox website and use the id: 6026330891204c128d52358f
2. Add the only visible Date/Time control to open the edit dialog
3. Switch to the Date tab and see that it looks bad - my intention was to hide just only one checkbox control (enableMinDateInput) there but whole layout changed. Please, reffer to Expected/Observed behaviour for details.

## Expected behavior
![image](https://user-images.githubusercontent.com/45002835/107743044-75e86180-6d10-11eb-992d-1a136f7256d4.png)
Marked control should be hidden

## Observed behavior
![image](https://user-images.githubusercontent.com/45002835/107743099-91ec0300-6d10-11eb-906a-6e33c40d16fb.png)
Control I wanted to hide is indeed hidden, but also minDate datepicker placeholder changed and maxDate controls are gone.

## Example
See above.

For code or form JSON, please enclose in a code block:

```js
{
  "builder": {
    "basic": false,
    "advanced": false,
    "data": false,
    "premium": false,
    "customBasic": {
      "title": "Questions",
      "default": true,
      "weight": 0,
      "components": {
        "datetime": {
          "title": "Date / Time",
          "key": "dateTimeQuestion",
          "icon": "calendar",
          "schema": {
            "label": "Date / Time",
            "type": "datetime",
            "key": "dateTimeQuestion",
            "input": true,
            "format": "dd-MM-yyyy"
          }
        }
      }
    }
  },
  "editForm": {
    "datetime": [
      {
        "key": "api",
        "ignore": true
      },
      {
        "key": "date",
        "components": [
          {
            "key": "enableMinDateInput",
            "ignore": true
          }
        ]
      }
    ]
  }
}
```

Is this a bug or is there any different way to hide particular controls from settings dialog (especially in Date tab)?

**Comment by wag110894** [comment]
Hello @mm-mgustowski,

Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you and have a great day!

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
