### ISSUE TITLE
Currency component in ar language

### ISSUE THREAD

**Issue by fadelsahmarani** [formio/formio.js#3767]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x ] Local deployment
- Formio.js version: v4.13.0-rc.6
- Frontend framework: JavaScript
- Browser: Firefox
- Browser version: latest

## Steps to Reproduce
1. Add currency component with ar language

## Expected behavior
Open form normally
## Observed behavior
Form is not opened with console error
## Example
https://jsfiddle.net/6smkntwz/1/

**Comment by wag110894** [comment]
Hello @fadelsahmarani, we are able to replicate this issue and have added it to our backlog. We welcome a pull request and we also have a process to expedite if you are interested. For reference, the ticket number is FIO-1426.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
