### ISSUE TITLE
[QUESTION] Submission reference ID in form settings

### ISSUE THREAD

**Issue by fabien-feat** [formio/formio.js#3770]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 1.63.5
- Formio.js version: 4.7.8
- Frontend framework: javascript
- Browser: chrome
- Browser version: latest

Hi Guys !
Is it possible to store in form settings a reference ID from a resource submission, so the api give us the complete data when requested.
Example : 
form object : 

```json
{
  "components": [ .... ],
  "settings" : {
     "myresource": ObjectID("5fb253cfc5fd5be640aa16a4")
  }
}
```

http request : /form/5dfbb8c842a8427132c38e88 will produce

```json
{
  "components": [ .... ],
  "settings" : {
     "myresource": {
          "data" : {
               "name": "....",
               "firstname": "...."
          }
     }
  }
}
```

Thanks !

**Comment by travist** [comment]
What is wrong with just sending another API call to get this information? I don't believe there is a way to do this.
