### ISSUE TITLE
[BUG] Radio component has ID in name attribute

### ISSUE THREAD

**Issue by wpf500** [formio/formio.js#3772]
Hello!

When I create a radio component it's `name` attribute uses a different pattern to other components (i.e. it is `data[key][id]` rather than `data[key]`). This means if I submit the form the "normal HTML" way (i.e. not using Formio's submit functionality) then the data that is sent to the server is incorrect.

In the example below it manifests as:
```html
<input type="radio" name="data[aRadioQuestion]"> <!-- expected -->
<input type="radio" name="data[aRadioQuestion][asdgds]"> <!-- observed -->
```

This does not happen if I use Formio's submission object, i.e.
```js
form.on('submit', submission => {
  console.log(submission); // {data: {aRadioQuestion: 5}}
});
```

I did a bit of digging and this is the line of code where it happens is:
https://github.com/formio/formio.js/blob/77575e763dd6977cef5eadcf3a57276fe7d946df/src/components/radio/Radio.js#L50

I've removed that line and it then works as expected, but I don't know the codebase so there might be some knock on effects I don't know about.

I believe this may be what https://github.com/formio/formio.js/issues/3032 was also referring to.

## Environment
Please provide as many details as you can:

- Hosting type
  -  Local deployment
    - Version: just formio
- Formio.js version: 4.12.7
- Frontend framework: none
- Browser: Firefox
- Browser version: 85

## Steps to Reproduce

1. Create a form with a radio component
2. Render with Form.createForm
3. Inspect radio element

## Expected behavior

Radio `name` attribute is `data[key]`

## Observed behavior

Radio `name` attribute is `data[key][id]`

![image](https://user-images.githubusercontent.com/2084823/107943402-8f91df00-6f84-11eb-9ee4-d63041357eae.png)

## Example

https://jsfiddle.net/4ugc6wvj/

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
