### ISSUE TITLE
Using options object in angularJs application

### ISSUE THREAD

**Issue by phanikumar252** [formio/formio.js#3776]
@wag110894 

Hi,

When I am using option object submit button is not working. Please help me on this.

  Formio.createForm(document.getElementById('formio1'), formiobase1).then(function(form) {
            // Defaults are provided as follows.
            form.submission = {
                data: ($sessionStorage.newFormData != undefined) ? $sessionStorage.newFormData : {}
            };
            form.options = {
              "disableAlerts":true,
               "noAlerts": true,
              "submitMessage":""
            }
      form.on('submit', function(submission) {

   })
});

**Comment by wag110894** [comment]
Hello @phanikumar252,


Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you and have a great day!

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
