### ISSUE TITLE
[BUG] Validation for select boxes not working properly when content used on the same form

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3786]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment: only FormIO JS
- Formio.js version: 4.12.7
- Frontend framework: React
- Browser: Google Chrome
- Browser version: Version 88.0.4324.182 (Official Build) (64-bit)

## Steps to Reproduce
**Reproduce with FormIO Sandbox**
1. Open https://formio.github.io/formio.js/app/sandbox and load sandbox with id 602e4f222d19c2e78f06b85a
2. Scroll down to "Form Rendered" section and see that "Multiple choice" (Select Boxes) component is required, but the validation error is not shown:

![image](https://user-images.githubusercontent.com/49182064/108350813-a43dd380-721f-11eb-816b-dd80ab41cc05.png)

From technical point of view, it means that on `submission` object the flag `isValid` is not set to `false` (while it should be).

Notice that when you remove the "Content" component (the one with text "Some content") from the form, everything works as expected.
Also when you select one of the select boxes and deselect it, the validation error appears:

![image](https://user-images.githubusercontent.com/49182064/108351753-e4518600-7220-11eb-92eb-9759990d6bb0.png)

**Reproduce with form definition JSON**
You can also reproduce the same behavior with this JSFiddle: https://jsfiddle.net/dsibinski/63ckd5nf/3/

## Expected behavior
Validation error is shown straightaway for Select Boxes component and `isValid` flag on `submission` obejct is set to `false` when a required component is used and "Content" component is also present on the same form.

## Observed behavior
Validation error is not shown for Select Boxes component and `isValid` flag on `submission` object is not set to `false`.

If there's any workaround for that before the actual bug is fixed, please propose.

**Comment by wag110894** [comment]
This is working as expected. 
Can you provide a little more content on why you think this a bug?

**Comment by mm-dsibinski** [comment]
@wag110894 I integrate `Form` component into a specific web page. On this page, I don't want the user to be able to save his/her work if the form has any validation errors. For that, when the user clicks a "Save" button (our specific button), I check the `isValid` flag on `submission` object and if it's set to `true`, I don't let the user save.

I think I know what you mean that this "is working as expected". I think you mean that after rendering the form there's actually no `submission` yet, so the validation flag is also not set.

But your answer made me thinking... I created another sandbox: 60332ebcd25616686d9de00f
In this sandbox the "Submit" button is actually disabled even with no validation error shown:

![image](https://user-images.githubusercontent.com/49182064/108661548-08ee7c00-7507-11eb-9270-6fde59d2ca86.png)


I guess there must be another way to detect that the form doesn't meet the validation criteria (i.e. required select boxes field have no value selected), even without `submission` object? How to do that?

**Comment by travist** [comment]
It is disabled because the Select Boxes is required and you have not added any values to it (and therefore cannot submit). This is because the check to see if the Submit button should be disabled ignores the "pristine" flag on components which is used to indicate if the field has been modified (and when a validation error should actually be shown to the user).

**Comment by mm-dsibinski** [comment]
So how can I check, on the level of my own save button, that the value is not selected for Select Boxes which is required and not allow clicking or disable my own save button? I'm rendering the form using `Form` component (I'm using React but let's say the form is rendered using `Formio.createForm`) and I have some Select Boxes that is required (like in the example).

My first idea with checking `isValid` flag on `submission` object doesn't work here, because there's no `submission` yet (before user selects anything on the form).

**Comment by mm-dsibinski** [comment]
hi @travist , can I get some answer here? We have more users facing this problem, and it's really annoying.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
