### ISSUE TITLE
Calculated values not working on Edit Grid component

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#379]
Please add any text field or number component to Edit Grid and configure to take value outside Edit Grid from another component, for example:
value = data['anotherfield']
Calculated value is not working in Edit Grid component.

So far, the workaround works:
value = document.getElementById('anotherfield').value

**Comment by krixerx** [comment]
The custom error message is not displayed too. The ng-formio version is 2.25.9

**Comment by randallknutson** [comment]
This is working in formio.js but not in ng-formio

**Comment by randallknutson** [comment]
This was fixed in https://github.com/formio/ngFormio/pull/570
