### ISSUE TITLE
[BUG] Console errors while typing within "Disabling dates by a function" section

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3802]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment (only FormIO JS)
- Formio.js version: 4.13.0-rc.9
- Frontend framework: React
- Browser: Google Chrome
- Browser version: Version 88.0.4324.150 (Official Build) (64-bit)

## Steps to Reproduce
1. Open FormBuilder and insert Date/Time component, so the component's edition popup is opened
2. Go to "Date" tab
3. Scroll down to and click on "+" icon next to "Custom Disabled Dates"
4. Scroll down and type something in "Disabling dates by a function" section
5. See the errors in Google Chrome Console (F12)

## Expected behavior
No error is logged in the console

## Observed behavior
Error is logged in the console when typing something in "Disabling dates by a function" section:
```
An error occured within custom function for unknown ReferenceError: s is not defined
    at eval (eval at evaluator (formio.full.min.js:16), <anonymous>:3:1)
    at Object.evaluate (formio.full.min.js:16)
    at Object.b [as evaluate] (formio.full.min.js:10)
    at n.value (formio.full.min.js:29)
    at formio.full.min.js:102
    at Q (flatpickr.min.js:2)
    at H (flatpickr.min.js:2)
    at R (flatpickr.min.js:2)
    at B (flatpickr.min.js:2)
    at Object.ce [as redraw] (flatpickr.min.js:2)
```

## Example
[JSFiddle example](https://jsfiddle.net/dsibinski/bx62h7uj/2/)
Reproduce with steps mentioned above

**Comment by wag110894** [comment]
Hello @mm-dsibinski,

Thanks for reaching out!

We are able to replicate this on our side. We have created a ticket and have added it to our backlog. We welcome a pull request and have a process to expedite if you are interested.

For reference, the ticket number is FIO-1564.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by mm-dsibinski** [comment]
hi @Tatsiana8 , has this issue been solved?

**Comment by brendanbond** [comment]
@mm-dsibinski The renderer evaluates "on change," which means as you're typing it's going to attempt to evaluate, even if you're not done. I believe we've debounced this a little bit, but ultimately there's not really a way around this. Once you've completed the input in that section, are you still running into errors, or is it just while you type?

**Comment by mm-dsibinski** [comment]
@brendanbond This is how it looks in https://formio.github.io/formio.js/app/builder:


![chrome_kIU26A6OC7](https://github.com/formio/formio.js/assets/49182064/557464e4-7d11-49cc-a062-1af41181d238)

so only during typing
