### ISSUE TITLE
[BUG] Select field with javascript values of 0 or 000 return validation errors

### ISSUE THREAD

**Issue by thenixtone** [formio/formio.js#3803]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.9.18
- Frontend framework: Bootstrap 4/
- Browser: Chrome
- Browser version: Latest

## Steps to Reproduce
1. Have a select field with values that contain 0 or 000, etc anything that can be considered false I assume
2. Make sure 'required' is set in validation, for the datatype, you can choose either string, integer or autotype, it will fail for all.
3. Change field to said value above
4. Look at validation error

## Expected behavior
Nothing, it's a valid value. I'm dealing with a vendor dataset that has valid values as 000, 452 etc.

## Observed behavior
It triggers validation errors as I assume formio does a simple type check and views it as false/empty
Also, when you click the select again it resets it to the default value because, again, I assume it thinks its empty.
It also looks like it works correctly in the 'Preview' in the builder, but doesn't in the frontend wizard.

Is this a bug or am I missing some config?

**Comment by wag110894** [comment]
Hello @thenixtone,

This issue is actually resolved on formio.js 4.13.0-rc.11.

I hope that this helps.

Thank you.

**Comment by thenixtone** [comment]
> Hello @thenixtone,
> 
> This issue is actually resolved on formio.js 4.13.0-rc.11.
> 
> I hope that this helps.
> 
> Thank you.

Thanks for the reply, I've updated but now nothing is loading.

Receiving `this.itemsLoadedResolve is not a function` in console on all my existing form schemas.

Any ideas?

**Comment by thenixtone** [comment]
When starting a new form, it happens when using a custom javascript variable with data objects for the select dropdown. It's fine until I select 'HTML5' instead of Choices.js, it creates the error in console immediately.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
