### ISSUE TITLE
How to hide component's "Remove" and "Copy" buttons on form builder?

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3804]
Hi guys!
I'm trying to hide, for a particular component on the form builder, the "Remove" and "Copy" buttons:

![image](https://user-images.githubusercontent.com/49182064/108841300-84891f80-7612-11eb-990f-775867f12fe4.png)

I marked these buttons in red.

Is there any way to do that? Some configuration of the component in JSON maybe?
Thanks for any insights.

**Comment by travist** [comment]
You would need to override the following template https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builderComponent/form.ejs

using the method described @ https://github.com/formio/formio.js/wiki/Templates-API#overriding-templates

**Comment by mm-dsibinski** [comment]
That does the job. Thanks @travist

**Comment by SaThViK81** [comment]
Hi @mm-dsibinski ,

Can you share some code, how you did it for specific component.

**Comment by mm-dsibinski** [comment]
Hi @SaThViK81 ,
sure. You can override any component's template by setting your custom templates e.g. on `FormIO.Templates.current`. You can find more details about that here:

In order to override the generic component wrapper used by any component on the form builder, you can override the template for `builderComponent`. I simply copied the contents of the original template from https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builderComponent/form.ejs and removed buttons for remove and copy. Finally it looks as follows:

```javascript
builderComponent: {
        yourRenderModeName: `
              <div class="builder-component" ref="dragComponent">
        {% if (!ctx.disableBuilderActions) { %}
          <div class="component-btn-group" data-noattach="true">
            <div class="btn btn-xxs btn-default component-settings-button component-settings-button-paste" ref="pasteComponent">
              <i class="{{ctx.iconClass('save')}}"></i>
            </div>
            <div class="btn btn-xxs btn-default component-settings-button component-settings-button-edit-json" ref="editJson">
              <i class="{{ctx.iconClass('wrench')}}"></i>
            </div>
            <div class="btn btn-xxs btn-default component-settings-button component-settings-button-move" ref="moveComponent">
              <i class="{{ctx.iconClass('move')}}"></i>
            </div>
            <div class="btn btn-xxs btn-secondary component-settings-button component-settings-button-edit", ref="editComponent">
              <i class="{{ctx.iconClass('cog')}}"></i>
            </div>
          </div>
        {% } %}
        {{ctx.html}}
      </div>
        `
      }
```

With this template, all components on my form builder don't have these two buttons:

![image](https://user-images.githubusercontent.com/49182064/109754967-01725580-7c20-11eb-9831-08828060f24f.png)


I hope that helps 😉

**Comment by SaThViK81** [comment]
hi @mm-dsibinski, 

thanks for the quick response

I am using react-formio

I am getting the formData object from API and the object looks like

`
const formData = {
        display: 'form',
        settings: {
            pdf: {
                id: '1ec0f8ee-6685-5d98-a847-26f67b67d6f0',
                src: 'https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0',
            },
        },
        components: [
            {
                label: 'First Name',
                tableView: true,
                key: 'firstName',
                type: 'textfield',
                input: true,
            },
            {
                label: 'Last Name',
                tableView: true,
                key: 'lastName',
                type: 'textfield',
                input: true,
            },
        ],
    };
`

I want to hide the above components (First Name and Last Name) Remove button on the form builder, the rest of the components should remain the same


`  <FormBuilder
                form={formData}
                onChange={(form: any) => {
                    setFormSchema(form);
                }}
                options={options}
                
            />`
            
            
            
  Thanks for any insights.

**Comment by mm-dsibinski** [comment]
@SaThViK81 I don't know if you'll be able to do that using custom templates. Maybe @travist can help here

**Comment by SaThViK81** [comment]
@mm-dsibinski  thanks.

@travist  can you please help me with that.
