### ISSUE TITLE
Can we have a "toggle" input type for checkbox component?

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#3806]
Currently the available input types are "checkbox" and "radio".
I am interested, if there is a plan  to add "toggle" type too. It should be quite easily doable with styles.

**Comment by travist** [comment]
I believe there is a "pretty-checkbox" way to do this.

It is called "Switch" https://lokesh-coder.github.io/pretty-checkbox/

You may check, but this library may be able to accomplish it.  https://github.com/formio/pretty-checkbox
