### ISSUE TITLE
[BUG] >= 4.12.1 Event `nextPage` triggers `render` to be emitted twice

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3810]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: 4.12.1
- Frontend framework: none
- Browser: all
- Browser version: N/A

## Steps to Reproduce
1. Visit https://codepen.io/SalTor/pen/VwmyLJW
2. Open console
3. Press "Next" and observe that "render" was emitted twice
4. Continue forward through the form a few pages and see that `render` is emitted twice every time a `nextPage` is triggered
5. Press "Page 1" in the breadcrumb and notice the same thing
6. Continue to the end of the form and then press "Page 1" and notice that it doesn't happen anymore

## Expected behavior
The render event should only be emitted once per page

## Observed behavior
The render event is emitted multiple times per page and in an inconsistent manner

## Example
https://codepen.io/SalTor/pen/VwmyLJW

**Comment by SalTor** [comment]
I first observed this after upgrading to version 4.12.4 and after some digging I discovered this was introduced in version 4.12.1 and continues through to the latest version available via https://unpkg.com/formiojs@latest/dist/formio.full.min.js

**Comment by wag110894** [comment]
Hello @SalTor, 

Thanks for reaching out! We are able to replicate this issue and have added it to our backlog. We welcome a PR and we also have a process to expedite the issue. 

For reference, the ticket is FIO-2089.

Thank you.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
