### ISSUE TITLE
[BUG] Radio button selection not persisting and is deselected on click

### ISSUE THREAD

**Issue by jgar123** [formio/formio.js#3811]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ]  Local deployment
    - Version: 
- Formio.js version: 4.12.1 (have updated to`4.12.7`, however, the issue persists. Version `4.12.1` is where the initial bug occurs)
- Frontend framework: React
- Browser: All
- Browser version: N/A

### When building a form (example of form in the jsfiddle - http://jsfiddle.net/gm23xy6L/1/)
1. Add a data grid component
2. Within the data grid component, add a field set component
3. Within the field set component, add a tabs component
4. Within the tabs component, add a container component
5. Within the container component, add a radio component that has 2 values (i.e. yes and no)
6. Add another radio component in the container with multiple values and conditionally render these radio buttons based on the choice made in the previous radio button

## Expected behaviour
On the jsfiddle (http://jsfiddle.net/gm23xy6L/1/) in the rendered panel, select `Yes` on the question `Show radio buttons below`. This should render 4 additional radio buttons. When a user selects one of the radio buttons from the 4 rendered, the selection *should* persist and not be 'de-selected'.

## Observed behaviour
On the jsfiddle (http://jsfiddle.net/gm23xy6L/1/) in the rendered panel, select `Yes` on the question `Show radio buttons below`. This renders 4 additional radio buttons. When a user selects one of the radio buttons from the 4 rendered, the selection *does not* persist and it is 'de-selected'.

## Example
http://jsfiddle.net/gm23xy6L/1/

Note - this bug potentially impacts select dropdowns and checkboxes as well.

**Comment by wag110894** [comment]
Hello @jgar123,

Thanks for reaching out!

We are able to replicate this issue on our side.  We have created a ticket and have added it to our backlog. We welcome a pull request and also have a process to expedite if you are interested. For reference, the ticket is FIO-1562.

We will let you know once this issue is resolved.

**Comment by kapilbhalada** [comment]
@wag110894 
We are using  Formio.js 4.14.7 but still this issue persists

**Comment by VikitorChidi** [comment]
@wag110894 
This issue still persists even in Formio.js 4.14.5
