### ISSUE TITLE
Cannot find the anonymous role as expected in the walkthrough

### ISSUE THREAD

**Issue by ryceg** [formio/formio.js#3818]
## Environment
Have tried on Form.io (https://pro.formview.io/#/hslcnhleqweitcn/deity?header=1&reset=1), as well as an inserted iframe, the CodePen demo, and a React boilerplate. Followed the walkthrough, but am unable to find where the "Anonymous" role is hiding.

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: Application: 7.0.42, Renderer: 4.12.4
- Frontend framework:
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Set all non-destructive (i.e. everything except delete) API things to allow everyone
2. Try to load up the form
3. Observe that the form API query is still received, counting against the monthly allotment, but hasn't rendered.

## Expected behavior
Form to load completely.
## Observed behavior
Text loads, but form elements do not.
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

![image](https://user-images.githubusercontent.com/36913739/109294666-97edf200-7881-11eb-97ea-a77b9f0434e2.png)

https://pro.formview.io/#/hslcnhleqweitcn/deity?header=1&reset=1

Howdy folks. I'm afraid that this is likely a PEBKAC issue, but I can't for the life of me figure out what I'm doing wrong. My intended use for this is to generate `.json` files to be used for a webapp- no accounts or anything are needed, anonymous is in fact likely preferable. Any help pointing in the right direction of how to get the forms up and running would be much appreciated!

**Comment by travist** [comment]
You need to edit the Access section of each of these Nested Forms and ensure that the Read Form Definition permission has the Anonymous role added to it.

**Comment by ryceg** [comment]
Hi, thanks for the response. Each of the Nested Forms has the Read Form Definition permission set to "Everyone". There is no Anonymous role showing up anywhere, which is why I'm having trouble.

**Comment by travist** [comment]
Hmmm... there should be an anonymous role. Was it deleted? If so, then that could be the problem.

**Comment by ryceg** [comment]
Think I figured it out; I copy pasted the code from the "demo" that you can
make before signing up, and used that as my base. Created a bunch of
issues. This issue is closed.
