### ISSUE TITLE
[BUG] DateTime date format

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#3821]
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: Chrome, Firefox
- Browser version: latest

## Steps to Reproduce
1. Create date-time elements
2. Add custom date format like dd.MM.yyyy hh:mm
3. Open in desktop and mobile window size

## Expected behavior
Date format is dd.MM.yyyy hh:mm
## Observed behavior
In mobile window size: Date format use default by currentLocation, because input type is 'datetime-local'
In desktop: looks fine

**Comment by wag110894** [comment]
Hello @homashevchenko, 

Can you provide a video of the issue?

Thank you.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
