### ISSUE TITLE
[BUG] radio button default value not showing correctly

### ISSUE THREAD

**Issue by shaymaBraham** [formio/formio.js#3822]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: v4.12.4
- Formio.js version: v4.12.4
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
adding radio button group with values  0 &  1

## Expected behavior
set default value always at 0
## Observed behavior
the default selected radio button  showing  selected in the builder but not in the rendered from ,,,,
 sometimes it is selected in the rendered from and not in the builder and vis versa 

## Example

![154411753_1329770684046200_6187361689406076965_n](https://user-images.githubusercontent.com/64074491/109319551-4593dd80-784f-11eb-888a-7f51570109ce.png)

**Comment by wag110894** [comment]
Hello @shaymaBraham,

Thanks for reaching out! We are able to replicate this issue and have added it to our backlog. We welcome a PR and we also have a process to expedite the issue.

For reference, the ticket is FIO-2091.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
