### ISSUE TITLE
[QUESTION] Recommended way to access form data during "blur" event?

### ISSUE THREAD

**Issue by waterbuckit** [formio/formio.js#3827]
I need to access the current form data on blur to update data on the backend (I need it on blur to save on killing the server with the 'change' event).

At present I've been doing something like this (update function handles the backend updating):
```javascript
Formio.createForm('form',{},{})
                    .then((form) => {
                      form.on('blur', function (e) {
                            if(e.inDataGrid){
                                updateFunction(form.data[e.parent.component.key], e.parent.component.key);
                            }else{
                                updateFunction(form.data[e.component.key], e.component.key);
                            }
                        });
                     }
```
The issue I have is that, if the updated component is a DataGrid, I'm getting an Array(0) from the value, but it's an array with string indices, i.e.: ['key' : 'value'], presumably because there's something asynchronous going on? What's the best way to get that data? (I need the datagrid component as it's how my backend knows which associated table to put the rows into).

Although... Interestingly, the first element seems to come out as one of those "string-indexed arrays" but subsequent elements are actual objects.

Thanks for the great package!

**Comment by waterbuckit** [comment]
This is kind of weird but it seems to be that when the datagrid is not sortable, the first element comes out like an "array with keys", I don't know how to even describe it other than the output of the console looks like: "['key' : 'value']", whereas subsequent elements are normal objects. Switching to sortable fixed my issue.

**Comment by travist** [comment]
The data model update is on a debounce method, so you may need to have a timeout to give the model some time to update, then you can make the update call.

**Comment by waterbuckit** [comment]
> The data model update is on a debounce method, so you may need to have a timeout to give the model some time to update, then you can make the update call.

Right, I see - gave it a shot, I've wrapped it in a `setTimeout()` for 20 seconds and unfortunately I'm still getting an empty array on my server, but a glance in chrome devtools, I see it resolving it once I click the dropdown?

```js
form.on('blur', function (e) {
    if(e.inDataGrid){
        setTimeout(()=>{
               updateFunction(form.data[e.component.key], e.path, form.data);
        }, 20000);
    }else{
        updateFunction(form.data[e.component.key], e.path, form.data);
    }
});
```
In fact, the issue is still somewhat the same:

![2021-04-07-180156_1896x1015_scrot](https://user-images.githubusercontent.com/22277521/113905793-70b50980-97cb-11eb-8a1c-bea7f0c09ed9.png)

The first element is being returned as a "string indexed" array of some sorts. Subsequent rows have no trouble at all. Looks fishy to me?

Any ideas? Sadly I need to use this particular hook as we need pretty much real-time updates.

**Comment by waterbuckit** [comment]
I've found that a temporary solution is to start the datagrid as empty - doesn't seem to have the same issues. But this does seem wrong to me, no?
