### ISSUE TITLE
[BUG] Fields from Resource not carry over configs if they come from search fields

### ISSUE THREAD

**Issue by zzdjk6** [formio/formio.js#3835]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: Chrome
- Browser version: 88.0.4324.150

## Steps to Reproduce
1. Create a field (**FieldA**) in a Resource (**ResourceA**), make some configs on it
2. Create a new Form (**FormA**)
3. Search "FieldA", then drag **FieldA** into **FormA**

## Expected behavior

Configs should be kept for **FieldA**.

## Observed behavior

Configs are **NOT** carried over for **FieldA**.

However, if we don't search for "FieldA", but directly drag it from **ResourceA**, the behaviour is correct (configs are carried over)

## Example

When dragging from search result:

![image](https://user-images.githubusercontent.com/3908516/109745191-5de16f00-7c38-11eb-95fc-824ce5418072.png)

When dragging directly

![image](https://user-images.githubusercontent.com/3908516/109745113-40140a00-7c38-11eb-8f2b-ea68c543544e.png)

**Comment by wag110894** [comment]
Hello @zzdjk6,

This issue will be resolved in 4.13.0-rc.9. We are working hard on getting our 4.13x renderer to our production portal.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
