### ISSUE TITLE
[BUG] Radio buttons component breaks for bootstrap 3

### ISSUE THREAD

**Issue by geynen** [formio/formio.js#3836]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: v4.13.0-rc.12
- Frontend framework: bootstrap3
- Browser: Chrome
- Browser version: 88.0.4324.150

## Steps to Reproduce
1. Add a component radio button to the form builder.
2. Go to the data tab.
3. 

## Example

![image](https://user-images.githubusercontent.com/1620474/109748229-7f921600-7ba6-11eb-80c8-2b84babaafb2.png)

When inspecting the element, you can see that it is missing closing quotes.

![image](https://user-images.githubusercontent.com/1620474/109748470-ef080580-7ba6-11eb-9cd7-534a406cb731.png)

however when I change from bootstrap 3 to bootstrap 4 the boxes are displayed fine.

**Comment by wag110894** [comment]
Hello @geynen, 

Thanks for reaching out! 

We are aware of the issue and currently have one of our developers working on the resolution.

For reference, the ticket number is FIO-2463.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
