### ISSUE TITLE
How to implement custom upload adapter for Content component?

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3837]
Hi guys,
I'm using formio form builder and "Content" component. It uses `ckeditor` for WYSIWYG editor. When I want to use the image file upload function, there's the following error:

`filerepository-no-upload-adapter: Upload adapter is not defined. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-filerepository-no-upload-adapter`

I'm only using FormIO JS, the backend is our custom .NET backend with ASP.NET as a web solution.

I found this item: https://github.com/formio/formio.js/issues/1071 and it says that the issue has been fixed.
What does it exactly mean that it has been fixed? How can I implement the custom file uploader for Content component so the users can upload files to our backend server?

I will also be working with File component and there I found that I need to implement the web server side to be compliant with `ng-file-upload` and I even found a [.NET example](https://github.com/stewartm83/angular-fileupload-sample/tree/master/src/AspNetWebApi) for that. Is it the same mechanism for File and Content components?

Thanks for any help here.

**Comment by travist** [comment]
We already have provided an image upload capability in our custom build of CKEditor. https://github.com/formio/ckeditor5-build-classic/tree/master/src/plugins/image/imageupload

Please make sure you are using this build of CKEditor.

**Comment by mm-dsibinski** [comment]
Hi @travist ,
do you have it published as npm package or in some other place, or I have to take the `ckeditor.js` manually from your ckeditor repo?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
