### ISSUE TITLE
How to send additional parameters when saving files with File component?

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#3838]
Hi guys!

I'm using the `File` component (https://help.form.io/userguide/form-components/#file) in FormIO builder, so our users can upload files on their forms.

I implemented the ng-file-upload-compatible  .NET server-side using the example from [here](https://github.com/stewartm83/angular-fileupload-sample/tree/master/src/AspNetWebApi).

When the file is dragged-and-dropped on the `File` component:

![image](https://user-images.githubusercontent.com/49182064/110106690-f1f03980-7de4-11eb-8415-343af3504ab6.png)

the "Add" method in my server controller is called. I noticed that, I assume FormIO, provides only the file content and file name parameter in the form data of the web request. It means that I don't have any other parameters available in this controller, like the name of the form or its ID (specific to our system).

The fact is that the files saved using this `File` component are having some unique ID assigned, so when the file is later downloaded it's downloaded with the name containing the unique ID:

![image](https://user-images.githubusercontent.com/49182064/110107007-57dcc100-7de5-11eb-8da8-30b6abd07579.png)

That makes me wondering how to improve the files saving process with FormIO a bit. What I'd like to achieve is to be able to send some custom parameters to the files saving controller's `Add` method, for example the ID of the form object and the name of the form (we are saving the FormIO's form inside our own entity, which has name and ID). It would let me create a separate folder on our server for all files related only to this particular form.

Do you have any idea how this can be achieved?
Thanks for your help :)

**Comment by travist** [comment]
This would require some extensive debugging to determine how this could be done. Maybe someone from the community has done this before and can lend a hand?

**Comment by Sefriol** [comment]
I am little unsure what is the desired goal. I would assume that all of this could be achieved with by adding custom FileService to the form itself?

By defining custom upload and download functions, I would assume that you can send and receive whatever parameters you want?

**Comment by mm-dsibinski** [comment]
@Sefriol I guess so. That would be the goal - to be able to modify the web request sent by the form to the custom files' provider (URL).

**Comment by Sefriol** [comment]
This is how we do this in VueJS:

```vuejs
<template>
  <div class="form-render">
    <Form
      ref="formio-form"
      :options="{
        fileService:storage
      }"
      :form="form"
      :submission="submission"
    />
  </div>
</template>
<script>

import { Form } from 'vue-formio'
import { downloadFile, uploadFile } from '@/api/files'
class FileService {
  uploadFile(storage, file, fileName, dir, evt, url, options, fileKey) {
    return new Promise((resolve, reject) => {
      console.log(storage, file, fileName, dir, evt, url, options, fileKey)
      const formJSON = {
        [fileKey]: file,
        name: fileName,
        dir
      }
      const fd = new FormData()

      for (const key in formJSON) {
        fd.append(key, formJSON[key])
      }
      uploadFile(fd)
        .then((res) => {
          return resolve({
            storage: 'url',
            name,
            url: res.data.url,
            size: file.size,
            type: file.type,
            data: res.data.uploadResponse.response
          })
        })
        .catch((err) => reject(err))
    })
  }
  async deleteFile(fileInfo) {
    console.log(fileInfo)
  }
  downloadFile(fileInfo, options) {
    return new Promise((resolve, reject) => {
      downloadFile(fileInfo.url).then(response => {
        var fileURL = window.URL.createObjectURL(new Blob([response.data]))
        var fileLink = document.createElement('a')

        fileLink.href = fileURL
        fileLink.setAttribute('download', fileInfo.originalName)
        document.body.appendChild(fileLink)

        fileLink.click()
        fileLink.remove()
        resolve()
      })
    })
  }
}
```

Where /api files are just axios api wrappers

**Comment by mm-dsibinski** [comment]
Thanks @Sefriol , that should work in React as well.
I will check it in a few weeks when I get back to this issue and let you know the results :)

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
