### ISSUE TITLE
How to use advanced conditions to show elements inside a data grid based on a select?

### ISSUE THREAD

**Issue by Chaz0r** [formio/formio.js#3840]
Hey guys,

I have the following structure of a form:

![Bildschirmfoto 2021-03-05 um 13 02 23](https://user-images.githubusercontent.com/6491705/110113193-087d9d00-7db3-11eb-8d44-a0385101da9d.png)

It is possible to add as many ParentPanels inside the data grid as you want. Inside every ParentPanel we have a select and 2 ChildPanels. What I want to do now is to hide both of the ChildPanels and make one visible based on the select in the same ParentPanel.

Another example: Imagine I already created 2 ParentPanels inside the data grid. If I chose "ChildPanel1" in the first ParentPanel the "ChildPanel1" panel in the same ParentPanel will be visible. If I select "ChildPanel2" inside the second ParentPanel the "ChildPanel2" panel becomes visible in the second ParentPanel.

Any idea how to do that?

I thought about an "advanced condition" in the ChildPanels like (pseudo code) `show = instance.parent.the_select_element.value == "the specific child panel I want to show".`
But this doesn't work because parent is undefined.

**Comment by ccontour** [comment]
<img width="503" alt="Screen Shot 2021-03-05 at 9 02 13 AM" src="https://user-images.githubusercontent.com/35661840/110133090-7f09a300-7d91-11eb-83bc-3c49aebb9177.png">

Check out the Conditional Tab. Here is an example of how to reference a value in a select in order to hide/show a component

**Comment by Chaz0r** [comment]
I tried that and if I didn't do anything wrong this doesn't work inside the grid because the selects all have the same name and data.

But it looks like I got it working with a simple script which directly checks the select that is inside the same container:
`var dependsOnField = "producttype"
var dependsOnValue = "deal"
var isHidden = true

instance.parent.components.forEach(function(entry) {
    if(entry.component.key == dependsOnField) {
      if(entry.dataValue == dependsOnValue) {
        isHidden = false  
      }
    }
});

show = !isHidden`
