### ISSUE TITLE
It is possible to create attribute group ?

### ISSUE THREAD

**Issue by chiragkanhasoft** [formio/formio.js#3853]
It is possible to create attribute group in form.io? here is the example how i want like this in form.io [LINK](https://docs.magento.com/user-guide/stores/attribute-sets.html)

**Comment by ccontour** [comment]
The closest feature would be custom properties

Can you describe what you are trying to do, there may be another strategy available

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
