### ISSUE TITLE
[BUG] How to bring data from API  for Select Boxes and Custom Component

### ISSUE THREAD

**Issue by sabnandha** [formio/formio.js#3879]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by ccontour** [comment]
If you are intending to file a bug, please include details for replication. This appears to be an information request, you may be able to find help in our community chat

https://gitter.im/formio/formio
