### ISSUE TITLE
Using search bar for components stops the ability to select different tabs on the builder palette

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#3893]
"@formio/react": "^5.0.0-rc.3"
 "formiojs" "4.12.7"

When you use the search bar to find a component the ability to then select any tabs in the builder palette fails. You cannot select different tabs.

**Comment by wag110894** [comment]
Hello @aminmc,

Apologies for the delay. We believe that this is working as expected as it is filtering out the entire builder and showing the results.

**Comment by aminmc** [comment]
The issue is when you clear the search and then try to select another tab within the palette. You can't do that. I understand the search is supposed to filter the components. But once I clear the search bar then I should be able to select different components.

**Comment by wag110894** [comment]
Hello @aminmc, I am not able to replicate this on my side. What version are you running on?

**Comment by JRiggenbach** [comment]
Any chance there is a way to remove this search bar via a formio option or configuration override?

**Comment by kavinkumarbaskar** [comment]
Myself facing same issue. After removing the text from search field I was not able to open the other palettes

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
