### ISSUE TITLE
[BUG] Wizard. Setting form.data updates conditional rendering but does not reset field values

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#3897]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Formio.js version: v4.10.5
- Frontend framework: none
- Browser: all
- Browser version: all

## Steps to Reproduce
1. Visit https://codepen.io/SalTor/pen/JjEYjaE?editors=1010
2. Open the console
3. Notice in the preview that the checkbox is checked
4. Notice that in the console the reported form data includes a field that should not be present based on the fact that is comes from a page that is hidden
5. Toggle the checkbox to be unchecked followed by checked and you will notice that now the form data propery reflects the expected state which is that the field we saw in step 4 is no longer there

## Expected behavior
We expect `field_that_should_not_be_in_form_data_when_page_hidden` to not be in the form data

## Observed behavior
It **is** in the form data

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

https://codepen.io/SalTor/pen/JjEYjaE?editors=1010

## Usecase
We have data for the form that is set later on, after the form is loaded, specifically determined by the contents of a query parameter in the URL and we use advanced logic in the form to check for the presence of the field that we're setting and the advanced logic is for rendering. The actual rendering is respected, but the fields in the page that gets hidden do not get their values in the form data reset

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
