### ISSUE TITLE
Custom Validation error in zone.js with an angular application

### ISSUE THREAD

**Issue by BVBen** [formio/formio.js#392]
A invalid custom validation for a formio component will reject the submission. But in form.js the created promise will be returned and not been handeld, so an angular application will handle this promise with zone.js. When the promise will be rejected zone.js throw an error.

_Uncaught (in Promise): Invalid Submission_
I can't find a possibility to catch the error and handle the rejection by myself

**Comment by xellafe** [comment]
Same issue here

**Comment by irsmart** [comment]
Did anyone find a solution to this as i have the same too?

**Comment by jhen1422** [comment]
Closing - outdated issue
Please open a new issue if this is still outstanding
