### ISSUE TITLE
[BUG] setSelectionRange() for a number input causes a DOMException.

### ISSUE THREAD

**Issue by DaveBagler** [formio/formio.js#3932]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: I'm using `4.12.7-patch.2`, but the problem still exists on the master branch.
- Frontend framework: VueJS
- Browsers: Chromium Edge 89.0.774.57, Chrome 89.0.4389.72, Firefox 86.0 

## Steps to Reproduce
1. Open the form in a browser that follows the spec for `setSelectionRange()` for number inputs.
2. Open the browser's console.
2. Do something on a form with a number field that triggers its focus call, for example clicking a error message for the field.
3. See the exception in console.

## Expected behavior

The browser should move the focus to the number field and scroll the field into view.

## Observed behavior

The browser does move the focus to the number field, but then it throws a DOMException because of the `setSelectionRange()` call on a number input field. The browser does not scroll the field into view in Edge/Chrome, but does in Firefox.

**Edge/Chrome:**  
<img width="715" alt="ChromeError" src="https://user-images.githubusercontent.com/3266985/113719565-be425100-96bb-11eb-8cb2-02c2f7ff7f1e.PNG">

**Firefox:**  
<img width="437" alt="FirefoxError" src="https://user-images.githubusercontent.com/3266985/113719936-22fdab80-96bc-11eb-8820-8f7b8b9d90a8.PNG">

## Fix

The relevant line of code is here: https://github.com/formio/formio.js/blob/master/src/components/number/Number.js#L181

I think the easiest solution that will provide the most consistent behavior is to remove the call to `setSelectionRange()`.

An alternative that keeps the functionality for browsers that don't follow the spec (for example IE11) could be leaving the call there but wrapping it in a try/catch block and simply swallowing the exception.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
