### ISSUE TITLE
How to suppress Submission Complete Bar when submit the form?

### ISSUE THREAD

**Issue by vpmashokkondal** [formio/formio.js#3937]
I have tried the following code in the submit. But the alerts is not suppressed.

           // Prevent the submission from going to the form.io server.
            form.nosubmit = true;

          // I have used the below code also
          form.noAlerts = true;
                
                    
            // Triggered when they click the submit button.
            form.on(''submit'', function(submission) {
                 noAlerts: true ;

           }

Could you please help me to suppress the Submission Alerts

**Comment by vpmashokkondal** [comment]
It is working fine by the following command:

form.options.noAlerts = true;

Thanks

**Comment by phinguyen202** [comment]
set `noAlerts = true` is not working in my case.
My workaround in scss file: 
```
formio-alerts {
    display: none;
}
```

**Comment by bradwray** [comment]
Trouble is that also suppresses the validation errors. Any more specific class or option to use?

**Comment by danman01** [comment]
I see that they are using `alert-success` in a prependTo method that is invoked right before `submit` is emitted.

![Screen Shot 2023-12-07 at 3 23 41 PM](https://github.com/formio/formio.js/assets/58710/f5d1cea6-6ce7-41c0-b8eb-9d430da61be5)

The entire element looks like:

```
<div class="alert alert-success" id="error-list-<your-custom-component-id-here>">
  <p>Submission Complete</p>
</div>
```

I am going to try to hide this alert-success for the specific page.
