### ISSUE TITLE
Custom CSS Class is not working

### ISSUE THREAD

**Issue by vpmashokkondal** [formio/formio.js#3939]
I have added a new TextField and try to set the font-size in the Custom CSS Class property. It is not reflecting.

Here is the sample:

![image](https://user-images.githubusercontent.com/82076818/113857408-1d898980-97c0-11eb-97a4-19f23074cb90.png)

Here is the form rendered output:

![image](https://user-images.githubusercontent.com/82076818/113857675-6d685080-97c0-11eb-9c86-e132113de1dc.png)

Could you please help me to add the custom CSS Class for form components labels

**Comment by AlexeyDavyd** [comment]
Hi @vpmashokkondal,
This property is responsible for adding css Classes form the css file you can attach in project settings. Not for css styles.

**Comment by vpmashokkondal** [comment]
> 
> 
> Hi @vpmashokkondal,
> This property is responsible for adding css Classes form the css file you can attach in project settings. Not for css styles.

I am novice programmer to the FormIO. I couldn't understand what you are trying to say.

Could you please explain in detail with sample.

In my earlier question I have asked how to suppress the "Submission Completed" bar. I have gone through all the existing issues raised so far. There are similar question and answer exists.  But they all failed to give straight forward answer.

They all quote that use noAlerts. But they failed to give the exact syntax. Finally lot of trail and error I found that to use the below expression to suppress the "Submission Completed" bar.

form.options.noAlerts = true;

Why FormIO members are so Lazy to give the answer with proper syntax or example. Most of them are novice programmer.

My Humble request please if you would like to answer the question, provide the enough detail, so that novice programmer will get benefit.

Thanks

**Comment by vpmashokkondal** [comment]
Hi Alexey,

Could you please explain in detail or give some sample code to increase the
font size for all the labels on my page

Thanks

Ashok

**Comment by AlexeyDavyd** [comment]
@vpmashokkondal 
1) You should have your css file hosted somewhere. You can sue github pages for example: https://alexeydavyd.github.io/customstyles/styles/form-styles.css
2) You should set link to your hosted css in project settings.
![image](https://user-images.githubusercontent.com/47381348/113997396-c5ef2a80-9860-11eb-9e2b-954e1f310d28.png)
3) Set the class from the stylesheet that you want to apply to your component:
![image](https://user-images.githubusercontent.com/47381348/113997639-0189f480-9861-11eb-99be-7ff538a64c8b.png)

**Comment by vpmashokkondal** [comment]
Hi Alexey,

Thanks a lot. Let me explore it.

Regards

Ashok

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
