### ISSUE TITLE
Form don't save after change type of number component  

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#3940]
- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: latest
- Browser: Chrome
- Browser version: 89.0.4389.114

## Steps to Reproduce
1. Create number component with Multiple Values
![image](https://user-images.githubusercontent.com/22855299/113862501-245cd000-97b1-11eb-9b1b-e1d7b8d05e0c.png)
2.  Disable Multiple Values option
![image](https://user-images.githubusercontent.com/22855299/113862583-41919e80-97b1-11eb-8cc5-09c5c0315709.png)
3. Try to save

## Expected behavior
Number component change type to single value and save
## Observed behavior
Number component don't change type
## Example
Observed on form.io

**Comment by wag110894** [comment]
Can you provide a video of the issue taking place?

**Comment by homashevchenko** [comment]
https://user-images.githubusercontent.com/22855299/114012912-972c8080-986f-11eb-9347-ccb260584e02.mov

**Comment by wag110894** [comment]
Hello @homashevchenko,

We are able to replicate.
For reference, the ticket number is FIO-2731.

We will let you know once this issue is resolved.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
