### ISSUE TITLE
Custom Validation - Create custom error message after server side validation

### ISSUE THREAD

**Issue by Stanzarectah** [formio/formio.js#3944]
Hi,

I want to validate a field after user enters an email address.
On change of the field a jscript should send the email value to a REST API which checks if the record exists.
An error should display if record does not exist using the same format as the following:

![image](https://user-images.githubusercontent.com/17443786/113990878-43cd2900-9895-11eb-9e6f-0aa6b05527fe.png)

Does anyone have a working example ?

I have checked this thread:  https://github.com/formio/formio.js/issues/1622 

but doesn't seem to working ?

**Comment by wag110894** [comment]
Hello @Stanzarectah, you can accomplish this by setting the Validate On from onChange to onBlur. 

I hope that this helps.

**Comment by Stanzarectah** [comment]
Hi,

I have changed to onBlur and nothing happens.

Here is my JSON:

`{
  "label": "Customer email",
  "placeholder": "your.name@company.com",
  "tableView": true,
  "validateOn": "blur",
  "validate": {
    "required": true,
    "customMessage": "Please enter an email in the format: customername@example.com",
    "custom": "    var xmlhttp = new XMLHttpRequest();   // new HttpRequest instance\r\n    var theUrl = \"https://XXXXXXX/XXXXXXXXXXX\";\r\n    xmlhttp.open(\"POST\", theUrl);\r\n    xmlhttp.setRequestHeader(\"Content-Type\", \"application/json;charset=UTF-8\");\r\n    xmlhttp.setRequestHeader(\"x-functions-key\", \"XXXXXXXXXXXX\");\r\n    xmlhttp.send(JSON.stringify({ \"email\": input, \"check_lead\": true }));\r\n    xmlhttp.addEventListener('load', complete, false);\r\n\r\n    function complete(e) {\r\n        if (this.status === 200) {\r\n            valid = true;\r\n        }\r\n        else {\r\n            alert('Lead already exists');\r\n        }\r\n    }",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false,
    "minLength": "",
    "maxLength": "",
    "pattern": ""
  },
  "errorLabel": "Please enter an email in the format: customername@example.com",
  "key": "email",
  "type": "email",
  "input": true,
  "lockKey": true,
  "prefix": "",
  "customClass": "",
  "suffix": "",
  "multiple": false,
  "defaultValue": null,
  "protected": false,
  "unique": false,
  "persistent": true,
  "hidden": false,
  "clearOnHide": true,
  "refreshOn": "",
  "redrawOn": "",
  "modalEdit": false,
  "labelPosition": "top",
  "description": "",
  "tooltip": "",
  "hideLabel": false,
  "tabindex": "",
  "disabled": false,
  "autofocus": false,
  "dbIndex": false,
  "customDefaultValue": "",
  "calculateValue": "",
  "calculateServer": false,
  "widget": {
    "type": "input"
  },
  "attributes": {},
  "conditional": {
    "show": null,
    "when": null,
    "eq": ""
  },
  "overlay": {
    "style": "",
    "left": "",
    "top": "",
    "width": "",
    "height": ""
  },
  "allowCalculateOverride": false,
  "encrypted": false,
  "showCharCount": false,
  "showWordCount": false,
  "properties": {},
  "allowMultipleMasks": false,
  "mask": false,
  "inputType": "email",
  "inputFormat": "plain",
  "inputMask": "",
  "spellcheck": true,
  "kickbox": {
    "enabled": false
  },
  "id": "e4c1d5p"
}`

I have tested that function works normally in Postman

**Comment by wag110894** [comment]
I am unable to replicate this issue on my side.
Testing using: https://formio.github.io/formio.js/app/sandbox
Load Sandbox: 6088618efb4d0585939dbb12

**Comment by Stanzarectah** [comment]
Yes you are correct wag110894 cos nothing ever happens when I put an email address in even after loading sandbox

**Comment by Stanzarectah** [comment]
I can confirm that the API is being triggered in the sandbox and that is returning the appropriate status code.
The only problem now is that I can't set the 'valid' variable to anything, no red text comes up under the field. 

```
/*Does not work */
valid = this.status == 200 ? true: 'Lead already exists';
```

However, the if I put the validation message in inside an alert popup then it shows up.

Any ideas ?

**Comment by travist** [comment]
This could be achieved by using our Data Source component where the endpoint to validate the email would be triggered on the change of the email field (using the trigger section). You would then make the validation of the email field depend on the valid state of the data source.

valid = data.emailCheck ? true : 'Email is invalid.';

**Comment by prasanjeetdas** [comment]
> This could be achieved by using our Data Source component where the endpoint to validate the email would be triggered on the change of the email field (using the trigger section). You would then make the validation of the email field depend on the valid state of the data source.
> 
> valid = data.emailCheck ? true : 'Email is invalid.';

through Premium Actions/Components (paid version).
