### ISSUE TITLE
[BUG] EditGrid column labels/names are not translated

### ISSUE THREAD

**Issue by llaurentiu** [formio/formio.js#3955]
## Environment
Please provide as many details as you can:

- Formio.js version: any
- Frontend framework: any
- Browser: any

Edit grid columns are not translated.
The reason is that in the header template, the component labels are not run through the translate function.

I created a PR that fixes it here: https://github.com/formio/formio.js/pull/3954

**Comment by pa-aaron** [comment]
There is still a small issue here, where by default the Column Headers were not translated in Edit Grids. I've made a PR at #4486

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
