### ISSUE TITLE
Bootstrap 5 Support?

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#3956]
Any current support for bootstrap 5? If not, any plans for it yet?

**Comment by ProteanHub** [comment]
bump

**Comment by travist** [comment]
Yes, we will create support for bootstrap 5 in an up coming release.

**Comment by ProteanHub** [comment]
Ok, thanks @travist ! We are looking to use a new web site template and will defer to Bootstrap v4 for now as they offer a v5 and v4 option.

**Comment by sayedmohsinreza** [comment]
Any updates on it?

**Comment by Ruxx28** [comment]
when will you update it?

**Comment by travist** [comment]
This is done and ready to be merged.

https://github.com/formio/formio.js/pull/4607

We plan on doing this once we release our next major milestone for our platform which is to introduce a new portal interface (currently in Bootstrap 4). Once this occurs, you will then see a lot of movement in this repository where we merge a log of the outstanding PR's to get a new build in place.

Thank you for your patience.

**Comment by ilyas5** [comment]
Any update on Bootstrap 5?
