### ISSUE TITLE
DataGrid header and footer template?

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#3963]
Is there any way to define DataGrid header and footer, like EditGrid has?

**Comment by mikekotikov** [comment]
@krixerx for now DataGrid does not support such functionality from the builder.
But in your application you can override the template for DataGrid with your own.
You can take the default used template from `src/templates/bootstrap/datagrid/form.ejs`, copy it, change for your needs and apply it as written in the [docs](https://github.com/formio/formio.js/wiki/Templates-API#overriding-templates).
Here is a small [example](https://gist.github.com/mikekotikov/593bc9a3c68d33affb35224307db0acf) of how you can perform this.

**Comment by krixerx** [comment]
Merci beaucoup!
That sounds good!
