### ISSUE TITLE
[DOCUMENTATION] How to duplicate a form or subform  

### ISSUE THREAD

**Issue by tacman** [formio/formio.js#3969]
I'm trying to render a form with a "Add Another" option, e.g. a family form where you're asked to enter the data about each child (firstname, lastname, date of birth).  

I see that there's a Nested component, but I'm not sure how to use it (or even if that's the right component).  If this is possible, could you point me to the documentation (and/or an example) please.

Thanks.

**Comment by ccontour** [comment]
I believe you are looking for Data Grids

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
