### ISSUE TITLE
[BUG] form.showError no longer accepts strings

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#3970]
- Formio.js version: 4.13.0

## Steps to Reproduce
1. form.showErrors('error');
2. form.showErrors(['error']);
3. 

## Expected behavior
Previous to https://github.com/formio/formio.js/commit/9d645494d4cb89b8fc5df78ae5a5bed0006504f0#diff-7855a6dd80d9df39fdfc8b5408184edab6a38ecfb49a165c448d5dfab1264a1fR1210 showError accepted a string or an array of strings

## Observed behavior
showError fails with "TypeError: Cannot create property 'formattedKeyOrPath' on string"

**Comment by ccontour** [comment]
@paulfalgout I see you have a commit referenced that seems to provide a fix to this issue. If you are happy with that solution, can you provide that as a PR to this repository and we can try to get it merged in?

**Comment by wag110894** [comment]
Hello @paulfalgout, 
Can you provide an example of the issue taking place?

**Comment by paulfalgout** [comment]
No need for a video.  https://jsfiddle.net/5cgkuj8n/
```js
Formio.createForm(...).then(function(form) {
  // Both of these used to work and now they don't
  form.showErrors('error');
  form.showErrors(['error']);
});
```

**Comment by bilogic** [comment]
@paulfalgout 

Was your issue addressed? The docs say it has to be an object but webform.js itself still uses string. This is getting quite confusing #4862

**Comment by paulfalgout** [comment]
AFAIK this hasn't been addressed @bilogic

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
