### ISSUE TITLE
Hidden component with modalEdit option.

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#3972]
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: latest
- Formio.js version: latest
- Browser: Chrome
- Browser version: 89.0.4389.114 

## Steps to Reproduce
1. Create textField component with hidden and modalEdit options
![image](https://user-images.githubusercontent.com/22855299/114688828-c46ca900-9d1d-11eb-8bf3-66e28e18d646.png)

## Expected behavior
Button "Click to set value" is hidden
## Observed behavior
Button "Click to set value" don't hidden
In modal window component is hidden
![image](https://user-images.githubusercontent.com/22855299/114689181-1d3c4180-9d1e-11eb-9726-01e8c1b20c24.png)

**Comment by wag110894** [comment]
This seems to be working as expected but really something that seems to pair together. Do you have any recommendations on what this should do?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
