### ISSUE TITLE
[BUG] datagrid fixedLayout option no longer fully working

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#3986]
During 4.13 development awkward "fixes" were made to the datagrid

A change was made to fix "fmg 99 padding".
https://github.com/formio/formio.js/pull/3544
This added `class="col-md-{{ctx.colWidth}}"` to all of the datagrid `td`s

Then that change was half-removed and broken further in 
https://github.com/formio/formio.js/pull/3658

Apparently adding those classes in 3544 caused a problem, so the fix was to add the class `col-md-` to the `th`s based on `colWidth` which was removed, and then remove most of the changes from the previous PR, and change a bunch of other stuff, including breaking `fixedLayout: false` the default setting if a select is included within the datagrid.  Having a select certainly _does not_ require a fixed layout table in order to work.

I think both PRs should be reverted and whatever the original issue was should be readdressed.

**Comment by paulfalgout** [comment]
@wag110894 where was this fixed?

**Comment by paulfalgout** [comment]
@wag110894 Can you let me know what version to expect this fix in?

**Comment by mikekotikov** [comment]
@paulfalgout the `fixedLayout` option should be fixed since `formiojs@4.13.0-rc.7`.
If you'll still experience some issues with that, please share the form json and ping me back.

**Comment by paulfalgout** [comment]
It looks like the fixes might be somewhere in here
https://github.com/formio/formio.js/commit/afefc5ca26195a92ff0a5a42540aaee9b54376ba
https://github.com/formio/formio.js/commit/e4f55a0dfac4d2e9a72db971eebef9a1667e1ad6
https://github.com/formio/formio.js/commit/41c00fe2823f803ddc1f1ca3b0b5ecf410768af4
