### ISSUE TITLE
[BUG]  Uncaught ReferenceError: Formio is not defined

### ISSUE THREAD

**Issue by YouginaCh** [formio/formio.js#3989]
The formio script won't work any more , I started receiving  this issue  with formio official doc examples  : 

Uncaught ReferenceError: Formio is not defined
    at window.onload (Form.html:9)

## Expected behavior

loads the forms contents.

##  Fomio form.html with inspect screenshot

![Screenshot 2021-04-16 at 18 40 45](https://user-images.githubusercontent.com/82672934/115063287-46f29580-9ee3-11eb-851e-f3e4bf6063dc.png)

```js
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.form.io/formiojs/formio.full.min.css">
    <script src="https://cdn.form.io/formiojs/formio.full.min.js"></script>
    <script type="text/javascript">
      window.onload = function() {
        Formio.icons = 'fontawesome';
        Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example');
      };
    </script>
  </head>
  <body>
    <div id="formio"></div>
  </body>
</html>
```

**Comment by mikekotikov** [comment]
@YouginaCh thanks, seems we need to update the script on cdn. For now you can use this url instead to point to the latest version of formio.js: `https://unpkg.com/formiojs@latest/dist/formio.full.min.js`. You can also specify the version after `@` if you wish (ex. `formiojs@4.12.7`)

**Comment by mikekotikov** [comment]
@YouginaCh appeared to be an encoding issue. [Here is how to update the template](https://github.com/formio/formio.js/pull/4005/files) to make formiojs script work fine.
