### ISSUE TITLE
[BUG] Endless/Infinite loop occurring for calculated values - need protection against change loops 

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#3992]
## Environment

- Formio.js version: latest
- Frontend framework: all
- Browser: all

## Steps to Reproduce

You can see the issue occur: https://formio.github.io/formio.js/app/builder

1. Create a form with a calculated value that will change on every onChange action: such as `value = new Date().toISOString()`

<img width="1795" alt="Screen Shot 2021-04-19 at 10 20 29 AM" src="https://user-images.githubusercontent.com/1994838/115252044-1be18f00-a0f9-11eb-8ccc-80762075649a.png">

<img width="659" alt="Screen Shot 2021-04-19 at 10 22 26 AM" src="https://user-images.githubusercontent.com/1994838/115252089-26038d80-a0f9-11eb-9e96-ae2d822906eb.png">

2. Watch the value endlessly change/update

## Expectations

It appears that formio.js will perform a endless loop when calculated values are used and the calculated value changes on every check.  This appears to be caused by the way formio calculates a change: where the calculated value is activated when the form loads, BUT it also re-cacluates it-self.  As a result in the case of values such as dates with millisecond precision, an endless loop is triggered and formio does not guard against this.

Expectations would be something in the area of:

1. formio and/or the browser is detecting the loop as a performance issue
2. formio maybe has a max loop setting before throwing an error?

**Comment by StephenOTT** [comment]
Any update on this?  Is there a mitigation for this?

Thanks!

**Comment by travist** [comment]
Hey @StephenOTT we are getting some feedback from other customers that this is an issue, so we have added this as one of our topics for discussion next planning meeting. We will inform you on what we decide. We may have to come up with a better change detection strategy to resolve some of these issues.

**Comment by StephenOTT** [comment]
Thanks

**Comment by lane-formio** [comment]
This issue is expected to have resolved with this PR: https://github.com/formio/formio.js/pull/4082
