### ISSUE TITLE
Remove submit button on readonly mode

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#3998]
Is there a way to remove a submit button on a form that is readonly? You don't see the submit button on a wizard but it's available in form display mode

**Comment by travist** [comment]
Maybe add a condition on the button that says.

```
show = !instance.options.readOnly;
```

**Comment by aminmc** [comment]
Is there not a global option? I would have to apply that logic to every form.

**Comment by MaksimFalei** [comment]
Hello @aminmc, you can use the viewAsHtml option additionally.
If a form has readOnly and viewAsHtml it will hide all buttons;

```
<formio src="submissionUrl" read-only="true" options="{viewAsHtml: true}"></formio>
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
