### ISSUE TITLE
Custom component in formio.js

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#400]
hi
i would be wondering if u could tell me is there any way to add custom component to formio.js?
i found a solution in angular version but couldn't found any in pure js version 
thanks

**Comment by asalhani** [comment]
@amirmf check the code in [this closed defects](https://github.com/formio/angular-formio/issues/85). Although it's being answered under Angular project, however, same steps can be applied in vanila JavaScript but your project should use TypeScript since the core of form.io (render engine) is being written by it.

**Comment by amirmf** [comment]
@asalhani thanks for the response 
you mean we cant register any custom component if we use pure js renderer like below ???

 Formio.createForm(document.getElementById('taskForm'), formioJSON,formOptions).then(function (form) { ....

**Comment by travist** [comment]
Here is a Gist of how to create custom components. The registration of this component in the gist happens in Angular 5, but the concept is the same for just the vanilla.js renderer here. 

https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075

**Comment by Aiso786** [comment]
Awesome. Thank you @travist

**Comment by Sigkill9** [comment]
@travist @Aiso786 does this line work for you?
 import { FormioForm } from 'formiojs/full';
if so what version are you using? 
I am using: "formiojs": "^3.5.3" and so far cannot find this formiojs/full

I just want to use a custom component and cannot as this code does not work!
What am I missing here?
Thanks.

**Comment by Aiso786** [comment]
Hello @Sigkill9 
I'm doing like this with the latest version:

`import { Formio, Form } from 'formiojs';
...
Formio.registerComponent('tabs', CustomTabsComponent);`

**Comment by Sigkill9** [comment]
@Aiso786 Thanks for the reply. 
I am using angular-formio and have installed formiojs using:
**npm i formiojs --save**
and the @types/formio is not a thing.

I have this problem?
Could not find a declaration file for module 'formiojs'. 'c:/angularapp/node_modules/formiojs/index.js' implicitly has an 'any' type.
  Try `npm install @types/formiojs` if it exists or add a new declaration (.d.ts) file containing `declare module 'formiojs';`

**Comment by Aiso786** [comment]
You just need to 
> add a new declaration (.d.ts) file containing declare module 'formiojs';"

**Comment by virajkanwade** [comment]
> You just need to
> 
> > add a new declaration (.d.ts) file containing declare module 'formiojs';"

Where? :(

**Comment by rohitsiddha** [comment]
> You just need to
> 
> > add a new declaration (.d.ts) file containing declare module 'formiojs';"

Can you please let me know where to add this file?

**Comment by Sigkill9** [comment]
Stepping out of this thread as my issue is really about registering custom components in angular-formio and not vanilla JavaScript.

Based on the example below.
[Angular 5 + Form.io Custom Component](https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075)

**Comment by psmarsch** [comment]
Hi fomiojs,

I am facing the same issue (being on 4.0.0-rc.22).

HOW TO REPRODUCE

1. Take the sample component Javascript as it is from:
https://github.com/formio/formio.js/blob/v4.0.0-rc.22/app/examples/customcomponent.md 

2. Add it to the builder:
`
        mygroup: {
            title: "My Group",
            key: "mygroup",
            default: true,
            weight: 0,
            components: {
                checkmatrix: {
                    title: "Check Matrix",
                    group: "mygroup",
                    key: "checkmatrix"
                }
            },
            subgroups: []
        }
`

CURRENT BEHAVIOUR

The component is displayed for selection and it is possible to add it to the form. However, there is no preview available:

![image](https://user-images.githubusercontent.com/51445681/62279394-4897d380-b44a-11e9-92a8-ed4759206e88.png)

**Comment by psmarsch** [comment]
Additional Note: 

When taking the component code from https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075 without altering it, not even the "unknown component" message is displayed. The console says "component.render is not a function".

![image](https://user-images.githubusercontent.com/51445681/62281066-63b81280-b44d-11e9-9a8a-de7d87843abc.png)

Please provide a working example for a custom component. Thank you!

**Comment by randallknutson** [comment]
That component is designed for the 3.x branch. Here is the same one converted to the 4.x branch which has very different internals. https://github.com/formio/react-app-starterkit/blob/master/src/components/CheckMatrix.js

**Comment by psmarsch** [comment]
@randallknutson 
Thank you, this worked as expected! Also, it looks cleaner than the previous version.

I just had to add
`Formio.Components.addComponent('checkmatrix', CheckMatrix);`
at the end.
