### ISSUE TITLE
FormIO form submission discard empty values

### ISSUE THREAD

**Issue by waqar1** [formio/formio.js#4006]
Is there an option to discard components having empty values from form submission ? 

I have conditional components but on form submission, components that are hidden and have no value are also part of form submission event with empty values. Which I want to discard but cannot find in documentation.

**Comment by wag110894** [comment]
Hello @waqar1,
We do not have this functionality.

**Comment by waqar1** [comment]
Thank you @wag110894. Much appreciated.
