### ISSUE TITLE
Use hex colors when creating button component

### ISSUE THREAD

**Issue by Josema93web** [formio/formio.js#4007]
Good Morning.

We are currently developing a custom component, in which you want to insert buttons within it.
We have seen that the colors it accepts are bootstrap's own (such as "success", "info", "danger" ...)

I attach an example:
            Formio.createForm($(self.element).find('.table-responsive #dataTable tbody tr #buttonRef'), {
                components: [
                                           {
                                              type: "button",
                                              key: "sendMail",
                                              label: "Send an Email",
                                              input: true,
                                              theme: "success"  // Here I have tried to add the hexadecimal color (for example # CD5C5C), but it 
                                                                               does not work, it takes a gray color by default
                                           }
                                      ]
            });

Is there a way to be able to assign colors in hex in addition to bootstrap's own?

Thank you very much in advance.
All the best.

**Comment by ccontour** [comment]
It'll be easier CSS to override the theme for that button (keeping all your styling decisions together in a CSS file) instead of trying to style directly

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
