### ISSUE TITLE
Possibility to refresh the forms list of Nested Form component.

### ISSUE THREAD

**Issue by e-gauthier** [formio/formio.js#4030]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.13.0
- Frontend framework: React
- Browser: Chrome
- Browser version: 90.0.4430.93

We have a controller that return a list of available forms for the Nested Form component.
The communication work and a list appears in the Select box.

However, since the system is cached to avoid unnecessary callback to the server, there is no way to refresh the list to see if new forms are available.

## Steps to Reproduce
1. Create a form named FormA with a textbox and save.
2. Create a form named FormB with a textbox and save.
3. Create a form named FormC.
4. Add a nested form.
5. Open the select in the form tab. The list contains FormA and FormB.
6. Open a new tab in the browser.
7. Create a form named NewFormD with a textbox and save.
8. Return to the previous tab in the browser.
9. Click on the list in the From tab of the Nested Form.
10. The list contains only FormA and FormB.
11. BUT, if you search for NewForm, the item is shown.

## Expected behavior
Maybe a refresh icon near the control would be nice.
## Observed behavior
There is no way to refresh the list of form.

**Comment by wag110894** [comment]
Hello @e-gauthier, 
Can you provide a form embed so that we can replicate?

**Comment by e-gauthier** [comment]
> Hello @e-gauthier,
> Can you provide a form embed so that we can replicate?

To be able to load a NestedForm, you need a server.  

Also, the form ids that Formio load are the ones from the server.

I'm afraid, you will have to create it on your own dev environment.

**Comment by wag110894** [comment]
Hello @e-gauthier,

Thank you for your patience. We have created a ticket for this feature to be added to our platform. For reference, the ticket number is FIO- 3450. Please let us know if you are interested in a quote for this new feature.
