### ISSUE TITLE
Create a custom seperator for Select control with multiple options

### ISSUE THREAD

**Issue by ashutoshkumars** [formio/formio.js#4033]
Hi Team,
  I wanted to create a Select control where i can have multiple values seperated by "|" (pipe) symbol. However, select control only joins on comma sign. 

```
https://formio.github.io/formio.js/docs/file/src/components/select/Select.js.html
Line 1149
  getValueAsString(data) {
    return (this.component.multiple && Array.isArray(data))
      ? data.map(this.asString.bind(this)).join(', ')
      : this.asString(data);
  }

``` 

Can we have an option where we can define our custom seperator character, instead of default comma sign ?

Thanks,
ashutosh

**Comment by irshadmb** [comment]
You can overwrite through custom javascript to process it.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
