### ISSUE TITLE
How to add dynamic dropdown or custom control on on edit form popup in formio drag and drop?

### ISSUE THREAD

**Issue by AnujAttri** [formio/formio.js#4042]
Hi, I want to populate dynamic dropdown or controls value from database on edit form popup in formio. I have already populated left hand side components from the database dynamically but now i need my full control on its edit form functionality so that i can show more setting for one dragged component and hide unnecessary setting.

I am populating left components from database in loop as shown below in the code.
SetLeftComponents method is called in loop with incremented i value and result every time.

                    function SetLeftComponents(result, i) {
                        var htmlComponent = Formio.Components.components.textfield;

                        function CustomizeComponent(component, options, data) {
                            htmlComponent.prototype.constructor.call(this, component, options, data);
                        }

                        CustomizeComponent.prototype = Object.create(htmlComponent.prototype);
                        CustomizeComponent.prototype.constructor = CustomizeComponent;

                        CustomizeComponent.schema = function () {
                            return htmlComponent.schema({
                                label: result[i].screenName,
                                type: 'textfield',
                                tag: 'input',
                                key: result[i].tableColumnName,
                                CustomizeID: result[i].customizeID,
                                datalength: result[i].dataLength,
                                content: result[i].tableColumnName
                            });
                        };

                        CustomizeComponent.builderInfo = {
                            title: result[i].screenName,
                            group: 'basic',
                            icon: 'fa fa-terminal',
                            weight: 10,
                            id: result[i].customizeID,
                            documentation: 'http://help.form.io/userguide/#table',
                            schema: CustomizeComponent.schema()
                        };

                        CustomizeComponent.prototype.render = function (element) {

                            //console.log("HeaderComponent.prototype.render",element,this)

                            return this.renderTemplate('html', {
                                component: this.component,
                                tag: this.component.tag,
                                attrs: this.component.attrs || {},
                                content: this.content,
                                singleTags: this.singleTags,
                            });
                        };

                        CustomizeComponent.prototype.elementInfo = function () {
                            const info = htmlComponent.prototype.elementInfo.call(this);
                            info.changeEvent = 'click';
                            return info;
                        };

                        CustomizeComponent.prototype.getValue = function () {
                            var value = [];
                            if (!this.refs.input || !this.refs.input.length) {
                                return value;
                            }
                            for (let i = 0; i < this.component.numRows; i++) {
                                value[i] = [];
                                for (let j = 0; j < this.component.numCols; j++) {
                                    var index = (i * this.component.numCols) + j;
                                    if (this.refs.input[index]) {
                                        value[i][j] = !!this.refs.input[index].checked;
                                    }
                                }
                            }
                            return value;
                        };

                        CustomizeComponent.prototype.setValue = function (value) {
                            var changed = htmlComponent.prototype.updateValue.call(this, value);
                            if (!value) {
                                return changed;
                            }
                            for (let i = 0; i < this.component.numRows; i++) {
                                if (!value[i]) {
                                    break;
                                }
                                for (let j = 0; j < this.component.numCols; j++) {
                                    if (!value[i][j]) {
                                        return false;
                                    }
                                    let checked = value[i][j] ? 1 : 0;
                                    var index = (i * this.component.numCols) + j;
                                    this.refs.input[index].value = checked;
                                    this.refs.input[index].checked = checked;
                                }
                            }
                            return changed;
                        };
                        // Use the htmlelement component edit form to build the form element
                        //CustomizeComponent.editForm = Formio.Components.components.textfield.editForm;

                       

                        CustomizeComponent.editForm = function () {
                            return htmlComponent.editForm([
                                {
                                    label: 'OVERWRITE ME',
                                    weight: 100,
                                    key: 'display',
                                    ignore: false,
                                    components: [
                                        {
                                            key: 'refreshOnChange',
                                            ignore: true
                                        },
                                        {

                                            // originally a textarea with Ace editor.
                                            type: 'textfield',
                                            key: 'content',
                                            input: true,
                                            ignore: false,
                                            //editor: 'ace',
                                            //rows: 10,
                                            //as: 'html',
                                            label: 'xContent',
                            weight: 80
                                        }
                                    ]
                                }
                            ]);
                        };

                        Formio.Components.addComponent(result[i].tableColumnName, CustomizeComponent);
                    }

Please help me as soon as possible and as you can do.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
