### ISSUE TITLE
 How to activate logic in constructor mode?

### ISSUE THREAD

**Issue by vlont** [formio/formio.js#4046]
I'm using the form builder and when I program a logic, it works in the final form, but it doesn't work in constructor mode.

**Comment by wag110894** [comment]
Can you explain what do you mean by constructor mode?

**Comment by sr-msilva** [comment]
Hello sorry. I meant using the drag and drop form builder, I would like custom logic to work directly on it. Without having to render the json schema to be able to test

**Comment by ccontour** [comment]
What type of logic are you trying to get working inside the builder? Can you describe your goal / use case

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
