### ISSUE TITLE
[Question] : Is it possible to create a URL by using values from other fields?

### ISSUE THREAD

**Issue by prateekmishra13** [formio/formio.js#4050]
I want to create a URL by using vales from other API keys. Ex: https:// + APIKEY1 + APIKEY2
This should be  a clickable URL. I did check the URL feature but it cerates a simple text field. Clickable URL can be generated by HTML component by writing below code in content.
"a href="https://www.google.com">google</a"

Now I want to fetch some portion of this URL from other API keys/elements. Any help regarding this?

**Comment by mohammadk2** [comment]
hi try this.

`{ "components": [
        {
            "label": "text",
            "tableView": true,
            "defaultValue": "click me",
            "key": "text",
            "type": "textfield",
            "input": true
        },
        {
            "label": "href",
            "tableView": true,
            "defaultValue": "www.google.com",
            "key": "href",
            "type": "textfield",
            "input": true
        },
        {
            "label": "link",
            "tag": "span",
            "attrs": [
                {
                    "attr": "",
                    "value": ""
                }
            ],
            "content": "<a href='{{data.href}}'  >{{data.text}}</a>",
            "refreshOnChange": true,
            "key": "link",
            "type": "htmlelement",
            "input": false,
            "tableView": false
        }
    ]
}`
