### ISSUE TITLE
[QUESTION] Use camera on file component

### ISSUE THREAD

**Issue by YouginaCh** [formio/formio.js#4052]
## Environment

Since formio does not offer a clear SDK for react native, the solution  for us was to build our form inside a WebView ( loading  html which uses a formio version scripts stored into CDN ),  we which to have a behaviour like in angular and Cordova  but when choosing use camer a video streaming zone was opened , not the native camera

## Question
Does formio js  offers a way to test if loaded content was in a native-web-view app , not a web ( behaviour mentioned is for Web)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
