### ISSUE TITLE
[BUG] - Flatpickr calendar widget anchored to the center (should be left)

### ISSUE THREAD

**Issue by elibus** [formio/formio.js#4061]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Add a text field
2. Configure the text field to use a calendar widget
3. Click on the component, the calendar pops up

## Expected behavior

The calendar widget should be anchored to the left.

## Observed behavior
The calendar is centered with formiojs 4.13.x

## Example
Use this codepen: https://codepen.io/localhorst/pen/BaaEBZz
just add the caledar widget to the text field. 
![Screenshot 2021-05-06 at 13 57 13](https://user-images.githubusercontent.com/1153733/117295608-588ce480-ae74-11eb-969d-0aae4e1a7ade.png)

**Comment by elibus** [comment]
@heather-formio this is ECB

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
