### ISSUE TITLE
Root user or password was incorrect - Form.IO

### ISSUE THREAD

**Issue by nitpanj56** [formio/formio.js#4063]
Hi,

I downloaded form builder interface Github code using the below link:

https://github.com/formio/formio

I followed all the steps mentioned within the link. But after I run the command npm start, the terminal prompts root user credentials. I typed in an email/password and successfully registered the root user. Now, these root user credentials are used for the admin sign-in form. But, every time I enter credentials it gives me the error "user or password was incorrect" as shown in the below image

![image](https://user-images.githubusercontent.com/83805027/117423613-89d1e700-af3e-11eb-888b-36ca4c988fc1.png)

Please let me know what is required to be done.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
