### ISSUE TITLE
Add "data" tab parameters on custom components

### ISSUE THREAD

**Issue by lennygir** [formio/formio.js#4066]
In some basic components there's a "data" tab parameters (see image), i want it on my custom components but i dont know how to implement it because there's absolutly no documentation... 

Basic component :
[![enter image description here][1]][1]
My component : 

[![enter image description here][2]][2]

Does anyone has aldready did it ?
Thank you 

  [1]: https://i.stack.imgur.com/6HPHc.png
  [2]: https://i.stack.imgur.com/O3ypM.png

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
