### ISSUE TITLE
[BUG] Formio Doesnt Always Load Data in The Form

### ISSUE THREAD

**Issue by crivera305** [formio/formio.js#4068]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12.1
- Frontend framework: Bootstrap 4
- Browser: Chrome / Safari
- Browser version: Various -  Chrome Version 89.0.4389.128

## Steps to Reproduce
1. Goto https://jsfiddle.net/mr24hour/cw04oy8f/2/
2. Click Play button to refresh the demo enough times till you see the form render with no data prepopulated

## Expected behavior

Every time a form that has data to pre populate a form, should load pre populated.

## Observed behavior

Randomly, Formio pre populated the form and other times formio renders the form blank as if no data was provided 

## Example

Link to recreate the issue: https://jsfiddle.net/mr24hour/cw04oy8f/2/
Link to Video to watch the issue in action: https://streamable.com/2vn41f

If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

All code is in the jsfiddle example 

############

I am using the following version ( https://unpkg.com/formiojs@4.12.1/dist/formio.full.min.js ) which was fine until May 5th. May 5th we started to get complaints by clients who are unable to see data they entered into FORMIO.

The HUGE issue we are having is happening upon the rendering of the data onto the form. 

A regular user with the developer toolbar closed and cache on will most of the time show the form with no data loaded.

As a developer if I have my developer toolbar open and cache is disabled upon refresh I can see the data loaded into the form at a higher rate. 

I was able to extract the form from the application to prove the issue is not with the application but within formio specifically by creating a static page on jsfiddle for review. ( https://jsfiddle.net/mr24hour/cw04oy8f/2/ ). From this link click play to refresh the demo enough to see the issue at play.

I created a video to show upon refreshing of the page - formio is not loading the data on to the form consistently as expected. ( https://streamable.com/2vn41f )

The issue here is very big as forms that were previously filled out are loading BLANK and users are trying to reenter the data and save resave the form - even though the data is saved in the backend. This can quickly lead to data integrity issues and needs review ASAP.

I set the code up when we load data using form.data  i binded that to window so we should be able to check the formio component by checking the console for: window.form.
 
When the data fails to load window.form.data is not set properly. 
When the data loads successfully window.form.data is set.

Since this is a static page, the backend is not the issue here, seems the front end formio rendering engine seems to be the problem here.

**Comment by crivera305** [comment]
I was instructed by support that the version 4.13 of form.io should solve the issue but after further review not only does the issue still exist. Version 4.13 introduces a new issue where the file uploader component doesn't work.


Here is a link to jsfiddle using 4.13 example: https://jsfiddle.net/mr24hour/r35w6jv9/1/

- The original issue where the form doesn't load the data is still present
- a new issue is present - file uploads are not loading as expected. The form loads and the upload component shows dimmed with loader that never goes away

Video of the issue showing both issues with the new version: https://streamable.com/cdlqp2

**Comment by crivera305** [comment]
Support pointed our version 4.13.1 required a css update which was missed.  I have updated the demo to use 4.13.1 js and css and still find the original issue with form.io not always pre populating the form.

Upon loading of form.io component - the data does not always populate the form even when using the latest 4.13.1 version.

Please note: https://unpkg.com/formiojs@latest/dist/formio.full.min.js currently redirects to https://unpkg.com/formiojs@4.13.1/dist/formio.full.min.js

We never hardcode @latest into our project. We use versioned files which is why we reference the version instead of the latest in our demo and application.

Please review the updated jsfiddle demo which shows the issue is still present: 
https://jsfiddle.net/mr24hour/r35w6jv9/4/

Here is a video that demonstrated version 4.13.1 still has issues with pre populating forms on load: 
https://streamable.com/qbnf8t

**Comment by edwinanciani** [comment]
Hi @crivera305 watching your video and trying to replicate the issue I found that there is a `Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null` which is caused a line in the code 340 that you implemented.

` document.getElementById('saveButton').addEventListener('click', validate);`

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
