### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by virenderAttri** [formio/formio.js#4076]
Hi,

Is it possible that we can handle onchange or something event in editform popup?
Actually
             The requirement is that I have added a custom dropdown in data tab component in editform popup
             like this { type: 'select', key: 'dynamic', label: 'Dynamic Data For', data: { values: dynamicDropdown }, input: true, validate: { onChange: "change", optionsChangedEvent: "change" } } 
             
but here I need to show or hide another custom control in base of this changing dropdown value ,here I have already tried something optionchangeEvent but not working  so please help me to out this that there is a way or or not to do this
And please make sure we are using JavaScript API documentation

**Comment by anthemi** [comment]
I have the same issue, need events to trigger new action on custom controls added

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
