### ISSUE TITLE
Question:  Using the renderer with a bootswatch theme

### ISSUE THREAD

**Issue by srinisubramanian** [formio/formio.js#4078]
Before instantiating the renderer, we include one of the bootswatch themes, like for e.g. darkly.  However somehow bootstrap standard is overriding and the theme is not taking effect .. 

Any ideas on how to correctly set the theme to a bootswatch them in the renderer using theme bootstrap?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
