### ISSUE TITLE
Security Vulnerability with dependancy ssri

### ISSUE THREAD

**Issue by kurianbenoy-aot** [formio/formio.js#4091]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.13.1
- Frontend framework: VueJs
- Browser: Firefox
- Browser version:

## Steps to Reproduce
1.  In your package-lock.json the package `cacache` has a sub dependency of `ssri 6.0.1` which is having a security vulnerability.

https://github.com/formio/formio.js/blob/master/package-lock.json#L3478

![image](https://user-images.githubusercontent.com/70306694/119437132-1ea85300-bd3b-11eb-9115-cc8f5e038daa.png)

**Comment by ccontour** [comment]
If you need to deal with this CVE before an update gets pushed, you can update your own package.json resolutions to bump the version inside your code.

https://classic.yarnpkg.com/en/docs/selective-version-resolutions

**Comment by kurianbenoy-aot** [comment]
Thanks you @ccontour. Will do that.
