### ISSUE TITLE
[BUG] Translation:  Untranslated Text in Data Tab of Password Field

### ISSUE THREAD

**Issue by Vedhachala** [formio/formio.js#4092]
## Environment
Please provide as many details as you can:

- Formio.js version: latest
- Frontend framework: angular
- Browser: Chrome

## Steps to Reproduce
1.  Add a Password Component 
2. Go to data tab in the Edit Dialog

This is the untranslated text: 

"Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API."

<img width="362" alt="PasswordUntranslated" src="https://user-images.githubusercontent.com/15833345/119525735-627f7480-bd9c-11eb-86f3-2462405d1298.PNG">

Added translation for that text while passing translations via i18n resources.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
