### ISSUE TITLE
Unable to use custom date format(dd-MM-yyyy) for component date

### ISSUE THREAD

**Issue by vijaynet10** [formio/formio.js#4094]
Hai I am using formiojs version 4.12.0 , with this version everything looks good except the date picker with custom date (dd-MM-yyyy), but it is working fine with the default format (yyyy-MM-dd),
I'm tried to set custom format(dd-MM-yyyy) but it is  not staying as the one that selected.
Ex: 
With custom date  format (dd-MM-yyyy)  am selecting the date value : 26-05-2021 then am leaving the control it changes the value to 20-01-2021

**Comment by wag110894** [comment]
Can you try a later version of formio.js and see if the issue has been resolved?

**Comment by vijaynet10** [comment]
Hai @wag110894 thanks for the response ,I have tried with the latest version (4.13.1) , the custom date formats worked as expected but we cant continue with new version  (4.13.1), the validation on event not triggered with new version. but in previous version the validation on event working fine. So we rolled back to the previous version (4.12.0)

![image](https://user-images.githubusercontent.com/4167992/119752385-8f29ae00-beba-11eb-9375-cb006b180d28.png)

**Comment by vijaynet10** [comment]
its working as expected with the latest version thank you @wag110894

**Comment by mohammadaaqib** [comment]
@vijaynet10  @wag110894  i am facing same issue with angular formio 4.11.5.

**Comment by mohammadaaqib** [comment]
@wag110894  https://github.com/formio/angular/issues/912 ticket link

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
