### ISSUE TITLE
[Question] Bootstrap 5 support

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#4095]
As formiojs@5 will drop support for semantic and bootstrap3, are there any plans to adopt bootstrap5 or will bootstrap4 remain the default template for formio.js?

**Comment by ccontour** [comment]
There are no current plans to make that type of upgrade

**Comment by ckoch1979silentservice** [comment]
I do not understand. Is Bootstrap 4 supported? I still just see Bootstrap 3 in the snippets. When will it be dropped? 

In general it is quite complicated to use form.io regarding CSS if you do not want to use this old Bootstrap version.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
