### ISSUE TITLE
[BUG] Wizard Form Builder deletes page components on cancel

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#4096]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:  `4.x`
- Frontend framework: `React `/ `Vanilla JS`
- Browser: `Chrome` / `Firefox `/ `Edge`
- Browser version: `latest`

## Steps to Reproduce
1. Render the FormBuilder
2. Set display as wizard
3. Add some components to the form
4. Click on the page delete icon
5. Once the warning alert comes up, click on cancel
6. Nested components will still be deleted

## Expected behavior
If the user clicks on the wizard page component's delete button, after clicking on cancel, no changes should be made to the form schema.

## Observed behavior
After the user clicks on cancel, all the page's nested components are deleted regardless of his intention to cancel the deletion.

## Example
- [Vanilla JS](https://codesandbox.io/s/formio-builder-js-dbl8z)
- [React](https://codesandbox.io/s/formio-builder-react-qdod1)

PS: The `Missing projectId` error has already been reported here: https://github.com/formio/formio.js/issues/4048

```html
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.form.io/formiojs/formio.full.min.css"
    />
    <script src="https://cdn.form.io/formiojs/formio.full.min.js"></script>
  </head>

  <body class="container px-1 pt-2">
    <div id="app"></div>
    <script>
      window.addEventListener("load", () => {
        const form = {
          display: "wizard",
          components: [
            { type: "textfield", label: "First Name", key: "firstName" },
            { type: "textfield", label: "Last Name", key: "lastName" }
          ]
        };
        Formio.builder(document.getElementById("app"), form, {});
      });
    </script>
  </body>
</html>
```

**Comment by wag110894** [comment]
Hello @airarrazaval,

Can you provide a video of this issue occuring?

**Comment by airarrazaval** [comment]
https://user-images.githubusercontent.com/9391489/123906805-d6381280-d942-11eb-8f61-5d4cc9ff0409.mp4

**Comment by MoraParamesh5b0** [comment]
I have same issue related to it and also getting an extra console error by just dragging to drop area as below
![image](https://user-images.githubusercontent.com/89075952/129711193-258e0235-d87e-4cfe-9fae-649a4df96482.png)
https://prnt.sc/1q45cjh
when i click action buttons of field saving like save, cancel, remove and close icon in top of window 
Below are the screenshot of errors i am getting
![image](https://user-images.githubusercontent.com/89075952/129711366-252ab869-1c99-4682-b8d5-da22e3aebcde.png)
https://prnt.sc/1q45i3u
and i am using angular 12 with below versions
"formiojs": "^4.13.5",
"angular-formio": "4.11.0",
    "@webcomponents/webcomponentsjs": "2.6.0",
    "@webcomponents/custom-elements": "1.3.0",

Help me if any thing need to change or any extra information provided
