### ISSUE TITLE
Question Label Length

### ISSUE THREAD

**Issue by dwaynedsouza** [formio/formio.js#4097]
Hi,

Is there a setting by which I can limit the number of characters in a question Label or option value?

In my scenario, users create questions and I parse the JSON to save the questions in my database but the question field has a limit of 80 characters. Any advice would be useful

Thanks.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
