### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by virenderAttri** [formio/formio.js#4114]
Hi ,

Is it possible that we can change this header text in edit form of every component,

![Screenshot 2021-06-02 064115](https://user-images.githubusercontent.com/83203521/120490837-972b9700-c36d-11eb-97d1-f0a7a78ac322.png)

Actually we are using many custom or other components, and now as per requirement we want to change the header text of edit form accordingly.

So please help that there is a way or not to do this in javascript or something in Formio.Components

**Comment by wag110894** [comment]
Hello @virenderAttri,

You can accomplish this using the custom builder.

**Comment by virenderAttri** [comment]
@wag110894 , Can you explain this with some example

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
