### ISSUE TITLE
[BUG] Toggling "multiple values" on Number field breaks portal and cannot save changes

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#4115]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Browser: all I think

## Steps to Reproduce
1. Create a form
2. Drag a “Number” component onto the form
3. Enable “Multiple values”
4. Save the changes to the field
5. Edit the field
6. Disable “Multiple values”
7. Save the changes to the field
8. Edit the JSON of that number field and notice that defaultValue is `[ null ]` rather than `null`
9. Open the developer console
10. Refresh the page and see errors about `Uncaught (in promise) Error: The ‘value’ provided to Text Mask needs to be a string or a number. The value received was: [null]`

## Expected behavior
The default value of the Number field should be reverted to `null`

## Observed behavior
The default value remains `[ null ]` and actually throws many errors in the console ultimately preventing us from making any further edits to the form

## Example
N/A

## Notes on workaround
The forms we build display as Wizard. To move around pages we change display to Form so we can rearrange pages.

Due to this bug, any time we dragged around pages or made any changes to the form, it would not properly save.

The way I got the form out of this bad state was as follows:
1. Set "Display as" to "Wizard"
2. Go to the panel which has the bad field
3. Delete the bad field and save the form
4. Refresh the page
5. Add the field back with the correct default value
6. Save the form and refresh
7. Set "Display as" to Form and make my intended edits and go back to Wizard later

**Comment by ccontour** [comment]
Confirmed. In addition, using this workflow doesn't result in the portal UI identifying the form as being dirty / needing saving.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
