### ISSUE TITLE
[BUG] Validation error message is not displayed for custom ckeditor

### ISSUE THREAD

**Issue by ShintoSan** [formio/formio.js#4116]
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Development deployment
    - Version: 
- Formio.js version: 4.5.1
- Frontend framework: AngularJs
- Browser: Chrome/Firefox (All Browser)
- Browser version: 

## Issue
Validation error message is not displayed for custom **ckeditor**.
In console validation message can be seen but not displayed on error label.

## Expected behavior
Validation Error Message Should have been displayed on label.
 
## Observed behavior
Validation Error Message not displayed on label.

Screenshot -> https://snipboard.io/ETl2nC.jpg

## Custom Element JSON: -

```js
{
  "type": "editorCK",
  "key": "keyName",
  "label": "Body",
  "input": true,
  "customClass": "newcontainer",
  "clearOnHide": false,
  "validate": {
    "customMessage": "Summary is required",
    "required": true,
    "custom": "",
    "customPrivate": false,
    "strictDateValidation": false,
    "multiple": false,
    "unique": false
  },
  "tableView": false,
  "keyModified": true,
  "protected": false,
  "persistent": true,
  "id": "idsample"
}```

**Comment by wag110894** [comment]
@yrakessh, are you using version 4.5.1 of our formio.js? If so, we recommend upgrading.

**Comment by yrakessh** [comment]
Updated to formiojs@4.13.1 but still facing this issue of validation error message.
