### ISSUE TITLE
[BUG] On selecting and desecting multiple values checkbox for input field throwing an error

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#4126]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 4.11.5
- Formio.js version:4.11.5
- Frontend framework:angular-formio
- Browser:Firefox
- Browser version:78.7.1esr

## Steps to Reproduce
1. Drag number input field
2. Under data tab select multiple values and uncheck
3. Now you will see an error in console

## Expected behavior
Should not see errors and functionality should work like other components 

## Observed behavior
Seen error and after that nothing is working.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
![image](https://user-images.githubusercontent.com/7270651/121129471-a073a280-c84a-11eb-9591-f69f539adca3.png)

[https://codesandbox.io/s/formio-starter-ridtr?file=/src/app/app.component.ts](url)

For code or form JSON, please enclose in a code block:

```js
// your code here
```

Error Snippet:
![image](https://user-images.githubusercontent.com/7270651/121129621-d749b880-c84a-11eb-8512-9b09c9315f98.png)

**Comment by wag110894** [comment]
Hello @sriram275,
Is this issue still occuring? 

If so, can you provide a form embed so that we can take a look at it?

Thank you.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
