### ISSUE TITLE
[BUG] - Required field validations are triggered on form load in certain situations

### ISSUE THREAD

**Issue by base64000** [formio/formio.js#4128]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ x] Local deployment
    - Version: 
- Formio.js version: 4.13.0 - 4.14.0-rc7
- Frontend framework: Sandbox
- Browser: Chrome, Edge
- Browser version:

## Steps to Reproduce
1. Open a new incognito window and go to the sandbox
2. Load sandbox with id 60bfaa9f74f4034f9bf03456
3. The form contains several fields that are marked as required. They all immediately show as being in error state even though the user has not attempted to submit the form

Then load sandbox with id 60bfaa76cf821262f992bb3c
This form behaves correctly. The only difference between this form and the form that behaves incorrectly is the presence of a Number field. 

We have not narrowed down all the exact conditions in which the erroneous behavior occurs but all forms that do not have a visible number field on them seem to exhibit the erroneous behavior.

## Expected behavior
Required fields should not show as being in an error state immediately after the form is loaded, only after an action that causes form validation to take place, such as trying to submit the form, or programmatically invoking form validation, or the user clearing a required field

## Observed behavior
All required fields are immediately showing as being in an error state after the form is loaded in certain situations

## Example
See steps to reproduce

## Other
This behavior is very disconcerting to our users. When an empty form with a lot of required fields is loaded they are immediately presented with a wall of red validation errors before they have had to fill out the form.

**Comment by wag110894** [comment]
Ticket has been created for this issue.
FIO-3287.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
