### ISSUE TITLE
Custom Message when the submit button is clicked without entering required fields ?

### ISSUE THREAD

**Issue by paulmartinjoy** [formio/formio.js#4132]
I would like to change the error message that is displayed in situations where we click the submit button, but some compulsory fields are empty. The message that I receive by default is "Please check the form and correct all errors before submitting the form". I want to use instead a custom message. Is there a way to achieve this ?

**Comment by Brokkoly** [comment]
You can override the error message by adding to the options when creating a form:
```
var options = {
   i18n: {
            en: {
                  submitError: 'My custom submission error',
            }
   }
}
```
And then later you're probably doing a call to Formio.createForm(Formio.createForm(document.getElementById(settings.id), formDefinitionUrl, options) which is where the options object you need is found.

Here's a list of the strings you can override this way: https://github.com/formio/formio.js/blob/master/src/translations/en.js

**Comment by paulmartinjoy** [comment]
Thanks for the reply. I am really new to formio and angular. I hope you won't mind me asking implemnt the form differently. I use the following code in ts: 
const bookingFormConfig: FormioForm = {
				display: 'form',
				components: [
					......,
					......,
					{
						type: 'button',
						label: 'Submit',
						key: 'submit',
						disableOnInvalid: false,
						input: true,
						tableView: false
					}
				]
			};  and in the html I use :  <formio [form]="bookingFormConfig" (submit)="onSubmit($event)">
      </formio>. In the formio config where should I use the options.

**Comment by paulmartinjoy** [comment]
Thanks for the reply. It worked.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
