### ISSUE TITLE
[BUG] select list values re-written

### ISSUE THREAD

**Issue by jalama** [formio/formio.js#4137]
## Environment
Please provide as many details as you can: 

- Hosting type
  - [x] Form.io
  - [ x] Local deployment
    - Version: 
- Formio.js version: 4.13.2
- Frontend framework: Angular (@formio/angular 5.1.1
- Browser: FF, Chrome, Edge
- Browser version:

## Steps to Reproduce
The values of select lists are being re-written to match the label (in camelCase) when I click on the data tab of a select list

In a new sandbox, I add a select component with 2 possible labels/values (test/1, test2/2) and a storage type of number. After saving I see this reflected in the form JSON..
![image](https://user-images.githubusercontent.com/640153/121533787-9da1ba80-c9ce-11eb-9e4b-f982f0324c00.png)

```
      "data": {
        "values": [
          {
            "label": "test",
            "value": "1"
          },
          {
            "label": "test2",
            "value": "2"
          }
        ]
      },
      "dataType": "number",
```

When I edit the form and click on the data tab, without actually touching any fields on the tab, the values are converted to text matching the label ( (test/test, test2/test2)

![image](https://user-images.githubusercontent.com/640153/121533913-bc07b600-c9ce-11eb-8830-b60b3baa81a2.png)

After clicking save on the select component I see the new value reflected in the form JSON
```
      "data": {
        "values": [
          {
            "label": "test",
            "value": "test"
          },
          {
            "label": "test2",
            "value": "test2"
          }
        ]
      },
      "dataType": "number",
```

https://user-images.githubusercontent.com/640153/121537240-bfe90780-c9d1-11eb-973c-ab2ea6826b36.mp4

## Expected behavior
Don't touch the values in the select list :)

**Comment by jalama** [comment]
Also, we are not seeing this in formiojs v4.13.0, @formio/angular v5.1.0

**Comment by wag110894** [comment]
Hello @jalama, we are aware of this issue and have assigned to a developer. For reference, the ticket number is FIO-3254. 

We will let you know once this has been resolved.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution! The ticket is in done status
