### ISSUE TITLE
[BUG] undefined is not an object (evaluating 'i.type')

### ISSUE THREAD

**Issue by SalTor** [formio/formio.js#4154]
## Environment
Please provide as many details as you can:

It seems that sometimes input is not defined when this line is run:
https://github.com/formio/formio.js/blob/4acec764d17e7b51027923048002d49967851ad1/src/components/_classes/component/Component.js#L1613

- Hosting type
  - [x] Form.io
- Formio.js version: 4.13.2
- Frontend framework: none
- Browser: n/a
- Browser version: n/a

## Steps to Reproduce
We customize the "multi" view with textfields and haven't been able to reproduce this error. It has only happened once according to our alerting and doesn't seem to impede user experience. Moving this line one line down should prevent the error from ever occurring and doing the calculation again in the else block.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
