### ISSUE TITLE
[BUG] Edit Grid does not display numbers, checkbox, selects etc

### ISSUE THREAD

**Issue by srinisubramanian** [formio/formio.js#4161]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: As deployed in formio cloud
- Frontend framework:
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create a form and add an edit grid
2. Add Text field, number, checkbox etc to the edit grid
3. Use the form
4. Once add row is clicked and values set, only text field is displayed.  Number, checkbox etc are all not displayed.
5. Needs a fix urgently
6. You can check an example form here: https://pro.formview.io/#/dvmhhnoozovucxc/testeditgrid?header=1&reset=1

## Expected behavior
All fields need to be displayed
## Observed behavior
Only text field is shown
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Text is displayed in first grid, numbers etc in second grid are not displayed
![image](https://user-images.githubusercontent.com/8343179/123072467-3276d000-d433-11eb-9ad9-10a823d12384.png)

Numbers etc are present when you click Edit

![image](https://user-images.githubusercontent.com/8343179/123072594-4de1db00-d433-11eb-8965-11bc67dd3f5b.png)

@travist  Request quick resolution as this is a kind of a blocker for customers.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
Hello @srinisubramanian,
Can you provide a form embed so we can investigate?

**Comment by srinisubramanian** [comment]
@wag110894  I had added a public URL .. but below is the embed code I copied over from your portal

`<script src="https://unpkg.com/formiojs@latest/dist/formio.embed.js?src=https://dvmhhnoozovucxc.form.io/testeditgrid"></script>
`

**Comment by airarrazaval** [comment]
@srinisubramanian the checkbox and number components in your form definition has the option `tableView` set to `false`.  If you check the default EditGrid header and row templates are the following:

### Header Template
```html

      <tr>
        {% util.eachComponent(components, function(component) { %}
          {% if (!component.hasOwnProperty('tableView') || component.tableView) { %}
            <td class="editgrid-table-column">{{ component.label }}</td>
          {% } %}
        {% }) %}
        {% if (!instance.options.readOnly && !instance.disabled) { %}
          <td class="editgrid-table-column">Actions</td>
        {% } %}
      </tr>
    
```

### Row Template
```html

      {% util.eachComponent(components, function(component) { %}
          {% if (!component.hasOwnProperty('tableView') || component.tableView) { %}
            <td class="editgrid-table-column">
              {{ getView(component, row[component.key]) }}
            </td>
          {% } %}
        {% }) %}
        {% if (!instance.options.readOnly && !instance.disabled) { %}
          <td class="editgrid-table-column">
            <div class="btn-group">
              <button class="btn btn-default btn-light btn-sm editRow" aria-label="{{ t('Edit row') }}"><i class="{{ iconClass('edit') }}"></i></button>
              {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}
              <button class="btn btn-danger btn-sm removeRow" aria-label="{{ t('Remove row') }}"><i class="{{ iconClass('trash') }}"></i></button>
              {% } %}
            </div>
          </td>
        {% } %}
    
```

As you can see, the default templates hide any component that has `tableView` set to `false`.  You may change this behavior by editting the EditGrid templates as such:

### Header Template
```html

      <tr>
        {% util.eachComponent(components, function(component) { %}
          <td class="editgrid-table-column">{{ component.label }}</td>
        {% }) %}
        {% if (!instance.options.readOnly && !instance.disabled) { %}
          <td class="editgrid-table-column">Actions</td>
        {% } %}
      </tr>
    
```

### Row Template
```html

      {% util.eachComponent(components, function(component) { %}
          <td class="editgrid-table-column">
            {{ getView(component, row[component.key]) }}
          </td>
        {% }) %}
        {% if (!instance.options.readOnly && !instance.disabled) { %}
          <td class="editgrid-table-column">
            <div class="btn-group">
              <button class="btn btn-default btn-light btn-sm editRow" aria-label="{{ t('Edit row') }}"><i class="{{ iconClass('edit') }}"></i></button>
              {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}
              <button class="btn btn-danger btn-sm removeRow" aria-label="{{ t('Remove row') }}"><i class="{{ iconClass('trash') }}"></i></button>
              {% } %}
            </div>
          </td>
        {% } %}
    
```

**Comment by srinisubramanian** [comment]
@airarrazaval  Thanks for the hint.  The template was already set to what you mention but it was still not displaying.  I then enabled "Table View" and it started displaying.  Looks like the template is somehow being overridden by the default?

**Comment by srinisubramanian** [comment]
@airarrazaval  I can confirm that using the template you provide or by setting tableView to true it is displayed.
