### ISSUE TITLE
Make it easier to create custom components by not hardcoding template names in render() - functions of components

### ISSUE THREAD

**Issue by MasterMart** [formio/formio.js#4166]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.2.17
- Frontend framework: Angular
- Browser: Chrome

## Steps to Reproduce
1. Open for instance checkbox.js
2. Check the 'render' method

## Expected behavior
I would like render() functions in components to render not a template with a hardcoded template name, but a template with a template name returned by a function so that I can override this function in my custom implementation. 

## Observed behavior
When creating custom components off of existing components with a few alterations (for instance to be WCAG compliant, or because I need a slightly different HTML structure), I am forced to implement some hack because the render() method hardcodes the template name. 
I sometimes need a whole new html template for a custom component because not all components support adding all html attributes that I need. Also sometimes I want to make small changes in the html structure. 

## Example
```js
super.render(this.renderTemplate('checkbox', {
}

->

super.render(this.renderTemplate(this.getTemplateName(), {
}
```

**Comment by airarrazaval** [comment]
@MasterMart have you tried looking at the documentation for building [Custom Components](https://formio.github.io/formio.js/app/examples/customcomponent.html)?

If you want to make small changes (such as adding or removing attributes), then I would recommend you to execute a custom javascript.  There are many instances where you can achieve this (on form render event, on component redraw event, etc).

Using custom components you just need to define your render function and you can also define your own custom templates.  You could do something like this:

```js
import { Components } from 'formiojs';

export default class CustomCheckbox extends Components.components.checkbox {
  render() {
    return super.render(this.renderTemplate('custom-checkbox', {
      input: this.inputInfo,
      checked: this.checked,
      tooltip: this.interpolate(this.t(this.component.tooltip) || '', { _userInput: true }).replace(/(?:\r\n|\r|\n)/g, '<br />')
    }));
  }
}
```

then, when building your form you could do:

```js
import { Formio } from 'formiojs';

import CustomCheckbox from '/path/to/component';
import CustomCheckboxTemplate from '/path/to/template';

Formio.Templates.current['custom-checkbox'] = CustomCheckboxTemplate;
Formio.Components.setComponent('custom-checkbox', CustomCheckbox);
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
