### ISSUE TITLE
[BUG] / Change request - Reduce the quality of images taken from the web view camera/gallery and fix their orientation

### ISSUE THREAD

**Issue by oneserve** [formio/formio.js#4171]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework: Angular
- Browser: Cordova
- Browser version: 

## Steps to Reproduce
1. Add file component to survey
2. Fill out survey on a phone and take a photo

## Expected behaviour
Small file size of image, allowing multiple images to be used on the form (without using up too much hardware resource of the phone), images should be orientated the same way that they were taken

## Observed behaviour
Images taken with the camera or chosen from the gallery are not compressed, causing issues when adding 3+ photos to the form (especially when using the offline plugin). On some devices, images are also rotated in different ways than they were taken (portrait becomes landscape and vice versa)

I'll create a PR against this issue to change the args passed into the camera and gallery

**Comment by oneserve** [comment]
Ah I don't think I have permission to create a branch and subsequent PR :)

**Comment by airarrazaval** [comment]
@oneserve you can fork the repo, set the official repo as upstream, create your own branch in your forked repo and then submit the PR to upstream.

**Comment by airarrazaval** [comment]
Another thing, you could just hook on to the change event of the component and do the preprocessing of the image yourself.  Image processing can have quite an impact on the client (specially older devices).

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
