### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by murugaratham** [formio/formio.js#4173]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.13.2
- Frontend framework: React
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Install and configure 
2. Turn off internet connectivity
3. Load Formbuilder

## Expected behavior
Components should work off-line, or at least give options to overwrite internet-only resources
## Observed behavior
FormBuilder requires 3rd party online resources like`cdn.form.io/flatpickr/flatpickr.min.js` & bootstrap etc, 
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:
```js
new Formio.FormBuilder(builderRef.current, {...}, {
      builder: {
        premium: false,
      },
```
https://github.com/formio/formio.js/blob/16f9e796d3e739876090bd9d9dd47a90cd274c00/src/widgets/CalendarWidget.js#L23

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
