### ISSUE TITLE
Vulnerability on json-logic-js@2.0.1 dependency of formiojs

### ISSUE THREAD

**Issue by cuneytdev** [formio/formio.js#4181]
Hello, when my project is scanned via fortify software security center, it detects vulnerability like the following dependency json-logic-js of formiojs;

**Vulnerability Description : The product does not validate or incorrectly validates input that can affect the control flow or data flow of a program.**

json-logic-js version: **2.0.1**
formio version: **4.12.7**
@formio/angular version: **5.1.1**
frameweork: **Angular**

Thanks.

**Comment by cmcortez** [comment]
Hello,

Thank you for taking the time to report this to us. We are unable to identify any listed vulnerabilities against that package. Are you able to provide a link to the CVE? Please note this is also a 100% optional feature. There is no significant loss of functionality from avoiding its usage.

**Comment by cuneytdalan** [comment]
Sorry for cannot sharing the link.  This is scanned in our local Fortify Security Center servers but here is the description.

![json-logic-js_vulnerability](https://user-images.githubusercontent.com/18741605/124655035-fc603400-dea7-11eb-96bc-3a734127f915.jpg)

Thanks for your attention.

**Comment by airarrazaval** [comment]
@cmcortez here is the npm audit (although it is triggered from the [formio/formio-service](/formio/formio-service) package which uses formiojs@2.32.2)

![image](https://user-images.githubusercontent.com/9391489/125315005-b6222f00-e304-11eb-8d4e-704688e5b427.png)

On a clean install this is the only warnings coming from the latest formiojs package:

![image](https://user-images.githubusercontent.com/9391489/125316450-22516280-e306-11eb-9631-d2dbd29e37be.png)

Directly installing json-logic-js@2.0.1 doe not throw an npm alert neither:

![image](https://user-images.githubusercontent.com/9391489/125316937-97bd3300-e306-11eb-8b86-97eff5293f5c.png)
 

@cuneytdalan have you checked if you are using an older version of formio.js (maybe you have an outdated package-lock.json file referencing to an older json-logic-js package).

For more information check https://snyk.io/advisor/npm-package/json-logic-js

**Comment by cuneytdalan** [comment]
Hello, @airarrazaval,

Currently using;

    formiojs: 4.13.3
    @formio/angular: 5.1.1
    json-logic-js: 2.0.1

Having the vulnerabiliy on comment: https://github.com/formio/formio.js/issues/4181#issuecomment-875020749

Also i think the 3rd party library of json-logic-js is not being maintained enough because i opened this issue there with the link https://github.com/jwadhams/json-logic-js/issues/101#issue-933561483 and they haven't answered me yet. So maybe it would be better the replace json-logic-js lib with another library. 

Thanks,
Cüneyt.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
