### ISSUE TITLE
How to Change the CKEditor configuration?

### ISSUE THREAD

**Issue by lane711** [formio/formio.js#4183]
I want to enable the source option in a ckeditor text area 

what value should be placed in the "Editor Settings" value?

I have tried some test values, but they don't seem to take effect:
https://www.dropbox.com/s/u9zplnrpkmaee0w/Screen%20Shot%202021-07-02%20at%201.29.45%20PM.png?dl=0

**Comment by rrg92** [comment]
someone?

**Comment by brendanbond** [comment]
The "Editor Settings" value takes JSON configuration, in this case [CKEditor's ClassicEditor configuration object](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html). For example, try putting this in the "Editor Settings:"

```
{
  "rows": 3,
  "base64Upload": true,
  "mediaEmbed": {
    "previewsInData": true
  },
  "toolbar": [
    "bold",
    "italic",
    "|",
    "undo",
    "redo"
  ]
}
```
