### ISSUE TITLE
[BUG] Tooltip interpolation breaks when using double quotes

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#4190]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: `4.x`
- Frontend framework: `any`
- Browser: `Google Chrome`
- Browser version: `91.0.4472.124 (Official Build) (64-bit)`

## Steps to Reproduce
1. Create a new form
2. Add any component with tooltip
3. Includes at least one double quote (`"`) character in the tooltip content
4. Render the form
5. The tooltip content will break starting from the position of the double quote character

## Expected behavior
The tooltip should escape and handle double quotes properly and they should render correctly inside the tooltip.

## Observed behavior
The tooltip interpolation breaks when it encounters a double quote (it does not render any content after the double quote).  If more than 1 double quote is present, then the content between double quotes is not rendered.  It could be caused by a sanitization function in tooltip.js or in another utility method.

## Considerations
**tooltip.js** [has been deprecated](https://www.npmjs.com/package/tooltip.js) and should be replaced with [tippy.js](https://github.com/atomiks/tippyjs) 

## Example

Live example here: https://jsfiddle.net/airarrazaval/89y5dkhb

```js
const el = document.getelementById('formio');
const form = {
  type: 'textfield',
  label: 'Textfield',
  tooltip: 'hello "world"!'
  }]
}
Formio.createForm(el, form);
```

**Comment by airarrazaval** [comment]
Escaping the double quotes also breaks the tooltip.


```js
const el = document.getelementById('formio');
const form = {
  type: "textfield",
  label: "Textfield",
  tooltip: "hello \"world\"!"
  }]
}
Formio.createForm(el, form);
```

**Comment by airarrazaval** [comment]
The issue is caused by the template engine not escaping double quotes and thus creating invalid HTML.

https://jsfiddle.net/airarrazaval/15bc6e48/

![image](https://user-images.githubusercontent.com/9391489/126016669-6b8058b9-d8d5-48f5-804b-8c8b2a979311.png)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
