### ISSUE TITLE
how to hide <formio-loader> element on form render

### ISSUE THREAD

**Issue by kiranpwr1260** [formio/formio.js#4198]
I want to hide <formio-loader> element along its parent <div class="ng-star-inserted">

**Comment by wag110894** [comment]
Can you provide a form as well as the element that you want to hide?

**Comment by airarrazaval** [comment]
@kiranpwr1260 If you want to "force" hide the loader you can do it using CSS

```css
.formio-loader {
  display: none;
}
```

Please be aware that the form loader is set when building the form and it is replaced once the form is ready.

https://github.com/formio/formio.js/blob/4e19e2b3cbd0885d4d38c68176105d1a337ca274/src/Form.js#L247-L269

If the loader does not disappear that means that there was a problem loading the form (the form endpoint does not exists, the server is unreachable or the request has timed out.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
