### ISSUE TITLE
Module identifier warning when building with Webpack

### ISSUE THREAD

**Issue by mdurling** [formio/formio.js#42]
WARNING in ./~/formiojs/src/Formio.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Git\proximus\node_modules\formiojs\src\Formio.js
    Used by 1 module(s), i. e.
    C:\Git\proximus\node_modules\formiojs\src\providers\storage\url.js
* C:\Git\proximus\node_modules\formiojs\src\formio.js
    Used by 7 module(s), i. e.
    C:\Git\proximus\node_modules\react-formio\lib\components\Formio.js
webpack: bundle is now VALID.

**Comment by travist** [comment]
This should now be resolved in version 1.5.3. Thanks!
