### ISSUE TITLE
how can i habilite value table in custom radio component?

### ISSUE THREAD

**Issue by santiagoO28** [formio/formio.js#4200]
Hi, I am trying to build a custom radio component in formio.js but I cannot enable this option for values, can someone help me please?

  - [x]    @@@Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.13.4
- Frontend framework: Angular

I´m creating my radio custom with modules, like this picture:
![Capturaformio](https://user-images.githubusercontent.com/87341097/125360000-c9e38a80-e330-11eb-987a-e372634950cd.PNG)

## Expected behavior
![CapturaTableValues](https://user-images.githubusercontent.com/87341097/125360363-6017b080-e331-11eb-9dd0-b38f3744d321.PNG)

## Observed behavior
![CapturaNoTable](https://user-images.githubusercontent.com/87341097/125360515-9a814d80-e331-11eb-9004-931c03fcd593.PNG)

**Comment by dcmadushani** [comment]
Hello @santiagoO28, did you update formio.js project to add you custom component

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
