### ISSUE TITLE
[BUG] CalendarWidget altInput has multiple 'is-invalid' classes (fix available)

### ISSUE THREAD

**Issue by AlexanderKochIBK** [formio/formio.js#4208]
We run into an issue where the altInput of the calendar widget in a DateTime-Component had multiple 'is-invalid' classes.

So if the Custom-Validation of the element is not true, the element gets the error-message and multiple 'is-invalid' classes (do not know why). Everything seems fine.
But if changing values so the validation is returning true after, just one 'is-invalid' class is removed from the input.
The error message disappears, but the input still has the 'invalid'-Look through CSS-classes.

Simple fix was changing the following inside the CalendarWidget.js (should not disturb at all, it is even more reliable):

    setErrorClasses(hasErrors) {
        if (!this.input) {
            return;
        }

        if (hasErrors) {
             this.input.className = "".concat(this.input.className, " is-invalid");
        } else {
            //this.input.className = this.input.className.replace('is-invalid', '');
            this.input.className = this.input.className.replaceAll('is-invalid', '');
        }
    }

Maybe already fixed with [this pr](https://github.com/formio/formio.js/pull/4131), so 4.14.0 should deal with that as well.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
