### ISSUE TITLE
Can we use formioJS Javascript SDK to create formbuilder 

### ISSUE THREAD

**Issue by vivek-Havalad** [formio/formio.js#4209]
Hi, I have gone through the docs are no examples or a solution provided using JavaScript SDK formio to create a form-builder is there any way to implement form-builder using Fomiojs imports without using CDN's.

**Comment by airarrazaval** [comment]
Yes you can. In fact it is the first example in the readme.

```html

<html>
  <head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
    <script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.builder(document.getElementById('builder'), {}, {});
      };
    </script>
  </head>
  <body>
    <div id='builder'></div>
  </body>
</html>
```

**Comment by vivek-Havalad** [comment]
Hi @airarrazaval 
Actually, i don't want to use CDN's or the links basically I am trying to use the formio in stencilJS so I require a pure **_import_** structure from FormIO SDK

**Comment by aminmc** [comment]
https://www.npmjs.com/package/formiojs has instructions on how to install via npm.

**Comment by vivek-Havalad** [comment]
Yea I have tried it too but of no use, it nowhere defines how to use the formJS javascript SDK for **FormBuilder**.

**Comment by aminmc** [comment]
It's in the content for the link I pasted. One example is for form rendering and the other is for form building. Also there numerous examples within the formio GitHub repository. There is a react example and vue.

**Comment by vivek-Havalad** [comment]
Yea I have worked with formio/angular and it Is working fine but the same FormBuilder implementation i want build using StencilJS.

**Comment by airarrazaval** [comment]
@vivek-Havalad it is the same as with the CDN as with the node package:

```
npm install --save formiojs
```

Then you can do the following:

```js
import { Formio } from 'formiojs';

// The HTML element you wish to append the FormBuilder
const element = document.getElementById('builder');
// The default form schema to be rendered in the builder
const schema= {
  display: 'form',
  components: []
}
// The builder options (optional)
const options = {
  [your options here]
}
Formio.builder(element, schema, options);
```

Remember that you can use the framework specific version of formiojs as well:

* ReactJS: https://github.com/formio/react
* VueJS: https://github.com/formio/vue-formio
* Angula: https://github.com/formio/angular

**Comment by vivek-Havalad** [comment]
Hi, @airarrazaval I have tried that too and you can see https://github.com/formio/formio.js/blob/master/types/formio.d.ts that the SDK nowhere emits the **builder** function with { Formio } export.

**Comment by airarrazaval** [comment]
@vivek-Havalad There are a couple of methods that are not yet included for typescript.  I leave below a couple of static methods defined for Formio class that may not be defined for typescript.

You can see a working example here:

https://codesandbox.io/s/crazy-water-fnzle?file=/src/index.js

Regarding some missing static methods for the Formio class:

https://github.com/formio/formio.js/blob/a56cc08744ece4f8c1e443c01a53d07475086192/src/Form.js#L295-L311

https://github.com/formio/formio.js/blob/a56cc08744ece4f8c1e443c01a53d07475086192/src/FormBuilder.js#L28-L41

https://github.com/formio/formio.js/blob/a56cc08744ece4f8c1e443c01a53d07475086192/src/formio.form.js#L20-L42

https://github.com/formio/formio.js/blob/a56cc08744ece4f8c1e443c01a53d07475086192/src/formio.form.js#L47-L131

https://github.com/formio/formio.js/blob/a56cc08744ece4f8c1e443c01a53d07475086192/src/Formio.js#L1554-L1575

**Comment by vivek-Havalad** [comment]
Hi @airarrazaval This was really helpful thank you for the support.
