### ISSUE TITLE
[BUG] Components inside layout components create elements with non-unique id

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#4213]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: `>= 4.12.0-rc.1`
- Frontend framework: `any`
- Browser: `any`
- Browser version: `any`

## Steps to Reproduce
1. Create a form with a Data Grid
2. Insert a Columns component inside the Data Grid
3. Insert any input component inside the Columns component
4. Render the form
5. Add a second row

## Expected behavior
All components should be created with a unique HTML id.

## Observed behavior
Components inside a layout component (which in turn is inside a Data Grid, Edit Grid, etc) retain their unique id and are not updated with the parent Nested Component's row index as it should.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/9391489/125981584-d5fe6b56-2f3b-492a-80e8-a4f3871d0440.gif)

This causes the browser to trigger a warning for detecting non-unique HTML ids.

The bug was introduced in `formiojs@4.12.0-rc.1` and is still present.

## Example

https://jsfiddle.net/airarrazaval/b10pda43/

**Comment by airarrazaval** [comment]
@wag110894  

Related to issue https://github.com/formio/formio.js/issues/3973

**Comment by airarrazaval** [comment]
Bug introduced in PR https://github.com/formio/formio.js/pull/3076. Possible solution would require layout components to check if they are inside a row, and if so, pass on that to their child components so they can build up a unique id.

**Comment by airarrazaval** [comment]
Created PR https://github.com/formio/formio.js/pull/4214.

The issue was caused by NestedComponents not making shallow copies of its components.  This caused the NestedComponent components to overwrite their component id when the NestedComponent was rendered inside a NestedArrayComponent (eg: TextfieldComponent inside a ColumnsComponent inside a DataGridComponent).

**Comment by jtamm-red** [comment]
I try fix it.

I made my PR: https://github.com/formio/formio.js/pull/4281

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
