### ISSUE TITLE
FileService URL storage is inconsistent [BUG] 

### ISSUE THREAD

**Issue by nathanieltagg** [formio/formio.js#4218]
When using a custom URL upload service, the provider/storage/url.js class massages the returned URL in unexpected ways.

## Expected behavior

The user uploads a file. The component is configured to use the route '/upload' to save the file. The backend returns that the file is saved, for example, with the url
  /files/thing.png
That is, my backend will serve the file on https://myserver.com/files/thing.png

## Observed behavior

The url.js script, however, massages this to 
  /upload/files/thing.png
and stores it in the saved form.

I see that the script is even worse (src/providers/storage/url.js):
```
          // If they provide relative url, then prepend the url.
          if (respUrl && respUrl[0] === '/') {
            respUrl = `${url}${respUrl}`;
          }
```
I'm not sure why the author thought that starting with a slash was a RELATIVE address. It could easily be an absolute address without protocol, like //storage.com/file/thing.png, or as in my case an absolute address without a hostname, like /file/thing.png.

## Remedy
In fact, I believe that the above script should either look for NO internal slashes, or addresses starting with a '.' for relative addresses. 

As it stands, there is no correct way of making it do the right thing without returning a full response, including protocol, so that it starts with ('h') and doesn't hit this code.  I can see many issues with this.

One solution would be to create my own FileService subclass, but that seems like overkill since this one does 99% of what I need.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
