### ISSUE TITLE
[BUG] Blur event not dispatching on Quill WYSYWYG editor

### ISSUE THREAD

**Issue by waterbuckit** [formio/formio.js#4219]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
- Formio.js version: 4.13.4
- Frontend framework:
- Browser: Chromium 
- Browser version: Version 91.0.4472.114 (Official Build) Arch Linux (64-bit)

## Steps to Reproduce
1. Include a text area with editor Quill (I don't think it works with the other editors either besides basic HTML textarea)
2. Focus element
3. Lose element focus
4. No blur event fired.

## Expected behavior
Blur event to be dispatched

## Observed behavior
No blur event dispatched 

```js
//... typical code for setting up a form
form.on('blur', (e) => {
    console.log(e);
});
//...
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
