### ISSUE TITLE
Single-file file fields have a trailing file input field that interferes with pointer events

### ISSUE THREAD

**Issue by colons** [formio/formio.js#422]
There's a file field that lives, hidden, alongside the 'Drop files to attach' target. It does not disappear when the drop target does, which means that users are likely to accidentally click it when aiming for, for example, the 'next' button that might be immediately underneath it. This leads to a file open dialog box appearing, which can be pretty disorientating.

Setting `display: none` on this element solves this problem.

**Comment by jhen1422** [comment]
Closing - outdated issue
