### ISSUE TITLE
Disable only few form fields and keep rest fields editable

### ISSUE THREAD

**Issue by hemant-joshi** [formio/formio.js#4220]
## Environment
Hi Team, I am trying to build a form in formio.js and i want to disable **only few form fields** and **keep other fields editable**. Currently i can disable full form at once and can not do it for particular field . Can someone help me please?

Please provide as many details as you can:
 
 * Hosting type   
   * [ ]  Form.io
   * [x]  Local deployment
     * Version:
 * Formio.js version: 4.12.4
 * Frontend framework: React
 * Browser:
 * Browser version:

**Comment by sureshyadaw437** [comment]
I dont remember the exact syntax or keyword.   But we can pass set of components array while calling create form.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
