### ISSUE TITLE
[QUESTION] Wizard (panels/pages) with global panel shown on every page

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#4221]
## Question

Sorry, my mistake.. I opened a bug. Please change label to: **question**

Is it somehow possible to implement a Wizard which shows a component (eg. panel) on every page (position: fixed)?
I would like to show some kind of summary (with calculated components) on every page.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
