### ISSUE TITLE
[BUG] EditGrid with "Display as modal" do not work in read-only

### ISSUE THREAD

**Issue by AlexanderKochIBK** [formio/formio.js#4222]
Hello,

we are using an EditGrid-Component with "Display as modal" activated (in a wizard-form).

As long as we are not in read-only mode on the renderer, everything works fine.

But enabling read-only leads to weird behaviour on the EditGrid on page 3 of the wizard.
We enabled the edit-Button in the template for each row even in read-only, so the user can see the data behind.

First time visiting page 3, the EditGrid is drawn as expected, each row with a edit-button to show the data (no inline-editing).
But if you go one page back and one pack forward (visit page 3 for the 2nd time/3rd time/..), inline-editing is activated and the data is not displayed in a modal anymore.

I logged something in the templates and it seems like the templates are not called anymore after the first time getting rendered.

Feels like a bug for me. Is this expected behaviour?

**Comment by AlexanderKochIBK** [comment]
Seems like the state of the editRow is not in the correct state after closing the dialogue. It is still on "viewing", but it should be on "saved", no? Got that from editing the isOpen-method from EditGrid-Component.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
