### ISSUE TITLE
[Enhancement] Add ability to add DOMPurify profiles (svg/mathml)

### ISSUE THREAD

**Issue by Rolf-MP** [formio/formio.js#4224]
## Environment
Local deployment
Formio.js version: latest
Frontend framework: angular
Browser: any
Browser version: any

## Desired behavior
Be able to add the DOMPurifyer svg/mathMl USE_PROFILES config through the options json.

See: https://github.com/cure53/DOMPurify#can-i-configure-dompurify

```
// allow all safe HTML elements but neither SVG nor MathML
// note that the USE_PROFILES setting will override the ALLOWED_TAGS setting
// so don't use them together
var clean = DOMPurify.sanitize(dirty, {USE_PROFILES: {html: true}});

// allow all safe SVG elements and SVG Filters, no HTML or MathML
var clean = DOMPurify.sanitize(dirty, {USE_PROFILES: {svg: true, svgFilters: true}});

// allow all safe MathML elements and SVG, but no SVG Filters
var clean = DOMPurify.sanitize(dirty, {USE_PROFILES: {mathMl: true, svg: true}});

```

## Observed behavior
Currently I can allow e.g. svg but need to add and allow all svg/mathMl tags and attributes "manually" (lots of bookkeeping) whilst DOMPurify has specific profiles for this. An very incomplete sample of such sanitizeConfig for svg below:

`{
  "sanitizeConfig": {
    "allowedTags": [
      "svg",
      "title",
      "path",
      "circle",
      "rect"
    ],
    "addTags": [
      "svg",
      "title",
      "path",
      "circle",
      "rect"
    ],
    "allowedAttr": [
      "d",
      "transform",
      "fill",
      "viewBox",
      "xmlns",
      "cx",
      "cy",
      "r",
      "stroke",
      "stroke-width",
      "visibility"
    ],
    "addAttr": [
      "d",
      "transform",
      "fill",
      "viewBox",
      "xmlns",
      "cx",
      "cy",
      "r",
      "stroke",
      "stroke-width",
      "visibility"
    ]
  }
}`

## Example
From what I can see from the source it would be a matter of inserting the code below around line 1249 in https://github.com/formio/formio.js/blob/master/src/utils/utils.js:

```js
  // Use profiles
  if (options.sanitizeConfig && options.sanitizeConfig.useProfiles) {
    Object.keys(options.sanitizeConfig.useProfiles).forEach(key => {
      sanitizeOptions.USE_PROFILES[key] = options.sanitizeConfig.useProfiles[key];
    });
  }
```

In the options config we could then have `useProfiles` next to addTags, allowedTags, addAttr, allowedAttr:
```json
{
  "sanitizeConfig": {
    "useProfiles": {
      "mathMl": true,
      "svg": true
    }
  }
}
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
