### ISSUE TITLE
[QUESTION] DataGrid with minLength == 0

### ISSUE THREAD

**Issue by harthorst** [formio/formio.js#4230]
Hi. I'd like to add a data grid with minLength=0. 

The expected behavior is that there are no data rows created by default and without any rows the validation throws no errors.

The actual behavior is:
- a row is created by default
- I can't submit an empty data grid

How can I configure the DataGrid to get the desired behavior?

**Comment by airarrazaval** [comment]
You can actually do this by setting the `initEmpty` property to `true`:

![image](https://user-images.githubusercontent.com/9391489/127043459-5b9573f6-16a7-49b5-aab0-15c3a45cb669.png)

This will make the Data Grid to be rendered with no rows.

![image](https://user-images.githubusercontent.com/9391489/127043566-c520006b-80f9-497b-9e35-cf1b44162348.png)

There is no need for you to set `minLength` to `0`.

**Comment by harthorst** [comment]
@airarrazaval many thanks. I guess I have to enhance the free editor to enable this checkbox?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
