### ISSUE TITLE
Dropdown values getting auto-selected with the last value in the data grid

### ISSUE THREAD

**Issue by nithinnani07** [formio/formio.js#4231]
![image](https://user-images.githubusercontent.com/34380304/126978295-af29f12f-b22c-4874-a04d-c27bc316761d.png)

I want to either make it empty by default or through some advanced logic.

But I can't set value from advanced logic. 

Kindly help

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
