### ISSUE TITLE
Question - How to make an input text field masked with only numbers

### ISSUE THREAD

**Issue by opcodewriter** [formio/formio.js#4243]
How I can make the Text Field component have a mask of only numbers? In other words, I want the user be able to type only numbers.
AFAIK, the mask property needs an exact mask using the format used by the jquery.inputmask.

**Comment by wag110894** [comment]
You can use the Number component or use the input mask settings inside of the textfield.

**Comment by opcodewriter** [comment]
@wag110894 I cannot use the Number component because the value in the data is a **number**, and in my case I need it as a **string**.

Also, I cannot use the input mask for the reasons I already explained: As far as I'm aware, the way the mask works is it forces the value of a certain length. I cannot set a mask which allows the value to be of **numeric characters** **and** of **any length** 

Masking a Text field to only allow numeric characters is a pretty basic and common scenario if you ask me.

**Comment by opcodewriter** [comment]
I know I can use a regular expression in the Validation tab, but that's validation, it's not masking. Ideally, I would like to be able to restrict the user to only write numeric characters.

**Comment by opcodewriter** [comment]
@MaksimFalei If you try it, you'll see it's not the ideal experience for the user, but at least it works. Thank you so much!
