### ISSUE TITLE
Hiding fields on inherited components

### ISSUE THREAD

**Issue by DanDvoracek** [formio/formio.js#4248]
Hi there,

I'm posting an issue here today as I'm trying to hide fields on inherited components, but without success so far.

I get the basics I think. I the logic about hiding/showing fields for components. But my concern is about the "inherited component". Basically, when creating a structure for a custom builder, I can define "custom" components that are based on formio's components offer. 

I can do something like this (based on htmlelement component):

```
builder_components = {
...
        "components":{
            "sectionTitle":{
                "title":"Section title",
                "key":"sectionTitle",
                "icon":"header",
                "schema":{
                    "label":"Section title",
                    "type":"htmlelement",
                    "key":"sectionTitle",
                    "tag": "h3",
                    "className": "simple-title",
                    "content": "Un titre de section",
                }
            },
...
```

Thing is, I am then unable to disable the tag parameter for this component using the following snippet in my json:

```
builder_params = {
...
"sectionTitle":[
        {
            "key":"display",
            "ignore":false,
            "components":[
                {
                    "key":"tag",
                    "ignore":true
                },
                
            ]
        },
...
```

Any idea of how I could disable the tag for this component only, meaning without having to disable it on the htmlelement component that is is based on ?

This feature would be extremely helpful, but I didn't find a way yet to achieve it. @randallknutson is that even possible ?

Thanks for the help in advance

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
