### ISSUE TITLE
Change 'time_24hr' to 'time24hr' to follow camelCase

### ISSUE THREAD

**Issue by shea-maykinmedia** [formio/formio.js#4254]
I could be wrong but I believe that when dealing with numbers in a variable when using camelCase you should still not use an underscore.

In the DateField component and Calendar widget (and possibly other places) 'time_24hr' is used as a key but I think this should be 'time24hr' 

References: https://github.com/formio/formio.js/blob/0af704817b2d4b7931a8db3e0ea9d779b2fb9b75/src/components/datetime/DateTime.js#L102
https://github.com/formio/formio.js/blob/33c5777c483582b37b45515f6913f6ef68794f7e/src/widgets/CalendarWidget.js#L48

**Comment by ccontour** [comment]
Unfortunately that's a public variable undoubtedly with production code depending on it being inconsistently cased. Since the inconsistency isn't currently breaking anything, it is unlikely to get refactored due to the potential regressions it would cause
