### ISSUE TITLE
[BUG] Data Grid clears all items on item Reorder

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4256]
Using [Data Grid] with option [Initialize Empty] and [Allow Reorder] results in all items being cleared (removed) when items are reordered. 

NOTE: This issue exist only when [Initialize Empty] is checked otherwise the re-order works ok.

You can reproduce this in Sandbox Id: 610cd39fa889a6745ff95a8b

## Environment
- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Formio.js version: 4.13.4
- Browser: Chrome v92

## Steps to Reproduce
1. Add [Edit Grid] with [Texbox] column to form
2. In Options select both [Initialize Empty] and [Allow Reorder]
3. In rendered form and Add items to the Grid
4. Reorder one of the items 

## Expected behavior
- Items to remain visible and reordered
## Observed behavior
- All items are removed and Data Grid is empty

## Example
Before: 
![image](https://user-images.githubusercontent.com/9924769/128465266-3ffbf18f-24cb-40b5-9042-4eed2d3ecc39.png)

After Reorder:
![image](https://user-images.githubusercontent.com/9924769/128465350-ed3ea658-99cd-4546-87fc-200c4df96e6d.png)

Notice all values are still in the form in JSON but not visible

**Comment by wag110894** [comment]
Hello @ak99372, can you see if this is an issue on newer versions of formio.js?

**Comment by ak99372** [comment]
Hi @wag110894 I think I originally included `angular-formio` version instead but I'm assuming both angular and sendbox are using the latest formio.js version (4.13.4) right?

**Comment by ak99372** [comment]
I also tried the 4.14.0-rc.7 version in sandbox and the issue is still there as well

**Comment by nikithanarsing** [comment]
Hi, were you able to solve this issue?

**Comment by ak99372** [comment]
@nikithanarsing The issue is that reorder completely recreates the component as if the component was created the first time which wipes out all the rows (sinze [InitialzeEmpty] is set to true). So you'd have to override datagrid init function to something like this

```
init() {
	  const resurrectRows = this.rows && this.rows.length > 0;
	  super.init();
	  if (resurrectRows) {
	   this.createRows(true);
	  }
	}
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
