### ISSUE TITLE
[BUG] Time component in Safari not working

### ISSUE THREAD

**Issue by przzz27** [formio/formio.js#4258]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:  4.12.7
- Frontend framework: Vue
- Browser:  Safari
- Browser version: Version 14.1.2 (15611.3.10.1.5, 15611)

## Steps to Reproduce
1. Create a new form
2. Add a time component to the form
3. Make the time component required
4. Make the form available for public | Embed it anywhere
5. Open the form in Safari
6. Set a time
7. Try to submit
8. See how the submit button is not enabled

## Expected behavior
- Setting a time would submit the form
## Observed behavior
- Setting the time in Safari doesn't enable the submit button, if somehow the button is enabled an error appears in the time component saying it's required even though it has information

## Example
Live example; 
https://jsfiddle.net/przzz1227/068ymqtf/

For code or form JSON, please enclose in a code block:

```js
{
"_id": "610d523de101623c055bef1b",
"type": "form",
"tags": [],
"owner": "5fd3992814d672d78cd14468",
"components": [
{
"label": "Time",
"tableView": true,
"dataFormat": "HH:mm",
"validate": {
"required": true
},
"key": "time",
"type": "time",
"input": true,
"inputMask": "99:99"
},
{
"type": "button",
"label": "Submit",
"key": "submit",
"disableOnInvalid": true,
"input": true,
"tableView": false
}
],
"revisions": "",
"_vid": 0,
"title": "Time Bug",
"display": "form",
"access": [
{
"roles": [],
"type": "create_own"
},
{
"roles": [],
"type": "create_all"
},
{
"roles": [],
"type": "read_own"
},
{
"roles": [
"5f0e1601870c11341bd8e135",
"5f0e1601870c11e672d8e136",
"5f0e1601870c1176bdd8e137",
"5f0e1601870c111717d8e138",
"5f0e1601870c111397d8e139"
],
"type": "read_all"
},
{
"roles": [],
"type": "update_own"
},
{
"roles": [],
"type": "update_all"
},
{
"roles": [],
"type": "delete_own"
},
{
"roles": [],
"type": "delete_all"
},
{
"roles": [],
"type": "team_read"
},
{
"roles": [],
"type": "team_write"
},
{
"roles": [],
"type": "team_admin"
}
],
"submissionAccess": [
{
"roles": [
"5f0e1601870c1176bdd8e137"
],
"type": "create_own"
},
{
"roles": [],
"type": "create_all"
},
{
"roles": [],
"type": "read_own"
},
{
"roles": [],
"type": "read_all"
},
{
"roles": [],
"type": "update_own"
},
{
"roles": [],
"type": "update_all"
},
{
"roles": [],
"type": "delete_own"
},
{
"roles": [],
"type": "delete_all"
},
{
"roles": [],
"type": "team_read"
},
{
"roles": [],
"type": "team_write"
},
{
"roles": [],
"type": "team_admin"
}
],
"controller": "",
"properties": {},
"settings": {},
"name": "timeBug",
"path": "timebug",
"project": "5f0e1601870c11ec13d8e134",
"created": "2021-08-06T15:16:13.087Z",
"modified": "2021-08-06T15:17:57.008Z",
"machineName": "apiabroad-app-bxuidffwambbmmu:timeBug"
}
```

**Comment by przzz27** [comment]
Workaround;
Edit the time component's json schema and set "inputType" to text instead of time
<img width="666" alt="Screen Shot 2021-08-09 at 14 16 49" src="https://user-images.githubusercontent.com/61523021/128775711-3e6a63ad-afdd-4e3c-964c-6525c9287595.png">

Even as text, formio will take of invalid times

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
