### ISSUE TITLE
Set [readOnly, ViewAsHtml] proparty to a form with subform is not working

### ISSUE THREAD

**Issue by asalhani** [formio/formio.js#426]
@travist @Navpreet2289 @zackurben @AlameerDev

**Senario (steps):**
1. Create a new form which will act as a subform. (let's call it SubForm)
2. Create a new form (doesn't matters if it's form or wizard) (this is the main form)
3. In main form, add new form component and link it the SubForm created in Step# 1
4. Open main form in submission mode and submit new value
5. Capture submission in step 4 and open main form in view mode, by setting the submission proparty.
6. Set readOnly and ViewAsHtml proparty of form

**Expected:**
In submission mode the form should open in view (readonly) mode. By form I mean the main form which include a component of type form

**Actual:**
What happens now is that the components in subform are still enabled and didn't changed to read-only mode. The textbox in subform still redering as a textbox instead of label.

**Below is the form schema and a submission if you want to replicatet the case:**

` Formio.createForm(document.getElementById('formio'), {"_id":"5adefc5855c73f05a0f94a83","type":"form","tags":[],"deleted":null,"access":[{"roles":["5acdfe28e398a322a8a119a6","5acdfe28e398a322a8a119a7","5acdfe28e398a322a8a119a8"],"type":"read_all"}],"submissionAccess":[],"owner":"external","components":[{"type":"panel","title":"Page 1","components":[{"input":true,"tableView":true,"inputType":"text","inputMask":"","label":"","key":"page1TextField","placeholder":"","prefix":"","suffix":"","multiple":false,"defaultValue":"","protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"validate":{"required":false,"minLength":"","maxLength":"","pattern":"","custom":"","customPrivate":false},"conditional":{"show":"","when":null,"eq":""},"type":"textfield","hideLabel":false,"labelPosition":"top","tags":[],"properties":{}},{"clearOnHide":false,"input":true,"tableView":true,"key":"page1MySubForm","src":"","reference":true,"form":"5adee73755c73f05a0f94a7c","path":"","label":"mySubForm","protected":false,"unique":false,"persistent":true,"type":"form","project":"","hideLabel":false,"labelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{}}],"input":false,"key":"page1","clearOnHide":false,"theme":"default","tableView":false,"hideLabel":false},{"clearOnHide":true,"input":true,"tableView":true,"key":"undefinedHospitalSpec","src":"","reference":true,"form":"5adf0a1f55c73f05a0f94a92","path":"","label":"hospitalSpec","protected":false,"unique":false,"persistent":true,"type":"form","project":"","labelPosition":"top","tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{}},{"autofocus":false,"input":true,"label":"Submit","tableView":false,"key":"submit","size":"md","leftIcon":"","rightIcon":"","block":false,"action":"submit","disableOnInvalid":false,"theme":"primary","type":"button"}],"created":"2018-04-24T09:43:52.337Z","display":"wizard","name":"TestDatagridForm","path":"testdatagridform","title":"Test Data grid form","modified":"2018-04-30T10:33:01.696Z","machineName":"TestDatagridForm","__v":22}, {
       readOnly: true,
       viewAsHtml: true
    }).then(function (form) {
      form.submission = {"data":{"page1TextField":"dsf","page1MySubForm":{"_id":"5ae6f19db540020ee48dd6e0","form":"5adee73755c73f05a0f94a7c"}}};

    });`

![main](https://user-images.githubusercontent.com/5410830/39447371-2eeb8924-4cca-11e8-8a03-f400dea200fc.JPG)

![issue](https://user-images.githubusercontent.com/5410830/39447145-8c4341da-4cc9-11e8-9ea2-fc02e6aae4ea.JPG)

![code](https://user-images.githubusercontent.com/5410830/39447452-7546898c-4cca-11e8-8235-29696d40e794.JPG)

**Comment by asalhani** [comment]
@travist @AlameerDev
Any update on this issue? I just updated to latest version (**3.0.0-alpha.13**) however the issue still there..
Can you shed some light on what cause the issue.. and how I can fix it?

**Comment by asalhani** [comment]
@travist @Vercjames @YuryRybakSoftensity @randallknutson
Any update on this issue? 
As you know, read-only mode is being used heavily to display the submitted data.

Much appreciated...

**Comment by YuryRybakSoftensity** [comment]
@asalhani Thanks for your reporting and sorry for delay!
https://github.com/formio/formio.js/pull/487 should fix it.

**Comment by asalhani** [comment]
@jhen1422  @travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update so far?

**Comment by jhen1422** [comment]
This issue should be resolved
