### ISSUE TITLE
[QUESTION] Is there a way to self reference the [Resouce] in Parent/Child relationship?

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4262]
I would like to link submissions (of the same [Resource]) as Parent->Child (i.e. tree). I setup a [Node] resource and I added a reference field [Parent] that should list all existing [Node] submissions. The form looks like this:
![image](https://user-images.githubusercontent.com/9924769/128643322-3c07cf20-e925-4909-add7-08eb18ddd8f8.png)

Sandbox: 61102b3fe45ab84cb03e8c5d

However when I try to setup the field and link to [Parent] select control under [Data]->[Resource] the **[Node] resource itself is excluded from the list**.

**Q: Is there a reason why [Resource] can't self reference itself?** (or is there a different way to do this other than via custom URL)?

UPDATE: if I force override and set the Resource to [Node] on the form in the code it actually seems to work, so this might be just a UI builder blocking this option.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
