### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by virenderAttri** [formio/formio.js#4270]
Hi,

Is there any event which is trigger on copy paste component, actually I am using the **change** event but I am not able to find that
the component is by drag drop or  by copy paste. I am doing like this
**var onReady = function (e) {
                var formElement = document.getElementById('formio');
                builder.instance.on('addComponent', onBuild);
                builder.instance.on('change', onBuild);
            };**

Actually the issue is when we copy the component and paste in somewhere all the json will also be same as copy element. In this case we will not able to verify that component is different.

So  we are in trouble to save components, so please let me know that what is event for copy paste that I can handle the JSON of copied element and can distinguished both them.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
