### ISSUE TITLE
CDN's in sample code for Builder page is broken

### ISSUE THREAD

**Issue by donnyv** [formio/formio.js#4275]
Your sample code in the ReadMe to create the builder is broken. It seems the cdn libraries its pointing too are broken.

**Comment by ccontour** [comment]
Can you provide a link to the broken page?

**Comment by donnyv** [comment]
I think I fixed it. Seems to be working now. But I am getting this error.
https://gis.civilsolutions.biz/downloads/FormBuilder/FormBuilder.htm
![image](https://user-images.githubusercontent.com/2224189/129632907-21c3caef-32fe-41ec-9da7-05cfdc1e8c37.png)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
