### ISSUE TITLE
How to display Date Time in UTC, not as a time offset from UTC?

### ISSUE THREAD

**Issue by opcodewriter** [formio/formio.js#4276]
By default, a Date Time component saves its value formatted to **ISO 8601 - time offset from UTC** :
```
  {
      "myDateTime1" : "2021-08-18T12:00:00+02:00"
  }
```
I would like to have the value formatted to **ISO 8601 - UTC**, like this:
```
  {
      "myDateTime1" : "2021-08-18T10:00:00Z"
  }
```

When the form is rendered, the value must be displayed in the user's local time. In the example above, it will show "2021-08-18 12:00:00".

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
