### ISSUE TITLE
Documentation on building the formio.full.min.js

### ISSUE THREAD

**Issue by donnyv** [formio/formio.js#4279]
Is there any documentation anywhere on how the JavaScript library is built?

I want to generate 
formio.full.min.js
formio.full.min.css

**Comment by travist** [comment]
Clone this repo and then type the following.

```
npm install
npm run build
```

These files will be in the dist folder.

**Comment by donnyv** [comment]
Sorry for the noob question. I've never done a node project. Thanks!
