### ISSUE TITLE
Can't Find Example / Documentation for Custom Component Without Angular

### ISSUE THREAD

**Issue by vchtelmakh** [formio/formio.js#428]
@travist: We have a form.io subscription to hold our form schemas. I don't understand how to create a custom component without angular. I see the Angular example here: https://github.com/formio/ngFormBuilder/issues/135

The documentation for custom components without Angular doesn't really provide a solid starting point: 
https://github.com/formio/formio.js/wiki/Custom-Component

Do I just force the custom component into the html here:

```
"type":"form",
"owner":"598090952b8ca5000707ba89",
"components":[
  PUT MY CUSTOM COMPONENT HERE ALONG WITH THE OTHERS?
]
````

...using your Angular example, it would look like this?

```
[title: 'Five Star',
        template: 'formio/components/fivestar.html',
        settings: {
          input: true,
          tableView: true,
          inputType: 'number',
          label: '',
          key: 'numberField',
          placeholder: '',
          prefix: '',
          suffix: '',
          defaultValue: 0,
          protected: false,
          persistent: true,
          validate: {
            required: false,
            min: '',
            max: '',
            step: 'any',
            integer: '',
            multiple: '',
            custom: ''
          }](url)
```

Can I in-line the html? Will this work or do I need to do something else? Appreciate any help.

**Comment by sunshinesanty** [comment]
I would also be interested to know more about adding custom components and registering with the existing Components.
I did see from the code that the Components class has a addComponent() method. could you elaborate more on the usage or if there are any restrictions in the usage of the same.

**Comment by MichaelSchmetter** [comment]
Hi @travist,
that is something I would be interested too.
Using the form-builder and customizing the actual template that gets rendered.
https://github.com/formio/formio.js/wiki/Form-Renderer unfortunatly is not really helpful. The mentioned "Templating section" is not available.

**Comment by jhen1422** [comment]
Closing - outdated issue
Please open a new issue if this is still outstanding or contact support@form.io
