### ISSUE TITLE
[BUG] Strings in custom default value and calculated value tabs are not localized

### ISSUE THREAD

**Issue by PranapSivadasan** [formio/formio.js#4283]
## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.10.5
- Frontend framework: Angular
- Browser: Not browser specific

## Steps to Reproduce
1. In form builder, drag and drop a text field component.
2. Navigate to data tab and expand the custom default value panel.
3. The data injected there as html from util.js file is not translated.

## Expected behavior
 - The expected behaviour is the data must be translated in the selected language.

## Observed behavior
 - The observed behaviour is the data not being translated.
 - I investigated the issue from the [Util.js - logicVariablesTable function](https://github.com/formio/formio.js/blob/56622b0c743baea38083e20787862bd208f2fda4/src/components/_classes/component/editForm/utils.js#L38)
 - The [html components' template](https://github.com/formio/formio.js/blob/56622b0c743baea38083e20787862bd208f2fda4/src/templates/bootstrap/html/form.ejs#L1) is written in a way that the contents provided inside the _**content**_ property under [Util.js - logicVariablesTable function](https://github.com/formio/formio.js/blob/56622b0c743baea38083e20787862bd208f2fda4/src/components/_classes/component/editForm/utils.js#L38) will be translated as such.
 - But in the [Util.js - logicVariablesTable function](https://github.com/formio/formio.js/blob/56622b0c743baea38083e20787862bd208f2fda4/src/components/_classes/component/editForm/utils.js#L38) the content contains html tags along with the strings.
 - Requesting a way to localize those strings.

## Example

**English Locale -** 

![image](https://user-images.githubusercontent.com/44242289/130227217-58c3c288-96e4-4c69-9095-9e1a8abcd0d4.png)

**French Locale -**
 
![image](https://user-images.githubusercontent.com/44242289/130227146-30ba5455-41bf-4579-99b2-2b4a68dad47d.png)

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
