### ISSUE TITLE
[BUG] URL parameter is being cut to base domain only

### ISSUE THREAD

**Issue by NiMusco** [formio/formio.js#4285]
Hey,
I'm trying to change formio URL (the one that is used to fill resource dropdowns).

So, I set "url" parameter as, ie: ```http://domain.com/formioServer```.
And the requests are being fired as: ```http://domain.com/form/5b3a67f607ac4a6f777dbfe6/submission```
Note how **formioServer** is missing. Like it's being cut or sanitized. I understand that as a bug.

------

Just to give you a little more of background:
What I'm trying to do is to have two instances of Formio (pointed at two different hosts) in the same page. Is that possible?

This does not suit me, since it will globally replace all my forms.
```Formio.setBaseUrl(...);```
```Formio.setApiUrl(...);```

------

Any of these "solutions" would make it work:

1. Being able to do something like this:
```Formio[0].setBaseUrl(...)```
```Formio[1].setBaseUrl(...)```

2. Or to change formio URL per instance of form, allowing full URLs (domain, directories, query params).
```<form url=http://domain.com/formioServer?id=1>```
```<form url=http://domain.com/formioServer?id=2>```

3. Or to have an "extraParams" sort-of attribute. So I can pass any extra information to tell them apart.
```<form extraParams={id:1}>```
```<form extraParams={id:2}>```

4. Or to pass the whole Formio instance.
```<form Formio={Formio1}>```
```<form Formio={Formio2}>```

Do we have anything like that?

JFYI: I'm using react-formio, but it doesn't seem to be a problem with the component itself.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
