### ISSUE TITLE
[BUG] Validate on blur not respected for nested forms

### ISSUE THREAD

**Issue by mrcandu** [formio/formio.js#4289]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: Enterprise 7.1.7
- Formio.js version: 4.13.5
- Frontend framework: Vanilla JS
- Browser: Chrome, Edge etc
- Browser version: Latest

## Steps to Reproduce
1. Create a form with a single text field. For the text field set `Minimum Length`:100 and `Validate on`:Blur
2. Create a new form with nested form component with the previously created form to nest
3. Launch the new form

## Observed behavior
When entering a value in the text field it validates on change, not on blur.

## Expected behavior
The form that the text field form is embedded in should respect the validate on blur setting.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
