### ISSUE TITLE
[BUG] Data Grid item getting too long

### ISSUE THREAD

**Issue by pocketcap** [formio/formio.js#4294]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12.1
- Frontend framework: vanilla JS
- Browser: IE
- Browser version: 11

## Steps to Reproduce
1. Create a Grid Data component with dropdown fields and date fields
2. Open the form in IE 11
3. Choose an option with long value (eg, Service Dropdown in below screenshot).

## Expected behavior
All the fields are displayed within the grid.

## Observed behavior
Some fields exceeds the right side of the window.

![image](https://user-images.githubusercontent.com/1475774/131039622-05c23d41-373c-4943-98fb-822a7d6c7036.png)

Can I limit the width of the Service Dropdown? Also can date field become shorter?

I tried to put columns layout within grid, but one row fields would be displayed in multiple rows.

Thanks.

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
