### ISSUE TITLE
[BUG] embedded form into the application has styling issues

### ISSUE THREAD

**Issue by mdesousa** [formio/formio.js#4296]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 5.1.1
- Frontend framework: React

## Steps to Reproduce
Embed a form inside and existing React application as shown in the example (this is using @formio/react):

```
        <Form
          src="https://example.form.io/example"
          onSubmit={console.log} />
```

## Expected behavior

The form shows as it appears in the preview in form.io

## Observed behavior
The form is not using the original styling from form.io. Is there a way to preserve the original style?
Thanks!

![image](https://user-images.githubusercontent.com/1141403/131183532-1d53e095-338b-44e4-8890-1c44f0d778dd.png)

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
