### ISSUE TITLE
[BUG] {Storage Type}=[Object] ignored when using {DataType} = [values] on select field

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4298]
## Environment
- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Formio.js version: 14.3.2
- Frontend framework: angular
- Browser: Chrome 92.0

## Steps to Reproduce
1. Create form with a [select] field
2. In field [Data] options set [Data Type] to "Values" with list of values (example below)
3. In field [Data] option set [Storage Type] to "Object"
4. save and open the form

![image](https://user-images.githubusercontent.com/9924769/131408219-95c941e1-816e-4846-a5a8-c5248b593026.png)

Sandbox: 612d4dc0dd98944fde580976

## Expected behavior

I expect submission to store the answer as an Object with both label and value included i.e.  ```"selectObject":{"label:"One", value:"1" "}```

## Observed behavior
Instead only the value is stored as String like this ```"selectObject": "1"```

## Example
Storing Values as Object on submission would be very helpful from historical point of view **when the list of values/labels on the form can change over time** while submission **retains original answer i.e "as entered originally"**.

So [Object] as Storage Type doesn't work for Data Type = 'Values' (or that option shouldn't be included in the options as it doesn't seem to do anything different than String and Autotype?) or is there another way to include the object (label & value) of selected item from Values in the submission data?

**Comment by xishuiinsz** [comment]
part codes for you reference
--------------------------------
  "dataSrc": "custom",
  "data": {
    "custom": "values = [\n{label:'One', value: '1'},\n{label:'two', value: '2'},\n{label:'three', value: '3'},\n{label:'Four', value: '4'},\n]"
  },
"valueProperty": "",

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
