### ISSUE TITLE
[BUG] When creating new components, the last modified default value is displayed in the form editor

### ISSUE THREAD

**Issue by lHilovsky** [formio/formio.js#4299]
## Enviroment

- Formio.js version: 4.13.5
- Frontend framework: Angular
- Browser: Chrome

## Steps to reproduce

1. Drag and drop some component
2. Change the default value
3. Close edit modal
4. Drag and drop same type of component
5. Save component

## Expected behavior

- The default value of newly added component (from step 4) in the form editor should be empty
## Observed behavior

- The default value of newly added component (from step 4) in the form editor is the same as the value modified for the first component

## Example
Textfield and number component can be used as examples:
https://user-images.githubusercontent.com/56341727/131485508-da678f6c-4d26-4546-8683-344bd5b2b993.mp4

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
