### ISSUE TITLE
Question - Is there a way for me to catch a schema Error on my Vue client?

### ISSUE THREAD

**Issue by MichaelChung123** [formio/formio.js#4304]
I am trying to do custom Error handling when a user has a broken Form Schema. 

In this example, I found a bug that breaks the schema if you remove the `Currency` Type of a currency component. 
![image](https://user-images.githubusercontent.com/32748701/131713596-56f6271b-4852-4237-b72d-357c3eddd66d.png)

I am trying to catch the errors that get created on the Form IO end, when you view your Form with this broken schema.
![image](https://user-images.githubusercontent.com/32748701/131713615-43a98302-f8f3-4c7a-9fd9-4bd271519f2c.png)

I found that are the events called `componentError` and `error` but have had no luck receiving any information from those events in my `<Form>` Component on the client.

Ref: https://github.com/formio/formio.js/blob/af41f01d52c884805adb742a95d01cd59b425f07/src/components/form/Form.js#L741

My Form Component in the Vue client
```
      <Form
        :form="formSchema"
        :key="reRenderFormIo"
        :submission="submission"
        @change="onChange"
        @submit="onSubmit"
        @submitDone="onSubmitDone"
        @submitButton="onSubmitButton"
        @customEvent="onCustomEvent"
        @componentError="onError" // not getting any error info from this one
        @error="onError" // not getting any error info from this one
        @focus="onFocus"
        :options="viewerOptions"
      />
```

Is there any way for me to attach to the Error instance that's being sent from Form IO when the Form Schema errors like this?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
