### ISSUE TITLE
- I need to have custom error comments while creating form

### ISSUE THREAD

**Issue by Chayannath19** [formio/formio.js#4306]
![image](https://user-images.githubusercontent.com/89972934/131819534-68ea2d88-ef93-43ed-909e-70186bb29880.png)

Need to give custom comments like this, how it is coming up " API Key is not unique" While creating the form, is there any way to do it?

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
