### ISSUE TITLE
[BUG] Edit Modal is not rendering properly with many UI Bugs and missing options

### ISSUE THREAD

**Issue by us24man** [formio/formio.js#4307]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
- Version: 
  - Formio.js version: latest version using the CDN
  - Frontend framework: Django + Bootstrap 4.4
  - Browser: Chrome
  - Browser version: Version 92.0.4515.159 (Official Build) (arm64)

## Steps to Reproduce
1.  Integrate the form builder into your django application using the official CDN
2.  Open the edit dialogue box of any component

## Expected behavior
The edit dialogue box/modal should display as it is in the demo. With all the options and properly sized UI elements.

## Observed behavior
The edit dialogue box/modal has many missing options. It only displays labels of options and the checkboxes are all hidden. Advanced Logic options are not sized properly. The edit modal is simply not showing properly. 
## Example
![image](https://user-images.githubusercontent.com/32433278/131860593-769274ad-f2bc-4873-a0e7-8ef8355c5de3.png)
![image](https://user-images.githubusercontent.com/32433278/131860616-fbef25bc-39b8-4e9b-9d24-7e1a780bfa18.png)
![image](https://user-images.githubusercontent.com/32433278/131860631-c9bddad6-e14c-46ec-ad5f-9aa9f392fdda.png)

For code or form JSON, please enclose in a code block:

```js
<link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
<link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
<script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
    window.onload = function() {
    Formio.builder(document.getElementById('builder'), {}, {  
        noDefaultSubmitButton: true,  
        builder: {
        premium: false
         }
})
};
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
