### ISSUE TITLE
[BUG] Tree won't display items when Columns are used

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4308]
## Environment
  - [x] Local deployment
- Formio.js version: 4.13.2
- Frontend framework: angular
- Browser: Chrome
- Browser version:93.0

## Steps to Reproduce
1. Add Tree Component
2. Add Columns with Textfields in them
3. Enter submission and add items to tree

![image](https://user-images.githubusercontent.com/9924769/132160063-5f0f4fa7-26bf-4360-b369-d075f4c4c572.png)

Sandbox: 613595b3f222874fdcdde5e7

## Expected behavior
Tree to display items/values entered in Textfields

## Observed behavior
Tree items appears empty

![image](https://user-images.githubusercontent.com/9924769/132160389-6068820e-90b5-45fe-9f95-def5d31060e5.png)

**Comment by Tatsiana8** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
