### ISSUE TITLE
[BUG] Tree - [Cancel] button on root item clears the whole tree (with all children)

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4309]
## Environment
  - [x] Local deployment
- Formio.js version: 4.13.2
- Frontend framework: angular
- Browser: Chrome
- Browser version: 93.0

## Steps to Reproduce
1. Create Tree with single Textfield
2. Enter couple tree items/nodes
![image](https://user-images.githubusercontent.com/9924769/132161019-3db62e3d-d5a0-45ac-b1f2-cf736c7e0584.png)
3. Click [Edit] on **root** item
4. Then click [Cancel]

![image](https://user-images.githubusercontent.com/9924769/132161166-ae62ea61-cded-4c6c-8d3c-691c484070f4.png)

## Expected behavior
Edit mode of **root** item to revert back to tree view.
Note: this issue only applies to root item (all child items behave as expected)

## Observed behavior
The whole tree is reset and all items are removed and there isn't really way out of it (without reloading the whole submission)
![image](https://user-images.githubusercontent.com/9924769/132161226-79d04b7a-104a-4a10-8910-301387f11d6d.png)

Could this be related to #4256 as the underlying data stay intact just the UI becomes disconnected.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
