### ISSUE TITLE
Datagird lose data when its hidden 

### ISSUE THREAD

**Issue by asalhani** [formio/formio.js#431]
@travist @Navpreet2289 @zackurben @AlameerDev

The issue occured when the Datagird component is being hidden after initial render. So depends on user input (let's say checkbox) the datagrid will be visiable only if the checkbox value is true.
When the datagrid became visiable, after clicking "Add another" button, the data of previous record in datagrid is lost.

_Note: In building datagrid component, I used the same structure mentioned in below sample link:_
[datagrid sample](https://github.com/formio/formio.js/blob/8ba9cd3888529be730f07a809826b3779c9a78ee/app/examples/datagrid2.md)

To re-produce the case, use the following form definition:

`{
  "components": [
    {
      "autofocus": false,
      "input": true,
      "inputType": "checkbox",
      "tableView": true,
      "label": "isEnabled",
      "dataGridLabel": false,
      "key": "isEnabled",
      "defaultValue": false,
      "protected": false,
      "persistent": true,
      "hidden": false,
      "name": "",
      "value": "",
      "clearOnHide": true,
      "validate": {
        "required": false
      },
      "type": "checkbox",
      "labelPosition": "right",
      "tags": [],
      "conditional": {
        "show": "",
        "when": null,
        "eq": ""
      },
      "properties": {},
      "lockKey": true,
      "hideLabel": false
    },
    {
      "label": "Children",
      "key": "children",
      "type": "datagrid",
      "input": true,
      "components": [
        {
          "type": "panel",
          "label": "User Information",
          "key": "userinfo",
          "components": [
            {
              "autofocus": false,
              "input": true,
              "tableView": true,
              "label": "Main Speciality",
              "key": "mainSpeciality",
              "placeholder": "",
              "data": {
                "values": [
                  {
                    "value": "1",
                    "label": "1"
                  },
                  {
                    "value": "2",
                    "label": "2"
                  },
                  {
                    "value": "3",
                    "label": "3"
                  }
                ],
                "json": "",
                "url": "",
                "resource": "5adeff0655c73f05a0f94a85",
                "custom": ""
              },
              "dataSrc": "values",
              "valueProperty": "data.mainSpecialityResource",
              "defaultValue": "",
              "refreshOn": "",
              "filter": "",
              "authenticate": false,
              "template": "<span>{{ item.label }}</span>",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "validate": {
                "required": false
              },
              "type": "select",
              "labelPosition": "top",
              "tags": [],
              "conditional": {
                "show": "",
                "when": null,
                "eq": ""
              },
              "properties": {},
              "lockKey": true,
              "searchField": ""
            },
            {
              "autofocus": false,
              "input": true,
              "tableView": true,
              "label": "Sub Speciality",
              "key": "subSpeciality",
              "placeholder": "",
              "data": {
                "values": [
                  {
                    "value": "a",
                    "label": "a"
                  },
                  {
                    "value": "b",
                    "label": "b"
                  },
                  {
                    "value": "c",
                    "label": "c"
                  }
                ],
                "json": "",
                "url": "",
                "resource": "5adeffac55c73f05a0f94a89",
                "custom": ""
              },
              "dataSrc": "values",
              "valueProperty": "data.subSpecialityResource",
              "defaultValue": "",
              "refreshOn": "",
              "filter": "data.mainSpecialityRefrence={{data.mainSpeciality}}",
              "authenticate": false,
              "template": "<span>{{ item.label }}</span>",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "validate": {
                "required": false
              },
              "type": "select",
              "labelPosition": "top",
              "tags": [],
              "conditional": {
                "show": "",
                "when": null,
                "eq": ""
              },
              "properties": {},
              "searchField": "",
              "clearOnRefresh": true,
              "lockKey": true
            }
          ],
          "inDataGrid": true,
          "clearOnHide": false,
          "input": false,
          "title": "",
          "theme": "default",
          "tableView": false,
          "hideLabel": true
        }
      ],
      "autofocus": false,
      "tree": true,
      "tableView": true,
      "protected": false,
      "persistent": true,
      "hidden": false,
      "clearOnHide": true,
      "addAnotherPosition": "bottom",
      "tags": [],
      "conditional": {
        "show": "true",
        "when": "isEnabled",
        "eq": "true"
      },
      "properties": {},
      "isNew": false
    }
  ],
  "display": "form",
  "name": "TestDatagridform",
  "path": "testdatagridform",
  "title": "Test Data grid form"
}`

**Comment by asalhani** [comment]
@travist @Vercjames @YuryRybakSoftensity @randallknutson
Any update on this issue?

Much appreciated...

**Comment by asalhani** [comment]
@jhen1422  @travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update so far?

**Comment by jhen1422** [comment]
This issue has been resolved

**Comment by dileepkumarsaxena2012** [comment]
@travist @Vercjames @YuryRybakSoftensity @randallknutson

The same issue has been occurring here If I'll drag "Select Boxes" of the basic component, choosing "Multiple Values" option then if I click on save button, the whole form is not showing including Datagrid component...

**Comment by dileepkumarsaxena2012** [comment]
@travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update on this issue???

**Comment by wag110894** [comment]
Hello Dileep,

Thanks for reaching out! 

We do offer Support Packages to help you make the most of Form.io. Let us know if you are interested via email at support@form.io and we can send over Pricing.

Our support packages are for training, support or development services. The hours can be used in one hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.

We also recommend that you open a new issue for this item.
Thanks.
