### ISSUE TITLE
[BUG] Mounting a form.io form breaks i18next instance and the whole website

### ISSUE THREAD

**Issue by sansiaali** [formio/formio.js#4324]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.13.5
- Frontend framework: React
- Browser: Chrome/Firefox
- Browser version: 93/91

## Steps to Reproduce
https://codesandbox.io/s/sharp-chandrasekhar-199or

1. Open the codesandbox
2. Translating works on the homepage
3. Navigate to /form using the link

## Expected behavior

I am able to use react-i18next with a backend (in this case http-backend) and plugins of my choice alongside with form.io.

## Observed behavior

Upon mounting the form.io form, it replaces the existing i18n instance resulting in React's Suspense system freezing the whole site. I have tried giving the form component an existing i18next instance but it seems that it forces a reinitialization anyway which seems to break the site.

If it is the reinitialization that is causing the problem, would it be possible for form.io not to run reinit on the i18next instance if it's given one during mount? Could `i18next.loadResources` be used to bring in the form translations?

(react-)i18next setup is straight from the library's documentation.

I can't seem to get this working, any help would be greatly appreciated!

**Comment by shancial** [comment]
Upon opening the codesandbox the first time, you might need to refresh the inner browser window to display the example site.

**Comment by madflow** [comment]
@shancial There is an undocumented hack, which I have found in some of the issues here:

```js
  const { t, i18n } = useTranslation();
```

```js
 <Form options={{i18next: i18n.createInstance()}} 
```

This should get rid of the suspense loading problem - could introduce other side effects.

**Comment by shancial** [comment]
Thanks! I actually ended up removing the reinitialization of i18next in `Webform.js` (if i18n is already present) from formio source and creating a patch with `patch-package` a few days ago. Since I always initialize i18n before loading the forms it seems to work, but as with your solution it could have side effects. I haven't tested it enough yet.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
