### ISSUE TITLE
[BUG] Wizard buttons are not translated

### ISSUE THREAD

**Issue by madflow** [formio/formio.js#4328]
## Environment

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: latest
- Formio.js version: latest
- Frontend framework: Vanilla JS / React
- Browser: Firefox
- Browser version: Latest

## Steps to Reproduce

We are embedding a "wizard" Form in a React web application. In order to translate the form elements we followed:  https://docs.form.io/developers/translations

The translations work - except for the standard (?) wizard buttons. I have created a Jsfiddle to illustrate the problem. I copy pasted https://formio.github.io/formio.js/app/examples/language.html and changed display to "wizard".

## Expected behavior

The standard wizard buttons are translated when providing the necessary "18n" payload.

## Observed behavior

The standard wizard buttons are not translated.

## Example

https://jsfiddle.net/9buohsjq/

**Comment by LorandNeculae** [comment]
Hi @madflow . I've had the same issue, try using lowercase letters for the wizard button key (e.g. 'Cancel' should be 'cancel' and 'Submit' -> 'submit' ).

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
