### ISSUE TITLE
[QUESTION] Configure wizard panel specific options

### ISSUE THREAD

**Issue by tiberiu89** [formio/formio.js#4346]
Is there a way to customize the wizard builder panels, more specifically the panel options that related to wizard pages.
I can see they are put inside a conditional fieldset, but the fieldset does not have a key associated so I don't see how can that be overwritten via custom editForms

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
