### ISSUE TITLE
Form renderer - How to get submission data without data from the disabled fields?

### ISSUE THREAD

**Issue by andreinitescu** [formio/formio.js#4351]
I see the submission data contains disabled fields. 
Is there a way to make the Formio renderer not create submission data with disabled fields?

My scenario is my backend does not allow data with disabled fields.

**Comment by xishuiinsz** [comment]
codes in your button edit form is for your reference
--------------------------------------------------------------
utils.eachComponent(form.components, function(comp) {
  const { disabled,key } = comp.component;
  if(disabled === true && data.hasOwnProperty(key)){
    delete data[key]
  }
})
const { element } = instance;
const btn = element.querySelector('button');
component.action = 'submit';
btn.click();

**Comment by andreinitescu** [comment]
@xishuiinsz Thanks for that, I already know how to remove properties based on the disabled component setting.

I was looking instead for a no-code option, like for example, a setting on the form renderer or, when editing the form in the form builder, on the disabled component.
It would be useful because in my scenario, updating read-only data is considered an error. So now, I need to clean-up the submission data before sending it to the server.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
