### ISSUE TITLE
[BUG] FormBuilder.setForm() method does not work any more

### ISSUE THREAD

**Issue by kzhang-dsg** [formio/formio.js#4359]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.12 +
- Frontend framework: None
- Browser: All browsers
- Browser version: latest version

## Steps to Reproduce
FormBuilder.setForm() does not update the form schema anymore. The same code works in Formio 4.9 version.
- See this non-working example using latest version of formio: https://jsfiddle.net/nxu01kh5/
- See this working example using 4.9 version of formio: https://jsfiddle.net/nxu01kh5/1/

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
