### ISSUE TITLE
[BUG] Cancelling submission does not re-enable button

### ISSUE THREAD

**Issue by dsuresh-ap** [formio/formio.js#4365]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: v4.13.6
- Frontend framework: Android, iOS
- Browser: Chrome, Safari
- Browser version:

## Steps to Reproduce
1. Click to submit
2. Pass an empty message into the `next` callback

## Expected behavior
The submission button re-enables.

## Observed behavior
The submission button stays disabled. This used to work but broke after a certain update. Refreshing the form resets it.

We followed the example from https://help.form.io/developers/form-renderer#beforesubmit-submission-next.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

https://user-images.githubusercontent.com/21132682/135164480-8fb9a110-d534-44ad-a137-eeb6a1dcc2bc.MP4

For code or form JSON, please enclose in a code block:

```js
next({
    message: '',
    component: {},
    silent: true
  });
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
