### ISSUE TITLE
customize formbuilder button actions

### ISSUE THREAD

**Issue by vivekarza** [formio/formio.js#4370]
Hi

I am using formio js react app and trying to customize/limit what to show in button actions dropdown. Is there a way to control what to show in the popup drop down values
![image](https://user-images.githubusercontent.com/5533012/135311805-480d571f-2799-42f8-8390-4a5891b4d1c0.png)

I wanted to show only two actions "submit" and " "Reset" insted of "Submit", "Reset" "Save in State", "Event","OAuth", etc

I tried like this in the form builder options 

editForm: {
                textfield: [
                  {
                    key: 'api',
                    ignore: true
                  },
                  {
                    key: 'data',
                    ignore: true
                  },
                  {
                    key: "display",
                    ignore:false,
                    components:[
                        {
                            key:"prefix",
                            ignore:true
                        },
                        {
                            key:"widget.type",
                            ignore:false
                        },
                        {
                            key:"inputMask",
                            ignore:false
                        },
                        {
                            key:"inputMasks",
                            ignore:false
                        }
                    ]
                  }
                         
                ],
                button:[
                    {
                        key:"display",
                        ignore:false,
                        components:[
                            {
                                key:"action",
                                ignore:false,
                                **data:{
                                    values:[
                                     {label: 'Submit', value: 'submit'},
                                     {label: 'Reset', value: 'reset'}
                                    ],
                                },
                                dataSrc:"values",**
                                defaultValue:"reset",
                            }
                        ]
                    },
                    {
                        key: 'api',
                        ignore: true
                      }
                ],
but did not work, can you please let me know if we can able to customize the submit button actions
Any help is appreciated.
Thanks

**Comment by xishuiinsz** [comment]
override the button compoent of formio.js , codes below is for you reference.
-----------------------------------------------------------------------------------
const { Formio } = require("formiojs");
const BtnComponent = Formio.Components.components.button;
class MyBtnComponent extends BtnComponent {
  static schema(...extend) {
    return BtnComponent.schema(
      {
        label: "my button",
        type: "myButton"
      },
      ...extend
    );
  }

  static get builderInfo() {
    return {
      title: "my Button",
      group: "layout",
      icon: "code",
      weight: 2,
      documentation: "/userguide/#button-component",
      schema: MyBtnComponent.schema(),
    };
  }
}
MyBtnComponent.editForm = (...args) => {
  const editForm = BtnComponent.editForm(...args);
  const actionComponent = Formio.Utils.getComponent(editForm.components, "action");
  actionComponent.data.values = [
    {
      label: "Submit",
      value: "submit",
    },
    {
      label: "Reset",
      value: "reset",
    },
  ];
  return editForm;
};
Formio.Components.addComponent("myButton", MyBtnComponent);

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
