### ISSUE TITLE
[BUG] Not consuming latest fuse.js which is dependency to Choices.js

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#4378]
## Environment
Please provide as many details as you can:
There is an issue with old fuse.js in searching, when characters length more than 32 then search is not working as expected.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 3.x
- Formio.js version: 3.29.9 , 4.x too
- Frontend framework: 
- Browser: Any
- Browser version:

## Steps to Reproduce
1. Create select component
2. Under data tab for values add more length value like I have given below
3. Now try searching in renderer with more than 32 chars in search field.

## Expected behavior
Should show all values when searching with more than 32 chars.

## Observed behavior
Search is not working properly.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```
```json
"data": {
                "values": [
                    {
                        "label": "Food Establishment Application",
                        "value": "foodEstablishmentApplication"
                    },
                    {
                        "label": "Food Establishment ApplicationX",
                        "value": "foodEstablishmentApplicationX"
                    },
                    {
                        "label": "Food Establishment ApplicationXY",
                        "value": "foodEstablishmentApplicationXy"
                    },
                    {
                        "label": "Food Establishment ApplicationXX",
                        "value": "foodEstablishmentApplicationXx"
                    },
                    {
                        "label": "Food Establishment ApplicationXXA",
                        "value": "foodEstablishmentApplicationXxa"
                    },
                    {
                        "label": "Food Establishment ApplicationXXB",
                        "value": "foodEstablishmentApplicationXxb"
                    },
                    {
                        "label": "Food Establishment No match 1",
                        "value": "foodEstablishmentNoMatch1"
                    }
                ]
            },
```

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
