### ISSUE TITLE
CKeditor - How to customize CKeditor Toolbar

### ISSUE THREAD

**Issue by eganugrah** [formio/formio.js#4384]
I want to add some plugins in CKeditor Toolbar. How do I install the plugin?

**Comment by glazkovalex** [comment]
So, how do you connect and configure the plugin for CKEditor? For example, how to install a plugin to support saving text in markdown rather than html?

**Comment by lane-formio** [comment]
We don't currently support the plugin, but are always willing to review any contributions to include this functionality in the renderer.

**Comment by glazkovalex** [comment]
> We don't currently support the plugin, but are always willing to review any contributions to include this functionality in the renderer.

@lane-formio, hello!
I understand that you do not support plugins for CKEditor. I don't expect that you would support a lot of plugins for it. I hope that connecting the plugin to the CKEditor editor you use in your wonderful Formio is possible without any special support from Formio. In particular, the "Markdown" plugin is connected [like this:](https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html#installation) :

    import { ClassicEditor, Markdown } from 'ckeditor5';
    // More imports.
    // ...
    ClassicEditor
    .create( document.querySelector( '#snippet-markdown' ), {
        plugins: [
            Markdown,
            // More plugins ...
        ],
        // More of editor's configuration ...
    } )
    .then( /* ... */ )
    .catch( /* ... */ );
As I see in your Formia for the "TextArea Component" it is possible to set not only the WYSIWYG editor CKEditor, but also specify some "Settings" for it. 
![image](https://github.com/user-attachments/assets/ceaff4dd-1c2a-42ae-8672-16bfefc7f4d6)
These are probably the very Settings in which you need to register `{plugins: [ Markdown, ...`. 
Please find out from your colleagues if someone has connected any plugin for CKEditor in your Formio. I would like to see at least one example of connecting a plugin to the CKEditor built into Formio.
