### ISSUE TITLE
[BUG] DevTools failed to load source map: Could not load content for tooltip.js.map:

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#4388]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: N/A, custom backend 
- Formio.js version: 4.13.7
- Frontend framework: React
- Browser: Google Chrome
- Browser version: Version 94.0.4606.81 (Official Build) (64-bit)

## Steps to Reproduce
1.  Open any page with `formiojs` loaded, for example the official builder example: https://formio.github.io/formio.js/app/builder
2. See the warning in the console about source maps. In our React app, we'are only getting the one about `tooltip.js`:
```
DevTools failed to load source map: Could not load content for webpack://Formio/node_modules/tooltip.js/dist/esm/tooltip.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

but there are more there.

## Expected behavior
No warning in the DevTools Console.

## Observed behavior
Warning about missing source maps.

## Example
![image](https://user-images.githubusercontent.com/49182064/136516193-dbbb98dd-d111-4a40-bf60-ead3ccadeb87.png)

**Comment by opcodewriter** [comment]
Is there a way to prevent this? Can someone please help? I see this happening in my production app. How can I prevent this?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
