### ISSUE TITLE
[BUG] Date/Time requires two clicks to set date value

### ISSUE THREAD

**Issue by AndewKolovrat** [formio/formio.js#4401]
## Environment
- Formio.js version: 4.13.6 or more
- Frontend framework: react

## Steps to Reproduce
1. Enter value to data/time or select value from widget
2. delete value
3. select value from widget

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
