### ISSUE TITLE
[BUG] Tabs with Columns compatibility issue with v4.13.8

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4406]
## Environment
Hosting type
- [x] Local + Sandbox deployment
- Formio.js version: 4.13.8
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 94.0

## Steps to Reproduce
1. Use version 4.13.7 to load sandbox form 616f33015fe198f2d4f8b88e 
2. Switch version to 4.13.8 
3. Navigate to tab [New] and try to remove field set named ["Try To Remove Me in 4.13.8"]

## Expected behavior

Remove field without error.

## Observed behavior
The builder crashed with following error and becomes irresponsive
```
Tabs.js:132 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at eval (VM234472 Tabs.js:132)
    at Array.map (<anonymous>)
    at TabsComponent.get (VM234472 Tabs.js:131)
    at eval (VM234449 Webform.js:1059)
    at eval (VM234354 NestedComponent.js:327)
    at arrayEach (VM233607 lodash.js:531)
    at Function.forEach (VM233607 lodash.js:9411)
    at Webform.eachComponent (VM234354 NestedComponent.js:326)
    at Webform.get (VM234449 Webform.js:1058)
    at ColumnsComponent.init (VM234373 Columns.js:172)
```

It seems like the Tabs are being recreated when Columns create triggers get schema on of tabs that are not fully created (the last tab is missing in the this.tabs array)

The strange part is this error occurs locally even when form is created with version 4.13.8 while in sandbox it works if the forms is loaded directly with version 4.13.8.

## Example (video)

https://user-images.githubusercontent.com/9924769/137994341-1f34d806-be6e-439f-863c-9e17bc56e081.mp4

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
