### ISSUE TITLE
[QUESTION] - How to use Premium Components locally?

### ISSUE THREAD

**Issue by kkaragki** [formio/formio.js#4407]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Formio.js version: 4.13.8
- Frontend framework: JS
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Load a form with a `datasource` component

## Expected behavior
The datasource component will be rendered

## Observed behavior
An error message is shown: `"Unknown component: datasource"`

## Question
I'm trying to find a way to add the specific _Premium Component_ to my project. I came accross to [this](https://github.com/formio/formio.js/issues/2482) question and I would like additional explanation.

I created an online form in Form.IO (trial version) and I added a `Data Source` _Premium Component_. Then, I took the public URL and tried to load this form to my local project for my company, but the `Data Source` never rendered either on my local Form Builder or my local Form Viewer / Filler.
If we pay for a **Teams Pro (100$ / month)** package, will we be able (and how) to use and render these _Premium Components_ within our local project on our local Form Builder & Form Viewer / Filler?

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
