### ISSUE TITLE
[Question]Custom Conditional on Dropdown Select item

### ISSUE THREAD

**Issue by CWD12345** [formio/formio.js#4410]
Hi,

I am creating a form that opens hidden fieldsets when the correct dropdown selection is selected.  I can get it to hide using simple custom javascript.  However, I have tried for quite some time now using many different methods to get it to open the hidden fieldset with no success.  The dropdown, how many children are you registering, has 6 options, 1-6.The "Clubber 2" fieldset should bet set to show or hidden = false when the 2 children registered select value is chosen.  The custom conditional javascript is being written on the "Clubber 2" fieldset itself.
![Screenshot (94)](https://user-images.githubusercontent.com/92949438/138353102-59d1a793-d4c9-4d46-bfb4-1d99d059e1df.png)
![Screenshot (95)](https://user-images.githubusercontent.com/92949438/138353107-78be9c0c-6480-40c9-b89e-7d9dcc065a54.png)
![Screenshot (96)](https://user-images.githubusercontent.com/92949438/138353108-d6b67129-570d-496a-b26f-f2bf310c952f.png)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
