### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'requireLibrary') 

### ISSUE THREAD

**Issue by j-perl** [formio/formio.js#4416]
We recently updated our formiojs dependency from 4.11.3 to 4.13.8 and we were greeted with this error:

`TypeError: Cannot read properties of undefined (reading 'requireLibrary')
    at new GoogleAddressProvider (http://localhost:3000/_snowpack/pkg/formiojs.js:2108:21)`

The incriminated line:

`_Formio.default.requireLibrary(_this.getLibraryName(), 'google.maps.places', src);`

I dug a little further and seem to have found the cause of the problem (circular dependency): the Formio file depends on Providers but one of the provider (GoogleAddressProvider) also depends on Formio. The provider gets imported first and this line resolves to undefined: `import Formio from '../../Formio';` and won't ever change. The dependency on Formio in GoogleAddressProvider wasn't there with the 4.11.3 version, so that explains why we didn't have this bug before.

Is this a known bug? The 4.13.8 version seems to be the latest stable release.

**Comment by j-perl** [comment]
It seems that there was an attempt at fixing it in this commit [https://github.com/formio/formio.js/commit/e47b6a4c1c823eeb4ccc5eba31dbd7ba5634bec7](e47b6a4). However, this change wasn't added yet in the latest stable release. The commit was in a release candidate (4.14.0-rc.32). Why didn't it make it to a stable version?

**Comment by wag110894** [comment]
Hello @j-perl,

We are still working on 4.14.0 build as it is not ready yet to be a stable version.

**Comment by j-perl** [comment]
Hi @wag110894. Oh I see, thank you. I was confused as there is already a v5 tag so I thought v4.14 was dropped and this would be the next release. Any chance we're going to see a release soon? Let me know if I can help.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
