### ISSUE TITLE
[BUG] Wordcount not counting newline as a separator

### ISSUE THREAD

**Issue by HundredBeans** [formio/formio.js#4422]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser: Chrome
- Browser version: 95.0.4638.54

## Steps to Reproduce
1. Go to https://formio.github.io/formio.js/app/builder
2. Drag and drop Text Area Component
3. Go to Editor dropdown, and select either CKEditor or QUILL
4. Go to the Show Word Counter checkbox, and check it
5. Try writing and add newline as separator instead of space
6. See the word count

## Expected behavior
The word count will count the newline as a separator. So when I type
```text
This
is
four
words
```
It will count as 4 words

## Observed behavior
When I type
```text
This
is
four
words
```
it only counts as 1 word

## Example
Expected behavior using basic Text Area component
![image](https://user-images.githubusercontent.com/57991340/139188364-d4512eba-c2d2-488c-a3b5-5dcf7379da15.png)

Observed behavior using CKEditor component
![image](https://user-images.githubusercontent.com/57991340/139188469-19d31b1b-22f4-4a4b-8ab3-bf864a2c2bd8.png)

Observed behavior using QUILL component
![image](https://user-images.githubusercontent.com/57991340/139188541-7bf96dd8-62ae-4e92-8c8a-c3296be37009.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
