### ISSUE TITLE
[FEATURE REQUEST] New conditional form for conditional selects

### ISSUE THREAD

**Issue by vodickavaclav** [formio/formio.js#4425]
Hi,

we would like to set visibility conditions for every option in the select or selectbox component. This should help us to make conditional selects which can be currently done only with URL or Resource data type.  

There are two problems:
1. Neither URL nor Resource data type is supported in selectbox component.
2. You need to use javascript or JSONLogic to specify conditional select if you choose "Values" data source type.

It would be great if the visibility conditions could be applied to every option in the select when the data source type "Values" is defined. Something like a new conditional form would be able to solve that. See the form for one select option on the picture below:
![image](https://user-images.githubusercontent.com/11456989/139428735-854805de-8815-4622-9364-70eee840f0eb.png)

**Comment by vodickavaclav** [comment]
I have found that new conditions settings are in FormioJs v5.

**Comment by PhilCliv** [comment]
I could not find any references to FormioJs v5 in this github. Any idea? Thanks
