### ISSUE TITLE
[BUG] Strings containing HTML elements are not translated

### ISSUE THREAD

**Issue by PranapSivadasan** [formio/formio.js#4431]
## Environment

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: Latest
- Frontend framework: Angular

## Steps to Reproduce
1.  Setup form builder along with Localization.
2.  Select any language other than English (For Example : French).
3. Drag and drop the Text Field and Hover over the tool tip of Input Mask field.
4. The String in the tool tip is not translated.

Note: The tool tip string is localized and properly added to the i18n.

## Expected behavior
The string in the tool tip must be translated.

## Observed behavior
The string is not translated. 

## Example

This is the [permalink](https://github.com/formio/formio.js/blob/5313922a0d9a398afcb06b26301c830d66d964a2/src/components/textfield/editForm/TextField.edit.display.js#L71) of formio code.

Similar to this component other components containing the HTML elements are also not translated even after localization.

Attached an example below.

In this example the Text Field is Localized in French language. The strings are properly translated but the tool tip containing the HTML elements is not translated.

![image](https://user-images.githubusercontent.com/44242289/139840029-04c6da92-51c6-4039-b4a5-c8e6092e6b4a.png)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
