### ISSUE TITLE
[BUG] Downloading using the File component set to Custom URL requires the endpoint to be open

### ISSUE THREAD

**Issue by Rick-Ritense** [formio/formio.js#4438]
## Environment
Downloading using the File component, set to Custom URL,  requires the endpoint to be open.

We have a FormIO File component in use set to the Custom URL. This URL points to an endpoint of an application set up using Spring Boot. This endpoint has to be set to `permitAll()` in the `HttpSecurityConfigurer`.

We rather have this endpoind closed by setting it to `hasAuthority(USER)`, but the file will not download with this setting. Using permitAll() does download the file.

It looks like formio doesn't set the correct http headers when a file download is requested

When POST and DELETE requests are used the application has no problem with closed endpoints

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 
- Frontend framework: Angular
- Backend framework: Spring boot
- Browser: Chrome
- Browser version: 95.0.4638.69

## Steps to Reproduce
1. Setup a Spring Boot application and create an endpoint for the file download.
2. Close the GET endpoint using a hasAuthority(USER)
2. Setup a form using a File component. Set this component to Custom URL and point it to a REST endpoint in Spring boot
2. Use the form and upload a file
3. Try to download the uploaded file

## Expected behavior
The file opens in a new browser tab

## Observed behavior
The new browser tab shows an error and the file is not downloaded

## Example
![formio-bug](https://user-images.githubusercontent.com/86724253/140289460-46727eea-9672-4a39-908c-d5934842815e.png)

![formio-bug-browser-error](https://user-images.githubusercontent.com/86724253/140289477-221e1ae7-d619-46e5-91b0-60dad5ec3a32.png)

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
