### ISSUE TITLE
[Question] Button with "Custom Event" doesn't fire in form readonly mode

### ISSUE THREAD

**Issue by sdebuggalo** [formio/formio.js#4448]
Hi
i have put some "logic" into a button to enable it even if the form is in readOnly mode, because i need to dispatch a "custom event" in every sistuation, to show a dialog.

I have declared it with
"action": "event",
"event": "myEvent"

In formiojs v3.20.x it did works, in formiojs v4.13.8 (and later)  it has stopped work.
Hi, i don't know if it is a bug or if it's done on purpose, so i'm asking it without opening as a bug for now.

Thank you for the attention.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
