### ISSUE TITLE
Formiojs + Flatpickr keyboard navigation issue

### ISSUE THREAD

**Issue by iPhobb** [formio/formio.js#4449]
Formiojs + Flatpickr keyboard navigation issue.

Flatpickr supports keyboard navigation itself.

Keyboard navigation is missed in case if Flatpickr is used from Formiojs forms based on json. 

[Link to codepen.io](https://codepen.io/bogdanshyl/pen/QWMxeez)

Steps to reproduce:
Press Tab to focus on input and get datepicker dropdown.
Try to navigate between dates with ArrowUp, ArrowDown, ArrowLeft, ArrowRight.

Environment details:
Formiojs 4.11.0
Flatpickr 4.6.3
Google Chrome 95.0.4638.69
Windows 10 Pro

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
