### ISSUE TITLE
Select Component Interpolation

### ISSUE THREAD

**Issue by josecristhian** [formio/formio.js#4463]
Select component with resource type in the template item is not working with two interpolations:

<span>{{ item.data.textField }} {{item.data.textField1}}</span>

4.14.0-rc.28 => Does not work
https://jsfiddle.net/josecristhian/jo72rgaw/6/

4.14.0-rc.27 => Works
https://jsfiddle.net/josecristhian/cqbdkuza/2/

{
  "label": "Select",
  "widget": "choicesjs",
  "tableView": true,
  "dataSrc": "resource",
  "data": {
    "resource": "6196891303607508f5c67c81"
  },
  "template": "<span>{{ item.data.textField }} - {{ item.data.textField1 }}</span>",
  "key": "select",
  "type": "select",
  "input": true,
  "addResource": false,
  "reference": false
}

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
