### ISSUE TITLE
[BUG] Label should be rendered as it appears in form definition when translation is missing for selected language

### ISSUE THREAD

**Issue by akgagnat** [formio/formio.js#4465]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.13.10
- Frontend framework: 

## Steps to Reproduce
1. Create form definition containing texts in other language than english ('nb-NO' in fiddle, see example below)
2. Render form and provide options where `language` set to language used in form definition, and `i18n` contains english translation along with default translations (validations, buttons etc.) for other language.

## Expected behavior
Rendered label to be equal to label in form definition

## Observed behavior
Rendered label is equal to the english translation

## Example
https://jsfiddle.net/akgagnat/7xfhv41d/13/

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
