### ISSUE TITLE
Number test fails if browser is in french

### ISSUE THREAD

**Issue by turtledev1** [formio/formio.js#447]
I just changed all my settings in french because there is a law in Quebec that states that our computers must be in french, and now one of Formio tests fails.

This is the test:
Chrome 66.0.3359 (Windows 10.0.0) Number Component Should limit decimals using step FAILED
        Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

I checked and it is related to thousandsSeparator. The test suppose it will be ',' when for me it is ' '

The component.inputs[index].value is '123 456 789,123' and the visible is '123,456,789.123'

**Comment by tchab2** [comment]
This bug is not already fixed!!

Is it possible to advice??

Best regards,

**Comment by jhen1422** [comment]
Closing - outdated issue
Please open a new issue if this is still outstanding on our 4x renderer or contact support@form.io
