### ISSUE TITLE
[BUG] [Columns] [formbuilder]:  TypeError: Cannot read properties of undefined (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by JanSatnik** [formio/formio.js#4472]
## Environment
https://formio.github.io/formio.js/app/builder
Also in my implementation. 

- Formio.js version: 4.13.10
- Frontend framework: Angular
- Browser: chrome
- Browser version: 93.0.4577.82

## Steps to Reproduce
1. Open formBuilder
2. Add column field
3. Click on button "add column"

enviroment : https://formio.github.io/formio.js/app/builder

https://user-images.githubusercontent.com/56277503/144593065-0037bd64-067c-405e-b62d-f10aa0b4b681.mp4

 
enviroment: my implementation
![Screenshot from 2021-11-26 10-46-31](https://user-images.githubusercontent.com/56277503/143561082-89f45c27-fb9c-483f-8436-3e18be95dc52.png)

```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
