### ISSUE TITLE
[QUESTION]  The request for a view (html rendering) always return "Invalid Alias" 

### ISSUE THREAD

**Issue by p4535992** [formio/formio.js#4473]
## Environment

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 2.3.0 (the docker build)
- Formio.js version: 4.13.10
- Frontend framework: javascript and third libraries like jquery
- Browser: Chrome
- Browser version:  95.0.4638.69 (Build ufficiale) (a 64 bit)

## Steps to Reproduce
1. Prepare this piece of code on my index.html
```javascript

		  function createForm(data) {
		    const urlsubmission = data.urlsubmission; // https://myserverdocker/formio/wizard/submission/5a542c9e2a40bf0001e0f8a9
		    const token = data.token;
		    const baseurl = data.baseurl; // https://myserverdocker/formio
		    // Formio.setProjectUrl(); // https://myserverdocker/formio/adapter
		    Formio.setBaseUrl(baseurl); // https://myserverdocker/formio
			Formio.setToken(token); // my token
			Formio.createForm(document.getElementById('formio'), urlsubmission, {
			  readOnly: true,
			  renderMode: 'html'
			});
			// 'https://examples.form.io/wizard/submission/5a542c9e2a40bf0001e0f8a9'
			/*
			let formio = new Formio(urlsubmission);
			formio.loadForm()
			.then(function(form) {
			  form.display = 'form';
			  Formio.icons = 'fontawesome';
			  Formio.createForm(document.getElementById('formio'), form, {
			    readOnly: true,
			    renderMode: 'html'
			  }).then(function(instance) {
			    formio.loadSubmission().then(function(submission) {
			      instance.submission = submission;
			      
			    });
			  });
			});
			*/
		}
		
		$.getJSON(window.origin + "/myservice", function(data) {
			console.log("Loaded details");
			return data;
        })
        .then(createForm)
        .fail(function(e){
        	console.error("An error has occurred:"+e);
        });
 }

```
2. I get the error "Invalid alias" when call the code 
 ```
Formio.createForm(document.getElementById('formio'), urlsubmission, {
	readOnly: true,
	renderMode: 'html'
});
 ```
## Expected behavior

Obtain the rendered view of the submission or at least a non error response 

## Observed behavior

The "edit" of the form is working fine with a similar code, so i'm confident is some error on the use of the Formio. js library instead of a bug.

## Example

Here the file html i'm trying to make it work:
[form-view2.html.txt](https://github.com/formio/formio.js/files/7609417/form-view2.html.txt)

renamed with ".txt" the html file for limitation of the github.

**Comment by p4535992** [comment]
sorry to bother any news on this ?

**Comment by p4535992** [comment]
sorry to bother again, any news on this ?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
