### ISSUE TITLE
[Question] Native browser date input

### ISSUE THREAD

**Issue by Brianmantay** [formio/formio.js#4474]
Hi is it possible to use a native browser date input in form.io? i.e. <input type='date' />
I'm using the native browser date picker in other non-formio parts of my app and want a consistent experience.
I've tried setting the type attribute via the text input custom attributes etc but nothing seem to work. Is there any way to achieve this? Many thanks!

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
