### ISSUE TITLE
[BUG] FileType in file submit "label" instead "value"

### ISSUE THREAD

**Issue by scope-li** [formio/formio.js#4475]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [] Local deployment
    - Version: Only formio-js without server
- Formio.js version: 4.13.9
- Frontend framework: Webpack
- Browser: any
- Browser version: any

## Steps to Reproduce
1. Create a fiel input
2. Define some fileTypes
3. "label" instead of "value" is in submission

## Expected behavior
The "value" of the selected fileType is submitted.

## Observed behavior
The "label" of the selected fileType is submitted.
Thats really bad, for some reason you have to define a "value"

## Example
https://jsfiddle.net/b0fejphc/ it's not from me, but it demonstrates the problem perfectly.
![image](https://user-images.githubusercontent.com/46850657/143845220-1de6180d-e140-4588-84f5-7edfc4a1131c.png)

https://github.com/formio/formio.js/commit/4dce3d037498f373cf98f75102db18dabb9510f1#diff-88fcc2d2f31515efb91047d6564cc78e83922d7d795e776c2523d7c94f844e6dR435
I think, this change broken it. 

A label can change every time (e.g. translation), so you have a "value".

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
