### ISSUE TITLE
[Question] How can I mask the first 6 digits of an input field

### ISSUE THREAD

**Issue by haarismian** [formio/formio.js#4478]
I want to create an input field that does the following two tasks:

1. On blur I want it to mask the first 6 characters with a *. So the user types 123456789, and on blur it would appear as ******789, however on submission I still get the full data 123456789

Sorry I know this isnt a bug but I dont know how to change the label.
Thanks!

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
