### ISSUE TITLE
[BUG] [FormBuilder] [Table + quill] - overflow issue

### ISSUE THREAD

**Issue by JanSatnik** [formio/formio.js#4484]
Environment
https://formio.github.io/formio.js/app/builder

Frontend framework: Angular
Browser: chrome
Browser version: 93.0.4577.82

Steps to Reproduce
- Open formBuilder
- Add table field
- Add textfield (quill) editor
- Type long word

Demo:

https://user-images.githubusercontent.com/56277503/144592505-dd87ffff-563d-402d-8b9e-aa3c7644f065.mp4

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
