### ISSUE TITLE
[BUG] Select inside Data Grid always repopulates default values (when empty)

### ISSUE THREAD

**Issue by ak99372** [formio/formio.js#4490]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
- Formio.js version: 4.13.7
- Frontend framework: angular
- Browser: Chrome
- Browser version: 96.0

## Steps to Reproduce
1. Create Data Grid 
2. Add Select component with list of values and
   - multi-select 
   - set some as default values
3. Create submission and add couple rows to grid 
   - default values will be populated in select column
   - Save
4. Edit submission and remove all selection from one of the Select rows 
  - Save
5. Reload/refresh submission 
  - notice the row that was manually set to be empty now has default values instead

## Expected behavior
When user manually clears default values in [Select] component the selection remains cleared on reload 
(this is how Select behaves when placed directly on the form)

## Observed behavior
**NOTE this happens only inside Edit-Grid!** 
When user manually clears default values in [Select] component after refresh default values are displayed instead

It seems like Edit-Grid can't differentiate between new row and existing row.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
