### ISSUE TITLE
[BUG] [Panel] Empty title do not work properly in renderer.

### ISSUE THREAD

**Issue by JanSatnik** [formio/formio.js#4491]
## Environment
https://formio.github.io/angular-demo/#/forms/builder

## Steps to Reproduce
1. Add panel to the builder
2. Clear title field
3. In renderer, title value is still display in label.

## Expected behavior
I expect label without title

## Example

https://user-images.githubusercontent.com/56277503/144986342-45c87589-0cee-4c03-9401-4fda557e0c20.mp4

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
