### ISSUE TITLE
[BUG] using custom flatpicker does not work with datetime component

### ISSUE THREAD

**Issue by danielzzz** [formio/formio.js#4498]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework: vanilla js (within laravel mix)
- Browser: chrome
- Browser version: 96.0.4664.45 (Official Build) snap (64-bit)

## Steps to Reproduce
```
require('formiojs');
require('flatpickr');
const { German } = require('flatpickr/dist/l10n/de.js');
```
## Expected behavior
I should be able to localize flatpicker
## Observed behavior

If I require custom flatpicker the datatime component stops working altogether

**Comment by AlexByte** [comment]
add
```
    <script src="https://cdn.form.io/flatpickr/flatpickr.min.js"></script>
    <link rel="stylesheet" href="https://cdn.form.io/flatpickr/flatpickr.min.css">
     <script src="https://npmcdn.com/flatpickr/dist/l10n/ar.js"></script>

```
then use this method to localize flatpickr before `Formio.createForm`
`flatpickr.localize(flatpickr.l10ns.ar);`

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
