### ISSUE TITLE
[BUG] Cannot set start day of week for date input

### ISSUE THREAD

**Issue by hisuwh** [formio/formio.js#4499]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: n/a
- Frontend framework: n/a
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. View the docs: https://help.form.io/userguide/forms/form-components#date-time
2. Note how docs state there is an option for starting day:
  ![image](https://user-images.githubusercontent.com/4470351/145808589-97556110-0ece-47c3-8362-9d9a1b6f5c9e.png)
3. Visit the sandbox and add a date/time to a form: https://formio.github.io/formio.js/app/sandbox

## Expected behavior
It should show option to set Starting Day of the week as per the docs

## Observed behavior
It does not show the starting day option:
![image](https://user-images.githubusercontent.com/4470351/145808707-d79422bd-9e64-4e58-b214-0646dd5c1018.png)

## Example
https://formio.github.io/formio.js/app/sandbox

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
