### ISSUE TITLE
unable to open/close the field accordion after search the field in "Search Field" input box

### ISSUE THREAD

**Issue by jcsofts** [formio/formio.js#4514]
Formio: 4.14.0

I pass the options when show the builder

1.  Enter some thing in the "Search Field" input box. 
2.  Clean the "Search Field" .
3. the according will can be unable to open/close

this is the example with the bug
https://jsfiddle.net/9e7s1hvx/3/

**Comment by aln447** [comment]
Connected to https://github.com/formio/formio.js/issues/3278

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
