### ISSUE TITLE
[BUG] formio.setSubmission({...}) does not set custom components submission data.

### ISSUE THREAD

**Issue by CatBakun** [formio/formio.js#4515]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest (4.13.11)
- Frontend framework: Default/VanillaJS
- Browser: Any
- Browser version: Any

## Steps to Reproduce
1. Create a form with a custom component along with Formio default components.
2. Set the form submission with submission data for all components (custom and defaults)

## Expected behavior
The custom component can render the whole submission data values set in step 2.

## Observed behavior
The custom component key/value pair in the submission data gets lost somewhere.

## Example
http://jsfiddle.net/07cn3fer/

**Comment by Alexa-Green** [comment]
@CatBakun Did you ever find a fix for this? Experiencing the same thing

**Comment by henriquesoareslima** [comment]
@Alexa-Green, @CatBakun. I'm with the same issue. Any solutions?

**Comment by Alexa-Green** [comment]
@henriquesoareslima Implemented a local saving of the custom component details in state if I remember correctly, then re-injected that for handling the final submission. Not ideal or that dynamic, but it is a workaround.

**Comment by henriquesoareslima** [comment]
Thanks @Alexa-Green. It's cool. I implemented different. I set the component value in the dataset tag and put that in the application. This is also not ideal.

**Comment by Sidiro23** [comment]
Thank you for reporting this issue. I am able to reproduce and have logged a ticket for the backlog. We are always willing to review any contributions to resolve this issue from the open source community.

For internal reference: FIO-8642

**Comment by lane-formio** [comment]
<div>Agent Lane Doughtie linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/45962">45962</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
If you are expecting a string, have you tried just extending the text field component?

**Comment by henriquesoareslima** [comment]
In my case, I didn’t use the text field component. Instead, I created a custom component where the user selects a response value by clicking a button. On click, I passed the value using the super.setValue(value, flags) method, but it didn’t work. So, I started assigning the value to a dataset tag instead.
