### ISSUE TITLE
[QUESTION] How can I set up the dynamic development environment?

### ISSUE THREAD

**Issue by oguzhanbolme** [formio/formio.js#4528]
I want to develop the dist file dynamically instead of constantly building it. I tried to catch the changes in the lib folder using webpack, but I couldn't. How can I set up a development environment in a practical way? Can you explain in detail?

**Comment by oguzhanbolme** [comment]
Long live webpack. I solved.

**Comment by ajhalls** [comment]
Sounds nice, care to share the solution?

**Comment by oguzhanbolme** [comment]
> 
I solved it with webpack If I need to give an example for the solution, you can look at my forked repository. You can check this link: https://github.com/oguzhanbolme/formio.js/tree/master/dev-workspace

**Comment by oguzhanbolme** [comment]
> Sounds nice, care to share the solution?

I solved it with webpack If I need to give an example for the solution, you can look at my forked repository. You can check this link: https://github.com/oguzhanbolme/formio.js/tree/master/dev-workspace

**Comment by michelveloso** [comment]
@oguzhanbolme saved my day!!
