### ISSUE TITLE
Example for Builder to be embedded in plain HTML, throws Formio.builder not available

### ISSUE THREAD

**Issue by sunshinesanty** [formio/formio.js#453]
Latest updates with example to allow Form Builder to be embedded is not working.
'Formio.builder' object is returned as null

![formiobuilderissue](https://user-images.githubusercontent.com/10233469/39962370-d9043f2c-568f-11e8-8437-8ca64e6f244b.png)

Tried this on the [JS Fiddle link](http://jsfiddle.net/v38du9y1/322/) as well.

Looks like the formio.builder.(js|css|min files) are all missing in the build.

**Comment by sakshammufc99** [comment]
Yes,I am facing the same issue. Formio.builder is not working.

**Comment by travist** [comment]
Here is a JSFiddle that shows how it works.

https://jsfiddle.net/travistidwell/zs3sntyv/1/

**Comment by sakshammufc99** [comment]
Thanks travis

**Comment by sunshinesanty** [comment]
Was refering to the 2.0.0_aplha.9 version. Got the correct version now.
Thank you Travis
