### ISSUE TITLE
Basic example accesses https://api.form.io/form/false/action

### ISSUE THREAD

**Issue by ajhalls** [formio/formio.js#4531]
This could just be me, but when I did the most basic example:
```
<html>
  <head>
    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
    <script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
    <script type='text/javascript'>
      window.onload = function() {
        Formio.builder(document.getElementById('builder'), {}, {});
      };
    </script>
  </head>
  <body>
    <div id='builder'></div>
  </body>
</html>
```

I see in the network activity that I am accessing `https://api.form.io/form/false/action` with an XHR GET request, which returns "Invalid Alias". 

I can see that the request headers are empty, so it doesn't look like it actually IS spying on me, but it does feel invasive. I am looking at building new patient forms, which will need to be secure, and so to have the very first thing I see when doing a basic example be the potential for the app to be sending out data doesn't inspire the confidence of security. 

Of course I know it is open source, so I can disable it, but what other unknown tasks may be being performed in the background that I may miss?

Just thought I would pass along my first impression. Actually, this was my second impression, the first was excitement for what a great project it was.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
