### ISSUE TITLE
DateTime Component is reset at focusOut()

### ISSUE THREAD

**Issue by viorelhojda** [formio/formio.js#4540]
I have a simple DateComponent in a grid, the issue is that after I set a date in it whenever I click outside of the input (basically the focus is lost) the date from it is reset to the current date. So......the selected date is not saved.

Step1. Select date
![image](https://user-images.githubusercontent.com/64518064/149893528-1d2ce3af-032b-43af-b722-009a554b70ce.png)

Step2.Date is set
![image](https://user-images.githubusercontent.com/64518064/149893574-c7913363-34cd-41f4-8154-699081928457.png)

Step3.Focus lost-> date lost
![image](https://user-images.githubusercontent.com/64518064/149893629-22b44f85-a372-4057-94d0-a2b763951801.png)

I have no errors in the console or anything like that.

Please help :) !

The formIo JSON:
{
  "display": "form",
  "settings": {
    "pdf": {
      "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
      "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
    }
  },
  "components": [
    {
      "label": "flowStep",
      "defaultValue": "1",
      "key": "flowStep",
      "type": "hidden",
      "input": true,
      "tableView": false
    },
    {
      "label": "header",
      "tag": "h1",
      "attrs": [
        {
          "attr": "",
          "value": ""
        }
      ],
      "content": "Administratori",
      "refreshOnChange": false,
      "key": "html",
      "type": "htmlelement",
      "input": false,
      "tableView": false,
      "hideOnChildrenHidden": false
    },
    {
      "label": "Te rugǎm sa introduci date legate de administratori",
      "reorder": false,
      "addAnotherPosition": "bottom",
      "layoutFixed": false,
      "enableRowGroups": false,
      "initEmpty": false,
      "tableView": false,
      "validate": {
        "required": true
      },
      "key": "administrators",
      "type": "datagrid",
      "input": true,
      "components": [
        {
          "label": "Container",
          "tableView": false,
          "key": "container",
          "type": "container",
          "input": true,
          "components": [
            {
              "label": "Nume/prenume",
              "labelPosition": "left-left",
              "placeholder": "Nume şi prenume",
              "tableView": true,
              "validate": {
                "required": true,
                "minLength": 2,
                "maxLength": 50
              },
              "key": "name",
              "type": "textfield",
              "input": true
            },
            {
              "label": "CNP",
              "labelPosition": "left-left",
              "placeholder": "Codul numeric personal",
              "tableView": true,
              "validate": {
                "required": true,
                "pattern": "^[1-9]\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])(0[1-9]|[1-4]\\d|5[0-2]|99)(00[1-9]|0[1-9]\\d|[1-9]\\d\\d)\\d$"
              },
              "errors": {
                "pattern": "Câmpul trebuie sa fie un CNP valid."
              },
              "key": "cnp",
              "type": "textfield",
              "input": true
            },
            {
              "label": "Telefon",
              "labelPosition": "left-left",
              "placeholder": "Numărul de telefon",
              "tableView": true,
              "validate": {
                "required": true,
                "minLength": 4,
                "maxLength": 20,
                "pattern": "^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\\s\\./0-9]*$"
              },
              "errors": {
                "pattern": "Câmpul trebuie sa reprezinte un numǎr de telefon valid."
              },
              "key": "phone",
              "type": "textfield",
              "input": true
            },
            {
              "label": "Email",
              "labelPosition": "left-left",
              "placeholder": "Adresa e-mail",
              "tableView": true,
              "validate": {
                "required": true,
                "pattern": "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"
              },
              "errors": {
                "pattern": "Câmpul trebuie sa reprezinte un e-mail valid."
              },
              "key": "email",
              "type": "textfield",
              "input": true
            },
            {
              "label": "Locul naşterii",
              "labelPosition": "left-left",
              "placeholder": "Locul naşterii",
              "tableView": true,
              "validate": {
                "required": true,
                "minLength": 2,
                "maxLength": 50
              },
              "errors": {
                "pattern": "Câmpul trebuie sa reprezinte un e-mail valid."
              },
              "key": "placeOfBirth",
              "type": "textfield",
              "input": true
            },
            {
              "label": "Data naşterii",
              "labelPosition": "left-left",
              "displayInTimezone": "location",
              "format": "dd-MM-yyyy",
              "placeholder": "Data naşterii",
              "tableView": false,
              "enableMinDateInput": false,
              "datePicker": {
                "disableWeekends": false,
                "disableWeekdays": false
              },
              "enableMaxDateInput": false,
              "enableTime": false,
              "validate": {
                "required": true
              },
              "key": "dateOfBirth",
              "type": "datetime",
              "timezone": "Europe/Bucharest",
              "input": true,
              "widget": {
                "type": "calendar",
                "timezone": "Europe/Bucharest",
                "displayInTimezone": "location",
                "locale": "en",
                "useLocaleSettings": false,
                "allowInput": true,
                "mode": "single",
                "enableTime": false,
                "noCalendar": false,
                "format": "dd-MM-yyyy",
                "hourIncrement": 1,
                "minuteIncrement": 1,
                "time_24hr": false,
                "minDate": null,
                "disableWeekends": false,
                "disableWeekdays": false,
                "maxDate": null
              }
            },
            {
              "label": "Adresǎ",
              "labelPosition": "left-left",
              "placeholder": "Adresa de corespondenţǎ",
              "autoExpand": false,
              "tableView": true,
              "validate": {
                "required": true,
                "minLength": 5,
                "maxLength": 250
              },
              "key": "address",
              "type": "textarea",
              "input": true
            },
            {
              "label": "Incarcǎ",
              "labelPosition": "left-left",
              "tableView": false,
              "storage": "base64",
              "image": true,
              "uploadOnly": true,
              "webcam": true,
              "fileTypes": [
                {
                  "label": "",
                  "value": ""
                }
              ],
              "fileMaxSize": "1MB",
              "key": "fileUpload",
              "type": "file",
              "options": {},
              "input": true
            }
          ]
        }
      ]
    },
    {
      "label": "Continuă",
      "customClass": "rounded-pill",
      "showValidations": false,
      "disableOnInvalid": true,
      "tableView": false,
      "key": "submit",
      "type": "button",
      "input": true,
      "hideOnChildrenHidden": false,
      "width": 6
    }
  ]
}

**Comment by rschaad** [comment]
Experiencing the same issue. Date goes back to 20.02.2022 after focusing out

**Comment by rschaad** [comment]
With the format yyyy-MM-dd it works as expected. I am using dd.MM.yyyy and it breaks

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
