### ISSUE TITLE
[BUG] Date/time component "Display In Timezone" of Submission does not work

### ISSUE THREAD

**Issue by APhanMonadel** [formio/formio.js#4549]
## Environment
[Formio Sandbox](https://formio.github.io/formio.js/app/sandbox) running Renderer v4.14.1-rc.7

- Hosting type
  - [x] Form.io
- Browser: Chrome & Firefox

## Steps to Reproduce
1. Open [Formio Sandbox](https://formio.github.io/formio.js/app/sandbox) 
2. Load the following submission Id: `61ebb363e24cfb05ec943a86`
3.  A form and response will be loaded. Please notice how the date/time component has the displayInTimezone setting set to "of Submission" however when you view the response it will show in the timezone of the viewer (your local time zone)

## Expected behavior
- When a date/time component is used and the "displayInTimeZone" setting is set to "of Submission" the date time rendered in the form should display in the timezone of the original submission or the time zone available in the metadata fields. At the moment it is displaying in the time zone of the viewer.

## Observed behavior
Even when the displayInTimezone setting is set to "Of Submission" the time zone is displayed in the time zone of the viewer. 
In the example I have submitted the form in my local time zone  (perth) however when I open the submission on a VM with a different time zone it shows in the local timezone (UTC). This can be see in the screen shot below
![image](https://user-images.githubusercontent.com/91739927/150630042-63b3e72d-e23f-4c64-bf85-53d59bf6fdb1.png)

## Example

https://formio.github.io/formio.js/app/sandbox

Please use the following sandbox id:
61ebb363e24cfb05ec943a86

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
