### ISSUE TITLE
Rebuild formio.full.min.js with error $A is not defined

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#4550]
Hello Support,

I have downloaded and deployed the npm version (https://www.npmjs.com/package/formiojs)
When I rebuild the "formio.full.min.js" using the plain "npx webpack" I get a correct working script file but when I want to use it in Salesforce it does not comply with the Locker Service restriction.
The original "formio.full.min.js" however does comply.
So my question is: Do you build using a "webpack.config.js" and if you do can you fill me in with the configuration? Or perhaps you are using ESLint and can tell me about the ESLint configuration? 

Kind regards,
Mario

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
