### ISSUE TITLE
[BUG] When selecting 'Heading 1' in content component, In html the heading becomes <h2>

### ISSUE THREAD

**Issue by MasterMart** [formio/formio.js#4553]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.13.5
- Frontend framework: Angular
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create a form with a content component. Select 'Heading 1' from the dropdown in the rich text editor. Add some arbitrary text.  
2.  Render the form in Angular and open the form in a browser. 
3.  Check the html source code of the page. 
4. Observe the <h2> around the arbitrary text you entered in step 1. 

## Expected behavior
When I select 'Heading 1' from the dropdown, the content component gets rendered with a <h1>. So forth for 'Heading 2', 'Heading 3', etc. 

## Observed behavior
'Heading 1' -> <h2>, 'Heading 2' -> <h3>, etc. 
See screenshots below

## Example
In editor:
<img width="858" alt="Screenshot 2022-01-25 at 11 52 06" src="https://user-images.githubusercontent.com/61278382/150963584-9a028499-fba8-4b67-82e1-e73d5e937a30.png">

Rendered in Angular:
<img width="823" alt="Screenshot 2022-01-25 at 11 52 21" src="https://user-images.githubusercontent.com/61278382/150963592-c4307af1-b7c9-4196-b862-572ba7f82645.png">

**Comment by sdancer75** [comment]
The content component does not seem to work with the latest version (4.15.0-rc.12) of formiojs and react. It shows an empty area. Any recommendations? Does this version work fine with angular?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
