### ISSUE TITLE
[BUG] When including a panel with no default buttons in a wizard form, an empty <ul> is created in the html

### ISSUE THREAD

**Issue by MasterMart** [formio/formio.js#4554]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.13.5
- Frontend framework: Angular
- Browser: Chrome

## Steps to Reproduce
1. Create a wizard form with multiple pages. On the panel options, don't select any button beneath 'Panel Navigation Buttons'. 
2. Render your form in Angular and open it in a browser. 
3. Open the html, search for 'formio-wizard-nav-container'
3. Observe the empty html list

## Expected behavior
An html list always contains elements, this is according to https://www.w3.org/TR/wai-aria-1.1/#mustContain

## Observed behavior
The html list doesn't contain any elements.

## Example
<img width="693" alt="Screenshot 2022-01-25 at 15 42 48" src="https://user-images.githubusercontent.com/61278382/150998211-e85331e5-a22b-4603-8d3a-9d40b5256407.png">

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
