### ISSUE TITLE
[BUG] Cannot select file after a validation error

### ISSUE THREAD

**Issue by ps-ohanel** [formio/formio.js#4555]
## Environment
With the described Steps below, the Form.io File component gets into the state that does not allow any other interaction nor file selection.
The error occured in our own project, but can be reproduced as well on the official [formio example page](https://formio.github.io/formio.js/app/builder).

- Hosting type
  - [x] Local deployment
- Formio.js version: 4.14.0
- Frontend framework: both Angular / vanilla JS
- Browser: Chrome
- Browser version: 97

## Steps to Reproduce
You can use the [official example](https://formio.github.io/formio.js/app/builder) of the builder.
1. Create/define a file component 
2. Set the File/Storage to Base64
3. Do NOT allow multiple file selection
3. Set some restriction (e.g. file type, file size, etc.)
4. Save the component and interact with it in a way:
5. Drag/drop some file that violates some of the restriction
6. Read the error and remove the wrongly selected file by clicking "x" button

## Expected behavior
- after the wrongly selected file and its removal, I expect that the user can select another file

## Observed behavior
- after the wrongly selected file and its removal, the drag/drop zone disappears as well as any other way how to actually select the file
- if the field is required, the user gets into the state where the form is not valid but there is no way how to proceed

## Example
Failing form JSON:

```js
{
    "display": "form",
    "components": [
        {
            "label": "Upload",
            "tableView": false,
            "storage": "base64",
            "webcam": false,
            "fileTypes": [
                {
                    "label": "",
                    "value": ""
                }
            ],
            "filePattern": "*.png",
            "key": "file",
            "type": "file",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by AlexByte** [comment]
confirm
![record_000004_Trim](https://user-images.githubusercontent.com/25251772/153401582-28c9e52b-005f-4f23-8ca6-2dee412a36fd.gif)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
