### ISSUE TITLE
File uploader inline styles violate strict Content Security Policies

### ISSUE THREAD

**Issue by sergei-maertens** [formio/formio.js#4570]
https://github.com/formio/formio.js/blob/78608aaa5eeeb68aba0094684a193a4fb483d851/src/components/file/File.js#L236 appears to be the culprit.

We have deployed a CSP which blocks `unsafe-inline` styles (and scripts, but that's not relevant). For file uploads, we see violations because the file upload progress indicator uses inline styles.

This would benefit from classnames and having the JS toggle the classnames + including the appropriate styles in the Formio stylesheets. I could work on a patch for this if this approach is accepted.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
