### ISSUE TITLE
Cannot add/drag new components to form builder when default form is set

### ISSUE THREAD

**Issue by alphazhe** [formio/formio.js#4571]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.13.12
- @formio/react version: 5.2.0
- Frontend framework: React
- Browser: Chrome
- Browser version: Latest

## Steps to Reproduce
Code -
```js
          import {FormBuilder} from '@formio/react';

          <FormBuilder
              form={{
                display: 'form',
                components: [
                  {
                    type: 'textfield',
                    key: 'firstName',
                    label: 'First Name',
                  },
                  {
                    type: 'textfield',
                    key: 'lastName',
                    label: 'Last Name',
                  },
                ],
              }}
              onChange={(schema: any) => console.log(schema.components)}
            />
```

1. The web builder shows first name and last name as default fields.
2. But when I am trying to drop new component, edit modal opens and but nothing happens on tapping on save, cancel or remove.
3. It does not even pre-render default component in builder paste area.

## Expected behavior
Adding new component should work, when default form components are provided.

Can someone please help me here?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
