### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MasterMart** [formio/formio.js#4577]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.13.5
- Frontend framework: Angular
- Browser: Chrome

## Steps to Reproduce
1.  Create a form with a datagrid in a container. Add some text fields in the datagrid. 
2. Copy the container. 
3.  Create a new form and use 'paste below' to paste the copied container in the new form.
4. Change the property name under 'api' for one of the text fields. Save the new form.
5. Open the new form in an Angular frontend. Submit the form and check the submission object of form.io
6. Observe that the submission still holds the old name (within the container -> datagrid) for the text field of which you just changed the property name. 

## Expected behavior
Property names stay the same, even though you change them in the form builder. 

## Observed behavior
Property names change accordingly.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
