### ISSUE TITLE
Cascading select components inside Data grid component does not work as expected

### ISSUE THREAD

**Issue by asalhani** [formio/formio.js#459]
@travist @AlameerDev
@travist : I need your kind support to investigate on the following case.
Note: Since the prerequisite to reproduce the case is to have a resource control, therefore I've uploaded a dump of [formioapp] MongoDB. Just restore it in your environment and you are ready to go.

Steps:
1- Create new form
2- Add data grid component
3- Inside data grid, add a column component to split the grid into 2 half.
4- In the 1st half, add new select component and set data property to be from resources
5- In the 2nd half, add another select component, set data to a resource, and filter data based on data selected from step (4). To create a cascading select components, I've followed the steps [here](https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/).
6- save the form
7- Open the created form in submission mode to submit new instance.
8- Select a value from 1st select component
9- The 2nd select control should display a filtered data based on selection from previous step. Chose a value.
10- Click "Add another" button
11- In the new added row, select a value from the 1st select component.
12- **Now , if you tried to select a value from 2nd select component, you will notice that component did not have any value to select from. In another word, the 2nd select component didn't notice that there was a selection. The behavior I was expecting  will be the same as in step (9)**

I will attach here a dump of [formiojs] MonogoDB along with a file which contains form schema described above to generate issue.

Also I've attached a gif file to quickly review what I was trying to describe
![grid issue](https://user-images.githubusercontent.com/5410830/40000704-230ad878-5795-11e8-8fb4-4fa21882120e.gif)

I hope that my explanation was clear enough.

[formioapp.zip](https://github.com/formio/formio.js/files/2000895/formioapp.zip)

**Comment by asalhani** [comment]
@travist @Vercjames @YuryRybakSoftensity @randallknutson
Any update on this issue?

Much appreciated...

**Comment by asalhani** [comment]
@jhen1422  @travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update so far?

**Comment by jhen1422** [comment]
Closing - outdated issue
Please open a new issue if this is still outstanding on our 4x renderer or contact support@form.io

**Comment by dipakveer** [comment]
I was facing same issue,but i resolved it.
![Screenshot (242)](https://user-images.githubusercontent.com/40272020/174722427-966bb295-4677-40b5-8aa9-f59d3a096d51.png)
![Screenshot (243)](https://user-images.githubusercontent.com/40272020/174722462-2cc557d6-cdf5-41b3-9cff-71f599c88b47.png)
(master=>resource and skillset is properties of 1st dropdown)
