### ISSUE TITLE
[BUG] Set 'validate.onlyAvailableItems' default value to true should work in editForm

### ISSUE THREAD

**Issue by ollybondareva** [formio/formio.js#4592]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
- Formio.js version: 4.13.8
- Browser: Google Chrome
- Browser version: Version 98.0.4758.80 (Official Build) (x86_64)

## Steps to Reproduce
I'm trying to override some editForm components on validation tab for Select. I have my custom select which extends formio Select. Then I'm trying to override default value of 'validate.onlyAvailableItems' in my custom editForm.

<img width="1210" alt="Screen Shot 2022-02-14 at 23 29 31" src="https://user-images.githubusercontent.com/15728593/153941667-0ec09119-c868-461e-b331-e710558e498a.png">

In my formEdit I'm merging Select.edit.validation and my custom validation, which is intended to override the default value of  'validate.onlyAvailableItems', but it doesn't work:
```
export const validation = [
    {
        weight: 52,
        type: 'checkbox',
        label: 'Allow only available values',
        tooltip:
            'Check this if you would like to perform a validation check to ensure the selected value is an available option.',
        key: 'validate.onlyAvailableItems',
        input: true,
        defaultValue: true,
    },
]
```
I've also tried with other options like 'validate.required', 'unique' and it doesn't work. Seems there is some problems with ovveriding default value for checkbox type.

## Expected behavior
Set 'validate.onlyAvailableItems' default value to true should work in editForm

## Observed behavior
Set 'validate.onlyAvailableItems' default value to true doesn't work in editForm

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
