### ISSUE TITLE
[BUG] fields fail validation silently unless changed/blurred

### ISSUE THREAD

**Issue by danielzzz** [formio/formio.js#4596]
## Environment
Please provide as many details as you can:
when I press submit I would expect the form to show all the errors in all fields.
but these messages seem to be shown only after the user changed/blurred the field.

this sometimes is confusing for users, as on bigger forms it's hard to spot which field has some validation problems.

thanks, best, dan

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: https://cdn.form.io/formiojs/formio.full.min.js
- Frontend framework: vanilla js
- Browser: chrome
- Browser version: 98.0.4758.80 (Official Build) snap (64-bit) 

## Steps to Reproduce
![formio](https://user-images.githubusercontent.com/351916/154247752-dca20f81-4422-4a49-a01b-5f561e685263.gif)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution
