### ISSUE TITLE
[QUESTION] r.message.replace is not a function when using the File upload component

### ISSUE THREAD

**Issue by pimduijst** [formio/formio.js#4605]
Hello,

I am implementing the Open Source version which works fine as far as I can see for now but I am having issues with the File component.

I am using the Laravel-framework which expects a valid CSRF-token on every request done within the application. So I have send the csrf-token in the headers as in the screenshot can be seen. But now I get the message as mentioned in the subject. Can someobody help me out?

<img width="1418" alt="Screenshot 2022-02-19 at 12 54 44" src="https://user-images.githubusercontent.com/1483463/154799669-06a00a81-0a87-4945-877b-f19e57f6c645.png">

<img width="538" alt="Screenshot 2022-02-19 at 12 45 16" src="https://user-images.githubusercontent.com/1483463/154799419-0dc8e366-4fd5-48a1-b845-ca6a6052e446.png">

**Comment by 0liver** [comment]
You can try to find our yourself what the underlying problem is by enabling your Script debugger to pause on exceptions. Then inspect the stacktrace and find out where that `r.message` comes from and why it does not contain `replace`.

**Comment by pimduijst** [comment]
Well @0liver the issue is I am rendering the form.io lib from their cdn which gives me a minified version. I have no clue how I can apply breakpoints in a minified version...

**Comment by 0liver** [comment]
What's the URL you're using? Have you tried removing the `.min` from the end of the file?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
