### ISSUE TITLE
Get a minimal form schema? (omit default configurations, etc?)

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#4609]
Is there a smaller schema available that removes default configs/values?  When working with large schemas, the configuration size adds up quickly (Tabs with data grids, etc).

Looking at ways to generate a smaller schema.

Thanks!

**Comment by 0liver** [comment]
How are getting your schema?

**Comment by StephenOTT** [comment]
@0liver from the form builder output

**Comment by 0liver** [comment]
I'm guessing that you're doing it the way I was doing it at first, too - which gave me a very verbose configuration. I'm doing the following now to get the minimal schema that Form.io provides:

```js
window
    .Formio
    .builder(formBuilderElement, getFormConfig(), builderOptions)
    .then(function onCreate(builder) {
        builder.on('change', () => {
            // Store the schema - here, log it as an example:
            console.log(builder.schema);
        });
    });
```

I found this somewhere in the Docs, but I don't have the link ready anymore.

**Comment by StephenOTT** [comment]
What is the difference between your example of the builders generated schema?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
