### ISSUE TITLE
Evaluator should allow for exposing errors

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#4613]
I realize that the evaluate function appears to be trying to give context to where errors are occurring which is nice, but because they're all `console.warn` we aren't getting logs on our error services.  And I don't want to override warn because some things are legitimately warnings.

I would actually prefer that an error is always an error, but perhaps this could be done with a flag like `Evaluator.noEval` that would do something like: `Evaluator.warnOnError ? console.warn(...) : console.error(...);`

For the moment my solution is to:

```js
const evaluator = Formio.Evaluator.evaluator;
Formio.Evaluator.evaluator = function(func, ...params) {
  try {
    return evaluator(func, ...params);
  } catch (e) {
    console.error(e);
  }
};
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by paulfalgout** [comment]
So if it is still relevant is there any real point to reopening it, or will the issue go unaddressed and closed in a couple of years?

**Comment by daneformio** [comment]
Please re-open and provide an example of this issue in the latest versions and we'd be happy to review soon.
