### ISSUE TITLE
[BUG] EditGrid won't save first row when "Open First Row When Empty" is checked

### ISSUE THREAD

**Issue by katie-a-chu** [formio/formio.js#4620]
When "Open First Row When Empty" is checked on an edit grid component, the first row won't save. Note that this seems to only happen when the edit grid component is on a page that is NOT the first page (this works as expected if the edit grid is on the first page of the form).

## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.14.1
- Frontend framework: React
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create a form with the Edit grid **on a page other than the first page** and a select component inside. Ensure that "Open First Row When Empty" is checked on the edit grid component. 
2. Navigate to the page with the edit grid and attempt to save the first row.

## Expected behavior

First row should save.

## Observed behavior

First row does not save - see screen recording: 

https://user-images.githubusercontent.com/36900799/155809556-f29efee4-3639-418f-bd8b-e5d136b16360.mov

## Example
JSON with edit grid:

```
{
  "label": "Edit Grid",
  "openWhenEmpty": true,
  "tableView": false,
  "rowDrafts": false,
  "key": "editGrid",
  "type": "editgrid",
  "input": true,
  "components": [
    {
      "label": "Surgery or procedure",
      "widget": "choicesjs",
      "tableView": true,
      "dataSrc": "json",
      "data": {
        "json": [
          "Test",
          "Test",
          "Test"
        ]
      },
      "clearOnHide": false,
      "customDefaultValue": "// rowIndex = component.row.split('-')[0]\n// console.log(component.value)\n// value = data.existingAppointmentContext.historicalChartData.surgicalHistory[rowIndex]",
      "calculateValue": "value = _.get(row, 'label')",
      "allowCalculateOverride": true,
      "validate": {
        "required": true
      },
      "key": "text",
      "type": "select",
      "input": true
    }
  ]
}
```

```js
// your code here
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
