### ISSUE TITLE
[BUG] Hooks are not working on form renderer 

### ISSUE THREAD

**Issue by mujtaba1016** [formio/formio.js#4625]
## Environment
Documentation code is not working even on following sandbox
https://jsfiddle.net/travistidwell/v38du9y1/

## Example
As described in docs example. Change all rendered fields to be required:

```js
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example', {
  hooks: {
    addComponent: (component) => {
      component.required = true;
      return component;
    }
  }
})
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
