### ISSUE TITLE
formBuilder & bootstrap 4

### ISSUE THREAD

**Issue by AlameerDev** [formio/formio.js#463]
Dears,

@travist @asalhani

I'm facing an issue to make form builder work with bootstrap 4 ( as you know there is some changes between V3 & V4 like how bootstrap deal with collapse ).

Is there any plan to upgrade form builder to use bootstrap 4 ?

**Comment by anupavanm** [comment]
+1

**Comment by anupavanm** [comment]
I see the main problem is with glyphicons..

**Comment by AlameerDev** [comment]
and the collapse as well.

**Comment by kbeckwith** [comment]
any update to this?

**Comment by wag110894** [comment]
Hello AlameerDev,

This is William with the Form.io support team. Great to hear from you!

Yes! The process is already under way in the 4.x. branch which will allow switching from bootstrap 3 to bootstrap 4 as well as other frontend frameworks.

We are working to complete this as soon as possible.  We will let me know when this update is completed. 

Please let us know if you have any further questions or concerns .

Thanks,

William Gay

**Comment by kbeckwith** [comment]
Great news!

**Comment by nashy18** [comment]
Still facing same issue !! Have we got solution?

**Comment by randallknutson** [comment]
This is currently available in Release Candidate state and we are hoping for a release very soon. It is pretty stable so feel free to start testing it and see if it works for you.

**Comment by jptissot** [comment]
> This is currently available in Release Candidate state and we are hoping for a release very soon. It is pretty stable so feel free to start testing it and see if it works for you.

Do you have some documentation on 4.x ?

**Comment by jhen1422** [comment]
We are constantly working on 4.x updates - documentation is in our backlog. As mentioned please feel free to test the latest 4.x candidate
