### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Andrewknackstedt** [formio/formio.js#4632]
## Environment
Please provide as many details as you can:
https://formio.github.io/formio.js/app/sandbox

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.14.x 4.15.x
- Frontend framework:formio.full.js
- Browser: Chrome 
- Browser version: 98.0.4758.105
- OS: Debian 11. KDE 5.20.5.

## Steps to Reproduce
1. Load the Sandbox page at https://formio.github.io/formio.js/app/sandbox. 
2. See no editor boxes for adding controls
3. Select 4.13.12 to get the boxes to show up and work. 

## Expected behavior
Edit boxes show up and I can edit form JSON.
## Observed behavior
Editor doesn't initialize

## Example

![image](https://user-images.githubusercontent.com/47012541/156826125-9b641389-8b68-4f74-82d7-c3ab7c7e62cf.png)

I noticed the following error. It seems that the sandbox page isn't loading/initializing the script properly.

![image](https://user-images.githubusercontent.com/47012541/156826075-e566db3b-dc94-46bb-b046-58b1d2412c19.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
