### ISSUE TITLE
Sidebar components disabled on custom PDF server handling.

### ISSUE THREAD

**Issue by Anandks1993** [formio/formio.js#4634]
Hi,

We have been trying to use PDF form builder with our own backend server. We modified the upload part in formio to upload PDF file into our server. This is done successfully and the PDF from our backend server is loading perfectly, but the sidebar draggable components are not getting enabled for us to drag and drop onto the PDF. Kindly let us know how to enable the sidebar components once the PDF file is loaded.

Thanks in advance.

**Comment by Anandks1993** [comment]
![disabled](https://user-images.githubusercontent.com/26414695/157390732-35eb4879-11b5-4477-86eb-75fb6abcf425.gif)

As you can see the sidebar fields are not getting enabled once the PDF is loaded and the PDF link is provided by our own server where we are converting the PDF into html using `pdf2htmlEX` library to enable formio to load the PDF.

**Comment by Anandks1993** [comment]
@wag110894 Any update on this? Will be really helpful to know if it can be solved or not. Thanks in advance.

**Comment by edwinanciani** [comment]
@Anandks1993 The PDF Server is required for this and is part of our commercial offering. Please contact sale@form.io for more information.

**Comment by andynguyenqtech** [comment]
@Anandks1993 Hi, how to you can fix this, I saw same your issues

**Comment by brendanbond** [comment]
Hi @Anandks1993 as mentioned above, the ability to build and render PDF-first forms is a part of our enterprise offering. I'm closing this issue, but let us know if you have any more questions.
