### ISSUE TITLE
Form Builder - can't modify columns

### ISSUE THREAD

**Issue by AlameerDev** [formio/formio.js#464]
Dear @travist ,

I tried to create more than 2 columns using the new form builder here : https://formio.github.io/formio.js/app/builder but doesn't work. ( even try to remove one column and keep it 1 doesn't work )

@asalhani  FYI

**Comment by AlameerDev** [comment]
I used Form.builder in my application and I'm facing the same problem.

**Comment by travist** [comment]
This is fixed with latest release.
