### ISSUE TITLE
[BUG] Request to https://cdn.form.io/ace/1.4.10/worker-json.js is canceled (sometimes)

### ISSUE THREAD

**Issue by 0liver** [formio/formio.js#4651]
## Environment
Please provide as many details as you can:

- Hosting type: none
  - ✓ Form.io
  - X Local deployment
    - Version: 
- Formio.js version: both 4.13.12 and 4.14.2
- Frontend framework: none
- Browser: Chrome
- Browser version: 98

## Steps to Reproduce
1. It's not easy, because it doesn't happen every time. But if you try long enough, you should see the error.
2. Add a Number component to any form.
3. Open the Edit UI via the settings cog. 
![image](https://user-images.githubusercontent.com/164360/159119297-49e7a65b-3d03-4aba-aba9-9dcb415a2261.png)
4. Once every N times, this will lead to a canceled request to https://cdn.form.io/ace/1.4.10/worker-json.js, which is reported as an error by our frontend error handling script.
5. The error does **not** occur with any other scripts.

## Expected behavior
- Request succeeds.

## Observed behavior
- Request is canceled one in N times.

## Example
![image](https://user-images.githubusercontent.com/164360/159119416-c0f5243b-1f18-4b24-b6e9-eecdd3a39a85.png)

**Comment by 0liver** [comment]
Has anybody been able to look into this? Has anyone else experienced this issue?

**Comment by wag110894** [comment]
Can you provide the form embed of this form?

**Comment by 0liver** [comment]
This happens even on a fresh form.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution
