### ISSUE TITLE
[BUG] Submitted form view -> Signature component doesn't show on Firefox but does show on Chrome

### ISSUE THREAD

**Issue by sthammav** [formio/formio.js#4655]
## Steps to Reproduce /Environment
- Login to form.IO and view a document that was submitted using the signature component
  On Chrome: Version 99.0.4844.82 (Official Build) (64-bit Windows)
  Observation: The signature is partially captured, but there's not pdf button at the top
![image](https://user-images.githubusercontent.com/15822738/159737997-8982c29c-61bd-404e-98dd-372a5a41fe66.png)
![image](https://user-images.githubusercontent.com/15822738/159738199-47dc1ea2-3cae-4811-9ab8-00f86ff3bd32.png)

  On Firefox: Version 98.0.1 (64-bit Windows)
  Observation: The signature is empty, but there's a pdf button at the top.  If I click on the pdf it errors out, a different issue.

![image](https://user-images.githubusercontent.com/15822738/159738432-9535b72f-2985-42a7-bf85-8b6f1c183a8f.png)
![image](https://user-images.githubusercontent.com/15822738/159738526-c8640279-c31b-4d2d-b3a9-10d1b47a2a73.png)

Error when clicking on the pdf icon to check how the form is saved, I get the token error:
![image](https://user-images.githubusercontent.com/15822738/159738706-5d0d950e-2951-4992-ba8e-20318826f22d.png)

Questions:
- How I do get the full signature to show in the submitted form view?
- Why am I getting an error when I click on the pdf icon on Firefox?
- Why is there not a pdf icon on Chrome?
- Not sure if this the right place to post it.  Or should I send this to form.io support about their application?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
