### ISSUE TITLE
[BUG] Does datepickerMode actually get used?

### ISSUE THREAD

**Issue by simonv3** [formio/formio.js#4657]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
    - Version: 4.14.4 
- Formio.js version:4.14.4
- Frontend framework: React
- Browser: Firefox
- Browser version: 98.0.1

## Steps to Reproduce
1. Adding `datepickerMode` to any datetime object seems to be ignored. It just displays "day". 

## Expected behavior

`datepickerMode` should change the display of what gets used by default for the user. 

## Observed behavior

Adding `datepickerMode` to the JSON of the datetime component in the form doesn't do anything, and the "initial mode" dropdown [present here](https://docs.form.io/userguide/forms/form-components#date-time) also doesn't exist in the settings of the datetime component.

[Doing a search for `datepickerMode`](https://github.com/formio/formio.js/search?p=2&q=datepickerMode&type=code) in the code shows it appearing in mocks and stubs, but it doesn't actually appear anywhere in the code. Does `datepickerMode` actually have any effect, and if so what's going wrong here. If not, how do we fix it, or should it be removed from documentation? 

## Example
![image](https://user-images.githubusercontent.com/485583/159950798-4cd79298-9512-444b-9a37-6c95ba4a5b98.png)
![image](https://user-images.githubusercontent.com/485583/159951079-d83732f5-a92e-4dbc-b1ae-1cebc1a8e33d.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
