### ISSUE TITLE
[BUG] Tooltips not working properly in mobile

### ISSUE THREAD

**Issue by adventmedia** [formio/formio.js#4659]
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.14.4
- Frontend framework: React - `@formio/react: 5.2.0`

## Steps to Reproduce
1. Create a form with a Panel component, add Tooltip text, select "Collapsible" and "Initially Collapsed" options
2. Viewing the form on a mobile device, tap the (?) tooltip icon

## Expected behavior
Tooltip appears

## Observed behavior
Panel opens (or closes)

If the collapsing behaviour is not selected, the tooltip does appear - though the tooltip is cut off by the right edge of the screen.
![screenshot_691](https://user-images.githubusercontent.com/1529172/160459961-ebe9c1b4-6425-45ad-9db8-e8c998eca623.jpg)

**Additional issues**
The behaviour with collapsible panels is the most egregious, but generally tooltips function erratically or not at all. One fix that needs to be applied is to add stopPropagation() to the tooltip event handler (click for mobile). This may be enough to solve all observed problems.

- on the Checkbox component, clicking the tooltip also toggles the checkbox (tooltip also appears)
- on the Text Input and Number components, clicking the tooltip causes the input field to focus (tooltip does not appear)

**Comment by ZenMasterJacob20011** [comment]
Thank you for taking the time to report this issue. I was able to reproduce this on formiojs@4.18.1. Created a ticket [FIO-8259].

**Comment by ZenMasterJacob20011** [comment]
It is expected that on mobile devices if you have a tooltip within a panel component you must press and hold on the tooltip icon in order to display the tooltip. This is also expected for other components that focus upon clicking near the label. Feel free to reopen the issue if pressing on a tooltip icon does not open the tooltip.
