### ISSUE TITLE
DataSource/makeStaticRequest Result string will be wrapped into quotes

### ISSUE THREAD

**Issue by DerH4NNES** [formio/formio.js#4661]
https://github.com/formio/formio.js/blob/0dd28a7ca7fd0d2b009114a2dc89f6889b0d4377/src/Formio.js#L900

I tried to create a raw Request body application/x-www-form-urlencoded with the datasource component.
This line wraps my raw body into quotes and creates an invalid request for my endpoint.

Is there any operator for raw body?

**Comment by DerH4NNES** [comment]
if (data) {
  if (typeof data !== string) {
    options.body = JSON.stringify(data);
  }
  else {
    options.body = data;
  }
}

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
