### ISSUE TITLE
DataGrid : Unable to edit or save the component 

### ISSUE THREAD

**Issue by uppalabharath** [formio/formio.js#4664]
Errors seen in console: 

```
TypeError: r is undefined
```

The component is also not rendering in the preview panel. 
While using the form with the above component,  an error is thrown in console 
```Cannot read properties of undefined (reading 'replace')```

![formio_2](https://user-images.githubusercontent.com/16371262/160987478-28fb2a8f-4b27-4333-a2f9-fa3f2d66a9de.gif)
![formio](https://user-images.githubusercontent.com/16371262/160987496-a0686014-a3dd-4e16-bd2a-73cfa4e4074d.gif)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
