### ISSUE TITLE
[BUG] Date validation min/max does not allow a single date to be valid

### ISSUE THREAD

**Issue by leoc** [formio/formio.js#4667]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
- Formio.js version: 4.9 beta
- Frontend framework: vanilla
- Browser: Chromium
- Browser version: Version 98.0.4758.102 (Official Build) Arch Linux (64-bit) and others

## Steps to Reproduce

See example:

https://jsfiddle.net/52mdjpnx/

1. Select today
2. Blur date select field

## Expected behavior

Keep selected date of today.

## Observed behavior

Validation error and empty field

## Example

https://jsfiddle.net/52mdjpnx/

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
