### ISSUE TITLE
[BUG] Setting the namespace doesn't work

### ISSUE THREAD

**Issue by hbobka** [formio/formio.js#4673]
Hi guys,

I tried to set a namespace by using:

```
Formio.setUser({}, { namespace: 'myCustomNamespace' });
Formio.setToken('...jwt...', { namespace:  'myCustomNamespace' });

Formio.createForm(formWrapperId, submissionUrl, { namespace: 'myCustomNamespace' });
```
The namespace is set correctly in the localStorage but it seems that when the form renderer tries to load the submission, the namespace is lost and so the Token is not found. So I get the message: "Unauthorized" .

A workaround for me is to set:

`Formio.namespace = 'myCustomNamespace'`

Or to set the namespace in a plugin:
```

const formioFetchIntercept = {
  request: (requestArgs: FormioRequestArgs): void => {
    // set the namespace
    requestArgs.opts.namespace = 'myCustomNamespace';
  },
};

Formio.registerPlugin(formioFetchIntercept, 'formioFetchIntercept');
```

Is this a bug or do I miss something?

Greetings

**Comment by travist** [comment]
You will need to set the Formio.namespace value to tell the renderer the correct namespace to use, so your workaround is actually the right thing to do.

**Comment by hbobka** [comment]
ok 👍 thank you @travist
