### ISSUE TITLE
Full documentation on components js fields?

### ISSUE THREAD

**Issue by francesco-gallo** [formio/formio.js#4674]
I'm trying to find a full documentation on all the available fields I can use on a json component definition.  

For a specific custom function I had to reverse-engineer the code and find that there is a field called "allowCalculateOverride" that can be used to manually override a value generated with "calculateValue", but I couldn't find the documentation on the first, although valid for basic components (i.e. an input field).  

Similarly, there are a few possibility for "dataSrc", but I couldn't find their list or examples, and I had to scrape every example on "formio.github.io/formio.js/app/examples" to get an insight of what I could do and not do.

Is there an updated list of all the properties available on components, with examples on their usage?

Thanks

edit: sorry I didn't want to be tagged as bug but I can't find the remove label button

**Comment by edwinanciani** [comment]
@francesco-gallo https://help.form.io/userguide/forms/form-components

**Comment by francesco-gallo** [comment]
I'm sorry @edwinanciani , but in that documentation I couldn't find any reference for either dataSrc or calculateValue js'specification.  
There I could find only the manual for the user interface...

**Comment by travist** [comment]
The closest thing we have is this https://github.com/formio/formio.js/wiki/Form-JSON-Schema

This needs to be updated though with the latest documentation. Ultimately what I would prefer is a script parse the edit form JSON to determine each of these properties and their description, but this has not been done yet.
