### ISSUE TITLE
Build error occurred - ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by vijaygohil1223** [formio/formio.js#4678]
## Environment
node 14.19.1
npm 6.14.16

"react-formio": "4.3.0",
"formiojs": "^4.14.6",

I am using formio with nextjs. there is an error while generating build it says that 
**ReferenceError: navigator is not defined    at Object.<anonymous> (node_modules/formiojs/components/file/File.js:179:21)**

I have rendered formio with ssr false. its is working fine in development mode and giving error while creating build

**Comment by edwinanciani** [comment]
@vijaygohil1223 it is not a bug. You are trying to render formiojs which is a library that uses the browser's API in nextjs which uses SSR. This is how you can handle formiojs and other frontend libraries in nextjs. https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage

Example code.
I created a General Form Component
```
import 'formiojs/dist/formio.full.css'
import {Form} from '@formio/react'

const FormComponent = ({form, data, onSubmit, onChange}) => {
  return (<div>
    {
      typeof window !== "undefined" ? <Form src={form} onChange={onChange} submission={data} onSubmit={onSubmit}  /> : <h3>Form not Loaded</h3>
    }
  </div>
  )
}

export default FormComponent
```
Then, I dynamic imported this component and set the SSR to false.
`const FormComponent = dynamic(() => import('../../../components/Form'), {ssr: false})` 

And finally, render it in the browser context.

```
 { typeof window !== "undefined"  ? <FormComponent data={data} form={url} onSubmit={onSubmit} /> : null}
```
