### ISSUE TITLE
[Information] - Client side PDF generation

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#468]
Hello @travist @randallknutson 
We would like to share with you a package that we use to generate a printable PDF and HTML from the form components.
https://github.com/UN-FAO/fast-export

Best!

**Comment by asalhani** [comment]
@travist @AlameerDev
@cabrerabywaters : it's a good add to the library, however, keep in mind that since you are using `jsPDF` library, therefore, some language will not be supported. For instance, rendering Arabic chars is not working as expected. This is a known issue in jsPDF library.

Find below URL of a forked sample of yours where I've added some Arabic text. Notice that how the correct rendering in HTML is being corrupted when converted to PDF.

**Comment by travist** [comment]
This is a great contribution! @cabrerabywaters!

We will look into adding this as part of our core platform. I really appreciate your contribution!

Travis.

**Comment by cabrerabywaters** [comment]
@travist 

You can also check this other two https://github.com/formio/formio.js/issues/473
We are slowly releasing the tools that we use...so expect more in the following weeks

Best, Ignacio

**Comment by multinerd** [comment]
@cabrerabywaters Im trying to use your `formio-export` package but im having trouble getting it working.

I've opened an issue [here](https://github.com/airarrazaval/formio-export/issues/1) and [here](https://github.com/fast-platform/fast-export/issues/3) since i wasn't sure which one was active.

**Comment by krixerx** [comment]
How is going with formio-export? In Github it looks like abandoned. Is it already integrated to formio core?
Many thanks!

**Comment by travist** [comment]
We do not have ownership over that project, but we do have PDF capabilities within our commercial platform if anyone is interested, and we will continue to maintain this version indefinitely.

**Comment by multinerd** [comment]
@krixerx i was able to get it working

check out https://github.com/multinerd/formio-export for a modified version and see readme for the code im using. 

Feel free to ask any questions.

**Comment by krixerx** [comment]
@multinerd any plans to improve your fork?
* htmlElement is missing
* support JSONLogic in conditional values
* support server side PDF generation?
* something else? styles?

**Comment by multinerd** [comment]
@krixerx no, not anytime soon. I just needed something to generate a printout of a form but you're free to do a PR, though i recommend you PR the original repo. I have no plans on maintaining other than to keep it in a working state.

**Comment by cabrerabywaters** [comment]
Hello everyone!
Sorry I didn't get a notification on this issue. We have a pending PR that
fixes some issues with the library, including moving to the original
pdfhtml libraries and pagebreaks.
We will merge it tomorrow so you can start using it again.
All suggestions on how to improve the library are more than welcome, please
add them as issues on the original library and we will try to work on them.
Of course PRs are also welcome
Best!

**Comment by thanhvietnguyen255** [comment]
Hi @cabrerabywaters-zz,
First of all, I want to say, that you guys made great work with this package 👍

When I export to Html, the column doesn't work.
As my design, it is 2 columns but when exported to Html, it is in each row.
Also, I think you should set max-width: 100% instead of 250px for signature.

![image](https://user-images.githubusercontent.com/58280615/91519143-fe6a7580-e91b-11ea-9507-f6ff2668eee9.png)
![image](https://user-images.githubusercontent.com/58280615/91519183-1e019e00-e91c-11ea-898f-1147b9c000be.png)

**Comment by wag110894** [comment]
@thanhvietnguyen255, can you provide a form embed so that we can test on our side?

**Comment by thanhvietnguyen255** [comment]
@wag110894, this is a zip file that contains my code, components/submission data, and HTML result.
https://www.dropbox.com/s/33klhqg4u31y4zd/code%20and%20data.zip?dl=0

Thanks.

**Comment by thanhvietnguyen255** [comment]
Hi @wag110894, I have taken a look at your code. I think it should be based on all properties of components to generate HTML instead of just based on the labels and values. That is why the component "Content Component" doesn't exist in HTML.

Why do you set col-sm-3 and col-sm-9?

**Comment by wag110894** [comment]
@thanhvietnguyen255,

This module is actually community-contributed and is something that we do not support. You will need to get with the creator of the module for assistance.

**Comment by thanhvietnguyen255** [comment]
Thanks for your response @wag110894. I know this module is free so I can't ask for more. However, I hope the creator of the module can improve some of the bad things I suggested above.

Besides, do you know any free modules for exporting PDF or HTML like this one?

**Comment by thanhvietnguyen255** [comment]
Hi guys,

How do I hide other options (Base64, Dropbox, ...) and keep IndexedDB only?
![image](https://user-images.githubusercontent.com/58280615/94390053-c2753b00-017b-11eb-88ae-d1b66210bb93.png)

**Comment by letigiam** [comment]
Hi, I need to print my modules created in form.io.  Can I to use this library with angular?
