### ISSUE TITLE
[BUG] Overriding the documentation entry in builderInfo for custom component

### ISSUE THREAD

**Issue by jasonchung1871** [formio/formio.js#4684]
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version: 4.13.10
- Frontend framework: Vue 2.6.14
- Browser: Brave
- Browser version: 1.37.116

## Steps to Reproduce
1. Create a custom component
2. Return object in builderInfo function containing entry for documentation with the link to your documentation
3. Drag and drop the component using the builder
4. At the top right of the modal that pops up, hover over help or copy the link
5. The link will be `https://help.form.io` with the value of your documentation entry appended to the end of it

## Expected behavior
The documentation variable should override the original entry, so we can point it to documentation of our custom component.

## Observed behavior
The URL for the documentation when dragging and dropping a component into the builder points to our documentation value appended to the `https://help.form.io` URL.
## Example
We created a custom component and return builderInfo like so:
```ts
static get builderInfo() {
    return {
        title: 'Business Name Search',
        group: 'advanced',
        icon: 'database',
        weight: 70,
        documentation: Constants.DEFAULT_HELP_LINK,
        schema: Component.schema()
    };
}
```
[This is what happens if you view the documentation URL](https://i.ibb.co/MRK03k1/help.png)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
