### ISSUE TITLE
[BUG] Hide groups is not working in data grid

### ISSUE THREAD

**Issue by Yashika117** [formio/formio.js#4686]
## Environment
Web

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Drag and drop the Data Grid Component,
2. Drag any basic components inside the data grid,
3. Edit the Data Grid Component and select 'Enable Row Groups',
4. Add label and number of rows,
5. Check 'Hide Group on Header Click'
6. Click on Save

## Expected behavior
On click of Hide Group to the left of label, the rows should be hidden.
Again on clicking the Hide Group, the rows should be displayed.

## Observed behavior
On click of Hide Group, the rows are not hidden.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
![Form Dialog](https://user-images.githubusercontent.com/104346111/165040619-f4a47436-7614-4c86-8174-7027a1a01e60.PNG)
![Data Grid](https://user-images.githubusercontent.com/104346111/165040669-3384aa95-a896-4895-924e-3b5cb05d28d9.PNG)

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
