### ISSUE TITLE
TypeError: row.forEach is not a function in formioUtils eachComponent

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#469]
i'm using formiojs (pure js) v2.32.1
when trying to call this method:
     FormioUtils.eachComponent(form.components, function(component) { ...

i got this error:
     TypeError: row.forEach is not a function

json form schema attached 
     https://we.tl/Aq9ZXhySCB

it happens when i have DataGrid component in schema otherwise works fine

**Comment by jhen1422** [comment]
Issue should be resolved on the latest 4.x
