### ISSUE TITLE
[BUG] Content object (Rich HTML Editor based on CKEditor) does not showing up

### ISSUE THREAD

**Issue by sdancer75** [formio/formio.js#4690]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.15.0-rc.12
- Frontend framework: react
- Browser: chrome 
- Browser version:100.0.4896.127

## Steps to Reproduce
1. create a simple resource and add from basic components "Content"
2.  Try to enter some data
3. Content object is missing

## Expected behavior
To show the content object add data

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

The content object is missing at all from the user input
![Screenshot_4](https://user-images.githubusercontent.com/10809692/165468532-5fae71e2-eddd-4855-91ea-250e79c48847.jpg)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
