### ISSUE TITLE
Multiple select box displays undefined values

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#4691]
I defined a select box with:
* multiple values
* url
* **data type: object**
*  default value: **array of keys** (without labels)
*  idPath: key

Schema:
```
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "Select",
            "widget": "choicesjs",
            "tableView": true,
            "multiple": true,
            "dataSrc": "url",
            "data": {
                "url": "https://bpa.dev.lesotho.eregistrations.org/restheart/catalog/2p22p73_858368_858368.en/2c9280947d2e20a8017d2e52b3f2001b?pagesize=300&sort_by=customOrder",
                "headers": [
                    {
                        "key": "",
                        "value": ""
                    }
                ]
            },
            "dataType": "object",
            "idPath": "key",
            "template": "<span>{{ item.value }}</span>",
            "refreshOn": "data",
            "searchEnabled": false,
            "clearOnHide": false,
            "customDefaultValue": "value=[{\"key\": \"1 poland\"},{\"key\": \"5 canada\"}]",
            "key": "select",
            "type": "select",
            "lazyLoad": false,
            "selectValues": "values",
            "disableLimit": false,
            "input": true,
            "defaultValue": [
                {}
            ]
        }
    ]
}
```

**Comment by CHASESY** [comment]
Is it just the default values that are showing as undefined or all the options in the select that show as undefined? I went to re-create this in our https://formio.github.io/formio.js/app/builder and I'm seeing undefined for the default values, but not for all the options in the select. 

I was, however, able to get this to work with no undefined values. Here's my components property:
`"components": [
        {
            "label": "Select",
            "widget": "choicesjs",
            "tableView": true,
            "multiple": true,
            "dataSrc": "url",
            "data": {
                "url": "https://bpa.dev.lesotho.eregistrations.org/restheart/catalog/2p22p73_858368_858368.en/2c9280947d2e20a8017d2e52b3f2001b?pagesize=300&sort_by=customOrder",
                "headers": [
                    {
                        "key": "",
                        "value": ""
                    }
                ]
            },
            "dataType": "object",
            "idPath": "key",
            "template": "<span>{{ item.value }}</span>",
            "key": "select",
            "type": "select",
            "input": true,
            "lazyLoad": false,
            "defaultValue": [
                {
                    "key": "1 poland",
                    "value": "Poland",
                    "customOrder": 0
                },
                {
                    "key": "5 canada",
                    "value": "Canada",
                    "customOrder": 4
                }
            ],
            "selectValues": "values",
            "disableLimit": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]`

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
