### ISSUE TITLE
[BUG] Validation of a number component with negative sign fails

### ISSUE THREAD

**Issue by mohanakannan9** [formio/formio.js#4698]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: Latest from CDN
- Frontend framework:
- Browser: Chrome
- Browser version: Version 101.0.4951.41 

## Steps to Reproduce
1. Add a number component to a form
2. Set the Number field as Required
3. Save the form
4. Enter a negative number as value of the number component.
5. Click Submit
6. Form Fails validation as inserted value does not match the input pattern

## Expected behavior
Validation when negative number is inserted should pass

## Observed behavior
Validation is failing as the pattern on the input element is set to [0-9.]*

<input aria-required="true" aria-labelledby="l-euv49qp-number" id="euv49qp-number" value="" inputmode="decimal" lang="en" class="form-control" type="text" name="data[number]" ref="input" pattern="[0-9.]*" aria-invalid="false">

Adding an HTML attribute in the Layout of the component with pattern as [+-0-9.]* reverts back to pattern="[0-9.]*" 

May be the user supplied attributes should be allowed to override those set by form.io

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by mohanakannan9** [comment]
Any update on this issue? Am I just using the Number component incorrectly for Negative Integer?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
