### ISSUE TITLE
How to translate/localization the General Settings Component?

### ISSUE THREAD

**Issue by benjaminfaustinotiks** [formio/formio.js#4705]
How to translate those labels?

![Screenshot from 2022-05-12 12-17-55](https://user-images.githubusercontent.com/72246951/167991318-adf17077-1f57-4623-a552-9d94b29f683a.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
