### ISSUE TITLE
[BUG] Dragging a custom component onto form adds only a container - regression from 4.14.0 to 4.14.1

### ISSUE THREAD

**Issue by 0liver** [formio/formio.js#4709]
## Environment
Please provide as many details as you can:

- Hosting type
  - ❌ Form.io
  - ✔ Local deployment
    - Version: 4.14.1
- Formio.js version: 4.14.1
- Frontend framework: JS
- Browser: any
- Browser version: any

## Steps to Reproduce
1. [This fiddle](https://jsfiddle.net/efkghp5j/4/) contains a minimal working example of a nested component (Field & Measures -> Client -> First Name), which can successfully be dragged onto a form. It uses **v4.14.0**.
2. [This fiddle](https://jsfiddle.net/wu961g4e/2/) contains the same example, but uses the latest version, which is currently **v4.14.1**. Here, dragging the same component onto the form:
 a. Opens the component editor, which it shouldn't.
 b. After saving the component, leaves only an empty container component behind.
3. We're using the `resource` group at the root to be able to include several sub-groups in our complete setup. This might be of importance. I have found some changes regarding `resource` in `WebFormBuilder.onDrop()` but debugging those didn't lead to any enlightenment.

## Expected behavior
Dragging a (nested) component onto a form should work in 4.14.1 and higher.

## Observed behavior
Dragging a (nested) component onto a form does not work in 4.14.1.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
