### ISSUE TITLE
Cannot find complete documentation for custom components

### ISSUE THREAD

**Issue by Susccy** [formio/formio.js#4710]
I'm currently trying to implement a file upload component with custom validation logic for the uploaded files. I'm extending the base file component class as explained [in the official docs here](https://help.form.io/developers/custom-components).

However these docs don't really explain the base component's extendable methods outside of the vague and incomplete sample component and the very high-level CheckMatrix example (which confusingly exists in multiple different versions spread over the docs and GitHub). Even after reading all the comments on these components I still don't know what is required and what is optional to override to get a working component and I have absolutely no clue what method(s) I need to use for my requirements.

Am I missing something or is my only option to try and decipher the base component's scarcely documented source code?

**Comment by kylezhangjiawei** [comment]
me too, The documentation is confusing to me

**Comment by Susccy** [comment]
@kylezhangjiawei your best bet is to study the source code which will quickly make you realize what huge mess of a library formio.js is.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
