### ISSUE TITLE
How to check if a single page in a wizard is pristine or dirty

### ISSUE THREAD

**Issue by hbobka** [formio/formio.js#4718]
Hi guys,

I would like to check the pristine state of a single page inside a wizard.
I noticed that the pristine flag stays always true. (It does change correctly on the whole wizard though.)

I'm listening to the change event of the formio renderer:

```
form.on('change', () => handleChange(form), false);

const handleChange = (form: FormioWizard): void => {
  console.log('wizard pristine changes correctly: ', form.pristine);
  console.log('wizard page pristine doesn't change: ', form.pages[0].pristine);
};
```

Is this a bug or do I have to check another property?

Greetings

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
