### ISSUE TITLE
Form Builder Wizard - Deleting a component in nth page, redirects to page 1

### ISSUE THREAD

**Issue by anupavanm** [formio/formio.js#472]
While using form builder for constructing a wizard, deleting a component in any page redirects to 1st page. 

Found this in Wizard Builder.js
https://github.com/formio/formio.js/blob/master/src/WizardBuilder.js

```
  deleteComponent(component) {
    if (super.deleteComponent(component)) {
      this.gotoPage(0);
    }
  }
```

Is there any solution to overcome this ?

**Comment by jhen1422** [comment]
This issue has been resolved
