### ISSUE TITLE
[HELP] Button custom action - Add panel to form

### ISSUE THREAD

**Issue by mrazvan77** [formio/formio.js#4723]
I have a form that has a button and a panel with many select fields. I am new to Formio and I was wondering if when I press the button, a custom action will take place and add a copy of that panel in my form. 

I know I can make a copy of the panel when I am designing the form and hide it so I can unhide it when I press the button, but that is not what I want. If  the user will press 100 times on that button, I want 100 panels to appear.

Is this possible?

**Comment by paulbors** [comment]
You need to add your button inside a container like one of the many FomrBuilder already supports.

**Comment by paulbors** [comment]
Say you want to repeat an address panel that has many text boxes and buttons inside it.
Say you want a mailing address and a billing address when they are different addresses the user presses the button to repeat the address parent panel.

All you have to do, is to add the button and on click of it edit the form's model object and "copy" that one JSON node of the address panel. Not that difficult :)

**Comment by sureshyadaw437** [comment]
@mrazvan77   or see if you would like to use "Edit Grid" component.
1. https://formio.github.io/formio.js/app/builder
2. use "Edit Grid" component 
3. Modify the Templates if needed.
4. add your required components inside the edit grid
5. it gives us kind of widget to add n no. of same (step4) designed complex component.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
