### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tankasalagit** [formio/formio.js#4729]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 4.14.7
- Formio.js version:4.14.7
- Frontend framework:React js
- Browser:Chrome
- Browser version:

## Steps to Reproduce
1. Added a checkbox and a textfield
2. Added a condition on textfield  that, if checkbox value is true, textfield should be shown and if if is unchecked that textfield would be hidden.
3. When textfield is visible, entered some value, when it is hidden and shown again, the previously entered value is becoming blank.
4. As per our requirement the textfield value(previously entered) should exists, once it is shown again.

## Expected behavior
 When textfield is visible, entered some value.  When it is hidden and visible again, the previously entered value should be there.
## Observed behavior
But once the textfield is hidden, and it is shown again, the textfield is blank

```json form
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "label": "show weight",
            "tableView": false,
            "key": "showWeight",
            "type": "checkbox",
            "input": true,
            "defaultValue": false
        },
        {
            "label": "Weight",
            "tableView": true,
            "key": "weight",
            "conditional": {
                "show": true,
                "when": "showWeight",
                "eq": "true"
            },
            "type": "textfield",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}

```
<img width="960" alt="pic1" src="https://user-images.githubusercontent.com/104497174/171849338-70262d4b-693d-4b05-8e39-dec57662aa86.png">
<img width="960" alt="hidetextbox" src="https://user-images.githubusercontent.com/104497174/171849363-7bb2ed65-c85f-4623-b456-611d756befb3.png">
<img width="960" alt="pic3" src="https://user-images.githubusercontent.com/104497174/171849381-b760fa3d-d899-4e90-bb80-38b846fea0f3.png">

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
