### ISSUE TITLE
[Information] Form.io Submissions to CSV

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#473]
Dear @travist @randallknutson 

We would like to share with you a library that we use to export the Form.io submissions to flat CSV with translated labels. Is still a little big, but will remove some dependencies soon.
We will also share the one that we use for XLSX ;)
Enjoy!
https://github.com/UN-FAO/fast-submission2csv

**Comment by cabrerabywaters** [comment]
Just an update
Here is the library that we use to export to XLSX and other formats, again...is still kind of large because of some dependencies, but we will clean it soon.

https://github.com/UN-FAO/fast-submission2any

**Comment by randallknutson** [comment]
I just realized that no one ever responded to you on this. Thanks for sharing the library. We will keep it in mind if we ever need to add additional output options for our server.
