### ISSUE TITLE
[Question] Is there a way to move/replace the remove button in dataGrid?

### ISSUE THREAD

**Issue by ThomasVague** [formio/formio.js#4730]
Hi, quick question.  In the dataGrid container, the remove button takes up a lot of space - especially on phones. I'd rather remove the button and then add a remove button on the bottom after the input fields. Is there a way to do this? And is there a way to do this without creating a custom component?

![formio](https://user-images.githubusercontent.com/80428474/171648275-31994045-ff8f-4285-9eb2-6423a4836c52.PNG)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
