### ISSUE TITLE
[QUESTION] Update edit modal header

### ISSUE THREAD

**Issue by nikita-remeslov** [formio/formio.js#4740]
I can not find how to change the header in the modal window. Is there any way I can do this?
![image](https://user-images.githubusercontent.com/78347072/173559931-251dcbc4-9106-4c83-bed4-a5b6d6977e8c.png)

I want to change to any possible text. For example: "Add Text Field"
I am using 
`"formiojs": "^4.14.2",`

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
