### ISSUE TITLE
[BUG] URL at Webhook is not interpolated

### ISSUE THREAD

**Issue by tamfign** [formio/formio.js#4751]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io

## Steps to Reproduce
Use PATCH/GET method to an external Restful API.
With url like, `https://example.com/apples/{{data.appleId}}`

## Expected behavior
url will be interpolated like `https://example.com/apples/abcd-abcd-abcd-abcd`

## Observed behavior
API got the request as `https://example.com/apples/{{data.appleId}}`

So does it only support query param?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
