### ISSUE TITLE
Custom Metadata

### ISSUE THREAD

**Issue by knocknarea** [formio/formio.js#4759]
I would like to insert additional metadata into the form submission process. In addition to the usual keys of [timezone, browserName, pathName, etc..]

At the moment I am using the beforeSubmit hook to add additional metadata. However, no matter what I do, the injected metadata attributes are erased in the final submission. It's like the before submit alterations, no matter what are erased.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
