### ISSUE TITLE
 Circular dependency detected

### ISSUE THREAD

**Issue by Navpreet2289** [formio/formio.js#476]
WARNING in Circular dependency detected:
src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/container/Container.js -> src/formiojs/build/components/Components.js

WARNING in Circular dependency detected:
src/formiojs/build/components/columns/Column.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/columns/Column.js

WARNING in Circular dependency detected:
src/formiojs/build/components/columns/Columns.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/columns/Columns.js

WARNING in Circular dependency detected:
src/formiojs/build/components/container/Container.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/container/Container.js

WARNING in Circular dependency detected:
src/formiojs/build/components/datagrid/DataGrid.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/datagrid/DataGrid.js

WARNING in Circular dependency detected:
src/formiojs/build/components/editrgrid/EditGrid.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/editrgrid/EditGrid.js

WARNING in Circular dependency detected:
src/formiojs/build/components/fieldset/Fieldset.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/fieldset/Fieldset.js

WARNING in Circular dependency detected:
src/formiojs/build/components/form/Form.js -> src/formiojs/build/formio.form.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/form/Form.js

WARNING in Circular dependency detected:
src/formiojs/build/components/index.js -> src/formiojs/build/components/container/Container.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js

WARNING in Circular dependency detected:
src/formiojs/build/components/panel/Panel.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/panel/Panel.js

WARNING in Circular dependency detected:
src/formiojs/build/components/table/Table.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/table/Table.js

WARNING in Circular dependency detected:
src/formiojs/build/components/well/Well.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/well/Well.js

WARNING in Circular dependency detected:
src/formiojs/build/formio.form.js -> src/formiojs/build/components/Components.js -> src/formiojs/build/components/index.js -> src/formiojs/build/components/form/Form.js -> src/formiojs/build/formio.form.js

**Comment by Navpreet2289** [comment]
is there any fix required for this or its ok?

**Comment by jhen1422** [comment]
Please reopen a new issue if this is still occurring
