### ISSUE TITLE
[FEATURE] Text formatting of the Display -> Label field content

### ISSUE THREAD

**Issue by adventmedia** [formio/formio.js#4767]
We would like to be able to italicize or bold some of the text of the Display -> Label field, i.e. support a minimum level of html formatting.
Current work-around is to hide the label and use a Content component.

**Comment by wag110894** [comment]
You can accomplish this using CSS.

**Comment by adventmedia** [comment]
It’s not at all clear how css would be applied. Probably my request was not detailed enough.
There is a use case for formatting the Label text - as it turns out the existing field accepts html tags (who knew?)
![screenshot_781](https://user-images.githubusercontent.com/1529172/178297014-670cb31f-0d10-4676-b59d-95bffe9aea53.jpg)

This is nice but still given that FormIO is intended to be a low-code platform, let the feature request be understood that the Label field be a rich text editor (like the Content component), to give the content manager more complete control over the styling w/o requiring a knowledge of HTML.
