### ISSUE TITLE
[BUG] Setting the 'documentation' property on a custom control builderInfo has been broken at some point after 4.11.3

### ISSUE THREAD

**Issue by loneil** [formio/formio.js#4776]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.14.8
- Formio.js version: 4.14.8
- Frontend framework: any JS
- Browser: chrome
- Browser version: latest

## Steps to Reproduce
1. Create a custom component and set the documentation property in the builderInfo
2. In the form builder drag in that custom component
3. Try to use the help link

## Expected behavior
The help link I set in documentation is navigated to

## Observed behavior
It prepends "https://help.form.io" to the link you try and set

## Example
I can confirm this bug does not occur in 4.11.3 (running that locally right now to check) but when updating to a later version the prepend bug has been introduced.

```js

    static get builderInfo() {
        return {
            documentation: 'www.google.com',
        };
    }
```
This then results in the help link becoming:
![image](https://user-images.githubusercontent.com/17445138/179440355-768585a0-be55-4f2a-8403-80ed7251678e.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
