### ISSUE TITLE
[BUG] Builder is broken on https://formio.github.io/formio.js/app/builder

### ISSUE THREAD

**Issue by opcodewriter** [formio/formio.js#4780]
Builder is broken on https://formio.github.io/formio.js/app/builder, adding any component does not create any rendered form.
Looking at the console, it shows:

![image](https://user-images.githubusercontent.com/15019084/180021481-a7b5b67c-5694-41b9-9308-780b372daf86.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
