### ISSUE TITLE
[BUG] rendering form fields on the left side menu of Builder when we use Bootstrap 5.2 

### ISSUE THREAD

**Issue by sayedmohsinreza** [formio/formio.js#4790]
## Environment
 The form fields heading are not clickable when we use bootstrap 5. For  example; I can't click on "Basic" on the left side of form builder.

- Formio.js version: Lates
- Frontend framework: Javascript
- Browser:
- Browser version:

## Steps to Reproduce
1. Use Bootstrap 5
2. Load form io builder
3. click on Basic on the left side menu of the form builder

## Expected behavior
Click on "Basic" doesn't work
## Observed behavior
You need to change from 

<button class="btn btn-block builder-group-button" type="button" data-parent="#builder-sidebar-eaxtnca" aria-expanded="true" aria-controls="group-basic" ref="sidebar-anchor" data-toggle="collapse" data-target="#group-basic">Basic</button>

to 

<button class="btn btn-block builder-group-button" type="button" data-parent="#builder-sidebar-eaxtnca" aria-expanded="true" aria-controls="group-basic" ref="sidebar-anchor" data**-bs**-toggle="collapse" data**-bs**-target="#group-basic"> Basic</button>

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
