### ISSUE TITLE
[QUESTION] How to modify the preview to show a modal content and the button that will raise it

### ISSUE THREAD

**Issue by biaggi** [formio/formio.js#4791]
Hi all, I'm developing a custom component (a modal) and seems that I can only see a preview of the modal pop up inserting the modal into a form and rendering it.

There is any way to customize the preview to render the button that will raise the modal and the modal itself?

Any help will be appreciated

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
