### ISSUE TITLE
Is there any way to allow multiple date or date range in datepicker

### ISSUE THREAD

**Issue by Ajitha227** [formio/formio.js#4797]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: v4.12.7
- Formio.js version: v4.12.7
- Frontend framework: .Net
- Browser: chrome

## Steps to Reproduce
1. Add date picker control in formbuilder and check whether datepicker control allow multiple or daterange input

## Expected behavior
form builder must allow multiple or daterange filter

## Observed behavior
Not working in  v4.12.7

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
