### ISSUE TITLE
[BUG] URL provider's deleteFile method doesn't send JWT token

### ISSUE THREAD

**Issue by Susccy** [formio/formio.js#4798]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.14.7
- (anything else isn't relevant)

## Steps to Reproduce
1. look at source code of URL provider deleteFile method: https://github.com/formio/formio.js/blob/a83b1badb52cea11fab5d1242b86beb5a0fa098e/src/providers/storage/url.js#L117
2. notice how there's no x-jwt-token being set on header of HTTP request in deleteFile

## Expected behavior
DELETE requests always require authorization so I would expect the JWT token to be set on deleteFile.

## Observed behavior
JWT token is only set on uploadFile and downloadFile methods, but missing on deleteFile.

## Example
![image](https://user-images.githubusercontent.com/87642921/182175929-87fe9f6d-a0bc-4e22-bae2-07f308c9911a.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
