### ISSUE TITLE
[FormBuilder] Select boxes inside any layout element fail to store Data options

### ISSUE THREAD

**Issue by ensemblebd** [formio/formio.js#481]
To reproduce:

1. Add columns/panel/etc layout element
2. Add Select input to the layout
3. Edit options on the input's [Data] tab, hit [Save] 
4. Notice select lacks any inputs, goto [modify/wrench-icon] and back to [Data] tab, and notice all options were wiped out leave two empty rows for key/value pairs. 

I'll post more information as I did deeper into this. 

### Edit 1
It appears that it's storing them as an object by some means. The dropdown under the [Data] tab of the input editor lists the two options as "[object Object]" where normally the label would be displayed.
About to start digging through sources..

**Comment by jhen1422** [comment]
This should be resolved in the latest 4x renderer

**Comment by ensemblebd** [comment]
Thank you so much!
