### ISSUE TITLE
Set default value on a Date component when open form with saved submission data

### ISSUE THREAD

**Issue by mihaiandreicut** [formio/formio.js#4822]
### Discussed in https://github.com/formio/formio.js/discussions/4821

<div type='discussions-op-text'>

<sup>Originally posted by **mihaiandreicut** August 17, 2022</sup>
Hello,
I try to open a form with default data, and I have a Date field in which I try to set value 04.11.2021 but in the field appears 11.04.2021, I think it happens that because of this: moment.utc(input).toISOString(), which is in src/components/datetime/DateTime.js on line 153.

How to reproduce the error:
1. Create a form with more than one Page
2. On the 2nd page I put a date field, disabled, with {"dateFormat":"dd.MM.yyyy","locale":"ro"}, I also set the Format dd.MM.yyyy
3. Create a form with a submission data as I describe 

Have anyone any idea how to solve this kind of situations ?

Thank you.
 </div>

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
