### ISSUE TITLE
Latest formio.js version breaks on our app after update.

### ISSUE THREAD

**Issue by realbisoye** [formio/formio.js#4833]
We have been using a forked version of formiojs (and formio react) for a while, forked to enable us some custom needs and features.

We recently attempted to update our forked version to be up to date with the latest formio.js release. On update, we ran into this error message in the `FormBuilder` which breaks our entire UI,

```
Cannot assign to read only property 'id' of object '#<Object>'
```
It points to this line, ` _this.component.id = _this.id; ` . Basically, the component property returned by form builder seems non extensible. 

I have tested with the latest formiojs and formio react versions (fromiojs `v4.15.0-rc.13` and  @react/formio `5.2.3`) and encountered the same issue. Also the latest version of @react/formio works fine with older versions of formiojs including our fork. Hence this is an issue with formiojs.

Some of our shared library version information are shared below;
 
```  
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "lodash": "^4.17.21",
```

I have tried to figure out the root cause with no clear success. You help will be appreciated.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
