### ISSUE TITLE
File upload styling

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#4846]
![image](https://user-images.githubusercontent.com/946010/188295530-0a958fdc-c287-448d-ad68-d6c6bbc29167.png)

Is there a way to style the file upload to look like this?

**Comment by rishi-raj-jain** [comment]
How is this a bug?

**Comment by bilogic** [comment]
Bug label wasn't added by me. It is more a question.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
