### ISSUE TITLE
api.form.io call made when passing schema with nested forms

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#485]
@randallknutson, based on our conversation, it seems if you have nested forms and get the full schema, the client library under the hood is making an api.form.io call to load the nested schema.

In our use case we already preload the full schema therefore making a subsequent call to form io is unnecessary.

**Comment by pixie79** [comment]
I have found a few more spurious cases of this. When we have use the Wizard flow, then have multiple forms embedded, it appears that sometimes a form will show and other times it will fail. 
When it fails it appears to be trying to load the form from api.form.io instead of the local API server.
@randallknutson ^

**Comment by sabinayakc** [comment]
I have had similar issue with Nested Component. When I drag a nested component and hit save it makes a call to api.form.io. Do I have to provide any builder settings to disable this ? Are there other components anyone is aware of that has the same behavior?

Thank you. 

![image](https://user-images.githubusercontent.com/13154166/55248993-0d299600-5219-11e9-9e06-d7f88cb2a55e.png)

**Comment by travist** [comment]
This usually happens when the following are not set within your application.

```
Formio.setBaseUrl('https://yourdomain.com');
Formio.setProjectUrl('https://yourdomain.com');
```

If you are on Open Source server, then these will be the same, otherwise if you are using our Commercial server, then these need to be different urls.
