### ISSUE TITLE
[HELP] Documentation for `Advanced Logic`

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#4860]
```JSON
"logic": [
    {
        "name": "click",
        "trigger": {
            "type": "event",
            "event": "click"
        },
        "actions": [
            {
                "name": "selectall",
                "type": "customAction",
                "customAction": "instance.select();" // changing to this.select() also did not work
            }
        ]
    }
]
```

I can't find any documentation or good examples on `Advanced Logic`.
I would like to my textfields to select all its contents upon user click. So had the above on 1 of my textfield, but it does nothing.

Thank you.

**Comment by rahulchougule** [comment]
I have same situation where I want to uncheck all checked select boxes if I click on "None of the above" option. I tried with different logic but not worked.  I followed this fiddle - [https://jsfiddle.net/franke_mc/963nf54y/7/](https://jsfiddle.net/franke_mc/963nf54y/7/)

I'm able to uncheck required options but the checkbox with value "None of the above" is not selected at the same time.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
