### ISSUE TITLE
[BUG] Input Mask return Error validation on API Post Response

### ISSUE THREAD

**Issue by Cerebrovinny** [formio/formio.js#4865]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Create a form template containing a Input field with Input Mask e.g +1 (999) 999-9999
2. Send a POST request to submit a form against this form template
3. Even the data is correct the response is a error saying that the 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
 {
      "data":  {
    "ContactOwnerPhone":"+1 (123) 123-1234",
   "ContactOwnerEmail":"test@test.com",
   "ContactEstimatingFirstName":"Test",
   "ContactEstimatingLastName":"Test",
    }
}
```

JSON ERROR RESPONSE
```sh
{
    "name": "ValidationError",
    "details": [
        {
            "message": "Entry does not match format",
            "level": "error",
            "path": [
                "ContactOwnerPhone"
            ],
            "context": {
                "validator": "mask",
                "hasLabel": false,
                "setting": "+1 (999) 999-9999",
                "key": "ContactOwnerPhone",
                "label": "Telephone",
                "value": "+1 (123) 123‑1234",
                "index": 0
            }
        },
}
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
