### ISSUE TITLE
Problem with minimum date in date/time component (after updating formiojs 4.15.0-rc.14) using moment

### ISSUE THREAD

**Issue by javierel7** [formio/formio.js#4870]
I recently update formiojs to v. 4.15.0-rc.14, now when i use the datetime validation for minimum date its not working anymore. I use "moment().add(3, 'days')", it shows disabled previous days ok, but when the component loses focus its trigger the required error and the value it's cleared.

![Captura de Pantalla 2022-09-22 a la(s) 14 05 18](https://user-images.githubusercontent.com/111383567/191830903-6e58605f-d16b-4772-83c0-ae214eb08c23.png)

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
