### ISSUE TITLE
[BUG] Multiple values selection in a html5 select component doesn't work

### ISSUE THREAD

**Issue by simonlemo** [formio/formio.js#4874]
## Environment
When using the html5 widget for a select component that accepts multiple values, only one of the selected value get saved

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: https://cdn.form.io/formiojs/formio.full.min.js
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. Create a form with a select component using the html5 widget that accept multiple values
2. Use this form and select more than one option
3. Only one of the selected values will be displayed 

## Expected behavior
All the selected values should be saved
## Observed behavior
Only one value is saved

## Example
https://jsfiddle.net/0atLb79u/2/
Select more than one option, only one of the selected value will be displayed in the console

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!

**Comment by pboucher1960** [comment]
I believe this bug is this relevant. I posted a bug myself with this same issue here [](https://github.com/formio/formio.js/issues/5572). If it's not possible to have multi select capabilities with an HTML5 widget, this option should only be available when "ChoicesJS" is selected as a widget type.
