### ISSUE TITLE
How to get the label of a selected select field 

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#4884]
Hello FormIOjs team,

How can I get the label of a select field (so not the value) after change in a calculated value of another field.
Please advise.

Kind regards,
Mario

**Comment by wag110894** [comment]
You can accomplish this using the Merge Component Schema Action Type inside of the Logic Tab.

**Comment by KyooMario** [comment]
Can you share a bit more detail? What would be the schema definition?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
