### ISSUE TITLE
[BUG] Multiple forms on the same page with survey components

### ISSUE THREAD

**Issue by peter-vostan** [formio/formio.js#4895]
## Steps to Reproduce
- Create 2 forms on the same page with Survey components that have the same key values
- Select some survey values on the first form
- Select some survey values on the second form
- As you select values on the second form you'll notice that the selected values on the first form are cleared

## Example
https://jsfiddle.net/h532emc0/2/

https://user-images.githubusercontent.com/50313639/194705788-76c04016-e235-4f81-9b37-0afce3e50745.mov

**Comment by wag110894** [comment]
It seems that you have not set up the second survey with a unique property name.

Here is an example of it working correctly:
https://formio.github.io/formio.js/app/sandbox
Sandbox ID:
634441252551706d942a5297

**Comment by peter-vostan** [comment]
Thanks but unfortunately my scenario requires multiple forms on the same page. And these forms often have overlapping property keys. I thought that this was a supported use case?

This seems to work fine for all of the other components I have tested, it's just the survey component that has issues. 

I tried changing the property keys at runtime and this does work, however our forms also have predefined data and updating the data to match the key name changes is quite tricky when you have nested components and keys using dot notation etc.

**Comment by ANovokmet** [comment]
This happens because radios work using the `input[name]` attribute. If multiple radio inputs on the same page have the same name, they are considered the part of the same radio. This is how I made the survey use unique names:

```js
class SurveyComponent extends Formio.Components.components.survey {
    getInputName(question) {
        return `${this.id}-${this.options.name}[${question.value}]`;
    }
}

Formio.use({
    components: {
        survey: SurveyComponent
    }
});
```

**Comment by ZenMasterJacob20011** [comment]
This is because of ``"key": "survey"`` defined in your schema variable is used to create both components, because your key names will be the same for all surveys you create with this schema all surveys will effect each other. You need to either create a new ``const schema1`` and have schema1 key set to ``"key": "survey1"`` or when you call 
```
Formio
  .createForm(document.getElementById('formio-1'), schema)
  .then(function(form) {});
```
update your schema to change the key like so
```
Formio
  .createForm(document.getElementById('formio-1'), schema)
  .then(function(form) {});
let cnt = 1
schema.components[0].key = schema.components[0].key+cnt;
cnt += 1 
Formio
  .createForm(document.getElementById('formio-2'), schema)
  .then(function(form) {});
```
and increment count each time you create a new form.
Fix: Your survey components keys need to be unique
