### ISSUE TITLE
HELP.  Modal Edit (CLICK TO SET VALUE)

### ISSUE THREAD

**Issue by bohnmd** [formio/formio.js#4898]
HELP.  Want to change the text  / label "CLICK TO SET VALUE" that is displayed when "Modal Edit" is selected on a component?  How / Where can I change this text / label?

<img width="359" alt="Screen Shot 2022-10-11 at 10 44 53 PM" src="https://user-images.githubusercontent.com/16611198/195237607-99ad05e9-dc8f-4348-b43d-c751f4f3a24e.png">

**Comment by lane-formio** [comment]
Edit component > Data > Default Value
