### ISSUE TITLE
Disappears previously filled data in Edit Grid.

### ISSUE THREAD

**Issue by nosovicki** [formio/formio.js#490]
## Steps to reproduce

1. Create following form:
`{
  "components": [
    {
      "input": true,
      "tree": true,
      "components": [
        {
          "label": "a",
          "key": "a",
          "data": { "custom": "values = [1,2]" },
          "dataSrc": "custom",
          "template": "<span>{{item}}</span>",
          "type": "select"
        },
        {
          "label": "b",
          "key": "b",
          "data": { "custom": "values=[3,4]" },
          "dataSrc": "custom",
          "refreshOn": "a",
          "template": "<span>{{item}}</span>",
          "type": "select",
          "clearOnRefresh": true
        }
      ],
      "label": "Edit Grid",
      "key": "editGrid",
      "templates": {
        "header": "<div class=\"row\"> \n  {%util.eachComponent(components, function(component) { %} \n    <div class=\"col-sm-2\"> \n      {{ component.label }} \n    </div> \n  {% }) %} \n</div>",
        "row": "<div class=\"row\"> \n  {%util.eachComponent(components, function(component) { %} \n    <div class=\"col-sm-2\"> \n      {{ row[component.key] }} \n    </div> \n  {% }) %} \n  <div class=\"col-sm-2\"> \n    <div class=\"btn-group pull-right\"> \n      <div class=\"btn btn-default editRow\">Edit</div> \n      <div class=\"btn btn-danger removeRow\">Delete</div> \n    </div> \n  </div> \n</div>",
        "footer": ""
      },
      "type": "editgrid"
    }
  ],
  "display": "form"
}
`
2. Add two rows, setting some values for a and b.
4. Check data.
## Expected behavior
Data contains selected values for all rows
## Observed behavior
Value of ***b*** is absent in all rows except the most recently filled one.
## Comment
This happens because ***a*** update in any row resets ***b*** in all rows. Note that ***b*** is configured to reset on change in ***a***.

**Comment by jhen1422** [comment]
This issue should be resolved
