### ISSUE TITLE
Question: Formio Datetime component i18n based date formats

### ISSUE THREAD

**Issue by jonahermy** [formio/formio.js#4901]
Hello,

I use Formio with i18n for labels and placeholders, which works totally fine. But now I need to set the date format differently depending on the language settings. What I would need is:
en: MM/dd/yyyy hh:mm a
de: dd.MM.yyyy hh:mm

But it seems the format field does not resolve the i18n key.

What would be the way to go in Formio to achieve this if not via i18n?
Thanks a lot in advance

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
