### ISSUE TITLE
[Question] How to access parent row data 

### ISSUE THREAD

**Issue by APhanMonadel** [formio/formio.js#4909]
## Environment
Formio builder

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

When nesting a data grid inside a data grid, how can I access the parent data grids row data or the parent rowIndex?

For example in the form below I'd like to access the text fields sitting outside of the nested data grid.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/91739927/196442803-3324ee27-5bab-4f18-b0c8-35c3539209cd.png">

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
