### ISSUE TITLE
Dynamic labels for Text Field based on the input data of another text field

### ISSUE THREAD

**Issue by MounikaMurugeshan** [formio/formio.js#4929]
Hi All, 
In my form, I have 2 text fields, Based on the user input from the input field 1, the label of the 2nd field should change.
Input 1 label: Name
Input 2 label: User, Please enter your age

Now when the user enters the name as John, Label 2 should be changed from 'User, Please enter your age' to 'John, Please enter your age'.

if I use " {{row.name}}, Please enter your age",
Initially when the form load there will not be any data in the name field, so the 2nd label is " , Please enter your age".

Is it possible to have "user" until the name value is entered?

**Comment by MounikaMurugeshan** [comment]
@wag110894 
@travist 
Kindly help me out with this issue

**Comment by michaelfliegner** [comment]
hi! have found a solution? I would need that too.
regards Michael

**Comment by brendanbond** [comment]
@MounikaMurugeshan @michaelfliegner You have access to each component's JSON in the Calculated Value field. Use the Calculated Value field to
1. Check if the data.name property has been populated
2. Change the component's label property (you're just editing JSON programmatically!)
3. Emit a redraw

See this [JSFiddle](https://jsfiddle.net/brendanbond/k6c3aLf2/39/) for a working example (please note that I've factored out the Calculated Value function for readability).
