### ISSUE TITLE
Select Component not checking for "limit" property / missing "load more" button

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#493]
Tested Versions:
- formiojs@2.32.x
- formiojs@3.0.0-alpha.x
- formiojs@3.0.0-rc.x

I have a select component that fills with a resource that have over 100 items.  When accessing the through formview.io the select list renders without problem, but when using Formio.createForm (or createForm in older releases) it ignores the limit set in the select component and uses the default 100.  Further more, the "load more" button at the end is not rendering.  The only solution is to use limit=<count> in the filter parameter of the component.

Examples (using https://mxutsqrnrusfanc.form.io/select):

- [Working](https://formview.io/#/mxutsqrnrusfanc/select) (formview.io)
- [Not Working](https://angular-formview.stackblitz.io/formio/mxutsqrnrusfanc/select) ([code](https://stackblitz.com/edit/angular-formview))

This is the component's configuration:

```json
{
    "autofocus": false,
    "input": true,
    "tableView": true,
    "label": "Resource",
    "key": "resource",
    "placeholder": "",
    "data": {
        "values": [
            {
                "value": "",
                "label": ""
            }
        ],
        "json": "",
        "url": "res",
        "resource": "5b07f4633fa56bac4d45910e",
        "custom": "",
        "headers": [
            {
                "value": "",
                "key": ""
            }
        ],
        "project": "mxutsqrnrusfanc"
    },
    "dataSrc": "resource",
    "valueProperty": "",
    "defaultValue": "",
    "refreshOn": "",
    "filter": "sort=data.shortName",
    "authenticate": false,
    "template": "<span><img src=\"{{ item.data.image }}\" height=\"18\" width=\"24\"/>&ensp;{{ item.data.shortName}}</span>",
    "multiple": false,
    "protected": false,
    "unique": false,
    "persistent": true,
    "hidden": false,
    "clearOnHide": true,
    "validate": {
        "required": false
    },
    "type": "select",
    "labelPosition": "top",
    "tags": [],
    "conditional": {
        "show": "",
        "when": null,
        "eq": ""
    },
    "properties": {},
    "searchField": "data.shortName__regex",
    "limit": "250",
    "lockKey": true
}
```

**Comment by airarrazaval** [comment]
Further looking into the code, the SelectComponent does not look for the filter property in the [loadItems](https://github.com/formio/formio.js/blob/21b1aa9ba54a293a281d02d9ede92f8ca168ef57/src/components/select/Select.js#L259) method.  

A similar code should be added:

```js
if (this.component.limit) {
    const limit = parseInt(this.component.limit, 10) || 0;
    query.limit = limit > 0 ? limit : query.limit;
}
```

**Comment by jhen1422** [comment]
Closing issue.

This should be resolved on the latest 4x renderer. If the issue persists, please open a new issue
