### ISSUE TITLE
[QUESTION] Is it possible to use response from post url in submission link?

### ISSUE THREAD

**Issue by buzzard10** [formio/formio.js#4934]
Hello Guys
i'm using formio in way which send submission to external url. Everything works fine, but i would like to send user after submission to dynamic page which require ID which generate on external page where formio send submission.
Is it possible to get this id from external url and use it in thank you page url?

For example:
1. Formio send data to external url
2. External url response contain id 
3. Formio use this id in thank you page, e.g. domain.com/%id%

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
