### ISSUE TITLE
[BUG] Date/Time component changes the selected date to a new value when defocusing the component

### ISSUE THREAD

**Issue by hbobka** [formio/formio.js#4939]
Hi guys,

I think I found a bug in the date/time component.
When using a date in the format `dd/MM/yyyy` and setting "Enable Time Input" to false, the selected date changes to a new value after clicking outside the component.
Using a date in this format `yyyy/MM/dd` and also with "Enable Time Input" set to false, doesn't produce this effect.

When "Enable Time Input" is set to true, all date formats work as expected.

I'm using: formiojs: "4.14.9"

Greetings
Henry

**Comment by wag110894** [comment]
Hello @hbobka,
This is a known issue that we have created a Ticket for FIO-5628. We will let you know once this issue is resolved.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution! FIO-5628 is in done status
