### ISSUE TITLE
Select Boxes not rendering correctly with label position left / right

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#494]
**Version**
- fromiojs@3.0.0-alpha.x
- formiojs@3.0.0-rc.x

**Issue**

SelectBoxes Component is not styling correctly the `form-group` div containing the select boxes options (style attribute is missing).  

**Steps to Reproduce**

* Create SelectBoxes Component
* Set `Label Position` to `left-left` / `left-right` / `right-left` / `right-right`
* Render form using `Formio.createForm` using `formiojs@3.0.0-*`

[Example Form](https://mxutsqrnrusfanc.form.io/selectBoxes)

**Expected**

Component should render with the following HTML (using https://mxutsqrnrusfanc.form.io/selectBoxes as example).

```html
<div class="form-group has-feedback formio-component formio-component-selectboxes formio-component-selectBoxes">
  <label class="control-label" style="float: left; width: 30%; margin-right: 3%; text-align: right;">Select Boxes</label>
  <div class="form-group" style="margin-left: 33%; width: 66%;">
    <div class="form-check checkbox">...</div>
    .
    .
    .
  </div>
</div>
```

**Actual**

The style attribute is missing (`style="margin-left: 33%; width: 66%;"`).

```html
<div class="form-group has-feedback formio-component formio-component-selectboxes formio-component-selectBoxes">
  <label class="control-label" style="float: left; width: 30%; margin-right: 3%; text-align: right;">Select Boxes</label>
  <div class="form-group">
    <div class="form-check checkbox">...</div>
    .
    .
    .
  </div>
</div>
```

**Comment by wag110894** [comment]
Hello Alfredo,

Are you still experiencing this issue?

Let us know.

Thanks.
