### ISSUE TITLE
Scroll to top on validation error offset by fixed navbar

### ISSUE THREAD

**Issue by chdonncha** [formio/formio.js#4953]
- Formio.js version: 4.14.7
- Famework: Laravel
- Browser: Edge
- Browser version: 107.0.1418.42

Wondering is it possible to include an offset on the scroll to that's used when a validation error is triggered?
Due to having a top navbar with a fixed position Formio does not scroll to the top of the validation error alert.

Instead of seeing the validation error like so:
![image](https://user-images.githubusercontent.com/8567795/202496228-95ca1c8f-27f9-45b8-9ace-5cd55c4b2e3e.png)

When the page scrolls to the top of the form it'll only show the bottom of the alert, which requires the user to then scroll up to see the rest
![image](https://user-images.githubusercontent.com/8567795/203761534-dbc599a2-de17-4098-a300-93c41fd5c793.png)

It is caused by the following CSS:
```css
.fixed-top {
  position: fixed;
  top: 0;
  right: 0;
  left: 0;
}
```

I've included a margin-top offset too but that doesn't seem to effect how Formio determines where to scroll to

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
