### ISSUE TITLE
Signature Component Not Working

### ISSUE THREAD

**Issue by knocknarea** [formio/formio.js#4955]
Without any code changes on our side, the signature component as stopped working. It would appear that this might be the result of updates to the CDN? This only happened in the last couple of 3-5 days.

## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.14.8-10
- Frontend framework: Angular
- Browser: All
- Browser version: All

## Steps to Reproduce
1. Create a Form with a Signature component
2. Attempt to fill in a signature mouse or finger (on tablets)
3. 

## Expected behavior
When user scribbles their signature they should be able to see it being drawn and on presentation of a signature component with existing signature, should be shown.

## Observed behavior
Signature component is blank

## Example

https://user-images.githubusercontent.com/12442390/204277845-2e7bb952-92b3-4706-972b-43f374443ab1.mov

**Comment by knocknarea** [comment]
Correction, it does show existing forms with signatures, if an only if those signatures were created *before* this problem appeared. New signatures are neither shown when drawn or displayed subsequent to form submission.

**Comment by brendanbond** [comment]
I'm not able to trivially reproduce, the signature component is working fine for me on a tablet. Can you provide us with a minimal, reproducible example (say, on a [CodeSandbox](https://codesandbox.io) so we can help you get to the bottom of this?

**Comment by brendanbond** [comment]
I believe we're in the process of standardizing the way the renderer will pull libraries from our CDN which will include tokenizing those URLs so you can self host. Stay tuned!

**Comment by knocknarea** [comment]
@brendanbond Superb!
