### ISSUE TITLE
FormIO Offline Date picker issue in React Native

### ISSUE THREAD

**Issue by RichaMSaxena** [formio/formio.js#4960]
We are getting an error on Formio when its been used in offline mode. Our project is build on react native. 

The issue is, after selecting date when we change focus to another field the date changes automatically to a default date i.e. 08-02-2027.

We also figure out the issue is only with the forms which has date but it works fine with the form which has date time picker.

We're getting error on focus of every form which has date picker. I'm attaching the error log, can anybody help me to fix this issue.

[datePicker_error.docx](https://github.com/formio/formio.js/files/10121932/datePicker_error.docx)

Thank you.

**Comment by olgabann** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
