### ISSUE TITLE
[QUESTION] How can I get a select custom datasource to trigger code on autocomplete?

### ISSUE THREAD

**Issue by miversen33** [formio/formio.js#4968]
This is a simple enough question I think.

I have found that if you provide a URL for select data population, as explained [here](https://help.form.io/userguide/forms/form-components#select), the URL is called with every keystroke on the keyboard (every character entered into the select input).
This is great and I would like to replicate this behavior, however I want a function called instead of calling out to a URL. 

However, using the `custom` data source, it seems that it only calls my function on focus, and the text being searched is not available to my function. I am not really sure what I am doing wrong.

Some images of what I am doing

When setting the data type to URL, you can see that each char entered into the input triggers a URL request
![URL Source](https://user-images.githubusercontent.com/2640668/206034366-182b9ce5-9019-4d93-bf40-58e44dec97aa.png)
![URL Autocomplete Search](https://user-images.githubusercontent.com/2640668/206034364-5f92332d-a088-4543-b030-4d48a0b250d8.png)

However, when using a custom source, you can see the "Custom" code was only ran once (I assume on focus), and was not provided with the current value in the field (which makes sense as at focus, there was nothing in the field).
![Custom source not called](https://user-images.githubusercontent.com/2640668/206034356-a9e1c4f8-34eb-47da-a750-a0753c4b7a7f.png)

I can hack something together with input listeners and the like to make what I want happen, but I feel like I am just missing something.

## Environment
Please provide as many details as you can:

I unfortunately do not have a ton of details on the environment being used here as we are using a version of FormIO that is included with the [NetIQ Designer](https://www.netiq.com/documentation/identity-manager-48/FormioHelp/userguide/form-components/#select) tool.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: Unknown
- Frontend framework: Electron (I don't know the version though)
- Browser: NA
- Browser version: NA

**Comment by brendanbond** [comment]
Without knowing the version of your renderer, it's tough, but you could hook into the [compontentChanged event](https://help.form.io/developers/form-renderer#form-events) in your form controller:
```
instance.on("componentChanged", (componentInstance, componentJson, value, flags) => {
  /* do stuff here */
});
```

Closing this for now
