### ISSUE TITLE
[QUESTION] Does Form.io meet the following criteria?

### ISSUE THREAD

**Issue by GaliusMulmus** [formio/formio.js#4982]
Probably my question does not fit into this forum. Nevertheless I ask for help, because I am a computer science layman. I am supposed to do a market analysis and check form solutions for the following criteria....

- Own compilation of questions and different answer options
- Form readable via csv or xlsx
- Solution can run on an external server, preferably accessible via browser
- Must be a web server
- URL is created and according to rights & roles concept can participate 
- external authentication must be possible
- Keycloak is at like teams 
- Modular system that has one of the following functions: fillable PDF, document is sent, filled in and collected again

**Comment by brendanbond** [comment]
I'm confident that this platform (in particular, our enterprise offering) can help create any form/API/application solution that you imaginable, although I'm not sure I understand some of these requirements.

> Own compilation of questions and different answer options

I guess? Isn't this just a normal form? ✅ 

> Form readable via csv or xlsx

✅

> Solution can run on an external server, preferably accessible via browser

✅

> Must be a web server

✅

> URL is created and according to rights & roles concept can participate

✅

> external authentication must be possible

✅

> Keycloak is at like teams

✅

> Modular system that has one of the following functions: fillable PDF, document is sent, filled in and collected again

✅ to all of the above (if I understand correctly)
