### ISSUE TITLE
Well label not showing in form builder/form render

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#499]
LOVE your work on this project. We have embraced it for one of our products.

Setting a well label saves, but does not display. I verified this on the form builder and the form renderer located here, not just our version.

**Comment by airarrazaval** [comment]
Well is a special kind of HTML element and therefor it does not renders label.  If you wish to display a label and a well try using a Fieldset with a well component inside or just use an HTML element and write the desired html.

**Comment by ProteanHub** [comment]
Is it a bug that I am seeing a label option when adding a well?

**Comment by denisekay** [comment]
Thank you for bringing this to our attention.  You are correct the well should not have a label option

**Comment by ProteanHub** [comment]
Thanks @denisekay

**Comment by jhen1422** [comment]
Closing issue.

This should be resolved on the latest 4x renderer. If the issue persists, please open a new issue
