### ISSUE TITLE
[HELP] How to validate a field that has been modified programmatically?

### ISSUE THREAD

**Issue by datenshi** [formio/formio.js#5001]
I am working with a form that I need to validate on initialization, so for that purpose I use the option: alwaysDirty: true

Then I set the value of several mandatory fields programmatically, but even I set a non empty value, the validation is triggered on the field and show an error
<img width="848" alt="image" src="https://user-images.githubusercontent.com/5069467/209917298-00dd86dc-c2ae-47a0-9273-979379e9cde3.png">

As you can see, the field CX Gen has a valid string (not empty) but the validation warning is still there.

This is how I change set the value, and redraw the component, although I think that is not necessary.
`
const cxGenElem = FormioUtils.getComponent(form.components, 'cxGen');
cxGenElem.setValue(localStorageInfo.home.cxGen);
cxGenElem.redraw();
`

How can I trigger validation after the value was set?

Thanks a lot. :)

**Comment by datenshi** [comment]
Sorry, I found it was my error in the logic to handle the data. With setValue in the proper place the validation works as expected

**Comment by brendanbond** [comment]
Great to hear @datenshi !
