### ISSUE TITLE
[Question/Bug] Is IE11 still supported by formio.js? 

### ISSUE THREAD

**Issue by MichaelStruk-GL** [formio/formio.js#5016]
Is IE11 still supported by formio.js? 

I upgraded formiojs from 4.14.7 to 4.14.8 and encountered an issue where the form does not display in IE11. I tried to update to the latest version 4.14.12 but found that the problem still exists and it exists since 4.14.7-patch.4.

Looks like a transpilation problem, missing polyfill as I can see an error in console:
SCRIPT1002: Syntax error
<img width="711" alt="image" src="https://user-images.githubusercontent.com/101116958/212299792-31b83b80-f8ae-492e-b3e1-e2235a77a831.png">

<img width="726" alt="image" src="https://user-images.githubusercontent.com/101116958/212304820-aa46d4cf-9aaa-491b-a0ed-18841b64c2ec.png">

**Comment by brendanbond** [comment]
What is the console error?

**Comment by MichaelStruk-GL** [comment]
The error in console:

SCRIPT1002: Syntax error
<img width="305" alt="image" src="https://user-images.githubusercontent.com/101116958/212352574-cd57e4fc-493d-45bf-ac92-e76c1d0cf0b1.png">
![image](https://user-images.githubusercontent.com/101116958/212352889-7e0c06f8-057b-4358-b2ce-798785f4f955.png)

`class BMF` is part of the `browser-md5-file` npm package on which formiojs has reference.

**Comment by brendanbond** [comment]
Hey @MichaelStruk-GL our official position is that we no longer support IE11. 

if you'd like to fix on your end, it looks like IE11 support in browser-md5-file may have been [wiped out](https://github.com/forsigner/browser-md5-file/issues/10) even though it claims to have compatibility with IE9+. Translated from Chinese, it reads something like "[t]he author wrote the es6 code which uses the class api, the packaged source code is still a class, and has not been transferred to es5, so the whole army is wiped out directly in ie."
