### ISSUE TITLE
[Question] Missing changelog for 4.13.0-rc.2 

### ISSUE THREAD

**Issue by francesco-gallo** [formio/formio.js#5018]
I had a breaking change regarding components' custom validation on webform.js that I could trace back to 4.13.0-rc.2 (I had no issues on 4.13.0-rc.1), but there is no changelog for that specific version.

What were the changes for that version?

I found that in the lines
```
          formattedKeyOrPath = this._parentPath + formattedKeyOrPath;
          if (!err.formattedKeyOrPath) {
            err.formattedKeyOrPath = formattedKeyOrPath;
          }
```
if "err" is a string and not an object it doesn't show any error message box

Thanks.

**Comment by lane-formio** [comment]
Looks like the changelog for rc.3 is the same as rc.2

https://github.com/formio/formio.js/commit/6ac161c0a5e2e78cb5562568f058f7f00ea50a8c

You might also peruse https://github.com/formio/formio.js/compare/v4.13.0-rc.1...v4.13.0-rc.2
