### ISSUE TITLE
Example of FormBuilder in README.md NOT working

### ISSUE THREAD

**Issue by kamanwu** [formio/formio.js#502]
I follow the example in README.md to create a Form builder embedded right within a html page.
And got these error:
FormBuilder.js:72 Uncaught TypeError: Cannot read property 'components' of undefined
    at FormBuilder.create (FormBuilder.js:72)
    at FormBuilder.setForm (Form.js:87)
    at FormBuilder.render (Form.js:103)
    at Function._Formio2.default.builder (FormBuilder.js:102)
    at window.onload (form-builder.html:8)

**Comment by hardfi** [comment]
You need to add 'components' array as a prop and create this variable, like this:

`Formio.builder(document.getElementById('builder'), {components: this.formioComponents});`

&

`let formioComponents;`

**Comment by kamanwu** [comment]
Thank you very much.  

I am reading the docs at : https://formio.github.io/formio.js/docs/class/src/FormBuilder.js~FormBuilder.html , and understand the 2nd arguments should be: Either a Form JSON schema or the URL of a hosted form via. form.io.

Now, I want to learn:  after I made some changes at client via FormBuilder (suppose the form is hosted form via form.io), how can I save the changes back to form.io?

**Comment by kamanwu** [comment]
I am confused.  This module is ONLY for browser?
Can I use it in server side (nodejs)?

when I use nodejs to run code like:
var Formio = require('formiojs');
var formio = new Formio('URL to get a form.io form');

I get error like this:

Formio.Headers = Headers;
                 ^

ReferenceError: Headers is not defined
    at Object.<anonymous> (/home/formiojs-test/node_modules/formiojs/Formio.js:1172:18)

**Comment by jhen1422** [comment]
Closing issue.

If the issue persists, please open a new issue
