### ISSUE TITLE
Form.io not generating Valid Swagger API

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#503]
Just moving a comment from the gitter chat to here (maybe belongs to the resourcejs library)

We are starting to check on the best way to integrate Form.io with GraphQL. 
We though about using the Form.io Swagger API as a quick start (https://myawesomeproject.form.io/spec.json) and then transforming it using something like https://github.com/yarax/swagger-to-graphql . But it seems that the spec.json does not provide a valid swagger Json file. Even using an empty project the file gets rejected http://online.swagger.io/validator/debug?url=https://tmczibpkavvswnk.form.io/spec.json 

Best!

**Comment by jhen1422** [comment]
This should be resolved
If the issue persists, please open a new issue
