### ISSUE TITLE
[BUG] Radio Component Boolean value is not rendered in html mode

### ISSUE THREAD

**Issue by mohanakannan9** [formio/formio.js#5032]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.15.0-rc.13
- Frontend framework: 
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create a Form with Radio Component with two values true and false
2. Save the form with true selected 
3. Render the form in html mode. 

## Expected behavior
The Label against the value true (or false for that matter) should be  displayed 

## Observed behavior
The Label against the value true (or false) is not displayed

**Comment by Sidiro23** [comment]
We are not able to reproduce this behavior
