### ISSUE TITLE
Nested form component in [Form] does not save submission data

### ISSUE THREAD

**Issue by asalhani** [formio/formio.js#504]
@travist @Vercjames @YuryRybakSoftensity @randallknutson

Today, I faced a strange behavior. The thing is I have created a form of type **[Form]**, not wizard. Then I added a sub form (nested form) component to it. On submitting the form, I noticed that _the data in subform (nested form) is not being captured and hence all fields for nested forms are empty._ So when rendering the submission, all fields in nested form have the default empty value (-).

Then I switched [Form] to **[Wizard]** and added the same nested form component. This time the data for nested form saved as expected and rendred correctly

Please consider this issue as **_CRITICAL_** since both forms and Nested forms are used extensively.

**Comment by YuryRybakSoftensity** [comment]
@asalhani Thank you for your reporting!
We already know about this issue and we are working on it.

**Comment by asalhani** [comment]
@YuryRybakSoftensity
 Any update? 
Thank you..

**Comment by asalhani** [comment]
@jhen1422  @travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update so far?

**Comment by jhen1422** [comment]
This issue should be resolved
