### ISSUE TITLE
how to override validator

### ISSUE THREAD

**Issue by amirreza58** [formio/formio.js#5040]
in day component there is init function:

```
init() {
    super.init();
    this.validators = ['day', 'maxDate', 'minDate', 'minYear', 'maxYear']

....

  }
```
how can i override 'day' validator in js.

in my custom component (99% like day component)

```
const DayContainer = Formio.Components.components.field;

class CustomDayComponent extends DayContainer {
...

init() {
    super.init();
    this.validators = ['customday', 'maxDate', 'minDate', 'minYear', 'maxYear']

....

  }
....

}
```

and i used :

```
Formio.Rules.addRule('customday', {
            message(component) {
                return component.t(component.errorMessage('invalid_day'), {
                    field: component.errorLabel,
                    data: component.data
                });
            },
            check(component, setting, value) {
                console.log('customday validator');
                return true;
            }
        })
```

Formio.Rules.getRules shows my customday but its not working (not called ,console.log('customday validator'))

**Comment by namti** [comment]
I have the same question. In my case, I need to add my custom rules. Any clues are appreciated.

**Comment by brendanbond** [comment]
FWIW we're actually in the process of revamping how validations work. Check out the [`checkRule` function](https://github.com/formio/formio.js/blob/6a0fe9c59fe2738cd5b8a6feb3d4e4afb512f0ce/src/validator/Validator.js#L1124), does that apply your rule and validate?

**Comment by demetris-manikas** [comment]
@amirreza58 I was able to plugin my custom validator by
`this.validator.validators['customMin']  = {
            key: 'validate.customMin',
            hasLabel: true,
            message(component: any, setting: any) {
                console.log('Hooooooooooooooooorrrrrrrrreeeeeeeeeeeeeeeeeeeeeyyyyyyyyyyyyyyy')
                return component.t(component.errorMessage('minLength'), {
                    field: component.errorLabel,
                    length: setting,
                    data: component.data
                });
            },
            check(component: any, setting: any, value: any) {
                console.log('Hooooooooooooooooorrrrrrrrreeeeeeeeeeeeeeeeeeeeeyyyyyyyyyyyyyyy')
                const minLength = parseInt(setting, 10);
                if (!value || !minLength || (typeof value !== 'string') || component.isEmpty(value)) {
                    return true;
                }
                return (value.length >= minLength);
            }
        }`
Instead of Rules.addRule

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
