### ISSUE TITLE
[BUG] Form Builder component search is not translated

### ISSUE THREAD

**Issue by DerH4NNES** [formio/formio.js#5045]
## Environment

- Hosting type
- Formio.js version: master (01-30-2023)
- Frontend framework: no
- Browser: chrome

## Steps to Reproduce
1. Add translation to form builder
2. search for translated component title
3. component will not be displayed

## Expected behavior
Translated components can be found in component search

## Observed behavior
Only original title can be filtered

## Solution
https://github.com/formio/formio.js/pull/5044

**Comment by radovan-jupa** [comment]
This issue should be closed. PR #5044  was already merged.

**Comment by DerH4NNES** [comment]
merged into master
