### ISSUE TITLE
[BUG] When two the date/time component are in fieldset and formio is localizated the second datepickr is not shown.

### ISSUE THREAD

**Issue by petrbizon** [formio/formio.js#5054]
When two the date/time component are in fieldset and Formio is localizated, the second datepickr is not shown.

## Steps to Reproduce
1. Get to the [https://jsfiddle.net/kr1eagf9/](https://jsfiddle.net/kr1eagf9/)
2.  Click on the first Date / Time component and the datepicker is shown
3.  Click on the second Date / Time component and the datepicker is not shown

## Example
[https://jsfiddle.net/kr1eagf9/](https://jsfiddle.net/kr1eagf9/)

Please help. Thank You.
Petr Bizon

**Comment by Abhishek7Tech** [comment]
Hi @petrbizon can I help you out in resolving this issue?

**Comment by petrbizon** [comment]
Hi @Abhishek7Tech  , It would be nice. What are You thinking about it?

**Comment by Abhishek7Tech** [comment]
@petrbizon  I am thinking of creating a boolean variable which will handle the state of datepicker. 
Like the default value will be false. When user clicks it will be true and form will be shown. When user clicks again it will became false again.

**Comment by petrbizon** [comment]
@Abhishek7Tech  I am not sure where are You wanted add such code?
I found this file:
[https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js](https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js)

Next I am thinking, why is this problem only when is Formio localizated. When I changed the name of constant from 'cs' to 'en', so problem disapeard, but datepicker is in english.

I recorded that when there is 'cs' so Formio is downloading this file:
[https://cdn.form.io/flatpickr-formio/4.6.13-formio.1/l10n/flatpickr-cs.js](https://cdn.form.io/flatpickr-formio/4.6.13-formio.1/l10n/flatpickr-cs.js). When there is 'en', so is not downloading such file.

I also recorded, then first date/time component has two inputs and first input is gray in Firefox:
![image](https://user-images.githubusercontent.com/29502760/216817480-929c9df8-5601-47c1-8ea7-43edb5f95e0c.png)
the second one has only the first input.

**Comment by Abhishek7Tech** [comment]
@petrbizon Yes you are correct. I also tried the same. There is some issue with the library.

**Comment by petrbizon** [comment]
@Abhishek7Tech  : Yes en is default language:

row 194 of [https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js](https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js):

```
              if (locale && locale.length >= 2 && locale !== 'en') {
                return Formio.requireLibrary(
                  `flatpickr-${locale}`,
                  `flatpickr-${locale}`,
                  `${Formio.cdn['flatpickr-formio']}/l10n/flatpickr-${locale}.js`,
                  false,
                  () => this.initFlatpickr(Flatpickr)
                );
              }

```

**Comment by Abhishek7Tech** [comment]
@petrbizon Hi, I found a solution! I mean a workaround....
         
![Screenshot (35)](https://user-images.githubusercontent.com/93655183/216823048-cbc0f7e4-dd22-4174-8462-558a710cc2f2.png)

**Comment by petrbizon** [comment]
I dont undastand it, but well done! Thank You!

Both datepickrs are really shown, but they are not returning value to date/time component. After clicking on time it is not shown in date/time component.

**Comment by Abhishek7Tech** [comment]
@petrbizon I think the required file is rendered only 1st time that's why the date and time component is only shown the first time.

**Comment by petrbizon** [comment]
@Abhishek7Tech Yes, you are right. I changed the code in 
[https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js](https://github.com/formio/formio.js/blob/master/src/widgets/CalendarWidget.js)

on row 194 from 
```
              if (locale && locale.length >= 2 && locale !== 'en') {
                return Formio.requireLibrary(
                  `flatpickr-${locale}`,
                  `flatpickr-${locale}`,
                  `${Formio.cdn['flatpickr-formio']}/l10n/flatpickr-${locale}.js`,
                  false,
                  () => this.initFlatpickr(Flatpickr)
                );
```
to

```
              if (locale && locale.length >= 2 && locale !== 'en') {
                Formio.requireLibrary(
                  `flatpickr-${locale}`,
                  `flatpickr-${locale}`,
                  `${Formio.cdn['flatpickr-formio']}/l10n/flatpickr-${locale}.js`,
                  true
                );
                Formio.libraryReady(`flatpickr-${locale}`).then(() => this.initFlatpickr(Flatpickr));
              }

```
and it is running right. Flatpicker is inited two times.

I am not sure, if it is good solution, but it is working.

Thank You for Your help!

**Comment by Abhishek7Tech** [comment]
@petrbizon  Yes it is better than mine work around.

Welcome and Good luck with your project

**Comment by bobslee** [comment]
I experience the same issue with multiple Calendar widgets and localization.

### TESTS (manual)

I tested with a datetime component (Calendar widget, by flatpickr).

**Multiple Calendar widgets - No localization**
Multiple widgets (flatpickr) work and are displayed.

**One Calendar widget - With localization**
Widgets are displayed and localization works.

**(!) Multiple Calendar widgets - With localization**
Widgets are NOT displayed (of course localization will not appear).

**Good to know**
By updating the `language` of the form, it does work (really!) with multiple Calendar widgets.
I checked in similar way, with the `setLanuage` from the example:
https://formio.github.io/formio.js/app/examples/language.html

### Question / Suggestion

I don't have a solution for this issue (I studied the code as well).

Would the `requireLibrary` suggestion/change above, https://github.com/formio/formio.js/issues/5054#issuecomment-1418638847 , something to submit in a PR ?
But leave the `polling` argument to `false`.
Or coud a core developer check this out ?

**Comment by petrbizon** [comment]
Hello,

thank You for message. I mean, that in current version of FormIO.JS somebody meanwhile repaired it.

Look there:
https://github.com/formio/formio.js/commit/757cf3a123c49c61f1230cceb046812cd14645f2

**Comment by petrbizon** [comment]
Have I close the issue?

**Comment by bobslee** [comment]
@petrbizon Thanks for your message too!
Affirmative, it works since the commit you mentoined.
Is backporting to v4.x.x in consideration?

**Comment by petrbizon** [comment]
@bobslee I am sorry, I dont know. I am not part of development. I downloaded somewhere version 5.0.0-rc.2, compiled it and it is working. I am closing the issue.
