### ISSUE TITLE
Upgrade/Allow to Bootstrap 5

### ISSUE THREAD

**Issue by tacman** [formio/formio.js#5060]
Bootstrap 5 has a lot of improvements, it'd be great if formio allowed it.  Related to  #4790.

Obviously, formio rocks the way it is.  But when integrating the builder or renderer on a site that's based on bootstrap 5, it gets messy.

**Comment by brendanbond** [comment]
Hey @tacman thanks for filing this issue. This is definitely on our roadmap and (as far as I know) is going to be included in the renderer when we release enterprise version 8.1.0 in the coming months. Stay tuned!
