### ISSUE TITLE
How to set the value of components to null

### ISSUE THREAD

**Issue by ousmorez** [formio/formio.js#5061]
## Environment
After selecting a component such as a textfield or a number, and entering a value for them and deleting it, you'll see formio acting like this:

![uuu](https://user-images.githubusercontent.com/50699824/218315441-931dfce8-c475-4b72-ac26-aa1bf4a97753.gif)

In the submission JSON part, we also have textField and number, but after deleting the values inside the inputs, the number is deleted generally and the textField represents the empty string, here my question is, how can I make them null? I don't want the textField to be an empty string because there is a big difference between an empty string and a null.
Also I don't want the number to be deleted, I want to make it null but it isn't possible.

I already tried to access them from outside using `window.Formio.Components.components.textfield...` and `window.Formio.Components.components.number...` but it doesn't work! There seems to be another function besides emptyValue or setValue or ... that performs the named actions in upper layers and i have no idea what's that.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: Latest
- Frontend framework: js
- Browser: Chrome, Firefox
- Browser version: latest

## Steps to Reproduce
1. Click [here](https://formio.github.io/formio.js/app/builder)
2. Select a textfield and a number
3. Act like the GIF file

## Example
![uuu](https://user-images.githubusercontent.com/50699824/218317741-03cf7af8-b49f-477c-b538-e01ff3920263.gif)

**Comment by brendanbond** [comment]
Although the renderer will be opinionated as far as how it will structure the submission data out-of-the-box, this is possible just using the `createForm` API to [manually set the submission data](https://formio.github.io/formio.js/app/examples/jsfiddle.html), for example when the component is changed:

```
Formio.createForm(document.getElementById('formio'), formDefinition).then(function(form) {
  form.on('change', ({
    changed: {
      component,
      value
    }
  }) => {
    if (!value) {
      form.submission.data[component.key] = null;
    }
  })
});
```

Here I'm checking for a falsy component value, and setting that property to null on the submission data object. See [here for a working example.](https://jsfiddle.net/brendanbond/k6c3aLf2/43/)

**Comment by ousmorez** [comment]
Thank you for answering, but forms are not always that simple. For example, if these two fields are inside two containers, this code will no longer work:

```json
const formDefinition = {
  components: [
   {
            label: "Container",
            tableView: false,
            key: "container",
            type: "container",
            input: true,
            components: [
                {
                    label: "Container",
                    tableView: false,
                    key: "container1",
                    type: "container",
                    input: true,
                    components: [
                        {
  
      type: "textfield",
      input: true,
      key: "player",
      label: "Player"
    },
    {
      type: "number",
      input: true,
      key: "number",
      label: "Number"
      },
      {
        label: "Show Submission",
        action: "custom",
        key: "showSubmission",
        type: "button",
        custom: "showSubmission(data)"
      }
      ]
      }
      ]
      }
  ],
  settings: {},
  properties: {},
}
Formio.createForm(document.getElementById('formio'), formDefinition).then(function(form) {
  form.on('change', ({
    changed: {
      component,
      value
    }
  }) => {
    if (!value) {
      form.submission.data[component.key] = null;
    }
  })
});

const showSubmission = (data) => console.log(data.container);
```
What should I do in these complicated cases?

And also as a more general question, how can I make emptyValue null?

@brendanbond
