### ISSUE TITLE
[BUG] Select component does not show the expected selected option

### ISSUE THREAD

**Issue by andreinitescu** [formio/formio.js#5069]
Steps:

1. Go to https://jsfiddle.net/bfwrzjp1
2. Note two things:
a. The `valueProperty` is set to the property `_id`:  

```
"valueProperty": "_id"
```

b. The item template is set as a concatenation of id and name:
```
 "template": "<span>{{ item._id }} - {{ item.data.name }}</span>"
```

3. Scroll to the very last item with the name "5b8c1362c02c2e5386440724 - Travis Corp".
4. Click away so that the drop down closes.
5. There are two problems. 
First, the selected option is `5b8c1362c02c2e5386440724` instead of `5b8c1362c02c2e5386440724 - Travis Corp`. 
Second, if you look to the network requests, there was an additional request done when the item was selected: `https://example.form.io/company/submission?limit=10&skip=11&limit=10&skip=11`

Is there a workaround to these problems?

I also try to set ``` "idPath": "_id",``` but it does not make any difference.

**Comment by Alexandr-Lonski** [comment]
Hi! Thank you for your message! We checked the operation of the select by the link, everything work correctly. Could you attach a video with the incorrect operation of the select component?

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
