### ISSUE TITLE
Question: Modal Panel - set text on "Click to set value" button (and theme)

### ISSUE THREAD

**Issue by therabreal** [formio/formio.js#5077]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.14.10, 4.15.0-rc.14
- Frontend framework: [Sandbox ](https://formio.github.io/formio.js/app/sandbox) for reproduction
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1.  Use json below to create modal panel in [Sandbox ](https://formio.github.io/formio.js/app/sandbox)
```json
    {
      "title": "Panel (title)",
      "tooltip": "panel tooltip",
      "hideLabel": true,
      "modalEdit": true,
      "key": "panel",
      "type": "panel",
      "label": "Panel (label)",
      "input": false,
      "tableView": false,
      "components": [
        {
          "label": "Text Field",
          "tableView": true,
          "key": "textField",
          "type": "textfield",
          "input": true
        }
      ]
    }
```

3. In rendered mode this displays a button with label "Click to set value" in grey color. 

![image](https://user-images.githubusercontent.com/51825659/222005800-29a96988-259c-4ea6-b4da-cf63af19535f.png)

4. When clicked it opens the model edit.

![image](https://user-images.githubusercontent.com/51825659/222005922-84259b5a-a74d-489f-b898-823ccffbe4d8.png)

5. Question is how to change the text and theme/color of  the "Click to set value" button.

6. Another question is how to change the text on the save, cancel, and delete buttons on the modal (close confirmation) dialog.

![image](https://user-images.githubusercontent.com/51825659/222006194-48ff17f8-d6b2-4dc1-a3be-95f27e01bbd3.png)

**Comment by wag110894** [comment]
Hello @therabreal, 

You can accomplish this by CSS. Here is an example of San Francisco Digital Services GitHub and their Form.io theme.

https://github.com/SFDigitalServices/formio-sfds

https://formio-sfds.herokuapp.com/

Hope that this helps.

**Comment by therabreal** [comment]
Thank you for your response @wag110894 - much appreciated.

I had a look at the links - interesting for sure but I don't think there is an answer to my question in there.

Maybe my use of the word "theme" distracted from the real question (although Formio Sandbox does use the word "Theme" as setting for the color of the panel heading).

The main question is: Can we control/alter the "Click to change value" text shown on the button when modal editing is set for a panel.
