### ISSUE TITLE
Form Builder Component: Layout-->Column has improper alignment

### ISSUE THREAD

**Issue by Rishikap123** [formio/formio.js#5078]
## Environment
Please provide as many details as you can:

- Formio.js version: 4.14.6
- Browser: IE

## Steps to Reproduce
1. Drag and drop Column component.
2. Display -> column properties
3. Observe that the alignment is improper

## Expected behavior
Component: Layout-->Column should have proper alignment
## Observed behavior
 Form Builder Component: Layout-->Column has improper alignment

**Comment by wag110894** [comment]
Hello @Rishikap123, We no longer support IE11. Is this issue happening using other browsers?
