### ISSUE TITLE
Survey component gives type error

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#508]
When adding a survey component, I immediately get a javascript error:
TypeError: undefined is not an object (evaluating 'n[t.key].checkConditions')

The questions and answers in the modal are un-editable.
<img width="1126" alt="screen shot 2018-06-06 at 10 49 34 am" src="https://user-images.githubusercontent.com/1413491/41045947-724e07f4-6977-11e8-9bd6-d775c94d81e3.png">

**Comment by jhen1422** [comment]
This issue has been resolved
