### ISSUE TITLE
[BUG] Pasting a number starting with zeroes deletes digits from the end of the number

### ISSUE THREAD

**Issue by Skipperwastaken** [formio/formio.js#5106]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: -
- Frontend framework: -
- Browser: any

## Steps to Reproduce
1. Create a number field
2. Paste a number starting with zeroes into it

## Expected behavior
The number appears without the leading zeroes
## Observed behavior
The number appears with leading zeroes, but without the last few digits. The number of digits lost is equal to the amount of leading zeroes. When the focus changes, the leading zeroes get removed as well.
## Example
Paste the number 001111 into any number field. Instead of 1111, 0011 will appear.

**Comment by daneformio** [comment]
Number values are expected to not have leading 0s. If you want there to be leading 0s in a value, a text field component is a better choice.
For the number conversion to scientific notation, I have created a ticket. Ticket FIO-8290 for internal tracking purposes.

**Comment by jeriah-formio** [comment]
FIO-8292

**Comment by lane-formio** [comment]
After review we don't expect to change this behavior, but would always be happy to review any contributions.
