### ISSUE TITLE
Simple Builder Question: how to set up a custom save action

### ISSUE THREAD

**Issue by tacman** [formio/formio.js#5116]
What an awesome tool!   Thanks for releasing it.

There's so much there, that I think I'm missing something easy.  How to I instantiate the form builder and set what the save button should do?  I would like to submit the builder json to my own endpoint.

Thanks.

**Comment by lane-formio** [comment]
<div>Agent Olga Bannikova linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/48552">48552</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
It is already possible. The builder doesn't send anything to any server unless you have a custom save button to send the Builder Form JSON to the API.

**Comment by tacman** [comment]
can you document how to do that?

**Comment by edwinanciani** [comment]
Here is an example https://formio.github.io/formio.js/app/examples/customendpoint.html

**Comment by tacman** [comment]
Thanks!  Somehow I missed this.
