### ISSUE TITLE
[BUG] Switching Wizard pages unescapes HTML-escaped input values

### ISSUE THREAD

**Issue by johnflavin-fw** [formio/formio.js#5124]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: We use 4.14.3, but I can reproduce this in the current https://formio.github.io/formio.js/app/builder.html
- Frontend framework: N/A, custom JS
- Browser: Safari, Chrome
- Browser version: as of today, Safari Version 16.4 (18615.1.26.11.22), Chrome Version 111.0.5563.146 (Official Build) (arm64)

## Steps to Reproduce
1. Use the form builder to create a Wizard with two pages
2. On Page 1, add a text field input. (We won't use any inputs on Page 2. It could contain whatever inputs you want, or none.)
3. View the rendered form
4. In the input on Page 1, enter a value with HTML-escaped characters.
5. Switch to Page 2, then back to Page 1.

## Expected behavior
1. When we switch back to the first page, the input value that appears is the same value that the user entered.
2. When the form is submitted, the input value that appears in the text field is identical to the input value that gets submitted.

## Observed behavior
1. When we switch back to the first page, the input value that appears in the form has been modified. Any HTML-escaped characters in the input have been unescaped.
2. Even though the input appears in the form unescaped, the underlying form data is still escaped. So if the form gets submitted, the submitted input value is not identical to what the user sees in the input field.

## Example

Input value entered by user
```html
&lt;script&gt;alert(&#39;XSS&#39;);&lt;/script&gt;
```
Input value that appears in the form input field after switching to Page 2 then back to Page 1
```html
<script>alert('XSS');</script>
```
Input value that gets submitted with the form after switching to Page 2 then back to Page 1
```html
&lt;script&gt;alert(&#39;XSS&#39;);&lt;/script&gt;
```

Form schema
```json
{
    "display": "wizard",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "title": "Page 1",
            "label": "Page 1",
            "type": "panel",
            "key": "page1",
            "components": [
                {
                    "label": "Text Field",
                    "applyMaskOn": "change",
                    "tableView": true,
                    "key": "textField",
                    "type": "textfield",
                    "input": true
                }
            ],
            "input": false,
            "tableView": false
        },
        {
            "title": "Page 2",
            "label": "Page 2",
            "type": "panel",
            "key": "page2",
            "input": false,
            "tableView": false,
            "components": []
        }
    ]
}
```

Screenshot
<img width="1155" alt="Screenshot 2023-04-05 at 1 45 29 PM" src="https://user-images.githubusercontent.com/99210085/230175922-fafd0bbc-058a-4f60-8b9c-2aa6a09fea4c.png">

**Comment by travist** [comment]
This works as expected. The strategy with Form.io rendered forms is to sanitize the render phase and not the input phase as you may need the data as it was input in the form. It is up to the rendering to ensure that sanitization occurs and block all XSS attempts, which the renderer already does.
