### ISSUE TITLE
[BUG] Select default value not update

### ISSUE THREAD

**Issue by homashevchenko** [formio/formio.js#5131]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
- Browser: Chrome
- Browser version:  112.0.5615.49

## Steps to Reproduce
1. Add select with 3 diferent options
2. Add default value
3. Change options keys

## Expected behavior
Default value update on new key
## Observed behavior
Default value key is old
Show 4 options
![image](https://user-images.githubusercontent.com/22855299/231979416-2dc25db2-7d94-4fee-a216-7c30f0b75a75.png)
Can you clear the default value when changing the key?

Thanks

**Comment by AlexanderLihodievskiy** [comment]
@homashevchenko Thank you for notifying us about this error. The error really exists and we will fix it soon.

**Comment by Tatsiana8** [comment]
@homashevchenko This is expected behaviour. The default value is not a reference, it is an actual value added to the component JSON. When you make changes to your keys, you need to update the default value as well.
