### ISSUE TITLE
[BUG] not applying css, if we try to render form html component with content have basic html & css  

### ISSUE THREAD

**Issue by syam2023** [formio/formio.js#5132]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: ^5.3.0-rc.2
- Frontend framework: Angular 13
- Browser: Chrome
- Browser version: 

## Steps to Reproduce
1. Goto from builder, drag html element from layout
2. In html content add basic html & css 
3. like  below this
4.  "<!DOCTYPE html>
      <html>
      <head>
      <style>
      body {background-color: powderblue;}
      h1   {color: blue;}
      p    {color: red;}
      </style>
      </head>
      <body>
      
      <h1>This is a heading</h1>
      <p>This is a paragraph.</p>
      
      </body>
      </html>"
![Uploading Screenshot 2023-04-14 at 17.01.41.png…]()

5. Check preview the css are applied to h1 & P.
6. But try render the same created form html component, in that case the html is rendering  but css is not applied

## Expected behavior
css should apply 

## Observed behavior
css not applied.

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:
{
    "addons": [],
    "allowCalculateOverride": false,
    "allowMultipleMasks": false,
    "attributes": {},
    "attrs": [
        {
            "attr": "",
            "value": ""
        }
    ],
    "autofocus": false,
    "calculateServer": false,
    "calculateValue": "",
    "clearOnHide": true,
    "conditional": {
        "eq": "",
        "show": null,
        "when": null
    },
    "content": "<!DOCTYPE html>\n<html>\n<head>\n<style>\nh1   {color: red;}\np    {color: red;}\n</style>\n</head>\n<body>\n\n<h1>This is a heading</h1>\n<p>This is a paragraph.</p>\n\n</body>\n</html>",
    "customClass": "",
    "customDefaultValue": "",
    "dataGridLabel": false,
    "dbIndex": false,
    "defaultValue": null,
    "description": "",
    "disabled": false,
    "encrypted": false,
    "errorLabel": "",
    "hidden": false,
    "hideLabel": false,
    "id": "e1sdbqh",
    "input": false,
    "key": "html1",
    "label": "HTML",
    "labelPosition": "top",
    "modalEdit": false,
    "multiple": false,
    "overlay": {
        "height": "",
        "left": "",
        "style": "",
        "top": "",
        "width": ""
    },
    "persistent": false,
    "placeholder": "",
    "prefix": "",
    "properties": {},
    "protected": false,
    "redrawOn": "",
    "refreshOn": "",
    "refreshOnChange": false,
    "showCharCount": false,
    "showWordCount": false,
    "suffix": "",
    "tabindex": "",
    "tableView": false,
    "tag": "p",
    "tooltip": "",
    "type": "htmlelement",
    "unique": false,
    "validate": {
        "custom": "",
        "customPrivate": false,
        "multiple": false,
        "required": false,
        "strictDateValidation": false,
        "unique": false
    },
    "validateOn": "change",
    "widget": null
}

```js
// your code here
```

**Comment by Alexandr-Lonski** [comment]
@syam2023  Thank you for notifying us about this error. The error really exists and we will fix it soon.

**Comment by syam2023** [comment]
@Alexandr-Lonski  Thanks, But when can we expect above fix

**Comment by Tatsiana8** [comment]
Thank you for taking the time to report this issue! I have created a ticket for our backlog. 
For internal reference: FIO-8262

**Comment by daneformio** [comment]
We have reviewed this issue and found a solution with dompurify that will not require a code change.
These docs have information that will help you https://help.form.io/developers/form-development/form-renderer#form-renderer-options, see the "sanitizeConfig" section
