### ISSUE TITLE
How to replace ckeditor in Content component with quill (or another component)?

### ISSUE THREAD

**Issue by mm-dsibinski** [formio/formio.js#5139]
The _Content_ component in FormIO uses `ckeditor` to compose the HTML.
I'd like to replace `ckeditor` with another editor, for example with `quill`.

I [found](https://github.com/formio/formio.js/blob/master/docs/file/src/components/textarea/TextArea.js.html) this is supported for a _TextArea_ component with `wysiwyg` set to `true`. I can specify `quill` as `editor`, which will make the `TextArea` use `quill`.

Is it possible for _Content_ component as well? I didn't find any similar properties [for Content component](https://github.com/formio/formio.js/blob/master/docs/file/src/components/content/Content.js.html).

The reason for replacing the editor can be licensing, which is not as flexible for `ckeditor` as it is for `quill`.

**Comment by alexandraRamanenka** [comment]
Hi! For the Content component the editor is used only in the component's settings in the builder and for now there is no built-in oppurtunity to change it.
