### ISSUE TITLE
Confirm field removal

### ISSUE THREAD

**Issue by jkapenieks** [formio/formio.js#5143]
Hi, is it possible to to add a confirmation dialog before a field is removed. There are cases I want to prevent removal of a field if there are results submitted and stored related to this field.

**Comment by travist** [comment]
I agree this would be handy.  It is already done for container elements that have multiple fields within it, but we currently do not have a feature that does it for all fields.  This would need to be implemented as a feature request.

**Comment by lane-formio** [comment]
This is now possible with the Form Builder option "alwaysConfirmComponentRemoval". The documentation can be found here: https://help.form.io/developers/form-development/form-builder#form-builder-options
