### ISSUE TITLE
Conditional logic

### ISSUE THREAD

**Issue by maartenvr98** [formio/formio.js#5144]
Does version 5 have the new Simple Conditions with multiple conditions?

https://help.form.io/userguide/logic-and-conditions#simple-conditions-8.1.0-release

**Comment by Alexandr-Lonski** [comment]
Hi! Thank you for your message! No, this functionality is not in 5 version.

**Comment by travist** [comment]
This is one of our Enterprise Features and is not part of this OSS library.
