### ISSUE TITLE
Using blob: to load a worker is unsafe

### ISSUE THREAD

**Issue by PatrikTrefil** [formio/formio.js#5146]
The library loads a worker using `blob:`, which is considered to be unsafe ([w3c security considerations](https://www.w3.org/TR/CSP2/#source-list-guid-matching)).

## Steps to reproduce:

1. Create a page with a form builder
2. Serve this page with safe CSP configuration (e.g. `script-src: 'self' cdn.form.io; img-src 'self' data:;`)
3. Open the page in a web browser
4. Create a new text field in the form

Error in console: `Content Security Policy: The page’s settings blocked the loading of a resource at blob:http://localhost:8080/b264ab82-7298-467b-98fc-390c07a8e412 (“script-src”).`

CSP would have to allow `blob:` in `script-src` or `worker-src`, which is undesirable. This makes any site using formio.js vulnerable.

**Comment by travist** [comment]
I am not sure we load any workers with blob so this report is kind of confusing... In fact, we do. not even use any workers in this library. Are you certain that the issue was not triggered by some other script on the page other than the form builder?
