### ISSUE TITLE
Plugin hooks are not being fired when using <formio> component

### ISSUE THREAD

**Issue by asalhani** [formio/formio.js#516]
@travist @Vercjames @YuryRybakSoftensity @randallknutson

I have a requirement were I have to modify the HTTP request which is being fired on loading resources/forms. I checked the documentation and I found that Formio.js has [Plugin hooks.](https://github.com/formio/formio.js/wiki/JavaScript-API#plugin-hooks) 

I configured a simple plugin as instructed.
```
 let simplePlugin = {
            priority: 0,
            init: function(formio) {
                debugger;
            },
            preRequest: function (requestArgs) {
                debugger;
            },
            request: function(requestArgs){
                debugger;
            },
            wrapRequestPromise: function(promise, requestArgs){
                debugger
                return promise;
            },
            preStaticRequest: function(requestArgs){
                debugger;
            },
            staticRequest: function(requestArgs){
                debugger;
            },
            wrapStaticRequestPromise: function(promise, requestArgs){
                debugger
                return promise;
            }
        };
        Formio.registerPlugin(simplePlugin, 'simplePlugin');
```

The case: the hooks is being fired when loading the new builder component. I designed a simple form which has a nested form component on it. When I open the form is submission mode, I’m expecting that one of the hooks should be fired too so I can modify the HTTP request headers before it’s being sent to the server. Unfortunately, nothing happened and the request bypassed all the hooks.

I loaded the same form but this time using pure formio.js library, the hooks there are working as expected. 

So either I’m doing something wrong or there is a bug in <formio> component which prevents hooks from being fired.

Appreciate your comment on this issue ASAP

Note: I opned the[ same issue under "angular-formio" project](https://github.com/formio/angular-formio/issues/178) just in order to be noticable for all team members.

**Comment by asalhani** [comment]
@jhen1422  @travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update so far?

**Comment by jhen1422** [comment]
Closing issue.

If the issue persists, please open a new issue
