### ISSUE TITLE
FormIO - Reorder the pages in formIO by dragging and rearranging

### ISSUE THREAD

**Issue by MounikaMurugeshan** [formio/formio.js#5161]
I want to swap page 3 and page 4. Is it possible to reorder the FormIO pages by dragging and reordering them? 
<img width="815" alt="Screenshot 2023-05-15 at 4 40 16 PM" src="https://github.com/formio/formio.js/assets/105483885/2d563b0a-30a8-4fc9-b840-d7892cdbf254">

I checked the possibilities of adding CDK-drag-drop to the existing FormIO Pages. But it didn't work. Is there any other ways to achieve this functionality in angular-formIO?

**Comment by MounikaMurugeshan** [comment]
@brendanbond kindly help me with this

**Comment by travist** [comment]
This was added to our builder at one point.

https://github.com/formio/formio.js/commit/c8144c55cbf1f89001be9dd93b0b55bbefc2b95d

It seems that maybe it no longer works?  Can you try an older version of the builder/renderer?

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
