### ISSUE TITLE
Uppercase issue with Text field

### ISSUE THREAD

**Issue by Bnayak123** [formio/formio.js#5162]
Environment:
Hosting type : Form.io

Version: Latest version (Even in online [demo builder](https://formio.github.io/angular-demo/#/forms/builder))

Browser: Microsoft Edge

Browser version: 113.0.1774.42 (Official build) (64-bit)

Steps to Reproduce
1 select one text component then select Uppercase option .
2 select another text component. 
3 add this API name to the first text component in calculated value.

Expected behavior
component value should display with Uppercase. 

{
  "display": "form",
  "components": [
    {
      "label": "Text Field",
      "applyMaskOn": "change",
      "tableView": true,
      "case": "uppercase",
      "calculateValue": "value=data.textFieldValue;",
      "key": "textField",
      "type": "textfield",
      "input": true
    },
    {
      "label": "Text Field Value",
      "applyMaskOn": "change",
      "tableView": true,
      "key": "textFieldValue",
      "type": "textfield",
      "input": true
    }
![UppercaseIssue](https://github.com/formio/formio.js/assets/113301614/13a81094-9435-438f-97ca-5c5c372ed99e)

  ]
}

The issue is When the Uppercase is selected and the field is given a calculated value, the uppercase selection is not honored. above is the JSON For your Information please check above Gif.

**Comment by travist** [comment]
This is a very minor issue that seems to only apply if you have a calculated value. I would say that if you are already writing a calculated value, then you should just apply the uppercase there like so.

```
value=data.textField.toUpperCase();
```

This is a "won't fix" issue.
