### ISSUE TITLE
Time Format Issue

### ISSUE THREAD

**Issue by Bnayak123** [formio/formio.js#5164]
{
  "display": "form",
  "components": [
    {
      "label": "Time",
      "tableView": true,
      "calculateValue": "value= new Date ();",
      "key": "time",
      "type": "time",
      "input": true,
      "inputMask": "99:99"
    }
  ]
}

Time component format is selected as HH:MM:ss but the issue is seconds are not shown
![Time Format Issue](https://github.com/formio/formio.js/assets/113301614/fa29c4f6-3a6f-4a8e-9b56-3df687f29f4c)
 and if we change any format always shows only hours with minutes only.

**Comment by travist** [comment]
I agree this is a bug. We will add it to our backlog.

**Comment by daneformio** [comment]
Ticket for internal tracking: FIO-8155

**Comment by Tatsiana8** [comment]
@Bnayak123 @daneformio the Format setting is located on the Data tab and its description saying that it is a format for saving value. It does not and should not affect how the values is displayed. For now we don’t have a setting to change the format of displaying value for the time component with HTML5 input.

**Comment by lane-formio** [comment]
As a workaround for this issue, you can accomplish this behavior using the "date/time" component.
Set the format as desired:
![image](https://github.com/formio/formio.js/assets/110409244/0492f72d-f680-445b-b71c-fd8ce1b57335)
Disable date input:
![image](https://github.com/formio/formio.js/assets/110409244/feca9a8a-a277-419b-a9e9-00ae8baac13e)
Then set your custom default value as demonstrated in OP.
