### ISSUE TITLE
Form Builder: Phone Number Component - Features not appropriate for the components

### ISSUE THREAD

**Issue by nishit4777** [formio/formio.js#5169]
### Environment:

- Hosting type : Form.io

- Version: Latest version (Even in online [demo builder](https://formio.github.io/angular-demo/#/forms/builder))

- Browser: Microsoft Edge

- Browser version: 113.0.1774.42 (Official build) (64-bit)

### Steps to Reproduce

1. We have a form with Phone number component added.

1. Click on Edit Phone number component.

### Expected behavior

1. Phone number Component has upper/lower case in Data section which is not required.

### Observed behavior

1. Phone number Component has upper/lower case option in Data section to edit.

### GIF

![Phone number - Defect](https://github.com/formio/formio.js/assets/54327380/4dce2624-3687-4993-98a5-a1cd40893808)

### Form JSON

```
{
  "display": "form",
  "components": [
    {
      "label": "Phone Number",
      "applyMaskOn": "change",
      "tableView": true,
      "case": "lowercase",
      "key": "phoneNumber",
      "type": "phoneNumber",
      "input": true
    },
    {
      "type": "button",
      "label": "Submit",
      "key": "submit",
      "disableOnInvalid": true,
      "input": true,
      "tableView": false
    }
  ]
}
```

**Comment by travist** [comment]
I agree that this should be fixed. If you wish to get this fix in quickly, then my guess is that you could add some "conditionals" to the following edit form components.

https://github.com/formio/formio.js/blob/master/src/components/textfield/editForm/TextField.edit.data.js#L29

Here is an example of adding conditionals to these...

https://github.com/formio/formio.js/blob/e827fdc5c8966ef03ff8c6a64b1f9fbd1a19386f/src/components/form/editForm/Form.edit.form.js#L32

**Comment by VikkiAlenn** [comment]
@nishit4777 The issue seems to be fixed https://formio.github.io/formio.js/app/sandbox.html. Let us know if you still see this issue.
![Screenshot_1905](https://github.com/formio/formio.js/assets/105641597/855bcb63-d757-4093-957a-9dd520060d79)

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
