### ISSUE TITLE
Removes ID attributes from JSON whenever new component is added

### ISSUE THREAD

**Issue by Bnayak123** [formio/formio.js#5171]
Form Json

 

{
  "display": "form",
  "components": [
    {
      "label": "Text Field 123",
      "applyMaskOn": "change",
      "tableView": true,
      "key": "textField123",
      "type": "textfield",
      "input": true
    },
    {
      "label": "Text Area 123",
      "applyMaskOn": "change",
      "autoExpand": false,
      "tableView": true,
      "key": "textArea123",
      "type": "textarea",
      "input": true
    },
    {
      "label": "Select",
      "widget": "choicesjs",
      "tableView": true,
      "key": "select",
      "type": "select",
      "input": true
    },
    {
      "type": "button",
      "label": "Submit",
      "key": "submit",
      "disableOnInvalid": true,
      "input": true,
      "tableView": false
    }
  ]
}

Whenever a new element is inserted into the Form any existing “id” tag is removed. For mor info refer to Attached video

**Comment by Bnayak123** [comment]
https://github.com/formio/formio.js/assets/113301614/cf357ad9-d43b-4470-85fb-1d85883f4125
For above defect

**Comment by travist** [comment]
This is expected and is not a defect. There should not be any "id" property saved in the components since this is simply used by the "builder" as a way to keep internal track of the components. As soon as the form is saved, it is expected that the ids will be removed.
