### ISSUE TITLE
Select component - Data getting cleared when changing data source.

### ISSUE THREAD

**Issue by TusharGoel14** [formio/formio.js#5177]
In SELECT Component when selecting any data source type and add some values. Then we move to any other data source and come back, previous values are getting cleared.

![ChangeSourceTypeInSelect](https://github.com/formio/formio.js/assets/84577843/099af8eb-199f-4cce-91f5-c456b90b27e9)

**Comment by travist** [comment]
I believe this is as-designed, but I can see how this may not be desirable. The idea here is to keep unnecessary configs out of your form json as you are building the form and making these kinds of changes. I would consider changing the behavior of this. Ultimately, what is causing this is that the "clearOnHide" option is set on the Data Source Values within the builder form, which seems to be here..  https://github.com/formio/formio.js/blob/master/src/components/select/editForm/Select.edit.data.js#L96

I am curious if you added a ```clearOnHide: false``` to this component json if it would solve this particular issue. If possible, could you make this change to see if it fixes the problem and if so, then feel free to submit a PR and we will evaluate it for inclusion of our future renderer version.
