### ISSUE TITLE
Form Component not coming getting  Cannot read properties of undefined (reading 'shortcut')

### ISSUE THREAD

**Issue by daanishlive** [formio/formio.js#5196]
Formio component is not coming

**Comment by daanishlive** [comment]
![check](https://github.com/formio/formio.js/assets/42837008/fd50c010-7d36-4669-815f-3ab49d896866)

**Comment by travist** [comment]
Please provide a jsfiddle of this issue happening so that we can investigate further.

**Comment by daanishlive** [comment]
Actually it is happening because we put the wrong html in the form
