### ISSUE TITLE
Translation issue for File Component label "Drop files to attach, or"

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#520]
**CONTEXT**

I am using Form.io to store project's translations using a Translations resource.  The structure of the resource is the following:

```json
{
  "components": [{
      "input": true,
      "inputType": "text",
      "label": "Label",
      "key": "label",
      "type": "textfield"
    },
    {
      "input": true,
      "inputType": "text",
      "label": "English",
      "key": "en",
      "type": "textfield"
    },
    {
      "input": true,
      "inputType": "text",
      "label": "French",
      "key": "fr",
      "type": "textfield"
    },
    {
      "input": true,
      "inputType": "text",
      "label": "Spanish",
      "key": "es",
      "type": "textfield"
    },
    {
      "input": true,
      "inputType": "text",
      "label": "Arabic",
      "key": "ar",
      "type": "textfield"
    },
    {
      "input": true,
      "inputType": "text",
      "label": "Chinese",
      "key": "zn",
      "type": "textfield"
    },
    {
      "input": true,
      "inputType": "text",
      "label": "Russian",
      "key": "ru",
      "type": "textfield"
    }
  ]
}
```

Where `label` is the label we want to translate.  The other components maps to a specific language code (defined by their key) of the label's translation.  

**ISSUE**

When the File Component is rendered it builds the following text node:

https://github.com/formio/formio.js/blob/76eb26435690ff361f035d6da81c11010c0bfae1/src/components/file/File.js#L271

As you can see, the text node appends extra spaces to both sides of the label `' Drop files to attach, or '`.  Because Form.io trims all inputs, this specific label cannot be translated.  Instead of using spaces in the text node, the same can be achieved with CSS.

**PROPOSED FIX**

Change

https://github.com/formio/formio.js/blob/388e6e4678e143418b1ee319415071ec090e9649/src/sass/formio.form.scss#L204-L207

to

```scss
.formio-component-file .fileSelector .glyphicon, .formio-component-file .fileSelector .fa {
  font-size: 20px;
  margin: 0 5px;
}
```

Change 

https://github.com/formio/formio.js/blob/388e6e4678e143418b1ee319415071ec090e9649/src/sass/formio.form.scss#L209-L211

to

```scss
.formio-component-file .fileSelector .browse {
    cursor: pointer;
    margin: 0 5px;
}
```

change

https://github.com/formio/formio.js/blob/76eb26435690ff361f035d6da81c11010c0bfae1/src/components/file/File.js#L271

to

```js
this.text('Drop files to attach, or'),
```

The added margin to both sides is to adjust for `ltr|rtl` support.

**Comment by darabi** [comment]
This problem still exists in formio 4.1. The sources have changed a bit and some parts are now moved to the templates, but the main problem remains.

Would you accept a PR to fix this?

**Comment by wag110894** [comment]
We welcome a pull request to fix this item.

Thank you!

**Comment by pmatulionis** [comment]
If this is still an issue for someone, I found a solution that works with "@formio/angular": "5.3.0"
You have to translate all three parts separately in your translation JSON, for e.g.:

```
export const FORM_RENDERER_LANGUAGE = {
    lt: {
        'browse': 'pasirinkite',
        'Drop files to attach,': 'Įkelkite failus, kuriuos norite pridėti,',
        'or': 'arba'
    }
};
```
then provide that translation for your renderer or builder:

```
      [renderOptions]="{
        language: 'lt',
        i18n: {
          lt: FORM_RENDERER_LANGUAGE.lt
        }
      }"
```
and it translates nicely:
![image](https://user-images.githubusercontent.com/6089316/192534505-a1613c93-a499-4840-8b76-13843635511d.png)
