### ISSUE TITLE
Selectbox onlyAvailableItems validation always fails

### ISSUE THREAD

**Issue by michealharrington** [formio/formio.js#5211]
When using selectboxes with onlyAvailableItems validation enabled, the input is always invalid because it is using Radio's validation while selectbox's data structure is vastly different.
It appears to be comparing the available options, example { "a": false, "b": false, "c": false } to a single option's value of "a". It tries to normalize the value which converts it to {"a": true}. The object comparison that falls will always fail, because {"a": true} != { "a": false, "b": false, "c": false }.

What we'd really want to do is validate the value of "a" is one of the "keys" within the option's object.

**Comment by travist** [comment]
I can confirm that this is a bug and can reproduce. We will create a ticket for it on our end so that it can be prioritized.

**Comment by michealharrington** [comment]
Any updates on this bug?

**Comment by lane-formio** [comment]
This issue is fixed by [pull request 5302](https://github.com/formio/formio.js/pull/5302).
