### ISSUE TITLE
text placeholder dependent on select

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#5214]
1. The placeholder of my text field depends on the select field.
2. In the text field's `customConditional`, what is the code I can write so that it only runs when select changes, not when keys are being typed in the text field?

**Comment by travist** [comment]
You should be able to do this with the Logic tab in the text field, which triggers on the "change" event. This only occurs when they select the item and does not trigger on the change event. 

You can see this if you go to https://formio.github.io/formio.js/app/sandbox.html and then load the following sandbox id.

6481ccca5954aaeb24cf8c62

**Comment by bilogic** [comment]
@travist 

Thanks! However, I need more complex logic, is there a way to do it using customAction?

This was as far as I went

```JSON
      "logic": [
        {
          "name": "Change Placeholder",
          "trigger": {
            "type": "event",
            "event": "change"
          },
          "actions": [
            {
              "name": "change placeholder",
              "type": "customAction",
              "customAction": "instance.placeholder = data.select"
            }
          ]
        }
      ],
```

**Comment by bilogic** [comment]
> You should be able to do this with the Logic tab in the text field, which triggers on the "change" event. This only occurs when they select the item and does not trigger on the change event.

Actually, the placeholder is being replaced on every single key typed into the text field. You can verify this by using dev tools to modifying the placeholder, and typing a key into text field. Placeholder will be restored to `data.select`.
