### ISSUE TITLE
Color picker from `HTML Element` component

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#5223]
Hi, I need a color picker.

1. What is the use case for `HTML Element`?
2. I tried adding to its `Content`
    ```
    <input type="color" id="bg-color" value="{{data.textArea}}">
    <label for="bg-color">Background color</label>
    ```
3. It made the color picker show up, but I was not able to get its value after `Submit`

**Comment by brendanbond** [comment]
An `<input />` html element (added via a Content or an HTML component) wouldn't automatically plug in to the renderer's data system. To get a color picker working in Form.io you'll need to [create a custom component](https://help.form.io/developers/form-development/custom-components) or write your own javascript to extract the value out of the <input type="color" /> tag
