### ISSUE TITLE
Data not deleting from the grid for a single record

### ISSUE THREAD

**Issue by ishan-bhuta-squarerisk** [formio/formio.js#5225]
formio.full.min.js:2 Uncaught TypeError: Cannot delete property '3' of [object Array]

Getting this error when trying to remove one iterated value from a grid.

![image](https://github.com/formio/formio.js/assets/122768529/854cb7a6-9050-46c6-b8d1-cb68e959a723)

**Comment by olgabann** [comment]
@ishan-bhuta-squarerisk I was not able to replicate the issue (video attached). Please, provide steps if it was not your scenario. 

https://github.com/formio/formio.js/assets/128126697/4e4c9fe2-8999-4f98-8e72-e95f5c759f23

**Comment by ishan-bhuta-squarerisk** [comment]
Issue fixed at my end
