### ISSUE TITLE
Pushing buttons together to the left

### ISSUE THREAD

**Issue by bilogic** [formio/formio.js#5226]
![image](https://github.com/formio/formio.js/assets/946010/901d0fd6-56ff-45b5-86e7-f5fa9ce9d1e1)

I can't seem to move `Make primary` button just right beside `Activate`. Any idea?

**Comment by travist** [comment]
If you inspect the html, what does it look like?

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
