### ISSUE TITLE
[BUG] Data Grid issue with Select component with ChoicesJS widget

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#5229]
Affected versions:
- the issue occurs since `v4.14.11`
- `v4.15.1-rc.1` (latest 4.15.x)
- `v5.0.0-rc.18` (latest 5.0.0-rc.x)

See the screenshot below:

A "datagrid" with a "select" component, with widget "ChoicesJS".
The choices (data) isn't rendered properly, it's invisible, get's underneath.

Note: This issue doesn't occur with an "editgrid" component.

![image](https://github.com/formio/formio.js/assets/328803/b80d5ac4-0840-4250-9753-5b91028259ef)

**Comment by bobslee** [comment]
Related issue: #5216

**Comment by travist** [comment]
May be resolved with https://github.com/formio/formio.js/pull/5299.  Will push out a version soon and test it.

**Comment by WalterMoar** [comment]
FYI, I'm still seeing the cut off select list in v4.17.2.
![image](https://github.com/formio/formio.js/assets/35532993/574436cb-fabf-4850-80f3-40661bd6f818)

**Comment by jeriah-formio** [comment]
This issue seems to be resolved with FJS version 4.19.1
