### ISSUE TITLE
Server side use

### ISSUE THREAD

**Issue by MiguiTE** [formio/formio.js#5245]
I have a SAAS project that relies on @formio/angular to render forms. We perform some client-side validations and compute values for components with formio, but we also have some workflows that modify resources based on some criteria.

We want to implement the same client-side validation/formulas but server-side. We tried to install formiojs serverside (on a NodeJS backend) but it is impossible as it depends on a client-side environment.

Is there a way to get formiojs utils server-side? It would be great to use the entire package server side, but a minimum necessary would be formiojs/utils functions such as `eachComponent`, `findComponents`.

Any way to install formiojs (or at least minimum utils functionalities) server-side on a NodeJS environment?

**Comment by brendanbond** [comment]
We do this ourselves in [the formio OSS server](https://github.com/formio/formio/blob/master/src/resources/Validator.js), what is preventing you from running validations in NodeJS?

**Comment by MiguiTE** [comment]
Formiojs is throwing an error when installing and importing it. 

Environment:
- Nodejs 20.3.0
- Express 4.18.2

What I did:
- Install formiojs: `npm i formiojs`
- Import utils: `const { Utils } = require('formiojs');`

It throws:
```
C:\{{path_to_app}}\api\node_modules\formiojs\components\file\File.js:103
var webViewCamera = navigator.camera || Camera;
                    ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (C:\{{path_to_app}}\api\node_modules\formiojs\components\file\File.js:103:21)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (C:\{{path_to_app}}\api\node_modules\formiojs\components\index.js:23:36)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)

Node.js v20.3.0
```

What may I be doing wrong?

**Comment by jesusduranevenbytes** [comment]
Same thing happening here when installing formiojs v4.14.15 (latest as of now) in our node 20 environment. Is there any compatibility limitation with node versions?

**Comment by blakbarn** [comment]
I am getting the same error due to the code running server side where there is no navigator available. I ended up commenting that out of the code as a test and it worked great. The only thing that needs to be done is check for navigator before calling navigator.camera.

**Comment by travist** [comment]
You will need to shim these constructs in your server side application. We do this as well in our OSS. It is ugly, but works.

https://github.com/formio/formio/blob/master/src/util/util.js#L20
