### ISSUE TITLE
EditGrid: editGridSelectRow and editGridUnSelectRow events not triggered

### ISSUE THREAD

**Issue by ambra-zuc** [formio/formio.js#5248]
I saw in the [documentation ](https://help.form.io/developers/form-development/form-renderer#form-events ) that 3 events are documented for the EditGrid component: editGridAddRow, editGridSaveRow, editGridDeleteRow. 
However, looking at the [source code](https://github.com/formio/formio.js/blob/4.14.x/src/components/editgrid/EditGrid.js), editGridSelectRow and editGridUnSelectRow events also seem to exist. 
I tried to subscribe to the these events as indicated in the documentation example, but I am not receiving anything when the row is clicked:

`form.on('editGridSelectRow',` (selected) => {
    console.log(selected);
});``

Everything seems to work fine for the documented events (editGridAddRow, editGridSaveRow, editGridDeleteRow).

Am I missing something?
See also #4041 

Thanks
 
Ambra

**Comment by brendanbond** [comment]
Seems to work fine for me (add a row then click it): https://jsfiddle.net/brendanbond/rjpfyacw/3/
