### ISSUE TITLE
EditGrid: editGridDeleteRow should have row data as argument

### ISSUE THREAD

**Issue by ambra-zuc** [formio/formio.js#5249]
editGridDeleteRow  fires when a row has been deleted, and has only one argument: the index of the row that was deleted.
Would it be possible to add also "component" and "row" to the arguments, as in the editGridSaveRow event?
Thanks

**Comment by travist** [comment]
If you submit a pull request with this change, we would be happy to review it and include it in a future release.

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
