### ISSUE TITLE
CK Editor - add custom button

### ISSUE THREAD

**Issue by gwynncausing** [formio/formio.js#5253]
I would like to add a custom button in the content container, is there any way to do that?

I tried to add a classic ckeditor unto the options but it gives duplicate error, I also tried to add a text in the code in on of the issues provided here [CK Editor - Hiding Image and Media from the toolbar](https://github.com/formio/formio.js/issues/3181#issuecomment-1246140529) but it doesn't work.

**Comment by travist** [comment]
Can you please provide a fiddle of what you are doing and show it not working. Everyone seems to agree that it does work and the examples provided illustrate how this can be done.
