### ISSUE TITLE
Question - How can I dynamically render a component as a Radio button on desktop (wide screen) and as a Dropdown on mobile screens

### ISSUE THREAD

**Issue by Dev-Trilok** [formio/formio.js#5260]
Hello @travist  @randallknutson 
I'm looking for a component that can handle a series of rows containing radio buttons. On a wide enough screen, I would like the layout to be compact, with multiple rows displayed side by side. However, when the screen width falls below a certain threshold, I want each row to be displayed with the row label taking up the full width, and the radio buttons replaced with either a dropdown or a stacked series of radio buttons.
on large screen

![image](https://github.com/formio/formio.js/assets/48346388/d36cd6f1-2143-4b1f-b76a-17821070e18f)

 it would look on a small screen like:
 
 
![image](https://github.com/formio/formio.js/assets/48346388/78934099-b5bc-4e19-a9af-433d663503b7)

Is it possible to create a custom component that can achieve this dynamic render different component based on the screen size?
Thanks

**Comment by travist** [comment]
Absolutely this can be done with a custom component.... It actually may even be able to be accomplished by editing the radio template to turn into a select on smaller screens. Here are some docs on how to do that.

https://help.form.io/developers/form-development/form-templates#overriding-templates

**Comment by Tatsiana8** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
