### ISSUE TITLE
"Allow Manual Override of Calculated Value" prevents calculation altogether

### ISSUE THREAD

**Issue by BradBouquio** [formio/formio.js#5264]
Steps to recreate: Create a number component with default settings. Create a radio component with two options, Yes and No with the values 1 and 0. In the calculated value section of the radio component, enter a test calculation eg: value = data.number > 5 ? 1 : 0; This calculation works, however when you check the box "Allow Manual Override of Calculated Value" in the radio component, you would expect the calculation to still happen and also be able to override it if you want to. Instead, the calculation doesn't happen at all.

**Comment by travist** [comment]
For some reason the Radio believes it has been manually modified and rejects the calculation. Does this affect other components or just Radio?

**Comment by BradBouquio** [comment]
Other components as well. Tested on select, number, and checkbox and the same issue occurs.

**Comment by olgabann** [comment]
@BradBouquio I couldn't replicate the issue you mentioned in formiojs@4.19.0. Please let us know if you still face the same issue.

https://github.com/formio/formio.js/assets/128126697/900f401c-ed7a-4329-b878-9a0e09a5b8e5

**Comment by BradBouquio** [comment]
Yes the issue has been resolved 👍
