### ISSUE TITLE
Conditional from multiple fields does not match docs

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#5267]
Hi,

When trying to create conditional logic I noticed the Formio doc show that I can do conditional logic using multiple fields without JavaScript, however when using this library I don't seem to see the same options available? 

Am i doing something wrong?

![image](https://github.com/formio/formio.js/assets/12785492/e54f0256-6997-492a-834f-45b18e970eef)

**Comment by jadmsaadaot** [comment]
Hello @AnthonyPhan ,

I am also looking for the same thing. Did you find a solution?

**Comment by jadmsaadaot** [comment]
I actually found that this is a wontfix https://github.com/formio/formio.js/issues/5144

**Comment by travist** [comment]
We built out the advanced conditions as an Enterprise add-on. The OSS version still has the "simple" conditionals widget (which still works) but is more limited in functionality.
