### ISSUE TITLE
change component property after form render

### ISSUE THREAD

**Issue by Nabinsharma123** [formio/formio.js#5273]
in the documentation i see that we can change a component value after render the form like this.

```
const email = form.getComponent('email');
email.setValue('joe@examle.com');
``` 
is there has any property like "setDisable()" to set the disable property to "true" after render the form

**Comment by travist** [comment]
There is a setDisabled method.

https://github.com/formio/formio.js/blob/master/src/components/_classes/component/Component.js#L3376

But it also looks like you need to pass along the "element" you wish to disable, which is inconvenient. You may be able to get it to work by referencing the "refs.input" array of elements. Something like this maybe.

```
const email = form.getComponent('email');
email.refs.input.forEach((input) => email.setDisabled(input, true));
```
