### ISSUE TITLE
[BUG] alwaysConfirmComponentRemoval

### ISSUE THREAD

**Issue by adhonay** [formio/formio.js#5283]
Version Formiojs: 4.14.15

alwaysConfirmComponentRemoval = true

It doesn't work when you have a component open in editModal

Its behavior is working normally for a component already created, but on the modal screen it displays the warning and even clicking on no to cancel the request to remove the component, it ignores and removes it anyway.

![image](https://github.com/formio/formio.js/assets/14100568/5c5f6b52-d88b-48a1-a52e-966942d3feba)

**Comment by Zack-Dx** [comment]
#5379
