### ISSUE TITLE
Formbuilder Searchbar is not working with latest 5.x version.

### ISSUE THREAD

**Issue by sravani9995** [formio/formio.js#5288]
we are using form builder controls dynamically
In form builder search field If user enter some text after removing that text with backspace from  search field  page is refreshing

**Comment by travist** [comment]
I tested this in our latest builder and it does not behave as you describe, but it does seem to be broken. I am going to change the label of this issue so that it captures the problem more accurately.

**Comment by radovan-jupa** [comment]
I fixed search bar issue in  https://github.com/formio/bootstrap/issues/85

**Comment by lane-formio** [comment]
This should be resolved in our latest rc (5.0.0-rc.48)
