### ISSUE TITLE
File Upload as base64 issues

### ISSUE THREAD

**Issue by hochunang** [formio/formio.js#5295]
I have used the formiojs@4.13.2 to create a File Component (with base64 storage). When submitting the form, **submission.data** I get
 
![image](https://github.com/formio/formio.js/assets/54022779/c460f597-d3fd-4ffa-8cbe-68d45183d982)
(url have store base64 string when filesize is small)

However, if I upload 400MB file, I can't get the base64 string. What happens? How to solve it?
![image](https://github.com/formio/formio.js/assets/54022779/5a7438c9-dabf-436e-a594-c251cd34e62d)

**Comment by alexandraRamanenka** [comment]
@hochunang MongoDB does not allow to store documents that are larger that 16 MB. That's why it does not work with 400MB file and this is not recommended to use base64 storage unless you are going to upload only small files.
