### ISSUE TITLE
[SECURITY BUG] Populate returns user password and other protected fields

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#531]
We just detected a problem with the populate parameter for the GET queries.

I have a User resource that has a password field with the protected attribute. When I query directly the users there is no problem, but If I query the User resource and populate the owner field it will return the hashed password and all protected fields of the users...the query would be something like

https://myapi.form.io/user/submission?populate=owner&limit=1

![image](https://www.dropbox.com/s/78yqcza0ym4wrne/Screenshot%202018-06-15%2010.36.26.png?dl=1)

Thank you!

**Comment by jhen1422** [comment]
Closing issue.

This should be resolved on the latest 4x renderer. If the issue persists, please open a new issue
