### ISSUE TITLE
In layout component, in WYSIWYG, bulleted list and numbered list is not working as expected

### ISSUE THREAD

**Issue by Drashti-Shah** [formio/formio.js#5320]
While using storybook of formio library, in layout component Rich text editor is not working properly
The bulleted list and numbered list are not showing bullets and number index respectively
Anyone please tell me how can override the CSS of the library to make it work or how can I change the CSS manually inside lib in order to display bullets and numbers in the list?

![Screenshot 2023-08-17 224209](https://github.com/formio/formio.js/assets/67795694/be9b0604-82c3-47b1-97f8-ad2b5ec6b485)
![Screenshot 2023-08-17 224114](https://github.com/formio/formio.js/assets/67795694/23cbf3f4-590e-432d-afc6-c44a6fdc3c4c)
[https://www.loom.com/share/adffd78706a4447ca68056a0fc4f2fc3?sid=017f2082-da78-4d67-8fb8-b2a3d0a9303e](url)

**Comment by travist** [comment]
Which editor are you using. I just tried this out on a new form with our latest renderer and it seems to be working fine. I suspect that you may have some CSS in your application that is killing the UI here.
