### ISSUE TITLE
Not able to clear the default values for Survey component.

### ISSUE THREAD

**Issue by TusharGoel14** [formio/formio.js#5322]
1) Take the survey component under the Advanced
2) Add some questions and Values
3) Make some questions with default values and save
4) now try to clear the default value 
5) Observed Not able to clear the default values once we entered.

PFA the attached GIF for the better understanding of the issue.

Note : We can clear the values if we remove the same from FORM JSON but is there any way to clear the default value without changing the Form Json?

![SurveyComponent](https://github.com/formio/formio.js/assets/84577843/4ba70d8b-d2d5-4130-9a82-e40f93b27616)

**Comment by travist** [comment]
You would need to edit the component using the JSON editor to clear the values (wrench icon on the field). I know the UI is not the best with this method, but that is how you would do it.
