### ISSUE TITLE
Is we can bind only 4 level/hierarchy  of data grid within another data grid control?

### ISSUE THREAD

**Issue by MuhammadAhsanKamal** [formio/formio.js#5363]
I have tested on formio builder screen but here i found an issue. you can see in the screenshot in the 2nd column of parent grid we can add only 4 level of heirarchy while in the 3rd column we can add more then 4 column
![image](https://github.com/formio/formio.js/assets/54303862/00086c9b-0a77-418f-a3a4-88ce6e9647fa)

**Comment by olgabann** [comment]
@MuhammadAhsanKamal 

https://github.com/formio/formio.js/assets/128126697/e107d57f-7eba-4088-96d3-da19d2f7c2c0

Hi, I was not able to replicate the issue in formiojs@4.19.0. Please review the attached video and let us know if the scenario was reproduced incorrectly.

**Comment by Sidiro23** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
