### ISSUE TITLE
[BUG] Select component's custom data logic overwrites the choiceJs plugin search filter

### ISSUE THREAD

**Issue by bogist** [formio/formio.js#5368]
### Steps to Reproduce
Create a form that contains a SelectComponent where you add custom logic to filter data based on any rule.
Select the component and start typing in order to filter dynamically the list of options.
Click outside the component's area so that the dropdown closes.
Click again on the component to display the filtered list.

### Expected behavior
The user is presented with a list of entries that are filtered once by the custom logic and once by the choicesJs search input.
Component should have the same behavior as if it would have predefined values.

### Observed behavior
The user is presented with a list of entries that has been reset to the logic from the custom data field and the search input is populated without any effect over the displayed list

**Comment by daneformio** [comment]
Can you provide a jsfiddle and a form JSON example of this issue?

**Comment by bogist** [comment]
Closing the topic as this is not reproducing anymore
