### ISSUE TITLE
Multi select drop down inner box shows

### ISSUE THREAD

**Issue by ramkumar1984** [formio/formio.js#5369]
Hi, 

I have used select component and selected multiple value checkbox in the form builder.  When trying to render this multi select drop down shows inner box shows. Please find attachment highlighted yellow color.  Can anyone please sugguest. 

Thanks,
Ramkumar
<img width="503" alt="reasoncode" src="https://github.com/formio/formio.js/assets/57900873/7e1c204d-7069-42c8-a18a-4eb042f583a7">

**Comment by daneformio** [comment]
@ramkumar1984 Can you please provide your versions and a minimally reproducible example in form json or in https://jsfiddle.net/ ?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
