### ISSUE TITLE
Disabling form fields with conditions

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#537]
Instead of hiding form field with conditions, we would like to disabled them with conditions.
Specially when using buttons.

![image](https://user-images.githubusercontent.com/8056394/41903927-d15d4dd6-793f-11e8-8209-934155b9ba36.png)

**Comment by travist** [comment]
This should be possible using the up-and-coming Field logic system. I would need to verify with @randallknutson if "form invalid" is a trigger for field logic.

**Comment by airarrazaval** [comment]
Maybe a global variable (e.g.:  `formValid` or `errors` - array with available validation errors) which updates itself on form change could be available for the user.

**Comment by jhen1422** [comment]
This is available in using the logic system found on our beta site http://beta.form.io/
