### ISSUE TITLE
Formio.builder is not a function Error

### ISSUE THREAD

**Issue by priya30m** [formio/formio.js#5373]
I am trying to get my custom component included in formio builder navigation bar.
I am using below code, however Formio.builder is giving error - Uncaught TypeError: Formio.builder is not a function"

Is there anything missing?

```
<link rel="stylesheet" href="https://cdn.form.io/js/formio.full.min.css">
<script src="https://cdn.form.io/js/formio.full.min.js"></script>
<div id="builder"></div>
```

```
Formio.builder(document.getElementById('builder')
...
...
)
```

**Comment by Plonq** [comment]
Ran into same problem. I think they haven't updated the documentation. This worked for me using npm package, might work for CDN too.

```javascript
import { FormBuilder } from "formiojs";
new FormBuilder(document.getElementById('builder'), {}, {});
```

**Comment by ZenMasterJacob20011** [comment]
The links for the script and link tag are missing the prefix formio before the js. The html should look like the following
```
<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdn.form.io/formiojs/formio.full.min.css'>
<script src='https://cdn.form.io/formiojs/formio.full.min.js'></script>
<div id="builder"></div>
```
with the javascript being `Formio.builder(document.getElementById('builder'),{},{});`
For more information on how to create custom component please refer to our [help docs](https://help.form.io/faq/tutorials-and-workflows/custom-component)
