### ISSUE TITLE
Uncaught TypeError: Cannot add property initialized, object is not extensible

### ISSUE THREAD

**Issue by j-perl** [formio/formio.js#5382]
Hi,

We're currently using formiojs (4.12.1) and react-formio (4.3.0) and we're trying to update these dependencies to the latest stable versions (4.17.2 and 5.2.3 respectively at the time of this writing), however, when displaying a form, we're getting this error, which comes from this piece of code : 

https://github.com/formio/formio.js/blob/22b32cfadbbb02bcdc919403951bcaecca0c2202/src/Webform.js#L339C3-L366

Apparently, modifications are made to the i18next object that is [not extensible](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible).

> In [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), attempting to add new properties to a non-extensible object throws a TypeError.

Strangely enough, I couldn't find any thread mentioning this issue so I'm wondering whether we are not the only one having it. Do you have any idea what I could be doing wrong?

**Comment by j-perl** [comment]
For those having the same problem, I've found that importing and passing our own instance of i18next through the options parameter makes the problem go away.

**Comment by lane-formio** [comment]
@j-perl 
Thanks for the contribution. As you seem to have found a solution I am going to go ahead and close this out.
