### ISSUE TITLE
Render a radio as button group

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#5395]
Hi 👋

Is it possible in the form builder to configure a radio component to render as a group of radio button as show below:

![image](https://github.com/formio/formio.js/assets/12785492/2b2f07ae-2b00-4d7f-a0da-a2abc7d309f8)

I've tried using some boot strap classes like `btn-group btn-group-toggle` however this did not seem to work

**Comment by lane-formio** [comment]
<div>Agent Dane Acree linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/48984">48984</a> for this issue.</div><br/>

**Comment by travist** [comment]
In order to do this, you will need to override the "radio" template to provide the template (dom) for the radio buttons. Here are some docs for how to do this. 

https://help.form.io/developers/form-development/form-templates#overriding-templates
