### ISSUE TITLE
Dynamically populating select list leaves choice list empty

### ISSUE THREAD

**Issue by lynn-fisher** [formio/formio.js#540]
I am creating a form with a postcode search( a text field component ) and a corresponding button called Find Address that should populate a select list ( just formio select list available via wizard) with a list of addresses when pressed. 

I have created a service for the postcode search and am also using the custom event emitter to identify when the Find Addresses button is pressed and I am then populating the select list with the results from the service. This is all working fine accept the choice list that sits on top of the select list is not populating, therefore it looks like the select list is empty. 

How do I populate the choice list to include the values that are in the select? What am I missing? I am just looping through the postcode search results and creating an option element and appending to select list on form at the moment. Any clues would be appreciated.

**Comment by jhen1422** [comment]
You can find documentation on how setup dynamic select filtering from the following documentation https://help.form.io/userguide/form-components/#select
