### ISSUE TITLE
Case sensitive error on linux/ devops pipeline

### ISSUE THREAD

**Issue by FedericoPalma92** [formio/formio.js#5415]
I've been using the npm @formio/js package for months on my Windows PC without any problems. At the moment that i have created a pipeline for publishing my project on a static webapp in Azure i found the following error:
![screen_formio_error](https://github.com/formio/formio.js/assets/7261023/b27ca1b2-bf59-4ac3-9c26-44f9886798a4)

After investigating a bit I understood that the problem was case sensitive on Linux and by testing it on a Linux virtual machine I found the same problem. I attach a screen of the code where the case sensitive problem is highlighted.
![Schermata del 2023-11-28 15-45-55](https://github.com/formio/formio.js/assets/7261023/8490e337-5571-4a6b-962f-501c1352d5a7)

The npm package version that i've used is "5.0.0-rc.33"

**Comment by kamel-msaoubi** [comment]
Hello,
I have the same issue so I cannot work on gitpod (linux vm instances). I could provide a PR but I am not sure about the edge sides effects. Also the problem could be biggest than a simple upper case.

**Comment by FedericoPalma92** [comment]
@kamel-msaoubi the problem is strange because in the repos the name seems correct, with a lowercase 'F' but when you run the npm install command a version of the file with a capital 'F' is downloaded.

**Comment by kamel-msaoubi** [comment]
More information:
I have this error since I migrated to angular 17 and vite builder.
Vite can build on Windows but not on Linux due to this error.
Before, I managed to work with webpack as build for projects on Angular < v16

**Comment by FedericoPalma92** [comment]
I currently use angular version 16 but despite this the build fails on linux

**Comment by FedericoPalma92** [comment]
> @FedericoPalma92 I managed this issue by running my pipelines on windows-latest image. I think that the F uppercased is generated on FormioJS build and release pipeline. Maybe a core team member can help us. In that time, continue to follow next releases to see if the problem continue to occurs on the next versions. It is a bit strange, because it seems to me that the core team members works on linux because all the flows: build, tests and release can be launched only on Linux Os.

I also solved it by setting the pipeline to windows-latest. the problem is that there is another person who should be part of the project who works on linux and on his machine the build fails. I will stay updated on future versions of @formio/js in the hope that the problem will be resolved

**Comment by brendanbond** [comment]
So @FedericoPalma92 @kamel-msaoubi can you help me here - what if anything can we do to resolve this?

**Comment by Sidiro23** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
