### ISSUE TITLE
[BUG] Select Boxes (Data Source=URL) inside Data Grid cause side effects / flickering / extra XHRs

### ISSUE THREAD

**Issue by bobslee** [formio/formio.js#5419]
### formio.js versions affected:
- 4.16.0
- 4.17.4
- 4.18-rc8

### Steps to Reproduce

(1) Add a **Data Grid** component.

(2) Add a **Select Boxes** component inside the Data Grid.

(3) Configure the **Select Boxes** its **Data Source = URL**:

Eg use the example URL https://cdn.rawgit.com/mshafrir/2646763/raw/states_titlecase.json
It's mentoined in the user guide "Select Box" section: https://help.form.io/userguide/form-building/form-components#select-box

### Observed behavior

Screen flickering and additional/unpredictable XHRs when:
- Adding and removing Data Grid rows
- Checking select boxes

### Remarks

This behaviour / issue doesn't occur when:
- Select Boxes in the form root or layout component.
- Select Boxes inside an Edit Grid component.

Let me know when you need more info or a JSFiddle.

**Comment by jeriah-formio** [comment]
We could not reproduce this issue. Please try again on FJS version 4.19.x
