### ISSUE TITLE
[BUG] - Cannot focus Select component errors inside an edit grid via clicking the form validation errors

### ISSUE THREAD

**Issue by llaurentiu** [formio/formio.js#5431]
Cannot navigate via form validation errors to an invalid select field inside an edit grid, when submiting draft submissions. <br/><br/>

1. Having a form with an edit grid edited in modal, that has components of type select that are required (or any type of validation that can be triggered)
2. Save a submission in draft state
3. Edit the submission & try to submit it ( state = submitted)
4. Click on the validation error  related to the select component

Expected behavior: edit grid row modal is opened and the  invalidSelect field is focused.

Current behavior: nothing happens.

JS fiddle here (for latest stable version, but also for lower versions): https://jsfiddle.net/llaurentiu/kg1odh4s/26/ 

Notice that navigating to a text field works, or navigating to the Select after previously focusing the a Text field error for instance.

**Comment by theprogrammerinyou** [comment]
Hi, can you post a loom regarding the issue, bit unclear and would be happy to take this up.

**Comment by llaurentiu** [comment]
> Hi, can you post a loom regarding the issue, bit unclear and would be happy to take this up.

Hi, sorry for the late reply.

There is already a jsfiddle attached. Try to submit the form and click on the validation error for the "Country" field. It should open the modal and focus the component, but it doesn't.
![image](https://github.com/formio/formio.js/assets/2297869/4b1e0543-f5ec-48c0-a097-1b29e4666062)

We already have a fix locally for it. After it is being fixed in the repo we want to revert ours. Basically the select component should call `beforeFocus` of the parent component.

![image](https://github.com/formio/formio.js/assets/2297869/fadbe22a-542d-44ec-a4be-425435140dd7)

**Comment by theprogrammerinyou** [comment]
Hi, Thanks for the reply, can you assign this to me so that i can work on this?

**Comment by llaurentiu** [comment]
> Hi, Thanks for the reply, can you assign this to me so that i can work on this?

Don't seem to be able to do that - but I don't see why anyone else cannot come with MRs on this :)

**Comment by Tatsiana8** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.

**Comment by Sidiro23** [comment]
Thank you for your contribution. We have tested this use case and we recommend upgrading to our latest version.

**Comment by llaurentiu** [comment]
Closing as it seems to have been indeed fixed in v5+
Thank you @formio.
