### ISSUE TITLE
FormBuilder with offcanvamodal

### ISSUE THREAD

**Issue by mdsameerdev** [formio/formio.js#5441]
Is there any way to build a form inside an off-canvas modal? I have a requirement to implement customisation within the off-canvas modal. Please help at your earliest convenience; I've been stuck here for the past three weeks.

**Comment by travist** [comment]
It could definitely be done using a custom template. Here are the documentations on how to build a custom template.

https://help.form.io/developers/form-development/form-templates

You would just need to override the https://github.com/formio/bootstrap/blob/main/src/templates/bootstrap5/builder/form.ejs template to be off-canvas.

**Comment by mdsameerdev** [comment]
Hi team, could you please let me know in which file the classes '**formio-dialog formio-dialog-theme-default component-settings**' are defined in the '**src**' folder? I've been trying to debug but haven't been able to locate it. While I can find the codes up to the '**component-edit-container**' class, I'm unable to locate the above-mentioned classes. I need to add some code there in the source, along with the existing modal code, before making the build. Could you please share the exact file path in the source code based on the current file structure on GitHub - https://github.com/formio/formio.js?
