### ISSUE TITLE
Number component not working for long values

### ISSUE THREAD

**Issue by gyanendrasinghpanwar** [formio/formio.js#5445]
I presume this due to below function in Number.js where we have used parseInt.

parseNumber(value) {
    // Remove delimiters and convert decimal separator to dot.
    value = value.split(this.delimiter).join('').replace(this.decimalSeparator, '.');

    if (this.component.validate && this.component.validate.integer) {
      return parseInt(value, 10);
    }
    else {
      return parseFloat(value);
    }
  }

**Comment by travist** [comment]
I believe this has more to do with JavaScript limitations rather than this library limitations. Do you have an example number that causes failures?

**Comment by gyanendrasinghpanwar** [comment]
> I believe this has more to do with JavaScript limitations rather than this library limitations. Do you have an example number that causes failures?

"Indeed, this is more with JavaScript limitation. Currently, the number component is working accurately with up to 15 digits; after that, there is data loss due to parseFloat."

Do we have any plans to provide BigInt support in the number component or to offer number validation in the textfield component so that it can be used from there?

Let me know if need any Pull request.

**Comment by youcefelwaer** [comment]
hello i used this work around on the calculated Value logic 
const inputValue=data['test'];
if ((inputValue.length>15))
{
value=parseFloat(inputValue.replace(".","").substring(0,15));
}

**Comment by lane-formio** [comment]
@gyanendrasinghpanwar 
We don't have any expectations to but are always willing to review any pull requests.
As @youcefelwaer has provided a workaround (thanks!) I'm going to go ahead close this issue but would be happy to re-open if someone thinks it needs further consideration.
