### ISSUE TITLE
Facing memory leak in formio.

### ISSUE THREAD

**Issue by gyanendrasinghpanwar** [formio/formio.js#5446]
Couple of reason : -

1. Chocices js library is causing memory leak with large amount of data.

**Comment by travist** [comment]
Do you have any sample requests that causes large memory leaks?... Also, it should be noted that we are in the process of replacing the validation system in formio/formio with a new @formio/core processor system that we hope will resolve many of the memory leak issues in the API Server. That is coming in the next few weeks and me have you try it after that is pulled into an RC build.

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
