### ISSUE TITLE
Required Validation does not disappear with formio 5.0.0-x

### ISSUE THREAD

**Issue by ralfeis** [formio/formio.js#5457]
Hi,

if I use the newest version 5.0.0-rc38, then the "required" validation behaves different to the 4.6 version of formio.
![grafik](https://github.com/formio/formio.js/assets/26071892/451ac3ff-840c-4af8-91fc-600c3bf124df)

The example is a  "true","false" decision which must be selected (required validation)
If "no" is selected, then the required validation does not disappear.

Here is a simple example to test:
https://stackblitz.com/edit/js-o27pu6?file=index.html,package.json

Best regards

**Comment by jeriah-formio** [comment]
@ralfeis 
This issue seems to be resolved on 5.0.0-rc.39

**Comment by ralfeis** [comment]
Hi @jeriah-formio,

thanks for your feedback. 
I  updated the test project: https://stackblitz.com/edit/js-o27pu6?file=index.html,package.json 
to the latest Formio (5.0.0-rc.42), but the error is still there.
The pull request of https://github.com/formio/core/pull/31 must be merged, then it will be fixed.

Best regards

**Comment by lane-formio** [comment]
Just got get this into our workflow I've created an internal ticket: FIO-8221

**Comment by lane-formio** [comment]
The fix had to be reverted as it broke checkboxes. I'm going to go ahead and re-open the issue.

An internal ticket has been logged to track this issue: FIO-8221

**Comment by lane-formio** [comment]
@ralfeis
I have logged a ticket for internal reference, but it is not being prioritized at the moment. If you'd like to explore another fix that will work for both radio and checkboxes I'd be happy to have get it reviewed.

**Comment by ralfeis** [comment]
Hi formio team,
 
 this issue can be closed. You have fixed it with this pull request: https://github.com/formio/core/pull/88
Many thanks for the great work!

Best regards
Ralf
