### ISSUE TITLE
Render form with submission

### ISSUE THREAD

**Issue by martinbelcic** [formio/formio.js#5467]
I'm using `formiojs@4.13.11`. I'm trying to make a PDF out of the form displayed in my web page.
But I am having issues because since `Formio.createForm` does not renders the submission initally, I am setting it afterwards, the first time the form is rendered it's entirely empty.

**Comment by brendanbond** [comment]
The `createForm` API can either take a form JSON definition or a Form.io form or submission URL. Here's an example of the former: https://formio.github.io/formio.js/app/examples/jsfiddle.html

The latter would look something like `Formio.createForm(document.getElementById('formio'), 'https://<form.io server url>/project/<my project id>/form/<my form id>/submission/<my submission id>');` but you'd need to ensure that you have the correct access permissions.

**Comment by martinbelcic** [comment]
In the examplo you provided you are setting the submission inside the
.then(), after the createForm promise is resolved. I has the same issue,
the for will be empty on the first render

**Comment by brendanbond** [comment]
Right, the submission is always going to be injected at runtime when created like this

**Comment by humble-codes** [comment]
hey @brendanbond I am facing a different issues when rendering a form in edit mode. There is a trigger on a data-source resource which should trigger on form init ; but in edit mode, the trigger doesn't works unless and until I reload the same page. 

Can you please guide a little bit ?

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/56498">56498</a> for this issue.</div><br/>

**Comment by blakekrammes** [comment]
Since this only appears in edit mode and not in a application runtime/production context, we don't think this is worth looking into.
