### ISSUE TITLE
Translations disapear after modifying form

### ISSUE THREAD

**Issue by wisienkaa91** [formio/formio.js#549]
Hey i found out that there is some problem with i18n that appears in version 3.0.0 rc.20
https://codepen.io/anon/pen/JBjRKP - when u drag and drop or remove or update the form the translations disapear 

in version 3.0.0rc.2 it was fine 
https://codepen.io/anon/pen/oMNLRv

**Comment by jhen1422** [comment]
Closing issue.

This should be resolved on the latest 4x renderer. If the issue persists, please open a new issue
