### ISSUE TITLE
Translating component details form

### ISSUE THREAD

**Issue by wisienkaa91** [formio/formio.js#550]
Couldn't find anything in docs, also didn't find any wat to do it myself. The problem is with translating  this whole left column in component details.
![image](https://user-images.githubusercontent.com/8066832/42499517-4bfba43a-842f-11e8-9b1a-fd0dc48c7f51.png)

There is some codepens with how i try to do it.

https://codepen.io/anon/pen/oMNLRv - 3.0.0 rc.2 - not working
https://codepen.io/anon/pen/JBjRKP - 3.0.0 rc.20 not working

**Comment by shunichio** [comment]
Hello, have you solved this problem? I also encountered this problem.

**Comment by jhen1422** [comment]
Hello,

This is Jeriah from the Form.io support team. 

After discussion with the team, we have added this to our backlog. It may be some time before this item addressed but we will gladly accept a pull request if you would like to fix it. Alternatively, we offer support packages if you are interested in Form.io addressing this issue quickly.
 
Thanks!
