### ISSUE TITLE
Dynamic Colors

### ISSUE THREAD

**Issue by AnthonyPhan** [formio/formio.js#5519]
Hi All,

Im trying to change the background color of a component based on its value. Is there a way to achieve this within the formio builder?

I tried setting the className field using handle bars syntax but this does not seen to be interpolated (e.g. {{ data.calcualtedClassName }}

**Comment by ZenMasterJacob20011** [comment]
You can use the logic tab to add custom css to a component based on the value of the component or another component.
1. Go to logic tab in component
2. Add logic and set the trigger to javascript. Set result equal to the changing data that will trigger this logic
3. Set the action to type property, set component property to container custom class
4. Set the text to {{data.yourComponentKey}}

[Here is a jsfiddle of this behavior](https://jsfiddle.net/7gvxrceq/3/)

It should be noted that logic does not trigger when using components in the form builder. To have the logic trigger you must use the form outside of the builder e.g. Formio.createForm()
