### ISSUE TITLE
Validation Error for Select Component and Data Source Type URL

### ISSUE THREAD

**Issue by Leeloo5E** [formio/formio.js#5523]
**Describe the bug**

When using the Select component with the DataSource "URL" selected, a validation error occurs in the browser console.

If you use several of these select components with "URL", the browser becomes increasingly slower and even stops. The form is also hardly usable anymore.

**Version/Branch**

`├── @formio/js@5.0.0-rc.39
  ├── @formio/core@2.0.0-rc.10
`

**Steps To Reproduce**

1. Install Formio JS and create form builder
2. Create a select component
3. Go to data section and select "URL" as Data Source Type
4. Set a Data Source URL
5. Save the form
6. Open form in Viewer

**Expected behavior**
No error. Form works well.

**Actual behavior**

`
Validator error: Failed to validate available values in select component 'organizationalUnitName': data source url is not valid}
`

**Additional context**
Seems the error is cause from
https://github.com/formio/core/blob/v2.0.0-rc.10/src/process/validation/rules/validateAvailableItems.ts#L141

**Comment by lane-formio** [comment]
My initial suggestion is to update core to the latest rc to see if that has resolved.
Otherwise, I'd suggest using the latest stable release versions.

**Comment by radovan-jupa** [comment]
I think that problem could be function isValidateableSelectComponent. The function does not check value of validation settings onlyAvailableItems but only existence of this property. Even though the component hasdisabled validation of onlyAvailableItems (validate.onlyAvailableItems  = false), it still performs validation on the available values.
 
https://github.com/formio/core/blob/master/src/process/validation/rules/validateAvailableItems.ts#L17

function isValidateableSelectComponent(component: any): component is SelectComponent {
    return (
        component &&
        **!!component.validate?.hasOwnProperty('onlyAvailableItems')** &&     // probably should be !!component.validate?.onlyAvailableItems
        component.type === 'select' &&
        component.dataSrc !== 'resource'
    );
}

**Comment by lane-formio** [comment]
Have you attempted this with formiojs@4.19.1 and core@2.0.0?
