### ISSUE TITLE
"Formio.createForm" method return error when Input option parameter "components" provided

### ISSUE THREAD

**Issue by RahulKhandelwal17** [formio/formio.js#5538]
**Describe the bug**
When I'm creating a form with input option parameter "components" form doesn't render.

Below code run on perfectly fine https://jsfiddle.net/travistidwell/6uge153s/

Formio.createForm(document.getElementById('formio'), 'https://exampleapp.form.io/renderertest', {
  readOnly: false,
  hide: {"firstName": true},
  ////components: { "textfield": { "prefix": "hello" }},
  disabled: {"lastName": true},
  buttonSettings: { "showSubmit": false }
});

But when uncomment below code
components: { "textfield": { "prefix": "hello" }},

form doesn't get render and I'm getting below error in console.
"TypeError: this.getComponents(...).slice is not a function" error in console.

As per the documentation (screen-shot attached) I'm passing the right data in components.
![documentationPage](https://github.com/formio/formio.js/assets/39265558/cee36722-1ea9-472a-bda2-46e82f181030)

**Version/Branch**
https://github.com/formio/formio.js/tree/v5.0.0-rc.2

**To Reproduce**
1. Create form using method "Formio.createForm"
2. While creating form pass option parameter "components" which allows for overrides for certain components rendered.
3. Form doesn't get rendered.
4. See error on console.

**Expected behavior**
Form should be rendered.
![WithoutError](https://github.com/formio/formio.js/assets/39265558/a870e4d2-a3d6-498c-8e9e-6b2c799f7d26)
![WithError](https://github.com/formio/formio.js/assets/39265558/eb6b7a34-5c4f-4eaf-97fc-3a148bfbe3aa)

**Comment by lane-formio** [comment]
I am able to reproduce this and have created an internal ticket for review. In the meantime, if anyone would like to attempt to tackle this, we always welcome any contributions to our open source!

For internal reference: FIO-8345

**Comment by lane-formio** [comment]
@RahulKhandelwal17
The documentation is inaccurate in this regard. This particular option/override is not valid.

**Comment by CaptainGlac1er** [comment]
@lane-formio Noticing the documentation still stats that is a feature. Is there an alternative way of for example setting the prefix like it shows in the current documentation?
