### ISSUE TITLE
Populating form with selected resource submission data.

### ISSUE THREAD

**Issue by hermescati** [formio/formio.js#5557]
Hello,

I wanted some help with using resource fields outside the resource. For more context: I have created a resource called Product that has the following fields - title, description, and price. In a new form, I have added a select component that references all the Product submissions. 

What I want to achieve is to populate an HTML element or text field in this form, with the resource submission data. Ex: The select component displays the product titles, but in a separate component I want to see the description and price of the selected product.

**Comment by lane-formio** [comment]
I believe I was able to accomplish by setting the value property in the select dropdown to "Entire Object" and then proceeding to set the item template to only display the title of the project. This gives me access to the entire object while only displaying the title.
![image](https://github.com/formio/formio.js/assets/110409244/fc35dea4-a443-46cd-ac88-038ac1c41351)
Then in my text field I just added a calculated value based on the value of what was selected in the dropdown.
![image](https://github.com/formio/formio.js/assets/110409244/7b5d084b-0da2-4135-a2ce-d7e5d5d12bad)
