### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by malichishti** [formio/formio.js#556]
Hi,

I would like to know how can custom components be added to the Form builder e.g. if i want to add support for a Captcha Control or an Image upload control ?

Is there any example for this? I have seen this [documentation ](https://github.com/formio/formio.js/wiki/Custom-Component) but it looks incomplete.

Regards,
Ali

**Comment by AbhisheshPradhan** [comment]
https://github.com/formio/examples.form.io/tree/master/custom-component

have a look here

**Comment by malichishti** [comment]
@AbhisheshPradhan that example is for Angular, i'm looking for formio.js 

Also i'm more interested in Form Designer than Form Rendering at this point.

**Comment by 152hq** [comment]
@malichishti check this please
http://formio.github.io/formio.js/app/examples/customcomponent.html

**Comment by rod-o-walker** [comment]
Came across this while researching how to do custom formio component, and looks good, except for one annoying defect - the order of elements added to form doesn't get preserved. 

For example, add an instance of the custom element and works fine, but add a second instance to the top of the form (above the first instance) and that second instance gets thrown to the bottom after saving.

Not sure where start in resolving that.

**Comment by randallknutson** [comment]
Custom components have a weight property that determines the order.

**Comment by rod-o-walker** [comment]
I understood that weight affected the order components show in the palette. The issue I'm referring to is the order in which component instances are showing in the build/render area.

Should have added screen-shot earlier:
![chrome_tcvMs329YD](https://user-images.githubusercontent.com/2146471/64344194-fc493180-cfbb-11e9-8f54-cab5f841279b.png)

Here I inserted the 2x2 component instance at the very top, but immediately after clicking save in the edit dialog, it gets moved to the very bottom, below the Submit button.

**Comment by rod-o-walker** [comment]
Just noticed the screen-shot also shows another issue - the edit/copy/remove buttons for the custom component instances are always visible.

**Comment by jhen1422** [comment]
@rod-o-walker 
We are unable to replicate this issue using the latest version of our 4x builder. Can you confirm you are on the latest ?

**Comment by dkolasani9** [comment]
Do we have any examples on creating the Custom Rating component?

**Comment by wag110894** [comment]
We do not have a Custom Rating component, but we do have a survey component. Here is our documentation on this component: https://help.form.io/userguide/form-components/#survey-1

**Comment by dkolasani9** [comment]
Atleast Do we have any examples on creating a Custom component for rating?

**Comment by dkolasani9** [comment]
> We do not have a Custom Rating component, but we do have a survey component. Here is our documentation on this component: https://help.form.io/userguide/form-components/#survey-1

I know may be not available in Form.IO library. But Can I code to create a custom component and Is the communication possible between my component and formBuilder?

**Comment by wag110894** [comment]
Here is our documentation on  how to create custom components: https://formio.github.io/formio.js/app/examples/customcomponent.html

Hope that this helps.

**Comment by shahzadiiui2015** [comment]
![customTextArea](https://user-images.githubusercontent.com/38350534/142902939-76cff9ba-b286-48fa-a6a8-122ad448d260.png)

Can someone have any idea about it i and using it in angular application and this popup contains custom component
