### ISSUE TITLE
No change color - Panel component

### ISSUE THREAD

**Issue by afuentes1800** [formio/formio.js#5569]
Hello everyone,

 I want to change the color of a component bar, Customer has requested a custom color from their brand manual.

Object: panel component

CODE
{
    "display": "form",
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    },
    "components": [
        {
            "customClass": ".bg-success {   background-color: #7fbc03 !important; }",
            "collapsible": false,
            "key": "panel",
            "type": "panel",
            "label": "Panel",
            "customStyle": "background-color: #7fbc03 !important;",
            "input": false,
            "tableView": false,
            "components": [
                {
                    "label": "Hola mundo",
                    "applyMaskOn": "change",
                    "autoExpand": false,
                    "customClass": ".bg-success {   background-color: #7fbc03 !important; }",
                    "tableView": true,
                    "key": "holaMundo",
                    "type": "textarea",
                    "input": true
                }
            ]
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}

![example](https://github.com/formio/formio.js/assets/167112554/fd7cf28b-55b1-4c75-b6fb-6044208128f9)

Thanks.

**Comment by lane-formio** [comment]
<div>Agent Olga Bannikova linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51659">51659</a> for this issue.</div><br/>

**Comment by travist** [comment]
Since these are inline embedded, you can use CSS to alter the colors for this bar.
