### ISSUE TITLE
How to  remove "Common Parameters"  from the component.

### ISSUE THREAD

**Issue by vrkansagara** [formio/formio.js#558]
I have referred this link [https://github.com/formio/formio.js/wiki/Components-JSON-Schema](url)

And I am come accross with the question that how one can make / hide other parameters so it give clean view for the adding of component.

Can any budy guide me how to do this.!

~~~javascript

Formio.builder(document.getElementById('builder'), {}, {
  builder: {
    basic: false,
    advanced: false,
    data: false,
    customBasic: {
      title: 'Basic Components',
      default: true,
      weight: 0,
      components: {
        textfield: true,
        textarea: true,
        email: true,
        phoneNumber: true
      }
    },
    custom: {
      title: 'User Fields',
      weight: 10,
      components: {
        firstName: {
          title: 'First Name',
          key: 'firstName',
          icon: 'fa fa-terminal',
          schema: {
            label: 'First Name',
            type: 'textfield',
            key: 'firstName',
            input: true
          }
        },
        lastName: {
          title: 'Last Name',
          key: 'lastName',
          icon: 'fa fa-terminal',
          schema: {
            label: 'Last Name',
            type: 'textfield',
            key: 'lastName',
            input: true
          }
        },
        email: {
          title: 'Email',
          key: 'email',
          icon: 'fa fa-at',
          schema: {
            label: 'Email',
            type: 'email',
            key: 'email',
            input: true
          }
        },
        phoneNumber: {
          title: 'Mobile Phone',
          key: 'mobilePhone',
          icon: 'fa fa-phone-square',
          schema: {
            label: 'Mobile Phone',
            type: 'phoneNumber',
            key: 'mobilePhone',
            input: true
          }
        }
      }
    },
    layout: {
      components: {
        table: false
      }
    }
  }
}).then(function(builder) {
  builder.on('saveComponent', function() {
    console.log(builder.schema);
  });
});
~~~

**Comment by Tomislav-Dreamix** [comment]
I am also interested if it's possible to get a cleaner JSON schema when using the Form Builder. Currently it generates a bunch of properties with empty string or default values. Manually building the component without all the default properties works fine in the Form Renderer, so it doesn't make sense to have them there by default. Any suggestions?

**Comment by randallknutson** [comment]
builder.schema should only return the non-default properties. Are you using the 3.x version of the form builder? I think there has been a long standing issue there where it was returning the full version, not the overridden values only. Can you try 4.x and see if it works correctly?

**Comment by Tomislav-Dreamix** [comment]
I'm was using the builder at this url: https://formio.github.io/formio.js/app/builder , just testing stuff out to see how your library works. Not sure, but I assume it's on version 4.x. Anyway, I will try the embedded builder with version 4.x to see if that makes a difference.

**Comment by jhen1422** [comment]
Closing issue.

Please open a new issue if this issue persists on 4x.

**Comment by franke-mc** [comment]
@jhen1422 : I have created a JSFiddle based on the JS given in the issue description above:
https://jsfiddle.net/franke_mc/86mktgpL/10/
It shows that with current formiojs version 4.8.0-beta.1, `on('saveComponent', ... builder.schema ...)` events get the compact representation, stripped of default values, while the `on('change', form => ...)` events get the full representation including all of the default values.  Is this how it should be?  And what is supposed to be sent over the wire to the server when saving the form: the compact version without default values, or the full version including all the default values?
Shall I open a new issue if components sent to the server have not been stripped of default values?

**Comment by franke-mc** [comment]
@jhen1422: By the way, the current builder at https://formio.github.io/formio.js/app/builder which apparently uses 4.8.0-beta.1 as well, seems to show inconsistent behavior regarding stripping of default values:
- When adding a textfield component directly, the default values are stripped:
![FormioBuilderTextfield json](https://user-images.githubusercontent.com/46748541/69655108-2f103c80-1076-11ea-8134-5614425b0842.png)
- But when adding a textfield component directly into a column, the default values are not stripped:
![FormioBuilderTextfieldInColumns json](https://user-images.githubusercontent.com/46748541/69655158-43ecd000-1076-11ea-9242-be0a1ab82af9.png)

New issue for that?

**Comment by randallknutson** [comment]
Hi Frank,

I'm currently working on fixing the issues related to this. We intend for the stripped down version of the form definition to be saved to the server. In addition the component events should send the stripped down version of the component as well. We're trying to make the form definitions significantly smaller by doing this as they have gotten quite large. Right now it is only half implemented (and is causing some side effects). It is the next item for me to look at to get these issues fixed.

**Comment by franke-mc** [comment]
Cool, that sounds great!

**Comment by franke-mc** [comment]
In formiojs 4.8.0-rc.12, the form builder adds `"modalEdit": false` to seemingly each and every component in addition to all the gazillion default values which are already there.  Can you please point me to some place where I can follow the effort of stripping all default values from form components across the board, even when they are inside a column? Or is that already available in a more recent version?

**Comment by randallknutson** [comment]
If you use form.schema instead of form.form it should have the stripped out version of the form. 
https://github.com/formio/formio.js/blob/master/src/Webform.js#L782-L787
https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L445-L447
