### ISSUE TITLE
Reducing Form Builder Modal sizings

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#5583]
Loading the formio builder on laptop sized screens with the browser at 100% can lead to the field editor modal to appear as:

<img width="1285" alt="image" src="https://github.com/formio/formio.js/assets/1994838/71a7efd5-5ba1-4ff7-9ec5-bfa632233650">

Where fields such as the `Label` and `Value` are very tightly spaced.

Is there any common code to reduce the modal's sizing?  Increase width, hight? reduce paddings. etc ?

if we reduce the browser zoom we start to get better sizing such as:

<img width="1279" alt="image" src="https://github.com/formio/formio.js/assets/1994838/9d5748ff-3137-4e0d-99b4-1e588005ee1c">

Any ways to do this without having the user's having to zoom the browser?

for further thought: if the builder is embedded in an application that has any sort of left side menu, we further loose space  and fields can get even tighter on a laptop.

**Comment by lane-formio** [comment]
Have you tried the "Hide Preview" button? It was just recently added and I see it showing in your screenshots.

**Comment by StephenOTT** [comment]
Ah! that is a clever fix to this problem!

I will give that a try!

thanks
