### ISSUE TITLE
[Builder] Side menu groups collapse when component is added/edited/deleted

### ISSUE THREAD

**Issue by alaa13212** [formio/formio.js#559]
I noticed that when form schema changes, the builder is re-rendered which resets the state of the sidebar and collapse all sections.

I tested few old versions and found that this behavior started from `v3.0.0-rc11`. Previous versions don't have this issue.

**Comment by travist** [comment]
I am not seeing this on this page which is the latest version of the builder. https://formio.github.io/formio.js/app/builder

**Comment by alaa13212** [comment]
The [script](https://formio.github.io/formio.js/dist/formio.full.min.js) used in that page seems to start with `formiojs v3.0.0-rc.2`. Instead of rc.22 like in [gh-pages](https://github.com/formio/formio.js/blob/gh-pages/dist/formio.full.min.js) branch

I tried a simple html file with following code:
```html
<html>
<head>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                         <!-- Change version here ⬇ -->
  <link href='https://unpkg.com/formiojs@3.0.0-rc.11/dist/formio.full.min.css' rel='stylesheet' >
  <script src='https://unpkg.com/formiojs@3.0.0-rc.11/dist/formio.full.min.js'></script>
  <script type='text/javascript'>
    window.onload = function () {
      const builder = new Formio.FormBuilder(document.getElementById('builder'), { components: [] });
      builder.render();
    };
  </script>
</head>

<body>
  <br/>
  <div class="container">
    <div id='builder'></div>
  </div>
</body>
</html>
```

Changing version of the referenced unpkg will help testing different versions quickly.
In my case, version RC.10 doesn't reset the sidebar to default state, while newer versions do.

**Comment by travist** [comment]
Oh yeah, you are right. Thanks and I will take a look.

**Comment by jhen1422** [comment]
This issue has been resolved
