### ISSUE TITLE
Boostrap 5 level of support?

### ISSUE THREAD

**Issue by StephenOTT** [formio/formio.js#5626]
The docs: https://help.form.io/developers/css-frameworks#bootstrap-5 show that BS5 is considered a work in progress:

<img width="859" alt="image" src="https://github.com/formio/formio.js/assets/1994838/258c4f10-aec2-48de-8b28-6274510f9f16">

What is the level of support compared to bootstrap 4?

Thanks

**Comment by lane-formio** [comment]
It will be an equivalent level of support in the next couple months as we are preparing a release candidate for our QA to start testing in earnest.

**Comment by StephenOTT** [comment]
@lane-formio is there is currently large gaps

**Comment by lane-formio** [comment]
@StephenOTT Not that I'm aware of.
