### ISSUE TITLE
Select control not showing all the filtered data.

### ISSUE THREAD

**Issue by abhishek0196** [formio/formio.js#5644]
**Describe the bug**
I tried adding 104 records in the select and then when trying to filter with keyword "**che**", I am getting only 4 records, however there are 30 records.

**Version/Branch**
I can replicate it on the sandbox version

**To Reproduce**
1. Visit https://formio.github.io/formio.js/app/sandbox.html
2. Enter sandbox id - 666afd8ad353cd262d75ba9f
3. Try to filter with "che"

**Expected behavior**
I should get all the records

**Comment by Sidiro23** [comment]
Thank you for reporting this issue. I am able to reproduce and have logged a ticket for the backlog. We are always willing to review any contributions to resolve this issue from the open source community.

For internal reference: FIO-8520

**Comment by alexandraRamanenka** [comment]
This is the part of choices.js  library, it has a configuration called 'searchResultLimit' with a deafualt value 4. We need to overwrite it to make the select show more search results like shown on the screenshot.

![image](https://github.com/user-attachments/assets/068e63d4-7845-4168-9801-1aeb9476ad8f)

However, in the choices.js 10.x which is used currently in formiojs no option to make it ‘unlimited', but a workaround is to set it to some big numbers like 1000 (noone really will scroll through 1000 search results to see them all).
