### ISSUE TITLE
Custom properties in edit dialog

### ISSUE THREAD

**Issue by pmanu93** [formio/formio.js#567]
Hi, 

I'm trying to create a functionality that, when an user submits a form, should grab some fields from that form and send those fields to another endpoint. The problem is... I don't know where to put the flag that can make that possible.

The idea is to add a property/attribute that could be checked/unchecked by the user who builds the form and use that as the flag...

My question is: is that possible? Can I create or make custom properties or attributes available in all components  and available to the user in the edit dialog? 
Can I inject stuff like that somewhere? (I could't find FormBuilder documentation)

Thanks in advance,
Pedro Silva

**Comment by dhaval27021992** [comment]
Hey Any Luck on this I want to map my defaultValue of Form.io Json based on added custom property if any custom properties added

**Comment by felipebelluco** [comment]
@pmanu93 

Did you find the solution?

**Comment by travist** [comment]
Why not just render the form like https://formio.github.io/formio.js/app/examples/ which would give you full control of the JSON that is being rendered as well as allow you to "hook" into the submit process and make the changes you wish to make.

**Comment by felipebelluco** [comment]
First of all, thank you, @travist for your quick response. Secondly, I need to use the builder, but I don't want to give that much control the edit dialog gives to the user. E.g., the user can only inform the label and placeholder, and the rest is predefined in code.

Is it possible to accomplish just that?

**Comment by randallknutson** [comment]
You can do that by hiding all the other fields and providing the settings in the default schema for the components. It takes a bit of work to override all the items but it is definitely possible. You will probably want to allow them to set the API key as well since that is used for storing the data.

**Comment by felipebelluco** [comment]
@randallknutson, there is this example [here](https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.ts) that shows how to create a custom component. The example shows how to create a custom component which is one of the things a need. But, at the bottom of the code there is this line:

`CheckMatrixComponent.editForm = TableComponent.editForm;`

Which indicates that the edit form of the custom component is derivated from some other component. Is it possible to create a custom edit form without having to derivate from someone else, and how can I accomplish such a thing?

Thank you in advance.

**Comment by travist** [comment]
You can do something like the following...

```js
import TableComponentEditForm from 'formiojs/components/table/Table.form';
CheckMatrixComponent.editForm = function(...extend) {
  return TableComponentEditForm([{
    ... <--- Your custom options here.
  }], ...extend);
};
```

**Comment by felipebelluco** [comment]
@travist thank you very much! That is exactly what I was looking for.

**Comment by abhishek0196** [comment]
@travist  @randallknutson I was looking to add a custom property of role, the roles data would be coming from a external endpoint and not form io, so it would be a drop down which will list all the roles, and while building the form, the user can select for which role will the form be visible, I am unable to find any documentation regarding the same, any help would be grateful.
Thanks 
Abhishek.
