### ISSUE TITLE
Setting a function for click event of textfield

### ISSUE THREAD

**Issue by kato68** [formio/formio.js#5678]
how can set a function name for click event of a textfield component?
components: [ 
{
	title: 'First Name',
	key: 'firstname',  
	type: 'textfield',
	label: 'First Name',                            
	input: true,
         clickEvent:'test()',
}

or other ways

**Comment by lane-formio** [comment]
<div>Agent Tatsiana Ivashevich linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51668">51668</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
Please see the documentation found here: [https://help.form.io/developers/form-development/form-renderer#form-events](https://help.form.io/developers/form-development/form-renderer#form-events%E2%80%8B)
I'm not sure of your use-case but you might consider using the 'focus' event.
