### ISSUE TITLE
fields that are not required still have length requirements enforced

### ISSUE THREAD

**Issue by colons** [formio/formio.js#569]
in formio.js `3.0.0-rc.15` and `3.0.0-rc.26`, text fields that are not required but have a minimum length will be considered invalid if left blank

for what it's worth, i would expect a text field with a minimum length of 10 that is not flagged as required to only complain about strings with a length between 1 and 9, inclusive

this is kind of the opposite of #442, but might be related

**Comment by jhen1422** [comment]
This issue should be resolved in a 4x renderer
