### ISSUE TITLE
Builder: tab API: custom properties: bug

### ISSUE THREAD

**Issue by rzorzorzo** [formio/formio.js#5741]
**Describe the bug**
1. in "key" field: the text key is a value of the input field instead of a placeholder
2. when adding a second property: the property is repeated multiple times with empty value and copies of the key

**Version/Branch**
5.0.0-rc.48

**To Reproduce**
1. Create form...
2. Add component...
3. API tab, click "+add another"
4. enter key input field -> "key" is not a placeholder
5. enter key and value
6. click "+add another" again
7. enter a key and value -> multiple keys are added (depends on length of entered key)

**Expected behavior**
1. word key should be a placeholder not a value
2. ui should not add multiple properties

**Screenshots**

**Additional context**
![firefox_iDTyUyoTZu](https://github.com/user-attachments/assets/9a2fa91e-2a14-49d1-b49b-f76557e8c89f)
![firefox_PunqPD3Pio](https://github.com/user-attachments/assets/82ea9299-9f49-4dcd-b5b5-bfb021c47eca)

**Comment by lane-formio** [comment]
Should be resolved with https://github.com/formio/formio.js/pull/5733.
Try formio/js@5.0.0-rc.73
