### ISSUE TITLE
[HELP] How to adjust the shape of the button component

### ISSUE THREAD

**Issue by SmolmangoBFX** [formio/formio.js#5790]
Hello! 
I am pretty new to form io and wanted to ask a question about button functionality.

I basically want to have the button a different shape rather than the classic oval/pill shape. Is there any way for me to change it to be more like a square/rectangle? Does the shape have anything to do with the "Layout" section in the button tab? Is there some sort of attribute I can use to adjust the shape?

I appreciate the help :).

**Comment by ZenMasterJacob20011** [comment]
Internally all component have access to bootstrap css classes. To make the button square/rectangle you would add rounded-0 to your css class on your button component. For example...
```
{
  "label": "Submit",
  "showValidations": false,
  "customClass": "rounded-0",
  "disableOnInvalid": true,
  "tableView": false,
  "key": "submit",
  "type": "button",
  "input": true,
  "saveOnEnter": false
}
```
