### ISSUE TITLE
Formio Embed JS number field incorrect behavior with decimalLimit flag

### ISSUE THREAD

**Issue by dipankarmedhi91** [formio/formio.js#5802]
**Describe the bug**
I am rendering a Formio defined form using the Formio Embed JS definition as the web app just needs to render the form using the JSON output of a Form built using Formio builder.
For a number field if we add a **decimalLimit** flag the input value changes on focus out to get truncated and prefixed with a Zero `0`, this behavior continues if we keep focusing in and out of the number field until the value reaches only Zero `0`.

```js
{
    type: 'number',
    key: 'number',
    label: 'Enter a number',
    input: true,
    decimalLimit: 0
}
```

**Version/Branch**
N/A as we are using https://cdn.form.io/js/formio.embed.js

**To Reproduce**
JS Fiddle: https://jsfiddle.net/Lhtqb1oy/2/
1. Open the JSFiddle above
2. enter some number and tab out
3. the Input will get truncated and get prefixed with a `0`, focus in and out
4. the truncation will continue until only `0` is left
5. If we remove **decimalLimit** flag from the number field definition, the input behaves as expected

**Expected behavior**
The input shpuld not get truncated and prefixed with `0`

**Screenshots**
1. JSFiddle
<img width="828" alt="Full Window" src="https://github.com/user-attachments/assets/f563bc4d-a466-4c86-af58-5e7f34fdf67b"> 

2. User typed a number
<img width="208" alt="Screenshot 1" src="https://github.com/user-attachments/assets/9ed1ea56-0e82-41e9-8da6-1f22d2867303"> 

3. Tab/Blur out
<img width="139" alt="Screenshot 2" src="https://github.com/user-attachments/assets/86b04194-3f7b-49da-b3cc-5c712f03818e">

4. Tab in-n-out
<img width="122" alt="Screenshot 3" src="https://github.com/user-attachments/assets/07a8a063-ad0b-4528-9b02-5361ab1db55f"> 

5. Tab in-n-out, only 0 is left at the end
<img width="136" alt="Screenshot 4" src="https://github.com/user-attachments/assets/368d62ae-3827-42b2-9239-66d0c2a9342d">

**Comment by ZenMasterJacob20011** [comment]
Thank you for taking the time to report this issue. This issue has been resolved but has not yet made it into a build yet. For now you can use one of our test builds http://cdn.test-form.io/formiojs/5.0.0-rc.81/formio.full.min.js.
