### ISSUE TITLE
form wizard uncaught exception (page not found)

### ISSUE THREAD

**Issue by alfavat** [formio/formio.js#584]
hey
i am trying to use form wizard but when i use Wizard and then click the add page button 
it does not work and in console i see this error
"form wizard uncaught exception (page not found)" 
i added a photo of this error 
![wizarderror](https://user-images.githubusercontent.com/28217209/43762711-ec849fc8-9a3d-11e8-948d-6707695ea0ae.png)

**Comment by wag110894** [comment]
Hello thanks for reaching out,
 
This is William with the Form.io support team. Great to hear from you!
 
We are not able to replicate this issue on our end. Could you verify that you are using the latest version of the form builder?
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay

**Comment by alfavat** [comment]
hello
thanks for considering.
i think it is the latest version .
i was trying from web project in this url : '
formio.github.io/formio.js/app/builder' i do not know if this is the latest
version  or not
actually i was able to fix it in my own project
i was just trying to warn you to fix it
