### ISSUE TITLE
custom action of button component doesn't change data

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#585]
when i use button component with custom action with this code:
data.myFieldName = "100";
when i click on the button it doesn't change the field's data 

i thinks this should be a bug 

same code works on ngFormio (angular based form renderer)

**Comment by wag110894** [comment]
Hello Amir,
 
William here with the Form.io support team. Great to hear from you!

It is not expected to populate data using the button component. Component controls its own value. 
 
The best way to do this is to either:
1. Have myFieldName be a calculated value 
or 
2. Set the button to trigger a custom event and then use the Logic tab on the component to listen for the event and set its value.
 
Let me know if you have any further questions or concerns.
 
Thanks,
 
William Gay

**Comment by amirmf** [comment]
maybe related to this issue too 

[592](https://github.com/formio/formio.js/issues/592)

**Comment by AnthonyPhan** [comment]
> Hello Amir,
> 
> William here with the Form.io support team. Great to hear from you!
> 
> It is not expected to populate data using the button component. Component controls its own value.
> 
> The best way to do this is to either:
> 
> 1. Have myFieldName be a calculated value
>    or
> 2. Set the button to trigger a custom event and then use the Logic tab on the component to listen for the event and set its value.
> 
> Let me know if you have any further questions or concerns.
> 
> Thanks,
> 
> William Gay

Hi @wag110894 ,

When you create a button with "Custom Logic" the default placeholder text seems to suggest you can update data field from a button. Has there bee any changes since you responded to this issue?

![image](https://user-images.githubusercontent.com/12785492/143260605-74103461-7cb3-4199-a606-11d696fdfa0a.png)
