### ISSUE TITLE
File component ignores camera settings

### ISSUE THREAD

**Issue by Rolf-MP** [formio/formio.js#5854]
**Describe the bug**
On mobile device the File component allows getting a picture from the camera. The component suggests that the camera to grab from is configurable (`environment` or `user` representing back and front camera respectively).

Behavior on a mobile device is confusing to me (between enabling webcam and device capture, are they independent settings or are they related?).

In any case the device capture setting whether to use the front or back camera is ignored.

**Version/Branch**
latest and before, tested in sandbox

**To Reproduce**
On a mobile device go to sandbox: https://formio.github.io/formio.js/app/sandbox

In the Form JSON add the below to the components array"
```json
    {
      "label": "Upload",
      "tableView": false,
      "storage": "base64",
      "image": true,
      "uploadOnly": true,
      "webcam": true,
      "capture": "environment",
      "fileTypes": [
        {
          "label": "",
          "value": ""
        }
      ],
      "validateWhenHidden": false,
      "key": "file",
      "type": "file",
      "imageSize": "",
      "input": true
    }
```

**Expected behavior**
I would expect the camera selection to grab video from the configured camera. In the above case the back camera.

**Screenshots**
N/A

**Additional context**
here the videastream settings seem to be hard coded:  
https://github.com/formio/formio.js/blob/75fac6d329c812ccc27383a9a8c81c758e0dd640/src/components/file/File.js#L208
```js
  getVideoStream(constraints) {
    return navigator.mediaDevices.getUserMedia({
      video: {
        width: { min: 640, ideal: 1920 },
        height: { min: 360, ideal: 1080 },
        aspectRatio: { ideal: 16 / 9 },
        ...constraints,
      },
      audio: false,
    });
  }
```
Maybe `constraints` were meant to pass this/these settings, but nowhere the constraints are an input when `getVideoStream()` is called.  

I would expect this code to also set the `facingMode` property of video to `user` or `environment` per the setting of the component.
```js
  getVideoStream(constraints) {
    return navigator.mediaDevices.getUserMedia({
      video: {
        facingMode: `user`, // or `environment`
        width: { min: 640, ideal: 1920 },
        height: { min: 360, ideal: 1080 },
        aspectRatio: { ideal: 16 / 9 },
        ...constraints,
      },
      audio: false,
    });
  }
```

**Comment by Rolf-MP** [comment]
I am looking for behavior like the below (on mobile device):

Front/user camera:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><!-- Insert your title here --></title>
</head>
<body>
<video></video>
<script>
const stream = navigator.mediaDevices.getUserMedia({
    video: {
        facingMode: 'user',
        width: {
            min: 1280
        },
        height: {
            min: 720
        }
    }
}).then(function(stream) {
const video = document.querySelector('video');
video.srcObject = stream;
video.play();
})
</script>
</body>
</html>
```


Back/environment camera:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><!-- Insert your title here --></title>
</head>
<body>
<video></video>
<script>
const stream = navigator.mediaDevices.getUserMedia({
    video: {
        facingMode: 'environment',
        width: {
            min: 1280
        },
        height: {
            min: 720
        }
    }
}).then(function(stream) {
const video = document.querySelector('video');
video.srcObject = stream;
video.play();
})
</script>
</body>
</html>
```

**Comment by lane-formio** [comment]
The "Enable web camera" is intended for use with actual web cameras. If you leave that as "false", when a user simply selects "browse" the mobile device will take over the upload functionality and allow a user to select "camera" and use whatever they need.

**Comment by Rolf-MP** [comment]
Thank you  @lane-formio for the explanation of "Enable web camera".

The assessment that the configuration of device capture (user or environment) has no impact at all is correct then?
This seems to be an implementation oversight.

It defaults to user it seems. 
If it is not a non-respected property, it would still be convenient if the default capture device can be set.
