### ISSUE TITLE
Missing icon for tooltip when using Fontawesome 5

### ISSUE THREAD

**Issue by CaptainGlac1er** [formio/formio.js#5856]
**Describe the bug**
Tool question mark does not show when using fontawesome. 
https://github.com/formio/formio.js/blob/bcf06c2ec1eacc3f6127bec877f3cb30f6f9232b/test/renders/form-bootstrap-basic.html#L40
I see that `fa-question-sign` (broken) is used in some places while others use `fa-question-circle` (which works)

**Version/Branch**
5.0.0-rc.91

**To Reproduce**
Use formio with fontawesome. 

**Expected behavior**
question circle for tooltip icon

**Comment by namti** [comment]
Hi @CaptainGlac1er , can you please check if the bug has been fixed?

I am using the latest version `@formio/js@^5.1.2` `@formio/react@^6.0.1` but the issue still occurs.

https://github.com/user-attachments/assets/7aaa29e4-7d8e-4300-b35e-988ec181a1fb

**Comment by ibdnken** [comment]
This issue also affects to me!!

**Comment by sheldonlendrum** [comment]
Yes, this is also affecting us in version 5.1+

**Comment by Peter034** [comment]
Yes, exactly. We encounter the same issue!

**Comment by heather-formio** [comment]
We're reviewing. This is Open Source Code, so a PR is welcome to fix. We appreciate any contributions.

**Comment by CaptainGlac1er** [comment]
I forgot if I remapped the class used or the fix worked. Sorry juggling a few things so I won't be able to get you an answer soon
