### ISSUE TITLE
--

### ISSUE THREAD

**Issue by tejanarra** [formio/formio.js#5861]

**Comment by lane-formio** [comment]
Can you provide a codesandbox or jsfiddle or something so I can get this triaged quicker?

**Comment by tejanarra** [comment]
https://codesandbox.io/p/devbox/angular-angular

<img width="558" alt="Screenshot 2024-10-16 at 6 59 35 PM" src="https://github.com/user-attachments/assets/c2f8592c-4e50-4234-8d8d-da1c209ed532">

i have 3 entries try searching and wait for the result 1 after another 

i have tried by using a search button as well so search button as it is taking two hits to get the search done.

try for your self reach out if anything is needed from my end.

to run : ng serve --disable-host-check

**Comment by SSP23SCM38P** [comment]
https://codesandbox.io/p/devbox/angular-angular

Screenshot 2024-10-16 at 6 59 35 PM
i have 3 entries try searching and wait for the result 1 after another

i have tried by using a search button as well so search button as it is taking two hits to get the search done.

try for your self reach out if anything is needed from my end.

to run : ng serve --disable-host-check

**Comment by tejanarra** [comment]
I have closed this and opened a new issue.

you can take a look at this here:
https://github.com/formio/formio.js/issues/5868

**Comment by SSP23SCM38P** [comment]
follow this here : https://github.com/formio/formio.js/issues/5869
