### ISSUE TITLE
How programmatically  Edit , delete, save row in edit grid

### ISSUE THREAD

**Issue by jaisonmaqta** [formio/formio.js#5862]
Instead of clicking the buttons i want to enable the row in edit mode, is there any event when we are start editing the row

**Comment by lane-formio** [comment]
<div>Agent Olga Bannikova linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51356">51356</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
You can check here:
https://github.com/formio/formio.js/blob/master/src/components/editgrid/EditGrid.js#L535
