### ISSUE TITLE
[BUG] Loading a datagrid with more than 1 row of default values displays only one row in form builder 

### ISSUE THREAD

**Issue by Janis-K** [formio/formio.js#5872]
**Describe the bug**
Loading a datagrid with more than 1 row of default values displays only one row in form builder 

**Version/Branch**
Formio.js 4.16.0

**To Reproduce**
1. Create form
2. Add datagrid component
3. Edit datagrid to have multiple rows of default values
4. Save form
5. Load form from the saved json
6. Observe that in the builder only one row is created, while in the renderer the correct count of rows are there

**Expected behavior**
Should display whatever the amount of rows are there in component's default values

**Screenshots**
<img width="1468" alt="Screenshot (72)" src="https://github.com/user-attachments/assets/48a4b72e-b141-4cf7-a217-ef2ce3d04abd">

**Additional context**
Form.io sandbox ID to reproduce - 67120b181843cdba0835ec8d

**Comment by Tatsiana8** [comment]
@Janis-K Thank you for taking the time to report this issue! 
I have created a ticket for our backlog. 
For internal reference: FIO-9249

**Comment by heather-formio** [comment]
@Janis-K Can you try setting the minimum length in the validation tab of the Data Grid to whatever number of rows you'd like to have open? 

While we have created a ticket, this has not been prioritized as the builder context is not the expected context to have submission data handling feature functionality appear within the UI. We would welcome a PR if you would like to submit for review. 

<img width="1086" alt="Screenshot 2024-10-25 at 2 15 30 PM" src="https://github.com/user-attachments/assets/1fd91263-8cd2-49d4-ab4d-f1a903612367">

Let us know if you have any other questions, I'm closing this thread for now, feel free to reopen if more is needed.
