### ISSUE TITLE
Forms can be created with _id set to NULL

### ISSUE THREAD

**Issue by cohesivejones** [formio/formio.js#589]
We are currently in the process of creating our own formio administration portal and leveraging the api code located in src/Formio.js.

When calling saveForm(...) with form data that includes `id: null` this creates an invalid form that cannot be deleted from the formio api. 

Is the intention to call saveForm with a form data structure that does not include id when creating a form?

**Work around**
Our wrapper code is using typescript, so I have created two separate Form types here:
```
// for form update
type PersistedForm {
  id: string
  name: string
  ...
}
// for form create
type NonPersistedForm {
 name: string
  ...
}
```

**Comment by travist** [comment]
Thanks for reporting this. We will take a look.

**Comment by randallknutson** [comment]
PR https://github.com/formio/formio/pull/708

**Comment by jhen1422** [comment]
Issue has been merged and resolved
