### ISSUE TITLE
bug with custom submission.data & container & columns component 

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#592]
i'm trying to inject default values to form(which has container component in it):
```
    Formio.createForm(document.getElementById('${formId}'), _scope${formId}.formSchema, _scope${formId}.formOptions).then(function (form) {
            form.submission= {data:{containerfeild:{field1:1111}}};
```
but the value won't show in the form

**Comment by amirmf** [comment]
maybe related to this one 
[585](https://github.com/formio/formio.js/issues/585)

**Comment by amirmf** [comment]
i fixed the bug with the following code:
Container.js in line 75-78
old code:
```
      else if (_.has(value, component.key)) {
        component.setValue(_.get(value, component.key), flags);
      }

```
new code:
```
      else if (_.has(value, component.key)) {
        component.data = value;
        component.setValue(_.get(value, component.key), flags);
      }
```

**Comment by amirmf** [comment]
[sample-form](https://we.tl/TYsd20GZ8h)

use this sample form for debugging.... i have custom button with a debugger in it. 

i think this is happening only when you have a layout component(columns/fieldset) in container.
in my sample-form you can see the "t1" field works fine but you don't have the data of "t2" & "t3" which are in column component.

* you should set  form.submission= {data:{}}; after form creation

**Comment by jhen1422** [comment]
Could you try using the latest 4x renderer?

If the issue persists please feel free to open a new issue.
