### ISSUE TITLE
Component Edit > Data tab does not retain values even when switching between tabs

### ISSUE THREAD

**Issue by technofreak** [formio/formio.js#596]
Steps to Reproduce:
1. In the builder, drag and drop a new Select component.
![screen shot 2018-08-13 at 16 25 45](https://user-images.githubusercontent.com/1102388/44015932-368e65ea-9f16-11e8-9354-83758ba14466.png)
2. Move to the Data tab and mention a data source URL for the Select component
![screen shot 2018-08-13 at 16 25 59](https://user-images.githubusercontent.com/1102388/44015953-4f9fde10-9f16-11e8-8f5d-4c9840c993fb.png)
3. Move to the Display tab and come back to Data tab. The previously filled data source URL is gone.
![screen shot 2018-08-13 at 16 26 07](https://user-images.githubusercontent.com/1102388/44016023-9da5230e-9f16-11e8-894e-f13aa3b16010.png)

This also happens when you have saved a component with data source URL, then open the update component dialog and when you move over to the Data tab the filled values are gone.

**Comment by jhen1422** [comment]
This issue has been resolved
