### ISSUE TITLE
When I try to run formio i get the following error:

### ISSUE THREAD

**Issue by prakash-mukkamala** [formio/formio.js#5961]
I tried to incorporate formio as:
  <formio src='https://examples.form.io/example'></formio>

I installed formiojs and @formio/angular. Both installed fine.

But, I get the following error in console and the form doesn't render: Any reason why?
![{6B5DAF40-BAD6-4852-895C-7BADDCA0149D}](https://github.com/user-attachments/assets/c221e7ab-61be-4210-aa6d-1d57a04aa77a)

![{EEB64B42-6625-48CA-9A8C-BCF6D0EA2AB0}](https://github.com/user-attachments/assets/3133187e-e797-404c-b387-aa39180d6a27)

**Comment by prakash-mukkamala** [comment]
It was due to CSP

**Comment by expertprincekumar** [comment]
We are encountering issues rendering our form when implementing Content Security Policy (CSP) without unsafe-eval. As per our security guidelines, we are required to remove the unsafe-eval directive from the script-src policy.

Issue Details
When unsafe-eval is removed from the CSP, the form fails to render correctly. This appears to be related to the use of libraries or frameworks that rely on eval-like functionality, which is restricted by CSP policies. The affected components are critical to our application, and the error prevents users from interacting with the form.

Request for Support
We seek guidance on:
Workarounds: Any suggested approaches to handle CSP restrictions without enabling unsafe-eval.
Library Updates: Is there a roadmap to eliminate the reliance on eval in the library?
