### ISSUE TITLE
Wizard cancel button behaviour

### ISSUE THREAD

**Issue by aminmc** [formio/formio.js#622]
Hello,

How does one override the behaviour of the cancel button on a wizard page? I've tried to hook into the 'resetForm' event but this doesn't seem to work. I'd also like to override the prompt dialog window and redirect the user to a separate page.

Thanks

**Comment by jhen1422** [comment]
Hello Amin,

Jeriah here from the Form.io support team. Thank you for reaching out.
 
Currently, there is not a way to override the Cancel button behavior but you can hide the button. Below is documentation detailing on how to accomplish this.
 
https://github.com/formio/formio.js/wiki/Form-Renderer#options (see button settings section).
 
Once the Cancel button has been removed, you can then provide your own button. 
 
The real solution is coming along with the 4.x branch of our renderer which include templating abilities in our renderer where you can configure this functionality directly.

**Comment by learner291** [comment]
> 
> 
> Hello Amin,
> 
> Jeriah here from the Form.io support team. Thank you for reaching out.
> 
> Currently, there is not a way to override the Cancel button behavior but you can hide the button. Below is documentation detailing on how to accomplish this.
> 
> https://github.com/formio/formio.js/wiki/Form-Renderer#options (see button settings section).
> 
> Once the Cancel button has been removed, you can then provide your own button.
> 
> The real solution is coming along with the 4.x branch of our renderer which include templating abilities in our renderer where you can configure this functionality directly.

Hi,

Has the new solution released in 4.x branch of the renderer? If yes, how can I achieve the following behaviour: 

I need to redirect users to a different page when they click on cancel button so it would be better to have some type of control on cancel button click event.

**Comment by aminmc** [comment]
Hello

You can pass beforeCancel function in the hooks section of the tenderer options.

**Comment by learner291** [comment]
> Hello
> 
> You can pass beforeCancel function in the hooks section of the tenderer options.

This was working but since the upgrade, the button is no longer hiding. I wonder if there is a different property now for hiding cancel button? Is that correct?

**Comment by wag110894** [comment]
@learner291 can you provide a jsfiddle or a form embed of the button no longer hiding. Also, what version of formio.js are you running?
