### ISSUE TITLE
Getting Issue with logic filter. 

### ISSUE THREAD

**Issue by AvnishVerma** [formio/formio.js#628]
I am getting issue with Logic filter. I am able to create filter for any component but those filter not works for that component. and after creating the filter setting icons are also get hide. Once I create a logic filter then i am not able to edit or remove that control. 

I also experience same issue on https://formio.github.io/formio.js/app/builder example.

JSON : {
    "display": "form",
    "components": [
        {
            "input": true,
            "key": "number",
            "label": "Number",
            "type": "number"
        },
        {
            "label": "Number 1",
            "mask": false,
            "type": "number",
            "input": true,
            "key": "number1"
        },
        {
            "label": "Number 2",
            "mask": false,
            "type": "number",
            "input": true,
            "key": "number2",
            "logic": [
                {
                    "trigger": {
                        "type": "simple",
                        "simple": {
                            "show": true,
                            "conditional": {
                                "when": {
                                    "label": "Number",
                                    "value": "number"
                                }
                            },
                            "eq": "1"
                        }
                    },
                    "actions": [
                        {
                            "type": "value",
                            "name": "Action",
                            "value": "value=data.number;"
                        }
                    ],
                    "name": "Test"
                }
            ]
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by jhen1422** [comment]
Hello,
 
This is Jeriah from the Form.io support team. Thank you for reaching out and reporting these issues regarding the Logic feature.
 
 Could you please send the embed URL of the form you are having these issues on so we can further investigate? (screenshot for reference https://www.screencast.com/t/R8gQxQfL )
 
You can either post a comment within this thread with the embed URL or send to be directly - jeriah@form.io . 
 
We also have support packages available if you are interested to work directly with our developers.
 
Thank you!

**Comment by AvnishVerma** [comment]
I am using formio.js plugin in my application. I am not using your platform. I have checked at your portal there is not logic tab available in components properties.

![image](https://user-images.githubusercontent.com/7963769/44830814-3d886200-ac41-11e8-99f8-89fb88e15585.png)

**Comment by AvnishVerma** [comment]
![image](https://user-images.githubusercontent.com/7963769/44850517-0fc00f00-ac7b-11e8-82c0-fc0660129a32.png)

**Comment by denisekay** [comment]
The ‘Logic’ feature is part of our Core Builder which is currently in development at https://beta.form.io/ . This feature is not provided on our portal at https://portal.form.io/#/. We are planning to go live with https://beta.form.io/ sometime in Q4.
