### ISSUE TITLE
Not proper working with bootstrap 4

### ISSUE THREAD

**Issue by monikapathania** [formio/formio.js#633]
Hi
my project build in bootstrap 4 react js when i used this form builder in our project with out using bootstrap 3 cdn link its not working properly design messy and not show Glyphicon icon and when i used with bootstrap 3. its effects my other pages because i am using bootstrap 4.
please suggest any solution form that how i can use form.io with bootstrap 4

**Comment by denisekay** [comment]
This is coming in 4.x. The icon library is pluggable as well as the front end framework.  We are scheduled to release our 4x branch in Q4.

**Comment by monikapathania** [comment]
Hi denisekay.
Can you please provide release date and month because we planning to buy it so we need it earlier  stage of Q4.
