### ISSUE TITLE
Search not working on Select Components

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#663]
I have a Select component with a  raw JSON with Countries. I use the "starts with" search filter.
When we use the Form in Form.io there is no problem and the search executes as expected.

![screen shot 2018-09-15 at 16 20 29](https://user-images.githubusercontent.com/3051507/45589868-e3a3bf80-b903-11e8-8786-43bf1ddc7f64.png)

But when I do the same search on our App using formio.js we get no results back from the search

![screen shot 2018-09-15 at 16 20 37](https://user-images.githubusercontent.com/3051507/45589858-ca027800-b903-11e8-87a5-6df8ca734451.png)

Find here and example element of the RAW json

[
  {
    "value": "AF",
    "flag": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAwCAYAAAChS3wfAAAF5UlEQVRoQ+2ZaWwU5xnHf7O7s4f38C5e8H3g4GDiGKcLVFBjCoYkchJSEhcBraIoCVKgSgFxtqnStFFQwE2FiiBRokRBISJAVGjiBuMk5rBKSnOQ4FAMrPGJr12bXexd7+w1U7ERUVPlE3I/jDXzbd53ZqTnN8/zf45XABTG+XoeWDjO3zztgT88Pc4fBQQNgOYBWghoGjDe0qKJoJYFtDSo1QFaITTOyqpVglopPEF6AUNGBo45c0iEQhicTiJeL8mREQRRRI5GiQ8O/mDwTIgQMObkoAgC7poaIp2dWGfMYMzrRWprw5Sfj85qReroQOrsRA6HvwdC9QDMJSUY0tNJDA9jcLlIhsMo8TimvDyURAJrWRlSdzeJkRHSpk9ncN++iQPANC0fvdFO+rx5XG9qItrTQ8aDD6K32Ri7eBHR7SbQ1IStogLz1KmEL10COUzkcvd3EFTrAaaSbNyrfk74q4tEve1ELnWkjLLceSfodBgnTyZ84QKJQCC1nl49H0WI4VjwE4YOHUG6+C0EVQJQBMhcsxxMAjohjRsfniJypZPC57bRtX0nU7f/Hr3TxdUNWynYtpGuF3ZinlaAc2k1MlEEGQZ2v4ugqBSAZU4pjrke5PAYRnc2vXWvpv5m7m82IvW1U1y3A73BjPeZZzAXltC7c9e3+1vWEA34EF1Ogh+fIvJ1uzo9wDZ/JsnhAI7FS/C/fQh5ZCxl4MwTjXTt2EHB7zYj6PR0PvsCRX98npbq+1P7+nQrWasfI3D8OIrdQuRsq/oAVE8SmbRkMbZ7Kon6O7h+pAFBMKAzW8lc/RSTlz6UEryb18006D/WQP+evUCCmz7vrK3BmjeD4OkGgmfOcCIvoq6h6PJfPoTU38Pd+z/gyqb1DB/8GzmbVtP35zfI+vUTjJ79F2KGg+jAADprOvZZHgZ2v/XdM5MfW860l/5Eyy8ewFo8nfdajqoLwLKllehdDmylP8JgSCf4+UmK6/7C15XzKKx7id6XXyZy3psaydrmlpO7bh3tzz6H51QzbZvX4Zy3hGR0mPCV88T8QT7o/1RdAB5ethBzThYxvx+zq5DYYA9yVELq7sFRuQBL6XRMudlcXb8BRTCkQuJG80nMU4vQWdIwZRcS9XkRMzOJXO2i3vdPdQFY9auncFYuQPJ1EfF2klm7gn+vXI4iJSj9+2G+OfwIc7edI3ShlctPrqX04D5aa2rRW03MOHAI3/t/xXJHEcbMPEbO/IODZ99UF4D7iqfgXrEMvZjOpEX30rZpE+Fz36REr2TPHpLKDSJ9veSsXUv3iztxlFVwdf2W1L7NU05xXR2B5hMkpQDXjx6j0d6nLgALDQL26pkkRxPYZ5UTbr1CqOkcYk4mni8+59oruyEZQ5EkMIgUbf0t5+YvQrrsxV5Vhq3ibka+aEHnsjL6yZecLldUBgCY8nQtxGVi8TAGo43g+03krd+IKTcHORojPjCIIBoR0iwoo6MkRkP0vb4X57J7wZBEiekwOCz4Xjmsvjrg5kzQdEce7pUPkxwawbl4MbGuHkLnW4ld60+1vqLLhWA0IrW3p1xfzM3Efk8ZpqIC/I0NmLLcDB+sR2rrVicAncXMzOaPsJfPJtjczNCxAyQDQfwHGlBkGbvHA6JIpLWV5NgY7kd/ipiVg7tmJY6qKkLnP6NlUQ1yRFIngFRZa7dgq/IgmPWYcvORg6NI7ddQoroUBEFREMxmdDYFU3EB+jQLUk8XspRk9ORnyOGoervBW828qWgK2RvWEB8K4ayswlHhwXfiCPHWXrBZMJfko4+aSSu/C1/9UfR2kf5drxHt6Ff/POCWBe6f1ZDxaC0Oz49JhscYrq/HPns2MZ+PuN+fGoa4qhfR985bBI8fZ+johxNnIvTflmQ9/jjF219E6rnG9cZGkvIY+mwrUks3SijG4P793zP81o0qByI/aMltLmoAtIORCXIwcpsRoN464HYN/t/3NA3QNEDTAPW1w+MV/6o9GdIAjCMBLQtoWeD/kwX+A5byxc+4OURaAAAAAElFTkSuQmCC",
    "label": "Afghanistan"
  }
]

Is it something that we are doing wrong or a bug?

Best regards!

**Comment by wag110894** [comment]
Hello Ignacio,

This is William with the Form.io support team.

Thanks for reaching out! 

Try using the newest version of formio.js.

Please let me know if you have any further questions or concerns.

Thanks, 

William Gay
Form.io Developer Support

**Comment by cabrerabywaters** [comment]
Hello @wag110894 ,

Forgot to mention, I was using version 3.5.2 and now changed to 3.5.3 and the problem is still there.

Best regards,

**Comment by angelhu513** [comment]
@cabrerabywaters 

After further testing, we were unable to replicate the issue, can you please send us your form embed code so we can investigate further? Thank you.

**Comment by cabrerabywaters** [comment]
@angelhu513 
Sure it took me a while, have a look at the following form (check the country select)

https://codepen.io/cabrerabywaters/pen/mGYNOw

The issue only shows up when I include the flags as a data:image/png;base64, element. I guess that the element tries to also search for the text inside that label and then dies?

Best,
Ignacio

**Comment by wag110894** [comment]
Hello Ignacio,
 
William here again.
 
We have created a ticket for this issue and have added it to our backlog. For reference, the ticket number is FOR-1725. Please let me know if you are interested in a quote to expedite this development.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by wag110894** [comment]
Hello Ignacio,

William here again. 

Our development team has estimated this issue at 4 hours.  Please let me know if you’re interested and I can send you a formal quote.
