### ISSUE TITLE
Cannot read property 'version' of undefined moment-timezone.js

### ISSUE THREAD

**Issue by ayaanraj** [formio/formio.js#681]
After installation, I get this error : <b>Cannot read property 'version' of undefined moment-timezone.js</b>
this error is occurring when initialization of <i>formiojs@3.5.7/utils/utils.js</i>.

I think, this is because moment-timezone.js can't get moment, as per my research their is some issue in loading moment, in moment-timezone.js

**Comment by wag110894** [comment]
Hello Arun,
 
This is William with the Form.io support team.
 
Thanks for reaching out! 
 
How are you "initializing" the utils? Could you provide a JSFiddle with the issue replicating? 
We have support packages available if you are interested in having one of our developers help you with this issue
 
Thanks, 
 
William Gay 
Form.io Developer Support

**Comment by ayaanraj** [comment]
Hello William,
Thanks for you reply.

I just installed the package like this:
```jspm install npm:formiojs```

And I'm importing formiojs as:
```import * as formio from 'formiojs';```

And I get this following error:

![screenshot from 2018-09-25 10-54-31](https://user-images.githubusercontent.com/29095142/45995194-b4840f80-c0b4-11e8-9e7d-5c788475f410.png)

**Comment by wag110894** [comment]
Hello Arun, 
William here again with Form.io support. Thanks for reaching out! 
 
This seems to be because this is importing moment-timezone, but is not importing "moment" which is a dependency of moment-timezone. Are you importing this in Node.js or in the browser using Babel?
 
Thanks,
 
William Gay 
Form.io Developer Support

**Comment by ayaanraj** [comment]
In the browser using Babel

**Comment by wag110894** [comment]
Hello Arun,

We have created a ticket and have tagged you on it. For reference, the ticket number is FOR-1729.
In the meantime you can manually install moment.js to fix the issue.
Please let me know if you have any further questions or concerns.
Thanks,

William Gay
Form.io Developer Support

**Comment by travist** [comment]
I believe that this is a package dependency issue where you are not pulling in all the dependencies into your library. Please try it after using ```npm install``` and let us know if the error goes away.
