### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by SaaJoh0783** [formio/formio.js#685]
It would be really nice to see what is included with each release. Maybe there already is a place for that, but I have not found it.

**Comment by wag110894** [comment]
Hello John,
This is William with the Form.io support team. Thanks for reaching out!
Here is our change log to see what is included with each release.
https://github.com/formio/formio.js/blob/master/Changelog.md 

We would love to connect hear about your project and see how we can help.  Please let me know when you are available and I can setup a meeting. We also have support packages available for training, support or development services if you are interested! These services connect you directly with a Form.io developer and can be a huge help with your app.

Please let me know if you have any further questions or concerns.
Thanks,
William Gay
Form.io Developer Support

**Comment by SaaJoh0783** [comment]
That really helps. Thanks!
