### ISSUE TITLE
Optimal approach to customize API property names

### ISSUE THREAD

**Issue by abarrak** [formio/formio.js#691]
Hi guys ..

I'm looking for any insight of how to change the API property free text approach to a set of predefined API properties.

Altering API tab schema and replacement of `textfield` to `select` got me half of the way, but I'm still in need for the place to include fetching/populating list logic any time the form control is configured.

I've already examined assigning in [baseComponent](https://github.com/formio/formio.js/blob/master/src/components/base/Base.js#L335) constructor like so:
```javascript
    const customMode = options.predefinedProperties;

    if (customMode) {
      this.predefinedProperties = [
        { label: 'A', value: 'a' },
        { label: 'B', value: 'b' },
        { label: 'C', value: 'c' },
      ];
```
But it seems to be applied on initial rendering of form but [not in any new subsequent component creation](https://github.com/formio/formio.js/blob/master/src/components/Components.js#L32-L44).

![1](https://user-images.githubusercontent.com/20784990/46124825-c689bd80-c22e-11e8-96b4-8bdda3c2c5d1.png)

Thanks 🌹

**Comment by wag110894** [comment]
Hello Abullah,
This is William with the Form.io support team. Thanks for reaching out!
You can switch the textfield to a select component as you mention. Then you can set the data type to "url" and query an external data source. Field settings are themselves form.io forms so you can configure them in the form builder and copy fields into the edit forms. One way to test this out is to create the select component in a form on portal.form.io, get it exactly how you want with the data source URL and then copy it into the form configuration.
We would love to connect hear about your project and see how we can help.    We also have support packages available for training, support or development services if you are interested! 

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by abarrak** [comment]
Thank you William for the follow-up, and the clear explanation.

Indeed, I was able to see more of the possibilities of `select`, its data-source, `refrshesOn` to link to lists, and so on.

Although these didn't address my issue, I needed custom hook up to fetch predefined API keys, and set them once globally.

```javascript
Formio.predefinedKeysMode = false;
Formio.predefinedKeys = [];
```
