### ISSUE TITLE
Form.destroy() not destroying flatpickr elements

### ISSUE THREAD

**Issue by pmanu93** [formio/formio.js#693]
Hi,
Every time a form with a flatpickr is rendered, it creates extra elements which aren't destroyed after calling `form.destroy()`.

![captura de ecra de 2018-09-27 19 09 01](https://user-images.githubusercontent.com/15691766/46165544-d209d280-c288-11e8-883a-191e936f2642.png)

**Comment by wag110894** [comment]
Hello Pedro, 
Thank you for your patience. We have fixed this issue regarding flatpickr element. Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support
