### ISSUE TITLE
there is no custom component in latest version 

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#694]
i've used custom component in your angularjs version of formbuilder 

but i couldn't find custom component in formiojs form builder !!
is there any way to active the component in form builder ?

**Comment by wag110894** [comment]
Hello Amir,
 
This is William with the Form.io support team. Thanks for reaching out! 
 
We are in the process of completing the new core form builder and it is in our backlog to add the custom component.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by wag110894** [comment]
Hello Amir, 

The Custom Component has been added in the 3.12.3 version of our Core Renderer.

Please let us know if you have any further questions or concerns.

Thanks,
William Gay
Form.io Developer Support
