### ISSUE TITLE
Formbuilder submit form json

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#695]
Hello FormIO team,

I want to build a form and like to save the formbuilder json result and store it with my own code. But I can not find an example how to capture the form json when clicking the submit button.

Can you advise?

Thanks Mario

**Comment by wag110894** [comment]
Hello Mario,

This is William with the Form.io support team.

Thanks for reaching out! 

Here is example code showing how to get the JSON of the form here. https://raw.githubusercontent.com/formio/formio.js/master/app/builder.md 

This corresponds to this page https://formio.github.io/formio.js/app/builder .

You can also try using the Form Manager library in the Angular library which has the save form feature, but you will need to point the API to Form.io to get this to work.

https://formio.github.io/angular-demo/ 

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by KyooMario** [comment]
Hello William,

Thanks for your fast response. I will look into this.
And while I have your attention can I ask another one.
We noticed that we can choose Quill to get a Rich text editor in the text area but we also read that CKeditor is an option. Can you tell me how to get CKeditor working with form.io js?

Kind regards,
Mario

**Comment by wag110894** [comment]
Hello Mario, 
 
CKEditor is only available for angular 1 renderer. It does not work as well with newer frameworks which is why we switched to quill and ace. 
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by KyooMario** [comment]
Hello William,

Thanks. Understand.

I stumbled across an issue: When I use tabs layout component and I put a component in Tab 1 then I switch to another tab and drag a component into tab 2 the component in Tab 1 has disappeared. The same goes the other way around.

Can you advise?

I downloaded the github zip a few days ago.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello William,

My mistake. Sorry.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Michael,

Still an issue with the tab layout. But question first: Is tabs working? Because I cannot see this option in the form.io cloud.

But anyhow: I am trying to use the following json when opening the builder but Tab 2 renders empty:
Hope you can help.

The input below is just a copy of the builder schema when saved and used as an input.

`{"components":[{"components":[{"label":"Tab 1","key":"tab1","components":[{"label":"Text Field","allowMultipleMasks":false,"showWordCount":false,"showCharCount":false,"tableView":true,"type":"textfield","input":true,"key":"textField","widget":{"type":""},"tab":0,"placeholder":"","prefix":"","customClass":"","suffix":"","multiple":false,"defaultValue":null,"protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"dataGridLabel":false,"labelPosition":"top","labelWidth":30,"labelMargin":3,"description":"","errorLabel":"","tooltip":"","hideLabel":false,"tabindex":"","disabled":false,"autofocus":false,"dbIndex":false,"customDefaultValue":"","calculateValue":"","refreshOn":"","clearOnRefresh":false,"validateOn":"change","validate":{"required":false,"custom":"","customPrivate":false,"minLength":"","maxLength":"","minWords":"","maxWords":"","pattern":""},"conditional":{"show":null,"when":null,"eq":""},"mask":false,"inputType":"text","inputMask":"","id":"exq9iah"},{"input":true,"key":"select","tableView":true,"label":"Select","type":"select","data":{"values":[],"json":"","url":"","resource":"","custom":""},"valueProperty":"value","tab":0,"placeholder":"","prefix":"","customClass":"","suffix":"","multiple":false,"defaultValue":null,"protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"dataGridLabel":false,"labelPosition":"top","labelWidth":30,"labelMargin":3,"description":"","errorLabel":"","tooltip":"","hideLabel":false,"tabindex":"","disabled":false,"autofocus":false,"dbIndex":false,"customDefaultValue":"","calculateValue":"","widget":null,"refreshOn":"","clearOnRefresh":false,"validateOn":"change","validate":{"required":false,"custom":"","customPrivate":false},"conditional":{"show":null,"when":null,"eq":""},"dataSrc":"values","filter":"","searchEnabled":true,"searchField":"","minSearch":0,"authenticate":false,"template":"<span>{{ item.label }}</span>","selectFields":"","id":"eg61n3"}]},{"label":"Tab 2","key":"tab2","components":[{"label":"Text Field","allowMultipleMasks":false,"showWordCount":false,"showCharCount":false,"tableView":true,"type":"textfield","input":true,"key":"textField2","tab":1,"widget":{"type":""},"placeholder":"","prefix":"","customClass":"","suffix":"","multiple":false,"defaultValue":null,"protected":false,"unique":false,"persistent":true,"hidden":false,"clearOnHide":true,"dataGridLabel":false,"labelPosition":"top","labelWidth":30,"labelMargin":3,"description":"","errorLabel":"","tooltip":"","hideLabel":false,"tabindex":"","disabled":false,"autofocus":false,"dbIndex":false,"customDefaultValue":"","calculateValue":"","refreshOn":"","clearOnRefresh":false,"validateOn":"change","validate":{"required":false,"custom":"","customPrivate":false,"minLength":"","maxLength":"","minWords":"","maxWords":"","pattern":""},"conditional":{"show":null,"when":null,"eq":""},"mask":false,"inputType":"text","inputMask":"","id":"ekgt673"}]},{"label":"Tab 3","key":"tab3","components":[]}],"label":"Index","mask":false,"tableView":true,"type":"tabs","input":false,"key":"index","placeholder":"","prefix":"","customClass":"","suffix":"","multiple":false,"defaultValue":null,"protected":false,"unique":false,"persistent":false,"hidden":false,"clearOnHide":true,"dataGridLabel":false,"labelPosition":"top","labelWidth":30,"labelMargin":3,"description":"","errorLabel":"","tooltip":"","hideLabel":false,"tabindex":"","disabled":false,"autofocus":false,"dbIndex":false,"customDefaultValue":"","calculateValue":"","widget":null,"refreshOn":"","clearOnRefresh":false,"validateOn":"change","validate":{"required":false,"custom":"","customPrivate":false},"conditional":{"show":null,"when":null,"eq":""},"id":"e3cleja"},{"type":"button","label":"Submit","key":"submit","disableOnInvalid":true,"theme":"primary","input":true,"tableView":true,"placeholder":"","prefix":"","customClass":"","suffix":"","multiple":false,"defaultValue":null,"protected":false,"unique":false,"persistent":false,"hidden":false,"clearOnHide":true,"dataGridLabel":true,"labelPosition":"top","labelWidth":30,"labelMargin":3,"description":"","errorLabel":"","tooltip":"","hideLabel":false,"tabindex":"","disabled":false,"autofocus":false,"dbIndex":false,"customDefaultValue":"","calculateValue":"","widget":null,"refreshOn":"","clearOnRefresh":false,"validateOn":"change","validate":{"required":false,"custom":"","customPrivate":false},"conditional":{"show":null,"when":null,"eq":""},"size":"md","leftIcon":"","rightIcon":"","block":false,"action":"submit","id":"ehtbl86"}]}`

Kind regards,
Mario

**Comment by Aiso786** [comment]
I've noticed this issue (Tabs losing content in builder mode).
To get around it, you have to navigate into each tab before doing any changes.
This is issue is occuring because only the firts tab has its content rendered if you look at the "Tabs" component code.

**Comment by KyooMario** [comment]
Hello Aiso,

Just tried the "navigate into each tab" approach but the issue remains.
Should I skip the Tabs for now because it is still in beta?

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Aiso,

Just to be sure because I cannot find the documentation but my approach to save the initial formtemplate after build is as follows:
I ask this so I know I am saving the correct schema.

`var builderSchema;
let formioComponents;
Formio.builder(document.getElementById('builder'), {
			components: this.formioComponents
		}).then(function(builder){
			builderSchema = builder.schema;
		});
function saveFormTemplate() {
//I am saving the builderSchema here
}
`

Please advise.
Kind regards,
Mario

**Comment by wag110894** [comment]
Hello Mario,
William here again with Form.io support. 
This all applies to the same issue. When you have multiple tabs, after adding components to all tabs, components in tab 1 disappear
This is a known issue. We have tagged you on this issue. For reference, the ticket number is FOR-1688. We will notify you once this issue is resolved.

Please let us know if you have any further questions or concerns. 

Thanks,

William Gay 
Form.io Developer Support

**Comment by KyooMario** [comment]
Hello William,

Thanks for the update.
Good luck with the progress.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello William,

While not using tabs I investigated another approach with buttons and hiding field sets but there is an disturbing issue doing this because when a field set is hidden the form field values inside this field set are not updated with existing form entry values.
Can you acknowledge this behavior and if true advise a fix?

Kind regards,
Mario

**Comment by wag110894** [comment]
Hello Mario,
This is William with the Form.io support team.

Thanks for reaching out! 

You can uncheck the setting 'Clear Value When Hidden' to allow values to be retained when a field is hidden.

Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by KyooMario** [comment]
Hello William,

Thanks. But I used the conditional logic to show/hide the component. So I did not enable the  "Clear Value When Hidden".

Does it make sense that I still have this behavior?

Kind regards,
Mario

**Comment by wag110894** [comment]
Hello Mario,
This is William with the Form.io support team.
 
Thanks for reaching out! 
 
This setting is checked by default when a component is added to the builder. Can you verify the setting is unchecked?
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by KyooMario** [comment]
Hello William,

Thanks for the quick responses. I appreciate this.
I will try to do this tonight or at least this weekend.

Kind regards,'
Mario

**Comment by wag110894** [comment]
Hello Mario,

Thank you for your patience while we worked on fixing FOR-1688(Tabs - When you have 3 a more tabs, after adding components to all tabs, components in tab 1 disappear). This issue has been resolved in our latest version of our Core Renderer (3.7.0).

Please let me know if you have any further questions or concerns.

Thanks!

**Comment by KarthikJohn** [comment]
Hello FormIo Team,
I am having Form Builder in my application with custom component in it. After creating a form, in form builder, how can I  provide title or name to that form. And aslo What can be done to save that form or JSON data to my local mongoDB.

Thanks in Advance.

**Comment by wag110894** [comment]
Hello Karthikeyan, 
Could you please create a new issue for this item. This will ensure that others with the same issue can locate the answer easier. 

Thanks.

**Comment by Abdalmassih** [comment]
> schema

Hello @KyooMario, I am facing an issue which might be related to your message which I am quoting. Your attached code retrieves the schema from *builder.schema on initial form builder object perfectly. However, did you find a way to get access to the schema after adding further components to the builder via drag & drop? i.e. if I drag another input text field the schema should get updated, but I cannot find a way to hook to this updated value. Any help would be appreciated. Thank you.

**Comment by KyooMario** [comment]
Hello Abdal,

I managed it as below but I reckon this is not the most efficient way because with every component change I rewrite the form schema I eventually save. I would prefer to "get" the last schema on save but did not find this method. So if someone else shows a more elegant way please come forward ;-)

`let formioComponents;
            Formio.builder(document.getElementById('builder'), {
                components: this.formioComponents//componentsTemp.components//this.formioComponents
            }).then(function (builder) {
                form.kyooboo__FormSchema__c = JSON.stringify(builder.schema);
                //component.set('v.form',form);
                builder.on('componentChange', function(){
                    //console.log('builder.schema: '+JSON.stringify(builder.schema));
                    form.kyooboo__FormSchema__c = builder.schema;
                    //if(!form.formId)form.formId = 'null';
                });
            });`

Kind regards,
Mario

**Comment by foduu-rahul** [comment]
Hello Support,
I am using form.io javascript library to build a form. its working with json files also.
but now i want to get json data when i add (drag & drop) every fields  in that form.
Please help me asap.
