### ISSUE TITLE
The required validation does'nt work when the component is in datagarid 

### ISSUE THREAD

**Issue by amirmf** [formio/formio.js#715]
The required validation does'nt work when the component is in datagarid

**Comment by wag110894** [comment]
Hello Amir,
This is William with the Form.io support team.
 
Thanks for reaching out! 
 
We have tested this issue and are unable to replicate the issue. Here is a screenshot of the required validation working inside a datagrid.
https://www.screencast.com/t/Ad3Px2moiM
 
On another note, Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help with your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support
