### ISSUE TITLE
Dynamically populated select box, retaining initial ID's

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#719]
Hi,

We have some select boxes that are dynamically generated from remote url json lists. These are referenced via ID's but the labels show in the drop down.
Where the user has visited the form before we auto select the ID they chose last time (this is a UUID). As the list populates and brings in the labels from the remote list this is replaced with the current list and the correct label selected however, if you look at the list the original UUID that we selected is still present in the list in addition to the correct text labels.
This looks like a refresh issue switching between the original ID and the correct label.

Mark

**Comment by wag110894** [comment]
Hello Mark, 
 
This is William with the Form.io support team.  Can you please produce a jsfiddle of the problem? This will help follow what the problem is.  
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support
