### ISSUE TITLE
Modal window

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#722]
Would like to have modal window component.
And modal window itself could support formio schemas.

**Comment by wag110894** [comment]
Hello Krixerx,

This is William with the form.io support team. Thanks for reaching out. 

We often provide quotes to our customers for new feature requests.  Our development team has estimated this feature at 16 hours.  Please let me know if you’re interested and I can send you a formal quote.

We would love to connect hear about your project and see how we can help.   Additionally, our on premise deployment allows you to deploy our entire platform within your own infrastructure giving you complete control over your data.  
 
And finally, we also have support packages available for training, support or development services if you are interested! 


Please let me know if you have any questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support
