### ISSUE TITLE
HTML Element component Bootstrap support

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#723]
All custom attributes are escaped in HTML Element component except src, href and class.

Why not to support bootstrap attributes too?

**Comment by wag110894** [comment]
Hello Krixerx, 
 
This is William here with the Form.io support team. Thanks for reaching out.
 
We have created a ticket for this item and have tagged you on it. For reference, the ticket number is FOR-1774.  We do offer the chance to expedite this issue.  Please let me know if you’re interested and I can send you a formal quote. 
 
We would love to connect hear about your project and see how we can help.   
 
And finally, we also have support packages available for training, support or development services if you are interested! 

Please let me know if you have any questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by krixerx** [comment]
Looks good now!
Tnx!
