### ISSUE TITLE
Build Issue With Node Version 8.12.0

### ISSUE THREAD

**Issue by abhisheksdm** [formio/formio.js#724]
I am unable to build with latest node version 8.12.0,

**Comment by travist** [comment]
I just updated my machine to the latest 8.12.0 and the build is working just fine for me. Can you elaborate what issue you are having? Are you on a Windows machine? If so, then you may need to install the Node build tools for windows, which you can read about here https://github.com/nodejs/node-gyp#on-windows

**Comment by abhisheksdm** [comment]
hello @travist i am using react-formio V3.0.1 in my application and i have tried on windows as well as linux also.  my issue is that if i try to make a production build using nodejs 8.12.0 then it failing and giving "javascript heap memory error" but if i remove the react-formio package from package.json then preforming same steps lead to successful production build

**Comment by wag110894** [comment]
Hello,

We haven't had this issue with our build process. We do depend on bcrypt which requires compiling or downloading a binary. If your system isn't set up to compile properly it may fail. Are you getting any errors during the build process?


Thanks, 
William Gay 
Form.io Developer Support

**Comment by abhisheksdm** [comment]
Thanks @wag110894  for your valuable reply, yes we are getting error during build process while using react-formio.
I am attaching the screenshot of the error, please let me know how to fix it, if you found anything helpful.
![image](https://user-images.githubusercontent.com/32297964/47000440-e9303780-d145-11e8-9b23-f0bc6c52eb32.png)
![image](https://user-images.githubusercontent.com/32297964/47000532-1a106c80-d146-11e8-8ab7-a1b11e948a13.png)

**Comment by wag110894** [comment]
Hello again,
This appears to be a known issue with create-react-app. Issue is here: https://github.com/facebook/create-react-app/issues/2555 

The reason our module triggers this is because it increases the source above the size that causes the crash.

Please let me know if you have any further questions or concerns.

Thanks,

William Gay 
Form.io Developer Support

**Comment by abhisheksdm** [comment]
Thanks @wag110894 , It really helped me, thanks alot.
Cheers...
:)
