### ISSUE TITLE
Resources not populated when we select Data Source Type of "Select" component as resource

### ISSUE THREAD

**Issue by sanjaykrgaur** [formio/formio.js#729]
When I select the Data Source Type of a select component as resource then all resources should be populated in the resource dropdown. But resource dropdown remains empty. When I checked in developer options --> network I found that no request/API call is being made when resource is selected in the Data Source Type.
Am I doing anything wrong or is there any other way of doing this?
![resource](https://user-images.githubusercontent.com/34021269/47080117-c4f75800-d224-11e8-8a71-5489645fb013.png)

**Comment by sanjaykrgaur** [comment]
Hi,

Thanks for the prompt response. I have set the baseUrl already. When I select a resource component then all resources are shown in the dropdown. Issue is only when I choose the select component and  set its Data Source Type as resource. Then no resources are populated there. I am using version 3.6.3

Steps to replicate it are:-
1. Create a resource save it with some name
2. Now create a form and drag and drop the select component
3. Goto tab 2 and select data source type as resource
4. The resource created in step 1 should come in the "resources" dropdown but nothing is coming.

**Comment by sanjaykrgaur** [comment]
Hi,

I upgraded to latest version 3.6.7 and the issue is resolved. Thanks for your support

**Comment by Josephalexantony-aot** [comment]
I got the same issue with version 4.3.0

**Comment by wag110894** [comment]
@Josephalexantony-aot Try upgrading to newer verison of formio.js. The latest stable version is 4.14.9.
