### ISSUE TITLE
Component disabled while it shouldn't be

### ISSUE THREAD

**Issue by Aiso786** [formio/formio.js#735]
Hello guys,

In "Base.js", we should have this:
`// Do not allow a component to be disabled if it should be always...`
`if (disabled && !this.shouldDisable) {`
`      return;`
`}`

Instead of this:
`// Do not allow a component to be disabled if it should be always...`
`if (!disabled && this.shouldDisable) {`
`      return;`
`}`

**Comment by Aiso786** [comment]
I've made a PR #736

**Comment by travist** [comment]
Thanks for the pull request. Although I am thinking that this needs to handle both cases like this.

```js
if ((!disabled && this.shouldDisable) || (disabled && !this.shouldDisable)) {
  return;
}
```

Do you agree?

**Comment by Aiso786** [comment]
Yes i agree, i'll update the PR.

**Comment by Aiso786** [comment]
PR updated.

**Comment by travist** [comment]
Looks good. Thanks for the PR. I will include that in the build I am going to do today.
