### ISSUE TITLE
Documentation dead link

### ISSUE THREAD

**Issue by dolphinsd** [formio/formio.js#740]
https://formio.github.io/formio.js/docs/class/src/Formio.js~Formio.html

**Comment by wag110894** [comment]
Hello Again,

Can you please clarify where this link is from? This would help us locate it so we can update it to the correct link.

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by travist** [comment]
I know where this is from. For some reason ESDoc is messing up on that page. We will need to take a look.
