### ISSUE TITLE
Filter Query on select component not working

### ISSUE THREAD

**Issue by sanjaykrgaur** [formio/formio.js#741]
I followed the tutorial below to apply dynamic filtering on select components but it is not working.

https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/

Also if I tick the "clear value on refresh" checkbox for any select component then edit option for that select component does not come in the form builder.

**Comment by wag110894** [comment]
Hello,
 
Can you please clarify what you mean by “not working”? We are unable to replicate this issue on our end. Could you please send us your embed code so we can get a sense of where this issue is originating from? 
 
Thanks, 
William Gay 
Form.io Developer Support
