### ISSUE TITLE
Minimum/Maximum value = 0 not validating

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#747]
Hi, If you have a number component with validation minimum or maximum value 0, it doesn't check the validation for it.

Thanks

**Comment by wag110894** [comment]
Hello David, 
 
William here again with Form.io support. Thanks for the feedback!
We have created a ticket and have tagged you on it. For reference, the ticket number is FOR-1821.
We will let you know when this has been addressed. 
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay

**Comment by wag110894** [comment]
Hello David, 

Thank you for your patience regarding this issue while we worked on it. We were able to fix this issue in our latest version of our Core Renderer (3.7.0)

Please let me know if you have any further questions or concerns.

Thanks!
