### ISSUE TITLE
Data grid with multiple components with tooltips only shows first tooltip

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#748]
Hi, if you have a Data Grid component with multiple components inside it with tooltips, only the first component shows up with a tooltip on it.

![image](https://user-images.githubusercontent.com/24515980/47541923-d88e7700-d926-11e8-9415-6bfb5232940e.png)

Thanks

**Comment by shsfez** [comment]
Hi, any news about this issue?

Thanks

**Comment by wag110894** [comment]
Hello,

We have added this item to our backlog. We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you. Our support team has estimated this fix at 2 hours. 

Thanks.

**Comment by wag110894** [comment]
Hello,

This issue have been resolved in the latest version of our 4x Core Renderer.

Thanks.
