### ISSUE TITLE
Components within tabs are being deleted on change

### ISSUE THREAD

**Issue by Davidvlv** [formio/formio.js#749]
Hi, there is an issue with the Tabs component in which all the predefined components in a tab get deleted when a change happens. I have created a jsfiddle here:

[https://jsfiddle.net/g4asLdyp/8/](https://jsfiddle.net/g4asLdyp/8/)

If you don't activate tab 2, the pre-defined form components inside tab 2 are deleted, but if you click on tab 2 before making changes, the components are kept.

**Comment by wag110894** [comment]
Hello David, 
This is William with the Form.io support team. This is a currently known issue and we are working to . I have tagged you onto the existed ticket. For reference, the ticket number is FOR-1508.  We will keep you posted.

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by jhen1422** [comment]
This issue has been resolved with the latest version of formio.js
