### ISSUE TITLE
Select Component 'Filter Query ' error

### ISSUE THREAD

**Issue by beniaminp** [formio/formio.js#751]
Hello!
If in a Select Component, on tab 'Data' at 'Filter Query' by mistake I put 2 equals (ex. `data.test1==data.test2`), the Select Component is disappearing from the form and I cannot correct my error.
It still exist in MongoDB and if I correct that double equal (I put it `data.test1=data.test`2) the field is visible again in builder.
Do you have any idea on how to solve this?

Thank you!

**Comment by wag110894** [comment]
Hello Dragos,
This is William here with the Form.io support team. Thanks for reaching out!
If you could do a pull request to fix this issue, that would be great. We have added this item into our backlog and have tagged you on it. For reference the ticket number is FOR-1820.
Please let me know if you have any further questions or concerns.
Thanks, 
William Gay 
Form.io Developer Support

**Comment by beniaminp** [comment]
Hi Will!
I'll do it as soon as possible.

Thank you!

vin., 26 oct. 2018, 20:02 Will Gay <notifications@github.com> a scris:

**Comment by jhen1422** [comment]
This should be resolved in our 4x renderer. 
If the issue persists, please feel free to open a new issue.
