### ISSUE TITLE
Checkbox component not displaying on mobile browsers

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/formio.js#756]
I having issues displaying the checkbox component on mobile browsers and cordova.

Please check the following form
https://codepen.io/anon/pen/OoYKPx#_=

The web version display correctly the checkbox "Data Collected"
![screenshot 2018-10-27 02 02 50](https://user-images.githubusercontent.com/3051507/47599824-b29bbd80-d98c-11e8-98f1-d58b973bac7a.png)

But when I open it in cordova on android 4.6 5 and 6 the checkbox dissappears.

<img width="571" alt="screenshot 2018-10-27 02 24 14" src="https://user-images.githubusercontent.com/3051507/47599962-92213280-d98f-11e8-964e-257ffaa37da3.png">

On safari  I can see the following error.
![screenshot 2018-10-27 02 35 49](https://user-images.githubusercontent.com/3051507/47600049-5b4c1c00-d991-11e8-9ebf-45ce312919b2.png)

**Comment by travist** [comment]
We will investigate. If this is confirmed, then I am sure this will be elevated as a high priority bug for us to fix. We will let you know.

**Comment by jhen1422** [comment]
Could you please provide a form embed of the issue?
We are unable to replicate this issue on our end.

Thanks!
