### ISSUE TITLE
Form Builder : cannot find "Value Property"

### ISSUE THREAD

**Issue by samayool** [formio/formio.js#757]
In the Form Builder when I add "Select" Component 
and set data source to URL
I Can add "Data source Url" and item template 
But there is no  "Value Property"  ! !
Then I select each option the value is set wrongly to "[Object object]"

is it a Bug Or there is another way to add Value Property ?
I am adding builder to my code using this : 
    `Formio.builder(document.getElementById('builder'),{},{})`

How Can I Fix it ?

**Comment by wag110894** [comment]
Hello Sam,
 
This is William with the Form.io support team. Thanks for reaching out! 
Value Property has not been added to our beta portal yet but it is on our backlog. We have created ticket and have added it to planning. For reference, the ticket number is FOR-1831.
 
We will let you know when this is added to our Beta Site.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by samayool** [comment]
Hello William,

Thank you,
There is another issue I will ask in a new Issue.

Regards

**Comment by AnasHijazi** [comment]
@wag110894 any update ?

**Comment by jhen1422** [comment]
Value property has been added to the 4x builder.

Thanks!
