### ISSUE TITLE
Is there any method to update FormBuilder's components without re new a FormBuilder?

### ISSUE THREAD

**Issue by kokororin** [formio/formio.js#762]
```js
const builder = Formio.builder(document.querySelector('#form'), {}, options);
```

Now I want to update the initial components, is there a method like 
```js
const myComponents = [
  {
    label: 'Text Field',
    allowMultipleMasks: false,
    showWordCount: false,
    showCharCount: false,
    tableView: true,
    type: 'textfield',
    input: true,
    key: 'textField',
    widget: {
      type: ''
    }
  }
];

builder.updateComponents(myComponents);
```

I have tried `builder.clear()` and `builder.build({components: myComponents})`, but it not work.

**Comment by wag110894** [comment]
Hello,
You can just set up the configuration for the builder (like you see it here http://formio.github.io/formio.js/app/examples/custombuilder.html) and then you can call “builder.redraw()” when you want to redraw the builder with new configurations.
 
Please let me know if you have any further questions or concerns.
 
Thanks, 
William Gay 
Form.io Developer Support

**Comment by kokororin** [comment]
Hello William,
I have tried `builder.redraw()`, it seems like restore to the init state, but is doesn't receive new configurations.
Also tried 
```js
builder.components = myComponents;
builder.redraw()
```
It will throw `Uncaught TypeError: component.destroy is not a function` after call `builder.redraw()`.

Any suggestions, Thanks.

**Comment by kokororin** [comment]
I have found method `builder.setForm()` which is same as my expected, is it the correct way to match my needs ?

Regards

**Comment by travist** [comment]
Hey @kokororin , if ```builder.setForm()``` is working for you, then I can confirm that this is the correct way to do it and it should be good. Let us know if it is still a problem and we will elevate the ticket in our internal system.

**Comment by marcus-at-localhost** [comment]
In case someone desperately searches for code samples how to update the form builder at runtime (after saving data somewhere and return ids and store them in `components.*.properties.id` or whatever)
I put a demo together on how to use `builder.setForm()` to set a schema programmatically.

```js
const myComponents = [
  {
    label: 'Text Field',
    allowMultipleMasks: false,
    showWordCount: false,
    showCharCount: false,
    tableView: true,
    type: 'textfield',
    input: true,
    key: 'textField',
    widget: {
      type: ''
    }
  }
];

// initialize formio
var builder = new Formio.FormBuilder(document.getElementById('builder'), {}, {
  noDefaultSubmitButton: true,
});

builder.instance.ready.then(function() {
    
    // Set schema 
    builder.setForm({components: myComponents});
  
    builder.instance.on('saveComponent', function() {
		// save builder.instance.schema.components somewhere, or whatever...
		builder.setForm({components: changedComponents});
    });
});
```

https://codepen.io/localhorst/pen/BaaEBZz  

At this point, I have no clue why I have to use `new Formio.FormBuilder()` instead of `Formio.builder()` and a mix of `builder.instance.*` and `builder.setForm()`. I hope devs can shed some light on this or extend the docs. I hope this helps someone.
