### ISSUE TITLE
ReadOnly Mode TextArea Error (BUG)

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#777]
Hi, 
textArea causes a problem in ReadOnly Mode

Webform.js:762 TypeError: Cannot set property 'innerHTML' of undefined
    at TextAreaComponent.setValue (TextArea.js:254)
    at PanelComponent.setNestedValue (NestedComponent.js:674)
    at NestedComponent.js:688
    at Array.reduce (<anonymous>)
    at PanelComponent.setValue (NestedComponent.js:687)
    at Webform.setNestedValue (NestedComponent.js:669)
    at NestedComponent.js:688
    at Array.reduce (<anonymous>)
    at Webform.setValue (NestedComponent.js:687)
    at Webform.setValue (Webform.js:706)

**Comment by imadbakir** [comment]
Well I will explain
I'm using formiojs 3.6.13 renderer in an angular project,
and then I'm  initiating the form:

```
return Formio.createForm(this.formioElement ? this.formioElement.nativeElement : null, this.form, assign({}, {
            icons: get(this.config, 'icons', 'fontawesome'),
            noAlerts: get(this.options, 'noAlerts', true),
            readOnly: this.readOnly,
            viewAsHtml: this.viewOnly,
            i18n: get(this.options, 'i18n', null),
            fileService: get(this.options, 'fileService', null),
            hooks: this.hooks
        }, this.renderOptions || {})).then((formio) => { ... });
```

Whenever readOnly is true and the form has a textArea in it (which form is irrelevant it happens in any form that has a TextArea eg: https://poigzzrvpuvpgcy.form.io/formcarrequeststart )
the problem arises, 
additionally I noticed that commenting out the line  TextArea.js:254 solves the problem, But I'm not sure of the real cause of that, and since I'm not I decided to open an issue here.

**Comment by jhen1422** [comment]
@imadbakir 
This issue should be resolved in the latest 4x renderer. 

If the issue still persists please feel free to open a new issue.
