### ISSUE TITLE
ReadOnly - Edit / Delete buttons.

### ISSUE THREAD

**Issue by NiMusco** [formio/formio.js#778]
Hi Travis,

When building a form as "readOnly" and "viewAsHTML", some components (like lists) still display the Edit/Delete buttons. They don’t work when clicked, but showing them at all is unwanted behavior. Shouldn't those buttons be completely hidden?

On the other hand, I noticed that on the form.io server (running on port 3001) everything works fine. That makes me think there might be differences between formio.js and formio.
Could it be that the Angular version behaves differently?

Thank you.

**Comment by wag110894** [comment]
Hello, 

The difference between Formio.js and Formio is Formio.js is the render of the forms whereas formio is the server library.  In order to assist customers that are starting out with the server, we install a frontend as well that includes a angular.js version of our renderer. When you are in readOnly or viewAsHTML mode, it should not display the buttons or they should be disabled. You may be missing styling to show the buttons as disabled. Can you confirm that the disabled class on the buttons component is there?

Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out!

The buttons in the editgrid are part of the rowTemplate. You can add a conditional there to hide the buttons if the form is read only. You can do something like this:

{% if (!instance.options.readOnly) { %}
<div class="btn-group pull-right">
<button class="btn btn-default btn-sm editRow">Edit</button>
<button class="btn btn-danger btn-sm removeRow">Delete</button>
</div>
{% } %}


Please let me know if you have any further questions or concerns.
Thanks,
William Gay
Form.io Support Team

**Comment by NiMusco** [comment]
If I'm following you, I have to edit each grid of my project to add a condition before "Edit Delete" in it template. It's kinda hacky, shouldn't this be a default behavior of "readOnly"?

Also, doing it this way only hide the buttons. Doesn't re-organize bootstrap's grid. ("col-sm-2").
So I'll need to enclose everything inside {% if (!instance.options.readOnly) { %} and duplicate it.

I'm not very happy to tell my team modelers to do this every time. There's another workaround?

Thank you!

**Comment by NiMusco** [comment]
> The row templates are customizable per field so this is not something that can be handled by our renderer out of the box.

Oh, I understand.

> [...] if you send a pull request with this change [...]

Sure! Is [EditGrid.js](https://github.com/formio/formio.js/blob/master/src/components/editgrid/EditGrid.js) the right file? What about [comp1.js](https://github.com/formio/formio.js/blob/master/src/components/editgrid/fixtures/comp1.js) and [comp2.js](https://github.com/formio/formio.js/blob/master/src/components/editgrid/fixtures/comp2.js)?

**Comment by randallknutson** [comment]
This is correct. The change would be in https://github.com/formio/formio.js/blob/master/src/components/editgrid/EditGrid.js#L45-L59

you shouldn't have to change comp1 and comp2 as they are for tests

**Comment by NiMusco** [comment]
Pull request #784
