### ISSUE TITLE
Create a new component

### ISSUE THREAD

**Issue by gjagomez** [formio/formio.js#786]
Hi,
I find it very interesting formio I would like to know if you can create new components, it would be nice to create a component to take capture photos from a web cam or camera phone.

**Comment by wag110894** [comment]
Hello,

Thanks for reaching out.  This is available in our File Upload Component. Here is a step by step video on how to do this.

https://www.screencast.com/t/xgrkgNUoM 

Please let me know if you have any further questions or concerns.

Thanks!

**Comment by gjagomez** [comment]
thanks for the answer is great, 
the library js has some cost or is open source..

**Comment by wag110894** [comment]
Hello,

The formio.js library is open source, but it ties into our platform which is a hosted and paid platform.  Some of the additional features available with our hosted platform are:

1. OAuth - OpenID Connect
2. LDAP Authentication
3. Advanced Webhooks
4. Team management
5. Collaboration on Forms
6. Audit Logging
7. Multi-tenant management
8. Email Templates (coming soon)
9. Temp tokens & Email based authentication
10. Report API (aggregated reports)
11. Staging and Deployment (SDLC)s
12. Form Submission Collections (saving submissions to different collections for indexing)
13. Form Versioning
14. Dynamic PDF workflows
15. Encrypted Fields
16. Offline Forms
17. File Uploads
18. CORS Configuration
19. SQL Connectors
20. Kickbox integration
21. Google Sheets
22. Atlassian (JIRA) integration
23. Office 365 integration
24. Hubspot integration
25. CCS templating 

Let us know if you want to connect for a technical discussion regarding the different options.

**Comment by gjagomez** [comment]
Thanks, I'm going to register your platform to evaluate

**Comment by wag110894** [comment]
Let me know if you have any questions.

Thanks!

**Comment by noman115pk** [comment]
@wag110894 Thanks for the feedback. I was also searching for this component. I found the component and made it to work on browser but on mobile i wasn't able to access the phone camera after clicking Take Photo. 
Debugging phone on Chrome Remote Tools i got this error.
`File.js:375 DOMException: Requested device not found`
and on other device it says
`ERROR TypeError: Cannot set property 'name' of null
    at eval (File.js:387)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5125)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)`
I checked on another device this time error was 
`File.js:375 DOMException: Permission Denied`

My app is built on Ionic 3 and tested this on Android Phones only.

Thanks

**Comment by randallknutson** [comment]
I believe you need to add this plugin to make it work. https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/

In ionic you may need some other functionality to add navigator.camera which does not come by default in Android.

**Comment by nimishdesai1989** [comment]
@wag110894 : I was trying to look for the step by step video you provided earlier in your comments. However, seems like the file resource has been moved or taken down. We were in the need to use forms engine for capturing image from a phone camera. I will be really helpful if you can guide me to the tutotial for this that will save us a lot of time. Thanks in advance !

**Comment by wag110894** [comment]
Hello @nimishdesai1989 sorry about that. Here is a new video on how to accomplish this: https://share.getcloudapp.com/RBu9xqOr. 

The process is the same for using your camera.

I hope that this helps.

**Comment by TriStarGod** [comment]
@wag110894 Hi, both previous links fail.
