### ISSUE TITLE
Custom Component Template

### ISSUE THREAD

**Issue by 152hq** [formio/formio.js#792]
Hi,

I am working on a custom component and have the following questions

1. Is it possible to have template config like angularjs when creating custom components in pure JS?
2. How do i bind events from defaults components, like textfield to do custom logic? (I have a "multiple" checkbox, which when selected does not work as a normal component functionality)

Any help would be really appreciated.

Thanks

**Comment by 152hq** [comment]
Thanks.

When creating is custom component, do we need any other config to enable "multiple" option to work? The code that I have, with the multiple option checked, does not show the "add item" button for a custom component.

**Comment by jhen1422** [comment]
Hello,

This is Jeriah from the Form.io support team.

The multiple setting should work without adding any other configs as long as you do not override any of the methods that are used to build the component. We will need to get on a debugging session with you looking at your code to determine what is wrong. Please let us know if you are interested in our support package pricing. Thank you!
