### ISSUE TITLE
How to retry the failed request again when we get 401

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#793]
Hi,

After getting 401 -> we are opening login form( or getting refresh token ) of ours and after successful login we are resetting the token with the new. But how do we retry the failed request like we do in angular (replay HttpRequest and HttpHandler).

Thanks.

**Comment by sriram275** [comment]
is it possible with in formio.js? Any suggestions will be great.

Thanks

**Comment by randallknutson** [comment]
What you can do is capture the submission object on the onSubmit event (which occurs before submit) and listen for the 401 failure. Then, if it fails, present the login form and on success send the submission again.

**Comment by sriram275** [comment]
It is not only about for submit but also to components (select with data as url). Even if it is for submit as you said we can retry the request but is it possible send back the response to who ever is fired this request?

Means for submit if we use custom action, in that I have written small script which sends ( with using fomio makeRequest method ) submission object to server and in success response I am notifying success notification and error case failure notification.

So I am trying to handle 401 is like below:
In **formio.js** static **request** method
 else if (response.status === 401) {
            //Formio.events.emit('formio.unauthorized', request);
            handle401(url, method, data, header, opts);
          } 

Able to open login form and after login retrying the failed request but unable to resolve the promise to who ever requested this call(which is failed in this case).

In angular it is possible with putting all failed promises into queue with help of $q and retry after login success.

Is it possible to retry the promise not only simple request in formio.js?

Thanks.

**Comment by travist** [comment]
For the Select component, it does appear that it triggers an event ```componentError``` when the request fails, which would also be the case for a 401.

https://github.com/formio/formio.js/blob/master/src/components/select/Select.js#L327

You could hook into this event, and then retry this request after logging in... something like this.

```js
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example').then(function(form) {
  form.on('componentError', function(err) {
    if (err.component.key === 'myselect' && err.message === 'Unauthorized') {
      const select = form.getComponent('myselect');
      select.updateItems();
    }
  });
});
```
