### ISSUE TITLE
Custom component table PrimeNG with formio

### ISSUE THREAD

**Issue by iamsandeepgupta** [formio/formio.js#794]
Hello,

I want to add PrimeNG in formio library to get the actual functionality of the HTML element. I have tried with check matrix example which works for me, but this is creating hurdle. Please tell me the suitable solution for the same.

**Comment by iamsandeepgupta** [comment]
@wag110894 i am looking to bind primeNG table.

**Comment by iamsandeepgupta** [comment]
any updates

**Comment by travist** [comment]
This would need to be a community development or a "sponsored" addition to the renderer.
