### ISSUE TITLE
Need Help - Custom Component

### ISSUE THREAD

**Issue by 152hq** [formio/formio.js#796]
Hi,

We are trying to build custom components that will meet our app needs. We could not find a way to call the build method (CheckMatrixComponent.prototype.build) explicitly as each time the call occurs, the DOM remains the same. Can you please help provide a better solution where build can be called on custom triggers.

Thanks

**Comment by jhen1422** [comment]
Hello,
 
Jeriah here from the support team.

The build method can be explicitly called by first targeting that component and then calling it like this.
 
var checkMatrix = instance.getComponent('checkmatrix');
checkMatrix.build();
 
Hope this helped you.
 
Thanks!
