### ISSUE TITLE
Register new component

### ISSUE THREAD

**Issue by hamidsharifi** [formio/formio.js#81]
Hi dears
How can I register new component. please help me for registering new component.
thanks

**Comment by gavieritei** [comment]
I'm having the same problem basically, but in ng2-formio.
I've tracked this to Components.js addComponents method [here](https://github.com/formio/formio.js/blob/master/src/components/Components.js#L106).

This means your component should somehow be added to index.js [here](https://github.com/formio/formio.js/blob/master/src/components/index.js).

I don't know way to add it dynamically. If you already found a way please let me know.
