### ISSUE TITLE
Multi-level Nested forms resource / submission assignment unpredictable  behavior

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#811]
Hello, 
I'm using formiojs renderer to render a multilevel nested forms, which consists of a form in a form in another form, I'm rendering the latter (eg: https://mgrfbliksxepjzm.form.io/formreqmngrreview) 
I'm then assigning submission data to the form, accordingly ( I have a custom formula to generate the data object), the most inner form (2nd level) is behaving strangely for example:

1- it doesn't view the data if the data was assigned before the form is fully loaded. 
2- it displays the data only partially if the data is assigned after the form is fully loaded. 
3- it displays the data Correctly only when the submission is set (by chance) at the time when the form is loading or has just loaded.

I'm trying to understand this strange behavior but  I couldn't. problems start to happen on 2nd level nested forms, I thought maybe multilevel nested forms are not stable for some reason? 

any help is appreciated

**Comment by randallknutson** [comment]
We have had another report of multi-level nested forms having issues last week and have assigned a dev to review and fix the issues. We hope to have this resolved next week.

**Comment by jhen1422** [comment]
Issues should be resolved on the latest 4x renderer
