### ISSUE TITLE
html content - iframe passing auth bearer

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#813]
Hi,

I am trying to add an iframe to one our our forms which loads a page from an internal site. Any ideas how i can pass the authentication token on to the page we are calling?
I was consdering something like this but not sure this will work.

var xhr = new XMLHttpRequest();

xhr.open('GET', 'page.html');
xhr.onreadystatechange = handler;
xhr.responseType = 'blob';
xhr.setRequestHeader('Authorization', 'Bearer ' + token);
xhr.send();

function handler() {
  if (this.readyState === this.DONE) {
    if (this.status === 200) {
      // this.response is a Blob, because we set responseType above
      var data_url = URL.createObjectURL(this.response);
      document.querySelector('#output-frame-id').src = data_url;
    } else {
      console.error('no pdf :(');
    }
  }
}

Thanks

Mark

**Comment by travist** [comment]
You need to send the token via ```postMessage()``` into the iframe. There are several libraries that do this including https://github.com/travist/seamless.js which is the library that we use. This would allow the parent page to send its auth token into the iframe to be received by the child.
