### ISSUE TITLE
HTML view - Resources as objects

### ISSUE THREAD

**Issue by NiMusco** [formio/formio.js#814]
Hi,

With **readOnly** and **viewAsHtml** as true, resources are showed as a plain JSON object instead of showing it value like angular does, since everything looks fine on formio Server.

Note that **Allow Multiple Resources** is enabled.

---

Server:
![screenshot from 2018-11-23 12-29-49](https://user-images.githubusercontent.com/12497746/48951011-d286b880-ef1b-11e8-8685-c7c968bf59e4.png)

SDK:
![screenshot from 2018-11-23 12-30-17](https://user-images.githubusercontent.com/12497746/48951012-d286b880-ef1b-11e8-95a7-f0468b6da970.png)

Thanks.

**Comment by randallknutson** [comment]
Thanks for the report. We'll add this to our bug list. If you want to fix it in the meantime, feel free to attach a pull request.

**Comment by travist** [comment]
This is because it is not using the component template to render this html.

**Comment by NiMusco** [comment]
Sorry, I don't get what you mean. Is that a bug?

**Comment by travist** [comment]
Yes it is a bug. We will add it to our backlog unless someone from the community tackles it.

**Comment by Ggleny** [comment]
Hi
I solved that.  is a bug when used component resource (multiple).
I am preparing the pull request but I left my fix.

In file formiojs/components/select/Select.js i change method **itemTemplate**

![screenshot from 2018-12-11 12-16-04](https://user-images.githubusercontent.com/5025463/49809923-e5ccbd00-fd3e-11e8-85ca-6a109d80f4c8.png)

dont forget apply in formio.full.min.js or formio.full.js 
Example Form with Fix

![screenshot from 2018-12-11 12-10-05](https://user-images.githubusercontent.com/5025463/49810037-1b71a600-fd3f-11e8-9a77-4fbf7f9d6bfe.png)


Sorry my  english is bad :+1: 
I hope it will help you
