### ISSUE TITLE
Minimalist configuration modal 

### ISSUE THREAD

**Issue by noman115pk** [formio/formio.js#816]
Hello Support Team,
I appreciate the effort behind this product. This product is awesome and a great contribution to open source community. 
Is there any way to reduce the configuration panel to a minimalist size or configure the modal to be basic or advanced?
[Sample picture of configuration Modal](https://help.form.io/userguide/form-components/#textfield).
Let's say if i want to reduce the tabs to Display and Validations only.
What if i want to reduce the number of fields from Display tab .i.e. to hide the prefix, suffix or input mask fields?

**Comment by travist** [comment]
Take a look at what the Custom component does.

https://github.com/formio/formio.js/blob/master/src/components/unknown/editForm/Unknown.edit.display.js

This shows how you can make modifications to the editForm to disable certain components within the edit form. This form is actually just a Form.io JSON form so it can easily be overridden and extended.

Hope this helps.

Travis.
