### ISSUE TITLE
Triggers on Survey Data || Radio || checkboxes

### ISSUE THREAD

**Issue by noman115pk** [formio/formio.js#817]
Hello Support Team,
I appreciate the effort behind this product. This product is awesome and a great contribution to open source community. 

Can you please provide me guidance if i can configure any triggers/callbacks on Radio Buttons, Checkboxes or Surveys? e.g I created a student medical form and added a question like Are you allergic to Epipen? If student submits yes to an answer in form submission. I want to trigger an alert / function from server side on the basis of user answers.

Thanks,
Nauman Rafique

**Comment by travist** [comment]
Yes this can be done. Basically, you can do it like this demonstration shows.

http://formio.github.io/formio.js/app/examples/externalload.html

What you want to do is similar to what this shows.
