### ISSUE TITLE
[Select] Choices JS - Brower freezing with a large dataset of values

### ISSUE THREAD

**Issue by Aiso786** [formio/formio.js#82]
Hello guys, We have an issue with a Select (i've seen that Formio is using Choices JS) receiving a large amount of values (700 rows). It takes some time for the Select to render and meanwhile the browser is freezing.

Do you have an idea ? I have tried to look into the code. Disabling the sort in the configuration helps a little bit but the browser is still freezing.

Thank you very much for your help.

**Comment by travist** [comment]
I am able to reproduce this, but it is an issue with the choices.js library. What I may do is have an option to not use Choices.js but rather just use a default select dropdown list to see if that fixes this problem.

**Comment by Aiso786** [comment]
Hello, yes with another select it is working fine (see React-formio which is using react-widgets).

**Comment by Aiso786** [comment]
Fixes since the v2.24.6, so i close this issue.

**Comment by abarrak** [comment]
@travist this is still exists and reported to ChoicesJS owners [1](https://github.com/jshjohnson/Choices/issues/522), [2](https://github.com/jshjohnson/Choices/issues/152), [3](https://github.com/jshjohnson/Choices/issues/830), [4](https://github.com/jshjohnson/Choices/issues/829).

Is there any workaround to avoid such freezing? Thanks.
