### ISSUE TITLE
Include "field" property in custom error message

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio.js#820]
Form.io component validator does not include the `field` property when getting the validation result.

https://github.com/formio/formio.js/blob/84109049e89044f1fade0185d889887973983247/src/components/Validator.js#L63-L71

As such, you cannot use the component's label (or error label) in its help block.

The following must be included:

```js
result = component.t(customErrorMessage || result, {
    field: component.errorLabel,
    data: component.data 
});
```

I have created the following pull request to address this issue: https://github.com/formio/formio.js/pull/819

**Comment by travist** [comment]
Looks good. We will pull this into our latest renderer release probably later this week.
