### ISSUE TITLE
eachComponent only get current tab components

### ISSUE THREAD

**Issue by kokororin** [formio/formio.js#821]
See pen: https://codepen.io/anon/pen/wQENwJ

Press the button, it only logs current active tab's components, not all the components, but the `builder.components` really contains all components in two tabs.

When switch to Tab 1, it logs `Text Field 1`, when switch to Tab 2, it logs `Text Field 2`, not all components.

**Comment by airarrazaval** [comment]
eachComponent ([see wiki](https://github.com/formio/formio.js/wiki/Form-Utilities#eachcomponentcomponents-fn-includeall-path) and [sdk documentation](https://formio.github.io/formio.js/docs/function/index.html#static-function-eachComponent)) has a third parameter which indicates to include layout (or non input) components when true.

Changing your code to the following will log all components.

```js
FormioUtils.eachComponent(builder.components, component => {
      console.log(component);
 }, true);
```

**Comment by kokororin** [comment]
Hello 
  I know this option, but i want to get all the components in tab 1 and tab 2, not only in tab 1.
Thanks

**Comment by kokororin** [comment]
Thanks, `build.schema.components` works.
