### ISSUE TITLE
Disable Logic not working on checkboxes

### ISSUE THREAD

**Issue by rishabh47** [formio/formio.js#822]
I added a logic on checkbox for it to get disabled and enabled based on another checkbox. It was working fine earlier. After your update the logic is not working.

**Comment by rishabh47** [comment]
It was working earlier but when I upgraded the library to version 3.6 the disable logic stopped working on check boxes. I can't provide the code.

**Comment by randallknutson** [comment]
Can you provide a demo form where this is not working?

**Comment by AnasHijazi** [comment]
@travist  @randallknutson  hello i face the same issue please see the below videos : 
https://drive.google.com/file/d/16Zy9ZyhuuGTcmoM2_33rPPxnx3c7mtbb/view?usp=sharing

https://drive.google.com/file/d/1zSg4uHl3zqMASgMjlIFmnWPeFc6Ucz5v/view?usp=sharing

**Comment by randallknutson** [comment]
Thanks for the info. We'll take a look.

**Comment by rishabh47** [comment]
@travist @randallknutson Hey, is this done yet?

**Comment by rishabh47** [comment]
@travist @randallknutson Any follow up here?

**Comment by wag110894** [comment]
This issue is currently on one of our developer's list. We will let you know once this issue is resolved. 

Thanks!

**Comment by krixerx** [comment]
For me it looks field logic is not working anymore at all, it just hides the component when field logic is attached. I remember too, it worked in summer time :-)

**Comment by ranjanasisodia** [comment]
I am facing the same issue. Any update or workaround for the same? 
 @travist @randallknutson @wag110894

**Comment by travist** [comment]
Here is an example of field logic working. 

http://formio.github.io/formio.js/app/examples/fieldLogic.html

It must have something to do with your specific logic configurations. Can you provide the specific configurations that you have?

**Comment by ranjanasisodia** [comment]
@travist Could you please give another configuration where  -> we have 2 checkbox, named one and two.
when I un-check checkbox one, checkbox two is disabled.

**Comment by ranjanasisodia** [comment]
@travist 

{
  "_id": "5c4ad3f8eabd074156db9874",
  "type": "form",
  "tags": [],
  "owner": "5c4aca396faee6838fc867a2",
  "components": [
    {
      "autofocus": false,
      "input": true,
      "inputType": "checkbox",
      "tableView": true,
      "label": "one",
      "dataGridLabel": false,
      "key": "one",
      "defaultValue": false,
      "protected": false,
      "persistent": true,
      "hidden": false,
      "name": "",
      "value": "",
      "clearOnHide": true,
      "validate": {
        "required": false
      },
      "type": "checkbox",
      "labelPosition": "right",
      "hideLabel": false,
      "tags": [],
      "conditional": {
        "show": "",
        "when": null,
        "eq": ""
      },
      "properties": {}
    },
    {
      "autofocus": false,
      "input": true,
      "inputType": "checkbox",
      "tableView": true,
      "label": "two",
      "dataGridLabel": false,
      "key": "two",
      "defaultValue": false,
      "protected": false,
      "persistent": true,
      "hidden": false,
      "name": "",
      "value": "",
      "clearOnHide": true,
      "validate": {
        "required": false
      },
      "type": "checkbox",
      "labelPosition": "right",
      "hideLabel": false,
      "tags": [],
      "conditional": {
        "show": "true",
        "when": "one",
        "eq": "true"
      },
      "properties": {}
    }
  ],
  "revisions": "",
  "_vid": 0,
  "title": "checkbox test",
  "display": "form",
  "access": [
    {
      "roles": [
        "5c4aca4aa3e8afa2afe0e4e2",
        "5c4aca4aa3e8af0e06e0e4e3",
        "5c4aca4aa3e8aff7ace0e4e4"
      ],
      "type": "read_all"
    }
  ],
  "submissionAccess": [],
  "settings": {},
  "name": "checkboxTest",
  "path": "checkboxtest",
  "project": "5c4aca4aa3e8af7b8ee0e4e1",
  "created": "2019-01-25T09:16:40.292Z",
  "modified": "2019-01-25T09:23:41.312Z",
  "machineName": "wnscbooqzizxjtm:checkboxTest"
}

In the above code I have created 2 checkboxes named one and two. As per the logic, two should show true when one is true. But when logic is added to checkbox two, it gets hidden.

Have a look at this link for the demo.

https://formview.io/#/wnscbooqzizxjtm/checkboxtest?header=1

**Comment by travist** [comment]
The logic will not work in the FormView application since that is an Angular 1.x renderer. Try it here...

https://formio.github.io/formio-viewer/dist/#/wnscbooqzizxjtm/checkboxtest

That is your form rendered using our core renderer.

**Comment by ranjanasisodia** [comment]
I tried another config at here: http://formio.github.io/formio.js/app/builder
It should enable checkbox two when checkbox one has value true. But it just renders checkbox one. See the screenshot and JSON below:

![output](https://user-images.githubusercontent.com/12969458/51834021-db7c7780-231a-11e9-99e2-90504a40d310.png)


JSON:

{
    "display": "form",
    "components": [
        {
            "label": "one",
            "shortcut": "",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "checkbox",
            "input": true,
            "key": "one"
        },
        {
            "label": "two",
            "shortcut": "",
            "mask": false,
            "disabled": true,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "checkbox",
            "input": true,
            "key": "two",
            "logic": [
                {
                    "name": "enableLogic",
                    "trigger": {
                        "type": "simple",
                        "simple": {
                            "show": true,
                            "when": "one",
                            "eq": "true"
                        }
                    },
                    "actions": [
                        {
                            "name": "enableAction",
                            "type": "property",
                            "property": {
                                "label": "Disabled",
                                "value": "disabled",
                                "type": "boolean"
                            },
                            "state": "false"
                        }
                    ]
                }
            ],
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "customConditional": ""
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}

**Comment by ranjanasisodia** [comment]
@travist @randallknutson Any update?

**Comment by rishabh47** [comment]
@travist @randallknutson Is there any update on this?

**Comment by wag110894** [comment]
This item is currently on one of our developers list. As Travis mentioned earlier, we do have an option to expedite this issue. Please contact support@form.io.


Thanks.

**Comment by franke-mc** [comment]
Maybe this issue has been fixed already? Based on the JSON in https://github.com/formio/formio.js/issues/822#issuecomment-458096815, I have created https://jsfiddle.net/franke_mc/963nf54y/7/ , which looks ok to me. Am I missing something?

**Comment by jhen1422** [comment]
This seems to be resolved in 4.8.0-beta.1
