### ISSUE TITLE
Recursion in change event

### ISSUE THREAD

**Issue by pkochubey** [formio/formio.js#823]
Hi, 
You can use this simple example http://jsfiddle.net/v38du9y1/1000/
If you open console log, you can see a lot of event "Form was changed" after entire any value in Text filed (see picture https://yadi.sk/i/V8e5sqdVm1zuUA).

I catch the same issue in my forms and this recursion call stack:
```
...
setTimeout (async)
setTimeout (lodash.js:6648)
leadingEdge (lodash.js:10343)
debounced (lodash.js:10412)
BaseComponent._this.triggerChange (Base.js:425)
checkData (NestedComponent.js:463)
checkData (Webform.js:1024)
onChange (Webform.js:1007)
(anonymous) (Base.js:411)
invokeFunc (lodash.js:10335)
trailingEdge (lodash.js:10384)
timerExpired (lodash.js:10372)
 ...
```

**Comment by pkochubey** [comment]
@travist Thanks, http://jsfiddle.net/v38du9y1/1000/ this is good lightweight example. Enter any value in text field (in example two component select box and text box) and you will catch this issue.

**Comment by travist** [comment]
This should be fixed with latest version.
