### ISSUE TITLE
Cannot Drag custom components

### ISSUE THREAD

**Issue by 152hq** [formio/formio.js#827]
Hi, 

We are trying to create custom components and find the components created cannot be dragged.

**Steps to re-create**
1. http://formio.github.io/formio.js/app/examples/customcomponent.html
2. Try creating 2 check box components
3. Try dragging one on top of other
4. Builder will show the change, but render component does not show the change
5. In the image below, the render and builder component shows different component order

![image](https://user-images.githubusercontent.com/31052571/49202552-10428000-f3f9-11e8-9fb8-1b8ac7a49c41.png)

**What is happening**
in WebFromBuilder.js ln: 938 `if (element.component)` returns as null for a custom component upon drag after initial setup.

Please help.
Thanks

**Comment by travist** [comment]
This is working for me... Please provide a jsfiddle of the problem.

**Comment by 152hq** [comment]
Hi,

Please find the fiddle below

http://jsfiddle.net/152hq/rj8403d9/3/

**Steps**
1. First create a 2x2 matrix checkbox
2. Then create a 1x1 matrix chechbox
3. trying moving 1x1 matrix to the top
4. The builder component will show the dragged object, while the Rendered Form will not. (check the console and you will see a warning "No element.id defined for dropping")

![image](https://user-images.githubusercontent.com/31052571/49255840-4a576480-f481-11e8-901a-1b13908e6a98.png)

**Comment by randallknutson** [comment]
Looks like there is a missing event when dragging the custom component. If you edit one of the components it updates and fixes.

**Comment by 152hq** [comment]
yes, but if a form has custom components, it really affects the layout . Is there a fix for this? We have worked out a solution by appending the below code as last line in the build function to fix this. Please let us know if there be a better solution

`this.element.component = this; `

Thanks

**Comment by travist** [comment]
Can you create a pull request with this fix in place so that it works for everyone else?

**Comment by travist** [comment]
No, don't include the checkmatrix component in your pull request.

**Comment by 152hq** [comment]
but, this is something which needs to be addressed while creating a custom component, how do I go with that then?

**Comment by travist** [comment]
I think that this change should be included in the core library so that any other custom component created would have this set and then not be required to set it within the custom component itself. Is there not a way to provide the code you did above to the point after the component is created?

**Comment by 152hq** [comment]
yep, working on your point. Will update with possible solution asap.

**Comment by amir135** [comment]
You must set an Id for first tag in custom component.
like this

`CheckMatrixComponent.prototype.build = function () {
    this.element = this.ce('div', {
        class: 'table-responsive'
    });
// for all CheckMatrixComponents need unique id like "testid"
    this.element.setAttribute('id', 'testid');
//some code
    this.element.component = this;
};
`

**Comment by mujtaba1016** [comment]
Hello! Anyone know why https://formio.github.io/formio.js/app/builder PDF builder does not work?
Drag and dropping fields not working
this is only happening for Chrome on MAC.

**Comment by wag110894** [comment]
@mujtaba1016,

We will take a look and see why this is happening. We created a ticket and have added it to our backlog. We welcome a PR or have a process to expedite this issue. For reference, the ticket number is PDF-159.

We will let you know once this issue has been resolved.
