### ISSUE TITLE
Formio JS API LoadActions returns Invalid alias

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#832]
Hello, 

I tried to load actions of a particular form using the method formio.loadActions({}) which is failing with invalid alias after calling this link https://dppidyxnitjgglo.form.io/requestorinformation/action?type=email

**Comment by randallknutson** [comment]
You may need to use the formId to load actions. For example, 

https://dppidyxnitjgglo.form.io/form/:formId/action?type=email

See the api docs at https://apidocs.form.io/#402b3260-e57e-4565-bd21-8a6f6b2394ce
