### ISSUE TITLE
unknown component error in latest version of angular-formio(3.9.0)

### ISSUE THREAD

**Issue by shivlila01** [formio/formio.js#833]
In the older version of angular-formio(1.18.0) we registered the custom components using Formio.registerComponent() method and it was working perfectly.

Recently we have upgraded our application with latest version of angular-formio (3.9.0) and formiojs version as 2.32.3 after this up-gradation our custom components are not working it is showing error message as "unknown component : mycustomcomponent". Please help.

**Comment by randallknutson** [comment]
The API for adding a custom component has changed since this was a major version change. You can see an example of how to do this with the new version at http://formio.github.io/formio.js/app/examples/customcomponent.html

**Comment by randallknutson** [comment]
Duplicate here: https://github.com/formio/angular-formio/issues/235
