### ISSUE TITLE
Script does not run in Salesforce Locker service

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#837]
Hello Support,

We want to use your components in the Salesforce platform but Salesforce has introduced a more strict script protocol they call the Locker service. This means your script is not allowed.
What it is all about you can read here: https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm

Can you advise how to fix this?

Kind regards,
Mario

**Comment by randallknutson** [comment]
Do you have any error messages or information about what it is in our codebase that is causing issues?

**Comment by KyooMario** [comment]
Hello Randall,

I have not seen any error message. Let me check if I can generate one.
Thanks for the quick response.

Kind regards,
Mario

**Comment by KyooMario** [comment]
Hello Randall,

Sorry. No error message. Does the link tell you something to look into?

Kind regards,
Mario

**Comment by travist** [comment]
@KyooMario we would need to try this ourselves to dig deeper into why it isn't working. If they are not providing you any errors, then this would need to be a support initiative on our part. Let us know if you would like to purchase a support package to have our support team dig into this personally.

**Comment by KyooMario** [comment]
Hello Travist,

"purchase a support package" I might do that but what is the price?

Kind regards,
Mario

**Comment by wag110894** [comment]
@KyooMario 
Here is our pricing doc with information regarding pricing for support packages.

[Form.io Platform Subscription and Services Pricing Summary 2018.pdf](https://github.com/formio/formio.js/files/2653942/Form.io.Platform.Subscription.and.Services.Pricing.Summary.2018.pdf)

Let us know which package is best suited for you.

Thanks.

**Comment by randallknutson** [comment]
If you aren't using the Ace editor on your forms you can skip the include. We may be including it by default though in which case you can create a custom build without it by forking the formio.js library and doing a custom build.

**Comment by KyooMario** [comment]
Hello Randall,

Thanks.

Kind regards,
Mario
