### ISSUE TITLE
Form component with autocomplete or typeahead

### ISSUE THREAD

**Issue by gerzenstl** [formio/formio.js#838]
Hi,

I'm trying to add a form field with autocomplete/typeahead, to suggest users possible values they can input. What I'm looking is something similar to this: https://angular-ui.github.io/bootstrap/#!#typeahead)

Is there any component I can use to replicate this functionality? Would I need to build it as a  custom component? 

Thanks!

**Comment by randallknutson** [comment]
Would this be a select component? If not, this would be a custom component or you could extend the existing textfield component to add support for typeahead. We can either facilitate this as a support request or would accept a pull request to add this functionality.

**Comment by gerzenstl** [comment]
It wouldn't be a select since the user would be able to add a value not present on the suggestions.
Is there any example of extending the existing textfield? I could try to provide PR if I'm able to build a custom component. Thanks!

**Comment by randallknutson** [comment]
Here is the form you would add the autocomplete settings to:
https://github.com/formio/formio.js/blob/master/src/components/textfield/editForm/TextField.edit.display.js
And then you would modify the build method to change the html for the textfield here:
https://github.com/formio/formio.js/blob/master/src/components/textfield/TextField.js#L65
