### ISSUE TITLE
Date / Time component data tab in edit  is not clickable in builder 

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#840]
Hi,
When clicking Data tab in edit of Date / Time Component is throwing following error:

Uncaught TypeError: Cannot read property 'toString' of null
    at t.value (formio.full.min.js:99)
    at t.get (formio.full.min.js:9)
    at t.value (formio.full.min.js:9)

**Comment by wag110894** [comment]
Hello, 

Thank you for your patience. We have fixed this issue with the 3.12.0 Version of our Core builder.

Regards,
William Gay 
Form.io Developer Support
