### ISSUE TITLE
nestedForm Doesn't respond to language Changes

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#845]
Hi, 
NestedForm doesn't seem to respond to language changes of parent form.

`formio.addLanguage(lang, translation);
 formio.language = lang;`

**Comment by randallknutson** [comment]
Sounds like the setLanguage may not be going down to the nested form. We may need to open a ticket to get this fixed.

**Comment by imadbakir** [comment]
@randallknutson I tried looping over formComponents and set language for all subForms as they load, but that didn't work either.

**Comment by imadbakir** [comment]
@randallknutson Well after few tries and errors I could make it work by looping  over all components, and check for forms, and assigning language to them too when subFormReady Fires, recursively (to find any deep level forms), which is an expensive operation. 
it will be great if we can look into this subject, where should we open that ticket?

**Comment by iobuhov** [comment]
#902
