### ISSUE TITLE
Formio beforeSubmit Uncaught (in promise)

### ISSUE THREAD

**Issue by john-eacomm** [formio/formio.js#862]
Hi Formio Team,

The custom errors does not appear or submission does not continue if I click the submit for the first time, but its ok when I try to click it again for the second time.

![formio-beforesubmit1](https://user-images.githubusercontent.com/8254298/49992292-9268a200-ffbe-11e8-9938-e99ae8cc7275.png)

Here's my code.

![formio-beforesubmit2](https://user-images.githubusercontent.com/8254298/49992306-9b597380-ffbe-11e8-95bf-bc23b7445058.png)

Regards,
John

**Comment by randallknutson** [comment]
Hi John,

I'm not sure what is going on here but you may have better luck with the customValidation hook. Here is an example of how to implement it:

http://jsfiddle.net/randallknutson/eLp1hrm2/

It is similar to the beforeSubmit hook but fires after the normal validations and handles the errors better.
