### ISSUE TITLE
[Bug] EditGrid headers dont localize.

### ISSUE THREAD

**Issue by multinerd** [formio/formio.js#865]
[Fiddle](http://jsfiddle.net/h75swpo8/4/)

In the fiddle, i have some components for a customer and similar components for witnesses such as `Name`, `Address`, `City`, etc...

If you change `languageToRenderIn` to `es`, you can see everything except the table headers being translated to spanish.

[In the off chance you get different results, heres what i see](https://files.catbox.moe/xjyl3k.png)

**Comment by travist** [comment]
Yep, this is a bug. Probably because we are not running the EditGrid header labels through the ```this.t()``` method.

**Comment by multinerd** [comment]
@travist @jhen1422 Was this issue closed because it was fixed or due to inactivity because I am not seeing the changes in the changelog.

**Comment by jhen1422** [comment]
This was closed to inactivity.

If this issue still persists in our 4x branch, please feel free to open a new ticket
