### ISSUE TITLE
File upload Error - Failed to execute 'replaceChild' on 'Node'

### ISSUE THREAD

**Issue by Mochaka** [formio/formio.js#875]
I'm getting an error using the fileuploader component. I've just tried different options and endpoints. This error i got was using base64.

Got any suggestions on how to debug this?

Thanks

Uncaught (in promise) DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
at http://localhost:8080/5.js:29415:40
(anonymous) @ File.js:831
Promise.catch (async)
(anonymous) @ File.js:824
upload @ File.js:755
onChange @ File.js:252

**Comment by travist** [comment]
What type of file upload are you using? S3, Base64, etc?

**Comment by Mochaka** [comment]
I've tried URL and Base64, i did set it to S3 but wasn't sure how to set the S3 options.

All 3 failed with the same error.

**Comment by Mochaka** [comment]
I'm not using the server component at all, doing my own implementation. 

I don't see any XHR requests when doing base64 though, so does it relate to the server?

**Comment by randallknutson** [comment]
We have lots of people using the file component with base64 who aren't getting that issue. Is there anything in particular that might be causing the issue? Here is an example of base64 upload working correctly: http://jsfiddle.net/randallknutson/1ok9yfpa/

**Comment by Mochaka** [comment]
I solved the issue. 

I'm using this in VueJS, and i was presetting the data variable to have all the fields as empty strings. 

So since the field already existed, the file upload was try to just push into that data field which was a string. Hence the error.

Not sure if maybe we should add a check to make sure the data field is an array before we push to it incase there's anyone else stupid enough like me out there! @travist

**Comment by travist** [comment]
@Mochaka do you have an idea on what you would change in our renderer to mitigate this problem? If so, then pull requests are welcome. The code for base64 file uploads is here...

https://github.com/formio/formio.js/blob/master/src/providers/storage/base64.js
