### ISSUE TITLE
Form submit button Issue

### ISSUE THREAD

**Issue by anveshsdd** [formio/formio.js#876]
When i clicked on Submit button, it shows submission complete bar before submit process start. I am also want to apply some condition before submit button to save, condition stops the submission of data but submission message and loading on submit button appears..

I do not want to show submission message and loader on submit button

Please help me to handle this...

**Comment by multinerd** [comment]
To apply some conditions before submitting, you can use the hook `beforeSubmit`


```
            Formio.createForm(myFormElement, myFormUrl, {
                hooks: {
                    beforeSubmit: (submission, next) => {
                        // apply your conditions
                        // call next when your ready to submit
                    }
                }
            }).then(function (form) {
                .....
            });
```

**Comment by anveshsdd** [comment]
I do not want to show submission complete bar and loader on submit button. how can i do this?

**Comment by multinerd** [comment]
You would have to modify the button using JS or jQuery, or you can hide the forms submit button and implement your own.
