### ISSUE TITLE
Multiple Query Strings set in url

### ISSUE THREAD

**Issue by tjgibbs92** [formio/formio.js#88]
I noticed a bug in formio.form.js for loading submission items. Right around Line 5535, the url variable is setting multiple query strings.

![image](https://cloud.githubusercontent.com/assets/12971717/26059155/5298a3a4-3946-11e7-831d-38bd08eb296c.png)
This is the result of a select box change.

![image](https://cloud.githubusercontent.com/assets/12971717/26059095/18f9f986-3946-11e7-9caf-6ce454ab9bb9.png)
This was a workaround fix I used while doing some testing. The comment out line worked.

**Comment by travist** [comment]
This should be fixed with the latest release.
