### ISSUE TITLE
New Tree component not available in builder 3.10

### ISSUE THREAD

**Issue by shauntrennery** [formio/formio.js#881]
The new Tree component (3.10) is not listed in the Builder's Data controls tab.

**Comment by travist** [comment]
We are working through a bug in the builder mode for this component. Until then, it will be a "hidden" feature.

**Comment by shauntrennery** [comment]
@travist any update on this?

**Comment by shauntrennery** [comment]
cc @YuryRybakSoftensity

**Comment by shauntrennery** [comment]
cc @YuryRybak

**Comment by jhen1422** [comment]
This component is now available using our 4x builder / renderer
