### ISSUE TITLE
"Advanced Next Page" field is missing

### ISSUE THREAD

**Issue by ivanljutyj** [formio/formio.js#883]
In the angular version of the form builder, we have the ability to add logic to determine next page from the form builder. The vanilla JS renderer still supports this behavior. Not sure if removing that option from the form builder was intentional. 
![image](https://user-images.githubusercontent.com/26074267/50301038-32f21280-0454-11e9-83d9-c23dce06a6c7.png)

**Comment by travist** [comment]
It's not intentional. We need to add this to the core builder.

**Comment by wag110894** [comment]
This has been added to the 4x Core Builder.

**Comment by MihlaliMgwebi** [comment]
I encountered issues with the previous implementation. 

After collaborating closely with @joe-masango and @[nkosie29@gmail.com](mailto:nkosie29@gmail.com), we arrived at the following solution:
<img width="189" alt="Screenshot 2024-11-04 at 09 42 32" src="https://github.com/user-attachments/assets/63db65f4-3426-49d4-93a9-10525642a215">
<img width="495" alt="Screenshot 2024-11-04 at 09 38 00" src="https://github.com/user-attachments/assets/b6270abf-df4c-4979-b3cf-c9e0d82f41a4">

This method allows navigation to any specified page within the form. Please note that the page indexing is zero-based, meaning the first page is referenced as 0.

Additionally, it appears that this functionality may have been removed from the core builder in recent updates. If anyone has insights or further information regarding this change, please share. Feel free to modify any specific terms or details to better fit your context!
