### ISSUE TITLE
(Select Component) "Data source url" & "Filter Query" values encoded on submit,  but not decoded when using

### ISSUE THREAD

**Issue by kran** [formio/formio.js#885]
for example: `node?a=1&b=2` will be encoded to `node?a=1&amp;b=2`, parameter `b` lost.

**Comment by jhen1422** [comment]
Thank you for the report. 

We have added this item to our backlog.

**Comment by kran** [comment]
@jhen1422 today I see another issue, value of "url component" is encoded. maybe it should keep the original value ?

**Comment by jhen1422** [comment]
Thank you.

We have added this information to the ticket.

**Comment by kran** [comment]
@jhen1422 issues above all are my fault. I do the encoding.
