### ISSUE TITLE
Library not accessible via bower as a bower component

### ISSUE THREAD

**Issue by Csini** [formio/formio.js#89]
`C:\ent>bower search formiojs`
`No results.`

missing
- bower.json bower-main-files (!!)
- build folder (?) (there ist a `require('./build/utils')` in dist folder)

npm is building the dependencies, but bower not, also in dist folder should contain only the ES5 transpiled builded ready-to-use code

**Comment by Csini** [comment]
can you please publish this library to bower?

**Comment by travist** [comment]
I am willing to do this, but I am curious what you get out of bower that you do not get with ```npm```. Historically we used bower in combination with wiredep, but this library would never need that. Also, some of the dependencies of this library also do not support bower (like signature-pad). I think that bower is going away but would like to hear from you your thoughts.

**Comment by Csini** [comment]
I would like to use and customize (simplify) your ng-form-builder. It has formio.js as an npm dependency. I have to work with a strict company framework, which has a strict gulp build process, based on, that all the dependencies are bower components, and in npm we only have the "build tools" as devDependencies like gulp, bower, ... Our system is not prepared for dependencies in npm :(

**Comment by Csini** [comment]
the main problem is with the dependencies from formiojs
for example: `lodash`
I have it in my spa as a bower dependency -> it makes versioning problems if I have it in npm and bower tooo
that's why I would like to have all the dependencies only in bower

**Comment by Csini** [comment]
I only need via bower a 

- transpiled (ES5) 
- derequired
- ready-to-use 
- distribution version 

from your formio.js source

**Comment by travist** [comment]
This is now accessible with bower. thanks.

**Comment by Csini** [comment]
THANK YOU!
