### ISSUE TITLE
ability to set any component as viewAsHtml

### ISSUE THREAD

**Issue by imadbakir** [formio/formio.js#894]
Hello, 
The code seems to be able to handle this feature, I already did implement that using API properties, but I had to override baseComponent. 

 key: "viewOnly",
      get: function get() {
        return this.component.properties && this.component.properties.readOnly === 'true' || this.options.readOnly && this.options.viewAsHtml;
      }

do you think it is a good idea to add this as an option to form builder?

**Comment by randallknutson** [comment]
Can you help explain the use case of this? The viewAsHtml option is to render a submission as an html as a whole. Are you suggesting adding this as an option on the component level to only render some components on a form as viewAsHtml?

**Comment by imadbakir** [comment]
@randallknutson Yes. That is what I meant, why? 
Example: 

a Form that on submission read, makes an external api call to fetch data to display in the form. (eg: Bank Information according to userId of submission creator).
it's for display only I don't want the user to change those, They should not have any inputs or validation, they may also render faster. 

Another example:

Let's assume a form progression where user A sees form A and provides input. 
while user B Sees form B which has its very own inputs, as well as Including input from user A using nested forms.

user B is not concerned about data user A did input. They are there to show user A's input. 
NestedForm Component can benefit from that too.

**Comment by randallknutson** [comment]
I can mostly see the use case. I think we'd be open to adding this to our platform. It would essentially be a "View as html" option in the form builder correct? How would we distinguish for when to show the form and when not to?

You can also use the content component to render form data as html. For example, within the content component you can use {{data.myfield}} to render other form fields. This may work to display the data.

**Comment by imadbakir** [comment]
@randallknutson Exactly, an option in the builder. 

Yes Content Component might come handy for some cases. 
Yet The power of including a whole form is to avoid repetition I guess.

Currently I have my own implementation for setting nested forms as ViewAsHtml which is working well, but it takes place at runtime where i have to change the object of the form before it is rendered hence unnecessary Deep Searching Webform Object.

I believe it might be helpful if it was an option since the code for it is almost already there.

**Comment by randallknutson** [comment]
This makes sense. It sounds like it would be a setting on the nested form component. We can add it to our backlog but it would be a while till we look at it unless someone wants to contribute the change or sponsor us making the change.
