### ISSUE TITLE
Print of form.io data as PDF using C# object in custom format

### ISSUE THREAD

**Issue by anveshsdd** [formio/formio.js#898]
I want to create print view for Form.io. I want to break json format of form into C# object to manage design of pdf by itself.

Please help to save save json format data of form.io into C# object with layout

**Comment by randallknutson** [comment]
You can get the submission object by either listening to the submit event, getting the submission from the server API or getting the form.submission from the form object. Once you have the json, you can do whatever you want with it.

**Comment by anveshsdd** [comment]
Yes, i am getting the json for submitted data. But json doesn't have same structure to convert into a same class structure. Thats why i am not able to use the json data for show in print.

Please help me to create class structure to convert json into class object format

**Comment by randallknutson** [comment]
I'm not entirely sure what you mean by the class structure. You can also get the form definition json and use it to build out the form and show it. You can also do something called viewAsHtml which will render just the data without fields. http://formio.github.io/formio.js/app/examples/htmlview.html

**Comment by nyirongojr** [comment]
@jhen1422, how did you manage to render the form data as pdf?

**Comment by thanhvietnguyen255** [comment]
Hi @anveshsdd, have you solved the issue yet?

Could you give examples on how to export a form/form submission to PDF file?
Or convert to HTML so from that HTML I can export to PDF file.
