### ISSUE TITLE
could not find Default values of datagrid component 

### ISSUE THREAD

**Issue by bagana89** [formio/formio.js#903]
since v3.10, i could not find default values in data tab of datagrid. how it be given in latest versions?

**Comment by randallknutson** [comment]
Is this across all components or just the number component?

**Comment by randallknutson** [comment]
Do you have any advanced conditional logic on the datagrid? It appears the default value may be evaluating conditional logic when it shouldn't be that causes the default value to hide itself.

**Comment by jhen1422** [comment]
This issue has been resolved
