### ISSUE TITLE
Data Grid Default value hide when add Advanced Conditions

### ISSUE THREAD

**Issue by AnasHijazi** [formio/formio.js#904]
when add custom Advanced Conditions to datagride the default value hide  Please see the the below video to view case : 

https://drive.google.com/file/d/1C_gAjfRSNdGpo5IymRPtcaT2KSX1Q4XU/view?usp=sharing

**Comment by bagana89** [comment]
we have a such things when we use v3.10 and higher version, So now using v3.9 that has default values

**Comment by NajwaKhaled** [comment]
@bagana89  that's true @travist  Please your advice

**Comment by AnasHijazi** [comment]
@bagana89  yes true , @travist  please your advice

**Comment by jhen1422** [comment]
This issue has been resolved on formio.js version 3.23.0 or later
