### ISSUE TITLE
Text Area issue

### ISSUE THREAD

**Issue by Bdestasio33** [formio/formio.js#907]
textarea component is set to true and not working correctly. I get an error in the console with this displayed as soon as I drag the field on.

> An error occured within custom function for wysiwyg TypeError: Cannot read property 'wysiwygDefault' of undefined
    at customDefaultValue (formio.full.min.js:117)
    at Object.v [as evaluate] (formio.full.min.js:9)
    at e.value (formio.full.min.js:49)
    at e.get (formio.full.min.js:9)
    at get (<anonymous>)
    at e.get (formio.full.min.js:117)
    at e.value (formio.full.min.js:9)
    at e.value (formio.full.min.js:9)
    at e.value (formio.full.min.js:9)
    at e.value (formio.full.min.js:9)

**Comment by randallknutson** [comment]
Can you clarify what you mean by textarea ciomponent is set to true?

**Comment by Bdestasio33** [comment]
The TextArea component where you can define what specific components you want to allow people using the formBuilder to use. But no matter what I get an error with the TextArea even if I'm just using the default template.

**Comment by travist** [comment]
So you mean you are disabling the Text Area using the ```ignore: true``` flag?

**Comment by Bdestasio33** [comment]
Using the Base components it fails as well with Formio.js
Here is a photo showing what happens when I drag a Text Area onto the builder.
[https://photos.app.goo.gl/fSvp1wYiy9tLSKcB8](url)

**Comment by Bdestasio33** [comment]
Here is how I render the form to make things more clear also.
`Formio.builder(document.getElementById('builder'), {},{}).then(function(form) {
        // Prevent the submission from going to the form.io server.
        form.nosubmit = true;
    
        // Triggered when they click the submit button.
        form.on('submit', function(submission) {
          console.log(submission.data);
          alert('Submission sent to custom endpoint. See developer console.');
          return fetch('http://httpbin.org/post', {
              body: JSON.stringify(submission.data),
              headers: {
                'content-type': 'application/json'
              },
              method: 'POST',
              mode: 'cors',
            })
            .then(response => {
              form.emit('submitDone', submission)
              response.json()
            })
        });
      });
  }`

**Comment by travist** [comment]
So, I am a little confused since you are showing a bug in the image that shows an issue with the builder, but your code you sent above is only executed when you are rendering this form. Are you seeing this error in both the builder and renderer or one or the other? We will add this to our list, but it may not make it to our priority list, so if you want to take a crack at putting some ```if``` protection around this variable in the renderer and submit a pull request, we would be grateful.
