### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by rmckeel** [formio/formio.js#91]
Using the sample code:
```
import {Formio} from 'formiojs';
...

        let formio = new Formio('https://examples.form.io/example');
        formio.loadForm((form) => {
            console.log(form);
            formio.saveSubmission({data: {
                firstName: 'Joe',
                lastName: 'Smith',
                email: 'joe@example.com'
            }}).then((submission) => {
                console.log(submission);
            });
        });
```

I receive the JS error:
`formiojs_1.Formio is not a constructor`

This also happens trying to use new `FormioForm(document.getElementById('my-div'));`

Any thoughts on why this basic 'hello world' script to load a sample form would not work inside another (otherwise working) ES6 app?

Thanks!

  Ryan

**Comment by rmckeel** [comment]
Another potentially useful piece of information here.  When I go into Chrome debugger just before `let formio = ...` and run a similar command from console `var formio = ...`, it seems the object is created properly with no visible JS errors.

I'm learning ES6, but it seems to me something about running that code in ES6 breaks, while running in console works as expected.

**Comment by travist** [comment]
Try this instead...

```
import Formio from 'formiojs';
```

Without the ```{}```

**Comment by rmckeel** [comment]
Thanks @travist.  I have already switched gears enough to another approach, so can't verify that.  However, I did also try a few working variants of what you recommended (for posterity).

Thanks!

```
import * as Formio from 'formiojs';
import * as FormioForm from 'formiojs/build/formio.form.js';
```

**Comment by rmckeel** [comment]
FWIW, I have another area I'm trying `import Formio from 'formiojs'`.  I get this:
```
main.ts:12 EXCEPTION: Error in :0:0 caused by: formiojs_1.default is not a constructor
main.ts:12 ORIGINAL EXCEPTION: formiojs_1.default is not a constructor
```

```
    ngOnInit(): void {
        this.src = 'https://example.formio.com/my-custom-form';

        let formApi = new Formio( this.src );
        formApi.loadForm().then(function (form) {
            console.log(form);
        });
    }
```

When I switch to `import * as Formio from 'formiojs';`, the code works as expected against the API and loads and logs the form.
