### ISSUE TITLE
Datagrid component getting too slow when rows count goes above 2000

### ISSUE THREAD

**Issue by suriyakumarcs** [formio/formio.js#911]
I have been using form.io for my project.it's a bigger one. the problem is when data grid rows go above 2000 suddenly forms getting slow when I perform delete and even add action. I go through your code and I found that total rows are removed and added again in the add and delete actions. But I thought that "we can do this removal using id attribute of the element which is needed to be deleted" but you guys have removed all the elements and render it again.  I don't know why are you doing like this. it will be more useful if you give some solution to this. Thanks.

**Comment by travist** [comment]
2000 seems excessive to me. I think the better solution (which is also been asked for by the community) is to figure out a "pagination" for data grid inputs so that you don't need to render so many rows within a single page. To be honest, I think being able to achieve 2000 rows is pretty darn good.

**Comment by travist** [comment]
That could possibly be improved. We will add this to our backlog, but to be honest, we have more important bugs we are currently looking at. If you want this particular one fixed you can either A.) dig into the code and fix the problem since it is open source. B.) Pay us to expedite it.

**Comment by abhishek0196** [comment]
> 2000 seems excessive to me. I think the better solution (which is also been asked for by the community) is to figure out a "pagination" for data grid inputs so that you don't need to render so many rows within a single page. To be honest, I think being able to achieve 2000 rows is pretty darn good.

Hello @travist,  can you please any reference link to implement pagination?
