### ISSUE TITLE
Trying Different edit component UI

### ISSUE THREAD

**Issue by 152hq** [formio/formio.js#914]
Hi,

Just giving a shot at a different component edit UI, is there a way to mock saveButton click actions on every time there is a change in the change component model? 

Thanks

**Comment by randallknutson** [comment]
There is a change event that fires on each component change. You can use this instead of mocking the save button press. Then you can grab the form definition from the builder and do whatever you want with it.

**Comment by randallknutson** [comment]
Here is an example of combining all the events into one change event: 
https://github.com/formio/react-formio/blob/master/src/components/FormBuilder.js#L40-L47

**Comment by 152hq** [comment]
Thanks, it worked !
