### ISSUE TITLE
How to bind value to a component in customDefaultValue or CacluclateValue with API response

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#915]
Hi,
I am trying to assign API response to **value**. But it is not reflecting. 
APIresponse.then( function(res){ value = res.data; }); 

What I understood is you are evaluating anonymous function of customDefault. How to set async function response to value field?

**Comment by randallknutson** [comment]
javascript functions only run synchronously, not async like with an api request. You can do this outside of the component though like this: http://formio.github.io/formio.js/app/examples/externalload.html

**Comment by sriram275** [comment]
That's good thing for single form but I wanted as generic  because api call may vary from component to component and form to form ( and api call should be able enter while building form). So if I write any custom js (api call) inside calculateDefaultValue it should fill the value of that component on rendering the form with out any code changes on form change.

Is it doable? 

Is there any way wait async call(api) and return value for that component? Or is there any exposed util method to set the value of component? then we can use that in async call promise block.
Like below:
api.then(function(response){
util.setComponentValue(componentKey, response.data);
}):

Thanks.

**Comment by randallknutson** [comment]
We currently don't have the functionality to asynchronously set a calculated value in a component. We can either look at extending our platform to add it or you can use custom properties to set the external url, use the method I mentioned the first time and basically create a generic way of doing that outside the form with the custom properties.

**Comment by sriram275** [comment]
Randall,

Did little debug and found a work around to set value in async with using instance like below
instance.setValue(apiResponse);

It's working in all cases with out any issue. Do you recommend this?

Thanks.

**Comment by travist** [comment]
This looks good to me. Do you mind sharing the full code snippet in this issue so it could help other people? Closing this issue in the meantime.
