### ISSUE TITLE
calculateValue and validation together

### ISSUE THREAD

**Issue by moreeshi** [formio/formio.js#916]
How to have calculateValue property of form and validate function(which is set for ValidateOn:blur) to be executed together. Actually when the calculateValue property gets calculated programatically and gets set as value, then validate function is not called. It gets called only when Validation is set on blur.

**Comment by travist** [comment]
You could manually trigger validation on change.

```
Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/example').then((form) => {
  form.on('change', () => form.checkValidity());
});
```

I haven't actually tried this, but it should manually trigger the validation.

**Comment by moreeshi** [comment]
Thanks for your reply.

Does the form object have checkValidity function?

**Comment by moreeshi** [comment]
Can you tell me if this would fire validity for all the controls?

**Comment by travist** [comment]
Yes it would fire for all controls.

**Comment by AnasHijazi** [comment]
@travist  please your advice : 
https://github.com/formio/formio.js/issues/930
