### ISSUE TITLE
Wiki example for "Form Renderer" does not work as intended

### ISSUE THREAD

**Issue by rmckeel** [formio/formio.js#92]
Hey Travis and team,

Thought I'd mention this [example](https://github.com/formio/formio.js/wiki/Form-Renderer#wizard-rendering) returns this:

`Uncaught ReferenceError: FormioWizard is not defined
    at window.onload`

Additionally, it returns a 404 on the [CSS](https://unpkg.com/formiojs@2.3.4/dist/formio.wizard.min.css)

I would have changed it in the wiki, but I'm not sure what to change it to.  Seems there is another way to call the form wizard now from the form.min.js code other than 'FormioWizard'?

Thanks!

**Comment by criticalmaas** [comment]
I had good success with this change when using Formio Wizard. Notice that the CSS needs to be `formio.form.min.css` and `new FormioWizard` is used instead of `new FormioForm` since it is a wizard and not a form


```
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://unpkg.com/formiojs@2.3.4/dist/formio.form.min.css'>
<script src='https://unpkg.com/formiojs@2.3.4/dist/formio.form.min.js'></script>
<script type='text/javascript'>
  window.onload = function() {
     var form = new FormioWizard(document.getElementById('formio'));
     form.src = 'https://example.form.io/example';
  };
</script>
```
