### ISSUE TITLE
Toggle command Palette?

### ISSUE THREAD

**Issue by Bdestasio33** [formio/formio.js#927]
I was wondering if there was any way to throw a button on the screen for the form builder that could toggle show/hide of the command palette? I want to be able to see how the form will actually look with a full screen in the renderer without swapping over to it and pasting code? Is this a possibility?

**Comment by travist** [comment]
The sidebar in the builder is available in the builder instance which you can hide and show manually. Something like this maybe....

```js
var formBuilder = null;
var sidebarvisible = true;
var button = document.getElementById('hide-sidebar');
button.addEventListener('click', function() {
  sidebarvisible = !sidebarvisible;
  formBuilder.showElement(formBuilder.sideBarElement, sidebarvisible);
});

Formio.builder(document.getElementById('formio'), {components: []}).then((builder) => {
  formBuilder = builder;
});

```

**Comment by Bdestasio33** [comment]
Hides the sidebar perfectly but the Form doesn't resize to the screen like I wanted.

**Comment by randallknutson** [comment]
The form area has the following classes, "col-xs-8 col-sm-9 col-md-10". When you hide the sidebar, change the classes on the form area to "col-xs-12 col-sm-12 col-md-12". Then change them back to the original when displaying the sidebar.
