### ISSUE TITLE
Event is emitted before form itself updated

### ISSUE THREAD

**Issue by krixerx** [formio/formio.js#931]
Code in WebformBuilder.js:

 ```
 deleteComponent(component) {
    if (!component.parent) {
      return;
    }
    let remove = true;
    if (component.type === 'components' && component.getComponents().length > 0) {
      const message = 'Removing this component will also remove all of its children. Are you sure you want to do this?';
      remove = window.confirm(this.t(message));
    }
    if (remove) {
      this.emit('deleteComponent', component);
      component.parent.removeComponentById(component.id);
      this.form = this.schema;
    }
    return remove;
  }
```
Why the line
 this.emit('deleteComponent', component);
is before form schema update?
It throws the event with old schema state.

Thanks!
Erki

**Comment by randallknutson** [comment]
We'll fix this in a new build. I'm working on getting the form builder events in more functional shape and will move the emit to after the removal.

**Comment by DA37708** [comment]
I'm only getting the saveCompnent event using the following:
    
Formio.builder(document.getElementById('builder'), formioForm, formioOptions ).then(function(builder) {
      builder.on
      ('saveComponent', function() { console.log('delete ********************************' }), 
      ('deleteComponent', function() { console.log('delete ********************************')}),  
      ('updateComponent', function() { console.log('update ********************************')}),  
      ('editComponent', function() { console.log('edit ********************************')}),  
      ('cancelComponent', function() { console.log('cancel ********************************')})  
    });
  },

Is there documentation available on what events are triggered by the builder? If so could yo pont me in the right direction (url)?

**Comment by jhen1422** [comment]
This should be a resolved on our 4x renderer. 

Please feel free to open a new issue if the problem persists

**Comment by neonterra** [comment]
deleteComponent has been replaced with removeComponent event.
