### ISSUE TITLE
How to over write validation messages?

### ISSUE THREAD

**Issue by akhilesh-sharma168** [formio/formio.js#933]
![homeerror](https://user-images.githubusercontent.com/45589364/51160278-448fd400-18b3-11e9-92ed-b262fcc38f5d.png)
Hi Team, 
Is there a way to modify the validation error messages in form io of home phone field

**Comment by akhilesh-sharma168** [comment]
@travist 
Can you just give me an example of this custom ().
That will be a great help .

**Comment by Bdestasio33** [comment]
How about inserting your own custom message from outside the builder? Such as 
Builder.error("Custom Message") or something similar?
