### ISSUE TITLE
WebpackError: ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by dyukov** [formio/formio.js#934]
Error while bundling using Webpack
`WebpackError: ReferenceError: Headers is not defined`

Caused by the following line in Formio.js
`Formio.Headers = Headers;`

**Comment by randallknutson** [comment]
Looks like you are embedding this on node.js. We currently have a few places where we are looking for global variables like Headers which can cause problems. You can add browser-env library for now and we will work on removing those global dependencies that cause issues in non browser environments.

**Comment by dyukov** [comment]
I am using Formio in Gatsby, so essentially, it is a browser environment. 
However, while building static HTML files I get the upmentioned error.
There are possible workarounds offered in the Internet.

However, because this seems to be common for Gatsby, NextJs and Server Side Rendering in general, I'd like to propose more general solution.

Something like:
` if (typeof Headers !== 'undefined') {...`
or 
` Formio.Headers = Headers || {}`

**Comment by randallknutson** [comment]
Yeah. We do need to make this change so we can work properly without Headers. Can you make a pull request?
