### ISSUE TITLE
How to update form data after click event custom “Button” control?

### ISSUE THREAD

**Issue by gladkiy** [formio/formio.js#941]
I created new custom control like button and after every click I need to update value of this control

```
import ButtonComponent from 'formiojs/components/button/Button.js';

export default class DynamicButton extends ButtonComponent {
  ...
  build() {
    this.dataValue = '';
    ...
    this.addEventListener(this.buttonElement, 'click', (event) => {
      this.dataValue = "some data";
    });
  }
  ...
}
```

So, value is updated and if I print `console.log(this.data)` here it's also updated, but it doesn't trigger "change" event on form and when I submit form then data for this control doesn't exist.

What I need to execute to trigger "change" event on form and populate data of this control to form?

**Comment by randallknutson** [comment]
You need to call this.triggerChange() after setting the value.

**Comment by gladkiy** [comment]
I did the following:

```
build() {
    this.dataValue = '';
    ...
    this.addEventListener(this.buttonElement, 'click', (event) => {
      this.dataValue = "some data";
      this.triggerChange();
      console.log(this.dataValue);
      console.log(this.data);
    });
    ...
  }
```

But `this.data = { "userName": "some data" }` and `this.dataValue = undefined`.
Why does this happen?

I also have:

```
getValue() {
  return this.dataValue;
}

set dataValue(value) {
  super.dataValue = value;
}
```

**Comment by randallknutson** [comment]
Can you check out this.setValue() and see if that works better? By setting this.dataValue directly you may be bypassing some of the update functionality that is causing the issues.

**Comment by gladkiy** [comment]
Unfortunatelly, it didn't help. I tried:
```
this.setValue("some data");
this.triggerChange();
```

**Comment by travist** [comment]
You are extending the Button component which I believe implements the setValue which sets the value as a boolean. You will need to override the ```setValue``` method and even ```getValue``` method in your component so that you are able to set string values.
