### ISSUE TITLE
Using fontawesome 5

### ISSUE THREAD

**Issue by DavidPLamas** [formio/formio.js#943]
Hi,

I've tried finding documentation for this, but unfortunately I couldn't find it. 
I'm using this library in a angular application (using your angular library) and I'm using fontawesome 5 in my application. 
The form builder component contains some icons which the name has been changed in fontawesome 5, more precisely, the icon "fa fa-remove" has been renamed to "fas fa-times". 
There are also icons inside the modal for editing a component that do not render because of similar problems.
Has this issue problem ever been reached out? Is the upgrade to fontawesome 5 a planned changed from you?

Thank you,
David Lamas.

**Comment by randallknutson** [comment]
Our 4.x branch will support custom icon sets. It is currently in alpha though so it is not entirely stable. 

Here is an example of what this will look like:
https://github.com/formio/formio.js/blob/4.x/src/templates/bootstrap/iconClass.js

**Comment by meljunediaz** [comment]
That's a broken link right there.

**Comment by travist** [comment]
It has been pushed to master branch.

https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/iconClass.js
