### ISSUE TITLE
disableOnInvalid is not working for button component

### ISSUE THREAD

**Issue by sriram275** [formio/formio.js#951]
I set checkbox for disableOnInvalid , So I am expecting the submit button should be disabled if the form is invalid( means if there is any required field not filled). But it is enabling always and once after I click it is showing me error instead have to disable the click if form is invalid.

**Comment by travist** [comment]
We are aware of this issue and will have a developer look into it asap. Thanks.

**Comment by travist** [comment]
Should be fixed in latest build.
