### ISSUE TITLE
Select URL Value Property not saving

### ISSUE THREAD

**Issue by ProteanHub** [formio/formio.js#953]
When adding/editing a template, the valueProperty of a select component using a URL is not saved. I can click the setting icon to immediately pull it back up after entering the valueProperty, and the field is blank. This is using v3.12.2 of Formio.full.min.js

**Comment by travist** [comment]
Thanks, we will file a bug internally and take a look.

**Comment by DavidPLamas** [comment]
Are there any updates on this issue ?

**Comment by travist** [comment]
We did make some changes within the 3.13.x version of this renderer around how the valuePropery is handled within Select components. These changes may have resolved this issue. Will you test your issue against the latest version and verify if it is working for you?

**Comment by travist** [comment]
Ok thanks.  we will add this to our backlog as a bug.

**Comment by ProteanHub** [comment]
@travist Out of curiosity, I noticed you mentioned in another issue about paying to prioritize a particular bug. Can you contact me about this one specifically with pricing and timeline if that is an option?

Either way, thanks for all you do with FormIO. It is an amazing product and we love it.

**Comment by travist** [comment]
Thanks for that @ProteanHub!  Denise will be reaching out to you soon regarding how to get some of your items expedited.

**Comment by denisekay** [comment]
Hi John, Happy to help.  Please email me at denise@form.io

**Comment by ProteanHub** [comment]
Hi @denisekay waiting for a reply to my email. Did you receive it?

**Comment by denisekay** [comment]
Sorry, I did not find an email.  What is yours and will contact you right away

**Comment by Romancha** [comment]
same issue

**Comment by travist** [comment]
This is fixed in https://github.com/formio/formio.js/pull/1028. Will be in the next build.

**Comment by ProteanHub** [comment]
Thanks @travist !

**Comment by travist** [comment]
Ok, **v3.15.4** has been released with this fixed. Thank you @ProteanHub for the expedition of this resolution!
