### ISSUE TITLE
Mismatch on integer default values

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#954]
When using a select box with a data URL, if you have a record looks as follows

|id|name|
|1|brighton|
|2|london|

Value Property = id
Item Template = <span>{{ item.name }}</span>
Default Value = 1

When viewing the rendered form it displays the int value rather than matching it against the data source and displaying the name. If however id is a UUID then the form renders correctly.

**Comment by travist** [comment]
It may be converting these values to numbers. We will add this to our backlog.
