### ISSUE TITLE
Many nested forms a lot of request 

### ISSUE THREAD

**Issue by pkochubey** [formio/formio.js#965]
Hi.
I have one root form and around 20 nested forms (they showing by condition dropdown list from root form). When I try render root form, in same time I catch 20 request for download nested form. Looks good but on 2-4 seconds I have UI freeze, not so good. Possible set rule, download and show nested form only if there is condition for showing this nested form?

**Comment by randallknutson** [comment]
The nested forms should only load if they are visible. Another option is in the root form you can append ?full=true to the form url and it will load subforms all at once.

**Comment by pkochubey** [comment]
?full=true this is good idea. but in any way, very big form\form with a lot of nested form has UI performance issue, I guess because JS worked as one thread application, and render formio affected on client application.

**Comment by pkochubey** [comment]
> The nested forms should only load if they are visible.
And by fact this is not worked, if you create one dropdown list and one nested form with simple condition. Nested form will loaded in any way, excluding state dropdown list

**Comment by pkochubey** [comment]
On this big example you can see pure formio implimentation http://jsfiddle.net/f78ekL20/ when at first load root form, you catch a lot of request for nested form

**Comment by pkochubey** [comment]
Yes this looks like a bug, because in old version 2.30.0 this is works as expected "The nested forms should only load if they are visible" but in new releases this is behavior not supported

**Comment by travist** [comment]
I would agree this is a bug. The forms should only load when they are needed. We will add this to our planning for resolution.

**Comment by pkochubey** [comment]
710fd2fdfbebbcb56470c2bd971a3e30cf5211c5 this can be related. In this commit was conditional logic, by this commit fixed recursion

**Comment by pkochubey** [comment]
@travist What do you think about estimation for for this issue? How long time to take fixed this issue?

**Comment by travist** [comment]
It would probably take 4 hours to complete and we will add it to our planning. Depending on other development items we have in our backlog it could take a couple of weeks to resolve. The other option is to have an expedited fix which puts this on the top of our list and we will look at it immediately, but you have to pay for our time to fix it. Let me know if you want to go down that route.

**Comment by pkochubey** [comment]
> it could take a couple of weeks to resolve

Good, I will wait.

**Comment by jhen1422** [comment]
This item should be resolved with the latest formio.js
