### ISSUE TITLE
Calendar Widget

### ISSUE THREAD

**Issue by Bdestasio33** [formio/formio.js#971]
For the Calendar Widget, if I edit the widget settings it just flashes and goes back to what it was before? In the developers console it says infinite loop detected. I haven't found any questions on this yet and wondered if I was the only one. Curious if the CDN was kept up to date at these sources?

https://unpkg.com/formiojs@latest/dist/formio.builder.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
https://unpkg.com/formiojs@latest/dist/formio.full.min.js

Thanks for any help in advance.

**Comment by travist** [comment]
Please try this with the latest release. This may have been resolved with the 3.13.1 version. Let us know otherwise.

**Comment by travist** [comment]
This is a known issue that is already added to our backlog. Let us know if you need to expedite it for a fee.
