### ISSUE TITLE
this.choices.containerOuter.setAttribute is not a function

### ISSUE THREAD

**Issue by KyooMario** [formio/formio.js#973]
Hello Support,

I am building the latest github with webpack.
All seems fine but when testing I get the following error message: this.choices.containerOuter.setAttribute is not a function

I have used the following code: var _choices = _interopRequireDefault(require("choices.js")); in the Select.js and Tags.js

And I have installed: npm i choices.js

Because I read some issues about this subject can you confirm I did it the right way? And if so what might be the cause of the error message.

Kind regards,
Mario

**Comment by travist** [comment]
Please ensure that you have not installed the latest version of choices.js (4.x). This renderer is not yet compatible with that version.

**Comment by travist** [comment]
The workaround is to make sure you are using choices.js (3.x) and not 4.x. This error makes me believe you are using the wrong version.

**Comment by KyooMario** [comment]
I did what you proposed. Thanks.
