### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by keyurmeandev** [formio/formio.js#978]
I'm getting below error when trying to render the form.

Uncaught (in promise) TypeError: Cannot read property 'key' of undefined

**Comment by travist** [comment]
Please provide a JSFiddle of this rendered form.

**Comment by keyurmeandev** [comment]
@travist 

It has been solved. It was due to below statement in form.io builder. 
"customDefaultValue":"value = new date();"
