### ISSUE TITLE
Form is submitted after click on "builder-group-button"

### ISSUE THREAD

**Issue by gladkiy** [formio/formio.js#981]
I mean "Basic Components", "Advanced", "Layout", "Data" buttons. It occurs because these buttons have no `type` attribute and by default `type="submit"`

**Comment by travist** [comment]
Yeah, that is bad. I see you created a pull request so we will fix this asap. Thanks!

**Comment by psmarsch** [comment]
+1 from my side. 
I can approve that adding type="button" fixes the issue.

@travist When will this be merged?

**Comment by gladkiy** [comment]
It's already merged here:
https://github.com/formio/formio.js/pull/980/commits/0901ea1801beec666df969bf66a07a7b85dbb65b

**Comment by psmarsch** [comment]
I'm on formiojs@4.0.0-beta.46 and it's not part of it.
Could this please also be integrated in that version? Thank you.

**Comment by gladkiy** [comment]
I'm not a developer of formio. I use v3 and it works fine. I think it would be good if you create separate issue for v4 beta.

**Comment by psmarsch** [comment]
The question was rather towards @travist ... :)
Can we reuse this issue for 4.0.0 or should I open a new one?

**Comment by gladkiy** [comment]
I'm not sure, but I would open new one :)
