### ISSUE TITLE
in the template not have translations

### ISSUE THREAD

**Issue by Spiritvoin** [formio/formio.js#982]
https://github.com/formio/formio.js/blob/4d534da2f8516f9efaa6b0920a330f81132f2917/src/components/tree/Tree.js#L223

There are no quotes in this line and no translations in the template 
"{{ node.collapsed ? instance.t('Expand') : instance.t('Collapse') }}"
Problem with translations also in edit grid

**Comment by travist** [comment]
We will add this to planning.

**Comment by travist** [comment]
We just decided that this is a low priority and we would like for the community to contribute a fix for this particular item.

**Comment by darabi** [comment]
In the mean time, with the addition of templates, the `Tree` component is fully internationalised. This issue can be closed.
