### ISSUE TITLE
require one of multiple radio boxes

### ISSUE THREAD

**Issue by pixie79** [formio/formio.js#983]
Hi,

We have a datagrid, which inside each row has a radio boxes with a true/false requirement. 

I need to allow only one of the radio boxes within the datagrid to be true. I guess this is probably a custom verification rule but i am not sure how. Unfortunately we also do not know how many rows there will be in advance.

Any ideas ?

Thanks

Mark

**Comment by travist** [comment]
You can add a "hidden" field outside of the datagrid. Within this component, you can write a custom validation rule like so.

```js
var valid = false;
for (var i; i < data.grid.length; i++) {
  valid |= data.grid[i].radioCheck
}
return valid.
```
