### ISSUE TITLE
Default value "0" for "number" component is not working

### ISSUE THREAD

**Issue by DavidPLamas** [formio/formio.js#997]
When using https://formio.github.io/angular-demo/#/forms/builder, if you try to add a "number" component with **0** as the default value, the input never gets the default value. It works with other values but never works with **0**.

I've also tested with your latest version (_3.13.6_). and it is also not working. Is this an intended behavior ?

**Comment by jhen1422** [comment]
Hello @DavidPLamas 

The default value when using '0' for the Number component is working fine on our end. You can also in the builder JSON the default value is being set correctly. You can try using the latest version of formio.js 3.13.9 / 3.13.10 to see if this fixes the issue for you.

**Comment by DavidPLamas** [comment]
Hi,
Sorry for the late reply. I've just tested this in https://formio.github.io/formio.js/app/builder and it is still not working. I've just dragged the component "Number", inserted **0** as the "Default value" and it does not appear in the input. It is inserted in the JSON but is not rendered on the form.

**Comment by wag110894** [comment]
Hello @DavidPLamas 

Thank you for notifying us of this issue. We were able to reproduce this issue and have created a ticket (FOR-2104). We will discuss level of priority for this item in our next planning meeting.

**Comment by travist** [comment]
This is now fixed in **3.16.2**

**Comment by shahzadiiui2015** [comment]
How to get and set default value of textArea as CKEditor in angular any idea.

**Comment by nikolozi2001** [comment]
I still have this issue :D
